### ISSUE TITLE
请给出开发规划

### ISSUE THREAD

**Issue by tidatida** [guanzhi/GmSSL#10]
关老师，您好。

首先OPENSSL扩展国密支持算法在国内安全产业具有非常重要的意义，感谢您及您的团队所做的工作。近期看到该项目获奖信息，在这里表示祝贺。

同时我们看到国密SSL距离扩展OPENSSL算法的目标，距离实用性还有一定的差距。 例如无法生成证书、使用证书。

关老师曾提到为支持SM系列算法，更改了EC算法,估计是导致GMSSL 无法兼容的主要原因。

希望能够给出开发规划、设计文档（开发者共享），便于所有关注者对GMSSL有更好的了解，同时也便于开源开发者参与进来，共同完成GMSSL的开发工作。

**Comment by tidatida** [comment]
编译为动态库，替换系统的libssl.so   libcrypto.so ， 经验证，原有的使用openssl的程序无法正常工作。我在定位问题原因后，重新开一个ISSUE. 

对OPENSSL 的扩展工作的确任务艰巨，与关老师的团队共勉。

**Comment by guanzhi** [comment]
开发规划如下：

1. 算法实现：SM2签名/加密/密钥交换、SM3、SM4及ECB/CBC/CFB/OFB/CTR/GCM/XTS/WRAP模式。这部分的开发目前完成度最高。
2. EVP API：使EVP API支持SM2、SM3和SM4。这部分基本完成，还需要完整的测试以便涵盖所有的EVP API。
3. 支持X509证书和PKCS7、PKCS8、PKCS12等PKI标准，工作量不多但是依赖于第2步的完成。
4. gmssl命令行，依赖于2、3步。
5. 支持国密硬件，通过ENGINE机制，支持提供国密SKF接口标准的国产密码硬件。
6. 支持国密SSL的部分CipherSuites。

近期的开发主要关注1、2、5。

**Comment by guanzhi** [comment]
关于设计文档：

1. 由于GmSSL新增的算法模块和在OpenSSL上的修改完全延续了OpenSSL的风格和逻辑，因此GmSSL基本上没有自己的设计。例如OpenSSL通过ENGINE机制支持密码硬件，GmSSL就通过ENGINE机制支持国产密码硬件；OpenSSL通过统一接口支持SSL/TLS/DTLS等不同协议，GmSSL也试图在这一框架上实现对国密SSL的支持。
2. GmSSL的接口说明会逐渐通过Wiki文档和各个模块的测试代码给出示例。
2. GmSSL新增代码通过OPENSSL_NO_SM2/SM3/SM4/GMSSL/SKF等宏进行包装，也可以通过diff和OpenSSL的源码进行对比。

**Comment by James1256** [comment]
国密算法 sm2/sm3/sm4是否已应用到SSL通讯协议中？如果把Gmssl组成C/S模式时，是否可以SM系统算法进行数据的加解密

**Comment by guanzhi** [comment]
SSL的功能还在开发中，进度请参考上面的开发规划。

**Comment by houruixiang** [comment]
请问libcrypto库在哪里，编译不成功
