### ISSUE TITLE
通过支持国密的浏览器访问不通的问题

### ISSUE THREAD

**Issue by bochs9** [guanzhi/GmSSL#100]
通过支持国密的浏览器访问，抓包发现速龙浏览器支持0xE011加密套件，通过之前沟通知道gmssl接口也实现了0xE011加密套件，但在握手阶段，serverhello之后，浏览器直接就fin掉了，是两者实现标准不同，还是其他可能的原因呢。

**Comment by sslvpn007** [comment]
楼主，你是在什么平台上测的win？mac？linux？

**Comment by bochs9** [comment]
@sslvpn007 win下的，速龙和360国密专版
