### ISSUE TITLE
升级OpenSSL或提供独立的GMSSL库可与标准OpenSSL共同使用

### ISSUE THREAD

**Issue by josephusmv** [guanzhi/GmSSL#1001]
**Is your feature request related to a problem? Please describe.**
在移动设备上，通常只能考虑使用静态库，而是用静态库经常会与OpenSSL冲突。客户应用通常存在其他安全组件对OpenSSL算法的依赖，同时因为OpenSSL的版本已经远超当前GMSSL所以依赖的版本，有时无法使用当前的GMSSL完全替代OpenSSL。而因为前述的静态库原因，直接导致符号冲突。

所以升级依赖的OpenSSL是十分必要的，或者能够提供不暴露OpenSSL接口的库，仅提供GMSSL接口的暴露，或提供宏选项或编译配置完全禁止编译OpenSSL需要暴露的接口。

**Describe the solution you'd like**
选项一：合并OpenSSL最新的功能到GMSSL库上，此库已经落后OpenSSL至少两年；
选项二：Fork库，包含裁剪后的代码，仅提供GMSSL的功能；
选项三：提供编译选项，除GM相关算法外，隐藏其他接口或不编译其他算法接口，包括通用的SSL等算法。

**Describe alternatives you've considered**
见前述三个选项。

**Additional context**
GMSSL目前推广受阻碍的一个重要原因是当其与OpenSSL共同存在时，即不足以完全替代最新的OpenSSL库，又无法避免与OpenSSL共同链接时候的冲突问题，请考虑此FQ。

**Comment by Mojicode** [comment]
> **Is your feature request related to a problem? Please describe.**
> 在移动设备上，通常只能考虑使用静态库，而是用静态库经常会与OpenSSL冲突。客户应用通常存在其他安全组件对OpenSSL算法的依赖，同时因为OpenSSL的版本已经远超当前GMSSL所以依赖的版本，有时无法使用当前的GMSSL完全替代OpenSSL。而因为前述的静态库原因，直接导致符号冲突。
> 
> 所以升级依赖的OpenSSL是十分必要的，或者能够提供不暴露OpenSSL接口的库，仅提供GMSSL接口的暴露，或提供宏选项或编译配置完全禁止编译OpenSSL需要暴露的接口。
> 
> **Describe the solution you'd like**
> 选项一：合并OpenSSL最新的功能到GMSSL库上，此库已经落后OpenSSL至少两年；
> 选项二：Fork库，包含裁剪后的代码，仅提供GMSSL的功能；
> 选项三：提供编译选项，除GM相关算法外，隐藏其他接口或不编译其他算法接口，包括通用的SSL等算法。
> 
> **Describe alternatives you've considered**
> 见前述三个选项。
> 
> **Additional context**
> GMSSL目前推广受阻碍的一个重要原因是当其与OpenSSL共同存在时，即不足以完全替代最新的OpenSSL库，又无法避免与OpenSSL共同链接时候的冲突问题，请考虑此FQ。

遇到同样的问题，和项目使用的openssl冲突。。。
