### ISSUE TITLE
gmssl基于rsa加密算法的https通信

### ISSUE THREAD

**Issue by ww1999520** [guanzhi/GmSSL#1003]
请问一下各位大佬,现在有哪位可以使用gmssl进行rsa加密算法的https通信么?
大致应用场景如下:
目前我们系统使用了国密SM2算法的证书,证书颁发过程中使用了gmssl库,
证书颁发过程中,我们会向省级CA中心发送证书签发请求(我们本身没有签发证书的资质),但是省级CA中心使用的是基于RSA加密算法的https协议;然后就出问题了,我以基于gmssl的库来进行https通信时,SSL_connect会失败;请问一下有哪位兄弟有过类似的应用场景么?客户端是下面这种用法,我使用s_client进行测试的时候会报:Verify return code: 20 (unable to get local issuer certificate)
SSL_CTX_set_verify(__ssl_ctx,SSL_VERIFY_NONE,NULL);

**Comment by davidkhala** [comment]
RSA跟国密的部分独立的吧
这个问题是否属于openSSL的范畴？

**Comment by ww1999520** [comment]
> RSA跟国密的部分独立的吧
> 这个问题是否属于openSSL的范畴？

是的,属于openssl的部分,我们上级证书中心用的给予rsa数字证书的https通信,在linux下时gmssl和openssl会冲突,谢谢哈,我单独做了一个localhost的子服务来处理这个事情
