### ISSUE TITLE
关于sm2_do_verify报错

### ISSUE THREAD

**Issue by licongxing** [guanzhi/GmSSL#1009]
使用 https://www.gmssl.cn/gmssl/index.jsp?go=nginxdown 上面的已经编译好的Nginx，配置好后，使用360浏览器和国密浏览器均能正常访问，使用s_client命令行访问却报错。
命令行：
gmssl.exe s_client -connect 192.168.75.100:443 -gmtls -cipher SM2-WITH-SMS4-SM3 -CAfile demo1.sm2.trust.pem

报错信息如下，请问是什么原因呢？
crypto\sm2\sm2_sign.c 504: sm2_do_verify
0:error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl\statem\statem_gmtls.c:897:
write:errno=0

New, (NONE), Cipher is (NONE)
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : GMTLSv1.1
    Cipher    : 0000
    Session-ID: 4AE471D1D20C850BF240EB3D75CE21B54F14388B510A44A30D32DF72CFE24B92
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1598424445
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no

**Comment by reclock** [comment]
https://download.csdn.net/download/qq_40153886/12550021?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522159832454219195264510621%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=159832454219195264510621&biz_id=1&utm_medium=distribute.pc_search_result.none-task-download-2~all~first_rank_ecpm_v3~pc_rank_v3-1-12550021.pc_ecpm_v3_pc_rank_v3&utm_term=statem_gmtls&spm=1018.2118.3001.4187  下载 statem_gmtls.c 替换这个重新编译，再试试，我也遇到了这个

**Comment by lucas-sss** [comment]
> https://download.csdn.net/download/qq_40153886/12550021?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522159832454219195264510621%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=159832454219195264510621&biz_id=1&utm_medium=distribute.pc_search_result.none-task-download-2~all~first_rank_ecpm_v3~pc_rank_v3-1-12550021.pc_ecpm_v3_pc_rank_v3&utm_term=statem_gmtls&spm=1018.2118.3001.4187 下载 statem_gmtls.c 替换这个重新编译，再试试，我也遇到了这个

这边下载了可以用吗？
