### ISSUE TITLE
请问 gmssl 怎么生成 SM2 临时公钥 双证书 csr 怎么生成

### ISSUE THREAD

**Issue by cz3pearl** [guanzhi/GmSSL#1011]
没有找到作者的联系方式... 只能来这里了

双证书PKI的一个流程:
1,订户生成签名密钥对
2,发送csr给RA/CA 含一个公钥、和临时公钥
3,RA/CA向KMC请求加密密钥对, KMC返回私钥 使用临时公钥加密
4,签发两张证书, 同加密密钥一起交给订户

想请教下  上面流程所述的csr怎样通过gmssl生成
我在网络上没有找到相关资料.... 万分感谢!

**Comment by zhengshundong01** [comment]
大佬，我也遇到类似的问题，咱可以共通下资源，我现在遇到这个问题：

https://github.com/guanzhi/GmSSL/issues/1013

**Comment by zhenyuwei** [comment]
https://github.com/jntass/TASSL-1.1.1b/tree/master/tassl_demo/cert
https://github.com/guanzhi/GmSSL/tree/master/apps/gmca
这两个应该都可以
