### ISSUE TITLE
360浏览器访问nginx握手失败-双向https-已解决

### ISSUE THREAD

**Issue by reclock** [guanzhi/GmSSL#1012]
使用gmssl编译了nginx，也使用939的文件替换了，单向访问可以了，但是使用双向https，抓包看还是报解密失败，这个怎么解决啊？

**Comment by reclock** [comment]
使用s_client双向https，怎么使用ECC_SM4_SM3，模拟360的建立过程？指定不了这个算法啊

**Comment by zhenyuwei** [comment]
https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述

**Comment by reclock** [comment]
> https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述
> -cipher cipherlist
> this allows the cipher list sent by the client to be modified. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See the ciphers command for more information.

目前使用GMTLS参数，使用s_sever   s_client命令行是可以了，走的协议也是SM2-WITN-SMS4-SM3，其实就是国密标准定义的ECC_SM4_SM3.。但是360浏览器还是访问失败
![image](https://user-images.githubusercontent.com/23696606/92898853-e7b23b80-f450-11ea-987f-a818b74f58c8.png)
Certificate Verify之后就报错。
看到这个问题的希望能给点意见，目前在使用s_server 启动服务，使用360访问，找问题出在哪里

**Comment by zhenyuwei** [comment]
> > https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述
> > -cipher cipherlist
> > this allows the cipher list sent by the client to be modified. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See the ciphers command for more information.
> 
> 目前使用GMTLS参数，使用s_sever s_client命令行是可以了，走的协议也是SM2-WITN-SMS4-SM3，其实就是国密标准定义的ECC_SM4_SM3.。但是360浏览器还是访问失败
> ![image](https://user-images.githubusercontent.com/23696606/92898853-e7b23b80-f450-11ea-987f-a818b74f58c8.png)
> Certificate Verify之后就报错。
> 看到这个问题的希望能给点意见，目前在使用s_server 启动服务，使用360访问，找问题出在哪里

我记得gmssl在做Z值计算的时候，取得id来自证书内容，不是1234567812345678，这块你改了吗？

**Comment by reclock** [comment]
> > > https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述
> > > -cipher cipherlist
> > > this allows the cipher list sent by the client to be modified. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See the ciphers command for more information.
> > 
> > 
> > 目前使用GMTLS参数，使用s_sever s_client命令行是可以了，走的协议也是SM2-WITN-SMS4-SM3，其实就是国密标准定义的ECC_SM4_SM3.。但是360浏览器还是访问失败
> > ![image](https://user-images.githubusercontent.com/23696606/92898853-e7b23b80-f450-11ea-987f-a818b74f58c8.png)
> > Certificate Verify之后就报错。
> > 看到这个问题的希望能给点意见，目前在使用s_server 启动服务，使用360访问，找问题出在哪里
> 
> 我记得gmssl在做Z值计算的时候，取得id来自证书内容，不是1234567812345678，这块你改了吗？

我看这个bug已经修改了，直接clone就可以了

**Comment by zhenyuwei** [comment]
> > > > https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述
> > > > -cipher cipherlist
> > > > this allows the cipher list sent by the client to be modified. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See the ciphers command for more information.
> > > 
> > > 
> > > 目前使用GMTLS参数，使用s_sever s_client命令行是可以了，走的协议也是SM2-WITN-SMS4-SM3，其实就是国密标准定义的ECC_SM4_SM3.。但是360浏览器还是访问失败
> > > ![image](https://user-images.githubusercontent.com/23696606/92898853-e7b23b80-f450-11ea-987f-a818b74f58c8.png)
> > > Certificate Verify之后就报错。
> > > 看到这个问题的希望能给点意见，目前在使用s_server 启动服务，使用360访问，找问题出在哪里
> > 
> > 
> > 我记得gmssl在做Z值计算的时候，取得id来自证书内容，不是1234567812345678，这块你改了吗？
> 
> 我看这个bug已经修改了，直接clone就可以了 #970

留个联系方式，我抽时间帮你看一下。

**Comment by reclock** [comment]
> > > > > https://www.openssl.org/docs/man1.1.0/man1/openssl-s_client.html 里面有个-cipher的描述
> > > > > -cipher cipherlist
> > > > > this allows the cipher list sent by the client to be modified. Although the server determines which cipher suite is used it should take the first supported cipher in the list sent by the client. See the ciphers command for more information.
> > > > 
> > > > 
> > > > 目前使用GMTLS参数，使用s_sever s_client命令行是可以了，走的协议也是SM2-WITN-SMS4-SM3，其实就是国密标准定义的ECC_SM4_SM3.。但是360浏览器还是访问失败
> > > > ![image](https://user-images.githubusercontent.com/23696606/92898853-e7b23b80-f450-11ea-987f-a818b74f58c8.png)
> > > > Certificate Verify之后就报错。
> > > > 看到这个问题的希望能给点意见，目前在使用s_server 启动服务，使用360访问，找问题出在哪里
> > > 
> > > 
> > > 我记得gmssl在做Z值计算的时候，取得id来自证书内容，不是1234567812345678，这块你改了吗？
> > 
> > 
> > 我看这个bug已经修改了，直接clone就可以了 #970
> 
> 留个联系方式，我抽时间帮你看一下。

我的QQ : 1091984657

**Comment by reclock** [comment]
问题找到，已解决，十分感谢楼上的帮助。解决办法如下：
**statem_srvr.c** 文件 ，**tls_process_cert_verify** 函数，增加对Z值的处理，修改后的函数如下,，黑体部分为修改代码


`MSG_PROCESS_RETURN tls_process_cert_verify(SSL *s, PACKET *pkt)
{
    EVP_PKEY *pkey = NULL;
    const unsigned char *sig, *data;
#ifndef OPENSSL_NO_GOST
    unsigned char *gost_data = NULL;
#endif
    int al, ret = MSG_PROCESS_ERROR;
    int type = 0, j;
    **unsigned int len, dgstlen;**
    X509 *peer;
    const EVP_MD *md = NULL;
    long hdatalen = 0;
    void *hdata;
    **unsigned char z[EVP_MAX_MD_SIZE],dgst[SM3_DIGEST_LENGTH];
    size_t zlen;**

    EVP_MD_CTX *mctx = EVP_MD_CTX_new();

    if (mctx == NULL) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_MALLOC_FAILURE);
        al = SSL_AD_INTERNAL_ERROR;
        goto f_err;
    }

    peer = s->session->peer;
    pkey = X509_get0_pubkey(peer);
    type = X509_certificate_type(peer, pkey);

    if (!(type & EVP_PKT_SIGN)) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY,
               SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE);
        al = SSL_AD_ILLEGAL_PARAMETER;
        goto f_err;
    }

    /* Check for broken implementations of GOST ciphersuites */
    /*
     * If key is GOST and n is exactly 64, it is bare signature without
     * length field (CryptoPro implementations at least till CSP 4.0)
     */
#ifndef OPENSSL_NO_GOST
    if (PACKET_remaining(pkt) == 64
        && EVP_PKEY_id(pkey) == NID_id_GostR3410_2001) {
        len = 64;
    } else
#endif
    {
        if (SSL_USE_SIGALGS(s)) {
            int rv;

            if (!PACKET_get_bytes(pkt, &sig, 2)) {
                al = SSL_AD_DECODE_ERROR;
                goto f_err;
            }
            rv = tls12_check_peer_sigalg(&md, s, sig, pkey);
            if (rv == -1) {
                al = SSL_AD_INTERNAL_ERROR;
                goto f_err;
            } else if (rv == 0) {
                al = SSL_AD_DECODE_ERROR;
                goto f_err;
            }
#ifdef SSL_DEBUG
            fprintf(stderr, "USING TLSv1.2 HASH %s\n", EVP_MD_name(md));
#endif
        } else {
            /* Use default digest for this key type */
            int idx = ssl_cert_type(NULL, pkey);
            if (idx >= 0)
                md = s->s3->tmp.md[idx];
            if (md == NULL) {
                al = SSL_AD_INTERNAL_ERROR;
                goto f_err;
            }
        }

        if (!PACKET_get_net_2(pkt, &len)) {
            SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_LENGTH_MISMATCH);
            al = SSL_AD_DECODE_ERROR;
            goto f_err;
        }
    }
    j = EVP_PKEY_size(pkey);
    if (((int)len > j) || ((int)PACKET_remaining(pkt) > j)
        || (PACKET_remaining(pkt) == 0)) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_WRONG_SIGNATURE_SIZE);
        al = SSL_AD_DECODE_ERROR;
        goto f_err;
    }
    if (!PACKET_get_bytes(pkt, &data, len)) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_LENGTH_MISMATCH);
        al = SSL_AD_DECODE_ERROR;
        goto f_err;
    }

    hdatalen = BIO_get_mem_data(s->s3->handshake_buffer, &hdata);
    if (hdatalen <= 0) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
        al = SSL_AD_INTERNAL_ERROR;
        goto f_err;
    }
#ifdef SSL_DEBUG
    fprintf(stderr, "Using client verify alg %s\n", EVP_MD_name(md));
#endif

**#ifndef OPENSSL_NO_GMTLS**
    **if (SSL_IS_GMTLS(s)){
		dgstlen = sizeof(dgst);
		zlen = SM3_DIGEST_LENGTH;
        if (!SM2_compute_id_digest(EVP_sm3(), SM2_DEFAULT_ID, SM2_DEFAULT_ID_LENGTH, z, &zlen,
	    	EVP_PKEY_get0_EC_KEY(pkey))) {
			SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
	    	goto f_err;
		}
		if(!EVP_Digest(hdata, hdatalen, dgst, &dgstlen, EVP_sm3(), NULL)) {
	    	SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
	    	goto f_err;
		}
    }
#endif
    if (!EVP_VerifyInit_ex(mctx, md, NULL)){
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
        al = SSL_AD_INTERNAL_ERROR;
        goto f_err;
    }
#ifndef OPENSSL_NO_GMTLS
    if (SSL_IS_GMTLS(s)){
		if(!EVP_VerifyUpdate(mctx, z, zlen)
		  ||!EVP_VerifyUpdate(mctx, dgst, dgstlen)) {
	            SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
		    	al = SSL_AD_INTERNAL_ERROR;
	            goto f_err;
		}
    }
    else
#endif
    {
        if(!EVP_VerifyUpdate(mctx, hdata, hdatalen)) {
            SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
            al = SSL_AD_INTERNAL_ERROR;
            goto f_err;
        }
    }** 

#ifndef OPENSSL_NO_GOST
    {
        int pktype = EVP_PKEY_id(pkey);
        if (pktype == NID_id_GostR3410_2001
            || pktype == NID_id_GostR3410_2012_256
            || pktype == NID_id_GostR3410_2012_512) {
            if ((gost_data = OPENSSL_malloc(len)) == NULL) {
                SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_MALLOC_FAILURE);
                al = SSL_AD_INTERNAL_ERROR;
                goto f_err;
            }
            BUF_reverse(gost_data, data, len);
            data = gost_data;
        }
    }
#endif

    if (s->version == SSL3_VERSION
        && !EVP_MD_CTX_ctrl(mctx, EVP_CTRL_SSL3_MASTER_SECRET,
                            s->session->master_key_length,
                            s->session->master_key)) {
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
        al = SSL_AD_INTERNAL_ERROR;
        goto f_err;
    }

    if (EVP_VerifyFinal(mctx, data, len, pkey) <= 0) {
        al = SSL_AD_DECRYPT_ERROR;
        SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_BAD_SIGNATURE);
        goto f_err;
    }

    ret = MSG_PROCESS_CONTINUE_PROCESSING;
    if (0) {
 f_err:
        ssl3_send_alert(s, SSL3_AL_FATAL, al);
        ossl_statem_set_error(s);
    }
    BIO_free(s->s3->handshake_buffer);
    s->s3->handshake_buffer = NULL;
    EVP_MD_CTX_free(mctx);
#ifndef OPENSSL_NO_GOST
    OPENSSL_free(gost_data);
#endif
    return ret;
}`

**Comment by Chadlucc** [comment]
> 问题找到，已解决，十分感谢楼上的帮助。解决办法如下：
> 
> **statem_srvr.c** 文件 ，**tls_process_cert_verify** 函数，增加对Z值的处理，修改后的函数如下,，黑体部分为修改代码
> 
> 
> 
> 
> 
> `MSG_PROCESS_RETURN tls_process_cert_verify(SSL *s, PACKET *pkt)
> 
> {
> 
>     EVP_PKEY *pkey = NULL;
> 
>     const unsigned char *sig, *data;
> 
> #ifndef OPENSSL_NO_GOST
> 
>     unsigned char *gost_data = NULL;
> 
> #endif
> 
>     int al, ret = MSG_PROCESS_ERROR;
> 
>     int type = 0, j;
> 
>     **unsigned int len, dgstlen;**
> 
>     X509 *peer;
> 
>     const EVP_MD *md = NULL;
> 
>     long hdatalen = 0;
> 
>     void *hdata;
> 
>     **unsigned char z[EVP_MAX_MD_SIZE],dgst[SM3_DIGEST_LENGTH];
> 
>     size_t zlen;**
> 
> 
> 
>     EVP_MD_CTX *mctx = EVP_MD_CTX_new();
> 
> 
> 
>     if (mctx == NULL) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_MALLOC_FAILURE);
> 
>         al = SSL_AD_INTERNAL_ERROR;
> 
>         goto f_err;
> 
>     }
> 
> 
> 
>     peer = s->session->peer;
> 
>     pkey = X509_get0_pubkey(peer);
> 
>     type = X509_certificate_type(peer, pkey);
> 
> 
> 
>     if (!(type & EVP_PKT_SIGN)) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY,
> 
>                SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE);
> 
>         al = SSL_AD_ILLEGAL_PARAMETER;
> 
>         goto f_err;
> 
>     }
> 
> 
> 
>     /* Check for broken implementations of GOST ciphersuites */
> 
>     /*
> 
>      * If key is GOST and n is exactly 64, it is bare signature without
> 
>      * length field (CryptoPro implementations at least till CSP 4.0)
> 
>      */
> 
> #ifndef OPENSSL_NO_GOST
> 
>     if (PACKET_remaining(pkt) == 64
> 
>         && EVP_PKEY_id(pkey) == NID_id_GostR3410_2001) {
> 
>         len = 64;
> 
>     } else
> 
> #endif
> 
>     {
> 
>         if (SSL_USE_SIGALGS(s)) {
> 
>             int rv;
> 
> 
> 
>             if (!PACKET_get_bytes(pkt, &sig, 2)) {
> 
>                 al = SSL_AD_DECODE_ERROR;
> 
>                 goto f_err;
> 
>             }
> 
>             rv = tls12_check_peer_sigalg(&md, s, sig, pkey);
> 
>             if (rv == -1) {
> 
>                 al = SSL_AD_INTERNAL_ERROR;
> 
>                 goto f_err;
> 
>             } else if (rv == 0) {
> 
>                 al = SSL_AD_DECODE_ERROR;
> 
>                 goto f_err;
> 
>             }
> 
> #ifdef SSL_DEBUG
> 
>             fprintf(stderr, "USING TLSv1.2 HASH %s\n", EVP_MD_name(md));
> 
> #endif
> 
>         } else {
> 
>             /* Use default digest for this key type */
> 
>             int idx = ssl_cert_type(NULL, pkey);
> 
>             if (idx >= 0)
> 
>                 md = s->s3->tmp.md[idx];
> 
>             if (md == NULL) {
> 
>                 al = SSL_AD_INTERNAL_ERROR;
> 
>                 goto f_err;
> 
>             }
> 
>         }
> 
> 
> 
>         if (!PACKET_get_net_2(pkt, &len)) {
> 
>             SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_LENGTH_MISMATCH);
> 
>             al = SSL_AD_DECODE_ERROR;
> 
>             goto f_err;
> 
>         }
> 
>     }
> 
>     j = EVP_PKEY_size(pkey);
> 
>     if (((int)len > j) || ((int)PACKET_remaining(pkt) > j)
> 
>         || (PACKET_remaining(pkt) == 0)) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_WRONG_SIGNATURE_SIZE);
> 
>         al = SSL_AD_DECODE_ERROR;
> 
>         goto f_err;
> 
>     }
> 
>     if (!PACKET_get_bytes(pkt, &data, len)) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_LENGTH_MISMATCH);
> 
>         al = SSL_AD_DECODE_ERROR;
> 
>         goto f_err;
> 
>     }
> 
> 
> 
>     hdatalen = BIO_get_mem_data(s->s3->handshake_buffer, &hdata);
> 
>     if (hdatalen <= 0) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
> 
>         al = SSL_AD_INTERNAL_ERROR;
> 
>         goto f_err;
> 
>     }
> 
> #ifdef SSL_DEBUG
> 
>     fprintf(stderr, "Using client verify alg %s\n", EVP_MD_name(md));
> 
> #endif
> 
> 
> 
> **#ifndef OPENSSL_NO_GMTLS**
> 
>     **if (SSL_IS_GMTLS(s)){
> 
> 		dgstlen = sizeof(dgst);
> 
> 		zlen = SM3_DIGEST_LENGTH;
> 
>         if (!SM2_compute_id_digest(EVP_sm3(), SM2_DEFAULT_ID, SM2_DEFAULT_ID_LENGTH, z, &zlen,
> 
> 	    	EVP_PKEY_get0_EC_KEY(pkey))) {
> 
> 			SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
> 
> 	    	goto f_err;
> 
> 		}
> 
> 		if(!EVP_Digest(hdata, hdatalen, dgst, &dgstlen, EVP_sm3(), NULL)) {
> 
> 	    	SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_INTERNAL_ERROR);
> 
> 	    	goto f_err;
> 
> 		}
> 
>     }
> 
> #endif
> 
>     if (!EVP_VerifyInit_ex(mctx, md, NULL)){
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
> 
>         al = SSL_AD_INTERNAL_ERROR;
> 
>         goto f_err;
> 
>     }
> 
> #ifndef OPENSSL_NO_GMTLS
> 
>     if (SSL_IS_GMTLS(s)){
> 
> 		if(!EVP_VerifyUpdate(mctx, z, zlen)
> 
> 		  ||!EVP_VerifyUpdate(mctx, dgst, dgstlen)) {
> 
> 	            SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
> 
> 		    	al = SSL_AD_INTERNAL_ERROR;
> 
> 	            goto f_err;
> 
> 		}
> 
>     }
> 
>     else
> 
> #endif
> 
>     {
> 
>         if(!EVP_VerifyUpdate(mctx, hdata, hdatalen)) {
> 
>             SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
> 
>             al = SSL_AD_INTERNAL_ERROR;
> 
>             goto f_err;
> 
>         }
> 
>     }** 
> 
> 
> 
> #ifndef OPENSSL_NO_GOST
> 
>     {
> 
>         int pktype = EVP_PKEY_id(pkey);
> 
>         if (pktype == NID_id_GostR3410_2001
> 
>             || pktype == NID_id_GostR3410_2012_256
> 
>             || pktype == NID_id_GostR3410_2012_512) {
> 
>             if ((gost_data = OPENSSL_malloc(len)) == NULL) {
> 
>                 SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_MALLOC_FAILURE);
> 
>                 al = SSL_AD_INTERNAL_ERROR;
> 
>                 goto f_err;
> 
>             }
> 
>             BUF_reverse(gost_data, data, len);
> 
>             data = gost_data;
> 
>         }
> 
>     }
> 
> #endif
> 
> 
> 
>     if (s->version == SSL3_VERSION
> 
>         && !EVP_MD_CTX_ctrl(mctx, EVP_CTRL_SSL3_MASTER_SECRET,
> 
>                             s->session->master_key_length,
> 
>                             s->session->master_key)) {
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, ERR_R_EVP_LIB);
> 
>         al = SSL_AD_INTERNAL_ERROR;
> 
>         goto f_err;
> 
>     }
> 
> 
> 
>     if (EVP_VerifyFinal(mctx, data, len, pkey) <= 0) {
> 
>         al = SSL_AD_DECRYPT_ERROR;
> 
>         SSLerr(SSL_F_TLS_PROCESS_CERT_VERIFY, SSL_R_BAD_SIGNATURE);
> 
>         goto f_err;
> 
>     }
> 
> 
> 
>     ret = MSG_PROCESS_CONTINUE_PROCESSING;
> 
>     if (0) {
> 
>  f_err:
> 
>         ssl3_send_alert(s, SSL3_AL_FATAL, al);
> 
>         ossl_statem_set_error(s);
> 
>     }
> 
>     BIO_free(s->s3->handshake_buffer);
> 
>     s->s3->handshake_buffer = NULL;
> 
>     EVP_MD_CTX_free(mctx);
> 
> #ifndef OPENSSL_NO_GOST
> 
>     OPENSSL_free(gost_data);
> 
> #endif
> 
>     return ret;
> 
> }`
> 
> 
> 
> 
> 
> 

这是个bug还是证书的问题

**Comment by Chadlucc** [comment]
应该不是这个问题，还是因为客户端证书签名用错了造成的，改完就可以了
