### ISSUE TITLE
GMSSL编译运行Java Wrapper踩坑记录

### ISSUE THREAD

**Issue by bluefin1986** [guanzhi/GmSSL#1014]
在Mac上，按以下官方文档的攻略是可以编译通过的，但是在Linux上加上java就编译失败!

首先，按官方攻略把Mac流程跑通

//官方攻略BEGIN

编译Java接口
由于GmSSL编译脚本还不能实现在所有操作系统上自动编译Java接口代码，因此编译脚本中默认没有启用Java接口的编译。 开启方式如下： 在源代码根目录下找到Configure文件，找到
```
$config{dirs} = [ "crypto", "ssl", "engines", "apps", "util", "tools", "fuzz", "test" ];
```
这一行，并将其修改为
```
$config{dirs} = [ "crypto", "ssl", "engines", "apps", "util", "tools", "fuzz", "test", "java" ];
```
重新编译，则可以自动编译java目录下的C代码和Java代码，并生成libgmssljni动态库和GmSSL.class。 这个模块的编译目前在Mac下可以测试通过。
在Linux和Mac下的编译和安装
```
./config
make
make test
sudo make install
```

//官方攻略End

在Mac上，编译完成后能产生两个dylib，一个是libgmssljni.dylib, 另一个是libcrypto.dylib 
![image](https://user-images.githubusercontent.com/506159/92890878-17aa1080-f44a-11ea-8ff2-ad44566a40ee.png)

接着，把java目录里头的GmSSL.java 拿出来，切记切记，项目中要保持原文件中给出的package包路径org.gmssl建目录

![image](https://user-images.githubusercontent.com/506159/92890999-2db7d100-f44a-11ea-9753-67f97f9c3ccf.png)

在GmSSL.java底部的loadLibrary，指向的就是libgmssljni.dylib (Mac OS)， 如果是Linux则是libgmssljni.so
```
static {
    System.loadLibrary("gmssljni");
}
```

接着运行GmSSL中的main方法，注意，要在VMOption中添加java.library.path为上述libgmssljni.dylib和libcrypto.dylib所在目录，例如：
```
-Djava.library.path=/Users/matt/Documents/securityworkspace/GmSSL
```
得到正确的运行结果
![image](https://user-images.githubusercontent.com/506159/92891117-458f5500-f44a-11ea-994b-fbded2df6392.png)

在Linux下的成功编译经验：

1、保持Configure文件中$config{dirs}原来的设置，不要添加java目录，完成make install，会在GmSSL目录内得到libcrypto.so
![image](https://user-images.githubusercontent.com/506159/92891166-4fb15380-f44a-11ea-88cb-62a05a6a617c.png)

2、接着进入java目录， 参考build.sh按下面的命令进行编译，build.sh中-L /path/to/gmssl/lib 其实就是gmssl根目录，加了lib有点误导人

```
gcc -shared -fPIC -Wall -I./jni -I /home/java/gmssl/include -L /home/java/gmssl GmSSL.c -lcrypto -o libgmssljni.so
```

编译成功，得到libgmssljni.so， 例如：
![image](https://user-images.githubusercontent.com/506159/92891236-60fa6000-f44a-11ea-8b01-100fe84c5e9d.png)

3、把步骤1中编译出的libcrypto.so 拷到当前java目录，当前目录一共要有3个东西
![image](https://user-images.githubusercontent.com/506159/92891257-65bf1400-f44a-11ea-9b76-beeff4a192eb.png)

4、最后，编译GmSSL.java 并运行
```
mkdir -p org/gmssl
cp GmSSL.java org/gmssl
javac org/gmssl/GmSSL.java

java -Djava.library.path=/home/java/GmSSL/java -classpath /home/java/GmSSL/java org.gmssl.GmSSL
```
![image](https://user-images.githubusercontent.com/506159/92891333-73749980-f44a-11ea-88c7-c0e45b4fcdae.png)

现在说下我是怎么发现这个坑的，一开始好不容易编译通过了，直接运行，报错
![image](https://user-images.githubusercontent.com/506159/92891386-7d969800-f44a-11ea-9aae-641d9651f743.png)

看着就像方法名不对，按master的最新GmSSL.java源码，和官网过期GmSSL Wrapper示例源码都不对，苦寻无果，只好把libgmssljni.so 用IDA-Pro反编译了一下，看到写死的类路径的时候，一度想要砸键盘
![image](https://user-images.githubusercontent.com/506159/92891415-82f3e280-f44a-11ea-96a1-661d6e5bb7cf.png)

**Comment by zhengshundong01** [comment]
大佬，我也在弄国密java相关，可否加个QQ，微信啥的，一起研究下

**Comment by reclock** [comment]
> 大佬，我也在弄国密java相关，可否加个QQ，微信啥的，一起研究下，我这里有个群，大家可以一起研究下

可否加我一个QQ 1092984657，最近也在弄GMSSL的东西

**Comment by zengminghua** [comment]
给蜀黍点个赞 @bluefin1986

**Comment by bluefin1986** [comment]
> 大佬，我也在弄国密java相关，可否加个QQ，微信啥的，一起研究下，我这里有个群，大家可以一起研究下

留个微信我加您？

**Comment by zhengshundong01** [comment]
我微信号：TZ_Breaker

**Comment by zhengshundong01** [comment]
> > 大佬，我也在弄国密java相关，可否加个QQ，微信啥的，一起研究下，我这里有个群，大家可以一起研究下
> 
> 可否加我一个QQ 1092984657，最近也在弄GMSSL的东西

兄弟也留个微信吧，都统一微信群吧

**Comment by reclock** [comment]
> > > 大佬，我也在弄国密java相关，可否加个QQ，微信啥的，一起研究下，我这里有个群，大家可以一起研究下
> > 
> > 
> > 可否加我一个QQ 1092984657，最近也在弄GMSSL的东西
> 
> 兄弟也留个微信吧，都统一微信群吧

我微信 zheng19901091

**Comment by wzlu** [comment]
我微信 wenzel 求加群

**Comment by Akuma1361** [comment]
大佬,我只能说牛逼!

**Comment by Akuma1361** [comment]
![image](https://user-images.githubusercontent.com/49395580/103344644-233d4800-4aca-11eb-959b-5e14e0fd1b1e.png)
大佬,我的运行java后,是这个结果是对的吗?

**Comment by xcw233** [comment]
Windows 编译jni https://blog.csdn.net/qq_43549604/article/details/121969046

**Comment by lb0820ynn** [comment]
> 

微信号搜不到了呀，现在还能进群么
