### ISSUE TITLE
通过其他开源国密实现生成的证书，通过gmssl验证不通过

### ISSUE THREAD

**Issue by victortanjh** [guanzhi/GmSSL#1016]
问题现象：
最近通过tjfoc/gmsm生成了十几组CA和CA签发的user证书（国密证书）。
通过CA证书对user证书验签，其中绝大部分证书对，通过gmssl命令行、tjfoc/gmsm和ZZMarquis/gm验签，都能验签成功。
但其中一组CA和user证书对，通过gmssl命令行验签失败，通过tjfoc/gmsm和ZZMarquis/gm验签成功。

gmssl命令行：gmssl verify -CAfile ca.org1.example.com-cert.pem Admin@org1.example.com-cert.pem 

gmssl验签失败日志：
root@HSH1000057266:/opt/temp/0910# gmssl verify -CAfile ca.org1.example.com-cert.pem Admin@org1.example.com-cert.pem 
crypto/sm2/sm2_sign.c 510: sm2_do_verify
C = test, ST = test, L = test, street = test, postalCode = test, OU = test, CN = Admin@org1.example.com
error 7 at 0 depth lookup: certificate signature failure
error Admin@org1.example.com-cert.pem: verification failed
140070593775424:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:188:

目前已经发现两对证书验签失败了。但生成的大部分证书，验签都是OK的。

问题：gmssl内部是用openssl EVP接口实现的，tjfoc/gmsm和ZZMarquis/gm都是对go语言原生ECDSA改造来支持国密的。
为啥有的证书在几种开源实现上都可以验证通过，低概率有某些证书对，通过gmssl就会验签失败？

**Comment by victortanjh** [comment]
附上被gmssl验签失败的证书（其它开源平台可以验签通过）：
CA：
-----BEGIN CERTIFICATE-----
MIICwjCCAmigAwIBAgIQNxGnB/OXHrhLxauFpjnGCzAKBggqgRzPVQGDdTCBkzEN
MAsGA1UEBhMEdGVzdDENMAsGA1UECBMEdGVzdDENMAsGA1UEBxMEdGVzdDENMAsG
A1UECRMEdGVzdDENMAsGA1UEERMEdGVzdDEZMBcGA1UEChMQb3JnMS5leGFtcGxl
LmNvbTENMAsGA1UECxMEdGVzdDEcMBoGA1UEAxMTY2Eub3JnMS5leGFtcGxlLmNv
bTAeFw0yMDA5MDQwMjE5MDBaFw0zMDA5MDIwMjE5MDBaMIGTMQ0wCwYDVQQGEwR0
ZXN0MQ0wCwYDVQQIEwR0ZXN0MQ0wCwYDVQQHEwR0ZXN0MQ0wCwYDVQQJEwR0ZXN0
MQ0wCwYDVQQREwR0ZXN0MRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMQ0wCwYD
VQQLEwR0ZXN0MRwwGgYDVQQDExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZI
zj0CAQYIKoEcz1UBgi0DQgAE31DYQt/+6IVretZDJRHXLbrc6BR+Gzcha31rRA0W
E0sACvLXaY/ZGh+26lnET57azv6WzcSmF+Udj0iTWEHCmaOBmzCBmDAOBgNVHQ8B
Af8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB
/wQFMAMBAf8wKQYDVR0OBCIEIJ5jvq5YJxo2NYd2im4/NIJjP/DnBClbzCVShS+l
5EEAMCsGA1UdIwQkMCKAIJ5jvq5YJxo2NYd2im4/NIJjP/DnBClbzCVShS+l5EEA
MAoGCCqBHM9VAYN1A0gAMEUCIQC4PiNbkgK/6jhaNnfd6RnFDfrcLZs4xml0GLcH
OWfE8gIgIonxUkVM2uttZtR1TQIUlcmt/KClctDq59DDL8pT9tg=
-----END CERTIFICATE-----

Admin证书（由CA签发）：
-----BEGIN CERTIFICATE-----
MIICWjCCAgCgAwIBAgIQRT2a5xiY4iSBoDKvSQo+aTAKBggqgRzPVQGDdTCBkzEN
MAsGA1UEBhMEdGVzdDENMAsGA1UECBMEdGVzdDENMAsGA1UEBxMEdGVzdDENMAsG
A1UECRMEdGVzdDENMAsGA1UEERMEdGVzdDEZMBcGA1UEChMQb3JnMS5leGFtcGxl
LmNvbTENMAsGA1UECxMEdGVzdDEcMBoGA1UEAxMTY2Eub3JnMS5leGFtcGxlLmNv
bTAeFw0yMDA5MDQwMjE5MDBaFw0zMDA5MDIwMjE5MDBaMHsxDTALBgNVBAYTBHRl
c3QxDTALBgNVBAgTBHRlc3QxDTALBgNVBAcTBHRlc3QxDTALBgNVBAkTBHRlc3Qx
DTALBgNVBBETBHRlc3QxDTALBgNVBAsTBHRlc3QxHzAdBgNVBAMMFkFkbWluQG9y
ZzEuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAAT+g0oIS8ou
NEidytS667F4LTkG0+9PyWw2m89IhZSgt+cNgG/yTg8is7UFxVDPC4JAUk0E3RDj
rTo0gOoQtH2Co00wSzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADArBgNV
HSMEJDAigCCeY76uWCcaNjWHdopuPzSCYz/w5wQpW8wlUoUvpeRBADAKBggqgRzP
VQGDdQNIADBFAiEAvPFfpRBs8ss5Zur5PGrUa0sbWSekCqM7oSkXEn4rbAACIHx4
kmXvV3OBrTFdHGquNU+psXhHm45i8ysu9JMpeINd
-----END CERTIFICATE-----

**Comment by zhenyuwei** [comment]
你需要知道其它开源工具签名前到底做了哪些操作，你可以把签名前的数据输出来（sign的数据是什么）和这边验签前的数据做对比（verify的数据），单纯的提供证书没办法给你答案。

**Comment by victortanjh** [comment]
> 把Sm2Sign的e和gmssl的SM2_verify参数输出来对比一下吧

这个问题目前找到了原因，但是不确定怎样是符合标准的：

问题原因：在证书生成和验证过程中，需要计算id（1234567812345678）的摘要，计算过程需要用到公钥的X和Y。对于制作证书的程序，X或者Y有时为31位（大部分情况是32位），然后计算摘要时，就以31位来计算摘要，但是gmssl内部，当X或者Y不足32位时，会在前面补0，补成32再使用。
不知道那种用法是标准的？

出问题证书的公钥的Y（31位）：165 224 176 2 234 22 7 166 16 135 30 95 99 101 17 104 161 139 215 231 148 60 13 140 36 147 61 237 237 153 64
在gmssl中，解析得到Y的值（32位，最前面补充了一个0）：0 165 224 176 2 234 22 7 166 16 135 30 95 99 101 17 104 161 139 215 231 148 60 13 140 36 147 61 237 237 153 64

gmssl中这段代码在sm2_id.c中的SM2_get_public_key_data函数内。

不知道gmssl内的做法是否标准？

**Comment by victortanjh** [comment]
因为Y的值不一样，导致id的摘要值不一样，最终导致验签时传入的消息的摘要值不一样，导致验签失败。
也就是每次当X或者Y为31位时，用gmssl验签就会失败
