### ISSUE TITLE
只用-gmtls无法连接

### ISSUE THREAD

**Issue by Kbdman** [guanzhi/GmSSL#1018]
**Describe the bug**
启动server端
./gmssl s_server -gmtls -port 3443 -key skey.pem -cert cert.pem
client连接
./gmssl s_client -connect 127.0.0.1:3443 -gmtls

服务端返回
`
Enter pass phrase for skey.pem:  

Using default temp DH parameters  

[GMTLS_DEBUG] set sm2 signing certificate  

[GMTLS_DEBUG] set sm2 signing private key  

ACCEPT  

ssl_get_algorithm2=b1e2a09008x  

ERROR  

140100516856064:error:141C0044:SSL routines:gmtls_construct_ske_sm2:internal error:ssl/statem/statem_gmtls.c:731:
shutting down SSL  

CONNECTION CLOSED  

ACCEPT  

ssl_get_algorithm2=b1e2a09008x  

ERROR  

140100516856064:error:141C0044:SSL routines:gmtls_construct_ske_sm2:internal error:ssl/statem/statem_gmtls.c:731:
shutting down SSL  

CONNECTION CLOSED  

ACCEPT  
`
**Expected behavior**
期望可以连接成功，商量出可用的ciphersuit

**Environments**
- OS: Linux lih-PC 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by reclock** [comment]
https://github.com/reclock/GmSSL  看我的修改，已经支持-gmtls  也支持360浏览器的访问

**Comment by zhenyuwei** [comment]
dkey和dcert呢？这是单证书模式

**Comment by xuzhaofangxzf** [comment]
> https://github.com/reclock/GmSSL 看我的修改，已经支持-gmtls 也支持360浏览器的访问

请问你的哪个分支是你修改360浏览器可用的，生成证书的方法还是用编译好的gmssl生成的吗
