### ISSUE TITLE
360认可的证书的私钥在哪儿获得

### ISSUE THREAD

**Issue by gujinqiangggs** [guanzhi/GmSSL#102]
@guanzhi 关大，在cert/sm2下我只找到了CFCA相关国密的证书，但是没有看到有私钥，那我要作为server端启动，让360来访问，要怎么获取相应的私钥？我自己签发的证书，360最后一步就提示我，错误描述：服务器证书验证出错，谢谢！ 
#48

**Comment by guanzhi** [comment]
服务器证书的私钥由服务器管理员生成并秘密保存，服务器的证书则需要管理员向某个CA申请，具体过程在网上有很多介绍。
当然管理员也可以自己充当CA发行证书，但是只有浏览器认可的CA发行的证书才能通过浏览器的验证。可以尝试将你的CA证书强制加入到360浏览器的受信任CA列表中（我不知道具体怎么做）。

**Comment by conezxy** [comment]
通过公网上的360浏览器国密版无法做到，其CA列表的维护方式没有公开。
但如果有项目合作上的渠道，应该可以联系360出一个专门的测试版。
