### ISSUE TITLE
通过BouncyCastle 进行sm2签名，在最新的gmssl代码上，验签失败

### ISSUE THREAD

**Issue by victortanjh** [guanzhi/GmSSL#1021]
问题背景：
我们客户端使用java的BouncyCastle库进行签名，服务端使用go通过cgo功能，集成gmssl的EVP接口，进行验签。

最初我们服务端底层集成的libcrypto.so是gmssl的2.4.0版本（大概2018年10月份之前），验签ok。
但是，最近我们对gmssl版本进行了升级，升级成最新代码，验签则会失败，反复验证，都是如此。

java 客户端，BouncyCastle的签名逻辑：
           Signature signature = Signature.getInstance(GMObjectIdentifiers.sm2sign_with_sm3.toString(), new BouncyCastleProvider());
            signature.initSign(privateKey);
            signature.update(message, 0, message.length);
            return signature.sign();

请问有哪位大神遇到过类似问题，指点一二，万分感谢！

**Comment by DWFLZXJ** [comment]
我遇到相同问题了 有解决吗
