### ISSUE TITLE
Ubuntu 20.04 GmSSL编译出错解决

### ISSUE THREAD

**Issue by luojia65** [guanzhi/GmSSL#1023]
遇到的问题：输入`./config`，出现这样的错误：

```
user@machine:/path/to/GmSSL$ ./config
Operating system: x86_64-whatever-linux2
"glob" is not exported by the File::Glob module
Can't continue after import errors at ./Configure line 18.
BEGIN failed--compilation aborted at ./Configure line 18.
"glob" is not exported by the File::Glob module
Can't continue after import errors at ./Configure line 18.
BEGIN failed--compilation aborted at ./Configure line 18.
This system (linux-x86_64) is not supported. See file INSTALL for details.
```

解决方法：https://www.xiaoheidiannao.com/211129.html
有两处要改。Configure文件，和test/build.info文件。改完就可以编译了。

后面用ldconfig就可以解决

**Comment by cb6e310** [comment]
> 遇到的问题：输入`./config`，出现这样的错误：
> 
> ```
> user@machine:/path/to/GmSSL$ ./config
> Operating system: x86_64-whatever-linux2
> "glob" is not exported by the File::Glob module
> Can't continue after import errors at ./Configure line 18.
> BEGIN failed--compilation aborted at ./Configure line 18.
> "glob" is not exported by the File::Glob module
> Can't continue after import errors at ./Configure line 18.
> BEGIN failed--compilation aborted at ./Configure line 18.
> This system (linux-x86_64) is not supported. See file INSTALL for details.
> ```
> 
> 解决方法：https://www.xiaoheidiannao.com/211129.html 有两处要改。Configure文件，和test/build.info文件。改完就可以编译了。
> 
> 后面用ldconfig就可以解决

你好，https://www.xiaoheidiannao.com/211129.html好像打不开了，能不能麻烦您说一下具体的改动情况，respect

**Comment by huangjunchao** [comment]
1、修改test/build.info文件的339行：

   use File::Spec::Functions;
   use File::Basename;
   #use if $^O ne "VMS", 'File::Glob' => qw/glob/;  去掉这行
   use File::Glob ':glob';  增加这行

 

2、修改Configure文件的第18行：

require 5.10.0;
use strict;
use File::Basename;
use File::Spec::Functions qw/:DEFAULT abs2rel rel2abs/;
use File::Path qw/mkpath/;
#use if $^O ne "VMS", 'File::Glob' => qw/glob/;  去掉这行
use File::Glob ':glob';  增加这行
