### ISSUE TITLE
client_key_exchange签名时hash过程前是不是要对一个z digest进行hash

### ISSUE THREAD

**Issue by Kbdman** [guanzhi/GmSSL#1026]
在搞boringssl支持ECC-SM4-SM3,在验证客户端证书的情况下，可以和gmssl通信，但是和tassl无法通信，报处理client_key_exchange时，签名验证失败。调试发现，tassl在验证签名时hash过程中，
1.计算了一个zdigest,EVP_DigestUpdate(ctx,zdigest)
2.进行EVP_DigestUpdata(ctx,原文)
3.解签比对
gmssl中没有1中的计算zdigist,EVP_DigestUpdate的过程。不清楚第一个步骤到底应不应该有，还是说有什么参数来控制。

**Comment by reclock** [comment]
如果服务端有Z值的计算，需要在客户端client_key_exchange 中也接入Z的计算，gmssl中是没有的，所以使用360浏览器作为客户端，gmssl中的s_server作为服务端也会失败
