### ISSUE TITLE
通过java jni调用sm2签名相关逻辑，大压力下，总是在BN_mul处崩溃

### ISSUE THREAD

**Issue by victortanjh** [guanzhi/GmSSL#1029]
![image](https://user-images.githubusercontent.com/9362682/98222722-2adde600-1f8c-11eb-9b75-f2ab4c3e37c2.png)

虽然不是每次都崩溃。但是崩溃之后，都是在这个位置。
请问如何能够打印出libcrypto.so中的崩溃栈？
目前崩溃栈，仅仅能够打印到java jni调用的地方。

**Comment by Youcai98** [comment]
请问您解决这个问题了吗
