### ISSUE TITLE
冒昧问一下，当前gmssl有通过商用密码检测中心的测试吗？

### ISSUE THREAD

**Issue by willalways** [guanzhi/GmSSL#103]
gmssl是我能找到的最规范的国密算法的开源实现了，我想确认一下该实现是否有通过检测中心测试？

检测中心测试网址： http://www.scctc.org.cn/index.aspx

**Comment by J-Feng** [comment]
应该是使用该库的产品去做检测吧？作为一个开源实现，如果去过国密检测，周期长，开销大

**Comment by LiTianjue** [comment]
过检的是产品而不是软件本身，除去国密相关的东西，其实还有很多杂七杂八的规范，周期确实会比较长，而且以我的经验，不会一次过，可能还要复检，一边开发一边检测，甚至还没开发好，就会先去检测，再按检测规范进行开发

**Comment by guanzhi** [comment]
目前没有参加检测，但是从中国的国情以及国际通行的做法来看，过检似乎有一定的必要，而且OpenSSL也经过了FIPS的的检测。

**Comment by yuanzh78** [comment]
试过了，用gmssl做的sm2证书在过检的产品上证书验证不过，虽然证书在window下打开显示信息无误

**Comment by yuanzh78** [comment]
搞笑的是，中国这些标准网上都禁止下载的，必须花钱去出版社买

**Comment by guanzhi** [comment]
部分文档在这里有：
https://github.com/guanzhi/GmSSL-Website/tree/master/standards

**Comment by zppet** [comment]
404了

**Comment by tian-zhong** [comment]
国标委的网站可以查看。以SM2为例的系列标准 （可能要用chrome浏览器）
part 1 [总则](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=3EE2FD47B962578070541ED468497C5B)
part 2 [数字签名算法](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=6F1FAEB62F9668F25F38E0BF0291D4AC)
part 3 [密钥交换协议](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=66A89DD6DA64F49C49456B757BA0624F)
part 4 [公钥加密算法](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=370AF152CB5CA4A377EB4D1B21DECAE0)
part 5 [参数定义](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=728DEA8B8BB32ACFB6EF4BF449BC3077)

**Comment by hustms** [comment]
gmssl有没有经过国密标准检测，能否和其他实现对通?
