### ISSUE TITLE
关于GmSSL的ENGINE机制的咨询

### ISSUE THREAD

**Issue by Yikun** [guanzhi/GmSSL#1031]
OpenSSL通过ENGINE来加载第三方加密库[1]，例如，我们可以使用ENGINE机制加载一些硬件模块来进行硬加速，比如KAE[2]。

想确认一下：

1. GmSSL是否完善的支持ENGINE机制，以支持第三方引擎的加载？
2. 是否所有的接口所依赖的数据结构均已和openssl同步？

[1] https://www.openssl.org/docs/man1.1.0/man1/engine.html
[2] https://github.com/kunpengcompute/KAE

**Comment by Yikun** [comment]
cc @zhaoxiaomeng @guanzhi

**Comment by zhenyuwei** [comment]
https://github.com/guanzhi/GmSSL/blob/gmbrowser-v0.1/engines/e_gmi.c 参考一下这个文件
