### ISSUE TITLE
error:100D7010:elliptic curve routines:ECKEY_PUB_DECODE:EC lib

### ISSUE THREAD

**Issue by qqchengshuai** [guanzhi/GmSSL#1035]
Red Hat Enterprise Linux Server release 6.7 环境下；
调用 SSL_CTX_use_certificate_file时失败，提示：error:100D7010:elliptic curve routines:ECKEY_PUB_DECODE:EC lib
哪位遇到过这个错误，帮解答一下，谢谢。

**Comment by csquan** [comment]
same question，solved？
