### ISSUE TITLE
指定密钥套件 0xe013，服务端报错gmtls_construct_ske_sm2:internal error:ssl/statem/statem_gmtls.c:731

### ISSUE THREAD

**Issue by 31308836** [guanzhi/GmSSL#1036]
**Describe the bug**
服务端指定密钥套件 0xe013启动ssl服务
gmssl s_server -key ./ssl/3rd.key -dcertform PEM -cert ./ssl/3rd.pem -accept 7443 -4 -cipher  SM2-WITH-SMS4-SM3
客户端发起ssl通信请求。
gmssl s_client -connect 127.0.0.1:7443 -gmtls -cipher SM2-WITH-SMS4-SM3

**Expected behavior**
握手成功

**Screenshots**
![image](https://user-images.githubusercontent.com/49849713/99935931-d49ae080-2d9c-11eb-98a8-c2e857fb765f.png)

**Environments**
<SM2-WITH-SMS4-SM3>
Using default temp DH parameters
[GMTLS_DEBUG] set sm2 signing certificate
[GMTLS_DEBUG] set sm2 signing private key
ACCEPT
Server has 1 from 0x1f1cd30:
0x7ff0f9f94968:SM2-WITH-SMS4-SM3
Client sent 1 from 0x1f1d7d0:
0x7ff0f9f94968:SM2-WITH-SMS4-SM3
dht=1 re=0 rs=0 ds=0
1:[alg_k=00000200:alg_a=00000100:mask_k=00000F8E:mask_a=00000114]0x7ff0f9f94968:SM2-WITH-SMS4-SM3
ssl_get_algorithm2=f9d4585008x
ERROR
140672964872000:error:141C0044:SSL routines:gmtls_construct_ske_sm2:internal error:ssl/statem/statem_gmtls.c:731:
shutting down SSL
CONNECTION CLOSED
ACCEPT

**Additional context**
gmssl生成的证书和第三方证书均报错

**Comment by 31308836** [comment]
[root@logstash test]# uname -a
Linux logstash.srv 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@logstash test]# cat /proc/version
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

**Comment by luhongxin1349** [comment]
There are some handshake errors in the source code
