### ISSUE TITLE
windows编译提示无法解析的外部符号 EVP_get_ciphernames

### ISSUE THREAD

**Issue by fairychao** [guanzhi/GmSSL#1037]
IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\LIYUEC~1\AppData\Local\Temp\nmBF67.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_ciphernames
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_digestnames
libcrypto.lib : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”
Stop.

环境：windows 10，vs 2019，当前master最新下载

**Comment by fairychao** [comment]
修改  include\openssl\evp.h
由于这两个函数没有实现，也没有其它函数调用，注释掉即可
/*
char *EVP_get_ciphernames(int aliases);
char *EVP_get_digestnames(int aliases);
*/

**Comment by YangShizhao** [comment]
> 

你好，我根据你提供的方法注释了这两行代码，但编译时任然提示无法解析的外部符号

**Comment by scribbler** [comment]
我在在evp_lib.c中增加了如下代码，编译通过
`char *EVP_get_ciphernames(int aliases)
{
    return NULL;
}
char *EVP_get_digestnames(int aliases)
{
    return NULL;
}`
