### ISSUE TITLE
error: ld returned 1 exit status

### ISSUE THREAD

**Issue by QZYooking** [guanzhi/GmSSL#1047]
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.shared:194: link_app.gnu] Error 1
make[2]: Leaving directory '/home/yooking/Downloads/GmSSL-gmbrowser-v0.1'
make[1]: *** [Makefile:2456: fuzz/bignum-test] Error 2

What shall I do?

**Comment by Jesson029** [comment]
What shall I do?
master banch has the same problem？
