### ISSUE TITLE
编译gmssl，运行sm3test的错误结果反馈 

### ISSUE THREAD

**Issue by willalways** [guanzhi/GmSSL#105]
我运行sm3test发现结果有打印出其中一个哈希值不匹配，不知道是什么原因
下面是我的运行结果

test 1 ok
test 2 ok
test 3 ok
test 4 ok
test 5 ok
test 6 ok
error calculating SM3 on 0090414C494345313233405941484F4F2E434F4D00000000000000000000000000000000000000000000000000000000000000000000E78BCD09746C202378A7E72B12BCE00266B9627ECB0B5A25367AD1AD4CC6242B00CDB9CA7F1E6B0441F658343F4B10297C0EF9B6491082400A62E7A7485735FADD013DE74DA65951C4D76DC89220D5F7777A611B1C38BAE260B175951DC8060C2B3E008E3BDB2E11F9193388F1F901CCC857BF49CFC065FB38B9069CAAE6D5AFC3592F004555122AAC0075F42E0A8BBD2C0665C789120DF19D77B4E3EE4712F598040415
got 329c2f6030cc7e0ca3af6c97b76243ca250338ad3d3dc3a8b322d1cfdf98c2b7 instead of ECF0080215977B2E5D6D61B98A99442F03E8803DC39E349F8DCA5621A9ACDF2B
test 8 ok
test 9 ok
test 10 ok

**Comment by guanzhi** [comment]
这一项SM3的测试数据来自于[SM2文档](https://github.com/guanzhi/GmSSL-Website/blob/master/standards/sm2.pdf)第76页（第三部分密钥交换第12页）第二行的数据ZB。GmSSL的SM3实现没有通过这项测试。

可能的原因：
1. GmSSL的SM3实现有错误，因此生成了错误的哈希值
2. GmSSL的测试的输入消息组成不正确（可能我们对ZB输入消息的组合方式理解不正确），导致哈希结果和ZB的值不匹配
3. 我们从文档上复制数据的时候出现编辑错误，或者文档上有编辑错误，导致这项测试数据本身不正确，因此也就无法通过测试。

这项测试的错误也导致SM2的这一项对应测试不能通过。

我们暂时无法确定错误原因，但是保留这个错误以提醒用户注意。

**Comment by guanzhi** [comment]
这一项SM3的测试数据来自于[SM2文档](https://github.com/guanzhi/GmSSL-Website/blob/master/standards/sm2.pdf)第75页（第三部分密钥交换第11页）最后一行ZA。GmSSL的SM3实现没有通过这项测试。

可能的原因：
1. GmSSL的SM3实现有错误，因此生成了错误的哈希值
2. GmSSL的测试的输入消息组成不正确（可能我们对ZB输入消息的组合方式理解不正确），导致哈希结果和ZB的值不匹配
3. 我们从文档上复制数据的时候出现编辑错误，或者文档上有编辑错误，导致这项测试数据本身不正确，因此也就无法通过测试。

这项测试的错误也导致SM2的这一项对应测试不能通过。

我们暂时无法确定错误原因，但是保留这个错误以提醒用户注意。
