### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by xhf2006hn** [guanzhi/GmSSL#1052]
使用gmssl替换openssl编译nginx后，配置国密证书，用国密浏览器（密信）访问，提示：
“使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH”

抓包：
![image](https://user-images.githubusercontent.com/19721628/102948107-0fa94480-4500-11eb-9165-1bca6ec5b8e4.png)

问题出在什么地方？

**Comment by xhf2006hn** [comment]
是不是不支持GMSSLv1协议？

**Comment by cnlh** [comment]
密信浏览器只在第一次访问一个域名时尝试GMTLS协议，如果尝试后发现不支持GMTLS，将不会再尝试GMTLS协议

**Comment by majorinche** [comment]
现在有解决吗？
