### ISSUE TITLE
请问sm2使用已有私密解密时，如何将char* 类型的私密转换成EC_KEY。

### ISSUE THREAD

**Issue by hubo980205** [guanzhi/GmSSL#1053]
请问sm2使用已有私密解密时，如何将char* 类型的私密转换成EC_KEY。这个私密是已经生成好的，以HEX的形式存储在内存。

**Comment by BalrogMithrandir** [comment]
BN_bin2bn将hex的私钥转为大数，然后调用EC_KEY_set_private_key

**Comment by boguang2000** [comment]
> 请问sm2使用已有私密解密时，如何将char* 类型的私密转换成EC_KEY。这个私密是已经生成好的，以HEX的形式存储在内存。

EC_KEY *createPubKey(const unsigned char *pubKeyBuf, size_t pubKeyLen) {
	char *pubHex;
	char *pubHex_ = smcrypto_buf2hex(pubKeyBuf, pubKeyLen);
	EC_KEY *ec_pubkey;
	const EC_GROUP *ec_group;
	BN_CTX *bn_ctx;
	EC_POINT *pubkey_point;
	if(isPublicKeyHex(pubHex_)==0) {
		ec_pubkey = NULL;
		goto end;
	}
	pubHex = repairPublicKeyHex(pubHex_);
	//ec_pubkey = EC_KEY_new();
	ec_pubkey = EC_KEY_new_by_curve_name(NID_sm2p256v1);
	ec_group = EC_KEY_get0_group(ec_pubkey);
	bn_ctx = BN_CTX_new();
	pubkey_point = EC_POINT_hex2point(ec_group, pubHex, NULL, bn_ctx);
	EC_KEY_set_public_key(ec_pubkey, pubkey_point);

	EC_POINT_free(pubkey_point);
	BN_CTX_free(bn_ctx);

	free(pubHex);
end:
	free(pubHex_);
	return ec_pubkey;
}

EC_KEY *createPrvKey(const unsigned char* prvKeyBuf, size_t prvKeyLen) {
	char *prvHex = smcrypto_buf2hex(prvKeyBuf, prvKeyLen);
	EC_KEY *ec_prvkey;
	BIGNUM *bn_prikey;

	if(isPrivateKeyHex(prvHex)==0) {
		ec_prvkey = NULL;
		goto end;
	}

	//ec_prvkey = EC_KEY_new();
	ec_prvkey = EC_KEY_new_by_curve_name(NID_sm2p256v1);
	bn_prikey = BN_new();
	BN_hex2bn(&bn_prikey, prvHex);
	EC_KEY_set_private_key(ec_prvkey, bn_prikey);

	BN_free(bn_prikey);
end:
	free(prvHex);
	return ec_prvkey;
}
