### ISSUE TITLE
2.0新版，编译不过。 请问了

### ISSUE THREAD

**Issue by andylau004** [guanzhi/GmSSL#106]
LD_LIBRARY_PATH=.:/usr/local/openssl/lib gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/bb1ibetest test/bb1ibetest.o -L. -lcrypto -ldl
test/bb1ibetest.o: In function `main':
bb1ibetest.c:(.text.startup+0x49): undefined reference to `BB1IBE_setup'
bb1ibetest.c:(.text.startup+0x6d): undefined reference to `BB1PublicParameters_free'
bb1ibetest.c:(.text.startup+0x77): undefined reference to `BB1MasterSecret_free'
bb1ibetest.c:(.text.startup+0x7f): undefined reference to `BB1PrivateKeyBlock_free'
bb1ibetest.c:(.text.startup+0xcc): undefined reference to `BB1IBE_extract_private_key'
bb1ibetest.c:(.text.startup+0x10a): undefined reference to `BB1IBE_encrypt'
bb1ibetest.c:(.text.startup+0x165): undefined reference to `BB1IBE_encrypt'
bb1ibetest.c:(.text.startup+0x19c): undefined reference to `BB1IBE_decrypt'
bb1ibetest.c:(.text.startup+0x1df): undefined reference to `BB1IBE_decrypt'
collect2: error: ld returned 1 exit status

**Comment by andylau004** [comment]
./config
make

后出现。

**Comment by willalways** [comment]
./config --prefix=/opt/GmSSL no-shared
你可以通过no-shared，既使用静态库的形式可以避免这个问题

另外你也可以通过手动链接静态库的形式，具体编译命令如下
gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/bb1ibetest test/bb1ibetest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/bfibetest test/bfibetest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/eciestest test/eciestest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/ffxtest test/ffxtest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/gmapitest test/gmapitest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/kdf2test test/kdf2test.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/otptest test/otptest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/sdftest test/sdftest.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/sm2test test/sm2test.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/sm9test test/sm9test.o libcrypto.a -ldl

gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/sms4test test/sms4test.o libcrypto.a -ldl

**Comment by andylau004** [comment]
@willalways 还是 不行。哎。

**Comment by orxvan** [comment]
@andylau004 有解决办法吗？

**Comment by andylau004** [comment]
@orxvan 不行。

**Comment by andylau004** [comment]
@orxvan 感觉每次出版本都无法一次编译过。。郁闷了。

**Comment by orxvan** [comment]
@andylau004 ./config no-bb1be试试，我编译gmssl.org主页2.0的版本，mac编译通过

**Comment by andylau004** [comment]
@orxvan 

./libcrypto.so: undefined reference to `padlock_reload_key'
./libcrypto.so: undefined reference to `padlock_ecb_encrypt'
./libcrypto.so: undefined reference to `padlock_ctr32_encrypt'
./libcrypto.so: undefined reference to `padlock_cfb_encrypt'
./libcrypto.so: undefined reference to `padlock_aes_block'
./libcrypto.so: undefined reference to `padlock_ofb_encrypt'
./libcrypto.so: undefined reference to `padlock_capability'
./libcrypto.so: undefined reference to `padlock_cbc_encrypt'
./libcrypto.so: undefined reference to `padlock_xstore'
collect2: error: ld returned 1 exit status


 ./config no-bb1ibe 使用这个命令后
编译新错误。

**Comment by HarukaMa** [comment]
原因大概是这个：

编译过程通过调用 `util/mkdef.pl` 来生成 .map 文件喂给链接参数（`--version-script`)，但其中并未正确加入项目新增的 .h 文件，所以生成的 .map 文件中没有这些函数，这些函数就不会在 .so 中 export 出来。

通过暂时修改 `Makefile.shared` 文件可以缓解此问题（但不靠谱）。

```
diff --git a/Makefile.shared b/Makefile.shared
index 098e1ec..82d6564 100644
--- a/Makefile.shared
+++ b/Makefile.shared
@@ -196,7 +196,7 @@ link_app.gnu:
 link_shlib.linux-shared:
        @$(PERL) $(SRCDIR)/util/mkdef.pl $(LIBNAME) linux >$(LIBNAME).map; \
        $(DO_GNU_SO); \
-       ALLSYMSFLAGS='-Wl,--whole-archive,--version-script=$(LIBNAME).map'; \
+       ALLSYMSFLAGS='-Wl,--whole-archive'; \
        $(LINK_SO_SHLIB)

 link_dso.bsd:
```

**Comment by francliu** [comment]
也不对啊，即使安装成功，也会出现gmssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by francliu** [comment]
@HarukaMa 请问下有那个版本可以稳定运行啊？我是了所有的要么是安装不成功，要么安装成功也没有gmssl命令可以执行啊，谢谢了。

**Comment by francliu** [comment]
@HarukaMa 请问下有那个版本可以稳定运行啊？我试了所有的版本要么是安装不成功，要么安装成功也没有gmssl命令可以执行啊，谢谢了

**Comment by andylau004** [comment]
晕了。

**Comment by francliu** [comment]
@andylau004 你是过其他版本吗？

**Comment by HarukaMa** [comment]
@francliu ……啊 这个的临时解决方案是 LD_LIBRARY_PATH 或者这俩文件直接扔到 /usr/lib 里。

最理想的是编译的时候这个调用 so 的位置根据 prefix 自动决定……

这个版本现在应该是能用的。我在 macOS 上测试了 SM2 的生成 privkey pubkey 和 sign verify，结果上看都没问题。

**Comment by sslvpn007** [comment]
mac上 是可以的。

**Comment by francliu** [comment]
@HarukaMa 不是mac啊，试了还是一样的结果，就是想问一下有没有一个稳定的版本我试试看看。

**Comment by HarukaMa** [comment]
@francliu 在 Linux 上也没问题啊……如果指的是不用折腾就能直接用得版本的话我就不知道了……试试 v1？

**Comment by francliu** [comment]
@HarukaMa 确实可以，刚才看错了，谢谢您了。

**Comment by iosKey** [comment]
mac 报 error: incomplete definition of type 'struct
      SM2CiphertextValue_st' 有人知道怎么解决吗
