### ISSUE TITLE
基于SM2-WITH-SMS4-SM3密码套件与客户端连接握手失败

### ISSUE THREAD

**Issue by luhongxin1349** [guanzhi/GmSSL#1064]
1、我们的程序为SSL服务端
2、抓包显示客户端的回复，服务端解密失败。
![887de32676792c6ab7ca22d0b663ee5](https://user-images.githubusercontent.com/75530368/106444511-d4b00e80-64b8-11eb-8330-6f6c9099a47c.png)
3、id已经改为了1234567812345678，n的长度已经+3.
还有哪里需要改？
**急！！！急！！！急！！！**

**Comment by luhongxin1349** [comment]
服务端也加入了Z值计算。

**Comment by ww1999520** [comment]
你好,可以麻烦你发一下给我吗?我现在在对接国密ssl的vpn,我要是在握手这一步扑街了,但是我对于算法完全是小白...

**Comment by ww1999520** [comment]
我是国密ssl的客户端部分,算法太懵了.....

**Comment by duoluodexiaokeke** [comment]
能提供一下修改的代码么？我这现在也是做客户端和服务通信失败
提示 SSL routines:tls_post_process_client_hello:no shared cipher
使用gmssl的通信测试
SSL_connect:SSLv3/TLS write client hello
read from 0xa3a5b0 [0xa3fb93] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
SSL_connect:error in SSLv3/TLS write client hello

**Comment by sunxinsara** [comment]
> 能提供一下修改的代码么？我这现在也是做客户端和服务通信失败
> 提示 SSL routines:tls_post_process_client_hello:no shared cipher
> 使用gmssl的通信测试
> SSL_connect:SSLv3/TLS write client hello
> read from 0xa3a5b0 [0xa3fb93] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
> SSL_connect:error in SSLv3/TLS write client hello


你这里是协商的密码套件的时候就失败了呀

**Comment by wugx520** [comment]
> 1234567812345678



> 服务端也加入了Z值计算。现在错误是：SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:512
> 根据0024-2014，计算PRF的方式是否需要改？？？？
> 
> **经历了为时一周的调试，终于和过检方可以连通了。 修改了多处GMSSL源码。鼓励下自己！！！！**

都是修改了哪些方便 给出吗 ，我的客服端，发出，服务端提示解密失败

**Comment by wugx520** [comment]
![image](https://user-images.githubusercontent.com/50013597/127452450-ded8d1b6-5dfa-47d1-b286-a041d5f0c58c.png)

**Comment by 403705726** [comment]
@luhongxin1349 请问如何解决的，我也是在过检的过程中出现这个问题，猜想是因为encrypt_then_mac的方式和对端不匹配呢，请给个建议
