### ISSUE TITLE
gmtls默认不支持sni吗？

### ISSUE THREAD

**Issue by wayixia** [guanzhi/GmSSL#1067]
@guanzhi  gmtls默认不支持sni吗？
ssl/statem/statem_clnt.c:932 下有段代码加了个判断 (s->version != GMTLS_VERSION) , 注释掉后，客户端发送的包带servername， sni才能工作正常

    if ( **(s->version != GMTLS_VERSION) &&** </font> (p =
         ssl_add_clienthello_tlsext(s, p, buf + SSL3_RT_MAX_PLAIN_LENGTH,
                                    &al)) == NULL) {
        ssl3_send_alert(s, SSL3_AL_FATAL, al);
        SSLerr(SSL_F_TLS_CONSTRUCT_CLIENT_HELLO, ERR_R_INTERNAL_ERROR);
        goto err;
    } 

不知道出于什么考虑，有人知道吗？

**Comment by wayixia** [comment]
经过测试gmtls，sni处理逻辑正常，后续的处理还有问题(SSL routines:ssl3_get_record:decryption failed or bad record mac ), 应该是改出问题了，还请指点一二

**Comment by syr-1** [comment]
> SSL routines:ssl3_get_record:decryption failed or bad record mac

SSL routines:ssl3_get_record:decryption failed or bad record mac    请问这个问题最终解决了吗？

**Comment by 403705726** [comment]
@wayixia 同问，问题解决了吗

**Comment by cppdebug** [comment]
客户端打开了tlsext, 服务端也需要打开啊.  这个函数tls_construct_server_hello的 s->version != GMTLS_VERSION 部分同样也注释掉即可.
