### ISSUE TITLE
有关sm2在codeblock上的运行问题

### ISSUE THREAD

**Issue by xiaoxiaoenjoying** [guanzhi/GmSSL#107]
老师您好，我最近从GitHub上下载了Gmssl的源码，将sm2的代码在codeblock上运行时，出现了找不到opensslconf.h文件的问题。而我在整个文件夹中只找到了opensslconf.h.in文件，没找到opensslconf.h文件。想请教老师这个问题怎么解决。谢谢您。

**Comment by guanzhi** [comment]
opensslconf.h文件是在运行`./config`后由编译系统从opensslconf.h.in生成的，如果没有找到这个文件说明配置和编译没有完成，注意`./config`的错误提示，有时候可能会提示需要执行`make update`。如果编译master分支的2.0，注意`./config no-saf no-sdf no-skf no-sof no-...`禁用所有出错的模块。如果是1.3应不存在问题。
