### ISSUE TITLE
老师好，使用官方的示例 gmssl sm2 -genkey -out skey.pem 生成私钥，可不可以不要码密码

### ISSUE THREAD

**Issue by haileshen** [guanzhi/GmSSL#1070]
**Describe the bug**
非BUG

**Expected behavior**
1、使用官方的示例 gmssl sm2 -genkey -out skey.pem 生成私钥时，强制需要输入密码，可不可加参加，不需要输入密码？
2、“ gmssl sm2 -genkey -out skey.pem” 与使用“gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -out pri_key.pem”命令生成的密钥，会有什么不同？

**Comment by firefeifei** [comment]
为何你有密码，而我的命令生成时没有呢？而我确是需要这个密码的

**Comment by grmust** [comment]
用base64解码看一下就知道有什么不同了
