### ISSUE TITLE
关于和tassl互操作的问题

### ISSUE THREAD

**Issue by Baymini-zx** [guanzhi/GmSSL#1078]
gmssl在和tassl进行互操作的时候，出现如下错误，想了解下gmssl与tassl兼容吗？可以进行互操作吗？
![微信截图_20210318161927](https://user-images.githubusercontent.com/61739820/111594215-be120c80-8805-11eb-8bf1-6dc1f9873682.png)

**Comment by zhenyuwei** [comment]
看你这截图，查一下两端预主密钥和会话密钥计算的参数有没有问题
