### ISSUE TITLE
JAVA 支持gmssl生成的证书加载吗

### ISSUE THREAD

**Issue by firefeifei** [guanzhi/GmSSL#1080]
**Describe the bug**
1. java 是否可以使用gmssl生成pem 格式的证书加载，并使用TLS的进行传输加密

**Expected behavior**

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by leavesth** [comment]
Java默认应该是不支持GMSSL的，但是国密的证书应该能加载和解析，只是无法验证。GMSSL的通信我的解决办法是自己实现一个socks5代理，然后代理分级部署，两个代理间使用GMSSL的协议通信。Java可以使用命令行、程序里面写的方式或者是在Linux里面配置透明代理的模式解决代理的使用问题。

**Comment by BinXiang123** [comment]
> 
> 
> Java默认应该是不支持GMSSL的，但是国密的证书应该能加载和解析，只是无法验证。GMSSL的通信我的解决办法是自己实现一个socks5代理，然后代理分级部署，两个代理间使用GMSSL的协议通信。Java可以使用命令行、程序里面写的方式或者是在Linux里面配置透明代理的模式解决代理的使用问题。

“自己实现一个socks5代理，然后代理分级部署，两个代理间使用GMSSL的协议通信”，请教以下两个问题：
第一，自己实现socks5代理是使用什么开源框架吗？
第二，在提供给客户端的java SDK中，若通过这个代理加载证书完成SSL通信，那么，代理程序必然会独立于SDK而存在，这里是否可以基于GmSSL的实现，通过JNI封装出对应的SSL传输接口，提供给SDK使用？

**Comment by wangyu096** [comment]
同求，希望能提供java实现的证书加载demo

**Comment by leavesth** [comment]
> > Java默认应该是不支持GMSSL的，但是国密的证书应该能加载和解析，只是无法验证。GMSSL的通信我的解决办法是自己实现一个socks5代理，然后代理分级部署，两个代理间使用GMSSL的协议通信。Java可以使用命令行、程序里面写的方式或者是在Linux里面配置透明代理的模式解决代理的使用问题。
> 
> “自己实现一个socks5代理，然后代理分级部署，两个代理间使用GMSSL的协议通信”，请教以下两个问题：
> 第一，自己实现socks5代理是使用什么开源框架吗？
> 第二，在提供给客户端的java SDK中，若通过这个代理加载证书完成SSL通信，那么，代理程序必然会独立于SDK而存在，这里是否可以基于GmSSL的实现，通过JNI封装出对应的SSL传输接口，提供给SDK使用？

1. 3proxy(https://github.com/z3APA3A/3proxy)可以达到目的，要修改代码，下级代理的remotesock使用gmssl里面的ssl通道；上级代理的clientsocket使用gmssl的ssl通道。
2. 因为配置有代理，java程序就不需要使用gmssl sdk，直接使用代理访问网络即可实现gmssl通信。代理配置为修改过的3proxy下级代理地址。
