### ISSUE TITLE
sm2算法与ecc的实现上的区别？

### ISSUE THREAD

**Issue by francliu** [guanzhi/GmSSL#109]
我看了相关资料，发现两者实际上基本差别不大，主要是曲线参数不同，以及运算过程的稍微有点变化，其他的思路感觉基本一致，请问下他们两者实现上有啥区别啊，比如曲线方面？

**Comment by guanzhi** [comment]
SM2的几个算法和椭圆曲线算法的国际标准有一定的区别，其中密钥交换的区别较大。SM2通常要求在处理的消息前添加公钥和ID的哈希值（即Z值），当然这也可以视为对消息的一个预处理。SM2标准给出了一个256位的默认椭圆曲线推荐参数`sm2p256v1`，因此SM2的应用大多默认采用这个曲线参数，但是这不应该视为区别。

**Comment by francliu** [comment]
@guanzhi谢谢您呀，这个我了解，这两天我在实现8bitcpu上的sm2算法，我根据别人已经写好的一个ecc算法进行修改，主要是把所有用到的曲线参数以及基点，公钥私钥修改为sm2上的参考例子里面的参数。之后根据算法签名以及验证过程修改为sm2的算法，其中hash值也是使用的案例上的，但是他计算过程中出现的结果和案例不一样，且验证不通过，请问下我这样做对吗？因为我看到这个开源中的sm2也是，修改曲线参数以及自己写的sm2签名以及验证过程就对着了。

**Comment by guanzhi** [comment]
使用测试数据中的固定随机数，并且和GmSSL (1.3.0) 对比你每一步的中间结果，应该很容易发现到底是哪一步出了错。

**Comment by junfx** [comment]
@francliu 请教一下, 8bitcpu上实现国密, 用openssl还是自己重头来, 重头来那BN, EC_POINT之类的都要自己写吗?

**Comment by junfx** [comment]
@guanzhi 请教一下, sm2中说的"可辨别标识", ID_A, 到底是什么东西?
1. gmssl是放在eckey中, 那能不能从证书中获取呢?
2. 如果client不提供证书, 使用ephemeral-sm2交换模式, 如何确定ID?
3. 如果使用ephemeral模式做sm2密钥交换, 可能使用RSA证书, 连eckey都没有, 那么如何确定ID?
4. 问题是标准中并没有定义这个到底是什么, 只是说"唯一可辨别"

**Comment by francliu** [comment]
@junfx 您好，我在github上找的一个ecc的代码， 进行修改的，只写了签名与验证过程，不过有点错误，不知道为啥

**Comment by junfx** [comment]
@francliu 像guanzhi说的, 先找到第一个出错的步骤. 如果你怀疑你找的代码, 可以用openssl来和他的对比, 看看他的实现有没有问题.

**Comment by guanzhi** [comment]
SM2标准将如何定义ID的任务留给了应用。GmSSL要求这是一个较短的（小于`SM2_MAX_ID_LENGTH`）、可以打印的C字符串（不能包含0x0）。如果应用使用证书，那么这个ID是证书中Subject的DN名字中的CN部分。如果不使用证书，那么应用可以自行指定这个ID的格式，比如邮件地址、IP地址、域名、手机号等。GmSSL 2.0默认不再进行Z值的计算，也不将ID保存在`EC_KEY`数据结构中，因此在用于SSL协议时不涉及获取ID的问题。
