### ISSUE TITLE
apple m1 build fail,symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by maxlv7** [guanzhi/GmSSL#1091]
(maybe you meant: _X509_STORE_CTX_set_time, _X509_time_adj_ex , _X509_time_adj , _x509_check_cert_time , _TS_TST_INFO_set_time , _TS_RESP_CTX_set_time_cb , _X509_VERIFY_PARAM_set_time , _PKCS7_add0_attrib_signing_time , _TS_TST_INFO_get_time , _CT_POLICY_EVAL_CTX_set_time , _SCT_CTX_set_time , _SCT_get_timestamp , _CT_POLICY_EVAL_CTX_get_time , _SCT_set_timestamp , _X509_cmp_current_time , _X509_cmp_time , _ASN1_UTCTIME_cmp_time_t , _X509_VERIFY_PARAM_get_time , _x509_set1_time )
  "_vfprintf", referenced from:
      _OPENSSL_showfatal in libcrypto.a(cryptlib.o)
  "_write$UNIX2003", referenced from:
      _conn_write in libcrypto.a(bss_conn.o)
      _conn_puts in libcrypto.a(bss_conn.o)
      _dgram_write in libcrypto.a(bss_dgram.o)
      _fd_write in libcrypto.a(bss_fd.o)
      _sock_write in libcrypto.a(bss_sock.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_shlib.darwin] Error 1
make[1]: *** [libcrypto.dylib] Error 2
make: *** [all] Error 2

**Comment by maxlv7** [comment]
apple m1 architecture is arm64.

**Comment by mr-m0nst3r** [comment]
@maxlv7 Hi, have you figured this out? any guide? thank you

**Comment by maxlv7** [comment]
> @maxlv7 Hi, have you figured this out? any guide? thank you

sry i did not,I use OpenSSL instead，openssl now support sm2 and sm3
