### ISSUE TITLE
gmssl server core when using cipher suite SM2DHE-WITH-SMS4-SM3

### ISSUE THREAD

**Issue by andyxmu** [guanzhi/GmSSL#1092]
**Describe the bug**
as title described, the core happens under below testing environment

server side:
gmssl s_server -accept 7443 -cert ./sm2.sig.crt.pem -key ./sm2.sig.key.pem -dcert sm2.enc.crt.pem -dkey sm2.enc.key.pem -msg -debug

client side:
gmssl s_client -connect 127.0.0.1:7443 -CApath ./ -gmtls -msg -debug -cipher SM2DHE-WITH-SMS4-SM3

result on sever side:

read from 0x7fa88e004960 [0x7fa88e813003] (5 bytes => 5 (0x5))
0000 - 16 01 01 00 2f                                    ..../
<<< ??? [length 0005]
    16 01 01 00 2f
read from 0x7fa88e004960 [0x7fa88e813008] (47 bytes => 47 (0x2F))
0000 - 01 00 00 2b 01 01 e5 c0-e6 5b b4 ed 6a 28 ab 8a   ...+.....[..j(..
0010 - 28 9e e4 c1 49 eb fa 80-df ab 00 60 da cc a1 22   (...I......`..."
0020 - b7 cf 09 6b f6 6b 00 00-04 e0 11 00 ff 01         ...k.k........
002f - <SPACES/NULS>
dec 47
01 00 00 2B 01 01 E5 C0 E6 5B B4 ED 6A 28 AB 8A
28 9E E4 C1 49 EB FA 80 DF AB 00 60 DA CC A1 22
B7 CF 09 6B F6 6B 00 00 04 E0 11 00 FF 01 00
<<< TLS 1.2Handshake [length 002f], ClientHello
    01 00 00 2b 01 01 e5 c0 e6 5b b4 ed 6a 28 ab 8a
    28 9e e4 c1 49 eb fa 80 df ab 00 60 da cc a1 22
    b7 cf 09 6b f6 6b 00 00 04 e0 11 00 ff 01 00

>>> ??? [length 0005]
    16 01 01 00 4a
>>> GMTLS 1.1 [length 004a]
    02 00 00 46 01 01 3c 6e ce ff 7b 70 06 d5 2b 20
    c6 fa ad b1 42 c6 73 a1 90 27 80 b4 83 31 d2 41
    82 55 75 00 bd 98 20 bf a1 65 8d 6c 0b 21 1c b1
    99 4b 8e 1d c7 b5 4d e9 f1 55 7b 7e 39 39 f2 cb
    1e 5e 55 b4 3f ca 40 e0 11 00
>>> ??? [length 0005]
    16 01 01 04 6e
>>> GMTLS 1.1 [length 046e]
    0b 00 04 6a 00 04 67 00 02 30 30 82 02 2c 30 82
    01 d0 a0 03 02 01 02 02 06 01 78 fd f5 28 ee 30
    0c 06 08 2a 81 1c cf 55 01 83 75 05 00 30 4b 31
    0b 30 09 06 03 55 04 06 13 02 43 4e 31 0e 30 0c
    06 03 55 04 0a 13 05 47 4d 53 53 4c 31 10 30 0e
    06 03 55 04 0b 13 07 50 4b 49 2f 53 4d 32 31 1a
    30 18 06 03 55 04 03 13 11 4d 69 64 64 6c 65 43
    41 20 66 6f 72 20 54 65 73 74 30 22 18 0f 32 30
    32 31 30 34 32 32 31 36 30 30 30 30 5a 18 0f 32
    30 32 32 30 34 32 32 31 36 30 30 30 30 5a 30 7e
    31 0b 30 09 06 03 55 04 06 13 02 43 4e 31 10 30
    0e 06 03 55 04 08 13 07 62 65 69 6a 69 6e 67 31
    10 30 0e 06 03 55 04 07 13 07 73 68 61 6e 67 64
    69 31 0c 30 0a 06 03 55 04 0a 13 03 61 63 67 31
    0e 30 0c 06 03 55 04 0b 13 05 62 61 69 64 75 31
    0e 30 0c 06 03 55 04 03 13 05 62 61 69 64 75 31
    1d 30 1b 06 09 2a 86 48 86 f7 0d 01 09 01 16 0e
    74 65 73 74 40 62 61 69 64 75 2e 63 6f 6d 30 59
    30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 81 1c
    cf 55 01 82 2d 03 42 00 04 b5 78 98 55 a3 da b0
    38 35 18 99 78 4c b1 4f 64 1f 4b 47 eb 39 09 0a
    42 ea ba 22 f8 42 4c 49 53 df 64 02 a0 71 0b e8
    e8 b6 68 fb 37 82 49 e9 5b 6f 7b c8 02 d7 ea 7a
    38 54 c3 ab 18 04 dd eb 23 a3 67 30 65 30 1b 06
    03 55 1d 23 04 14 30 12 80 10 f9 7f 55 b4 27 94
    33 62 a6 56 ca 6f cc 5d 1a ff 30 19 06 03 55 1d
    0e 04 12 04 10 94 70 01 b8 6b 78 10 cf 88 75 30
    97 1a 60 49 67 30 10 06 03 55 1d 11 04 09 30 07
    82 05 62 61 69 64 75 30 09 06 03 55 1d 13 04 02
    30 00 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02
    00 c0 30 0c 06 08 2a 81 1c cf 55 01 83 75 05 00
    03 48 00 30 45 02 21 00 a0 ef 55 97 0b 6e 58 2e
    f7 fc ab 1f 7e 28 83 94 14 9b 99 d8 b1 9d 40 fa
    85 14 bb 3e 68 7e 05 f1 02 20 4a ae b5 b1 f9 bb
    4e 86 ee 81 47 09 79 7a e9 76 ae c3 39 f2 af e8
    d2 46 c7 73 74 4d c2 68 e8 a7 00 02 31 30 82 02
    2d 30 82 01 d0 a0 03 02 01 02 02 06 01 78 fd f5
    29 17 30 0c 06 08 2a 81 1c cf 55 01 83 75 05 00
    30 4b 31 0b 30 09 06 03 55 04 06 13 02 43 4e 31
    0e 30 0c 06 03 55 04 0a 13 05 47 4d 53 53 4c 31
    10 30 0e 06 03 55 04 0b 13 07 50 4b 49 2f 53 4d
    32 31 1a 30 18 06 03 55 04 03 13 11 4d 69 64 64
    6c 65 43 41 20 66 6f 72 20 54 65 73 74 30 22 18
    0f 32 30 32 31 30 34 32 32 31 36 30 30 30 30 5a
    18 0f 32 30 32 32 30 34 32 32 31 36 30 30 30 30
    5a 30 7e 31 0b 30 09 06 03 55 04 06 13 02 43 4e
    31 10 30 0e 06 03 55 04 08 13 07 62 65 69 6a 69
    6e 67 31 10 30 0e 06 03 55 04 07 13 07 73 68 61
    6e 67 64 69 31 0c 30 0a 06 03 55 04 0a 13 03 61
    63 67 31 0e 30 0c 06 03 55 04 0b 13 05 62 61 69
    64 75 31 0e 30 0c 06 03 55 04 03 13 05 62 61 69
    64 75 31 1d 30 1b 06 09 2a 86 48 86 f7 0d 01 09
    01 16 0e 74 65 73 74 40 62 61 69 64 75 2e 63 6f
    6d 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08
    2a 81 1c cf 55 01 82 2d 03 42 00 04 83 f1 c9 77
    98 42 a6 1b bd e0 cf d5 9a 55 e3 7e 51 62 ca 7d
    2b 9f 44 0f 06 ff fb d0 ae 7e da 42 71 3d c0 7e
    74 fc b0 a5 b5 0e d8 49 18 29 7a 31 91 ee 8c 82
    5a 60 5a b5 3a 60 62 26 63 6f b0 89 a3 67 30 65
    30 1b 06 03 55 1d 23 04 14 30 12 80 10 f9 7f 55
    b4 27 94 33 62 a6 56 ca 6f cc 5d 1a ff 30 19 06
    03 55 1d 0e 04 12 04 10 72 19 ac 18 83 1e 40 2f
    a5 e2 91 86 82 bc 5d 18 30 10 06 03 55 1d 11 04
    09 30 07 82 05 62 61 69 64 75 30 09 06 03 55 1d
    13 04 02 30 00 30 0e 06 03 55 1d 0f 01 01 ff 04
    04 03 02 00 38 30 0c 06 08 2a 81 1c cf 55 01 83
    75 05 00 03 49 00 30 46 02 21 00 e5 2b fe 06 d2
    58 de 64 65 1d a4 48 dd b2 b0 a4 c0 7e b5 e3 d8
    51 25 7b 08 99 97 d9 7d d7 4b 18 02 21 00 ff 83
    d6 6e d4 fa e5 34 e2 64 de 78 4a c0 9d 6b 97 5c
    0f 81 1c f9 3f 24 8e 56 18 cc 5b fb a0 ba
gmssl(95872,0x11287edc0) malloc: *** error for object 0x104a0a19d: pointer being freed was not allocated
gmssl(95872,0x11287edc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Expected behavior**
core should not happen

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by changenamee** [comment]
你好，请问这个问题解决了嘛
