### ISSUE TITLE
请问下怎么在Java的SSL请求中使用Gmssl的密码套件

### ISSUE THREAD

**Issue by Donnyda** [guanzhi/GmSSL#1095]
服务器端使用C语言，修改SSL增加引擎然后支持Gmssl，但是JAVA的SSL SOCKET该怎么支持GmSSL呢

**Comment by SAMOxtan** [comment]
我现在也是有GmSSL支持JAVA的SSLsocket的需求，请问你解决了吗

**Comment by zhk56** [comment]
> 我现在也是有GmSSL支持JAVA的SSLsocket的需求，请问你解决了吗



> 我现在也是有GmSSL支持JAVA的SSLsocket的需求，请问你解决了吗

我现在也有这个问题,你解决了么,可否帮我解答疑惑
