### ISSUE TITLE
SSL套件中实现了SM2密钥交换协议吗

### ISSUE THREAD

**Issue by jiangbinghua** [guanzhi/GmSSL#1100]
我在SSL套件中找到了ECDH密钥交换接口，但是SM2密钥交换接口SM2_compute_share_key、SM2_compute_key都没有实现，请问SM2密钥交换是用其它方式或接口实现吗，还是目前暂不支持在SSL套件中使用SM2密钥交换？

**Comment by zhenyuwei** [comment]
参考标准自己添加呗，流程都已经有了，就是按照标准给实现就可以了
