### ISSUE TITLE
chromium怎么使用Gmssl

### ISSUE THREAD

**Issue by hk520570** [guanzhi/GmSSL#1103]
请问怎么将chromium中boringssl替换成gmssl，或者说共存呢?

**Comment by zhenyuwei** [comment]
Chrome有自己的boringssl ，使用boringssl支持更稳定的。

**Comment by hk520570** [comment]
> Chrome有自己的boringssl ，使用boringssl支持更稳定的。

谢谢，只是我们原来使用了openssl【改动比较多】，想要看下怎么结合比较方便点

**Comment by pgzhanglin** [comment]
> 请问怎么将chromium中boringssl替换成gmssl，或者说共存呢?
目前我也想使用GmSSL，使浏览器支持国密，正在调研探索阶段

**Comment by zhenyuwei** [comment]
> > 请问怎么将chromium中boringssl替换成gmssl，或者说共存呢?
> > 目前我也想使用GmSSL，使浏览器支持国密，正在调研探索阶段
在boringssl改，后续版本升级和维护的成本很低的，而且原生的支持性能和稳定性比openssl高的。

**Comment by zhenyuwei** [comment]
> > 请问怎么将chromium中boringssl替换成gmssl，或者说共存呢?
> > 目前我也想使用GmSSL，使浏览器支持国密，正在调研探索阶段

建议在boringssl上修改，其实改动量很小的

**Comment by ZyLin-ux** [comment]
> > > 请问怎么将chromium中boringssl替换成gmssl，或者说共存呢?
> > > 目前我也想使用GmSSL，使浏览器支持国密，正在调研探索阶段
> 
> 建议在boringssl上修改，其实改动量很小的

是嘛，感谢提供思路，我这边还是先恶补一下这方面的知识，尽量不问太小白的问题。您是有相关经验吗？

**Comment by zhenyuwei** [comment]
> 是嘛，感谢提供思路，我这边还是先恶补一下这方面的知识，尽量不问太小白的问题。您是有相关经验吗？

如果你想用GmSSL的代码，就在chromium的thrid_party目录下添加对应的代码目录，修改编译参数就可以使用了。在boringssl修改其实就是简单的加个国密代码，你可以参考GmSSL的实现，把相关代码移植到boringssl就可以了。

**Comment by ZyLin-ux** [comment]
> 如果你想用GmSSL的代码，就在chromium的thrid_party目录下添加对应的代码目录，修改编译参数就可以使用了。在boringssl修改其实就是简单的加个国密代码，你可以参考GmSSL的实现，把相关代码移植到boringssl就可以了。

好的，特别感谢您提供方向。
