### ISSUE TITLE
请问当前GMSSL在SSL握手实现上对SSLVPN国密标准中指定的算法套件支持如何

### ISSUE THREAD

**Issue by AivenYoung** [guanzhi/GmSSL#111]
老师您好：
       通过阅读GMSSL首页和相关Issues的解答，我了解到当前GMSSL对SSL握手支持SSLVPN国密算法套件等功能还在开发当中，我从最新的GMSSL代码中看到已经存在大概的框架和定义，请问当前是否存在已经支持的SSLVPN国密标准算法套件呢？SSL握手是否完整，能与如360国密版浏览器互联调试吗？

**Comment by guanzhi** [comment]
目前不支持SSL VPN协议

**Comment by AivenYoung** [comment]
@guanzhi 老师您好，请问，SSLVPN标准里面TLS握手协商也没有吗，我查看当前是有GMSSLv1_method的，只是实现不完全，正在开发中，是这样子吗？
