### ISSUE TITLE
关于SM2_set_id的讨论

### ISSUE THREAD

**Issue by gujinqiangggs** [guanzhi/GmSSL#112]
@guanzhi 关于SM2_set_id 这个我有一点想法，不知是否正确？ 
int SM2_set_id(EC_KEY *ec_key, const char *id)字面理解应该为设置一个id到ec_key中，但是当传入的ec_key中已经存在数据时，就会返回错误，而不管存在的id是否为我要设置的id。我认为这不能算一个真正意义上的错误，而应该修改逻辑，判断一下这个ec_key中对应的函数指针映射的data是不是就是我要设置的这个id，如果是的话，那么应该返回成功。如果不是，才应该返回失败。另外，EC_KEY_insert_key_method_data()中已经调用了EC_KEY_get_key_method_data()进行判断，所以没有必要再在SM2_set_id()中进行判断。修改后如下：
int SM2_set_id(EC_KEY *ec_key, const char *id)
{
	char *pid;
	if (strlen(id) > SM2_MAX_ID_LENGTH) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}

	/*if ((pid = EC_KEY_get_key_method_data(ec_key, sm2_data_dup,
		sm2_data_free, sm2_data_free)) != NULL) {
		if(strncmp(pid, "1234567812345678", 16) ==  0) return 1; //modify by ggs 
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}*/

	if (!(pid = OPENSSL_strdup(id))) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}

	void *tmp_pid = EC_KEY_insert_key_method_data(ec_key, pid, sm2_data_dup, sm2_data_free, sm2_data_free);
	if(tmp_pid == NULL)
		return 1;
	else{
		if (strcmp(tmp_pid, pid)!= 0) {
			fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
			//ERR_print_errors_fp(stderr);
			//OPENSSL_free(pid);
			return 0;
		}
	}
	return 1;
}

**Comment by guanzhi** [comment]
v1.3.0中将id作为EC_KEY的一个属性，通过SM2_set_id设定。这部分没有提供对应的clear_id的功能，功能上不完整。你设定的逻辑当然也没有问题。

主要的问题是，新的2.0不再支持往EC_KEY中插入id了，因为id等属性从逻辑上并不属于EC_KEY。从整体上也不打算支持默认的Z值计算了，当然实现和调用接口还是提供的。
