### ISSUE TITLE
nginx 获取不到SNI

### ISSUE THREAD

**Issue by soulbird** [guanzhi/GmSSL#1129]
在使用GMSSL结合Nginx搭建Web服务的过程中， 发现GMSSL无法解析ClientHello扩展中的ServerNme（即：SNI）

  在代码 ssl/statem_srvr.c +1299行
```
   /* TLS extensions */
    if (s->version >= SSL3_VERSION) {
        if (!ssl_parse_clienthello_tlsext(s, &extensions)) {
            SSLerr(SSL_F_TLS_PROCESS_CLIENT_HELLO, SSL_R_PARSE_TLSEXT);
            goto err;
        }
    }
```
 其中 SSL3_VERSION定义：
```
# define SSL3_VERSION                    0x0300
# define SSL3_VERSION_MAJOR              0x03
# define SSL3_VERSION_MINOR              0x00
```
而 GMTLS1_1_VERSION定义：
```
# define GMTLS1_VERSION     0x0100
# define GMTLS1_VERSION_MAJOR   0x01
# define GMTLS1_VERSION_MINOR   0x00
# define GMTLS1_1_VERSION   0x0101
# define GMTLS1_1_VERSION_MAJOR 0x01
# define GMTLS1_1_VERSION_MINOR 0x01
# define GMTLS_VERSION      GMTLS1_1_VERSION
# define GMTLS_VERSION_MAJOR    GMTLS1_1_VERSION_MAJOR
# define GMTLS_VERSOIN_MINOR    GMTLS1_1_VERSION_MINOR
```
 
这将导致函数```ssl_parse_clienthello_tlsext``` 无法进入，从而使函数```SSL_get_servername```无法获取到SNI。

环境描述：

GMSSL version： master（commit fc8ac63a72daea1eb37fb7908a284906d2e30f86）
Nginx version： v1.15.8
浏览器： 奇安信可信浏览器 V1.1.32932.15

**Comment by JasonHuangYa** [comment]
是的，我们也遇到了同样的问题。

**Comment by soulbird** [comment]
mark

**Comment by soulbird** [comment]
通过调整代码， 已支持SNI的获取。出现了关于https seesion崩溃的问题， 已修复。持续观察中

**Comment by ChaosExplorer** [comment]
> 通过调整代码， 已支持SNI的获取。出现了关于https seesion崩溃的问题， 已修复。持续观察中

请问在哪次commit id 提交的啊？

**Comment by soulbird** [comment]
在自己的代码库调整的，没有提交

**Comment by soulbird** [comment]
> > 通过调整代码， 已支持SNI的获取。出现了关于https seesion崩溃的问题， 已修复。持续观察中
> 
> 请问在哪次commit id 提交的啊？

在自己的代码库调整的，没有提交
