### ISSUE TITLE
启动skfeng找不到e_skf.c

### ISSUE THREAD

**Issue by yzqxmuex** [guanzhi/GmSSL#1131]
**Describe the bug**
./Configure enable-skfeng 之后进行make 编译会出错，在engine中找不到e_skf.c

**Comment by stardrift1** [comment]
请问找到原因了吗，是不是代码还没开发完成？

**Comment by 403705726** [comment]
碰到同样的问题，请问你们解决了吗

**Comment by fidderdan** [comment]
引擎需要和不同的硬件进行是适配，需要自己开发或者定制开发。

**Comment by changguangsheng** [comment]
> 引擎需要和不同的硬件进行是适配，需要自己开发或者定制开发。

您好，能添加您联系方式，询问您一些关于skf sdf的相关问题么

**Comment by fidderdan** [comment]
523665380@qq.com

**Comment by yzqxmuex** [comment]
哇靠，你还没搞定吗，我都送检结束了，设备端和平台端都送完了













杨智勤


***@***.***







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: stardrift1  ***@***.***>
 

 
 发送时间: 2021-11-05 11:40:58
 

 
 收件人:guanzhi/GmSSL ***@***.***> 

 
 抄送:13666070503 ***@***.***>,Author ***@***.***> 

 
 主题: Re: [guanzhi/GmSSL] 启动skfeng找不到e_skf.c (#1131)
 





 请问找到原因了吗，是不是代码还没开发完成？

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
