### ISSUE TITLE
用release提供的浏览器，服务端证书过期还可以访问？

### ISSUE THREAD

**Issue by xuzhaofangxzf** [guanzhi/GmSSL#1133]
如上，采用GMBrowser v0.1的浏览器访问通过gmssl编译的nginx，nginx版本1.21.1，
生成的自签名证书是过期的证书，但是采用浏览器访问仍可以正常访问，但是用自己编译的IOS及安卓客户端却不能访问。请问这个是正常的吗？

**Comment by yuanjilee** [comment]
你是移动端开启了 SSL 证书验证吧， 设置为 0L 也可以访问的。猜测是不是浏览器没有验证自签名证书，因为你都没有设置公钥给浏览器
