### ISSUE TITLE
GmSSL无法在CentOS 7.6上正常安装和使用

### ISSUE THREAD

**Issue by jadezhong** [guanzhi/GmSSL#1139]
**Describe the bug**
按照“快速上手”和 http://gmssl.org/docs/install.html 的步骤安装，在执行gmssl version的时候报“gmssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory”错误，请求帮助！

**Expected behavior**

**Screenshots**

**Environments**
- OS: CentOS 7.6
- Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Additional context**

**Comment by littlelearnlive** [comment]
你好，这个问题应该是libssl.so.1.1文件没有放到1你系统查找的目录下，可以先find / -name libssl.so.1.1查找这个文件。我之前遇到这个问题的时候，libssl.so.1.1文件是在/usr/lib/目录下，我链接到/usr/lib664/目录下就可以了。
你可以试一下
