### ISSUE TITLE
GMSSL 在 MariaDB 中与openssl版本冲突问题

### ISSUE THREAD

**Issue by flyasolo** [guanzhi/GmSSL#1141]
目前在数据库自定义插件中需要使用gmssl提供的函数，我是以静态库的形式编译了gmssl，但是在调用的时候发现和系统中自带的openssl版本冲突（gmssl基于1.1.0d开发，环境中的是1.1.1版本），默认调用的也是openssl中的方法，请问大家这个问题怎么解决？

**Comment by richard2218** [comment]
最好是重新编译mariadb，指定ssl的路径为gmssl的路径

**Comment by veniwang** [comment]
> 最好是重新编译mariadb，指定ssl的路径为gmssl的路径

在iOS上，我们依赖了一些第三方库（如用于支付的SDK，已基于openssl1.1.1库进行过改造）。目前最新GMSSL版本一定会与其冲突，有没有一种办法，使第三方库不改动，也能加入GMSSL静态库？
