### ISSUE TITLE
engine下e_sdf.c和e_skf.c不存在

### ISSUE THREAD

**Issue by Findlyzhu** [guanzhi/GmSSL#1147]
您好，在执行./config enable-sdfeng enable-skfeng后，编译时提示e_sdf.c和e_skf.c不存在，查看源码确实不存在 请问下engine下的e_sdf.c和e_skf.c不是开源的吗，是需要付费？

**Comment by Findlyzhu** [comment]
刚看到帖子说是收费的，请问如何收费

**Comment by fidderdan** [comment]
引擎代码需要自己开发，且需要和硬件接口适配。我们就是自己开发的。

**Comment by Findlyzhu** [comment]
>  引擎代码需要自己开发，且需要和硬件接口适配。我们就是自己开发的。

关键我适配了对称和摘要的SDF接口到engine中了，RSA的相关接口有点不太明白，SDF中对公钥的操作都是加密操作，而私钥都是解密操作吗，engine中需要设置公钥加密和解密，私钥加密和解密的操作，这个这么转换呢

**Comment by Findlyzhu** [comment]
>  引擎代码需要自己开发，且需要和硬件接口适配。我们就是自己开发的。

可以方便留您的联系方式，请教一下吗？

**Comment by Findlyzhu** [comment]
已经自己适配完成，关闭此问题

**Comment by YangShizhao** [comment]
> 已经自己适配完成，关闭此问题

你好，可以请问下你是怎么适配SDF接口的嘛？我有个SKF的接口动态库，也想对接上GMSSL的库，但是现在不清楚应该怎么做

**Comment by Findlyzhu** [comment]
根据SKF的接口对接到engine的接口上，完成对称，非堆成（RSA/ECC）,摘要的算法中间价适配，具体的engine的用例，网上有很多，然后根据你SKF的API进行二次开发



在 2022-01-11 10:39:46，"展昭" ***@***.***> 写道：

已经自己适配完成，关闭此问题

你好，可以请问下你是怎么适配SDF接口的嘛？我有个SKF的接口动态库，也想对接上GMSSL的库，但是现在不清楚应该怎么做

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
