### ISSUE TITLE
关于GmSSL提供的国密算法相关问题的咨询

### ISSUE THREAD

**Issue by Rafaelxue** [guanzhi/GmSSL#1148]
GmSSL项目组的老师们好，
目前我们需要对自研系统进行国密改造，我们的自研系统之前都是采用的OpenSSL里面的RSA/MD5/AES/DES等算法，现在我们将这些算法替换为GmSSL里面的SM2/SM3/SM4等算法，然后整理方案后参与行业的国密密评，行业之前出了相关文件，提到国密改造当中，密码算法是否取得国家密码管理部门同意其使用的证明文件，**我这里想询问的就是GmSSL里面的国密算法是否是取得了国家密码管理部门同意使用的证明文件**

**Comment by rikimeow** [comment]
这当然没有这样的文件，开源组件还能拿去过密评？能过密评的只有通过产品检测的密码产品，过检测产品都是有检测成本和时间成本的👀
