### ISSUE TITLE
编译gmssl出问题：ms\do_ms

### ISSUE THREAD

**Issue by AnndyH** [guanzhi/GmSSL#115]
下载最新版本的gmssl之后，编译时候，在ms文件夹之下并没有do_ms.bat或者do_win64a.bat等文件，所以执行ms\do_ms会出错，而在opnssl编译时，ms下有这些文件。请问该怎么解决？

**Comment by sslvpn007** [comment]
现在不支持win吧。

**Comment by AnndyH** [comment]
但是在网站http://gmssl.org/docs/install.html 上面是有windows编译的，然而并编译不了

**Comment by epuxilong** [comment]
在ubuntu上编译通过了， 在windows上遇到了类似的问题， 楼主解决了吗？

**Comment by pandongzi1980** [comment]
windows下能编吗？
