### ISSUE TITLE
按照官网的编译要求,一定编译报错,按照网友的要求,编译成功

### ISSUE THREAD

**Issue by Vzz1c** [guanzhi/GmSSL#1152]

**Comment by YangShizhao** [comment]
建议官方更新下文档信息，我这边根据官网的流程发现的两个问题，在网上都能找到大量的相同issue，应该不是个例。在configure流程有两个问题，1个是glob相关问题，另一个是NSAM问题；另一个是编译的时候，也会因为sam导致编译失败。

**Comment by xcw233** [comment]
官网太草率了

**Comment by YangShizhao** [comment]
> 官网太草率了

可能还是维护的人太少了，国密目前确实用的不多，另外真正做密码的人也不会用开源库，还是自己写的代码
