### ISSUE TITLE
gmssl+nginx1.8.0 在速龙浏览器中访问报错 ssl3_read_bytes:sslv3 alert bad record Mac

### ISSUE THREAD

**Issue by Vampire688** [guanzhi/GmSSL#1155]
编译gmssl+nginx1.8.0 在速龙浏览器中访问报错 ssl3_read_bytes:sslv3 alert bad record Mac，经定位是在ssl3_get_record的CRYPTO_memcmp(md, mac, (size_t)mac_size)不匹配导致的失败。
请问有大神可以解答一下该如何修改吗？

**Comment by syr-1** [comment]
请问这个问题最终解决了吗，我们也遇到了同样的问题

**Comment by syr-1** [comment]
> 编译gmssl+nginx1.8.0 在速龙浏览器中访问报错 ssl3_read_bytes:sslv3 alert bad record Mac，经定位是在ssl3_get_record的CRYPTO_memcmp(md, mac, (size_t)mac_size)不匹配导致的失败。 请问有大神可以解答一下该如何修改吗？

请问这个问题最终解决了吗，我们也遇到了同样的问题

**Comment by 403705726** [comment]
请问这个问题解决了吗，我也碰到同样问题gmssl2.5.4版本，是不是ssl中使用的encrypt_then_mac模式和对端不匹配阿
