### ISSUE TITLE
[emerg] invalid value GMTLS

### ISSUE THREAD

**Issue by majorinche** [guanzhi/GmSSL#1156]
https://www.freesion.com/article/19881394415/
按照这里编译的nginx，配置的ssl_protocols
ssl_protocols TLSv1.2 TLSv1.3 GMTLS;

但是启动nginx时会报错
[root@node14 ~]# /usr/local/nginxgm/sbin/nginx -t
nginx: [emerg] invalid value "GMTLS" in /usr/local/nginxgm/conf/nginx.conf:42
nginx: configuration file /usr/local/nginxgm/conf/nginx.conf test failed

什么原因呢？

**Comment by soulbird** [comment]
不用配置GMTLS就可以直接用， 原生nginx配置和gmssl就可以了

**Comment by majorinche** [comment]
不用也可以啊，那文档还那样写，弄了好久。

请问下，有没有什么正确的实现方案，可以给个链接看看不

**Comment by soulbird** [comment]
直接编译ngxin， --with-openssl=$gmssl  就可以用了

**Comment by majorinche** [comment]
浏览器不能访问是怎么回事？报这个错
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by CirillaQL** [comment]
需要使用支持国密的浏览器，目前可以用360企业安全浏览器，在证书管理平台导入CA

**Comment by yp2017** [comment]
有个问题：nginx的出方向协议无法通过配置指定为国密TLS，导致多个nginx串起来后，后面只能被迫走TLSv1.3及以下协议。建议：
1、ssl_protocols增加显性的国密TLS协议配置，本身国密TLS的id和TLSv1.3、TLSv1.2等不同。
2、proxy_ssl_protocols增加显性的国密TLS协议配置，保证nginx出方向可选择国密TLS。
