### ISSUE TITLE
Local var "b" not released in point_is_on_curve function in sm9_rate.c

### ISSUE THREAD

**Issue by shanzhashu** [guanzhi/GmSSL#1159]
In sm9_rate.c, line 1934, function point_is_on_curve 

There's 4 local variables fp2_t x, y, b, t;
Each is init by fp2_init

But at end: label, only x, y, t are released by fp2_cleanup
b not released.

**Comment by shanzhashu** [comment]
function eval_tangent and eval_line in sm9_rate.c also have the same problems.

**Comment by shanzhashu** [comment]
新的一年了，还有人维护不？

**Comment by guanzhi** [comment]
v2的SM9代码不再维护了
