### ISSUE TITLE
命名空间建议

### ISSUE THREAD

**Issue by h27109** [guanzhi/GmSSL#1170]
我们使用GMSSL做国密相关的功能时候，它与我们使用的openssl动态库(1.0.1D)的函数名冲突了。我们想尽量小范围的使用GMSSL的国密部分功能，其他原有功能使用openssl的。
现在这个问题的解决我想有三个：
1，GMSSL采用新的namespace。
2，全部用GMSSL替换我们现在使用的openssl。这样风险有点大，因为基础代码使用的老的openssl的动态库。
3，用dlopen/dlsym手工调用函数。这样会增加大很大的工作量，每个调用的库的函数都再做一次包装。
建议看下GMSSL是不是可以用namespace包装一下？

**Comment by sunxinsara** [comment]
我个人感觉GMSSL是基于C实现的，添加命名空间并不现实。
但他可以添加导出符号的链接版本，使用者可以通过指定函数版本进行链接。

我们在遇到这个问题时的解决方案，是更改冲突符号的命名。可以参考ld 和 objcopy的使用说明
