### ISSUE TITLE
编译php7.4的gmssl扩展各种问题

### ISSUE THREAD

**Issue by ddjuly** [guanzhi/GmSSL#1173]
ext/openssl/openssl.o: In function `php_openssl_get_evp_cipher_from_algo':
/home/gmssl/php-7.4.28/ext/openssl/openssl.c:1452: undefined reference to `EVP_sms4_cbc'
collect2: error: ld returned 1 exit status
make: *** [Makefile:284：sapi/cli/php] 错误 1

**Comment by guanzhi** [comment]
目前v3主项目中暂不支持PHP扩展
