### ISSUE TITLE
SM9算法支持情况

### ISSUE THREAD

**Issue by tonyw1989** [guanzhi/GmSSL#118]
我看sm9setup.c  168~172中
	/* set mpk->g1 = e(P1, Ppub) */
	//TODO

	/* set mpk->g2 = e(Ppub, P2) */
	//TODO
请问是否双线性映射算法尚未实现？
如果想把sm9算法编译进去，是否需要config怎样的参数？谢谢~

**Comment by guanzhi** [comment]
./config enable-sm9
