### ISSUE TITLE
【3.x版本】是否计划以某种方式实现`通过openssl的api使用gmssl`？

### ISSUE THREAD

**Issue by daipingh** [guanzhi/GmSSL#1180]
换句话说，我期望在不改动如nginx等组件源码的情况下，集成新版本gmssl以支持国密相关套件（包含双证书套件、单证书套件、skf/sdf等），这是否在新版gmssl的规划线路考虑之中？
一个预想中的方案是，稍微改造openssl源码，并在openssl编译时链接gmssl（或以插件方式？），以api透明的方式为应用程序提供国密相关支持，这是否存在可行性？

**Comment by guanzhi** [comment]
对于nginx这类重要应用，我们希望以直接给这些项目提供gmssl patch的方式来支持gmssl的新API。目前针对nginx的patch已初步完成，稍后会以一个独立项目的方式开源。对更多项目的支持，我们希望能够有志愿者可以贡献代码。
