### ISSUE TITLE
SM9主密钥导出PEM是否没有实现？如果要导出并且存储的话。有方案吗？

### ISSUE THREAD

**Issue by DWFLZXJ** [guanzhi/GmSSL#1184]
想要导出pem格式的主密钥。但是看了下代码好像没有实现啊。我是个java开发。java组织pem倒是会。用c就。。。有没有大佬实现的分享下。

**Comment by guanzhi** [comment]
当前版本已经支持SM9主密钥的口令加密PEM格式导出，请参考
https://github.com/guanzhi/GmSSL/blob/develop/demos/sm9demo.sh
