### ISSUE TITLE
Gmssl 代码下载后，make时报错 error: initializer element is not constant

### ISSUE THREAD

**Issue by zuoriqiufeng** [guanzhi/GmSSL#1185]
![image](https://user-images.githubusercontent.com/57280161/161418776-abb7668d-5543-4baf-89d1-5d0954a2ad82.png)

**Comment by taochuanhui** [comment]
不知道你现在是否已经解决了

cmake默认使用了gcc进行编译，而这个报错是c语言的语法规定

改用g++即可

**Comment by racebin** [comment]
> 不知道你现在是否已经解决了
> 
> cmake默认使用了gcc进行编译，而这个报错是c语言的语法规定
> 
> 改用g++即可

你好，在cmakelists.txt里添加了set(CMAKE_CXX_COMPILER "g++")还是出这个错。

**Comment by racebin** [comment]
可以更新gcc的版本，就会解决此问题。

**Comment by zhaoxiaomeng** [comment]
升级到最新版本的GCC以及G++即可解决这个问题。我这边是gcc-11 g++11

**Comment by ganzhigang** [comment]
使用GCC-11.2.0编译，依然存在上述问题

**Comment by zhaoxiaomeng** [comment]
@ganzhigang 请问操作系统和编译器的具体版本号，以及错误代码是什么？谢谢

**Comment by guanzhi** [comment]
该问题已修正
