### ISSUE TITLE
make test failed问题

### ISSUE THREAD

**Issue by hezhenhong** [guanzhi/GmSSL#1189]
make test x509_ext 会报错
<img width="665" alt="image" src="https://user-images.githubusercontent.com/40795177/163308498-1af4a3ec-1aa9-4b6d-a16f-dbe3f6255d21.png">

**Comment by guanzhi** [comment]
开发过程中会出现自测不通过的情况，如果在常规的OS和处理器上可以测试成功，但是在特殊的系统上测试失败，请报告您的测试环境
