### ISSUE TITLE
国密SM2大素数怎么选取？

### ISSUE THREAD

**Issue by francliu** [guanzhi/GmSSL#119]
@guanzhi 请问他可以使用ecc的大素数来计算国密吗？

**Comment by guanzhi** [comment]
`gmssl ecparam -list_curves` 可以列出所有曲线，对于SM2均可以使用
`gmssl ecparam -name <curve-name> -text -param_enc explicit` 可以打印曲线详细参数，其中Prime为大素数

**Comment by francliu** [comment]
@guanzhi 谢谢您，我是用了之后，看到的大素数与国密标准192位例子里面的不一样，那么secp192k1这个素数也可以当做国密的素数吗？

**Comment by guanzhi** [comment]
不建议使用例子里的参数。
secp192k1是可用的。

**Comment by francliu** [comment]
@guanzhi 谢谢您，不过我发现打素数25个字节，不是24个，还有G点，order等都多一个字节，如下图：
![192](https://cloud.githubusercontent.com/assets/7529927/24086569/8b5ec1f8-0d4c-11e7-9af3-822be5204c80.png)

**Comment by francliu** [comment]
@guanzhi 谢谢您了，我找到原因了，但是我有个问题，secp192k1是ecc的大素数，如果用在sm2上，他还是sm2吗？

**Comment by liu198520000** [comment]
@francliu ，sm2当前必须选用推荐曲线，其他曲线没有经过国密认证。
