### ISSUE TITLE
gmssl 3.0版本，sm2_encrypt 加密为什么限制加密的数据长度要小于255字节

### ISSUE THREAD

**Issue by qingfeng1992** [guanzhi/GmSSL#1190]
int sm2_encrypt(const SM2_KEY *key, const uint8_t *in, size_t inlen, uint8_t *out, size_t *outlen)
{
	SM2_CIPHERTEXT C;

	if (!key || !in || !out || !outlen) {
		error_print();
		return -1;
	}
	if (inlen < SM2_MIN_PLAINTEXT_SIZE || inlen > SM2_MAX_PLAINTEXT_SIZE) {
		error_print();
		return -1;
	}
	if (sm2_do_encrypt(key, in, inlen, &C) != 1) {
		error_print();
		return -1;
	}
	*outlen = 0;
	if (sm2_ciphertext_to_der(&C, &out, outlen) != 1) {
		error_print();
		return -1;
	}
	return 1;
}
为什么输入的数据长度要小于255字节（SM2_MAX_PLAINTEXT_SIZE 定义为255），正常来说，加密的数据长度都会比这个255字节要长，目前3.0版本还没开发完成吗

**Comment by wxiaoguang** [comment]
因为 SM2_CIPHERTEXT 结构是固定死的，SM2_CIPHERTEXT 里面的 buffer 只有 SM2_MAX_PLAINTEXT_SIZE 这么大，而 sm2_encrypt 又必须用这个 buffer ，所以这里就是个硬限制。

**Comment by qingfeng1992** [comment]
> 因为 SM2_CIPHERTEXT 结构是固定死的，SM2_CIPHERTEXT 里面的 buffer 只有 SM2_MAX_PLAINTEXT_SIZE 这么大，而 sm2_encrypt 又必须用这个 buffer ，所以这里就是个硬限制。

那可以把SM2_MAX_PLAINTEXT_SIZE 这个buffer定大一点吗，一般来说，255字节都太小了，我看到你们master分支的sm2加密函数，限制的大小是小于65535字节的，下面是master分支的sm2加密函数代码：
============================================
SM2CiphertextValue *SM2_do_encrypt(const EVP_MD *md,
	const unsigned char *in, size_t inlen, EC_KEY *ec_key)
{
	SM2CiphertextValue *ret = NULL;
	SM2CiphertextValue *cv = NULL;
	const EC_GROUP *group;
	const EC_POINT *pub_key;
	KDF_FUNC kdf;
	EC_POINT *ephem_point = NULL;
	EC_POINT *share_point = NULL;
	BIGNUM *n = NULL;
	BIGNUM *h = NULL;
	BIGNUM *k = NULL;
	BN_CTX *bn_ctx = NULL;
	EVP_MD_CTX *md_ctx = NULL;

	unsigned char buf[(OPENSSL_ECC_MAX_FIELD_BITS + 7)/4 + 1];
	int nbytes;
	size_t len;
	size_t i;
	unsigned int hashlen;

	/* check arguments */
	if (!md || !in || !ec_key) {
		SM2err(SM2_F_SM2_DO_ENCRYPT, ERR_R_PASSED_NULL_PARAMETER);
		return 0;
	}

	if (inlen <= 0 || inlen > SM2_MAX_PLAINTEXT_LENGTH) {
		SM2err(SM2_F_SM2_DO_ENCRYPT, SM2_R_INVALID_PLAINTEXT_LENGTH);
		return 0;
	}

=============================
以上代码SM2_MAX_PLAINTEXT_LENGTH的值为65535

**Comment by wxiaoguang** [comment]
我不是开发者。只是路过碰巧看看。

**Comment by qingfeng1992** [comment]
> 我不是开发者。只是路过碰巧看看。
> 
> ps: 一味的增加数组大小是不可行的。需要设计一套可行的内存使用机制。

这我也知道，但是为什么定那么小的长度，一般的使用都不会加密那么少的数据，我在想是不是长数据要我们自己分块加密，我对这个算法也不是很了解

**Comment by daipingh** [comment]
> > 我不是开发者。只是路过碰巧看看。
> > ps: 一味的增加数组大小是不可行的。需要设计一套可行的内存使用机制。
> 
> 这我也知道，但是为什么定那么小的长度，一般的使用都不会加密那么少的数据，我在想是不是长数据要我们自己分块加密，我对这个算法也不是很了解

- 非对称算法的 加密/解密 接口一般用于密钥交换，密钥交换数据量不会很大。
- 对数据的加密一般不会直接使用 非对称加密算法 来加密，而是推荐使用对称加密算法来加密，对称加密算法的密钥使用非对称加密算法进行加密保护。
- 如果确实要使用 非对称密码算法 对应用数据进行加密/解密，可以自行扩展实现（如你所说进行分块加密）

**Comment by guanzhi** [comment]
GmSSL中SM2和SM9加密应只用于加密较短的对称密钥，典型的长度如下：
* SM4-GCM密钥：16字节
* SM4密钥 + SM3-HMAC密钥：48字节
* SSL预主密钥：48字节

GmSSL中SM2的最大明文长度为`SM2_MAX_PLAINTEXT_SIZE`，SM9最大明文长度为`SM9_MAX_PLAINTEXT_SIZE`，开发者应检查输入明文的长度。

如果需要加密较长的数据，应使用SM4、ZUC算法或者CMS密文消息。

**Comment by hubo980205** [comment]
255太短了，推荐加密密钥使用，但是对接的平台就要求用公钥加密报文。这一帧报文怎么也10k以上，极端情况可能有1mb左右。这个限制太没必要了。

**Comment by hunter2009pf** [comment]
255实在是太短了，这个MAX_PALIN_TEXT_SIZE和MAX_CIPHER_TEXT_SIZE的对应关系式是什么啊？我简单修改了这2个值，发现长度还是被限制在255字节以内。

**Comment by zg-tips** [comment]
> 255实在是太短了，这个MAX_PALIN_TEXT_SIZE和MAX_CIPHER_TEXT_SIZE的对应关系式是什么啊？我简单修改了这2个值，发现长度还是被限制在255字节以内。

请问你的问题解决了吗？我最近也遇到了这个问题。

**Comment by h136799711** [comment]
只能把明文拆分成255字节的倍数，对每段多次加密了，密文长度 = 明文长度+ 96 字节
