### ISSUE TITLE
3.0 版本 编译安装后 gmssl命令行无法使用

### ISSUE THREAD

**Issue by He1loC** [guanzhi/GmSSL#1191]
/usr/local/bin 下也没有gmssl工具  基于arm64 还需要其他编译选项吗

**Comment by zhaoxiaomeng** [comment]
gmssl命令行工具目前没有在3.0版本中设计

**Comment by zhaoxiaomeng** [comment]
这是因为install的时候没有放在/usr/local/bin目录下，在make的时候bin目录下是有gmssl命令行工具的
