### ISSUE TITLE
gmssl v3.0不能在windows上编译

### ISSUE THREAD

**Issue by BigDev-Stack** [guanzhi/GmSSL#1199]
3.0版本会考虑兼容windows吗，未来是否会考虑跨平台

**Comment by dingdong005** [comment]
同样，建议说明里备注下环境。 Windows下很多错误。

**Comment by guanzhi** [comment]
兼容Visual Studio会放在 v3.1 版本中，VS是必须支持的主流平台。

**Comment by guanzhi** [comment]
当前版本支持Cygwin环境下的编译，安装Cygwin及cmake依赖的包（clang, make, cmake, unzip等），可以通过标准的cmake编译流程在Windows环境编译，并通过自测。

**Comment by Huihh** [comment]
@guanzhi 作者您好，我想问下 develop 分支的最新代码啥时可以支持在 Visual Studio 下编译，最近要使用这个，麻烦告知下或者怎样才能在 VS 下编译通过，目前编译产生一大堆问题，谢谢
