### ISSUE TITLE
AES 解密密钥生成bug，未初始化round

### ISSUE THREAD

**Issue by hz1624917200** [guanzhi/GmSSL#1206]
在`aes.c`文件中的`aes_set_decrypt_key` 函数，未将`struct AES_KEY`中`rounds`成员初始化，不可控的解密轮数将导致大概率的段错误。

**Comment by hz1624917200** [comment]
Solution: insert the code below in function `aes_set_decrypt_key`
```C
switch (keylen) {
	case AES128_KEY_SIZE:
		aes_key->rounds = 10;
		break;
	case AES192_KEY_SIZE:
		aes_key->rounds = 12;
		break;
	case AES256_KEY_SIZE:
		aes_key->rounds = 14;
		break;
	default:
		return 0;
	}
```

**Comment by guanzhi** [comment]
aes_set_decrypt_key 通过调用  aes_set_encrypt_key 实现了初始化

**Comment by hz1624917200** [comment]
![Screenshot 2022-05-08 112819](https://user-images.githubusercontent.com/23291572/167280488-951e5b3a-e382-4a20-8de3-e2718ffd04fe.png)
如图，实测已经经过调用，但是round仍未初始化。
在使用`aes_set_encrypt_key`返回的`enc_key`初始化`aes_key`时，没有把`round`成员赋值过来。
之前我的修改方法确实累赘，在原赋值后增加初始化round即可
```c
for (i = 0; i <= enc_key.rounds; i++) {
		aes_key->rk[4*i    ] = enc_key.rk[4*(enc_key.rounds - i)];
		aes_key->rk[4*i + 1] = enc_key.rk[4*(enc_key.rounds - i) + 1];
		aes_key->rk[4*i + 2] = enc_key.rk[4*(enc_key.rounds - i) + 2];
		aes_key->rk[4*i + 3] = enc_key.rk[4*(enc_key.rounds - i) + 3];
	}
	aes_key->rounds = enc_key.rounds;	// added
	ret = 1;
```
