### ISSUE TITLE
windows 环境下编译问题

### ISSUE THREAD

**Issue by dingdong005** [guanzhi/GmSSL#1207]
环境：win11+CLion+Cmake3.224

问题：
1、src\tlcp.c ：#include <arpa/inet.h>、#include <sys/socket.h> 、#include <netinet/in.h>文件找不到，也确实找不到相关文件夹和文件

**Comment by BigDev-Stack** [comment]
> 环境：win11+CLion+Cmake3.224
> 
> 问题： 1、src\tlcp.c ：#include <arpa/inet.h>、#include <sys/socket.h> 、#include <netinet/in.h>文件找不到，也确实找不到相关文件夹和文件

这些头文件是linux环境下才有的，windows肯定找不到

**Comment by BigDev-Stack** [comment]
> 环境：win11+CLion+Cmake3.224
> 
> 问题： 1、src\tlcp.c ：#include <arpa/inet.h>、#include <sys/socket.h> 、#include <netinet/in.h>文件找不到，也确实找不到相关文件夹和文件

我感觉gmssl v3.0似乎就是兼容linux，没考虑windows下的适配

**Comment by BigDev-Stack** [comment]
> 环境：win11+CLion+Cmake3.224
> 
> 问题： 1、src\tlcp.c ：#include <arpa/inet.h>、#include <sys/socket.h> 、#include <netinet/in.h>文件找不到，也确实找不到相关文件夹和文件

要不然用v2.5.4旧的代码也行，那个代码我试过可以在windows下编译使用

**Comment by guanzhi** [comment]
gmssl v3.0 目前ssl功能依赖posix socket，因此暂时不支持visual studio。
可以通过Cygwin等方式在Windows上编译。
对VS的支持会在 v3.1 这个版本完成。

**Comment by paipeng** [comment]
那个提交commit对应的是v2.5.4？我找不到branch、tag。提交说明也没看到。

还有请问计划v3.1版本的发布时间大概什么时候？

谢谢

**Comment by 841194253** [comment]
> > 环境：win11+CLion+Cmake3.224
> > 问题： 1、src\tlcp.c ：#include <arpa/inet.h>、#include <sys/socket.h> 、#include <netinet/in.h>文件找不到，也确实找不到相关文件夹和文件
> 
> 要不然用v2.5.4旧的代码也行，那个代码我试过可以在windows下编译使用

大佬麻烦问一下，您在cmake上运行也是重新写了一个cmake文件引入嘛

**Comment by guanzhi** [comment]
最新代码已经支持Windows下Visual Studio的编译，请参考源码根目录下的 INSTALL.md 编译说明。
