### ISSUE TITLE
 How does gmssl 3.0 support third-party hardware crypto device access

### ISSUE THREAD

**Issue by CaptainMiaow** [guanzhi/GmSSL#1208]
Hi! I noticed that GmSSL 3.0 no longer includes the ENGINE mechanism supported by GmSSL 2.0 after refactoring. I'd like to ask how the third-party hardware crypto device connects to GmSSL 3.0, then the user can use the hardware crypto device through GmSSL 3.0. Is there a follow-up support plan in this regard, or does the developer of the third-party hardware crypto device need to develop the corresponding framework themselves?

**Comment by guanzhi** [comment]
most recent updates support SDF crypto card.  Add `#include <gmssl/sdf.h>` to your source code, or use command line `gmssl sdfutil`. If you don't have a SDF crypto card. use the `sdf_dummy` dynamic library instead for trial.

**Comment by CaptainMiaow** [comment]
您发来的邮件已收到！

**Comment by CaptainMiaow** [comment]
thx!
