### ISSUE TITLE
请问怎么生成带密码的1024位sm2密钥对

### ISSUE THREAD

**Issue by worldask** [guanzhi/GmSSL#123]
请问怎么生成带密码的1024位sm2密钥对，文档上好像没有找到，谢谢

**Comment by guanzhi** [comment]
最多只能生成大概512位的SM2密钥，不过160位的安全性已经等价1024位的RSA了，通常还是用256位的比较好。如果希望生成以口令加密的密钥，需要使用pkcs12的功能。
http://gmssl.org/man/apps/pkcs12.html
