### ISSUE TITLE
怎么打包出iOS可以用的framework？

### ISSUE THREAD

**Issue by xiong1081** [guanzhi/GmSSL#1230]
目前在mac电脑上编译出的dylib是x86_64架构的。
Non-fat file: libgmssl.3.0.dylib is architecture: x86_64
想要编译出arm64架构的，要怎么操作？

**Comment by DukeHuang** [comment]
请问您有在iOS平台成功编译gmssl3.0吗

**Comment by sharpoc** [comment]
> 请问您有在iOS平台成功编译gmssl3.0吗

您好 ios平台的文件 您编译成功了吗

**Comment by guanzhi** [comment]
最近版本可以成功编译iOS/ARM的二进制代码，具体编译过程参考源代码根目录下的 INSTALL.md
