### ISSUE TITLE
V3 develop 类似这种代码uint8_t k[c2len + SM3_HMAC_SIZE];编译不过去。

### ISSUE THREAD

**Issue by suisou** [guanzhi/GmSSL#1236]
这个种动态长度的数组代码编译不过去。

**Comment by zhaoxiaomeng** [comment]
具体报什么错误呢？

**Comment by zhaoxiaomeng** [comment]
我更新编译强制要求c99了，您看现在可以编译通过么？ @suisou

**Comment by tuwulin365** [comment]
vs不支持可变长数组，最好还是改成malloc

**Comment by suisou** [comment]
我更新,仍然不通过,vs2022
uint8_t b64[datalen * 2];
报错如下：\_deps\gmssl-src\src\pem.c:60: error: C2057: 应输入常量表达式

**Comment by suisou** [comment]
> 我更新编译强制要求c99了，您看现在可以编译通过么？ @suisou

VS2022仍然编译通不过

**Comment by suisou** [comment]
@zhaoxiaomeng 查了一下，Visual Studio2022并不支持变长数组定义。
