### ISSUE TITLE
源码无法在Mingw上编译通过

### ISSUE THREAD

**Issue by ljx0305** [guanzhi/GmSSL#1245]
源码无法在Mingw上编译通过
gcc版本信息为
version 5.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)

**Comment by guanzhi** [comment]
这个项目配置了Cygwin的CI并且可以通过编译
https://github.com/guanzhi/GmSSL/actions/workflows/cygwin.yml

您可以对比一下配置差异，或者把具体的错误信息发出来。

**Comment by driver1998** [comment]
在MSYS2试了一下（CLANG64 环境，LLVM 14.0，MinGW trunk，UCRT）
- 时间相关的函数 `gmtime_r` `timegm` `strptime` 在Windows下没有，前两个有Windows对应的版本可以替换
- printf打印size_t的格式字符串不对（Windows是LLP64），换成%zu即可
```
D:/Documents/Desktop/GmSSL-develop/tests/sha256test.c:126:35: warning: format specifies type 'unsigned long' but the argument has type 'unsigned long long' [-Wformat]
                        printf("sha256 test %lu ok\n", i+1);
                                            ~~~        ^~~
                                            %llu
```
- TLS实现用到 `unistd.h` `arpa/inet.h` 等Windows没有的头文件，估计整一块要给Windows专门写一套代码...

**Comment by guanzhi** [comment]
对VS和Windows API的支持要等到下一个版本完成

**Comment by b1gcat** [comment]
mingw 支持最近有计划嘛

`
CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc cmake ..-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - no
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/local/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/local/bin/x86_64-w64-mingw32-gcc - broken
CMake Error at /usr/local/Cellar/cmake/3.24.1/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/local/bin/x86_64-w64-mingw32-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/b1gcat/Desktop/proj/gosrc/src/github.com/b1gcat/supervpn/src/lib/GmSSL/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_2f53c/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_2f53c.dir/build.make CMakeFiles/cmTC_2f53c.dir/build
    Building C object CMakeFiles/cmTC_2f53c.dir/testCCompiler.c.o
    /usr/local/bin/x86_64-w64-mingw32-gcc   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -o CMakeFiles/cmTC_2f53c.dir/testCCompiler.c.o -c /Users/b1gcat/Desktop/proj/gosrc/src/github.com/b1gcat/supervpn/src/lib/GmSSL/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_2f53c
    /usr/local/Cellar/cmake/3.24.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2f53c.dir/link.txt --verbose=1
    /usr/local/bin/x86_64-w64-mingw32-gcc  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_2f53c.dir/testCCompiler.c.o -o cmTC_2f53c 
    /usr/local/Cellar/mingw-w64/10.0.0_3/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: Error: unable to disambiguate: -search_paths_first (did you mean --search_paths_first ?)
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_2f53c] Error 1
    make: *** [cmTC_2f53c/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
`

**Comment by driver1998** [comment]
> mingw 支持最近有计划嘛

不需要TLS支持的话，那一块代码跳过不编译就可以了，记得是独立的两个c文件
剩下的测试用例都能通过

**Comment by xeronw** [comment]
> * strptime

这个strptime github有人写了一个https://github.com/p-j-miller/date-time，可以简单移植适配一下用起来。
