### ISSUE TITLE
请问Sm2的一些TLS实现是否与规范有差异

### ISSUE THREAD

**Issue by WendyWjt** [guanzhi/GmSSL#1246]
您好，我在 GMSSL 的源码中看到一些实现似乎与 [GB/T 38636-2020](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=778097598DA2761E94A5FF3F77BD66DA) 以及 [RFC8998](https://datatracker.ietf.org/doc/html/rfc8998) 提到的一些部分不太相符，想请问一下是否是我的理解有误，又或是有特殊的原因呢？

1. `develop/include/gmssl/tls.h`
```c
TLS_curve_x448				= 99, //30,
	TLS_curve_brainpoolp256r1tls13		= 31,
	TLS_curve_brainpoolp384r1tls13		= 32,
	TLS_curve_brainpoolp512r1tls13		= 33,
	TLS_curve_sm2p256v1			= 30,//41, // in gmssl v2, is 30
```
根据 [IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-16) 的注册值，以及 RFC8998，x448 是否应该为30？Sm2 是否应该为41？

2. `src/sm2_lib.c`
```c
int sm2_ecdh(const SM2_KEY *key, const SM2_POINT *peer_public, SM2_POINT *out)
{
	if (!key || !peer_public || !out) {
		error_print();
		return -1;
	}
	if (sm2_point_mul(out, key->private_key, peer_public) != 1) {
		error_print();
		return -1;
	}
	return 1;
}
```
这里是否是参考 IEEE 1363 或是最基础的 Diffie-Hellman 算法实现的密钥交换算法，即双方交换公钥点，根据对方公钥以及自身私钥生成共有点，取 x 值作为共有密钥？我阅读了源码，好像 TLS 1.2（GMSSLv1） 和 TLS 1.3 做 ECDHE 密钥交换时都使用的这个函数，但是这个实现与 Sm2 本身的规定（[GB/T 32918.3-2016](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=66A89DD6DA64F49C49456B757BA0624F)）不符。RFC8998 只说使用 "basic key exchange scheme"，但是 GB/T 38636-2020 中似乎应当使用 GB/T 32918.3-2016 规定的密钥算法？

3. 关于 Sm2 签名算法使用的 ID，RFC8998 在节 3.2.1 规定，当不验证对方证书链时，在其他使用场景，应当使用 ID `TLSv1.3+GM+Cipher+Suite`，我搜索了一下源码，好像没有这个字段，可以请问一下这一块的实现吗？

**Comment by guanzhi** [comment]
GmSSL 2.x早于这几个标准，因此在有些编号上存在冲突。
GmSSL 3.0目前还在alpha笨笨，正式发布后会在TLCP, TLS 1.2协议上和GmSSL 2.x保持协议上的兼容，在TLS 1.3上完全遵守RFC 8998。

GmSSL 3.0在TLCP协议中仅支持ECC加密密钥传输，在TLS 1.2, TLS 1.3中支持标准的ECDHE。
虽然GmSSL 2.x实现了SM2密钥交换协议，但是我们没有发现这个协议有任何实际应用需求，因此在3.0中不再支持。

此类问题我们后续会以正式的规范文档给出。

**Comment by WendyWjt** [comment]
好的，了解了，非常感谢您的时间和帮助！
