### ISSUE TITLE
v3版本  测试自签名证书生成时失败

### ISSUE THREAD

**Issue by iamgossh** [guanzhi/GmSSL#1254]
老师您好：
   今天在使用   ./gmssl certgen  时， 出现一下错误：
/root/GSP/GmSSL-develop/src/asn1.c:459:asn1_integer_to_der_ex():
/root/GSP/GmSSL-develop/src/x509_ext.c:671:x509_authority_key_identifier_to_der():
/root/GSP/GmSSL-develop/src/x509_ext.c:113:x509_exts_add_authority_key_identifier():
/root/GSP/GmSSL-develop/src/x509_ext.c:131:x509_exts_add_default_authority_key_identifier():
certgen: inner error

调试代码，发现一下问题：
在x509_ext.c 文件的第129行， 函数 x509_exts_add_authority_key_identifier  传入的参数中， 最后两个参数 [serial, serial_len]  传入的为空，长度为0，继续执行时， 会调用到asn1_integer_to_der_ex函数，而在此函数中又如下判断：

```
	if (alen <= 0 || alen > INT_MAX) {
		error_print();
		return -1;
	}
```
这里判断长度为0，就退出了。

**Comment by ziben** [comment]
我也遇到了，前天还好的，今天就突然出现了。。。。。

**Comment by ziben** [comment]
问题在这里：
```
int asn1_integer_to_der_ex(int tag, const uint8_t *a, size_t alen, uint8_t **out, size_t *outlen)
{
	if (!outlen) {
		error_print();
		return -1;
	}

	if (alen <= 0 || alen > INT_MAX) {
		error_print();
		return -1;
	}
	if (!a) {
		return 0;
	}
```

之前的版本一开始就判断 !a，然后就返回就了0，新版本先判断的长度，然后返回了-1。

**Comment by marshxq** [comment]
现在连证书都不能生成了

**Comment by guanzhi** [comment]
已经修复了这个bug
