### ISSUE TITLE
请问一下SM4-GCM算法计算出的结果和GB/T 36624-2018给出的协议数据不一致的原因可能是什么呢

### ISSUE THREAD

**Issue by Suterrra** [guanzhi/GmSSL#1263]
调用key_set后再使用sm4_gcm_encrypt加密后 计算出的密文段是正确的 但是TAG不符合，想请问一下有没有像test目录下的用例呢，不太确定是哪里配置出问题了

**Comment by guanzhi** [comment]
能否参考tests/sm4test.c中的test_sm4_gcm()函数给出测试数据

**Comment by zhangrui926** [comment]
> 调用key_set后再使用sm4_gcm_encrypt加密后 计算出的密文段是正确的 但是TAG不符合，想请问一下有没有像test目录下的用例呢，不太确定是哪里配置出问题了

我感觉sm4_modes.c中95行crt_incr()函数实现有误。

**Comment by guanzhi** [comment]
`crt_incr()`错误已经修复
`tests/sm4test.c`测试中包含了GB/T 36624-2018的测试数据。
