### ISSUE TITLE
生成自签名证书异常

### ISSUE THREAD

**Issue by lqmxiaogang** [guanzhi/GmSSL#1265]
[root@c529b9ffa19f ca]# gmssl sm2keygen -pass 1234 -out rootcakey.pem
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEpWQQVnsIZ1gm/TYvccmW08g+i0OQ
oFHXF24XM7ojqRYylXXxKFglRyyYRoPG7xlsAPYelQlb1df10yiwPQkutw==
-----END PUBLIC KEY-----
[root@c529b9ffa19f ca]# gmssl certgen -C CN -ST Beijing -L Haidian -O PKU -OU CS -CN ROOTCA -days 3650 -key rootcakey.pem -pass 1234 -out rootcacert.pem -key_usage keyCertSign -key_usage cRLSign
/opt/GmSSL-develop/src/asn1.c:458:asn1_integer_to_der_ex():
/opt/GmSSL-develop/src/x509_ext.c:671:x509_authority_key_identifier_to_der():
/opt/GmSSL-develop/src/x509_ext.c:113:x509_exts_add_authority_key_identifier():
/opt/GmSSL-develop/src/x509_ext.c:131:x509_exts_add_default_authority_key_identifier():
certgen: inner error

**Comment by marshxq** [comment]
没人管

**Comment by guanzhi** [comment]
这个bug已经修复了
