### ISSUE TITLE
求助求助，发布过的gmssl 2.4 不支持这个ECDHE-RSA-AES256-GCM-SHA384 加密套么？

### ISSUE THREAD

**Issue by funnyleo** [guanzhi/GmSSL#1267]
如题，在我使用过程中，发现使用国密库时，使用这个加密套 ECDHE-RSA-AES256-GCM-SHA384就会报这个错 bad ecpoint  换成 DHE-RSA-AES256-GCM-SHA384 就可以了，是我哪里没配置对么，代码里也没看说不支持ECDHE。。。。求助，问遍了也没人知道

**Comment by funnyleo** [comment]
@guanzhi @zhaoxiaomeng @

**Comment by guanzhi** [comment]
目前v3代码仅支持国密套件，不支持RSA套件
