### ISSUE TITLE
希望对vs10/13/19的常用项目官方进行支持，报错太多了

### ISSUE THREAD

**Issue by yanchenyuvip** [guanzhi/GmSSL#1268]
![image](https://user-images.githubusercontent.com/44298325/179441822-ab6db999-2769-44dd-8aef-0a030e9e1d86.png)
各种报错

**Comment by 841194253** [comment]
win下是不允许这种靠变量大小来申请数组空间的做法的，不行就改成malloc申请 内存资源，用完在free掉。

**Comment by guanzhi** [comment]
最新代码已经支持Visual Studio
