### ISSUE TITLE
Mac下Xcode导入gmssl后build fail

### ISSUE THREAD

**Issue by RideDi** [guanzhi/GmSSL#1279]
我尝试根据导入静态库的方式将gmssl编译后的include和lib部分添加进xcode的Build Settings中，代码中仅仅添加了#include <gmssl/sm3.h>请问应当如何解决此问题
<img width="816" alt="截屏2022-08-01 10 27 32" src="https://user-images.githubusercontent.com/55652807/182060869-109e99b2-1e8f-45be-a249-ed00fc89082a.png">
<img width="797" alt="截屏2022-08-01 10 27 43" src="https://user-images.githubusercontent.com/55652807/182060878-9cb56f85-a126-4bca-a8e1-b6de0a7a86cf.png">

**Comment by RideDi** [comment]
系统为Mac m1，Xcode版本为12.0

**Comment by RideDi** [comment]
选择legacy build system后又会出现
/GmSSL-develop/build/CMakeFiles/hmactest.dir/tests/hmactest.c.o.d:1: syntax error near ":"
/GmSSL-develop/build/CMakeFiles/gmssl.dir/src/zuc_modes.c.o.d:1: syntax error near ":"的build fail

**Comment by RideDi** [comment]
目前Xcode集成环境中还是无法使用gmssl库，但是通过vscode+cli的方式可以运行～

**Comment by HectorLiuk** [comment]
最终解决吗？
