### ISSUE TITLE
什么时候提供Python接口

### ISSUE THREAD

**Issue by hamdell** [guanzhi/GmSSL#128]
什么时候提供Python接口

**Comment by guanzhi** [comment]
如果有Python接口需求是可以考虑的。暂时你可以用Python直接调用gmssl的命令行，如果能够满足需要的话

**Comment by hamdell** [comment]
哎，还是喜欢python接口形式直接调用，强烈建议提供Python接口^-^

**Comment by guanzhi** [comment]
我们设计了新的GmSSL Go API  (http://gmssl.org/docs/go-api.html)，在完成之后会完全依照这个API来实现Python API并修改Java API。

**Comment by maxzlf** [comment]
希望可以提供 python api

**Comment by wossl33** [comment]
到现在都没看到python API，小哥哥不要骗我，嘤嘤

**Comment by whyshrha** [comment]
同希望可以有python版本api～

**Comment by chengboliber** [comment]
python这么流行的语言居然没有提供支持，不合理啊
