### ISSUE TITLE
如何生成pfx格式

### ISSUE THREAD

**Issue by HmingWang** [guanzhi/GmSSL#1283]
我看命令行改了 没找到怎么生成pfx格式 求教

**Comment by HmingWang** [comment]
有没有大佬帮忙解答一下，以前的命令 gmssl pkcs12 ... 系列指令用不了了。新版的替代指令是什么？

**Comment by guanzhi** [comment]
GmSSL 3.0 暂时不支持 PKCS #12 和 PFX 格式
