### ISSUE TITLE
gmssl3.0还支持SDF吗

### ISSUE THREAD

**Issue by lyc666-beep** [guanzhi/GmSSL#1284]

**Comment by guanzhi** [comment]
支持SDF，应用可以通过 `#include <gmssl/sdf.h>` 直接调用SDF设备，生成和GmSSL兼容的签名值。

**Comment by lyc666-beep** [comment]
好的，谢谢



---原始邮件---
发件人: "Zhi ***@***.***&gt;
发送时间: 2022年8月4日(周四) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guanzhi/GmSSL] gmssl3.0还支持SDF吗 (Issue #1284)




 
支持SDF，应用可以通过 #include <gmssl/sdf.h&gt; 直接调用SDF设备，生成和GmSSL兼容的签名值。

**Comment by lyc666-beep** [comment]
麻烦再问一下，SDF配置文件中，使用非sansec密码卡，openssl_cof , engines , sdf 三个配置项的值还是openssl_conf = openssl_init engines = engine_section sdf = sdf_section 吗，我用的是主分支代码
