### ISSUE TITLE
如何在gmssl3.0中进行性能测试？

### ISSUE THREAD

**Issue by RideDi** [guanzhi/GmSSL#1288]
我看#607 中存在gmssl speed以供进行性能测试，但我在gmssl3.0的cli和源码中没有发现这部分代码，请问 @guanzhi 关老师在gmssl3.0里是否存在什么方式可以测试SM2|SM3|SM4部分的代码运行效率呢？

**Comment by guanzhi** [comment]
3.0版本没有speed命令等性能测试功能，可以参考demos目录下面的示例代码或者tools下面的命令，自行编写性能测试代码。或者用time等命令行工具来测试gmssl命令行的性能。

**Comment by RideDi** [comment]
> 3.0版本没有speed命令等性能测试功能，可以参考demos目录下面的示例代码或者tools下面的命令，自行编写性能测试代码。或者用time等命令行工具来测试gmssl命令行的性能。

好的，谢谢关老师，如果参考tools实现了性能测试部分代码，是否有机会提交contribution嘞？
