### ISSUE TITLE
请问 Gmssl 是否计划升级 openssl 的版本？

### ISSUE THREAD

**Issue by ccxhwmy** [guanzhi/GmSSL#1289]
你好！
请问是否计划将 Gmssl 的 openssl 版本升级至最新版本？

**Comment by guanzhi** [comment]
GmSSL 从 3.0 开始不再依赖OpenSSL

**Comment by ccxhwmy** [comment]
> GmSSL 从 3.0 开始不再依赖OpenSSL

那 GmSSL 以后只能用来做国密接入了吗，RSA 相关的加密算法将去除掉吗？
