### ISSUE TITLE
GmSSL-master 在Unbuntu14.04 编译失败

### ISSUE THREAD

**Issue by sherry1118** [guanzhi/GmSSL#129]
使用命令为：
./config no-saf no-sdf no-skf no-sof no-zuc
make
但一直出现以下问题，急求大神帮忙！！！！

make[2]: Entering directory `/home/sherry/GmSSL-master'
Error: EVP_PKEY_get0_PAILLIER does not have a number assigned
LD_LIBRARY_PATH=: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/home/sherryGmSSL/ssl" -DENGINESDIR="/home/sherryGmSSL/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl
/usr/bin/ld:crypto.map:1620: syntax error in VERSION script
collect2: error: ld returned 1 exit status
make[2]: *** [link_shlib.linux-shared] Error 1
make[2]: Leaving directory `/home/sherry/GmSSL-master'
make[1]: *** [libcrypto.so] Error 2
make[1]: Leaving directory `/home/sherry/GmSSL-master'
make: *** [all] 错误 2

**Comment by sherry1118** [comment]
或者哪个大神有之前编译成功的版本，麻烦发给我。谢谢

**Comment by AivenYoung** [comment]
我在centos上编译没什么问题，使用./config，然后make，你可以尝试下呢

**Comment by sherry1118** [comment]
@AivenYoung 谢谢大神，我试试

**Comment by chary931201** [comment]
@sherry1118 ,你好，我现在也是和你遇到同样的问题，请问你Gmssl编译通过了?求救

**Comment by chary931201** [comment]
@sherry1118   压缩包直接用 linux的 unzip命令解压，则编译通过。怀疑跟解压后文件的格式或者操作系统的换行符或编码有关。

**Comment by sherry1118** [comment]
@chary931201 我的还是没有通过，依然是相同的问题。我试着换个unbuntu版本试试。

**Comment by chary931201** [comment]
昨天 ，让 大神，指导我 装好了。今天 自己独立装，又遇到这个问题了。大神 看着 我操作 ，步骤一样，还是 走到 这里了。

**Comment by troyseed** [comment]
大家有人解决了吗？我也遇到了
