### ISSUE TITLE
v3版本的性能较v2下降了一倍（sm4加密算法）

### ISSUE THREAD

**Issue by mesosxzan** [guanzhi/GmSSL#1290]
使用v3版本的sm4 cbc加密，比v2版本下降了接近一倍，请问这个后面优化吗？

**Comment by guanzhi** [comment]
3.0的代码未包含性能优化，并且为了可读性可能会降低部分算法的标准C实现性能。
下一个版本3.1会重点解决代码跨平台的问题，3.2版本会重点提升性能。

**Comment by mesosxzan** [comment]
收到
