### ISSUE TITLE
test_sm9_sign函数中对sm9_verify_finish返回值判断错误，sm9_verify_finish返回值为0，验签失败

### ISSUE THREAD

**Issue by smoonly** [guanzhi/GmSSL#1295]
if (sm9_verify_finish(&ctx, sig, siglen, &mpk, (char *)IDA, sizeof(IDA)) < 0) goto err; ++j;
sm9_verify_finish返回1验签成功，这里返回0

**Comment by guanzhi** [comment]
Bug已经修复
