### ISSUE TITLE
有关SM2withSM3签名时的UID取值

### ISSUE THREAD

**Issue by conezxy** [guanzhi/GmSSL#13]
在 https://github.com/guanzhi/GmSSL 项目中，提到了

“SM2数字签名方案中被签名的杂凑值不仅仅是消息的杂凑值，而是签名者身份信息串联上消息的杂凑值，其中签名者身份信息是签名者的可辨别标识字串、椭圆曲线方程系数、生成元和签名者公钥串联后字串的杂凑值。SM2标准中并未说明签名者的可辨别标识字串格式及获得方式，应用可以采用X.509证书中的Subject字段、CN (CommonName)或自行规定。”

但实际上在 GM/T 0009-2012《SM2密码算法使用规范》中第10小节“​用户身份标识 ID 的默认值”对此有附加描述：

`无特殊约定的情况下,用户身份标识 ID 的长度为 16 字节,其默认值从左至右依次为: 0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38。`

在标准的实际执行中，现有国密根CA颁发的证书中，CA的签名均采用此默认值。各接入国密根的二级CA也采用此值。

在国密的SSL标准 GM/T 0024-2014 《SSLVPN技术规范》中未对此取值做定义，因此目前国密局的SSLVPN检测平台采用了此值，因此所有通过平台测试的厂商也都采用了这个值。

**Comment by guanzhi** [comment]
目前的`SM2_compute_id_digest()`在`EC_KEY`中没有ID的情况下采用上述默认ID计算，但是如果用户没有通过`SM2_set_id()`设定，那么`SM2_get_id()`返回空。

**Comment by Leejiter** [comment]
您好，我用gmssl生成了一个证书， 然后用CA校验证书签名的时候，验证失败了： 计算Z值的时候，我试过ID为1234567812345678， ca的subject等，结果都是验签失败，我想问下验签的时候需要ID值参与Z的计算吗？
