### ISSUE TITLE
sm2 签名值是多少个字节？

### ISSUE THREAD

**Issue by sslvpn007** [guanzhi/GmSSL#130]
国密是64个字节，为什么我用sm2里的代码去签名，结果是71呢？？

**Comment by guanzhi** [comment]
这是根据国密 GM/T 0009-2012 SM2密码算法使用规范 7.3 编码后的结果，因为签名长度是随曲线不同而变化的，只有通过Tag-Length-Value方式的编码，才能够支持不同长度的签名值。

**Comment by sslvpn007** [comment]
关老师，我通过BN_num_bytes(s->r)，和BN_num_bytes(s->s),计算出，r和s 的bytes都是32个字节。

两个长度之和正好是64个字节。

这是不是说明，这个64个字节的字节流  就是sm2签名值 呢

这个我不是很理解。

**Comment by zhu071011** [comment]
关老师，那我用不同的私钥去签名，生成出来的是签名长度是不是都不一定是等长的，我发现我收到的结果，一会儿是4，一会儿38，一会儿70，一会儿72，请问这是不是出问题了？
