### ISSUE TITLE
请问有没有计划推出Erlang语言的接口？

### ISSUE THREAD

**Issue by leeyisoft** [guanzhi/GmSSL#1308]
我现在的项目后端语言是Erlang实现的，目前用的是RSA非对称算法，想学习学习GM相关的用法，求指导；

前端用的Flutter，也期望GmSSL能够提供flutter的支持

**Comment by guanzhi** [comment]
我不熟悉Erlang和Flutter，能否说明支持Erlang及Flutter的应用场景

**Comment by leeyisoft** [comment]
[Flutter是Google开源的构建用户界面（UI）工具包](https://baike.baidu.com/item/Flutter/22498985?fr=aladdin)

[Erlang是一种通用的面向[并发](https://baike.baidu.com/item/%E5%B9%B6%E5%8F%91?fromModule=lemma_inlink)的编程语言

**Comment by guanzhi** [comment]
这些语言和框架我都不熟悉，不过我可以为开源开发者提供GmSSL多种语言wrapper的技术支持。GmSSL官方大致会提供Java, Go, Rust这几个语言的支持
