### ISSUE TITLE
GmSSL version 2.5.4 vs2022编译不通过

### ISSUE THREAD

**Issue by CWQ111111** [guanzhi/GmSSL#1314]
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_ciphernames
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_digestnames

**Comment by CWQ111111** [comment]
请大家帮帮我

**Comment by kai-think-peach** [comment]
https://blog.csdn.net/zyhse/article/details/112325129

**Comment by kai-think-peach** [comment]
> libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_ciphernames libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_digestnames

https://blog.csdn.net/zyhse/article/details/112325129
