### ISSUE TITLE
gmssl3.0 ubuntu18编译报错

### ISSUE THREAD

**Issue by HUGO313L** [guanzhi/GmSSL#1321]
ib/libgmssl.so.3.0: undefined reference to `_rdseed64_step'
collect2: error: ld returned 1 exit status
CMakeFiles/rc4test.dir/build.make:95: recipe for target 'bin/rc4test' failed
make[2]: *** [bin/rc4test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rc4test.dir/all' failed
make[1]: *** [CMakeFiles/rc4test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xiaoheilong** [comment]
you had solve the issue?

**Comment by guanzhi** [comment]
问题已经修复

**Comment by Le0nFisher** [comment]
解决方法有么？主线还有这个错误。

**Comment by Le0nFisher** [comment]
dc7b9e68ecb3e2179e24aa7a729c33a83f3f4493 (HEAD -> master, origin/master, origin/HEAD) Update SM2 Extensions

**Comment by duwentao1** [comment]
主线这个错误还在呢

**Comment by alittlehorse** [comment]
The fix, that worked for me:

https://github.com/guanzhi/GmSSL/issues/1446#issue-1622872739

**Comment by Merlin0126** [comment]
问题还在呀,没有修复
