### ISSUE TITLE
cmake 最新版本的gmssl，出错!

### ISSUE THREAD

**Issue by xiaoheilong** [guanzhi/GmSSL#1324]
(sdk) -bash-5.1# cmake ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 10.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:114 (target_link_libraries):
  Cannot specify link libraries for target "gmssl" which is not built by this
  project.

-- Configuring incomplete, errors occurred!

**Comment by Mojicode** [comment]
参考 #1325

**Comment by xiaoheilong** [comment]
> 参考 #1325
yes , It's   ok!  thanks
