### ISSUE TITLE
SM9计划进行哪些性能优化？

### ISSUE THREAD

**Issue by chengyuma** [guanzhi/GmSSL#1339]
本人目前有使用SM9相关代码的需求，但是签名性能还不够理想。查看了一些文献和目前的GmSSL中的代码，发现代码里也加入了主要的常见的优化，请问下一步还会有哪些SM9的优化，本人也可为代码库贡献一些优化的代码。

**Comment by guanzhi** [comment]
欢迎贡献，可以给我发邮件讨论 guan@pku.edu.cn
