### ISSUE TITLE
红帽6.8，gcc4.7.2下编译出错

### ISSUE THREAD

**Issue by shady831213** [guanzhi/GmSSL#134]
In file included from include/openssl/gmapi.h:64,
                 from crypto/err/err_all.c:47:
include/openssl/sof.h:57: error: redefinition of typedef 'BOOL'
include/openssl/skf.h:66: note: previous declaration of 'BOOL' was here
make[1]: *** [crypto/err/err_all.o] Error 1
make[1]: Leaving directory `/home/yli/Downloads/GmSSL-master'
make: *** [all] Error 2

谢谢

**Comment by shady831213** [comment]
diff --git a/Makefile.shared b/Makefile.shared
index 098e1ec..82d6564 100644
--- a/Makefile.shared
+++ b/Makefile.shared
@@ -196,7 +196,7 @@ link_app.gnu:
 link_shlib.linux-shared:
 	@$(PERL) $(SRCDIR)/util/mkdef.pl $(LIBNAME) linux >$(LIBNAME).map; \
 	$(DO_GNU_SO); \
-	ALLSYMSFLAGS='-Wl,--whole-archive,--version-script=$(LIBNAME).map'; \
+	ALLSYMSFLAGS='-Wl,--whole-archive'; \
 	$(LINK_SO_SHLIB)
 
 link_dso.bsd:
diff --git a/crypto/ffx/ffx.c b/crypto/ffx/ffx.c
index ff2a917..b8e4bed 100644
--- a/crypto/ffx/ffx.c
+++ b/crypto/ffx/ffx.c
@@ -71,11 +71,6 @@ static uint32_t modulo[] = {
 		1000000000,
 };
 
-typedef struct FFX_CTX_st {
-	EVP_CIPHER_CTX *cctx;
-	int flag;
-} FFX_CTX;
-
 FFX_CTX *FFX_CTX_new(void)
 {
 	FFX_CTX *ret = NULL;
diff --git a/include/openssl/ffx.h b/include/openssl/ffx.h
index a044597..5c7c909 100644
--- a/include/openssl/ffx.h
+++ b/include/openssl/ffx.h
@@ -74,7 +74,11 @@
 extern "C" {

 #endif

 

-typedef struct FFX_CTX_st FFX_CTX;

+//typedef struct FFX_CTX_st FFX_CTX;

+typedef struct FFX_CTX_st {
+	EVP_CIPHER_CTX *cctx;
+	int flag;
+} FFX_CTX;
 

 FFX_CTX *FFX_CTX_new(void);

 void FFX_CTX_free(FFX_CTX *ctx);

diff --git a/include/openssl/sof.h b/include/openssl/sof.h
index 990eb32..ff83cae 100644
--- a/include/openssl/sof.h
+++ b/include/openssl/sof.h
@@ -52,10 +52,9 @@
 

 #ifndef HEADER_SOF_H

 #define HEADER_SOF_H

-

+#include <openssl/skf.h>

 typedef char *BSTR;

-typedef long BOOL;

-

+//typedef long BOOL;

 #ifdef __cplusplus

 extern "C" {

 #endif

diff --git a/test/sm2test.c b/test/sm2test.c
index 14c2aba..8ab0294 100644
--- a/test/sm2test.c
+++ b/test/sm2test.c
@@ -332,7 +332,12 @@ int test_sm2_sign(const EC_GROUP *group,
 		goto err;
 	}
 	printf("id=%s\n", id);
-	printf("zid(xx):"); for (int j = 0; j < dgstlen; j++) { printf("%02x", dgst[j]); } printf("\n");
+	printf("zid(xx):"); 
+	int j;
+	for (j = 0; j < dgstlen; j++) { 
+	  printf("%02x", dgst[j]); 
+	} 
+	printf("\n");
 	if (!hexequbin(Z, dgst, dgstlen)) {
 		fprintf(stderr, "error: %s %d\n", __FUNCTION__, __LINE__);
 		goto err;

以上修改后，编译通过

**Comment by shady831213** [comment]
虽然编过了，各种找不到定义。。。。

**Comment by ZhangKejie** [comment]
非常感谢。centos6.5下编译过了

**Comment by terasum** [comment]
@shady831213 可以把一些测试给删掉，比如sdftest
编译出来之后记得 ldconfig 一下

**Comment by shady831213** [comment]
@ZhangKejie 虽然编过了，但是还是各种跑不起来。。。等稳定一些再说吧T_T。

**Comment by ZhangKejie** [comment]
@shady831213 就是把一些测试都删了，然后就work了。

**Comment by shady831213** [comment]
我之前是需要用EC_GROUP， include "ec.h"后EC_KEY 和 EC_KEY_METHOD没有定义， 自己在ec.h中加上
typedef struct ec_key_st EC_KEY;
typedef struct ec_key_method EC_KEY_METHOD;
后ok了^_^

**Comment by chary931201** [comment]
@shady831213  hello。how  can  i   get hold of you?  i  need  your help.

**Comment by shady831213** [comment]
@chary931201 you can send me email^_^

**Comment by chary931201** [comment]
@shady831213  在头文件evp.h   sm2.h 都是 有声明
/tmp/cc7nRIV8.o: In function `test_sm2_sign':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:307: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:308: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:333: undefined reference to `SM2_compute_id_digest'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:350: undefined reference to `SM2_compute_message_digest'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:369: undefined reference to `SM2_sign'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:398: undefined reference to `SM2_verify'
/tmp/cc7nRIV8.o: In function `test_sm2_enc':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:421: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:422: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:436: undefined reference to `SM2_encrypt_with_recommended'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:456: undefined reference to `SM2_decrypt_with_recommended'
/tmp/cc7nRIV8.o: In function `test_sm2_kap':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:483: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:537: undefined reference to `SM2_KAP_CTX_init'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:540: undefined reference to `SM2_KAP_CTX_init'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:545: undefined reference to `SM2_KAP_prepare'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:551: undefined reference to `SM2_KAP_prepare'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:557: undefined reference to `SM2_KAP_compute_key'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:563: undefined reference to `SM2_KAP_compute_key'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:568: undefined reference to `SM2_KAP_final_check'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:571: undefined reference to `SM2_KAP_final_check'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:582: undefined reference to `SM2_KAP_CTX_cleanup'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:583: undefined reference to `SM2_KAP_CTX_cleanup'
collect2: error: ld returned 1 exit status

**Comment by shady831213** [comment]
@chary931201 他们头文件里有些数据类型都没定义，我是自己找的，然后自己在头文件里加上的。。。可以对照openssl原来的代码看一下，一般都是在对应的.c里定义了对应的结构体

**Comment by chary931201** [comment]
@shady831213  我弱弱的问一下，我的gmssl安装好了。为啥？gmssl 指令 没法用。 gmssl: command not found

**Comment by shady831213** [comment]
@chary931201 把安装路径下的bin加到PATH中吧

**Comment by chary931201** [comment]
能用其他 方式 交流？我想及时交流。

**Comment by chary931201** [comment]
@shady831213 能用其他 方式 联络？ 我想及时交流。

**Comment by chary931201** [comment]
@shady831213 我感觉 从 我 安装gmssl  到 编译 gmssl  都 有点 问题。
