### ISSUE TITLE
GmSSL sm9encrypt 工具-in参数打开文件有误

### ISSUE THREAD

**Issue by zhujunling-nj** [guanzhi/GmSSL#1342]
GmSSL sm9encrypt 工具-in参数打开文件有误，应该打开infile，实际打开outfile了。

![image](https://user-images.githubusercontent.com/26447863/196888440-4b67dd5b-71d5-45e8-af76-09b1fb29d08a.png)

sm3.c -out 参数打开文件方式有误，应该以“写”方式打开，实际以“读”方式打开了。

**Comment by guanzhi** [comment]
请提供一个pull request修改吧
