### ISSUE TITLE
sm9_sign_master_key_generate 和sm9_enc_master_key_generate

### ISSUE THREAD

**Issue by xiaoheilong** [guanzhi/GmSSL#1343]
sm9_sign_master_key_generate 和sm9_enc_master_key_generate , 有什么区别呢？我看是有不同系列的，  sm9_sign_*和sm9_enc_*系列的接口。

**Comment by guanzhi** [comment]
SM9的签名和加解密主密钥是不同的，这两个函数分别用于生成签名主密钥和加密主密钥

**Comment by venjin** [comment]
> SM9的签名和加解密主密钥是不同的，这两个函数分别用于生成签名主密钥和加密主密钥

这两个函数在主分支是不是没有？

**Comment by xiaoheilong** [comment]
@guanzhi  谢谢， 我自己已经试过了， 确实是签名和加密的是用不同的。
