### ISSUE TITLE
编译事sm2test.c 遇到错误。这个 宏不是 都 在 头文件里有了？（头文件是完整的）这个错误，有点疑惑？ 

### ISSUE THREAD

**Issue by chary931201** [guanzhi/GmSSL#135]
/tmp/cclNqHkX.o: In function `SM2_Test_Vecotor':
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:49: undefined reference to `CRYPTO_set_mem_debug_functions'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:151: undefined reference to `SM2_sign'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:158: undefined reference to `SM2_verify'
/tmp/cclNqHkX.o: In function `SM2_Test_Vecotor2':
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:203: undefined reference to `CRYPTO_set_mem_debug_functions'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:345: undefined reference to `SM2_sign_ex'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:353: undefined reference to `SM2_verify'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:409: undefined reference to `SM2_DH_key'
/tmp/cclNqHkX.o: In function `main':
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:435: undefined reference to `CRYPTO_set_mem_debug_functions'
/home/guard/experiment/TCP/PassWord/SM2/0331/sm2test.c:446: undefined reference to `CRYPTO_mem_leaks_fp'
collect2: error: ld returned 1 exit status

**Comment by shady831213** [comment]
https://github.com/guanzhi/GmSSL/issues/134

**Comment by chary931201** [comment]
@shady831213    hello。how  can  i   get hold of you?  i  need  your help.

**Comment by chary931201** [comment]
@shady831213  here！look！
collect2: error: ld returned 1 exit status
guard@Guard:~/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test$ gcc -g -o sm2test sm2test.c -I/usr/local/include/openssl -L/usr/local/lib -lssl -lcrypto -ldl
/tmp/cc7nRIV8.o: In function `test_sm2_sign':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:307: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:308: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:333: undefined reference to `SM2_compute_id_digest'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:350: undefined reference to `SM2_compute_message_digest'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:369: undefined reference to `SM2_sign'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:398: undefined reference to `SM2_verify'
/tmp/cc7nRIV8.o: In function `test_sm2_enc':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:421: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:422: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:436: undefined reference to `SM2_encrypt_with_recommended'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:456: undefined reference to `SM2_decrypt_with_recommended'
/tmp/cc7nRIV8.o: In function `test_sm2_kap':
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:483: undefined reference to `EVP_sm3'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:537: undefined reference to `SM2_KAP_CTX_init'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:540: undefined reference to `SM2_KAP_CTX_init'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:545: undefined reference to `SM2_KAP_prepare'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:551: undefined reference to `SM2_KAP_prepare'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:557: undefined reference to `SM2_KAP_compute_key'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:563: undefined reference to `SM2_KAP_compute_key'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:568: undefined reference to `SM2_KAP_final_check'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:571: undefined reference to `SM2_KAP_final_check'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:582: undefined reference to `SM2_KAP_CTX_cleanup'
/home/guard/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/test/sm2test.c:583: undefined reference to `SM2_KAP_CTX_cleanup'
collect2: error: ld returned 1 exit status
满篇的未声明。求解释我看到sm2.h 和 evp.h 都是有声明的。
guard@Guard:~/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/include/openssl$ grep EVP_sm3 *.h
evp.h:const EVP_MD *EVP_sm3(void);

guard@Guard:~/experiment/TCP/PassWord/SM2/Gmssl/GmSSL-master/GmSSL-master/include/openssl$ grep SM2_compute_id_digest *.h
sm2.h:int SM2_compute_id_digest(const EVP_MD *md, const char *id, size_t idlen,
