### ISSUE TITLE
现在的实现貌似握手过程是同步的，有考虑加入类似OPENSSL的异步方式吗？

### ISSUE THREAD

**Issue by xuming** [guanzhi/GmSSL#1351]
对于高并发服务器，异步模型能提供更好的性能，请问是否有计划加入？
另外openssl的engine机制是否会加入？

**Comment by guanzhi** [comment]
目前GmSSL支持select，是否支持其他模型要看需求。比如是否有高并发服务器项目或者企业用户在使用GmSSL时遇到因为异步模型产生的性能瓶颈，这个需求是否普遍。
GmSSL 3.0有专用的SDF、SKF机制，不再需要通过Engine机制接入，后续版本（3.3之后）会集成在SSL模块中。
