### ISSUE TITLE
   go调用测试 ，提示缺少openssl/sm2.h ，按照文档编译gmssl，也升级了openssl

### ISSUE THREAD

**Issue by yaofeiliang** [guanzhi/GmSSL#1355]
go run gmssltest.go

../gmssl/certificate.go:57:10: fatal error: openssl/sm2.h: No such file or directory
 #include <openssl/sm2.h>

也升级了openssl :OpenSSL 3.0.5 5 Jul 2022
是要将  ./local/include/gmssl/sm2.h 复制到 /usr/local/include/openssl 吗

**Comment by guanzhi** [comment]
目前的master分支的3.0不兼容之前的Go Wrapper，这部分功能会在3.3之后恢复
