### ISSUE TITLE
gmssl支持国密的数字信封吗

### ISSUE THREAD

**Issue by Ricard4869** [guanzhi/GmSSL#1356]
例如命令行解析国密pkcs7格式文件，gmssl pkcs7 -in xxx.pem -text -print

**Comment by guanzhi** [comment]
gmssl cmsencrypt, cmsdecrypt, cmssign, cmsverify, cmsparse 命令支持国密CMS标准的数字信封

或 #include <gmssl/cms.h>

**Comment by L-code256** [comment]
怎么使用这些命令，将国密加密证书的私钥转为数字信封呢
