### ISSUE TITLE
Ubuntu使用clang编译会找不到strptime函数

### ISSUE THREAD

**Issue by dreamcmi** [guanzhi/GmSSL#1378]
使用Ubuntu20.04 clang-16
cmake工具链换成clang直接编译会报错 `call to undeclared function 'strptime'`
解决方案如下
在CMakeLists.txt里加上
```cmake
add_definitions(-D_XOPEN_SOURCE -D_GNU_SOURCE)
```
当前方案仅在Ubuntu20.04试验通过

**Comment by guanzhi** [comment]
最新代码中对`strptime`函数的依赖已经去掉了
