### ISSUE TITLE
在centos8中编译的GMSSL3.0.0是否可以用在arm64架构下的系统中？

### ISSUE THREAD

**Issue by Tezzxamo** [guanzhi/GmSSL#1379]
我已经在centos8中编译好了，并且使用 gmssl version有正常的版本输出
此时我将整个GmSSL-3.0.0文件夹复制到另一个centos服务器上，软连接后（或直接在bin目录中）使用gmssl version依旧有正常的版本输出

问题：”如果我将这个GmSSL-3.0.0文件夹复制到一台arm64架构的服务器上，使用gmssl version会有正常的输出吗？“
这个问题也可以描述为：”我在x86的架构下使用cmake，make，make install 后的gmssl能否在arm64的服务器下使用？“

还希望能够解答  @guanzhi

**Comment by Tezzxamo** [comment]
can not

**Comment by zzl360** [comment]
其实一般情况下，交叉编译可以解决这个问题
