### ISSUE TITLE
请问SM4的OFB模式支持硬件加速吗？哪些模式支持硬件加速？

### ISSUE THREAD

**Issue by 956276933** [guanzhi/GmSSL#138]
请问SM4的OFB模式支持硬件加速吗？哪些模式支持硬件加速？

**Comment by guanzhi** [comment]
SMS4的AVX加速只支持ECB/CTR/GCM/CCM模式，不支持其他模式。
可以通过SKF Engine或者SDF Engine对SMS4的各个模式进行加速，具体支持哪些模式由硬件决定，但是通常这些外接的硬件性能大幅低于X86处理器的软件加解密性能。

**Comment by Jason0401** [comment]
关老师，您是说通过ENGINE调用SKF访问硬件这种方式的性能还不如软件加解密性能吗？
