### ISSUE TITLE
有点失望，3.0 和openssl好像完全不兼容了。

### ISSUE THREAD

**Issue by xuyb6** [guanzhi/GmSSL#1380]
有点失望，一个发布的realease版本居然在VS下编译不了。 DEV版本虽然编译了，但发现命令和原来openssl的相去甚远了，完全没有兼容之处。。
而且没有一个正式的help文件可参考。命令需要从代码里面去找。唉。
这样下去，这玩意也许没人用了。

**Comment by yw1573** [comment]
已经不如刚开始从openssl改过来的时候好用了

**Comment by yw1573** [comment]
现在openssl以及兼容了sm2、sm3、sm4，可能得用回openssl了

**Comment by yw1573** [comment]
用的人少，没有完整的文档支持，都是闷着搞，就这样咯
