### ISSUE TITLE
SM2加解密中EVP_PKEY生成

### ISSUE THREAD

**Issue by xroocky** [guanzhi/GmSSL#139]
@guanzhi 关老师，您好！非常感谢您和您的团队为大家的提供了如此强大的GmSSL，但是在使用SM2加解密过程中遇到了一个问题，还望您能不吝赐教！

在sm2evptest.c文件中，调用test_evp_pkey_encrypt函数时传入的参数EVP_PKEY是由EVP_PKEY_keygen函数生成的，当我尝试通过公钥和私钥来生成EC_KEY，然后再将EC_KEY封装成EVP_PKEY传递给test_evp_pkey_encrypt函数时，调用EVP_PKEY_encrypt函数进行加密就会报出如下错误：

```
4559156160:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:crypto/ec/ec_lib.c:707:
```

“通过公钥和私钥来生成EC_KEY，然后再将EC_KEY封装成EVP_PKEY”的代码是我从sm2test.c文件中拿来的，代码本身应该没有什么问题。我注意到在sm2test.c文件中EC_GROUP的生成方式和sm2evptest.c文件中的生成方式是不一样的，sm2test.c中生成方式如下：

```
sm2p256test  = new_ec_group(1,
		"8542D69E4C044F18E8B92435BF6FF7DE457283915C45517D722EDB8B08F1DFC3",
		"787968B4FA32C3FD2417842E73BBFEFF2F3C848B6831D7E0EC65228B3937E498",
		"63E4C6D3B23B0C849CF84241484BFE48F61D59A5B16BA06E6E12D1DA27C5249A",
		"421DEBD61B62EAB6746434EBC3CC315E32220B3BADD50BDC4C4E6C147FEDD43D",
		"0680512BCBB42C07D47349D2153B70C4E5D7FDFCBFA36EA1A85841B9E46E09A2",
		"8542D69E4C044F18E8B92435BF6FF7DD297720630485628D5AE74EE7C32E79B7",
		"1")
```

sm2evptest.c文件中生成方式如下：

```
sm2p256test = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
```
请问这两种生成方式有什么区别么？都是对应256比特素数域椭圆曲线吧？
在sm2evptest.c文件中我通过封装公钥和私钥生成EVP_PKEY再去调用加密会报错，后来我把EC_GROUP的生成方式改为sm2test.c文件中EC_GROUP的生成方式，就不会报错了，可以正常加解密。

劳烦关老师解答一下在下的疑问，万分感谢！

**Comment by xroocky** [comment]
@guanzhi 关老师，我这里还有一个疑问，我在本地测试sm2test.c时发现加密得到的密文和国密文档给出的加密示例一致，但是解密就无法正确得到明文了。另外我在sm2evptest.c中修改了genpkey，改为指定公钥和私钥为国密文档中的示例，可以正确解密得到相应的明文，但是为什么每次加密得到的密文和国密文档给出的加密示例不一样呢，而且每次加密得到的密文都不一样，但是可以正确解密得到明文。
麻烦关老师了！

**Comment by guanzhi** [comment]
SM2加密过程中会生成一个随机值，因此即使明文相同每次加密的结果也不同。随机值设定为示例中的值后生成的密文才会和示例的密文一样。

**Comment by xroocky** [comment]
谢谢关老师！

**Comment by Smalinuxer** [comment]
求问为什么第一种方式不可以成功？

**Comment by wandoha** [comment]
同问，sm2p256test = EC_GROUP_new_by_curve_name(NID_sm2p256v1); 为什么报
_4559156160:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:crypto/ec/ec_lib.c:707:_

@guanzhi 关老师，您好，有空的还请解答下。

**Comment by Yifei0727** [comment]
@xroocky  请教下 如何将EC_KEY封装成EVP_PKEY  我看了 好多 EVP_PKEY的API 没有找到相关方法
多谢

**Comment by lurenf11** [comment]
error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding 我客户单采用低版本openssl_1.0.1g和源站openssl_1.1.1c TLS握手，也客户端得到上述错误，这个问题是因为什么呢，楼主当时怎么解决的？客户端用openss_1.1.1版本和源站openssl_1.1.1c版本握手时是正常的。目前怀疑openssl_1.1.1c编译得有问题？？
