### ISSUE TITLE
undefined reference to `getentropy'

### ISSUE THREAD

**Issue by github9157** [guanzhi/GmSSL#1392]
GmSSL-master/src/rand_unix.c 中使用了getentropy，这个函数目前在unistd.h已经找不到了，编译不过去

**Comment by github9157** [comment]
/home/zyj/third-part/GmSSL-master/src/rand_unix.c: In function ‘rand_bytes’:
/home/zyj/third-part/GmSSL-master/src/rand_unix.c:36:13: warning: implicit declaration of function ‘getentropy’ [-Wimplicit-function-declaration]
   36 |         if (getentropy(buf, len) != 0) {
      |             ^~~~~~~~~~
[ 36%] Linking C shared library bin/libgmssl.so
[ 36%] Built target gmssl
[ 37%] Building C object CMakeFiles/gf128test.dir/tests/gf128test.c.o
[ 38%] Linking C executable bin/gf128test
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: bin/libgmssl.so.3.0: undefined reference to `getentropy'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/gf128test] 错误 1
make[1]: *** [CMakeFiles/gf128test.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by guanzhi** [comment]
`getentropy`在老版本的Linux发行版和glibc中不存在。你的Linux具体版本是什么？

可以将CMakeLists.txt中的
```
218 if (WIN32)
...
224 else()
225         list(APPEND src src/rand_unix.c)
226 endif()
```
改为
```
218 if (WIN32)
...
223         list(APPEND src src/rand.c)
224 else()
225         list(APPEND src src/rand.c)
226 endif()
```

**Comment by github9157** [comment]
嗯，谢谢，应该是我的centos版本是老版本，也没有升级glibc，现在用的centos版本是：CentOS Linux release 7.9.2009 (Core) ；glibc版本是：ldd (GNU libc) 2.17

**Comment by TheWaveLab** [comment]
> `getentropy`在老版本的Linux发行版和glibc中不存在。你的Linux具体版本是什么？
> 
> 
> 
> 可以将CMakeLists.txt中的
> 
> ```
> 
> 218 if (WIN32)
> 
> ...
> 
> 224 else()
> 
> 225         list(APPEND src src/rand_unix.c)
> 
> 226 endif()
> 
> ```
> 
> 改为
> 
> ```
> 
> 218 if (WIN32)
> 
> ...
> 
> 223         list(APPEND src src/rand.c)
> 
> 224 else()
> 
> 225         list(APPEND src src/rand.c)
> 
> 226 endif()
> 
> ```

已解决！
