### ISSUE TITLE
3.0 创建csr文件 reqgen_main 为啥需要私钥？

### ISSUE THREAD

**Issue by xsmart** [guanzhi/GmSSL#1395]
用3.0 创建csr文件 reqgen_main，看代码是解析私钥，理论上应用public key 就可以了吧？
![image](https://user-images.githubusercontent.com/4601085/212276174-a4ce4711-d9b9-41f1-b97b-a753cf365506.png)
skfutil 里面可以导出public key, 应该 reqgen 能够使用这里的输出吧？
![image](https://user-images.githubusercontent.com/4601085/212276419-06225219-3067-4b01-8e28-2f53c5cf8655.png)

**Comment by guanzhi** [comment]
`reqgen`需要用私钥签名，如果公钥来自于SDF密码卡，那么需要调用SDF进行签名。
这个命令行工具还不支持调用密码卡。

**Comment by xsmart** [comment]
Thanks， 有其他工具可以支持这个功能？
