### ISSUE TITLE
关于使用编译后的动态库，openssl相关通信异常

### ISSUE THREAD

**Issue by meakira** [guanzhi/GmSSL#14]
关于使用编译后的动态库（下载后使用make clean,./config,make。未使用自定义编译参数），启动openssl服务，使用网页链接后出现：
在高级设置中启用 TLS 1.0、TLS 1.1 和 TLS 1.2，然后尝试再次连接到 https://192.177.65.75 。如果此错误依然存在，请与站点管理员联系。

请问关老师，目前版本是否支持openssl通信（目前使用库后，原rsa套件使用场景也异常）。
若通信是否有需要别的设置或者操作。

ps：
Linux下编译时出现ecp_nistz256.o未定义错误
需要将crypto\ec下makefile增加 _.s的删除
clean:
    rm -f *.s *.o */_.o _.obj lib tags core .pure .nfs_ *.old *.bak fluff

**Comment by guanzhi** [comment]
目前国密SSL VPN的功能刚开始开发，并且对`ssl/`目录下的代码有所添加修改，可能会影响已有的SSL功能，建议先通过命令行中的s_server, s_client指令进行测试。现阶段SM3, SM4/SMS4的功能比较稳定，可能通过EVP接口访问。SM2的功能可以先调用sm2.h头文件中定义的功能。在GmSSL-1.2.1版本正式发布后会提供SM2的完整测试用例。在之后的一个版本会提供SM2经过测试的EVP接口实现。国密SSL的功能会排在更后面一点。

**Comment by LiTianjue** [comment]
国密ssl vpn  打算基于openvpn 吗还是能有其他的解决方案，那是不是还要搞一个工程 GmVpn ? 哈哈

**Comment by guanzhi** [comment]
是指实现国密的CipherSuite，包括ECDHE_SM4_SM3、ECC_SM4_SM3等，以及通过ENGINE支持ECDHE_SM1_SM3等。OpenVPN、OpenSWAN、StrongSWAN等开源VPN项目可以通过少量修改和配置，利用GmSSL替代OpenSSL，实现基于国密算法的安全通信。但是GmSSL暂时没有VPN子项目的计划，GmSSL会优先考虑支持Apache HTTPD。

**Comment by LiTianjue** [comment]
完全等不及项目的更新进度了，如果在GmSSL的基础上去做sslvpn的开发，还有哪些工作要做，一个人开发，以您的经验，需要多久做多久？

**Comment by guanzhi** [comment]
直接在OpenSSL/GmSSL的ssl目录里面改的话需要读代码，理解OpenSSL的代码才能改好，虽然最后加不了多少代码，但是时间上不好估计。如果你有严格的时间限制，也可以从头做一个国密SSL的协议层，实现基本握手和通信的代码量不会太大。我们之前做过的一个类似项目，不包含密码算法代码的协议层只有2000多行代码(Amazon自己的SSL层实现也只有6000多行代码)，当时用了差不多2个人月。VPN相关的工作我不了解，就没法估计了。

**Comment by jyy1082** [comment]
OpenVPN和GmSSL整合需要修改和配置哪些呢？请Dr. Guan指点！谢谢！

**Comment by guanzhi** [comment]
请参考Wiki [从OpenSSL迁移至GmSSL](https://github.com/guanzhi/GmSSL/wiki/从OpenSSL迁移至GmSSL)

**Comment by jyy1082** [comment]
谢谢回复！我看到Wiki介绍的好像是把算法改成国密的，如果保持原有的，再新加一个option国密也是那么做吗？
