### ISSUE TITLE
我发现SM4-GCM有问题

### ISSUE THREAD

**Issue by Cryptographer63** [guanzhi/GmSSL#1403]
https://github.com/guanzhi/GmSSL/blob/1fbdfeee59e9c32f7941bc957e3aa11a8ec37dc1/demos/sm4/sm4_gcm_demo.c#L78

上面是SM4-GCM的Demo，在解密的时候，使用的却是加密时的sm4_key，通过sm4_set_encrypt_key函数得到。按道理，在解密的时候不应该使用sm4_set_decrypt_key函数得到的sm4_key吗？如果使用sm4_set_decrypt_key，就会出错，我不知道是不是在GCM算法中有错误？

**Comment by guanzhi** [comment]
GCM和CTR模式下的加解密都只使用SM4加密，因此不会调用`sm4_set_decrypt_key`
