### ISSUE TITLE
sm2_encrypt 加密后的数据经过Base64产生\r\n回车换行问题

### ISSUE THREAD

**Issue by shentu521** [guanzhi/GmSSL#1417]
再使用官方的demo中我们发现，使用:
sm2_encrypt
通过公钥以及加密的msg,得到结果后，然后经过base64编码，得到的数据会有\r\n字符串这样的字符串经过GB35114协议的传输，会导致某些设备无法解析头部，特别是使用pjsip开源库的项目.

**Comment by guanzhi** [comment]
> 再使用官方的demo中我们发现，使用:
> sm2_encrypt
> 通过公钥以及加密的msg,得到结果后，然后经过base64编码，得到的数据会有\r\n字符串这样的字符串经过GB35114协议的传输，会导致某些设备无法解析头部，特别是使用pjsip开源库的项目.

目前Base64编码会自动生成换行
