### ISSUE TITLE
关于ECDHE_SM4_SM3  套件实现的疑惑

### ISSUE THREAD

**Issue by muryliang** [guanzhi/GmSSL#1418]
在gmssl中的ecdhe的实现，我看了下，sm2_do_ecdh中就是简单的把本方临时私钥与对方临时公钥相乘。   
与此对比，我还查看了Tongsuo(BaBaSSL) 以及 TASSL 的实现，两者在ecdhe的部分是完全一样的，都是严格按照 “GMT 0003.3-2012 SM2椭圆曲线公钥密码算法第3部分：密钥交换协议” 的部分来做的， 这三者在KeyExchange 消息传输上倒是都一样得，就是gmssl最后计算密钥的方式不同，无法互通。
    
我想问的是，这个没有统一标准的吗，还是某一方的实现有误？
按说这种类似rfc规范的国密规范，应该是要对每一步分操作完全准确定义的，但 "GMT 0024-2014 SSL VPN 技术规范" 中却没有明确解释， 这一部分有什么补充说明吗？实在是看得非常疑惑。

**Comment by guanzhi** [comment]
这是名字带来的误解。GM/T 0003.3提出了一个新协议，不同于ECDH或ECDHE，但是国密的标准中并没有给这个协议一个明确的缩写命名。GmSSL中`sm2_do_ecdh`这个函数的名字意思是在SM2曲线上做一个基本的ECDH密钥交换，使用的算法/协议是ECDH，而不是GM/T 0003.3。

但是对于某个实现来说，在实现一个名为`sm2_do_ecdh`的函数时，实现了GM/T 0003.3的算法/协议，也没什么问题，你可以理解这个函数实现了一个SM2的ECDH变体。

GmSSL在实现TLCP (GM/T 0024的后续国标标准）时只支持SM2公钥加密的套件，不支持ECDHE的套件，因此没有实现GM/T 0003.3的协议。

**Comment by muryliang** [comment]
明白了，感谢解答
