### ISSUE TITLE
sm9 是否已经基于国密局标准实现？

### ISSUE THREAD

**Issue by qishimafan** [guanzhi/GmSSL#146]
guanzhi大师，你好。
 请问sm9 是否已经基于国密局标准实现？ 鄙公司需要采购sm9 算法做邮件加密商用产品，以通过国密局产品验证。 方便的话请给个报价。联系qq： 6022605@qq.com.

**Comment by cryzefish** [comment]
已经实现，有需要的可以联系1291741371@qq.com！

**Comment by guanzhi** [comment]
已经给您回复邮件。

**Comment by zhangyuchi** [comment]
guanzhi老师，您好

我也有同样的关于sm9算法需求以通过国密局的产品验证，能否给一个报价或者更进一步的说明。联系方式：16378881@qq.com

**Comment by guanzhi** [comment]
没有报价，欢迎为GmSSL捐款
