### ISSUE TITLE
下载新的版本，编译报错啊 。。。。

### ISSUE THREAD

**Issue by sslvpn007** [guanzhi/GmSSL#147]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[1]: *** [crypto/gmapi/gmapi_sdf_ec.o] Error 1
make: *** [all] Error 2
bash-3.2$ 

===
no-sm9 也试过了

**Comment by zhaoxiaomeng** [comment]
可以先尝试编译 GmSSL-v1分支下的代码或者[release](https://github.com/guanzhi/GmSSL/releases)版本，我们尽快修复。

**Comment by sslvpn007** [comment]
@zhaoxiaomeng，您好，问下，现在的版本支持国密SSL VPN吗？

如不支持，估计什么时候能全面支持。现在急需这个功能，。
