### ISSUE TITLE
交叉编译mips版本报错：unrecognized command line option '-mrdrnd'

### ISSUE THREAD

**Issue by Ivan0325** [guanzhi/GmSSL#1479]
最新的3.1版本编译mips版本时报错，有人遇到过吗？
![image](https://user-images.githubusercontent.com/59823385/234210501-0475860a-383a-442d-8d21-263af169527a.png)

any1 have idea on this?

**Comment by zzl360** [comment]
这俩应该都是x64/x86特有的，mips不应该有这俩参数

**Comment by Ivan0325** [comment]
> 这俩应该都是x64/x86特有的，mips不应该有这俩参数

是的，屏蔽这俩编译选项，问题解决了
