### ISSUE TITLE
GmSSL-master在Ubuntu 16.04和CentOS 7.2以及CentOS 6.4中编译报错，请帮忙看一下

### ISSUE THREAD

**Issue by xiaohaowang** [guanzhi/GmSSL#148]
在Ubuntu 16.04下报错如下：
crypto/gmapi/gmapi_sdf_ec.c: In function 'SM2CiphertextValue_new_from_ECCCipher':
crypto/gmapi/gmapi_sdf_ec.c:316:13: error: too many arguments to function 'SM2CiphertextValue_new'
  if (!(cv = SM2CiphertextValue_new(group))) {
             ^
In file included from include/openssl/ec.h:30:0,
                 from crypto/gmapi/gmapi_sdf_ec.c:61:
include/openssl/sm2.h:102:24: note: declared here
 DECLARE_ASN1_FUNCTIONS(SM2CiphertextValue)
                        ^
include/openssl/asn1.h:247:15: note: in definition of macro 'DECLARE_ASN1_ALLOC_FUNCTIONS_name'
         type *name##_new(void); \
               ^
include/openssl/asn1.h:216:39: note: in expansion of macro 'DECLARE_ASN1_FUNCTIONS_name'
 # define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
                                       ^
include/openssl/sm2.h:102:1: note: in expansion of macro 'DECLARE_ASN1_FUNCTIONS'
 DECLARE_ASN1_FUNCTIONS(SM2CiphertextValue)
 ^
crypto/gmapi/gmapi_sdf_ec.c: In function 'SM2CiphertextValue_set_ECCCipher':
crypto/gmapi/gmapi_sdf_ec.c:393:43: error: dereferencing pointer to incomplete type 'SM2CiphertextValue {aka struct SM2CiphertextValue_st}'
  if (!BN_bin2bn(ref->x, ECCref_MAX_LEN, cv->xCoordinate)) {
                                           ^
crypto/gmapi/gmapi_sdf_ec.c:354:6: warning: variable 'nbytes' set but not used [-Wunused-but-set-variable]
  int nbytes;
      ^
crypto/gmapi/gmapi_sdf_ec.c: In function 'SM2CiphertextValue_get_ECCCipher':
crypto/gmapi/gmapi_sdf_ec.c:482:17: error: dereferencing pointer to incomplete type 'SM2CiphertextValue {aka const struct SM2CiphertextValue_st}'
  if (ref->L < cv->ciphertext_size) {
                 ^
Makefile:4032: recipe for target 'crypto/gmapi/gmapi_sdf_ec.o' failed
make[1]: *** [crypto/gmapi/gmapi_sdf_ec.o] Error 1
make[1]: Leaving directory '/home/postgres/Documents/GmSSL-master'
Makefile:128: recipe for target 'all' failed
make: *** [all] Error 2

CentOS 7.2中报错如下：
make[2]: Entering directory `/home/postgres/GmSSL-master'
Error: EVP_PKEY_get0_PAILLIER does not have a number assigned
LD_LIBRARY_PATH=:/usr/local/pgsql/lib gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl
/usr/bin/ld:crypto.map:1620: syntax error in VERSION script
collect2: error: ld returned 1 exit status
make[2]: *** [link_shlib.linux-shared] Error 1
make[2]: Leaving directory `/home/postgres/GmSSL-master'
make[1]: *** [libcrypto.so] Error 2
make[1]: Leaving directory `/home/postgres/GmSSL-master'
make: *** [all] Error 2

CentOS 6.4中报错如下：
In file included from include/openssl/gmapi.h:64,
                 from crypto/err/err_all.c:47:
include/openssl/sof.h:57: error: redefinition of typedef 'BOOL'
include/openssl/skf.h:66: note: previous declaration of 'BOOL' was here
make[1]: *** [crypto/err/err_all.o] Error 1
make[1]: Leaving directory `/home/highgo/GmSSL-master'
make: *** [all] Error 2

**Comment by xueyibing** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
编译同样错误
