### ISSUE TITLE
windows下clion编译总是找不到函数

### ISSUE THREAD

**Issue by zp405202476** [guanzhi/GmSSL#1497]
FAILED: bin/sm4test.exe 
cmd.exe /C "cd . && "E:\Program Files\CLion 2022.2\bin\mingw\bin\gcc.exe" -O3 -DNDEBUG  CMakeFiles/sm4test.dir/tests/sm4test.c.obj -o bin\sm4test.exe -Wl,--out-implib,bin\libsm4test.dll.a -Wl,--major-image-version,0,--minor-image-version,0  bin/libgmssl.dll.a  -lws2_32  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0xc0): undefined reference to `hex_to_bytes'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0xe1): undefined reference to `hex_to_bytes'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x102): undefined reference to `hex_to_bytes'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x123): undefined reference to `hex_to_bytes'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x147): undefined reference to `hex_to_bytes'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x178): more undefined references to `hex_to_bytes' follow
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x1fb): undefined reference to `sm4_set_encrypt_key'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x23e): undefined reference to `sm4_gcm_encrypt'
E:\Program Files\CLion 2022.2\bin\mingw\bin/ld.exe: CMakeFiles/sm4test.dir/tests/sm4test.c.obj:sm4test.c:(.text+0x2d0): undefined reference to `sm4_gcm_decrypt'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
是不是还是win32编译有误

**Comment by WennerChen** [comment]
在Win7+MinGW64-8.5.0环境中编译，出现类似的错误，显示数个undefined reference
