### ISSUE TITLE
国密的SM7算法目前有支持么？

### ISSUE THREAD

**Issue by zoopnin** [guanzhi/GmSSL#15]
国密的SM7算法目前有支持么？

**Comment by guanzhi** [comment]
不支持。
由于SM7的算法还没有公开，似乎也没有公开销售的SM7加密芯片，因此GmSSL无法提供软实现或者通过ENGINE支持硬件实现。GmSSL只是定义了SM7的算法OID `NID_sm7`。如果有SM7算法的公开描述文本，GmSSL可以提供SM7的软件实现和ECB/CBC/CTR等常用加密模式`EVP_CIPHER`模块(SM7似乎是分组密码)。
