### ISSUE TITLE
Cmake+vs2015+Win7编译3.1.0错误

### ISSUE THREAD

**Issue by WennerChen** [guanzhi/GmSSL#1502]
使用cmake+vs2015在win7系统中编译gmssl-3.1.0，使用cmakelists中的默认配置，编译时错误提示uint8_t重定义，size_t重定义

**Comment by kongleiqiang** [comment]
这个问题要怎么解决？

**Comment by kongleiqiang** [comment]
已解决，参考 visual studio中nmake编译工程报错 #1492
