### ISSUE TITLE
Windows10 vs2019 sm4test测试失败

### ISSUE THREAD

**Issue by Godli369** [guanzhi/GmSSL#1522]
test_sm4_ctr_update()测试部分失败：
G:\github\Git\GmSSL\GmSSL-master\tests\sm4test.c:614:test_sm4_ctr_update():
G:\github\Git\GmSSL\GmSSL-master\tests\sm4test.c:710:main():

也就是文件sm4test.c文件中下面这部分代码比较时不一致导致的测试失败
if (plen != mlen || memcmp(pbuf, mbuf, mlen) != 0) {
		error_print();
		return -1;
	}

请问是哪里的问题，Linux下可以正常运行通过。

**Comment by luckboa** [comment]
因为sm4test.c文件是UTF-8编码的，但其存在有中文注解(如596行)，可以将这文件修改为ANSI/GBK编码。
或者在CMakeLists.txt文件的357行后面增加target_compile_options(sm4test PRIVATE /utf-8)
