### ISSUE TITLE
请教大神，windows下编译GmSSL报错，如何解决

### ISSUE THREAD

**Issue by kevin-catlikepuma** [guanzhi/GmSSL#1533]
windows下编译：asn1.c和tls13.c 源码报错，如下。望大神解答，谢谢。
2>rsa.c
2>asn1.c
2>E:\DevC++\GmSSL-master\src\asn1.c(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
2>E:\DevC++\GmSSL-master\src\asn1.c(221,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(222,13): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(226,14): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(229,10): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(229,17): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(229,13): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(230,12): error C2065: “data”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(234,14): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(234,10): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(234,11): warning C4022: “memcpy”: 指针与实参 1 不匹配
2>E:\DevC++\GmSSL-master\src\asn1.c(234,20): error C2065: “data”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(234,16): warning C4022: “memcpy”: 指针与实参 2 不匹配
2>E:\DevC++\GmSSL-master\src\asn1.c(234,29): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(235,8): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(235,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(235,18): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(237,10): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(237,2): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(237,20): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(243,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(244,12): error C2065: “data”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(244,24): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(248,22): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(252,8): error C2065: “data”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(252,2): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(252,13): warning C4047: “=”:“int”与“const uint8_t *”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(253,16): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(254,19): error C2065: “datalen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(259,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(260,13): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(265,10): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(265,17): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(265,13): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(266,9): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(266,5): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(266,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(266,27): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(266,10): error C2106: “=”: 左操作数必须为左值
2>E:\DevC++\GmSSL-master\src\asn1.c(268,10): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(268,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(270,31): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(270,36): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(270,36): warning C4047: “函数”:“uint8_t **”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(270,33): warning C4024: “asn1_length_to_der”: 形参和实参 2 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(270,44): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(270,44): warning C4047: “函数”:“size_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(270,38): warning C4024: “asn1_length_to_der”: 形参和实参 3 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(275,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(276,13): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(281,8): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(282,11): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(290,10): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(290,17): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(290,13): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(291,9): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(291,5): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(291,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(291,27): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(291,10): error C2106: “=”: 左操作数必须为左值
2>E:\DevC++\GmSSL-master\src\asn1.c(293,10): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(293,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(296,31): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(296,36): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(296,36): warning C4047: “函数”:“uint8_t **”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(296,33): warning C4024: “asn1_length_to_der”: 形参和实参 2 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(296,44): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(296,44): warning C4047: “函数”:“size_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(296,38): warning C4024: “asn1_length_to_der”: 形参和实参 3 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(299,10): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(299,17): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(299,13): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(300,14): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(300,10): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(300,11): warning C4022: “memcpy”: 指针与实参 1 不匹配
2>E:\DevC++\GmSSL-master\src\asn1.c(300,17): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(300,16): warning C4022: “memcpy”: 指针与实参 2 不匹配
2>E:\DevC++\GmSSL-master\src\asn1.c(300,23): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(301,8): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(301,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(301,15): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(303,10): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(303,2): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(303,17): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(309,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(310,9): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(310,18): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(316,32): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(317,6): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(317,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(317,12): warning C4047: “=”:“int”与“void *”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(318,9): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(318,3): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(325,31): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(325,31): warning C4047: “函数”:“size_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(325,27): warning C4024: “asn1_length_from_der”: 形参和实参 1 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(331,5): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(331,2): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(331,10): warning C4047: “=”:“int”与“const uint8_t *”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(332,14): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(332,9): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(333,17): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(333,12): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(338,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(341,8): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(341,16): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,33): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,36): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,36): warning C4047: “函数”:“const uint8_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(345,35): warning C4024: “asn1_type_to_der”: 形参和实参 2 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(345,42): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,47): error C2065: “out”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,47): warning C4047: “函数”:“uint8_t **”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(345,44): warning C4024: “asn1_type_to_der”: 形参和实参 4 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(345,55): error C2065: “outlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(345,55): warning C4047: “函数”:“size_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(345,49): warning C4024: “asn1_type_to_der”: 形参和实参 5 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(353,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(356,35): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(356,38): error C2065: “d”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(356,38): warning C4047: “函数”:“const uint8_t **”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(356,37): warning C4024: “asn1_type_from_der”: 形参和实参 2 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(356,44): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(356,44): warning C4047: “函数”:“size_t *”与“int”的间接级别不同
2>E:\DevC++\GmSSL-master\src\asn1.c(356,40): warning C4024: “asn1_type_from_der”: 形参和实参 3 的类型不同
2>E:\DevC++\GmSSL-master\src\asn1.c(360,12): error C2065: “dlen”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(360,6): error C2100: 非法的间接寻址
2>E:\DevC++\GmSSL-master\src\asn1.c(368,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\asn1.c(369,11): error C2065: “tag”: 未声明的标识符
2>E:\DevC++\GmSSL-master\src\asn1.c(369,11): fatal error C1003: 错误计数超过 100；正在停止编译
2>hex.c

和
2>tls12.c
2>tls13.c
2>E:\DevC++\GmSSL-master\src\tls13.c(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
2>E:\DevC++\GmSSL-master\src\tls13.c(159,34): error C2373: “uint8_t”: 重定义；不同的类型修饰符
2>D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\stdint.h(22): message : 参见“uint8_t”的声明
2>E:\DevC++\GmSSL-master\src\tls13.c(159,42): warning C4228: 使用了非标准扩展: 忽略声明符列表中逗号后面的限定符
2>E:\DevC++\GmSSL-master\src\tls13.c(159,42): error C2143: 语法错误: 缺少“;”(在“*”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(159,51): error C2371: “size_t”: 重定义；不同的基类型
2>E:\DevC++\GmSSL-master\src\tls13.c : message : 参见“size_t”的声明
2>E:\DevC++\GmSSL-master\src\tls13.c(159,58): error C2146: 语法错误: 缺少“;”(在标识符“recordlen”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(159,69): error C2371: “size_t”: 重定义；不同的基类型
2>E:\DevC++\GmSSL-master\src\tls13.c : message : 参见“size_t”的声明
2>E:\DevC++\GmSSL-master\src\tls13.c(159,76): error C2146: 语法错误: 缺少“;”(在标识符“padding_len”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(160,2): error C2371: “uint8_t”: 重定义；不同的基类型
2>D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\stdint.h(22): message : 参见“uint8_t”的声明
2>E:\DevC++\GmSSL-master\src\tls13.c(160,10): error C2143: 语法错误: 缺少“;”(在“*”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(160,25): error C2371: “size_t”: 重定义；不同的基类型
2>E:\DevC++\GmSSL-master\src\tls13.c : message : 参见“size_t”的声明
2>E:\DevC++\GmSSL-master\src\tls13.c(160,32): error C2143: 语法错误: 缺少“;”(在“*”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(160,48): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(161,1): error C2054: 在“enced_recordlen”之后应输入“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(1036,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
2>E:\DevC++\GmSSL-master\src\tls13.c(1785,27): warning C4013: “tls13_record_encrypt”未定义；假设外部返回 int
2>E:\DevC++\GmSSL-master\src\tls13.c(1898,1): error C2143: 语法错误: 缺少“;”(在“{”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(1919,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
2>E:\DevC++\GmSSL-master\src\tls13.c(1975,43): error C2198: “tls_record_get_handshake_client_hello”: 用于调用的参数太少
2>E:\DevC++\GmSSL-master\src\tls13.c(2019,3): error C2059: 语法错误:“do”
2>E:\DevC++\GmSSL-master\src\tls13.c(2024,2): error C2059: 语法错误:“if”
2>E:\DevC++\GmSSL-master\src\tls13.c(2028,16): error C2143: 语法错误: 缺少“)”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2028,16): error C2143: 语法错误: 缺少“{”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2028,16): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2028,52): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2031,14): error C2143: 语法错误: 缺少“)”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2031,14): error C2143: 语法错误: 缺少“{”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2031,14): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2031,71): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,45): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,56): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,57): error C2146: 语法错误: 缺少“)”(在标识符“null_dgst_ctx”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,57): error C2061: 语法错误: 标识符“null_dgst_ctx”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,57): error C2059: 语法错误:“;”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,70): error C2059: 语法错误:“,”
2>E:\DevC++\GmSSL-master\src\tls13.c(2033,88): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,56): error C2059: 语法错误:“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,57): error C2146: 语法错误: 缺少“)”(在标识符“uint8_t”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,11): error C2084: 函数“int tls13_hkdf_extract(const DIGEST *,const uint8_t *,const uint8_t *,uint8_t *)”已有主体
2>E:\DevC++\GmSSL-master\src\tls13.c(381): message : 参见“tls13_hkdf_extract”的前一个定义
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,66): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,67): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2034,105): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,49): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,65): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,66): error C2146: 语法错误: 缺少“)”(在标识符“dgst_ctx”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,66): error C2061: 语法错误: 标识符“dgst_ctx”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,66): error C2059: 语法错误:“;”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,74): error C2059: 语法错误:“,”
2>E:\DevC++\GmSSL-master\src\tls13.c(2035,107): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,49): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,65): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,66): error C2146: 语法错误: 缺少“)”(在标识符“dgst_ctx”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,66): error C2061: 语法错误: 标识符“dgst_ctx”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,66): error C2059: 语法错误:“;”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,74): error C2059: 语法错误:“,”
2>E:\DevC++\GmSSL-master\src\tls13.c(2036,107): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,49): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,60): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,61): error C2146: 语法错误: 缺少“)”(在标识符“null_dgst_ctx”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,61): error C2061: 语法错误: 标识符“null_dgst_ctx”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,61): error C2059: 语法错误:“;”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,74): error C2059: 语法错误:“,”
2>E:\DevC++\GmSSL-master\src\tls13.c(2037,89): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,67): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2059: 语法错误:“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2143: 语法错误: 缺少“)”(在“(”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2143: 语法错误: 缺少“)”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2091: 函数返回函数
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2143: 语法错误: 缺少“{”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,74): error C2059: 语法错误:“常数”
2>E:\DevC++\GmSSL-master\src\tls13.c(2040,103): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2041,31): error C2143: 语法错误: 缺少“)”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2041,31): error C2143: 语法错误: 缺少“{”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2041,31): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2041,80): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,67): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2059: 语法错误:“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2143: 语法错误: 缺少“)”(在“(”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2143: 语法错误: 缺少“)”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2091: 函数返回函数
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2143: 语法错误: 缺少“{”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,73): error C2059: 语法错误:“常数”
2>E:\DevC++\GmSSL-master\src\tls13.c(2042,107): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2043,13): error C2143: 语法错误: 缺少“)”(在“->”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2043,13): error C2143: 语法错误: 缺少“{”(在“->”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2043,13): error C2059: 语法错误:“->”
2>E:\DevC++\GmSSL-master\src\tls13.c(2043,35): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,67): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2059: 语法错误:“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2143: 语法错误: 缺少“)”(在“(”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2143: 语法错误: 缺少“)”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2091: 函数返回函数
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2143: 语法错误: 缺少“{”(在“常数”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,74): error C2059: 语法错误:“常数”
2>E:\DevC++\GmSSL-master\src\tls13.c(2045,103): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2046,31): error C2143: 语法错误: 缺少“)”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2046,31): error C2143: 语法错误: 缺少“{”(在“&”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2046,31): error C2059: 语法错误:“&”
2>E:\DevC++\GmSSL-master\src\tls13.c(2046,80): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2047,67): error C2059: 语法错误:“字符串”
2>E:\DevC++\GmSSL-master\src\tls13.c(2047,73): error C2059: 语法错误:“(”
2>E:\DevC++\GmSSL-master\src\tls13.c(2047,73): error C2143: 语法错误: 缺少“)”(在“(”的前面)
2>E:\DevC++\GmSSL-master\src\tls13.c(2047,73): error C2059: 语法错误:“)”
2>E:\DevC++\GmSSL-master\src\tls13.c(2047,73): fatal error C1003: 错误计数超过 100；正在停止编译
2>file.c

**Comment by GavynG** [comment]
please check this: #1492

**Comment by kevin-catlikepuma** [comment]
非常感谢，已解决

**Comment by hailangljb** [comment]
怎么解决的
