### ISSUE TITLE
编译出错，centos 6

### ISSUE THREAD

**Issue by ugenehan** [guanzhi/GmSSL#155]
In file included from include/openssl/gmapi.h:64,
                 from crypto/err/err_all.c:47:
include/openssl/sof.h:57: error: redefinition of typedef 'BOOL'
include/openssl/skf.h:66: error: previous declaration of 'BOOL' was here

**Comment by yuanzh78** [comment]
#include<openssl/skf.h>
这种代码问题自己改下就可以了
只是奇怪这种明显的问题代码怎么merge上去的

**Comment by ugenehan** [comment]
不同版本下，不同错误，这个是在centos 7下的错误，只是截取了一部分
crypto/gmapi/gmapi_skf_ec.c:421:35: error: dereferencing pointer to incomplete type
  memcpy(blob->HASH, cv->mactag, cv->mactag_size);
                                   ^
crypto/gmapi/gmapi_skf_ec.c:423:8: error: dereferencing pointer to incomplete type
  if (cv->ciphertext_size <= 0) {
        ^
crypto/gmapi/gmapi_skf_ec.c:428:25: error: dereferencing pointer to incomplete type
  memcpy(blob->Cipher, cv->ciphertext, cv->ciphertext_size);
                         ^
crypto/gmapi/gmapi_skf_ec.c:428:41: error: dereferencing pointer to incomplete type
  memcpy(blob->Cipher, cv->ciphertext, cv->ciphertext_size);

**Comment by cqchengdan** [comment]
我在CentOS6里面编译也遇到了一大堆问题，请问楼主编译成功了吗，分享一下经验呗

**Comment by ugenehan** [comment]
根据错误提示，修改源代码

**Comment by guanzhi** [comment]
Linux编译问题请移至 #398
