### ISSUE TITLE
动态库连接问题

### ISSUE THREAD

**Issue by Dolphin92** [guanzhi/GmSSL#1554]
undefined reference to `gmssl_secure_clear(void*, unsigned long)'

已经用了-lgmssl

**Comment by Dolphin92** [comment]
@guanzhi

**Comment by lixianshang** [comment]
> undefined reference to `gmssl_secure_clear(void*, unsigned long)'
> 
> 已经用了-lgmssl

can you tell me how did you solve  this problem?
