### ISSUE TITLE
不能做 sm2_sm3的证书了

### ISSUE THREAD

**Issue by yuanzh78** [guanzhi/GmSSL#156]
搞不清哪里出问题的，以前已经做出sm2sign_with_sm3了，现在失败，把release版本都重新下了编译都一样的错
[root@localhost gmcert]# ./gmssl ecparam -out gmca_sm2.key -name sm2p256v1 -genkey
[root@localhost gmcert]# ./gmssl req -new -key gmca_sm2.key -out gmca_sm2.csr -sm3 
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [CN]:
Common Name (eg, your name or your server's hostname) []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
140636594882304:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:
[root@localhost gmcert]# 

../crypto/objects/obj_dat.h:    1128,    /* OBJ_sm2sign_with_sm3             1 2 156 10197 1 501 */
签名id也是定义了的

**Comment by yuanzh78** [comment]
找到一个旧版，加上ZA可以做sm2_sm3证书，可以被验证

**Comment by 1132719438** [comment]
@yuanzh78 同样的问题，你用的是什么版本

**Comment by ugenehan** [comment]
同样问题，2.0版本

**Comment by 609685846** [comment]
@yuanzh78 能否发个可以做SM2_SM3的BIN文件，跪求！！！！或者请教下如何添加ZA

**Comment by yudongf** [comment]
@yuanzh78 遇到同样的问题，你后来使用的是那个版本？

**Comment by yuanzh78** [comment]
抱歉很长时间没回复，这是在旧版本上改造的添加了ZA，各种证书测试无误

[GmSSL_withZA_sm2_sm3_cert.2017.08.20.tgz.zip](https://github.com/guanzhi/GmSSL/files/1335445/GmSSL_withZA_sm2_sm3_cert.2017.08.20.tgz.zip)

**Comment by yuanzh78** [comment]
另外本人处于对现状很无奈的状况， 想找个兼职

**Comment by yuanzh78** [comment]
这个国内开源项目看来很难维持和更新，没办法
