### ISSUE TITLE
SM2验签

### ISSUE THREAD

**Issue by gczhcm** [guanzhi/GmSSL#1562]
明文：SWRzS2ZHbVNSMTU1Nzk5NjUx44190100002000000001
签名base64:MEUCIGs1kH5j04B4+yDBY5iXZI4x3JjnphjF8WnoB4T3seCjAiEA3w7kNw05BbXh8I+cQYb9j6hjmRZf67aLPUt7P/Povdc=
证书：-----BEGIN CERTIFICATE-----
MIIB8zCCAZmgAwIBAgIMGvT17vlSl/s9J/w4MAoGCCqBHM9VAYN1MGMxCzAJBgNV
BAYTAkNOMRIwEAYDVQQIEwlHdWFuZ2RvbmcxEjAQBgNVBAcTCUd1YW5nemhvdTEP
MA0GA1UEChMGRXNob3JlMQswCQYDVQQLEwJaRjEOMAwGA1UEAxMFU3ViQ0EwHhcN
MjMwOTA4MDY1ODU1WhcNMjQwOTA3MDY1ODU1WjCBgzELMAkGA1UEBhMCQ04xCTAH
BgNVBAgTADEJMAcGA1UEBxMAMQkwBwYDVQQKEwAxCTAHBgNVBAsTADEdMBsGA1UE
AxMUNDQxOTUxNTA4MTExODcxMTEwMDQxKTAnBgNVBAUTIGMzYmJjNmVhYTUwMGUx
MTVjZTc1MTcyZmU3OTA0MmNmMFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEL0Hx
fSS8xmIH8DQQN+fNklpIeYxH7DQGX3FXqX8aFmDsgeGQNwHQFYfguCeYEZsdybCa
ArE8XACH5C581FpoBqMSMBAwDgYDVR0PAQH/BAQDAgeAMAoGCCqBHM9VAYN1A0gA
MEUCIQCGhrBJH0E0z/Fo7+1BfkklqddDsi5ov8SxE1lqlcn8zAIgB2BSZBm1WkYB
7+Jhbx143LuvVCQpkF/iwEK32eRjdsA=
-----END CERTIFICATE-----
请问如何验签，用sm2verify 无法验签通过

**Comment by lpilp** [comment]
你这个公钥是证书使用的公钥，相当于是 pkcs8的，需要转换成 更简单的公钥 类似pkcs1, 
给你转好了，你试试
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEL0HxfSS8xmIH8DQQN+fNklpIeYxH
7DQGX3FXqX8aFmDsgeGQNwHQFYfguCeYEZsdybCaArE8XACH5C581FpoBg==
-----END PUBLIC KEY-----
```

**Comment by gczhcm** [comment]
试过，计算的r 和r'跟直接使用证书计算的是一样的

**Comment by gczhcm** [comment]
> 你这个公钥是证书使用的公钥，x509证书 ,里面包含着证书相关的信息，如主题的OU，签发者的OU，证书算法，签名算法等一系列的信息 ，这边使用的时候不需要这些信息，需要转换成 更简单的公钥 类似pkcs1, 里面主要包含三个信息，密钥类型（ecPublicKey），算法（sm2）， 公钥 给你转好了，你试试
> 
> ```
> -----BEGIN PUBLIC KEY-----
> MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEL0HxfSS8xmIH8DQQN+fNklpIeYxH
> 7DQGX3FXqX8aFmDsgeGQNwHQFYfguCeYEZsdybCaArE8XACH5C581FpoBg==
> -----END PUBLIC KEY-----
> ```

**Comment by lpilp** [comment]
你是不是按demo的用法然后报了错误
```
/GmSSL-3.1.0/src/sm2_lib.c:286:sm2_verify():
/GmSSL-3.1.0/src/sm2_lib.c:444:sm2_verify_finish():
sm2verify: inner error
```
我这边也一样，不过你这个签名，用其他语言试了倒是正确的，也不知道怎么用

**Comment by gczhcm** [comment]
> 用其他语言试了倒是正确的
是的，echo 'SWRzS2ZHbVNSMTU1Nzk5NjUx44190100002000000001'|./gmssl sm2verify -cert nvr_sig_c3bbc6e.pem  -sig sm211.sig  -id '1234567812345678'，其他语言正确，是指gmssl的其他语言版本吗？

**Comment by lpilp** [comment]
> 

不是，gmssl生成的私钥有密码的，在使用中是不方便的，网上有很多各种语言开源的

**Comment by gczhcm** [comment]
> > 
> 
> 不是，gmssl生成的私钥有密码的，在使用中是不方便的，网上有很多各种语言

**Comment by lpilp** [comment]
找到问题了，不是我们的错误是 gmssl 的问题，
sm2_lib.c中的 320开始，计算Z值的方法和标准方法有异常
```
sm3_init(&ctx);
	if (strcmp(id, SM2_DEFAULT_ID) == 0) {
		sm3_update(&ctx, zin, sizeof(zin));
	} else {
		uint8_t idbits[2];
		idbits[0] = (uint8_t)(idlen >> 5);
		idbits[1] = (uint8_t)(idlen << 3);
		sm3_update(&ctx, idbits, 2);
		sm3_update(&ctx, (uint8_t *)id, idlen);
		sm3_update(&ctx, zin + 18, 32 * 6);
	}
	sm3_finish(&ctx, z);
```
这边如果id值为缺省值，那么做sm3 hash的时候就相当于把  id 给丢了， 而标准算法无论id什么值都会计算到Z值里的，所以如果你不是用gmssl的算法生成的签名，且缺省id (1234567812345678)的时候，就会s 不匹配了， 当id不是缺省值的时候，那个demo的用户应该是可以的

**Comment by gczhcm** [comment]
<img width="834" alt="1694597560384" src="https://github.com/guanzhi/GmSSL/assets/18482740/83593891-fbe7-4655-a00b-80844e1ed3a8">
`while ((len = fread(buf, 1, sizeof(buf), infp)) > 0) {
		if (sm2_verify_update(&verify_ctx, buf, len) != 1) {
			fprintf(stderr, "%s: inner error\n", prog);
			goto end;
		}`
这里len会把字符串的结束符‘\0’,读进去，用strlen就可以了

**Comment by lpilp** [comment]
上面是我看错了，在zin 里把  default id放进去了，
你指出的这个问题，好像有人提人，当时问的是sm3 字符串与含有字符串的文件为什么不一样，就是把 \0给读进去了，忘记这一茬了
