### ISSUE TITLE
提供一个命令，改window代码在linux下换行显示 ^M

### ISSUE THREAD

**Issue by yuanzh78** [guanzhi/GmSSL#157]
gmssl目录下
 # find|grep "\\.h"|xargs dos2unix
 # find|grep "\\.c"|xargs dos2unix

dos2unix命令没有的话安装一个，因为看有些代码是windows传到linux下有换行显示问题。

**Comment by yuanzh78** [comment]
有问题啊，系统把转义符 \弄掉了 
应该是  "\.h"

**Comment by yuanzh78** [comment]
有问题啊，系统把转义符 \弄掉了
应该是 "\\.h" "\\.c"

**Comment by QwertyJack** [comment]
直接`find . -name "*.h" -o -name "*.c"`就行了啊，不用先`find`再`grep`。
