### ISSUE TITLE
请教下国密标准GM/T-0024 SSL握手的实现

### ISSUE THREAD

**Issue by AivenYoung** [guanzhi/GmSSL#158]
基于算法ECC_SM4_SM3，握手的消息顺序一般是1，client hello,
2， server hello, server certificate, server key exchange, server hello done
3，client key exchange ,[change cipher spec],finished
4，[change cipher sped],finished
其中第二步的消息中,server key exchange 是否可以舍弃，不理解这个消息有何用，谁能解释下呢？ 因为server certificate中已经存在server端公钥，client端将premaster key使用该公钥加密传输给server，即可完成premaster key的共享。

此外，哪里可以获取到用于验证ssl握手的SM2证书链以及对应的私钥呢？ 使用360浏览器测试怀疑不被信任。

**Comment by gmfix001x** [comment]
国密SSL 实现了吗？ 你用的哪个版本？是什么系统？win？还是mac？还是Linux？

**Comment by conezxy** [comment]
Server KeyExchange不能省略，否则无法证明服务端拥有签名私钥。

**Comment by AivenYoung** [comment]
@gmfix001x 我是在基于openssl开发，开发进行中。
@conezxy 多谢您的指点。
