### ISSUE TITLE
请问这个版本的sm2签名和验证的实现和openssl的sm2实现有什么区别啊。

### ISSUE THREAD

**Issue by LWCjack** [guanzhi/GmSSL#1588]
rt

**Comment by lpilp** [comment]
我看到的openssl只实现了 sm3,sm4， sm2只实现了相关的椭圆，但并没有实现签名与验签的样子，你使用的opensll是哪个版本，相关的命令行是什么

**Comment by LWCjack** [comment]
还想问下，这个SM2的椭圆曲线的参数a、b是在哪里定义的呀。

**Comment by LWCjack** [comment]
好的谢谢您的耐心解答。

**Comment by LWCjack** [comment]
> include/gmssl/sm2_alg.c 数据是标准的sm2参数，没有不同

![image](https://github.com/guanzhi/GmSSL/assets/149768809/93795d16-1984-4eae-95b8-ff74b0fad8e9)
您好，貌似标准的sm2椭圆曲线的参数是上面这个吧，但是，我看了sm2_alg.c里面文件的参数，好像一个都对不上，是我理解的有问题吗？

**Comment by LWCjack** [comment]
这个是sm2_algc.c里面的所有的const参数。
![image](https://github.com/guanzhi/GmSSL/assets/149768809/15370ea4-feff-4ca3-828e-518cf2e8e9ac)


> include/gmssl/sm2_alg.c 数据是标准的sm2参数，没有不同

**Comment by lpilp** [comment]
亲，一样的啊，你再看看，C的这个是高位在数组后面，低位在前面，你由后向前看

**Comment by LWCjack** [comment]
> 亲，一样的啊，你再看看，C的这个是高位在数组后面，低位在前面，你由后向前看

懂了，谢谢您的解答。
