### ISSUE TITLE
请教调用GmSSL sm2签名/验签 命令行时的签名者的可辨别标识字串及HASH算法配置

### ISSUE THREAD

**Issue by mxlmeng** [guanzhi/GmSSL#159]
1）签名时使用如下命令行：
gmssl pkeyutl -sign -pkeyopt ec_sign_algor:sm2 -inkey signkey.pem  -in <yourfile> -out <yourfile>.sig
得到的结果，使用的 签名者的可辨别标识字串 是哪一个：SM2_DEFAULT_ID_GMT09	，SM2_DEFAULT_ID_GMSSL？ 命令行界面是否可以指定 该标识字串的值？
使用的HASH算法 是SM3 吗？ 如何配置使用指定的HASH算法？
2）是否支持 sm2加解密命令行，如果支持是否有例子可以参考？

**Comment by guanzhi** [comment]
1. 默认ID没有参与运算
2. 加密解密也是使用 pkeyutl 完成的，v1代码demo/gmssl 目录中有 gmssl.sh 中包含加解密的例子

**Comment by sanderchen** [comment]
关老师，你好，你这个回答是指目前通过命令行无法传入自定义的签名ID是么？

**Comment by zhaoxiaomeng** [comment]
@mxlmeng 
gmssl pkeyutl -encrypt -pkeyopt ec_scheme:sm2 -pkeyopt ec_encrypt_param:sm3 -pubin -inkey sm2    pubkey.pem > sm2ciphertext.bin
cat sm2ciphertext.bin |  gmssl pkeyutl -decrypt -inkey sm2key.pem -pkeyopt ec_scheme:sm2 -pkeyopt ec_encrypt_param:sm3
