### ISSUE TITLE
ECC_SM4_SM3密码套件理解

### ISSUE THREAD

**Issue by ixp2xxx** [guanzhi/GmSSL#160]
ECC_SM4_SM3可以理解为类似RSA密钥交换协议，只是使用SM2签名、验签，并使用SM2证书吗？
还是要参考"GM/T 0003 SM2椭圆曲线公钥密码算法-第-3-部分：密钥交换协议"去实现，这样的那就需要请求发送客户端证书。但360浏览器和boc服务器之间交换的时候并没有看到客户端证书哦。
请各位指点。谢谢！

**Comment by ixp2xxx** [comment]
ssl vpn规范中没有明确SM2密钥交换协议。我想多了。:)

**Comment by conezxy** [comment]
**ECC-SM4-SM3**
对应GM/T 0003 SM2椭圆曲线公钥密码算法-第-4-部分：公钥加密算法
由于只需要使用服务端加密公钥，因此可以在客户端无证书的情况下使用（单向认证）

**ECDHE-SM4-SM3**
对应GM/T 0003 SM2椭圆曲线公钥密码算法-第-3-部分：密钥交换协议
需要使用双方的加密公私钥，因此必须在客户端有证书的情况下使用（双向认证，也即客户端认证）

**Comment by ixp2xxx** [comment]
@conezxy 谢谢解惑，这样就理解了。

**Comment by yunlai** [comment]
抓包看360国密，密钥交换好像并不遵守GM/T 0003的规范，而是类似RSA，这是为什么呢
