### ISSUE TITLE
能否提供编译好的gmssl供下载呢

### ISSUE THREAD

**Issue by kimqcn** [guanzhi/GmSSL#161]
看来大伙儿编译遇到好多问题，为啥不提供编译好的版本供大家下载呢？

**Comment by gmfix001x** [comment]
首先必须为关老师等人的努力点万个赞。

对于楼主的想法，比较赞同。

希望先提供一个完整的版本，可以编译的，功能完善的。

其实完全可以提供在一个平台（如mac）的全面支持。

**Comment by guanzhi** [comment]
我们争取在五一后提供一套Mac版的命令行工具和库。

**Comment by kimqcn** [comment]
我在https://github.com/davidmr001/GmSSL下载了v1.2.1版，ubuntu14.04下编译biu的一下就通过了，
下载地址：
http://pan.baidu.com/s/1nvfV54d
windows下我没装vs2013，希望编译通过的同学分享。

**Comment by 27954741** [comment]
1.3版本也编译通过,centos和ubuntu,但在使用中出现各种错误.
跪求2.x版本的

**Comment by gmfix001x** [comment]
感谢大家的分享。

**Comment by 27954741** [comment]
vs2013下面编译成功. gmssl1.3的版本

**Comment by dlynine** [comment]
@27954741 能把编译好的windows版发下吗？非常感谢
