### ISSUE TITLE
SM9签名中的密码函数H1

### ISSUE THREAD

**Issue by donaldlim** [guanzhi/GmSSL#1613]
规范中的步骤和代码中的实现差异很大，请确认一下，谢谢！
![image](https://github.com/guanzhi/GmSSL/assets/40256742/62d41c94-3208-45d1-913d-698a19673d72)
![image](https://github.com/guanzhi/GmSSL/assets/40256742/e425eb31-dc7d-4c1d-ba6d-dcb3a39d75e6)

**Comment by emmansun** [comment]
步骤2 **hlen** 计算结果是多少？应该是40，对吧。步骤3 就是 i 从 1到2执行。实现中只是把循环取消、简化一下而已。

**Comment by donaldlim** [comment]
> 步骤2 **hlen** 计算结果是多少？应该是40，对吧。步骤3 就是 i 从 1到2执行。实现中只是把循环取消、简化一下而已。

OK，谢谢~
