### ISSUE TITLE
WINDOWS平台编译错误

### ISSUE THREAD

**Issue by HWen37** [guanzhi/GmSSL#162]
64位WIN10系统编译32位库
按照教程编译会报错：
'ms\do_ms' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
查百度知道现在openssl不再需要这一步，直接nmake就行。
所以编译步骤就两步：
1.perl Configure VC-WIN32 no-asm --prefix=e:\openssl
1.nmake
报如下错误，看着是代码有问题：
crypto\gmapi\gmapi_sdf_ec.c(316) : warning C4087: “SM2CiphertextValue_new”: 用“void”参数列表声明
crypto\gmapi\gmapi_sdf_ec.c(393) : error C2037: “xCoordinate”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(393) : error C2198: “BN_bin2bn”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(398) : error C2037: “yCoordinate”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(398) : error C2198: “BN_bin2bn”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(404) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(405) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(411) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(411) : warning C4133: “函数”: 从“BIGNUM *”到“EC_POINT *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(411) : warning C4133: “函数”: 从“BN_CTX *”到“const BIGNUM *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(411) : error C2198: “EC_POINT_set_affine_coordinates_GFp”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(416) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(416) : warning C4133: “函数”: 从“BIGNUM *”到“const EC_POINT *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(416) : warning C4133: “函数”: 从“BN_CTX *”到“BIGNUM *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(416) : error C2198: “EC_POINT_get_affine_coordinates_GF2m”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(422) : error C2037: “mactag_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(423) : error C2037: “mactag”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(423) : warning C4022: “memcpy”: 指针与实参 2 不匹配
crypto\gmapi\gmapi_sdf_ec.c(423) : error C2168: “memcpy”: 内部函数的实参太少
crypto\gmapi\gmapi_sdf_ec.c(430) : error C2037: “ciphertext_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(432) : error C2037: “ciphertext”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(432) : warning C4022: “CRYPTO_realloc”: 指针与实参 1 不匹配
crypto\gmapi\gmapi_sdf_ec.c(432) : warning C4047: “函数”:“size_t”与“char [28]”的间接级别不同
crypto\gmapi\gmapi_sdf_ec.c(432) : warning C4024: “CRYPTO_realloc”: 形参和实参 2 的类型不同
crypto\gmapi\gmapi_sdf_ec.c(432) : warning C4047: “函数”:“const char *”与“int”的间接级别不同
crypto\gmapi\gmapi_sdf_ec.c(432) : warning C4024: “CRYPTO_realloc”: 形参和实参 3 的类型不同
crypto\gmapi\gmapi_sdf_ec.c(432) : error C2198: “CRYPTO_realloc”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(437) : error C2037: “ciphertext”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(437) : warning C4022: “memcpy”: 指针与实参 2 不匹配
crypto\gmapi\gmapi_sdf_ec.c(437) : error C2168: “memcpy”: 内部函数的实参太少
crypto\gmapi\gmapi_sdf_ec.c(482) : error C2037: “ciphertext_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(513) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(513) : warning C4133: “函数”: 从“BIGNUM *”到“const EC_POINT *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(513) : warning C4133: “函数”: 从“BN_CTX *”到“BIGNUM *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(513) : error C2198: “EC_POINT_get_affine_coordinates_GFp”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(518) : error C2037: “ephem_point”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(518) : warning C4133: “函数”: 从“BIGNUM *”到“const EC_POINT *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(518) : warning C4133: “函数”: 从“BN_CTX *”到“BIGNUM *”的类型不兼容
crypto\gmapi\gmapi_sdf_ec.c(518) : error C2198: “EC_POINT_get_affine_coordinates_GF2m”: 用于调用的参数太少
crypto\gmapi\gmapi_sdf_ec.c(548) : error C2037: “mactag_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(553) : error C2037: “mactag”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(553) : error C2037: “mactag_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(553) : error C2168: “memcpy”: 内部函数的实参太少
crypto\gmapi\gmapi_sdf_ec.c(556) : error C2037: “ciphertext_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(561) : error C2037: “ciphertext_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(562) : error C2037: “ciphertext”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(562) : error C2037: “ciphertext_size”的左侧部分指定未定义的结构/联合“SM2CiphertextValue_st”
crypto\gmapi\gmapi_sdf_ec.c(562) : error C2168: “memcpy”: 内部函数的实参太少
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.

**Comment by gmfix001x** [comment]
不知道 你下载的是什么版本

反正2.x的版本，肯定不行。

因为 目录ms下，就没有do_ms这个文件

**Comment by RundongYang** [comment]
请问现在有人解决吗 这个问题。我也遇到再Windows下编译不过的问题，求大神解答

**Comment by sslvpn007** [comment]
win下的，可以尝试用gmsslV1 的版本。

但这个版本，我试了下 有问题。

与国密的标准有距离。

我用ssl23 这个试了下，验证不了sm2的证书。

还要自己去改openssl里的底层代码。

相当复杂。尝试了下，放弃了。

**Comment by maxzlf** [comment]
同样的 windows 平台编译错误
![image](https://user-images.githubusercontent.com/8374236/27414655-472f4ca4-5735-11e7-9653-4de412363d6a.png)
![image](https://user-images.githubusercontent.com/8374236/27414666-59277d46-5735-11e7-8264-1ca5b39b4b90.png)
