### ISSUE TITLE
gmssl jni调用出错

### ISSUE THREAD

**Issue by 27954741** [guanzhi/GmSSL#163]
各位好:
          在编译和调用GMSSL Java Wrapper时候出现以下情况:
          1.分别在CentOS6.8,Ubuntu1604上编译GMSSL Java Wrapper,都可以出来.so文件,但都有报警,如下,
GmSSL.c: In function ‘Java_GmSSL_getVersion’:
GmSSL.c:73:35: warning: implicit declaration of function ‘OpenSSL_version’ [-Wimplicit-function-declaration]
  return (*env)->NewStringUTF(env, OpenSSL_version(type));
                                   ^
GmSSL.c:73:35: warning: passing argument 2 of ‘(*env)->NewStringUTF’ makes pointer from integer without a cast [-Wint-conversion]
GmSSL.c:73:35: note: expected ‘const char *’ but argument is of type ‘int’
         编译的过程没有err,也出了gmssl.so,后面在代码中调用的时候出现问题.
        2. jdk1.7,myeclpse2013
        把gmssl.so加入到java的library,如/usr/lib下,
       java代码:System.loadLibrary("gmssl");
      报错: no gmssl in java.library.path
      调整java代码,使用绝对路径: System.load("/gmssl/gmssl.so");
      报错: java: symbol lookup error: /gmssl/gmss.so undefined symbol: OpenSSL_version

      使用的GmSSL版本: GmSSL 1.3.0 - OpenSSL 1.0.2d
      请问是什么情况,该如何编译和调用Gmssl的java wrapper
谢谢

**Comment by xinlong-song** [comment]
你好，请问你编译源码后自动生成gmssl.so文件了吗？

**Comment by 27954741** [comment]
是的,我编译了GmSSL 1.3.0版本,在做jni调用的时候报错

**Comment by hloser** [comment]
楼主搞定了么，这两天开始要做gmssl相关的，一脸懵逼啊

**Comment by 27954741** [comment]
已解决,关贴

**Comment by kiddingquan** [comment]
请问，你是怎么解决这个问题的呢，我现在也遇到这个问题，报错：undefined symbol: OpenSSL_version，并且加密的方法返回的总是null值

**Comment by knull-cn** [comment]
我碰上过类似的问题，不知道对不对：

**Comment by dajiangzhong** [comment]
Linux 环境下，使用前设置环境变量LD_LIBRARY_PATH指向libgmssljni.so的地址，即 $:export LD_LIBRARY_PATH=$location_of_libgmssljni.so

**Comment by 31308836** [comment]
绝对路径和LD_LIBRARY_PATH 相对路径都试过还是不行呢？输入命令gmssl version是正确的
