### ISSUE TITLE
目前版本支持SSL通信只有国密算法？其他算法不兼容吗

### ISSUE THREAD

**Issue by wuzhongyuanking** [guanzhi/GmSSL#164]
根据测试目前SSL通信使用到算法
ECDHE-SM2-SM4-SM3
SM2-SM4-SM3
IDEA-CBC-MD5
RC2-CBC-MD5
RC4-MD5
DES-CBC3-MD5
DES-CBC-MD5
EXP-RC2-CBC-MD5
EXP-RC4-MD5
比原先openssl支持的还少了，原来的秘钥证书都不支持了。
s3_lib.c里面注释了大部分算法。放开之后国密算法又不支持了。
问下老师有什么解决方法？

**Comment by dgyx** [comment]
您好！
         我也正在测试国密通讯，但是通讯有一些问题，能否麻烦您提供一份server和client的demo供参考，非常感谢。我的邮箱，omni.dgyx@gmail.com。

**Comment by wuzhongyuanking** [comment]
你用他自带的gmssl  s_server -accept 2009 -key server.pem -cert server.pem
gmssl  s_client -connect localhost:2009 命令测试吧，这个库到处感觉都是bug，另外你想调用国密的话
int nid = NID_X9_62_prime256v1;
	EC_KEY* ecdh = EC_KEY_new_by_curve_name(nid);
	if (ecdh == NULL) {
		printf("unable to create curve\n");
	}
	SSL_CTX_set_tmp_ecdh(g_sslctx, ecdh);
	SSL_CTX_set_options(g_sslctx, SSL_OP_SINGLE_ECDH_USE);
	EC_KEY_free(ecdh);
要加这段代码，这是我研究好几天才得出来的

**Comment by dgyx** [comment]
我试下，非常感谢！

**Comment by sslvpn007** [comment]
问下楼主，你国密ssl 通信，都通了吗？

具体在那个平台？（win ，mac，linux），用的那个gmssl版本

**Comment by wuzhongyuanking** [comment]
win ，linux都可以，但是EDCHE-SM2-SM4-SM3可以，其他算法在调。。用的就是最新的gmssl-v1

**Comment by sslvpn007** [comment]
ffxtest.c
.\crypto\ffx\ffxtest.c(85) : error C2143: 语法错误 : 缺少“;”(在“类型”的前面)

.\crypto\ffx\ffxtest.c(86) : error C2065: “in”: 未声明的标识符
.\crypto\ffx\ffxtest.c(86) : warning C4047: “函数”:“const char *”与“int”的
间接级别不同
.\crypto\ffx\ffxtest.c(86) : warning C4024: “FFX_encrypt”: 形参和实参 2 的类型
不同
.\crypto\ffx\ffxtest.c(86) : error C2065: “in”: 未声明的标识符
.\crypto\ffx\ffxtest.c(86) : warning C4047: “函数”:“const char *”与“int”的
间接级别不同
.\crypto\ffx\ffxtest.c(86) : warning C4024: “strlen”: 形参和实参 1 的类型不同
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 10.
0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.

==================

win 编译，是不是只能在vs2013下编译过。

我机器上只有vs2010 ，

**Comment by wuzhongyuanking** [comment]
test不用管吧，你编译到这种程度看out目录下应该就有gmssl   crypto   ssl  这些库了。你把test文件屏蔽也可以，编译器都可以编译，我还用2008也可以

**Comment by 1132719438** [comment]
@wuzhongyuanking s3_lib.c里的ssl3_ciphers数组里的密码套件要根据id由小到大排序，因为查找密码套件时用的是二分查找

所以把国密的密码套件的定义放到Cipher C032后面，国际和国密套件就都可以用了

**Comment by simelsi** [comment]
你用他自带的gmssl s_server -accept 2009 -key server.pem -cert server.pem 
gmssl s_client -connect localhost：2009命令测试吧，这个库到处感觉都是bug，另外你想调用国密的话
int nid = NID_X9_62_prime256v1; 
EC_KEY * ecdh = EC_KEY_new_by_curve_name（nid）; 
if（ecdh == NULL）{ 
printf（“无法创建曲线\ n”）; 
} 
SSL_CTX_set_tmp_ecdh（g_sslctx，ecdh）; 
SSL_CTX_set_options（g_sslctx，SSL_OP_SINGLE_ECDH_USE）; 
EC_KEY_free（ECDH）; 
要加这段代码，这是我研究好几天才得出来的


这段代码在哪里添加？？

**Comment by duoluodexiaokeke** [comment]
wuzhongyuanking ，请问一下SM2-SM4-SM3这个怎样调用呢？再通讯的时候使用什么算法，理论上应该是需要指定的把，不然怎么确认呢？
