### ISSUE TITLE
曲线参数a的定义

### ISSUE THREAD

**Issue by Chris-hhc** [guanzhi/GmSSL#1643]
是否定义了曲线参数a，没找到诶，还是可以优化掉。我看库里所有y^2 = x^3 +ax +b,中a都取的3，这是什么原因，求大佬们帮助！

**Comment by emmansun** [comment]
你可以参考一下这个：https://github.com/emmansun/gmsm/discussions/38

**Comment by Chris-hhc** [comment]
> 你可以参考一下这个：[emmansun/gmsm#38](https://github.com/emmansun/gmsm/discussions/38)

明白了，太感谢老师了！
