### ISSUE TITLE
compile error in GmSSL v1.2.1

### ISSUE THREAD

**Issue by peer2peer** [guanzhi/GmSSL#166]
- Ubuntu 16.04.1 LTS
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
- GNU Make 4.1 Built for x86_64-pc-linux-gnu

**~/GmSSL-gmssl-1.2.1$ make**
...
MODES_OBJ     =ghash-x86_64.o aesni-gcm-x86_64.o
PADLOCK_OBJ   =e_padlock-x86_64.o
CHACHA_ENC    =chacha-x86_64.o
POLY1305_OBJ  =poly1305-x86_64.o
BLAKE2_OBJ    =
PROCESSOR     =
RANLIB        =ranlib
ARFLAGS       =
PERL          =/usr/bin/perl

SIXTY_FOUR_BIT_LONG mode

Configured for linux-x86_64.

**~/GmSSL-gmssl-1.2.1$ make**
...
make[2]: Entering directory '/home/xyz/GmSSL-gmssl-1.2.1'
LD_LIBRARY_PATH=.: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/bb1ibetest test/bb1ibetest.o -L. -lcrypto -ldl
_test/bb1ibetest.o: In function `main':
bb1ibetest.c:(.text.startup+0x59): undefined reference to `BB1IBE_setup'
bb1ibetest.c:(.text.startup+0x7d): undefined reference to `BB1PublicParameters_free'
bb1ibetest.c:(.text.startup+0x87): undefined reference to `BB1MasterSecret_free'
bb1ibetest.c:(.text.startup+0x8f): undefined reference to `BB1PrivateKeyBlock_free'
bb1ibetest.c:(.text.startup+0xf0): undefined reference to `BB1IBE_extract_private_key'
bb1ibetest.c:(.text.startup+0x129): undefined reference to `BB1IBE_encrypt'
bb1ibetest.c:(.text.startup+0x182): undefined reference to `BB1IBE_encrypt'
bb1ibetest.c:(.text.startup+0x1bb): undefined reference to `BB1IBE_decrypt'
bb1ibetest.c:(.text.startup+0x1fe): undefined reference to `BB1IBE_decrypt'
collect2: error: ld returned 1 exit status
Makefile.shared:194: recipe for target 'link_app.gnu' failed
make[2]: *** [link_app.gnu] Error 1
make[2]: Leaving directory '/home/xyz/GmSSL-gmssl-1.2.1'
Makefile:7674: recipe for target 'test/bb1ibetest' failed
make[1]: *** [test/bb1ibetest] Error 2
make[1]: Leaving directory '/home/xyz/GmSSL-gmssl-1.2.1'
Makefile:128: recipe for target 'all' failed
make: *** [all] Error 2_

**Comment by sslvpn007** [comment]
现在有稳定点的吗 能用的吗

**Comment by peer2peer** [comment]
还没找到。总觉得跟OpenSSL搅和在一起把系统搞复杂了，应该抽取出来
