### ISSUE TITLE
按 README 所说无法得到 Linux 下的静态库

### ISSUE THREAD

**Issue by TENX-S** [guanzhi/GmSSL#1662]
> GmSSL 3 采用了cmake构建系统。下载源代码后将其解压缩，进入源码目录，执行：
> ```
> mkdir build
> cd build
> cmake ..
> make
> make test
> sudo make install
> ```
我只能得到位于 `/usr/local/lib` 目录下的一个动态库（`libgmssl.so.3.1`）和两个软链接（`libgmssl.so`, `libgmssl.so.3`），然而：
> 在make install完成后，GmSSL会在默认安装目录中安装gmssl命令行工具，在头文件目录中创建gmssl目录，并且在库目录中安装libgmssl.a、libgmssl.so等库文件。

可 `/usr/local/lib` 目录下并没有 `libgmssl.a` 静态库文件，我编译的是 v3.1.1 版本的仓库，希望能得到一点帮助，十分感谢！

**Comment by nonameless10** [comment]
把 `CMakeLists.txt` 中的最后一行改为：`add_library(gmssl STATIC ${src})`

**Comment by yanxianhe** [comment]
如果是 ubuntu 系统更新以下 库即可

sudo ldconfig

**Comment by yanxianhe** [comment]
centos
sudo /sbin/ldconfig
