### ISSUE TITLE
【一句话，只要一句话，拯救你编译不过的 GmSSL】请使用 -l:libcrypto.a 显示指定链接文件

### ISSUE THREAD

**Issue by xqyww123** [guanzhi/GmSSL#167]
你知道多少人的生命全花在编译错误上了么…
又有多少编译错误都是链接到系统openssl上导致的
Orz
请使用 -l:file_path.a 显示制定链接文件，拯救世界。
其他 lib 也同样。

--------------
解决方法在第三楼

**Comment by xqyww123** [comment]
编译挂的人，例如：
```
gcc -DDSO_DLFCN 这里有好大一坨 -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/eciestest test/eciestest.o -L. -lcrypto -ldl
```
把 -lcrypto 替换成 -l:libcrypto.a，单独执行一下：
```
gcc -DDSO_DLFCN 这里有好大一坨 -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o test/eciestest test/eciestest.o -L. -l:libcrypto.a -ldl
```
然后继续 make，再出现错误同上处理，直到 make 成功，或者出现新的错误（愿神能保佑你 :smile: ）

**Comment by xqyww123** [comment]
啊 :disappointed: 这样太累了，直接：

Linux only:
```
make clean
./config --prefix=/usr/local/
sed -i -- 's/-lcrypto/-l:libcrypto.a/g' ./Makefile
make
```

一口气替换掉 Makefile

**Comment by zhu071011** [comment]
Error: speck_decrypt16 does not have a number assigned
但是我一直会报这个错误。。。我用的是Ubuntu的虚拟机不晓得这两者之前有没有关系。。

**Comment by tengent** [comment]
说个替代的方案，不用去侵入原来的代码， 使用
export LIBPATH=<项目目录>:$LIBPATH
export LD_LIBRARY_PATH=<项目目录>:$LIBPATH
同样解决编译时link错误的.a, .so问题

**Comment by xqyww123** [comment]
我当时尝试是失败的，系统似乎会先查找标准路径，再找环境变量，而名字一样所以链接失败了。
