### ISSUE TITLE
gmssl 客户端连接自己写的服务端报错，不晓得服务端哪里问题导致的

### ISSUE THREAD

**Issue by xifenmin** [guanzhi/GmSSL#168]
GMSSL: pem_lib.c 857: pem_str = EC PARAMETERS
GMSSL: pem_lib.c 858: suffix = PRIVATE KEY
GMSSL: pem_lib.c 863: p = PRIVATE KEY
GMSSL: pem_lib.c 857: pem_str = EC PRIVATE KEY
GMSSL: pem_lib.c 858: suffix = PRIVATE KEY
GMSSL: pem_lib.c 863: p = PRIVATE KEY
GMSSL: pem_lib.c 857: pem_str = EC PRIVATE KEY
GMSSL: pem_lib.c 858: suffix = PRIVATE KEY
GMSSL: pem_lib.c 863: p = PRIVATE KEY
GMSSL: d2i_pr.c 96
GMSSL: d2i_pr.c 118
GMSSL: d2i_pr.c 121
CONNECTED(00000003)
139770571261608:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 143 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---

**Comment by dgyx** [comment]
关键在，服务端要加上这一段
    SSL_CONF_CTX *cctx = SSL_CONF_CTX_new();
    if( !cctx )
    {
        //TODO log
        return -1;
    }
    SSL_CONF_CTX_set_flags(cctx, SSL_CONF_FLAG_SERVER);
    SSL_CONF_CTX_set_flags(cctx, SSL_CONF_FLAG_CMDLINE);
    SSL_CONF_CTX_set_ssl_ctx(cctx, ctx);
    if (SSL_CONF_cmd(cctx, "-named_curve", "P-256") <= 0) {
        return -1;
    }
    if (!SSL_CONF_CTX_finish(cctx)) {
        return -1;
    }
    return 0;
我研究了好久才发现的，这段意思就是让服务端支持椭圆曲线算法

**Comment by xifenmin** [comment]
谢谢楼主，按照你的方法我的问题解决了。非常感谢

**Comment by dgyx** [comment]
不客气，我也是刚开始做这个，互相帮助吧！

**Comment by wuzhongyuanking** [comment]
我也是研究好久才发现的，不过那个加的通过命令行设置的，
int nid = NID_X9_62_prime256v1;
EC_KEY* ecdh = EC_KEY_new_by_curve_name(nid);
if (ecdh == NULL) {
printf("unable to create curve\n");
}
SSL_CTX_set_tmp_ecdh(g_sslctx, ecdh);
SSL_CTX_set_options(g_sslctx, SSL_OP_SINGLE_ECDH_USE);
EC_KEY_free(ecdh);

我通过这样设置也是OK的，就不用依赖命令行设置了

**Comment by gmfix001x** [comment]
楼主，我编译了下gm-v1的版本，替换了库和头文件，

运行的时候，报错：

8160:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:.\ssl\s3_
pkt.c:1210:

**Comment by gmfix001x** [comment]
Error:
1416:error:140830B5:SSL routines:ssl3_client_hello:no ciphers available:.\ssl\s3
_clnt.c:832:

**Comment by gmfix001x** [comment]
一个是 客户端报的错，一个是服务端报的错。

**Comment by wuzhongyuanking** [comment]
执行demo/gmssl/gmssl.sh可产生sm2的相关证书和秘钥
你用他gmssl自带命令测:
gmssl s_server -accept 2009 -key server.pem -cert server.pem
gmssl s_client -connect localhost:2009

**Comment by gmfix001x** [comment]
你有程序写的demo吗 ？

有，可以分享下吗？

我不知道是不是我的demo写的有问题。

我仅仅是，换了下TLSv1_1_server_method、TLSv1_1_client_method

**Comment by wuzhongyuanking** [comment]
没试过，你用SSLv23_client_method

**Comment by gmfix001x** [comment]
SSLv23_client_method，这个支持国密吗

**Comment by wuzhongyuanking** [comment]
当然支持了，你看国密定义都是在s3_lib.c里面，你用SSLv3_client_method都行

**Comment by gmfix001x** [comment]
楼主，我加了上面你说的代码，还是报错。

Connection: 192.168.1.98:37690
2532:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher:.\ssl\s3
_srvr.c:1413:



===========
Error:
6844:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake fa
ilure:.\ssl\s23_clnt.c:769:
请按任意键继续. . .

**Comment by gmfix001x** [comment]
楼主，你用demo跑过吗？
我也是最近才刚刚弄这个，很多东西都不熟

**Comment by gmfix001x** [comment]
我跟踪了下代码：

        /* Ciphers supported */
        i = ssl_cipher_list_to_bytes(s, SSL_get_ciphers(s), &(p[2]), 0);
        if (i == 0) {
            SSLerr(SSL_F_SSL3_CLIENT_HELLO, SSL_R_NO_CIPHERS_AVAILABLE);
            goto err;
        }

执行到这里的时候，程序会退出，提示:no shared cipher:

**Comment by wuzhongyuanking** [comment]
你是想用国密算法吧，服务器这边用SM2算法s3_lib.c里面其他算法要屏蔽，如果不屏蔽，EDCH-SM2-SM4-SM3在服务端ssl3_get_cipher_by_char这边不能解析出这个字段（可以手动解析），你这很有可能是没生成SM2证书放到server运行目录下加载

**Comment by gmfix001x** [comment]
是的。

我用SSLv23_server_method()/SSLv23_client_method() 没什么问题，但v23版本好像少了很多步骤
比如：没有证书，可以看看v23 clnt.c的connect函数的代码。至少比v3少了很多。

用SSLv3_server_method/SSLv3_client_method或其他的，也不行。

提示:no ciphers available  
貌似现在这个gm-v1的版本，在window下，对国密ssl的支持暂时还是欠缺的。

**Comment by gmfix001x** [comment]
我抓了下包，发现没有证书请求这个步骤。

是现在还不支持吗

**Comment by gmfix001x** [comment]
sslv23

**Comment by BoltedSnail** [comment]
遇到了ecdsa在协商加密套件时一直不行的问题。have_ecc_cert这个参数一直为0，原因是valid_flag为0。

**Comment by SDquantum** [comment]
你好请问你怎么加载sm2的证书和私钥的？我用SSL_CTX_use_certificate_file() SSL_CTX_use_PricateKey_file,
然后SSL_CTX_check_private_key()的时候报错了。
