### ISSUE TITLE
gmssl tls12_client 和 tls13_client 链接各自服务器报错,tlcp_client 链接 tlcp_server 没问题

### ISSUE THREAD

**Issue by ioserke** [guanzhi/GmSSL#1687]
% gmssl tls12_server -port 4430 -cert certs.pem -key signkey.pem -pass 12345678 -cacert cacert.pem
start listen ...

socket connected

/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/src/tls.c: 362: tls_cbc_decrypt: tls ciphertext cbc-padding check failure
/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/src/tls.c:415:tls_record_decrypt():
/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/src/tls12.c:991:tls12_do_accept():
/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/tools/tls12_server.c:151:tls12_server_main():

% gmssl tls12_client -host 127.0.0.1 -port 4430 -cacert rootcacert.pem -cert clientcert.pem -key clientkey.pem -pass 12345678
/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/src/tls.c:1396:tls_record_get_change_cipher_spec():
/Users/Documents/Openssl/GMSSL/GMSSL/GmSSL-masterTool/src/tls12.c:583:tls12_do_connect():
tls12_client: error

gmssl tls12_client 和 tls13_client 链接报错

**Comment by goudan8484** [comment]
你的cacert用的不一样吧？   目测是证书相关问题
