### ISSUE TITLE
sm2公钥加密算法密文结果与国标《0003.4-2012》不一致

### ISSUE THREAD

**Issue by zhenyuwei** [guanzhi/GmSSL#169]
加密结果好像和国标不一致，国标给的密文结果是 C1 || C3 || C2，GMSSL结果是C1 || C2 || C3。

**Comment by AivenYoung** [comment]
国标有旧版本，旧版本是C1 || C2 || C3， 新版本修改成了C1 || C3 || C2，GMSSL可能开发比较早，使用的是C1 || C2 || C3。

**Comment by disillusion028** [comment]
AivenYoung说的对，GMSSL的sm2使用的是2010年的版本

**Comment by guanzhi** [comment]
GmSSL 2.0 (Master分支) 已经更新为《GM/T 0009-2012 SM2密码算法使用规范》7.2节中定义的ASN.1/DER格式。GmSSL-1.3 还沿用之前的格式不进行修改。
