### ISSUE TITLE
Why delete '_gmssl_export' key word

### ISSUE THREAD

**Issue by maximluo** [guanzhi/GmSSL#1690]
In the commit [31c26de](https://github.com/guanzhi/GmSSL/commit/31c26de86579a6ad51b5e11e271e72849630ade1), it use '**CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS**' and delete '_gmssl_export'. This would make the symbols of dll become much larger and includes some unnecessary symbols. I would like to know the reason of this change of commit

**Comment by guanzhi** [comment]
I would like to use .exp or .lds symbol files to export or hide symbols. It keeps the code clean.
In SoftSDF (https://github.com/GmSSL/SoftSDF), I use this method to control the exportable of symbols.
I don't have a strong motivation to support symbol control in GmSSL. So maybe .exp and .lds files will not be added to the main branch.
