### ISSUE TITLE
运行 sm2test 会导致 "Segmentation fault"，烦请知悉，辛苦！

### ISSUE THREAD

**Issue by Jkinglyf** [guanzhi/GmSSL#17]
问题 1：
       编译后，运行 sm2test 文件会导致 "Segmentation fault"。
       通过调试定位于 test_evp_seal 函数。

解决：
      在 test_evp_seal函数中，

        1) 将 unsigned char ek[NUM_PKEYS][MAX_PKEY_SIZE] 修改为 unsigned char *ek[NUM_PKEYS]

        2) 分配 内存
             for (i = 0; i < NUM_PKEYS; i++) {
                 pkey[i] = genpkey(curve_id, out, verbose);
                 ekl[i] = MAX_PKEY_SIZE;
                 ek[i] = malloc(ekl[i]);
            }
  
        3) 释放内存
            for (i = 0; i < NUM_PKEYS; i++) {
                  EVP_PKEY_free(pkey[i]);
                  free(ek[i]);
           }

问题 2：

       运行 sm2test 会出现  "digital envelope routines:EVP_OpenInit:public key not rsa“ 的错误。

解决：

     修改 crypto/evp/p_open.c；

      1)  支持 EVP_PKEY_EC （85行处）；
           // if (priv->type != EVP_PKEY_RSA) {
           if ((EVP_PKEY_id(priv) != EVP_PKEY_RSA) && (EVP_PKEY_id(priv) != EVP_PKEY_EC))  

      2) 修改 size 取值方法（91行处）；
           //size = RSA_size(priv->pkey.rsa);
           size = EVP_PKEY_size(priv);

辛苦原作者！

**Comment by guanzhi** [comment]
谢谢！
问题已经修复，其中用了OPENSSL_malloc/free()，以及EVP_PKEY_based_id()。对于是否应该用EVP_PKEY_id()还是EVP_PKEY_base_id()我不能确定。

**Comment by Jkinglyf** [comment]
关老师：

      您好。

      EVP_PKEY_id() 与 EVP_PKEY_base_id() 结果值是一样的，其数据源都来自于 pkey_id。

      int EVP_PKEY_id(const EVP_PKEY *pkey)
      {
            return pkey->type;   // 该值来自于 pkey->ameth->pkey_id （详见 crypto/evp/p_lib.c 文件 238 行处）；
      }

      int EVP_PKEY_base_id(const EVP_PKEY *pkey)
      {
           return EVP_PKEY_type(pkey->type); // 该值来自于 ameth->pkey_id; （详见 crypto/evp/p_lib.c 文件 357 行处）；
      }

谢谢您的回复！
