### ISSUE TITLE
sm2验签返回-1该如何排错

### ISSUE THREAD

**Issue by Holy-Shine** [guanzhi/GmSSL#1700]
请问SM2验签返回结果-1，如何排查是哪一部步出错了。
使用场景是，lua通过ffi模块直接调用sm2_verify

**Comment by lpilp** [comment]
查看 /demos/scripts 下 的例子， 用命令行的样式跑下数据， 报错更清晰些， 验签不通过一般就几样： 
1 公私钥没有匹配
2 被签名的数据不对，如为简化将原始数据md5后再签名 
3 向量不对  
4 签名格式不对  标准是  asn1(r,s),   有些就 r+s 了

**Comment by Holy-Shine** [comment]
好的感谢~
