### ISSUE TITLE
客户端验证失败

### ISSUE THREAD

**Issue by gmfix001x** [guanzhi/GmSSL#186]
8924:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:.\crypto\asn
1\a_verify.c:218:
8924:error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify
failed:.\ssl\s3_srvr.c:3253:

有遇到过这样问题的吗

**Comment by gmfix001x** [comment]
证书，用的是国密的证书，格式.pem的

**Comment by AivenYoung** [comment]
如果你是基于OpenSSL开发的，我猜测可能是SM2证书的签名值验证失败了，SM2签名和验证签名，都需要预处理，GMSSL我没怎么看SM2的实现，也有可能其预处理使用的Z值不同。
供参考，希望能帮到你。

**Comment by sslvpn007** [comment]
不错。
