### ISSUE TITLE
进行国密SSL调试，需要双证书，有人知道怎么获取或者制作吗

### ISSUE THREAD

**Issue by AivenYoung** [guanzhi/GmSSL#187]
开发国密SSL服务端，需要与360国密专版联调，但是没有可用的双证书，请教下各位，哪里可以找到比较标准的测试证书呢。十分感谢。

360国密专版内置CFCA 根CA证书。
需要的证书：
1，服务器签名证书 和 对应的私钥。
2，服务器加密证书 和 对应的私钥。
3，相关CA证书。

**Comment by gmfix001x** [comment]
楼主，我们一起分享下：

我现在在win下，已经有了测试国密ssl的客户端和服务端的程序，

但测试的过程中，发现有问题。

=======
1、首先我用的是SSLv23这个去测的，很多地方都不符号国密ssl，比如版本，国密的版本是:0x0101
但sslv32是0x0303，其他的都不行了。

2、然后SSLv3、TLSv1\TLSv1_1,测了下，都不行。具体的问题就不一一说了。反正是有问题的。

3、我再验证双证书的时候
3.1：SSLv23测的时候，一直提示无法验证客户端证书。

3.2：GMSSLv1测试时候，一直提示：no shared cipher。。。

======================================
楼主 能提供QQ吗？

我们可以聊聊。我这有你想要的双证书，以及CA根证书。

=============
附注：
这个，凭一己之力做，有点困难，而且遇到了困难，也不好解决。尤其openssl底层的代码。

**Comment by AivenYoung** [comment]
@gmfix001x 我们可以交流下，1065190320

**Comment by AivenYoung** [comment]
2017.5.19 终于与国密专版浏览器和中行国密联调成功，记录下。
在这里给还在联调国密SSL的同学们点忠告，当遇到握手相关的问题时，请细致的阅读标准文档N遍。

**Comment by dgyx** [comment]
可以一起讨论下吗？ @gmfix001x @AivenYoung

**Comment by 1132719438** [comment]
@AivenYoung 请问一下国密ECC-SM4-SM3套件的双证书该怎么加载，加载到哪里，目前gmssl里面certificate发送的好像是server证书和CA证书

**Comment by AivenYoung** [comment]
@dgyx  项目已经开发结束了，该临时qq已经不再使用。有需要交流探讨，请直接发issue或者发邮件给我，我会在有时间的时候回复。
@1132719438 我是基于OpenSSL开发的，gmssl这里我看的是master分支代码，我理解它这里并没有实现，只有简单的定义一些头文件等，TLS/SSL只需要单证书校验，我实现是在TLS1.1的基础上进行调整修改，
自己实现额外加载SM2加密证书入SSL CTX，这里测试的话可以尝试使用SSL_CTX_get_extra_chain_certs，需要理解它的具体实现，可能需要修改握手流程中加载证书的地方。

**Comment by dgyx** [comment]
@AivenYoung 我想请问下，你与360国密浏览器连接使用的国密证书，能否发我一份，或者请教下怎么制作。非常感谢。

**Comment by AivenYoung** [comment]
@dgyx  http://pan.baidu.com/s/1qYiAMwk 密码:2185  
这是360工程师提供的测试证书，但是貌似不是CFCA签发的，能够完成GM握手，最后浏览器上会显示证书不可信，应该是360设置了验证服务器证书的回调函数，对服务器证书有要求。  建议使用 速龙 浏览器联调，速龙浏览器联调不会报错。

**Comment by dgyx** [comment]
@AivenYoung 非常感谢！

**Comment by AivenYoung** [comment]
@dgyx 好像是遗漏了，上传了。

**Comment by dgyx** [comment]
@AivenYoung 好人一生平安~^_^
