### ISSUE TITLE
tf-card openssl sm2/4

### ISSUE THREAD

**Issue by shi-hao** [guanzhi/GmSSL#189]
想在openssl的框架下，实现openssl调用tf-card加密卡中的国密算法（sm2/4），实现硬件加密，想问下，如何实现呢，基本思路是什么？
      自己已经查了很久了，但是没有具体的思路，网上好多文章说使用engine方式可以实现，关老师能不能给个具体的思路，需要做哪些编码工作，谢谢！

**Comment by LiTianjue** [comment]
用engine反而复杂了, 总的就那么几个算法函数, 直接EVP  + SKF 还简单点

**Comment by guanzhi** [comment]
我们采购并测试了几个供应商的密码硬件产品，稍后会更新skf/sdf engine以支持这些硬件。另外我们会提供少量的硬件免费给用户测试和试用，届时欢迎申请。

**Comment by shi-hao** [comment]
首先，谢谢关老师的指导，还有这位仁兄，LiTianjue！
然后，再追问一个问题，就是实现了openssl对加密卡算法调用后，希望openssl中的ssl私钥算法可以使用sm2，分组加密算法可以使用sm4，这样的话需要做哪方面的修改，望指教。

**Comment by guanzhi** [comment]
需要启动ENGINE，命令行和EVP API中都有指定ENGINE的接口参数。实际上OpenSSL/GmSSL已经内置了包括微软CryptoAPI，BSD CryptoDev，Intel RDRAND等在内的多个ENGINE，可以通过这些ENGINE访问对应的硬件设备或指令。
