### ISSUE TITLE
GmSSL 是基于什么版本的 OpenSSL 进行扩展的？

### ISSUE THREAD

**Issue by moonfruit** [guanzhi/GmSSL#20]
请问 GmSSL 是基于什么版本的 OpenSSL 进行扩展的？未来是否有计划合并更新的 OpenSSL 至 GmSSL?

**Comment by guanzhi** [comment]
目前基于OpenSSL 1.0.2d，这个版本的已知漏洞暂时对国密算法没有影响，是否有其他影响请参考OpenSSL的ChangeLog。OpenSSL的后续版本中1.1是一定会合并的，具体工作会在1.1正式发布后开始，预计可能会在1.1发布半年之后完成合并。是否合并OpenSSL 1.0.2后续版本主要看需求而定。

**Comment by moonfruit** [comment]
提一个小建议哈，OpenSSL 本身是支持第三方的扩展的，GmSSL 应该可以单独编译成一个动态库。通过类似于 OpenSSL_add_all_algorithms() 这样的函数，将自己的算法注册到 OpenSSL 中去。这样 GmSSL 就与 OpenSSL 独立开了，不光 OpenSSL 的版本怎么变化，只要它的扩展机制不变，就可以轻松嵌入进去。这样会不会会更好一点儿？

**Comment by guanzhi** [comment]
这是一个很好的建议。但是GmSSL暂时不会做这个尝试，有两个原因：

1. OpenSSL在SSL层面似乎不支持扩展，因此无法支持国密SSL协议。
2. 没有人手来做这方面的开发。

**Comment by J-Feng** [comment]
1. 请问GmSSL和OpenSSL在版本上有没有对应关系？
2. 目前GmSSL合并OpenSSL的策略是什么样的？定期合并？大版本合并？还是出现严重漏洞才会合并？
3. 如果我的项目既需要GmSSL，又需要保持对OpenSSL较新版本的跟踪，我自己对OpenSSL部分做了更新后，GmSSL主线是否接受这样的PR？
4. GmSSL有没有计划将国密相关代码提交到OpenSSL主线？
5. OpenSSL 1.1.1加入了对SM3和SM4的支持（[ChangeLog](https://www.openssl.org/news/changelog.html#x0)）

> *) Add SM3 implemented according to GB/T 32905-2016
     [ Jack Lloyd <jack.lloyd@ribose.com>,
       Ronald Tse <ronald.tse@ribose.com>,
       Erick Borsboom <erick.borsboom@ribose.com> ]
> *) Add SM4 implemented according to GB/T 32907-2016.
     [ Jack Lloyd <jack.lloyd@ribose.com>,
       Ronald Tse <ronald.tse@ribose.com>,
       Erick Borsboom <erick.borsboom@ribose.com> ]

请问这对GmSSL有什么影响？是否会继续开发？是否会针对这些做调整（比如合入OpenSSL1.1.1后移除GmSSL的相关算法，转而使用官方上游分支的实现）？

6. 从OpenSSL的[邮件列表](https://mta.openssl.org/pipermail/openssl-dev/2016-September/008552.html)看到建议将算法实现为外部ENGINE，请问GmSSL会有这样的实现吗？看上去这样会比较容易维护GmSSL和OpenSSL的关系

因为涉及到长期项目的选型，所以问题比较多，相信有些问题也是共性问题，谢谢！

**Comment by J-Feng** [comment]
补充一下，1.1.1中SM2也应该会支持了（只是在算法层面，协议层面暂时没有支持）http://cloud.idcquan.com/yzx/139408.shtml
