### ISSUE TITLE
现在GMSSL，对国密算法，以及国密ssl，支持到何种程度了

### ISSUE THREAD

**Issue by sslvpn007** [guanzhi/GmSSL#206]
关老师您好：
        现在GMSSL，对国密算法，以及国密ssl，支持到何种程度了？

**Comment by sslvpn007** [comment]
关老师，我用程序单步跟踪了下底层的源代码，到这里报错了，具体如下：
位置：在sm2_sign.c中的422行，

if (BN_ucmp(t, sig->r) == 0) {
	ret = SM2_VERIFY_SUCCESS;
} else {
	ret = SM2_VERIFY_FAILED;
}

**Comment by guanzhi** [comment]
这一步即验证签名的关键步骤，ret = SM2_VERIFY_FAILED 说明签名验证不通过，而不是产生普通的错误，因此这一步是不报错的。

**Comment by sslvpn007** [comment]
关老师，我测试的证书也是签发的sm2的证书以及ca都是没问题的。

为什么还会出现验签不通过的问题？

具体会出现在哪儿？

**Comment by BoltedSnail** [comment]
我自己集成的国密算法到openssl，也是验签失败，sm3算法用国密局的例子验证过了，参数都打印对照了一遍，我觉得应该是出在Z值计算上了，我的证书是CFCA签发的，ID字段不知道是啥，

**Comment by BoltedSnail** [comment]
id是1234667812345678，不过你的问题还要具体分析，

**Comment by gmfix001x** [comment]
做摘要的时候，你是怎么做的？

用没用到用户ID:1234567812345678

**Comment by sslvpn007** [comment]
我用的是GmSSL-v1这个版本，在win下跑的，是不是我的版本太低了。

**Comment by BoltedSnail** [comment]
我是自己集成到openssl的，做摘要时要计算Z值，Z值里有ID

**Comment by sslvpn007** [comment]
你具体是怎么弄的，Z值

**Comment by sslvpn007** [comment]
你说的是不是这个意思，再做sm2验签的时候，选对数据做摘要，
摘要具体如下：

hash = sm3（userID，userID_length,公钥x，公钥y，text，textlen）;
sm2Verify(hash,signvalue,公钥x，公钥y)
然后在用这个hash值 去做验签

**Comment by sslvpn007** [comment]
不知道说的对不对

**Comment by BoltedSnail** [comment]
你用asn1view打开你将要验证的证书，第二个节点(SEQUENCE)的内容就是md的内容

**Comment by sslvpn007** [comment]
问你下，我跟踪代码，发现ca根证书对签发的证书的签名值是72个字节

sm2签名值不是r和s 64个字节吗？

是不是我的证书有问题

**Comment by sslvpn007** [comment]
而且通过你说的工具，看了下，第二个节点，确实是72个字节

**Comment by sslvpn007** [comment]
这72个字节，程序获取 与 工具里获取的，数据是一样的 。

**Comment by AivenYoung** [comment]
ASN1编码而已，72字节是正确的。

**Comment by guanzhi** [comment]
gmssl-v1 目前默认不支持Z值的计算，因此默认下对于标准的CFCA证书不能验证通过，也不能和标准的国密服务器互联。但是gmss-v1自己的客户端、服务器、证书是互通的。gmssl-v1也提供了对Z值计算的支持，可以通过编程调用相应的函数。

**Comment by sslvpn007** [comment]
关老师，我看了下gmsslv1的客户端、服务端的代码，和我自己写的基本一致。

证书互通，有点不对，客户端是可以直接获取服务端的证书，但服务端无法获取客户端的证书。

我跟了下代码，除非调用了这个：SSL_CTX_set_verify(ctx,SSL_VERIFY_PEER,NULL);

服务端才会向客户端发送证书请求，否则不会客户端不会发送证书过去给服务端。

**Comment by BoltedSnail** [comment]
@sslvpn007我那个issues关了，我用的验签函数就是gmssl的验签函数。如果有问题可以发我邮箱lmyupc@163.com，我集成国密套间的openssl已经可以建立链接了。希望可以帮到你

**Comment by sslvpn007** [comment]
好的。我已经发您邮箱了。谢谢
