### ISSUE TITLE
sm2签名函数的签名验证不通过

### ISSUE THREAD

**Issue by BoltedSnail** [guanzhi/GmSSL#208]
之前验证证书上的签名通过了，也就是验签函数是没有问题的。
现在是秘钥交换过程的签名和验签，服务端签名后发送到客户端，客户端打印的参数与服务端完全符合。
传到签名函数内的dgst和传递到验签函数内的dgst内容完全一样，但是计算结果不一样。
私钥打印出来与证书符合，公钥也是正确的。
有遇到类似情况的吗

**Comment by sslvpn007** [comment]
能分享下你证书验签通过的 验签函数吗？？？
