### ISSUE TITLE
GmSSL java Wrapper中有关SM2公私钥对生成问题？？

### ISSUE THREAD

**Issue by sherry1118** [guanzhi/GmSSL#209]
我已经将java接口写好，但在使用非对称加解密时，如何得到SM2算法的密钥对？？？

**Comment by wrhsan** [comment]
对于java不太了解，直接用C的话，应该如下：
```
    EC_KEY *ec_key = EC_KEY_new();
    ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
    EC_KEY_generate_key(ec_key);
    const EC_POINT *point = EC_KEY_get0_public_key(ec_key);
    char *publicChar = EC_POINT_point2hex(EC_KEY_get0_group(ec_key), point, POINT_CONVERSION_UNCOMPRESSED, BN_CTX_new());
    const BIGNUM *privateKey = EC_KEY_get0_private_key(ec_key);
    char *privateChar = BN_bn2hex(privateKey);
```
publicChar, privateChar分别为公私钥。

**Comment by wrhsan** [comment]
@zhao1zhihui openssl 文档较多，这段代码是查 openssl 写的。

**Comment by happyycm** [comment]
> 对于java不太了解，直接用C的话，应该如下：
> 
> ```
>     EC_KEY *ec_key = EC_KEY_new();
>     ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
>     EC_KEY_generate_key(ec_key);
>     const EC_POINT *point = EC_KEY_get0_public_key(ec_key);
>     char *publicChar = EC_POINT_point2hex(EC_KEY_get0_group(ec_key), point, POINT_CONVERSION_UNCOMPRESSED, BN_CTX_new());
>     const BIGNUM *privateKey = EC_KEY_get0_private_key(ec_key);
>     char *privateChar = BN_bn2hex(privateKey);
> ```
> 
> publicChar, privateChar分别为公私钥。

麻烦问一下，这样生成的公私钥是什么格式的？

**Comment by wrhsan** [comment]
hexString 16进制字符串

**Comment by happyycm** [comment]
> hexString 16进制字符串

谢谢，您知道怎么把16进制字符串的密钥转换成ASN.1格式的密钥吗？java给的api好像需要ANS.1格式的密钥才可以
