### ISSUE TITLE
gmssl verify -CAfile ca.cer cert.cer 不能用

### ISSUE THREAD

**Issue by lvmengkeji** [guanzhi/GmSSL#215]
error 7 at 0 depth lookup:certificate signature failure
140156311619240:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:218:

这个命令可以验证sm2证书是否是ca签发的，恳请修复.
用的GmSSL 1.3.0 - OpenSSL 1.0.2d

**Comment by J-Feng** [comment]
在最新的版本上gmssl verify验证CFCA签发的证书成功
```
GmSSL 2.3.1 - OpenSSL 1.1.0d  30 Mar 2018
```

如果还没解决，可以试试最新版本

**Comment by softblade-c** [comment]
我自己生成的国密证书，使用gmssl 2.4.0不能验证通过，使用2.5.0能过。
