### ISSUE TITLE
vs2015 修改了一下可以编译成功，使用时错误

### ISSUE THREAD

**Issue by lilucpp** [guanzhi/GmSSL#216]
windows下修改了几个文件，可以编译成功了，但是使用gmssl库编译gloox库时出现下面的错误：
gloox\tlsopensslbase.cpp(261) : error C2027: 使用了未定义类型“x509_st”

暂时不能解决，请帮忙提示一下白，多谢

**Comment by 1132719438** [comment]
是不是因为`x509_st`是内部定义的类型，用`X509`代替试下

**Comment by lilucpp** [comment]
1.应该不是，查看了下头文件中有定义ossl_typ.h: typedef struct x509_st X509;   
2.昨天又尝试了一下，我工程的gloox时较早版本，最新的gloox-1.0.20可以编译过；对比gloox的两个版本、openSSL1.02与openssl-1.1.0f版本 代码发现有变化，如面x509_st结构的定义头文件名变化。
3.下了个GmSSL-gmssl-v1(基于 OpenSSL 1.0.2d)重新编译我的gloox，是可以编译过得，
几天的折腾辛得：版本害死个人

**Comment by lilucpp** [comment]
还是要多谢你 @1132719438
