### ISSUE TITLE
Centos7.0上  GmSSL-2.0版本是否能用，一直都无法安装成功，各种bug

### ISSUE THREAD

**Issue by RubicPhil** [guanzhi/GmSSL#219]

**Comment by RubicPhil** [comment]
GMSSL2.0安装成功后，运行出现错误

[root@localhost GmSSL-master]# gmssl
gmssl: relocation error: gmssl: symbol PBEPARAM_it, version OPENSSL_1_1_0d not defined in file libcrypto.so.1.1 with link time reference

**Comment by Linwenbo** [comment]
make之后在项目根目录下有一个libcrypto.so.1.1的文件,把它拷贝到/usr/lib目录下就可以了 .有可能还会报缺少libssl.so  同理可解决

**Comment by ugenehan** [comment]
感觉他们基本在一类系统中的某个版本下测试过就认为可以了。。。

**Comment by WeWebsterchen** [comment]
1.查找gmssl安装路径   whereis  gmssl.
2.ldd gmssl安装路径，查看gmssl依赖库。
3.设置export LD_LIBRARY_PATH=/usr/local/lib64（该路径根据ldd依赖项来设置）

**Comment by yorkew-east8** [comment]
我看make install是给安装到了/usr/local/lib，所以我的做法是在~/.bashrc里加入
export LD_LIBRARY_PATH=/usr/local/lib:LD_LIBRARY_PATH
测试有效

**Comment by RubicPhil** [comment]
感谢您的回答~~


| |
袁钦献
|
|
yqxw2495200715@163.com
|
签名由网易邮箱大师定制
在2019年2月22日 17:32，yorkew<notifications@github.com> 写道：

我看make install是给安装到了/usr/local/lib，所以我的做法是在~/.bashrc里加入
export LD_LIBRARY_PATH=/usr/local/lib:LD_LIBRARY_PATH
测试有效

**Comment by willson-chen** [comment]
官网`快速上手`里面有讲到这个问题，确实需要根据实际情况添加环境变量。

http://gmssl.org/docs/quickstart.html

![image](https://user-images.githubusercontent.com/53104026/84564918-08a6ba00-ad98-11ea-863a-b26b3bf58362.png)

**Comment by spiritedRunning** [comment]
gmssl 与系统openssl会发生冲突，最好安装时指定到一个单独的目录，比如/usr/local/gmssl，否则比较麻烦
