### ISSUE TITLE
正常编译正常安装没有问题，然而demo/gmssl下面initca和gencert均发生段错误

### ISSUE THREAD

**Issue by orikasahibiki** [guanzhi/GmSSL#22]
正常编译正常安装没有问题，然而demo/gmssl下面initca和gencert均发生段错误
具体是在 gmssl req -new -days 365 -key cakey.pem -out ca.pem ； 新建证书请求时发生段错误。
gdb显示收到SIG_TERM信号，在 int_update() 处发生段错误

**Comment by orikasahibiki** [comment]
Redhat 6 / CentOS 6 / Ubuntu 14 下测试均如此，还望指点迷津，谢谢

**Comment by guanzhi** [comment]
GmSSL目前还不支持证书功能，特别是通过命令行或高层的X509_xxx函数来生成证书。证书的完整支持会在下一次release时提供。目前生成证书的可能的方案是直接用底层的或者经过验证的API来编程初始化X509数据结构。
