### ISSUE TITLE
请问 gmssl 目前能制作证基于 SM2 的证书并使用吗？

### ISSUE THREAD

**Issue by maxzlf** [guanzhi/GmSSL#220]

**Comment by ugenehan** [comment]
同求。如何生成证书的步骤，如何生存CA等？

**Comment by zppet** [comment]
同问。

**Comment by zhaoxiaomeng** [comment]
在 readme 中增加了关于生成自签名证书的命令说明。 @maxzlf @ugenehan @zppet

**Comment by ugenehan** [comment]
提示如下错误，2.0版本
46912496234160:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:
@zhaoxiaomeng
