### ISSUE TITLE
GmSSL Java Wrapper 请问如何编译出libgmssl.so？可否提供编译好的libgmssl.so文件？

### ISSUE THREAD

**Issue by xinlong-song** [guanzhi/GmSSL#221]
开发Android应用，个人理解需要通过jni调用libgmssl.so文件，请问如何编译出该文件？望不吝赐教。

**Comment by jiajw0426** [comment]
我刚刚编译了一个linux 64位的，你能用吗？

**Comment by xinlong-song** [comment]
可以提供编译教程吗？

**Comment by xinlong-song** [comment]
我下载你编译好的libgmssl.so文件，调用时出现了下列错误（将libgmssl.so已放到libs目录下）：
Exception in thread "main" java.lang.UnsatisfiedLinkError: no gmssl in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at my.app.sm.GmSSL.<clinit>(GmSSL.java:37)
测试代码如下：
public class GmSSL {

	public native String getVersion(int type);
	public native byte [] generateRandom(int length);
	public native String [] getCiphers(boolean aliases);
	public native int getCipherIVLength(String cipher);
	public native int getCipherKeyLength(String cipher);
	public native int getCipherBlockSize(String cipher);
	public native byte [] symmetricEncrypt(String cipher, int flag, byte [] in, byte [] key, byte [] iv);
	public native byte [] symmetricDecrypt(String cipher, int flag, byte [] in, byte [] key, byte [] iv);
	public native String [] getDigests(boolean aliases);
	public native int getDigestLength(String digestAlgor);
	public native int getDigestBlockSize(String digestAlgor);
	public native byte [] digest(String algor, int flag, byte [] data);
	public native String [] getMacs(boolean aliases);
	public native String [] getMacLength(String algor);
	public native byte [] mac(String algor, int flag, byte [] data, byte [] key);
	public native String [] getSignAlgorithms(boolean aliases);
	public native byte [] sign(String algor, int flag, byte [] data, byte [] privateKey);
	public native int verify(String algor, int flag, byte [] digest, byte [] signature, byte [] publicKey);
	public native String [] getPublicKeyEncryptions(boolean aliases);
	public native byte [] publicKeyEncrypt(String algor, int flag, byte [] in, byte [] publicKey);
	public native byte [] publicKeyDecrypt(String algor, int falg, byte [] in, byte [] privateKey);
	public native String [] getDeriveKeyAlgorithms(boolean aliases);
	public native byte [] deriveKey(String algor, int flag, int keyLength, byte [] peerPublicKey, byte [] privateKey);
	public native String getErrorString();

	public static void main(String[] args) {
		final GmSSL gmssl = new GmSSL();
		System.out.println(gmssl.getVersion(0));
		System.out.println("IV length = " + gmssl.getCipherIVLength("aes-128-cbc"));
	}

	static {
		System.loadLibrary("gmssl");
	}
}

**Comment by jiajw0426** [comment]
java -Djava.library.path=/path/of/libgmssl.os  GmSSL ,指定路径就行了

**Comment by xinlong-song** [comment]
请问可以把您的整个测试工程发我一份吗？我指定路径后，又出现了其他的错误信息，找不到或无法加载主类。

**Comment by 27954741** [comment]
我之前编译的jni 在调so的时候出现问题,可以看我的帖子
目测貌似是版本不太兼容

**Comment by hloser** [comment]
想问下楼主Android成功加载了么？

**Comment by xinlong-song** [comment]
未成功加载

**Comment by Cocoon-break** [comment]
@jiajw0426 能提供下编译so的方法吗？🙏

**Comment by jnuleavin** [comment]
我是在linux下编译好gmssl后生成了libcrypto.so和libssl.so，再将他们放到android项目中，结合GmSSL给的GmSSL.c编译出libgmssl.so，使用时发现GmSSL.java中的getVersion函数用不了，加解密的函数返回null,其他函数都能运行，不知道什么原因，刚接触GmSSL

**Comment by xinlong-song** [comment]
请问你可以把你的demo给我一份吗？

**Comment by jnuleavin** [comment]
那我发你一份

**Comment by xinlong-song** [comment]
font{
        line-height: 1.7;
    }


    

好的，非常感谢您。


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    在2017年8月25日 08:42，jnuleavin<notifications@github.com> 写道： 


那我发你一份

**Comment by jnuleavin** [comment]
你邮箱多少？

**Comment by xinlong-song** [comment]
font{
        line-height: 1.7;
    }


    
xinlong.song@qq.com



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    在2017年8月25日 08:52，jnuleavin<notifications@github.com> 写道： 


你邮箱多少？

**Comment by xinlong-song** [comment]
非常感谢

**Comment by loocao** [comment]
@jnuleavin 请问你是怎么编译的？我想在mac编译一个so，一直不知道方法...

**Comment by kiddingquan** [comment]
@jnuleavin 我编译出的文件也是跟你一样，getversion函数缺少了依赖，一用虚拟机直接崩溃，还有加密出来的东西都是null，你现在解决这个问题了吗？老哥

**Comment by jnuleavin** [comment]
@loocao Mac下没编译过，我是在linux下编译的 网上有教程。
@kiddingquan 由于是在android下使用，我直接用的java的API，可以实现公司需求，然后就没管gmssl了。

**Comment by duyangs** [comment]
@jnuleavin 老哥可以把你编译的给我一份吗，一直搞不出来，邮箱：duyangs1994@Gmail.com
