### ISSUE TITLE
gmssl命令行下sm2怎么解密

### ISSUE THREAD

**Issue by lilucpp** [guanzhi/GmSSL#223]
SM2的工钥加密可以使用：./gmssl.exe pkeyutl -encrypt -in demo -pubin -pkeyopt ec_encrypt_algor:sm2 -inkey publicKey.pem -out demo.en
解密的命令行是什么样的？
我查看了ec_pmeth.c文件， -pkeyopt的操作有 ec_encrypt_algor:sm2，没有类似ec_decrypt_algor:sm2
有谁知道gmssl命令行下sm2怎么解密？多谢。

**Comment by maxzlf** [comment]
gmssl pkeyutl -sign -pkeyopt ec_sign_algor:sm2 -inkey private.pem -in data.txt -out out.sig
gmssl pkeyutl -verify -pkeyopt ec_sign_algor:sm2 -pubin -inkey public.pem -in data.txt -sigfile  out.sig

**Comment by lilucpp** [comment]
@maxzlf 这个是签名，

**Comment by 1132719438** [comment]
试试
gmssl pkeyutl -decrypt -pkeyopt ec_encrypt_algor:sm2 -inkey privatekey.pem -in in_data -out out_data

**Comment by lilucpp** [comment]
@1132719438 可以的，多谢
