### ISSUE TITLE
希望有好心人提供各平台编译成功的二进制文件

### ISSUE THREAD

**Issue by maxzlf** [guanzhi/GmSSL#226]

**Comment by sslvpn007** [comment]
哈哈，说的是。

**Comment by kimqcn** [comment]
好心的搬运工在此：linux和mac的二进制
https://github.com/guanzhi/GmSSL/releases/download/gmssl-1.3.0-bin/gmssl-1.3.0.tar.gz

**Comment by Cocoon-break** [comment]
求编译之后的可以给android和iOS使用的文件
