### ISSUE TITLE
关于国密SSL的几点疑问

### ISSUE THREAD

**Issue by 1132719438** [guanzhi/GmSSL#227]
最近在实现使用ECC-SM4-SM3密码套件的ssl握手流程，有几点疑问，还望解惑：
  1、ECC-SM4-SM3的server key exchange发送的是哪些数据？
  2、预主密钥是客户端根据 对端临时公钥X本端私钥 生成的吗？
  3、客户端需要使用服务端加密公钥加密预主密钥传给服务端，服务端的加密公钥是从server hello里的加密证书里取得的吗？
  4、握手过程中，双方交换的是算法的ID，国密这些算法好像没有国际标准的ID，这样不同实现的国密ssl里ID可能会不一致，应该会无法完成握手
  5、跟4类似，国密曲线也没有标准的ID，握手时需要将曲线参数进行交换吗？

**Comment by guanzhi** [comment]
问题1-3：ECC-SM4-SM3的细节在国密SSL VPN标准中有详述，这个套件和现有的TLS套件差异很大。在GmSSL-1.3中我们只是实验性质了实现了一个用国密算法和证书的套件，并未依照国密标准，而更类似于ECDHE-ECDSA-XXX套件，其中的签名(ECDSA)为SM2。在GmSSL-2.0中我们会公布一批新的国密套件，现有这个套件的实现将会重命名为 ECDHE-SM2-WITH-SMS4-SM3，而国密标准中的套件在国密协议(1.1)中的行为将依照国密标准。

问题4-5：国密曲线是有在国际OID树中的标准OID的，在GmSSL中可以通过名字"sm2p256v1"引用。但是有很多算法及其组合（例如SMS4+GCM模式）并不定义，GmSSL项目申请了一个子OID域，可以将没有OID标准定义的算法放到GmSSL子域中。目前这些算法的OID还放在国密局的子域中，但是国密局对其并无定义。SSL套件的ID则需要向IETF申请。

**Comment by 1132719438** [comment]
GmSSL 2.0 国密套件有发布的计划吗

**Comment by conezxy** [comment]
1、ECC-SM4-SM3的server key exchange发送的是哪些数据？
> 见0024-2014 SSLVPN技术规范

2、预主密钥是客户端根据 对端临时公钥X本端私钥 生成的吗？
> ECC-SM4-SM3套件时的预主密钥生成类似无ECDHE的RSA握手过程，是随机数；
> 传递时需要用服务端的加密公钥加密

3、客户端需要使用服务端加密公钥加密预主密钥传给服务端，服务端的加密公钥是从server hello里的加密证书里取得的吗？
> 从服务端Server Certificate包里的加密证书中获取

4、握手过程中，双方交换的是算法的ID，国密这些算法好像没有国际标准的ID，这样不同实现的国密ssl里ID可能会不一致，应该会无法完成握手
> 见0024-2014 SSLVPN技术规范，有明确定义

5、跟4类似，国密曲线也没有标准的ID，握手时需要将曲线参数进行交换吗？
> 有标准OID。握手时不需要交换参数，只需传递国密曲线的OID

**Comment by 1132719438** [comment]
@conezxy  我在gmssl上改了ECC-SM4-SM3，现在只实现了单正书，请问一下怎么在server certificate时发送双证书，有没有接口

**Comment by conezxy** [comment]
见 #274

**Comment by mysummergit** [comment]
@1132719438 
你好，我目前也准备在gmssl上面改ECC-SM4-SM3，你是在gmssl master还是V1上面改的呢？是在目前ECDHE-SM2-SM4-SM3通信基础上做修改吗？谢谢

**Comment by 1132719438** [comment]
@mysummergit 
在master上改的，主要是ssl握手里有一些报文组包要修改

**Comment by 1132719438** [comment]
@conezxy 
可能是我表述不太清楚，我在国密握手抓包报文里看到一些TLS扩展里有曲线和算法的nid，不是指oid
这个会有影响吗？
![1](https://user-images.githubusercontent.com/10138791/27674124-dd977af8-5cd6-11e7-97e3-8ab2e8c94cc4.PNG)
![2](https://user-images.githubusercontent.com/10138791/27674132-e2e4e252-5cd6-11e7-8f2c-cf3ee0b2b577.PNG)

**Comment by sslvpn007** [comment]
#274 

@1132719438

我也是这个问题，单一证书没问题，但双证书没实现。

第一，双证书怎么加上程序里，
第二，需要改哪些数据结构

我感觉，肯定要增加一个项，来存放另外一个证书（加密证书）。

希望搞定的人，将方案分享下。


另外，274那个，问题没有得到解决。

**Comment by mysummergit** [comment]
@1132719438 
我的目前的master版本编译一直不通过呢，于是一直改的v1版本，目前的master怎么样可以编译通过呢？谢谢

**Comment by 1132719438** [comment]
@mysummergit
master那几个编译错误都比较好改，主要是国密ssl在v1实现的一些功能在master分支没有迁移，还要自己修改

**Comment by sslvpn007** [comment]
如果你要在win下编译使用gmssl，那就用V1。
master编译不行，也有问题。

**Comment by mysummergit** [comment]
好的，那我再去改改master的编译错误，我目前是在linux使用gmssl

**Comment by mysummergit** [comment]
@1132719438 
我master先前就改到这儿，这个错误一直不知道怎么解决，请教一下大家碰到过这个问题吗？
/usr/bin/ld:crypto.map:1: syntax error in VERSION script
collect2: ld returned 1 exit status
make[2]: *** [link_shlib.linux-shared] Error 1
make[2]: Leaving directory `/root/desktop/GmSSL-master'
make[1]: *** [libcrypto.so] Error 2
make[1]: Leaving directory `/root/desktop/GmSSL-master'
make: *** [all] Error 2

**Comment by sslvpn007** [comment]
你的双证书 握手 那个 实现了吗

**Comment by 1132719438** [comment]
是不是要把speck_decrypt16加到/util/libcrypto.num里
这个libcrypto.num不知道是不是某个脚本生成的

**Comment by mysummergit** [comment]
@1132719438 
我按照你说的解决了make时候的那个问题，谢谢
现在make没有问题，但是在make install时候，我用的perl-5.16.1版本，出现很多这些错误
Cannot find "d2i_SSL_SESSION(3)" in podpath: cannot find suitable replacement path, cannot resolve link
Cannot find "SSL_set_fd(3)" in podpath: cannot find suitable replacement path, cannot resolve link
您知道这是什么问题吗？谢谢

**Comment by 1132719438** [comment]
是不是config执行的有问题
这个报错是帮助文件有问题，不影响使用，只要gmssl和libcrypto libssl生成了就行，可以自己复制到相应的目录

**Comment by mysummergit** [comment]
@1132719438 
我刚刚试了下，的确用好像没有问题，谢谢，但是我看到master目前并没有像v1那种可用的国密会话套件呢，你是直接在这上面自己先实现了一个ECC-SM4-SM3，还是这上面哪个会话套件基础上改的呢？

**Comment by 1132719438** [comment]
我是先对照v1在master分支上把ECDHE-SM2-SM4-SM3实现，这样国密几个算法就可以在ssl用了
然后再添加ECC-SM4-SM3套件，主要是server key exchange和client key exchange的报文组包解包以及预主密钥生成需要修改，还有sm2签名要添加Z值得计算

**Comment by 1132719438** [comment]
@sslvpn007
SSL_CTX_use_certificate是用来加载证书的，多次调用的话如果证书的公钥type一样的话就会覆盖之前载入的证书
所以只能修改现有接口或者增加接口，至于证书要添加到哪个数据结构里，不知道有什么优雅的做法

**Comment by 1132719438** [comment]
还有一个问题，server certificate只用传加密和签名证书吗，要不要传输证书链？

**Comment by conezxy** [comment]
需要传证书链，请仔细看规范

-
掌晓愚

在 2017年6月30日，10:30，1132719438 <notifications@github.com<mailto:notifications@github.com>> 写道：


还有一个问题，server certificate只用传加密和签名证书吗，要不要传输证书链？

**Comment by mjjy** [comment]
大家好，我再linux 使用gmssl 编译make卡住不动了，谁遇见过呢
ranlib libssl.a || echo Never mind.
make -f ./Makefile.shared -e \
        PLATFORM=linux-x86_64 \
        PERL="/usr/bin/perl" SRCDIR='.' DSTDIR="." \
        INSTALLTOP='/usr/local/openssl' LIBDIR='lib' \
        LIBDEPS=' '""' -lz -ldl ' \
        LIBNAME=crypto LIBVERSION=1.1 \
        LIBCOMPATVERSIONS=';' \
        CC='gcc' CFLAGS='-DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl\"" -DENGINESDIR="\"/usr/local/openssl/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE' \
        LDFLAGS='' \
        SHARED_LDFLAGS='-Wl,-znodelete -m64 ' SHLIB_EXT=.so.1.1 \
        RC='windres' SHARED_RCFLAGS='' \
        link_shlib.linux-shared
make[2]: Entering directory `/home/kk/GmSSL'
