### ISSUE TITLE
关于gmssl的使用疑问

### ISSUE THREAD

**Issue by cxueqin** [guanzhi/GmSSL#24]
研究信息安全技术，知道国家商用密码标准SM2/SM3/SM4等，既然是标准，理应有参考实现，重复发明轮子似乎没什么必要，而且标准公布也有4年了，一定有热心人士公开国密算法的代码。想到如今最大的代码共享平台github，因此到了这里，此缘起。

相见恨晚，这样的开放心态非常好，很大气，参考实现开源openssl，大家可以直接使用，甚至帮助完善代码，于各方都是有益的，东西融合，大好事。在使用上，一些疑问：
1）看gmssl的代码结构，应该是fork openssl的代码，增加了gmssl部分的处理，即为openssl的分支，使用上是否只需要可以与openssl共存，一般openssl是基础库，操作系统都自带了, 再安装gmssl则不影响原有openssl库的使用？
2）gmssl若基于openssl, 那么是否openssl库的原有功能在gmssl中也都有，这一部分二进制内容是否有重复了？不过，对于PC机而言，这部分的空间消耗不大，但对于一些嵌入式平台，重复的内容空间消耗就要考虑了。
3)能否介绍一下，那些商业机构在用此处公开的gmssl代码？毕竟，有成功案例，可极大的提升用户的信心。

期盼答复，谢谢

**Comment by guanzhi** [comment]
1）看gmssl的代码结构，应该是fork openssl的代码，增加了gmssl部分的处理，即为openssl的分支，使用上是否只需要可以与openssl共存，一般openssl是基础库，操作系统都自带了, 再安装gmssl则不影响原有openssl库的使用？

GmSSL和OpenSSL API兼容并保留了OpenSSL的全部功能，如果已有基于OpenSSL库(libcrypto, libssl)的应用程序，可以重新编译并且用GmSSL替代OpenSSL，但是要考虑版本的问题，目前的GmSSL基于OpenSSL-1.0.2。

GmSSL和OpenSSL二进制不兼容，因此不能将系统自带的OpenSSL动态库替换为GmSSL的动态库。

2）gmssl若基于openssl, 那么是否openssl库的原有功能在gmssl中也都有，这一部分二进制内容是否有重复了？不过，对于PC机而言，这部分的空间消耗不大，但对于一些嵌入式平台，重复的内容空间消耗就要考虑了。

嵌入式平台可以用GmSSL替代OpenSSL并重新编译二进制程序，降低开销。但是一般来说，对于一个平台一份共享的GmSSL动态库就可以了，也就是几MB的空间。

3)能否介绍一下，那些商业机构在用此处公开的gmssl代码？毕竟，有成功案例，可极大的提升用户的信心。

这个信息只能是GmSSL的用户自己公布为准。GmSSL项目欢迎来自用户，特别是商业机构的反馈。

**Comment by LiTianjue** [comment]
强烈建议项目邀请商业机构参与开发，既可以加快开发进度，又有实际应用经验，可以谈一些条件，比如只要某个机构参与开发，项目可以合并该公司的加密卡engine代码，既可以完善项目，又可以推广他们的产品，是双赢的，如果纯开发者参与，项目会缺乏生命力，一家公司参与了，其他公司势必也会加入，项目就能活跃起来，降低门槛对于普通用户是有利的，关键是看那些公司怎么想了

**Comment by guanzhi** [comment]
非常感谢你的建议！

关于合作：这方面的工作已经开展了，参与方为知名企业和机构，但是暂时还不包括加密卡厂商。合作情况在适当的时候我们会正式公布。

关于ENGINE：GmSSL正在开发通用的SKF ENGINE (engines/e_skf.c)，预期目标是符合国密SKF接口标准的加密卡、UKey都可以通过SKF ENGINE接入到GmSSL。如果用户对某个加密卡厂商的产品感兴趣，并且该厂商不提供SKF接口的开发包，那么可以请加密卡厂商和我们联系，在GmSSL中增加对其产品的支持。

**Comment by zhangshuang01** [comment]
guanzhi, 
      你好，我有如下两个问题，希望能帮忙解答。
1. 目前发布的gmssl最新版本，能不能与360国密专版浏览器进行通信，都支持哪些浏览器了呢？
2.gmssl是否已经支持ssl vpn的应用？
3.根据你以上的回答，是不是将来gmssl会添加通用引擎，支持一切符合SKF接口标准的硬件加密设备，而不再需要厂商提供ssl库？

**Comment by guanzhi** [comment]
1. 目前的1.x版本中没有完全按标准实现，因此目前应该不能够与按标准实现的浏览器进行通信。但是不排除在未来支持标准的协议。
2. 目前不支持SSL VPN，但是未来可能支持SSL VPN标准的site2site协议。但是未来也不会提供SSL VPN、IPSec VPN等超出项目范围的功能。
3. 通用引擎已经接近完成，支持标准的SKF接口与SDF接口，上层的密码计算、证书操作和SSL通信可以使用国密硬件。需要厂商的对应SKF或SDF的动态库，但是不依赖于厂商的其他上层库。

**Comment by zhangshuang01** [comment]
@guanzhi 
很感谢你的回复，由于工作需要目前我正在对openssl做简单的修改以支持国密ecc-sm4-sm3, 但在与360国密浏览器的调试过程中服务器发送的server-key-exchange包360总是验证不过，我怀疑自己的签名有问题，这个问题阻碍了我好多天了一直没有解决。等你们发布了能支持浏览器的国密包就是我的福音了！

**Comment by ygm521** [comment]
@guanzhi  gmssl目前支持国密ecc-sm4-sm3算法和 360国密专版浏览器？谢谢

**Comment by LiYang0818** [comment]
@guanzhi 
我们准备使用您的GmSSL 做一款测试软件，请问应该使用那个分支（或release）的代码
是https://github.com/guanzhi/GmSSL 的 master 分支吗？
如果不是，请问应该用那个repo？或者哪个zip包，请您给个链接，谢谢！
