### ISSUE TITLE
请问一个国密双证书握手的问题

### ISSUE THREAD

**Issue by mysummergit** [guanzhi/GmSSL#274]
请问目前版本有实现国密的双证书握手吗？
如果我想在gmssl源码上做国密双证书的握手，我应该大致在哪部分代码中着手呢？谢谢

**Comment by sslvpn007** [comment]
a_verify

加入计算Z值。就可以了

**Comment by sslvpn007** [comment]
另外 建议里 先编译一个 debug版本的库，直接跟踪代码。

这样你就知道哪些需要改了。

我也是弄了很久才解决这个问题。

希望能帮到你。

建议，gmssl这个库，先把SM2、sm3，SM4以及国密SSL VPN 想解决了，

至于SM1，sm9以及SKF等等，这些应该放在最后来实现。

很多人，基本上以SM2、SM3、SM4以及SSL VPN 使用的最多。

**Comment by mysummergit** [comment]
谢谢@sslvpn007，我目前就是想基于v1版本的ECDHE-SM2-SM4-SM3套件来改，我前期看了这个套件只是国密单证书握手，我看了下计算Z值，您说计算Z值的意思是加入计算Z值才能对标准的国密证书进行验签吗？目前我还没进行过debug，您debung出来后双证书的读入、解析、存储主要是在哪个源文件完成的呢？

**Comment by sslvpn007** [comment]
你先验证一个试试。

我也没实现双证。

**Comment by mysummergit** [comment]
@sslvpn007 您目前做ssl vpn的话，vpn这块是基于哪个开源在做呢？我目前这个最终也是想实现一个符合GM/T 0024-2014规范的SSL-VPN

**Comment by LiTianjue** [comment]
gmssl 合并到 openvpn 只需要做少量修改,我之前用openvpn 做的,双证书可以通过extern-cert 来实现,人为的将随机的加密秘钥替换成加密证书秘钥即可,openssl 里面有接口可以很方便的替换掉加密秘钥

**Comment by mysummergit** [comment]
谢谢@LiTianjue，我目前也是在基于openvpn做，一直在看openvpn的源码，您说这个extern-cert这个概念我没有看到过呢，这是openvpn上的还是ssl上的呢，我目前想法是把证书和私钥那个结构体变量在oepnvpn里面定义成数组

**Comment by mysummergit** [comment]
@LiTianjue 
还有就是这个双证书是不是只是服务器端需要双证书，客户端只需要签名证书就可以了？我看了gmssl-vpn规范没有看到哪一步使用了客户端加密证书呢？谢谢

**Comment by sslvpn007** [comment]
@mysummergit

我不知道，你现在有没实现过，然后通过抓包工具，去分析数据。

首先，你先保证，1、能验证国密证书（先实现单一证书）。2、抓包的数据，基本上要符合国密的标准。

如果能先保证这两点，算是迈出了一大步。

说说话，改这个，其实我原本是打算放弃的。想等着gmssl能够出一个完整可用的版本，

但等不了。所以，去分析底层的代码，至少要能跑demo，而且demo跑的数据，基本符合国密标准。

其他的，只能慢慢研究了。

**Comment by mysummergit** [comment]
@sslvpn007 
我目前国密VPN可以用单国密证书通信，因为规范规定了必须使用双证书，才开始做双证书这块，目前也是在抓包和分析源代码在看怎么去做双证书，就是感觉资料不是太多，只有慢慢研究了，谢谢

**Comment by LiTianjue** [comment]
国密文档里面握手协议里面有讲双证书的,但是讲的比较浅显,之前@guanzhi 给过我一份专门讲双证书的文档,你们可以去Issues 里翻翻 , 国密文档里讲握手协议的部分提到,发送 Certificate的时候 ,签名证书在前,加密证书在后,其实是发送了一个证书链,如果你抓过ssl 里的 包,你会发现单证书通讯的时候,是一个签名证书+CA证书,我当时的做法是再加了一个加密证书,加一个证书,openssl 里面也是有接口的

**Comment by LiTianjue** [comment]
openvpn 基本不需修改,只需要做
1. 在ssl协议套件选择的地方选择国密套件
2.国密套件里有RSA秘钥交换算法,openvpn默认不使用RSA秘钥交换算法,如果要用RSA证书,要解除这个限制
3. 要提供加载加密证书和加密秘钥的配置方法

**Comment by LiTianjue** [comment]
讲双证书 的文档在https://github.com/guanzhi/GmSSL/issues/created_by/LiTianjue

**Comment by LiTianjue** [comment]
https://github.com/guanzhi/GmSSL/issues/33

**Comment by sslvpn007** [comment]
@LiTianjue

看了下你发的相关资料，还是一头雾水，

具体在代码上，应该怎么去实现这个双证书呢？

能不能说的具体点，本来对gmssl 相关的东西也不太熟。

望不吝赐教。

**Comment by sslvpn007** [comment]
我怎么把 签名证书 和 加密证书 分别 在程序里加进去呢？

SSL_CTX_load_verify_locations-----这个 我用来加载CA

SSL_CTX_use_certificate_file-------这个用来加载用户证书，我调了两次，一次加载

签名证书，一次加载加密证书，但通过抓包分析，显示的还是一个证书。

**Comment by LiTianjue** [comment]
@sslvpn007 如果我没记错的话,openvpn配置选项里好像天然有extren-cert选项,你可以参考一下他是怎么额外加载一个证书的

**Comment by LiTianjue** [comment]
我现在暂时不做这个了,手上也没有代码,具体实现上你可能要自己琢磨琢磨

**Comment by conezxy** [comment]
首先你要在openssl基础上实现双证书。以国密规范中的ECC-SM4-SM3套件为例，握手流程上主要改动这几个地方：
- 服务端发送自身证书（先发送签名证书，再发送加密证书，再发送上级证书链）
- 客户端接收服务端证书（注意保存服务端的加密公钥）
- 客户端发送自身证书（先发送签名证书，再发送加密证书，再发送上级证书链）
- 客户端发送ClientKeyExchange（要使用服务端的加密公钥进行密钥交换计算）
- 服务端接收客户端ClientKeyExchange（要使用服务端加密私钥进行密钥交换计算）

在openssl实现了双证书握手的基础上，才能开展openvpn的修改（主要是增加命令行参数，使其能加载加密证书和加密私钥）

**Comment by mysummergit** [comment]
@conezxy 
请问1、ECC-SM4-SM3的这个握手套件，是不是客户端的加密证书和加密私钥没有用的呢？我研究了挺久规范，都没有看到客户端的加密证书在哪儿被用到呢？
2、目前gmssl这个开源我只用ECDHE这个秘钥协商的单证书模式跑通了，在看gmssl源码时貌似gmssl-V1版本在ssl3_send_client_key_exchange()函数中没有定义ECC这种秘钥协商呢？
3、所以目前想采用ECDHE-SM4-SM3，但是这个套件的话我看国密规范在客户端发送ClientKeyExchange阶段，也没有要求用服务端的加密公钥加密，所以这个套件要求的双证书中的加密证书在何时使用的呢？
谢谢

**Comment by conezxy** [comment]
- ECC-SM4-SM3在计算过程中的确使用不到客户端的加密证书和私钥，其密钥交换过程非常简单，使用服务端公钥加密即可；但按规范加密证书也是要传递的。
- 而ECDHE-SM4-SM3会使用到非常多的密钥（服务端/客户端加密证书和私钥，以及双方的临时密钥对），此过程更为复杂，建议先实现ECC-SM4-SM3.
- GMSSL的SSL握手实现不是按照国密规范来做的，这点在 #227 中关老师已经回答过了

**Comment by mysummergit** [comment]
@conezxy 
好的，做ECC-SM4-SM3的话，按照我目前理解，是不是就可以几乎模仿RSA的秘钥交换，只是在client端发送预主秘钥时，把本来用服务器RSA公钥加密的地方改成用SM2加密证书公钥加密即可，谢谢

**Comment by conezxy** [comment]
是的

**Comment by AivenYoung** [comment]
ECC-SM4-SM3双向认证，需要用到客户端的双证书和私钥，单向认证是不需要的。模仿RSA的秘钥交换，可以参考，单纯改算法不符合标准，毕竟国密使用的是双证书，一个是单证书。

**Comment by sslvpn007** [comment]
@LiTianjue

你说的抓包双证书：CA+一个证书，这个我是了下，确实是。

那你具体是怎么做的，加了一个项去容纳另外一个证书？

那你发送证书的时候，抓的包是什么情况？还是ca+证书吗？

如果不是，你在发送证书这个过程具体怎么改的

望不吝赐教。

**Comment by LiTianjue** [comment]
1. 我前面提到openvpn 天然自带 extern-cert选项(应该没记错),你可以参考他的实现,看怎么往里面加一个证书

2. 网上有个 <<VPN国密协议及SM2证书的鉴定方法>> 的文档,你可以看一下他抓包的时候是什么情况,

**Comment by LiTianjue** [comment]
刚才特意下了openvpn的代码验证了一下,确实有选项,不过我拼写错了, 应该是 extra-certs

**Comment by LiTianjue** [comment]
接口函数应该就是 
```
tls_ctx_load_extra_certs
```

**Comment by sslvpn007** [comment]
@LiTianjue

感谢帮助，已经解决了双证书的双向认证。

**Comment by 1132719438** [comment]
@sslvpn007
国密的 0x0101 ssl协议版本你实现了吗，国际的0x0303与国密的0x0101能够共存吗？

**Comment by sslvpn007** [comment]
通过抓包，符合国密的标准。

国际的，没有。还没细研究。

现在改的版本，仅仅支持国密。

**Comment by sslvpn007** [comment]
先搞通一个再说吧

没准，等弄兼容国际版本的时候，

关老师等各位老师，已经解决了或完善了所有的问题。

**Comment by mysummergit** [comment]
@LiTianjue 
您好，你好记得在openvpn中用extra-certs加入加密证书后在gmssl的函数中怎么能获取到这本证书吗？是保存在ssl_st结构体哪个变量里面了还是通过哪个函数获取呢？

**Comment by iF2007** [comment]
@sslvpn007 你好，你修改后的国密SSL方便开源下供我们学习吗？谢谢
