### ISSUE TITLE
Linux下编译动态库失败

### ISSUE THREAD

**Issue by whitemay** [guanzhi/GmSSL#28]
在CentOS7下，配置为编译动态库：

./config shared

然后在make的过程中失败，报告如下错误：

making all in apps...
make[1]: 进入目录“/root/GmSSL/apps”
rm -f gmssl
shlib_target=; if [ -n "libcrypto.so.1.0.0 libssl.so.1.0.0" ]; then \
    shlib_target="linux-shared"; \
elif [ -n "" ]; then \
  FIPSLD_CC="gcc"; CC=/usr/local/ssl/fips-2.0/bin/fipsld; export CC FIPSLD_CC; \
fi; \
LIBRARIES="-L.. -lssl  -L.. -lcrypto" ; \
make -f ../Makefile.shared -e \
    APPNAME=gmssl OBJECTS="gmssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o" \
    LIBDEPS=" $LIBRARIES -ldl" \
    link_app.${shlib_target}
make[2]: 进入目录“/root/GmSSL/apps”
../libcrypto.so：对‘PAILLIERerr’未定义的引用
collect2: 错误：ld 返回 1
make[2]: **\* [link_app.gnu] 错误 1

**Comment by guanzhi** [comment]
这个错误大概会在下周的更新中修复。
