### ISSUE TITLE
GmSSL建立ssl/tls客户端和服务端

### ISSUE THREAD

**Issue by bethewind** [guanzhi/GmSSL#29]
你好我想用gmssl建个客户端和服务端，用ssl，sm1,2,3,4的算法进行通信，是不是可以用/demos/ssl里的例子把SSLv2_client_method改成GMSSLv1_client_method，把SSLv23_server_method改成GMSSLv1_server_method，还是统一用GMSSLv1_method？

+#ifndef OPENSSL_NO_GMSSL
+const SSL_METHOD *GMSSLv1_method(void);
+const SSL_METHOD *GMSSLv1_server_method(void);
+const SSL_METHOD *GMSSLv1_client_method(void);

**Comment by guanzhi** [comment]
1. 用xxx_server_method还是xxx_method都可以。
2. GMSSLv1协议还没有做完，现在应该是不能用的。

**Comment by cyj1988jyc** [comment]
请问GMSSLv1协议什么时候会做完？
我试了下会报这样的error
140360640702112:error:14084044:SSL routines:ssl3_connect:internal error:s3_clnt.c:240:

            if ((s->version & 0xff00) != 0x0300) {
                SSLerr(SSL_F_SSL3_CONNECT, ERR_R_INTERNAL_ERROR);
                s->state = SSL_ST_ERR;
                ret = -1;
                goto end;
            }

**Comment by cyj1988jyc** [comment]
你好，我们公司想用国密算法建立客户端和服务端进行TLS通信，所以想问下GmSSL这样的通信什么时候会开发完？
我们可能没能力研究国密和openssl的实现,所以只能靠GmSSL,所以非常感谢北大能提供这样的项目。
另外实现时建议参考/demos/ssl里的例子给出demo，证书，私钥文件，和证书私钥的生成命令，方便使用。
谢谢

**Comment by guanzhi** [comment]
感谢您的建议，如果通信部分完成后应该只经过你上面提出的方法应该就可以使用了（如果这个demo目前可以使用的话）。但是国密SSL协议的预期完成时间不会早于10月份，实际上这部分功能也还没有设定具体的时间表。如果您有商业用途并且时间比较紧迫，可以考虑国密SSL VPN的商密产品，应该有很多厂家都提供满足你需要的产品，具体的产品列表可以在商密办的主页上找到。

**Comment by gs1989nm** [comment]
请问通过现有的gmssl，使用原有openssl协议，可以加载国产证书吗？

**Comment by guanzhi** [comment]
1. 可以解析国密证书
2. 可以生成SM2/SM3证书，但是还没有完全支持国密证书规范
3. 目前还不支持国密SSL协议

**Comment by LiTianjue** [comment]
生成国密正式是使用api编程接口来实现吗，还是gmssl命令行工具，我测试使用命令行工具生成证书请求，会出现段错误，有没有例子的

**Comment by chary931201** [comment]
请问现在 支持 国密SM2加密？我想用的话。需要自己编写api接口来实现吧？

**Comment by guanzhi** [comment]
#include <openssl/sm2.h>
SM2_encrypt/decrypt_with_recommended()

**Comment by pandongzi1980** [comment]
关老师您好，我们想做个网关产品，但是必须支持采用国密SM系列算法的SSL规范。
考虑到自己在openssl中集成国密算法难度超出了我们公司的能力范围，搜索到了您的GMSSL产品，请问目前能拿来替代openssl来让我们实现国密SSL功能吗？谢谢！
另外，我在刚下载GmSSL-master.zip，解压后demos下没有上面说的ssl目录，是不是删除了？
我们的产品要求windows和linux下都支持国密SSL，请问GMSSL目前能支持哪几种操作系统？
祝愿GMSSL越来越强大，给国人带来福音！

**Comment by chary931201** [comment]
@pandongzi1980  东子，你好。我也在做国密方面的。有机会多多交流。我想请教请教。

**Comment by pandongzi1980** [comment]
@chary931201  我刚搞，不懂，qq：15939566，有空多交流，向你请教。

**Comment by QinLongFei** [comment]
请问现在GMSSL支持SSL/TLS了吗？
