### ISSUE TITLE
是否在SSL通讯过程中支持了SM2/SM3/SM4算法

### ISSUE THREAD

**Issue by sinotitan** [guanzhi/GmSSL#3]
你好！

首先，你这个项目非常了不起，意义重大。

我想问下现在是否支持sm2的证书使用OpenSSL的SSL通讯。比如使用s_server和s_client。

我们也正在研究OpenSSL支持国密，希望可以一起交流。

**Comment by guanzhi** [comment]
由于国密SSL的握手协议和密码套件和TLS标准有差异，以及OpenSSL的各个层次之间依赖的依赖关系，GmSSL对国密SSL协议的完全支持需要在对密码库的修改完成之后才能完全展开。
