### ISSUE TITLE
请问在 Android NDK 下 build 的问题

### ISSUE THREAD

**Issue by allenforrest** [guanzhi/GmSSL#30]
请问下 GmSSL 是否有在 Android NDK 下交叉编译 arm/arm64 库的成功范例？
谢谢。

**Comment by guanzhi** [comment]
我们早前尝试编译过。虽然不清楚目前的版本能够通过交叉编译，但是即使出现问题应该也很容易解决。我们之前的方式是直接设定环境变量，将编译器、AR等设定为Android NDK的工具，然后用OpenSSL/GmSSL自己的Configure/Makefile来编译，而没有采用Android自己的mk编译系统。另外网上应该有很多OpenSSL/Android NDK的编译教程，也可以参考。

如果您编译成功，也请将编译过程贴上来分享给其他用户。
如果出现问题，可以把问题发上来看看能够解决。
谢谢。

**Comment by cyj1988jyc** [comment]
https://github.com/rjmangubat23/OpenSSL

**Comment by allenforrest** [comment]
多谢关老师和各位，我模仿 Android 为 OpenSSL 制作的 import 脚本来生成 mk 文件的方式，使用 NDK 编译成功，其间遇到了一些小问题，所幸都较好解决，详细流程随后我整理完发上来。

**Comment by sherry1118** [comment]
@allenforrest 您好。我想请教一下生成mk文件的具体流程，您能把详细流程贴上来吗？谢谢您了。

**Comment by baiyang9981** [comment]
@allenforrest 您好。我想请教一下生成mk文件的具体流程，您能把详细流程贴上来吗？谢谢您了。
