### ISSUE TITLE
有没有人做Android端 Gmssl的，求指导

### ISSUE THREAD

**Issue by hloser** [guanzhi/GmSSL#304]
前几天开始接触gmssl，让同事在linux上编译生成了静态库libcrypto.a 和libssl.a，然后自己用jni，做ndk-build (armeabi)的时候出现了 incompatible target的问题。请问有大神做成功的么，该如何做呢

**Comment by hloser** [comment]
现在对照opnssl的项目自己写.mk,打算用 ndk-build直接编译试试看了，armeabi 平台的貌似缺失很多文件（和openssl对照）。

**Comment by sherry1118** [comment]
我之前按照源码中的openssl的.mk文件来编译gmssl未能成功，如果您成功了，能教教我吗？

**Comment by hloser** [comment]
研究了半天最终没有实现，现在经理让 不用TLS了，直接伪SSL握手，连证书都不用。%>_<%

**Comment by 27954741** [comment]
要编译一个.so的文件,然后用java来调用.

**Comment by javake** [comment]
所以Android的用户大多是 从研究到放弃么？

**Comment by xuyewen288** [comment]
http://gmssl.org/docs/install.html
照这个编译就好， 要先自己下一个androidtoolchain 或者ndk编译一个
记住make前要make clean 不然会报错。。

**Comment by javake** [comment]
所以楼上是就加 make clean就好了？
交叉编译环境脚本本身就会找ndk里了，

当然，我这还是一堆错误

**Comment by xuyewen288** [comment]
不是的，我开始也是在配ndk的环境路径，但是怎么都不对，后来，自己弄了个 android-toolchain-arm在ndk目录下面， 这个你自己编译出来就可以吧，或者网上下一个

**Comment by swjtk** [comment]
直接下载Android5.0的工程代码，对照里面的openssl源码，编译出libcrypto.so 和libssl.so,然后在Android studio里使用。

**Comment by zhangxy123666** [comment]
可以在Android下使用，包括java调用JNI 加密和直接C层加密，等会儿整理发上来，避免大家踩这个大坑
