### ISSUE TITLE
基于Ubuntu 16.04 LTS系统上成功编译经验分享

### ISSUE THREAD

**Issue by zhu071011** [guanzhi/GmSSL#305]
环境：Ubuntu 16.04 LTS 32位
基于17.06.30的gmssl版本。
首先这份源码，在test文件夹里有语法错误。
test/seroenttest.c 这个文件里面缺少一个变量的定义和使用的函数入参变动了。
输入指令：perl util/mkdef.pl crypto update
执行成功后会提示你有哪些老旧的东西，update了哪些东西。
执行过后，再按照官方教程 ./config 和 make。
我是执行成功了。然后去执行make install也成功了。
在执行gmssl version检查安装情况之前，请执行以下指令：（我用的是ubuntu的虚拟机不是64的，如果你们是64的系统，请把lib换成lib64）
sudo ln -s /usr/local/lib/libssl.so.1.1 /usr/lib/libssl.so.1.1
sudo ln -s /usr/local/lib/libcrypto.so.1.1 /usr/lib/libcrypto.so.1.1
到这里gmssl就安装完毕了。不过我是开发android的，还有android的版本要尝试。如果我能成功的话我也不会吝啬的分享出来，讨厌自私自利的人。

Android版编译成功了！！不过还没有集成到项目里验证是否真的好用，不过我先说一下我的做法，希望能帮到大家一点，中间碰到了很多问题，一一克服后总算是没有报错了。
好文章推荐：https://stackoverflow.com/questions/11929773/compiling-the-latest-openssl-for-android
上面的文章是没有通过setenv-android.sh脚本来做的。我是按照openssl的官方wiki来做的：
首先，下载openssl for android：	https://github.com/rjmangubat23/OpenSSL.git
下载下来后，先在setenv-android.sh做如下修改：
首先给变量赋值：（注意这些变量有_开头和没有_开头之分，而且还不止一处需要赋值不要漏赋值）
ANDROID_NDK=$NDK_HOME（已经配置了NDK的根目录为环境变量）
_ANDROID_EABI="arm-linux-androideabi-4.9"
_ANDROID_API="android-23"
ANDROID_TOOLCHAIN="$ANDROID_NDK_ROOT/toolchains"
然后再额外添加这些语句：
export CROSS_SYSROOT="$ANDROID_SYSROOT"
export NDK_TOOLCHAIN_BASENAME="$ANDROID_TOOLCHAIN/arm-linux-androideabi"
export LD="$NDK_TOOLCHAIN_BASENAME-ld"

其中ANDROID_SYSROOT配置的地址（根据实际位置变动）：/home/molly/develop/android-ndk-r14b
ANDROID_TOOLCHAIN配置的地址（根据实际位置变动）：$ANDROID_NDK_ROOT/toolchains

使用教程地址：https://wiki.openssl.org/index.php/Android
上面的教程中有一句话“perl ........ Makefile.org”这句话里要用到这个Makefile.org，这个在gmssl里是没有的。你们可以下载普通的openssl源码，把里面的Makefile.org拷贝到gmssl的目录下，可用。

做完这些，还要安装：
sudo apt-get install gcc-multilib
sudo apt-get install g++-multilib
sudo apt-get install cmake（可装可不装因为我发现最新的ndk里面提到他们不用gcc了我也搞不清楚学艺不精，但是我本人是装了的就提一下）

这些准备工作做好后，执行：
chmod a+x setenv-android.sh
. ./setenv-android.sh
perl -pi -e 's/install: all install_docs install_sw/install: install_docs install_sw/g' Makefile.org
./config shared no-ssl2 no-ssl3 no-comp no-hw no-engine no-saf no-sdf no-skf no-sof no-zuc --openssldir=/usr/local/ssl/$ANDROID_API --prefix=/usr/local/ssl/$ANDROID_API
其中$ANDROID_API我配置的是android-23
执行完config，会动态生成makefile文件。
make depend
make all
如果你在执行make的途中出现一些语法错误，比如在test文件夹里的，那么这些你可以在makefile文件里删除掉这个文件，因为是测试代码所以无所谓啦。删的话注意不是删除XXXX：XXXX这种格式的地方。而是在一堆...test/XXXX test/yyyyy ...这样的地方删除掉这样就不会编译他了。
以上就是我编译成功的过程，希望能帮到大家。

如何将so库加入到工程里？（本人亲自测试有效）
我是参考这位朋友的教程，非常棒！http://www.jianshu.com/p/07df7626b4ee

**Comment by sherry1118** [comment]
谢谢大神的分享，商用密码管理中心也公布了一些国密算法的源码，而且代码正确，您可以试试用那个源码，我也是要在android上实现的，但也出了问题一直没有解决。如果您编译成功了，可不可以教教我？

**Comment by hloser** [comment]
好样的，我上周研究这个没搞懂。网上都没啥资料，一脸懵逼，不过最终经理放弃直接用gmssl。给楼主120个赞，我也是做Android的，求大神带O(∩_∩)O哈哈~

**Comment by AivenYoung** [comment]
GMSSL分支貌似不是很稳定，在不断的开发中。

**Comment by zhaoxiaomeng** [comment]
master 分支正在不断完善，V1的分支相对来说比较稳定，感谢分享。希望能够有更多的人参与并分享自己的经验。

**Comment by WeWebsterchen** [comment]
Linux VM_96_58_centos 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux 编译
sdftest.c:(.text.unlikely+0x45): undefined reference to `SDF_InternalSign_ECC'
sdftest.c:(.text.unlikely+0x5b): undefined reference to `SDF_InternalVerify_ECC'
sdftest.c:(.text.unlikely+0x76): undefined reference to `SDF_ExportSignPublicKey_ECC'
sdftest.c:(.text.unlikely+0x84): undefined reference to `SDF_GetErrorString'
sdftest.c:(.text.unlikely+0x9d): undefined reference to `SDF_PrintECCPublicKey'
sdftest.c:(.text.unlikely+0xc1): undefined reference to `SDF_ExternalVerify_ECC'
sdftest.c:(.text.unlikely+0xdc): undefined reference to `SDF_ExportEncPublicKey_ECC'
sdftest.c:(.text.unlikely+0xea): undefined reference to `SDF_GetErrorString'
sdftest.c:(.text.unlikely+0x11d): undefined reference to `SDF_PrintECCPublicKey'
sdftest.c:(.text.unlikely+0x14b): undefined reference to `SDF_ExternalEncrypt_ECC'
test/sdftest.o: In function `test_sdf_file':
sdftest.c:(.text.unlikely+0x1ae): undefined reference to `SDF_CreateFile'
sdftest.c:(.text.unlikely+0x1b9): undefined reference to `SDF_GetErrorString'
sdftest.c:(.text.unlikely+0x1f8): undefined reference to `SDF_WriteFile'
sdftest.c:(.text.unlikely+0x203): undefined reference to `SDF_GetErrorString'
sdftest.c:(.text.unlikely+0x22e): undefined reference to `SDF_ReadFile'
sdftest.c:(.text.unlikely+0x239): undefined reference to `SDF_GetErrorString'
sdftest.c:(.text.unlikely+0x271): undefined reference to `SDF_DeleteFile'
sdftest.c:(.text.unlikely+0x281): undefined reference to `SDF_GetErrorString'
collect2: error: ld returned 1 exit status
make[2]: *** [link_app.gnu] Error 1
make[2]: Leaving directory `/mydata2/websterchen/GmSSL-master'
make[1]: *** [test/sdftest] Error 2
make[1]: Leaving directory `/mydata2/websterchen/GmSSL-master'
这个报错是什么情况

**Comment by QwertyJack** [comment]
@zhu071011 编译安装完后执行一个`sudo ldocnfig`就好了，你这样手动链接库文件也行。

**Comment by gogoforit** [comment]
感谢 楼主Ubuntu的解决方法~
