### ISSUE TITLE
是否可以通过openssl engine机制实现SM2

### ISSUE THREAD

**Issue by linwenbo** [guanzhi/GmSSL#306]
openssl 的RSAengine很好实现，但是还没有见到过ecc算法的engine，并且ecdh和ecdsa在openssl
中是分开的两种method。我在openssl中也没有找到通过ecc加密解密的部分。
现在想通过openssl的engine机制来实现openssl对国密算法的支持，请问有没有什么好的办法？

**Comment by shi-hao** [comment]
你可以先看下这个issue，https://github.com/guanzhi/GmSSL/issues/189，对你可能有帮助。

**Comment by Linwenbo** [comment]
谢谢@shi-hao
我这边工作情况不允许修改openssl的代码，所以只能通过engine的方式来实现。
目前还是打算通过engine方式重写ecdh和ecdsa的method，但是ecies就没办法了，openssl中好像并没有ecies的method。

**Comment by guanzhi** [comment]
1、新的GmSSL-2.0/OpenSSL-1.1中Engine接口已经将ECDH/ECDSA合并到一起了。
2、加密算法可以通过ctrl或者pkey接口提供ECIES、SM2加密
3、如果独立的ENGINE对于您的应用场合非常必要，请提供介绍说明，我们可以考虑在未来的版本中提供独立的国密ENGINE

**Comment by Linwenbo** [comment]
谢谢关老师关注:)
我这边项目中有关于这方面的需求，主要是想使用openssl并在openssl更新时进行快速更新部署。采用engine的方式不需要更改openssl的代码和结构，应该是比较方便的做法。
个人感觉这种需求应该挺广泛的，如果能够提供国密的engine实现当然最好啦。
