### ISSUE TITLE
关老师，GmSSL-v2 国密套件有发布的计划吗？

### ISSUE THREAD

**Issue by lilucpp** [guanzhi/GmSSL#307]
关老师，您好。GmSSL-v2 国密套件有发布的计划吗？

**Comment by sslvpn007** [comment]
希望GMSSL-V2版本，能先支持：
SM2\SM3\SM4算法，以及符合国密标准的SSL功能。

**Comment by guanzhi** [comment]
预计9月份可以正式发布，目前在做硬件测试。

**Comment by johncol001** [comment]
关老师，我用wireshark抓包，分析clienthello的时候，cipher suite:unknown(0xe102).可能这块的没分析出来，我想问一下，这块对应的加密套件是ECDHE-SM2-WITH-SMS4-SM3吗？我用的是GMSSL2.0代码，在
GMT 0024-2014 SSL VPN里面没有相关的定义，所以这块比较迷茫，能帮忙确认一下吗？
