### ISSUE TITLE
gmssl命令行进行sm2加密

### ISSUE THREAD

**Issue by 344389541** [guanzhi/GmSSL#308]
hi. 用gmssl命令行进行sm2的加密。命令行参数如下
gmssl pkeyutl -encrypt  -pubin -inkey pubkey.pem -pkeyopt ec_encrypt_algor:sm2 -in ./sm2_in.bin -out demo.bin

例如 公钥数组是

char std_pubKey[64] = {0x09, 0xF9, 0xDF, 0x31, 0x1E, 0x54, 0x21, 0xA1, 0x50, 0xDD, 0x7D, 0x16, 0x1E, 0x4B, 0xC5, 0xC6,
									0x72, 0x17, 0x9F, 0xAD, 0x18, 0x33, 0xFC, 0x07, 0x6B, 0xB0, 0x8F, 0xF3, 0x56, 0xF3, 0x50, 0x20,
									0xCC, 0xEA, 0x49, 0x0C, 0xE2, 0x67, 0x75, 0xA5, 0x2D, 0xC6, 0xEA, 0x71, 0x8C, 0xC1, 0xAA, 0x60,
									0x0A, 0xED, 0x05, 0xFB, 0xF3, 0x5E, 0x08, 0x4A, 0x66, 0x32, 0xF6, 0x07, 0x2D, 0xA9, 0xAD, 0x13};

这个公钥数组怎么生成sm2能用的pem格式？
感谢大神帮忙解答。

**Comment by guanzhi** [comment]
需要通过编程实现，可以参考crypto/gmapi中的代码

**Comment by 344389541** [comment]
参考例子，自己实现了。忘记close了。
