### ISSUE TITLE
#error MD2 is disabled 

### ISSUE THREAD

**Issue by mrpre** [guanzhi/GmSSL#31]
HA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM   -c -o md2_dgst.o md2_dgst.c
In file included from md2_dgst.c:62:
../../include/openssl/md2.h:64:4: error: #error MD2 is disabled.
make[2]: **\* [md2_dgst.o] Error 1
make[2]: Leaving directory `/studio/gmssl/GmSSL/crypto/md2'
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory`/studio/gmssl/GmSSL/crypto'
make: **\* [build_crypto] Error 1
需要./config 时怎么不去编译md2 ?

**Comment by guanzhi** [comment]
不太理解你的意思，但是MD2不安全，默认应该是不编译的

**Comment by baggiowangyu** [comment]
我也遇到这样的问题，该怎么解决？

**Comment by mrpre** [comment]
@baggiowangyu 自己把 md2.h文件里 "#error MD2 is disabled" 这句话删掉。
当然，你会发现，后面还会有错，错哪里删哪里。

**Comment by mrpre** [comment]
@baggiowangyu 自己把 md2.h文件里 "#error MD2 is disabled" 这句话删掉。
当然，你会发现，后面还会有错，错哪里删哪里。

**Comment by mrpre** [comment]
其实MD2还是必要的，我就见过某机构现在用的根证书 是RSAwithmd2签名的。其实MD2还是必要的，我就见过某机构现在用的根证书 是RSAwithmd2签名的。
