### ISSUE TITLE
关于国密双证书算法与标准rsa算法的兼容问题

### ISSUE THREAD

**Issue by zhangshuang01** [guanzhi/GmSSL#311]
在gmssl的使用中发现，如果代码作为服务器端使用，需要调用GMSSLv1_server_method方法，而该方法的实现IMPLEMENT_gm1_meth_func中版本项为GM1_VERSION， 这样以来服务器就只能支持1.1版本的国密，而不能支持普通的RSA算法了！有什么办法能让他们兼容起来呢？

**Comment by sslvpn007** [comment]
我不知道 你用的哪个版本的gmssl。线上多个版本，之前我均试过，没有一个是完全支持国密的。
很多地方需要自己去改。

另外，你抓包支持国密了吗？

**Comment by sslvpn007** [comment]
我改了下V1版本，才支持。

**Comment by zhangshuang01** [comment]
我用的gmssl-master，修改后也能支持国密。谢谢你的答复！暂时不考虑兼容的需求了！
