### ISSUE TITLE
GMSSL对Golang的支持

### ISSUE THREAD

**Issue by gluttonouszx** [guanzhi/GmSSL#312]
关老师，您好！请问当前GMSSL对Golang的api接口开发完成了吗？我从master分支和v1.3.0-bin分支都没有能够成功运行。运行v1.3.0-bin中的test文件，发现SM3之前的部分能够成功调用，但SM3-HMAC、SM4以及SM2都会报空指针错误。
谢谢！

**Comment by guanzhi** [comment]
Go-API是直接针对GmSSL-2.0/OpenSSL-1.1.0的API开发的，不兼容GmSSL-1.3/OpenSSL-1.0.1的API。Go-API具体会包含哪些接口，支持哪些功能还需要用户的反馈。我们非常希望能够了解Go的用户的典型应用是什么？优先需要访问哪些功能？

**Comment by hxzqlh** [comment]
典型用法基本都差不多，比如：
```
c, err := crypto.New(name) // 生成加密实例子，name 是具体加密类型，sm2, sm3, sm4 等

priv, err := c.GenKey() //生成私钥
priv, err := c.PrivKeyFromBytes(bytes) // 加载私钥

pub := priv.PubKey() // 从私钥获取公钥
pub := c.PubKeyFromBytes(bytes) //加载公钥匙

signature := priv.Sign(msg) // 私钥对内容签名
signature, err := c.SignatureFromBytes(bytes) //加载签名

ok := pub.VerifyBytes(msg, signature) // 验证签名
```

**Comment by sheepbao** [comment]
好像只支持连接，而不支持作为服务端的监听？国内的政府项目网络通信需要国密
