### ISSUE TITLE
GmSSL在我的虚拟机上编译不过？

### ISSUE THREAD

**Issue by s0948013** [guanzhi/GmSSL#315]
我的笔记本是联想扬天系列B51-35的，AMD-A8四核CPU，8G内存，1T硬盘，Windows 7。虚拟机为2核、4G内存、200G硬盘，CentOS 7。

在如下网址点击绿色“Clone or Download”获得的代码：https://github.com/guanzhi/GmSSL/。用binary方式将GmSSL-master.zip经ftp传给虚拟机，再用unzip打开，之后执行“./config”成功，再后make出错？

![gmssl -github_download-2017-07-09](https://user-images.githubusercontent.com/21612379/27992884-bd417248-64d0-11e7-9e70-be229530b7a7.png)

![gmssl -github-2017-07-09](https://user-images.githubusercontent.com/21612379/27992886-ccafa222-64d0-11e7-8e9d-ebc125af20c5.png)

经过“make clean”和“make update”，再make，出如下错误：

![gmssl -make_update -2017-07-09](https://user-images.githubusercontent.com/21612379/27993176-b4699b40-64d6-11e7-94e6-ee270955bac4.png)

**Comment by zhaoxiaomeng** [comment]
./config no-speck no-serpent
make update 
make 
sudo make install

**Comment by s0948013** [comment]
赵师兄：
我按照你的指点：
1、./config no-speck no-serpent
2、make update
3、make
在第三步make时还是有错。如下：

![gmssl -config_no-speck_no-serpent-2017-07-11](https://user-images.githubusercontent.com/21612379/28054795-f2bd38d4-6648-11e7-9cf6-33dfa3ce92dd.png)

**Comment by zhaoxiaomeng** [comment]
你重新下载一份代码，然后试试

**Comment by s0948013** [comment]
赵师兄：
还是不行？我点击github上的那个绿色大按钮“clone or download”，下载了.zip文件，传到虚拟机上编译还是通不过，与前面的错误一样？

![gmssl -redownload-2017-07-12](https://user-images.githubusercontent.com/21612379/28098908-863c2f14-66eb-11e7-9c1f-275bc84232c8.png)

**Comment by zhaoxiaomeng** [comment]
./config 
make update 
make
