### ISSUE TITLE
我生成证书的命令是否正确？

### ISSUE THREAD

**Issue by ugenehan** [guanzhi/GmSSL#319]
1.生成CA自签证书
（1）gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out ca.key
（2）gmssl req -sm3 -new -x509 -days 365 -key ca.key -out ca.crt
2.生成server证书，并用CA签证
（1）gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve  -out server-key.pem -des3 2048
（2）gmssl req -sm3 -new -key server-key.pem -out server-csr.pem
（3）gmssl ca -in server-csr.pem -cert ca.crt -keyfile ca.key -out server-cert.pem -days 3650
3.生成client证书，并用CA签证
（1）gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve  -out client-key.pem -des3 2048
（2）gmssl req -sm3 -new -key client-key.pem -out client-csr.pem
（3）gmssl ca -in client-csr.pem -cert ca.crt -keyfile ca.key -out client-cert.pem -days 3650

**Comment by 1132719438** [comment]
我是这样生成的

创建CA密钥
gmssl ecparam -genkey -name sm2p256v1 -out cakey.pem

创建CA证书请求
gmssl req -new -sm3  -key cakey.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=CA/OU=CA/CN=ROOT\ CA/emailAddress=rootca@gmail.com -out cacsr.pem

生成CA自签名证书
gmssl req  -x509  -sm3 -days 3650 -key cakey.pem -in cacsr.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=CA/OU=CA/CN=ROOT\ CA/emailAddress=rootca@gmail.com -out cacert.pem

创建S/C密钥
gmssl ecparam -genkey -name sm2p256v1 -out serverkey.pem
gmssl ecparam -genkey -name sm2p256v1 -out serverkey2.pem
gmssl ecparam -genkey -name sm2p256v1 -out clientkey.pem
gmssl ecparam -genkey -name sm2p256v1 -out clientkey2.pem

创建S/C证书请求
gmssl req -new  -sm3 -key serverkey.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=Server/OU=Server\ Sign/CN=172.17.140.127/emailAddress=server@gmail.com -out servercsr.pem
gmssl req -new  -sm3 -key serverkey2.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=Server/OU=Server\ Encrypt/CN=172.17.140.127/emailAddress=server@gmail.com -out servercsr2.pem
gmssl req -new  -sm3 -key clientkey.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=Client/OU=Client\ Sign/CN=172.17.140.127/emailAddress=client@gmail.com -out clientcsr.pem
gmssl req -new  -sm3 -key clientkey2.pem -subj /C=CN/ST=Shang\ Hai/L=SH/O=Client/OU=Client\ Encrypt/CN=172.17.140.127/emailAddress=client@gmail.com -out clientcsr2.pem

签发S/C证书
gmssl x509 -req -sm3 -days 3650 -CA cacert.pem -CAkey cakey.pem -CAcreateserial -in servercsr.pem -out servercert.pem
gmssl x509 -req -sm3 -days 3650 -CA cacert.pem -CAkey cakey.pem -CAcreateserial -in servercsr2.pem -out servercert2.pem
gmssl x509 -req -sm3 -days 3650 -CA cacert.pem -CAkey cakey.pem -CAcreateserial -in clientcsr.pem -out clientcert.pem
gmssl x509 -req -sm3 -days 3650 -CA cacert.pem -CAkey cakey.pem -CAcreateserial -in clientcsr2.pem -out clientcert2.pem

**Comment by ugenehan** [comment]
跟我的一样，也是提示这个错误。gmssl1.3.0版本
SSL connection using (NONE)
Client does not have certificate.
140099596494504:error:140780E5:SSL routines:ssl23_read:ssl handshake failure:s23_lib.c:137:

**Comment by 1132719438** [comment]
报这个错是因为客户端没有传证书吧

**Comment by ugenehan** [comment]
我是按照openssl流程写的服务端和客户的，gmssl应该也是这个流程吧？

**Comment by 1132719438** [comment]
有可能是因为没有传客户端证书，或者客户端证书类型不正确

**Comment by zppet** [comment]
Other notes:
1.	To show private key content:
gmssl ec -in hsm_device_key.pem -text -out private.txt

**Comment by didiyou** [comment]
按照一楼的说法，生成server证书的第三步，显示ca: Cannot open input file server-csr.pem, No such file or directory，请问这是为什么
