### ISSUE TITLE
关于https握手性能测试

### ISSUE THREAD

**Issue by 1132719438** [guanzhi/GmSSL#320]
想要测试一下gmssl的https握手性能，现在已经找到可用的客户端性能测试软件，想问各位一下，有没有比较简单的搭建多线程https服务端的软件，能有性能统计功能更好

**Comment by guanzhi** [comment]
推荐的方案是：
1. 将GmSSL和Nginx编译在一起，通过Nginx提供SSL服务。
2. 利用现有的性能测试工具测试Nginx/GmSSL的性能。

**Comment by 1132719438** [comment]
@guanzhi 感谢，使用nginx测试了，性能还可以

**Comment by ygm521** [comment]
@1132719438  你使用nginx哪个版本 和 gmsll哪个版本 centos哪个版本？谢谢
