### ISSUE TITLE
go语言的维护缺失啊

### ISSUE THREAD

**Issue by xiaou** [guanzhi/GmSSL#321]
https://github.com/guanzhi/GmSSL/blob/master/go/gmssl/ibc.go
最下面的代码都不全。不仅仅是这一个go文件。go这块是不是没人维护啊。

**Comment by zhaoxiaomeng** [comment]
由于人员和时间有限，go 语言这部分的工作刚刚开始。如果可以的话，欢迎大家多多参与贡献代码。

**Comment by hxzqlh** [comment]
建议维护人员在提交、合并代码的时候： 1. 本地做好测试 2. master 分支应该是稳定可用的版本  ，免得给大家造成不必要的困扰。

**Comment by zhaoxiaomeng** [comment]
好的，我们会在后续维护的时候注意这个，目前Travis 测试功能有限，如果可以的话大家可以多多贡献代码。
