### ISSUE TITLE
官方二进制包是否支持 alpine

### ISSUE THREAD

**Issue by deepzz0** [guanzhi/GmSSL#324]
今天制作 docker 镜像，使用 alpine 作为基础镜像，但是好像不支持。一值报 `sh: common not found`。不知道是什么原因，在 ubuntu 下是可以的。

**Comment by kimqcn** [comment]
官方二进制包为啥不支持XXOO v2.0系统呢？XXOO v2.0系统可是alpha星系半人马座最流行的系统丫！

**Comment by deepzz0** [comment]
看了下，Linux 包编译的时候是动态链接的，但是 alpine 内根本没有链接的文件

**Comment by guanzhi** [comment]
具体是什么包？

**Comment by deepzz0** [comment]
$ file gmssl
gmssl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter **/lib64/ld-linux-x86-64.so.2**, for GNU/Linux 2.6.24, BuildID[sha1]=343c1b0afb1b9666b421eb6a55624dbf241bbd1f, not stripped

alpine 里没有 /lib64 文件夹
