### ISSUE TITLE
参照Gmssl-master该怎么入手写国密标准的接口

### ISSUE THREAD

**Issue by zyxx-13** [guanzhi/GmSSL#326]
现工作需要写符合密码设备应用接口规范和通用密码服务接口规范的接口现遇到如下问题：
1.看到现在代码中有SAF,SDF相关代码该如何入手去看这些代码？
2.该如何入手写SAF,SDF接口？
3.现有的SAF,SDF代码是否已经编写完成？是否能够直接用？
4.SAF,SDF,SOF,SKF的缩写分别是什么？
来自一个刚工作的新手提问，求各位大神给予回复。。。。（比心）

**Comment by guanzhi** [comment]
SKF和SDF两个接口在GmSSL中是内部接口，用于GmSSL访问各种密码硬件设备。GmSSL增加这两个模块的目的是让应用可以忽略USB-Key、TF/SD密码卡、PCI-E密码卡等不同类型密码设备的差异和GmSSL的算法软实现，可以由GmSSL的EVP/ENGINE API或者命令行调用这些硬件。由于厂商对SKF和SDF标准的理解和实现上有差异，应用这些访问这些接口不会有理想的可移植性。SAF和SOF是直接面向应该用的高层接口，建议应用调用这两个接口。SAF接口和GmSSL的原生EVP接口比较类似，在GmSSL实现上是EVP接口的封装，在使用上会比EVP更简洁一些。SAF等均来自函数名前缀，无官方缩写定义。SKF/SDF/SAF都会得到完整的支持，但是SOF的支持会靠后。实现的可用程度以更新的代码为准。
