### ISSUE TITLE
windows  有人可以编译过吗？

### ISSUE THREAD

**Issue by durake** [guanzhi/GmSSL#328]
rt

**Comment by 1132719438** [comment]
master有一些小问题，修改一下就可以编译了

**Comment by durake** [comment]
link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\jiao\AppData\Local\Temp\nm97DE.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 speck_expand16
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 speck_expand32
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 speck_expand64
libcrypto.lib : fatal error LNK1120: 3 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”

其他的编译错误我改了 但我遇到了这个问题

**Comment by 1132719438** [comment]
你用什么命令编译的，我编的时候没遇到这个问题

**Comment by durake** [comment]
perl Configure VC-WIN32
nmake
nmake install


网站上的

**Comment by 1132719438** [comment]
libcrypto.num里面有speck_expand16吗

**Comment by durake** [comment]
有

**Comment by 1132719438** [comment]
先执行一下
perl util/mkdef.pl crypto update
看看libcrypto.num里面还有没有speck_expand16，如果还有的话搜索整个工程看看哪里有speck_expand16

**Comment by durake** [comment]
还是有 我没有找到speck_expand 这个函数 。
 我现在编译的是主页下的zip 包。  我又试了之前有人给我的另一个包 编译是另外一个函数链接不到。但是我可以找到这个函数的实现，但是包含这个函数的c文件并未生成obj 文件。 还有我想知道如何看版本号码。

**Comment by 1132719438** [comment]
在speck.h里把这几个函数注释掉

**Comment by 1132719438** [comment]
然后重新生成libcrypto.num

**Comment by durake** [comment]
这回可以编译过了  非常感谢你的指导

**Comment by memdumper** [comment]
@durake 请问有编译生成了gmssl.exe吗

**Comment by durake** [comment]
@memdumper  生成了

**Comment by memdumper** [comment]
@durake 请问你编译的版本和 Visual Studio版本，我的情况下vs2010，
GmSSL-GmSSL-v1版本编译,perl Configure VC-WIN32后执行nmake，报错
makefile(241) : fatal error U1001: 语法错误: 宏中的非法字符“{”
Stop.
Master 版本 base58.c变量定义报错。

**Comment by durake** [comment]
我用的主页上下的代码  用的vs2013  master 那个base58.c错误你可以自己改下。

**Comment by dlynine** [comment]
@durake 你好，可以把你编译好的，分享下吗？非常感谢

**Comment by durake** [comment]
@dlynine  邮箱发我
