### ISSUE TITLE
请问一个添加ECC密钥协商的问题

### ISSUE THREAD

**Issue by mysummergit** [guanzhi/GmSSL#329]
我目前在gmssl加入ECC密钥协商，因为在ECDH的密钥协商的一些代码上改，目前我在客户端发送ECC加密的预主密钥给服务器时（ssl3_send_client_key_exchange），该消息长度是144字节，而ECDHE在该阶段是发送66字节，所以我想发送的消息无法用ssl_do_write(s)全部传过去，我想请问下该阶段发送消息的长度的定义是在哪儿的呢？找了好久没有找到在哪儿定义的，谢谢各位了

**Comment by 1132719438** [comment]
ssl_set_handshake_header第三个参数就是长度

**Comment by mysummergit** [comment]
@1132719438
设置后协商成功了，谢谢
