### ISSUE TITLE
sm2 加解密问题

### ISSUE THREAD

**Issue by LiTianjue** [guanzhi/GmSSL#33]
老师，你好
我用sm2做加解密测试的时候，
加密可以出来结果
解密的时候失败了，这是什么问题
API的调用正确吗，还是其他的什么问题

``` c

int test_sm2_enc()
{
    EC_KEY *key1;
    EC_GROUP    *group1;
    int nid,ret;

    key1 = EC_KEY_new();
    if(!key1)
        return 0;

    int nid = NID_sm2p256v1;
    group1 = EC_GROUP_new_by_curve_name(nid);
    if(group1 == NULL)
        return 0;

    ret = EC_KEY_set_group(key1,group1);
    if(ret != 1)
        return 0;

    ret = EC_KEY_generate_key(key1);

    //EC_KEY_print_fp(stdout,key1,0);
    /*---- ----*/

    printf("----加密测试----\n");
    char tmp_buf[48] = {0};
    memset(tmp_buf,'1',48);

    char out_buf[48+128] = {0};
    int buf_size = 48 +128;

    if(!SM2_encrypt_with_recommended(out_buf,&buf_size,
                (const unsigned char *)tmp_buf,sizeof(tmp_buf),key1)) {
        printf("SM2 Encryp ERROR !!!\n");
        return -1;
    }
    else
    {
        printf("SM2 Encrypt Result[%d] :\n",buf_size);
        //print_hex(out_buf,buf_size);
        printf("----测试成功----\n\n");
    }

    printf("----解密测试----\n");
    unsigned char msg[128] = {0};
    size_t msglen = 0;
    if(!SM2_decrypt_with_recommended(msg,&msglen,out_buf,buf_size,key1))
    {
        printf("解密失败！！！\n");
        return -1;
    }else {
        printf("SM2 Decrypt Result[%d] :\n",msglen);
        //print_hex(msg,msglen);
        printf("----测试成功----\n\n");
    }

    return 0;
}
```

另外想问一个国密SSL的问题
现在代码树中定义了SSL_kECC 密钥交换算法，我想问这是什么算法
从文档上看和SSL_kRSA算法应该是差不多(用非对称密钥加密预主密钥)，但是似乎openssl里面没有这种类似的算法
是不是要自己实现

**Comment by LiTianjue** [comment]
----加密测试----
SM2 Encrypt Result[145] :
04 1F D6 11 66 1E 53 60 A0 C2 98 E4 78 08 7D 50 E6 4C 98 CC 0C 3E 68 7B 5C F5 D9 3E B3 CE 38 CA E0 D2 99 02 EF 2A 68 18 3F 80 2D 76 93 2C DD F5 3C 87 54 62 F0 C2 87 51 47 EC B9 E5 DA 63 57 1E 78 15 AE 1B 36 83 F1 58 0B 1C 8A 58 3F F8 EE 30 0A 6D 3C 25 E1 BC AE E3 52 CA CA 6C F4 31 E6 FD 32 34 A7 C7 24 EE 6A 07 91 02 9B 73 1F DC 8E BD 90 91 26 02 CB 7C 35 F2 B9 94 83 8A 5F C1 B7 F8 A4 62 F6 32 E0 B1 F3 F4 55 C5 39 9F DA EA 80 48 54
----测试成功----

----解密测试----
解密失败！！！

**Comment by LiTianjue** [comment]
另外cryto/sm2/sm2test.c 编译之后运行也是出错的

sm2 sign p256 passed
sm2 sign b257 passed
error: sm2test.c 359
139772977178256:error:3406A06A:SM2 routines:SM2_decrypt:error:sm2_enc.c:520:
sm2 enc p256 failed

SM2 test failed

通过关注项目得到的信息是目前版本提供了完整的加解密示例
是不是我没找对示例代码的位置

**Comment by guanzhi** [comment]
sm2test.c可以看做是SM2加密签名的示例，涵盖了SM2内部接口和EVP接口的调用。

**Comment by LiTianjue** [comment]
建议：
1. 项目目前似乎没有.gitignore文件，个人感觉.gitignore在开发过程中比较重要，我从openssl项目中拷贝了.gitignore过来稍作改动可以参考一下

2. 基于第一点，发现在最新一次更新中居然有109个文件的改动，其中大部分是.save文件，如果是必要的，最好单独提交一次commit,如果不是，.gitignore 中加入Makefile.sava或者*.save能避免不必要的更新

3. 提议更新再频繁一点，比如一个功能做一次更新，一次更新夹杂太多的文件，容易淹没了真正需要关注的更改(比如最新一次更新)，不利于其他开发者理解项目的进展情况，比如通过阅读代码我发现对于国密SSL的支持，本项目已经做了相当的改造，但是从commit 信息找到相关的信息就比较困难，可以将commit 细化，分类 （当然可能会增加工作量，我也只是建议）

最后，对于SM2加解密失败的问题，示例文件 sm2test.c 单独拿出来编译，也是解密会失败的，显然没有做过良好的测试，我做了简单的修改后可以正常用于测试了
提交了pull request 望采纳
https://github.com/guanzhi/GmSSL/pull/35

**Comment by guanzhi** [comment]
非常感谢您的建议！
1. .gitgnore我们后续我们会加上去
2. 更新频率由目前开发方式导致暂时无法加快，并且由于暑期的影响近期频率会降低，不过我们正在准备社区化，期望在有更多贡献者加入后会形成对开发者比较友好的更新方式
3. 处于和上面相同的原因，没有提前通知我们的pull request难以直接合并，不过我们会在理解完代码之后将您的代码并入，并通过主页和AUTHORS文件等方式注明您的贡献。

**Comment by LiTianjue** [comment]
老师，目前我在做国密SSL的改造，想问几个关于密钥交换算法的问题
1.openssl中目前的密钥交换算法SSL_kECDHe 和 SSL_kEECH 算法有什么区别
2.GmSSL新定义的SSL_kECC算法又是怎么回事
3.GM/T 0024文档中描述的ECDHE 和ECC 密钥交换和以上的算法的对应关系是什么

**Comment by guanzhi** [comment]
SSL_kECC预计实现国密SSL的ECC-SM3-SM4套件，SSL_kECDHe和SSL_kEECH分别对应ECDHE-XXX、ECDH-XXX等SSL标准套件。

**Comment by LiTianjue** [comment]
我是想问,国密套件中的ECDHE算法，比如（ECDHE_SM4_SM3），ECDHE对应的是SSL_kECDHe吗，如果是SSL_kECDHe的话，那按照openssl的实现
等于国密套件中的ECDHE,ECC和RSA密钥交换都没有ServerKeyExchange消息，但是GM/T 0024又描述了这几种消息(6.4.4.3)，我觉得比较迷惑,还望解答一下

**Comment by guanzhi** [comment]
GM标准中的ECDHE对应双证书SM2密钥交换，ECC对应SM2公钥加密，这在SSL协议中没有对应的算法，因此不是SSL_kECDHe，需要定义新的SSL_kXXXXX。

**Comment by LiTianjue** [comment]
就是说
1、ECC_SM4_SM3 对应的是SM2公钥加密，这在SSL协议中没有，需要自己定义实现
2、ECDHE_SM4_SM3 对应的【双证书SM2密钥交换】,不是SSL_kECDHe,也不是SSL_kEECDH,同样需要自己定义并实现？那这个【双证书SM2密钥交换】应该怎么理解？我应该查哪个相关的资料

SM2公钥加密密钥交换可以拿RSA密钥交换来作为参考，容易理解，
但是这个双证书是个什么概念呢，有什么可参考的呢

**Comment by LiTianjue** [comment]
我这么理解：
服务器取服务器证书中的公钥，通过ServerKeyExchange发送
客户端取客户端证书中的公钥，通过ClientKeyExchange发送
通过SM2密钥交换算法，协商出预主密钥，实现密钥交换

全程完全使用证书中的公钥来做密钥交换，不会生成临时密钥对？（SSL_kECDHe,SSL_kEECDH都生成了临时密钥对）

是应该这样实现吗

**Comment by LiTianjue** [comment]
关老师，我学习openssl时间不长，问题有点缺乏逻辑，还望包含

1.服务器都各有2对证书密钥（加密证书，签名证书）,叫做双证书？
    ECDHE算法，服务器，客户端都有两对SM2证书密钥

2.在密钥交换和消息认证中，无论是RSA，ECC，ECDHE都区分加密证书和签名证书，都需要双证书，不只是ECDHE_XXX套件需要双证书？

我开发过程中完全漏了双证书，  那等于在国密ssl的实现中，双证书才是重点，国密算法GmSSL项目都完全支持好了，快吐血了

**Comment by sinv** [comment]
服务器都各有2对证书密钥（加密证书，签名证书）,这应该叫做单证书，单证书是指证书中的密钥仅支持加密或签名操作中的一种，我的理解。

在 2016年7月25日，18:59，XiaoTian <notifications@github.com<mailto:notifications@github.com>> 写道：

服务器都各有2对证书密钥（加密证书，签名证书）,叫做双证书

**Comment by LiTianjue** [comment]
老师，我还想最后确认两个问题
1 无论是 RSA_XXX,ECC_XXX,ECDHE_XXX,在国密标准里服务器都需要使用双证书？
2 【双证书SM2密钥交换】，客户端需要有双证书吗，客户端的交换密钥是来自客户端的加密证书还是使用临时密钥？

**Comment by LiTianjue** [comment]
老师

1. 关于【国密SM2双证书的密钥交换】，我使用了服务器的加密密钥和客户端的临时密钥的方式实现（可以成功建立连接），这样做是合理的吗，还是客户端和服务器都必须要使用双证书

2. 国密套件中的ECC_XXX 和 RSA_XXX套件实现也是要使用双证书吗（目前单证书已经实现了）

我要在下周结束SSL开发，还望老师帮忙确认一下这两个问题

**Comment by guanzhi** [comment]
http://www.cacrnet.org.cn/upload/fckeditor/File/2014/罗俊ssl%20vpn技术规范宣贯最终版0725挂网.pdf
其中有对12个密码套件使用的密钥和证书的说明，这个应该是比较权威的解释了。

**Comment by LiTianjue** [comment]
太感谢了，正是我需要的信息！！！！

**Comment by conezxy** [comment]
正式产品开发的话，建议去新华书店买一份纸质的规范，京东上应该也有。

网上的电子版不保证与实际发布的纸质版完全一致。

-
掌晓愚

在 2016年8月2日，17:27，xiyayadamaozai <notifications@github.com<mailto:notifications@github.com>> 写道：


太感谢了，正是我需要的信息！！！！

―

**Comment by tongyu123** [comment]
你好,老师,现在GmSSL编译的能编译支持arm64的么?你们给的编译后只支持x86_64的.

**Comment by LiTianjue** [comment]
支持的，我测试过的，arm-linux 下编译运行都没问题

**Comment by tongyu123** [comment]
我是想把GmSSL编译成静态库用于iOS开发,是在mac环境下编译的.发现不支持arm64的.

**Comment by guanzhi** [comment]
iOS模拟器和arm32支持吗？

**Comment by tongyu123** [comment]
你好，在mac环境下编译的我发现只支持x86_64，也就是说只支持iOS模拟器，对于iOS开发真机arm64是不支持的。


发自 网易邮箱大师
在2016年08月13日 05:32，Zhi Guan 写道:

iOS模拟器和arm32支持吗？

**Comment by guanzhi** [comment]
你可以把编译错误信息帖上来看看

**Comment by guanzhi** [comment]
另外请新开一个issue

**Comment by tongyu123** [comment]
你好,这是iOS开发真机报错:
ld: warning: ld: warning: ignoring file /Users/a123456/Desktop/SM2  SM4/libcrypto.a, file was built for archive which is not the architecture being linked (arm64): /Users/a123456/Desktop/SM2  SM4/libcrypto.aignoring file /Users/a123456/Desktop/SM2  SM4/libssl.a, file was built for archive which is not the architecture being linked (arm64): /Users/a123456/Desktop/SM2  SM4/libssl.a

ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(CharacterKeyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardThird.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(KeyboardTool.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(Keyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(XYKeyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardFirst.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardSecond.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(UIView+LVExtension.o)) was built for newer iOS version (9.0) than being linked (7.0)
Undefined symbols for architecture arm64:
  "_EVP_sm3", referenced from:
      _test_sm2_enc in sm2Plugin.o
  "_EC_POINT_point2hex", referenced from:
      _test_sm2_enc in sm2Plugin.o
  "_EC_KEY_new", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_EC_POINT_point2oct", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_KDF_get_x9_63", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_CRYPTO_malloc", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_GROUP_get_order", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestInit_ex", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_CTX_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      -[sm2Plugin sm2:] in sm2Plugin.o
      _test_sm2_enc in sm2Plugin.o
  "_EVP_MD_CTX_create", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_get0_group", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      -[sm2Plugin sm2:] in sm2Plugin.o
      _test_sm2_enc in sm2Plugin.o
  "_EC_GROUP_get_cofactor", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_get0_public_key", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_GROUP_get_degree", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_hex2point", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_BN_rand_range", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_OpenSSLDie", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      _test_sm2_enc in sm2Plugin.o
  "_BN_free", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestUpdate", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestFinal_ex", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_mul", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_free", referenced from:
      _SM2_CIPHERTEXT_VALUE_free in sm2_enc.o
  "_BN_CTX_free", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_num_bits", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_is_at_infinity", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_MD_CTX_destroy", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_new_by_curve_name", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_CRYPTO_free", referenced from:
      _SM2_CIPHERTEXT_VALUE_free in sm2_enc.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
