### ISSUE TITLE
windows master版本VS 2015 编译错误

### ISSUE THREAD

**Issue by memdumper** [guanzhi/GmSSL#330]
perl Configure VC-WIN32以后,执行nmake，报错
crypto\base58\base58.c(81): error C2057: 应输入常量表达式
crypto\base58\base58.c(81): error C2466: 不能分配常量大小为 0 的数组
crypto\base58\base58.c(81): error C2133: “outi”: 未知的大小
crypto\base58\base58.c(163): error C2065: “ssize_t”: 未声明的标识符
crypto\base58\base58.c(163): error C2146: 语法错误: 缺少“;”(在标识符“i”的前
面)
crypto\base58\base58.c(163): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(163): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(163): error C2065: “high”: 未声明的标识符
crypto\base58\base58.c(163): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(166): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(166): warning C4018: “<”: 有符号/无符号不匹配
crypto\base58\base58.c(167): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(169): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(170): error C2057: 应输入常量表达式
crypto\base58\base58.c(170): error C2466: 不能分配常量大小为 0 的数组
crypto\base58\base58.c(170): error C2133: “buf”: 未知的大小
crypto\base58\base58.c(173): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(173): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(173): error C2065: “high”: 未声明的标识符
crypto\base58\base58.c(173): warning C4018: “<”: 有符号/无符号不匹配
crypto\base58\base58.c(173): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(175): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(175): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(175): error C2065: “high”: 未声明的标识符
crypto\base58\base58.c(177): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(178): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(183): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(183): warning C4018: “<”: 有符号/无符号不匹配
crypto\base58\base58.c(185): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(185): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(187): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(187): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(191): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(192): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(193): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(193): error C2065: “zcount”: 未声明的标识符
crypto\base58\base58.c(193): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(193): warning C4018: “<”: 有符号/无符号不匹配
crypto\base58\base58.c(194): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(194): error C2065: “j”: 未声明的标识符
crypto\base58\base58.c(195): error C2065: “i”: 未声明的标识符
crypto\base58\base58.c(196): error C2065: “i”: 未声明的标识符

**Comment by 1132719438** [comment]
vs变量定义必须放在所有执行语句前，块开始处
不支持用变量定义数组大小

**Comment by memdumper** [comment]
GmSSL-GmSSL-v1版本，在vs2015下编译成功，加了个 no-asm参数
perl Configure VC-WIN32 no-asm
ms\do_ms
nmake -f ms\nt.bak
其中test\igetest.c内容要从dummytest.c复制过来。

**Comment by memdumper** [comment]
参考了1132719438的方法,编译成功，过程如下
1. 注解 speck.h里的speck_expand16,speck_expand32,speck_expand64，如下:
void speck_set_encrypt_key16(SPECK_TYPE16 const user[SPECK_KEY_LEN16], SPECK_TYPE16 key[SPECK_ROUNDS16]);
	void speck_set_decrypt_key16(SPECK_TYPE16 const user[SPECK_KEY_LEN16], SPECK_TYPE16 key[SPECK_ROUNDS16]);
	/* void speck_expand16(SPECK_TYPE16 const K[SPECK_KEY_LEN16], SPECK_TYPE16 S[SPECK_ROUNDS16]);*/
	void speck_encrypt16(SPECK_TYPE16 const pt[2], SPECK_TYPE16 ct[2], SPECK_TYPE16 const K[SPECK_ROUNDS16]);
	void speck_decrypt16(SPECK_TYPE16 const ct[2], SPECK_TYPE16 pt[2], SPECK_TYPE16 const K[SPECK_ROUNDS16]);

	void speck_set_encrypt_key32(SPECK_TYPE32 const user[SPECK_KEY_LEN32], SPECK_TYPE32 key[SPECK_ROUNDS32]);
	void speck_set_decrypt_key32(SPECK_TYPE32 const user[SPECK_KEY_LEN32], SPECK_TYPE32 key[SPECK_ROUNDS32]);
	/*void speck_expand32(SPECK_TYPE32 const K[SPECK_KEY_LEN32], SPECK_TYPE32 S[SPECK_ROUNDS32]);*/
	void speck_encrypt32(SPECK_TYPE32 const pt[2], SPECK_TYPE32 ct[2], SPECK_TYPE32 const K[SPECK_ROUNDS32]);
	void speck_decrypt32(SPECK_TYPE32 const ct[2], SPECK_TYPE32 pt[2], SPECK_TYPE32 const K[SPECK_ROUNDS32]);
2. 复制GmSSL-GmSSL-v1版本ms目录下的文件到master版本下的ms目录，同名的不要覆盖
3. 在vs 2015开发人员命令提示符下执行
   perl Configure VC-WIN32 no-asm no-base58
   perl util/mkdef.pl crypto update
   nmake

	void speck_set_encrypt_key64(SPECK_TYPE64 const user[SPECK_KEY_LEN64], SPECK_TYPE64 key[SPECK_ROUNDS64]);
	void speck_set_decrypt_key64(SPECK_TYPE64 const user[SPECK_KEY_LEN64], SPECK_TYPE64 key[SPECK_ROUNDS64]);
	/*void speck_expand64(SPECK_TYPE64 const K[SPECK_KEY_LEN64], SPECK_TYPE64 S[SPECK_ROUNDS64]);*/
	void speck_encrypt64(SPECK_TYPE64 const pt[2], SPECK_TYPE64 ct[2], SPECK_TYPE64 const K[SPECK_ROUNDS64]);
	void speck_decrypt64(SPECK_TYPE64 const ct[2], SPECK_TYPE64 pt[2], SPECK_TYPE64 const K[SPECK_ROUNDS64]);
