### ISSUE TITLE
生成证书报错

### ISSUE THREAD

**Issue by kssssssssss** [guanzhi/GmSSL#331]
在 Mac OS （macOS Sierra 10.12）中
参考文档使用以下命令
$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 \
                -pkeyopt ec_param_enc:named_curve -out ca.key
$ gmssl req -sm3 -new -x509 -days 365 -key ca.key -out ca.crt

生成SM3证书请求都时候，抛出下列错误：

140737252012992:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:

**Comment by memdumper** [comment]
请参考 https://github.com/guanzhi/GmSSL/issues/212
