### ISSUE TITLE
不支持WAPI的椭圆算法和OID

### ISSUE THREAD

**Issue by brookk** [guanzhi/GmSSL#335]
不支持WAPI 使用的签名算法OID：1.2.156.11235.1.1.1，椭圆参数OID：1.2.156.11235.1.1.2.1

**Comment by guanzhi** [comment]
有的，曲线wapip192v1

**Comment by guanzhi** [comment]
签名算法OID：1.2.156.11235.1.1.1，椭圆参数OID：1.2.156.11235.1.1.2.1 所属的标准是什么？

**Comment by brookk** [comment]
这两个OID所属的标准是 GB 15629.11-2003/XG1-2006, 其中 8.1.3.1 章 （X509 V3证书）

**Comment by guanzhi** [comment]
WAPI曲线的OID已经修改
