### ISSUE TITLE
V2.0版本生成国密证书失败是什么原因

### ISSUE THREAD

**Issue by WeWebsterchen** [guanzhi/GmSSL#337]
GmSSL 2.0 - OpenSSL 1.1.0d  26 Jan 2017版本求原因？
gmssl req -sm3 -new -x509 -days 365 -key ca.key -out ca.crt

140455543420672:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:

**Comment by panhb** [comment]
https://github.com/guanzhi/GmSSL/issues/212
