### ISSUE TITLE
哪位大神帮我看看我这个Z值正确吗？

### ISSUE THREAD

**Issue by mysummergit** [guanzhi/GmSSL#338]
我用的gmssl中的sm2_get_public_key_data获得的pkdata = a || b || G.x || G.y || P.x || P.y这个字符串，但是对360的国密证书验签过不了，下面这个是我计算hash之前的字符串，自己加上了默认的id和id长度
00 80 31 32 33 34 35 36 37 38 31 32 33 34 35 36 37 38 ff ff ff fe ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 00 ff ff ff ff ff ff ff fc 28 e9 fa 9e 9d 9f 5e 34 4d 5a 9e 4b cf 65 09 a7 f3 97 89 f5 15 ab 8f 92 dd bc bd 41 4d 94 0e 93 32 c4 ae 2c 1f 19 81 19 5f 99 04 46 6a 39 c9 94 8f e3 0b bf f2 66 0b e1 71 5a 45 89 33 4c 74 c7 bc 37 36 a2 f4 f6 77 9c 59 bd ce e3 6b 69 21 53 d0 a9 87 7c c6 2a 47 40 02 df 32 e5 21 39 f0 a0 36 f0 31 47 02 a9 9c 93 62 c5 d8 0f 5c 6a 03 83 91 95 6c ee 43 da 3e 88 a6 54 39 31 3e df f4 e5 c9 c9 e9 62 53 6c bc c5 1e f3 5d 79 64 60 55 c0 d7 84 42 a9 3c 02 29 25 d8 d0 84 96 28 d8 a5 07 
比较ca证书，最后64字节公钥没有问题的，我这个a，b这些变量这些获得对了的吗？

**Comment by 1132719438** [comment]
把证书贴上来

**Comment by mysummergit** [comment]
这本是CA
-----BEGIN CERTIFICATE-----
MIIBqjCCAVACCQCSqHkKANv2jjAKBggqgRzPVQGDdTBdMQswCQYDVQQGEwJDTjEQ
MA4GA1UECgwHMzYwLmNvbTEMMAoGA1UECwwDU1NMMQ8wDQYDVQQDDAZzbTItY2Ex
HTAbBgkqhkiG9w0BCQEWDnNtMi1jYUAzNjAuY29tMB4XDTE1MTAyMjA2MzIzOFoX
DTE4MDcxNzA2MzIzOFowXTELMAkGA1UEBhMCQ04xEDAOBgNVBAoMBzM2MC5jb20x
DDAKBgNVBAsMA1NTTDEPMA0GA1UEAwwGc20yLWNhMR0wGwYJKoZIhvcNAQkBFg5z
bTItY2FAMzYwLmNvbTBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABDbwMUcCqZyT
YsXYD1xqA4ORlWzuQ9o+iKZUOTE+3/TlycnpYlNsvMUe8115ZGBVwNeEQqk8Aikl
2NCElijYpQcwCgYIKoEcz1UBg3UDSAAwRQIgSMX/6H+SQyTrw/NRAbTgeO6MjBj7
RzxC79/RgdXdTS0CIQCrCZh6l/QG97SBJKiRNylaGz3/a6YmLZQWZg4q2JStIQ==
-----END CERTIFICATE-----

**Comment by mysummergit** [comment]
这本是要验证的
-----BEGIN CERTIFICATE-----
MIIBrzCCAVQCCQD8GBY2kjQ20zAKBggqgRzPVQGDdTBdMQswCQYDVQQGEwJDTjEQ
MA4GA1UECgwHMzYwLmNvbTEMMAoGA1UECwwDU1NMMQ8wDQYDVQQDDAZzbTItY2Ex
HTAbBgkqhkiG9w0BCQEWDnNtMi1jYUAzNjAuY29tMB4XDTE1MTAyMjA2MzI0MVoX
DTE4MDcxNzA2MzI0MVowYTELMAkGA1UEBhMCQ04xEDAOBgNVBAoMBzM2MC5jb20x
DDAKBgNVBAsMA1NTTDERMA8GA1UEAwwIc20yLXNpdGUxHzAdBgkqhkiG9w0BCQEW
EHNtMi1zaXRlQDM2MC5jb20wWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAASp+eC0
QuI+60HzjYShNsCH1VPTYLyK1jF1PdEIgL63KPc+rFukIeA2eEUjmYfYUidTJH1h
loiz5JrfghEH1f5bMAoGCCqBHM9VAYN1A0kAMEYCIQCfrPyTK3ZWTQ3QQmY6VJIl
ytBTYR5+MePxT6mvqxM3sgIhANP354sbzB5oBM4LO+fXjc9H1+Ln9WcGyvq29Bd7
9c1U
-----END CERTIFICATE-----

**Comment by mysummergit** [comment]
@1132719438 
我就是按照我上面说的，自己在M前面加的Z值，我计算出来的Z值就是我前面贴出来的数据，大神帮我看下你那儿验得过不呢，是我Z值问题还是什么问题呢？谢了

**Comment by mysummergit** [comment]
我用了这个SM2_get0_id(EC_KEY *ec_key)函数，没有获得到id，于是直接设置默认id（31 32 33 34 35 36 37 38 31 32 33 34 35 36 37 38）

**Comment by 1132719438** [comment]
把计算好的ZA值也贴上来，我对比一下

**Comment by 1132719438** [comment]
这是我的sm2_get_public_key_data获取的pkdata
`fffffffeffffffffffffffffffffffffffffffff0000fffffffffffffffc28e9fa9e9d9f5e344d5a9e4bcf659a7f39789f515ab8f92ddbcbd414d94e9332c4ae2c1f1981195f994466a39c9948fe3bbff266be1715a4589334c74c7bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a47402df32e52139f0a036f031472a99c9362c5d8f5c6a38391956cee43da3e88a65439313edff4e5c9c9e962536cbcc51ef35d79646055c0d78442a93c22925d8d0849628d8a57`

**Comment by mysummergit** [comment]
@1132719438 
这是Z值
00 80 31 32 33 34 35 36 37 38 31 32 33 34 35 36 37 38 ff ff ff fe ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 00 ff ff ff ff ff ff ff fc 28 e9 fa 9e 9d 9f 5e 34 4d 5a 9e 4b cf 65 09 a7 f3 97 89 f5 15 ab 8f 92 dd bc bd 41 4d 94 0e 93 32 c4 ae 2c 1f 19 81 19 5f 99 04 46 6a 39 c9 94 8f e3 0b bf f2 66 0b e1 71 5a 45 89 33 4c 74 c7 bc 37 36 a2 f4 f6 77 9c 59 bd ce e3 6b 69 21 53 d0 a9 87 7c c6 2a 47 40 02 df 32 e5 21 39 f0 a0 36 f0 31 47 02 a9 9c 93 62 c5 d8 0f 5c 6a 03 83 91 95 6c ee 43 da 3e 88 a6 54 39 31 3e df f4 e5 c9 c9 e9 62 53 6c bc c5 1e f3 5d 79 64 60 55 c0 d7 84 42 a9 3c 02 29 25 d8 d0 84 96 28 d8 a5 07 

这是我的H值
00 80 31 32 33 34 35 36 37 38 31 32 33 34 35 36 37 38 ff ff ff fe ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 00 ff ff ff ff ff ff ff fc 28 e9 fa 9e 9d 9f 5e 34 4d 5a 9e 4b cf 65 09 a7 f3 97 89 f5 15 ab 8f 92 dd bc bd 41 4d 94 0e 93 32 c4 ae 2c 1f 19 81 19 5f 99 04 46 6a 39 c9 94 8f e3 0b bf f2 66 0b e1 71 5a 45 89 33 4c 74 c7 bc 37 36 a2 f4 f6 77 9c 59 bd ce e3 6b 69 21 53 d0 a9 87 7c c6 2a 47 40 02 df 32 e5 21 39 f0 a0 36 f0 31 47 02 a9 9c 93 62 c5 d8 0f 5c 6a 03 83 91 95 6c ee 43 da 3e 88 a6 54 39 31 3e df f4 e5 c9 c9 e9 62 53 6c bc c5 1e f3 5d 79 64 60 55 c0 d7 84 42 a9 3c 02 29 25 d8 d0 84 96 28 d8 a5 07 30 82 01 54 02 09 00 fc 18 16 36 92 34 36 d3 30 0a 06 08 2a 81 1c cf 55 01 83 75 30 5d 31 0b 30 09 06 03 55 04 06 13 02 43 4e 31 10 30 0e 06 03 55 04 0a 0c 07 33 36 30 2e 63 6f 6d 31 0c 30 0a 06 03 55 04 0b 0c 03 53 53 4c 31 0f 30 0d 06 03 55 04 03 0c 06 73 6d 32 2d 63 61 31 1d 30 1b 06 09 2a 86 48 86 f7 0d 01 09 01 16 0e 73 6d 32 2d 63 61 40 33 36 30 2e 63 6f 6d 30 1e 17 0d 31 35 31 30 32 32 30 36 33 32 34 31 5a 17 0d 31 38 30 37 31 37 30 36 33 32 34 31 5a 30 61 31 0b 30 09 06 03 55 04 06 13 02 43 4e 31 10 30 0e 06 03 55 04 0a 0c 07 33 36 30 2e 63 6f 6d 31 0c 30 0a 06 03 55 04 0b 0c 03 53 53 4c 31 11 30 0f 06 03 55 04 03 0c 08 73 6d 32 2d 73 69 74 65 31 1f 30 1d 06 09 2a 86 48 86 f7 0d 01 09 01 16 10 73 6d 32 2d 73 69 74 65 40 33 36 30 2e 63 6f 6d 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 81 1c cf 55 01 82 2d 03 42 00 04 a9 f9 e0 b4 42 e2 3e eb 41 f3 8d 84 a1 36 c0 87 d5 53 d3 60 bc 8a d6 31 75 3d d1 08 80 be b7 28 f7 3e ac 5b a4 21 e0 36 78 45 23 99 87 d8 52 27 53 24 7d 61 96 88 b3 e4 9a df 82 11 07 d5 fe 5b 

这个对H(Z||M)的sm3
96 4f 0b b9 3a 30 21 1f b8 26 b6 30 8a 01 b7 8f 6c 44 cc 88 5e 23 9f 3d 3f 03 26 c4 3d 1e 98 46

**Comment by mysummergit** [comment]
@1132719438 
我对比了一下我们的pkdata应该是一样的

**Comment by mysummergit** [comment]
@1132719438 
可以帮我看下我们的H值和对H的sm3一样吗？
然后做验签的时候使用的CA公钥我打印出来是对比是没有问题的，
证书签名是
30 46 02 21 00 9f ac fc 93 2b 76 56 4d 0d d0 42 66 3a 54 92 25 ca d0 53 61 1e 7e 31 e3 f1 4f a9 af ab 13 37 b2 02 21 00 d3 f7 e7 8b 1b cc 1e 68 04 ce 0b 3b e7 d7 8d cf 47 d7 e2 e7 f5 67 06 ca fa b6 f4 17 7b f5 cd 54

**Comment by 1132719438** [comment]
sorry 刚才的pkdata贴错了，这个是我的pkdata，应该是一样的
`fffffffeffffffffffffffffffffffffffffffff00000000fffffffffffffffc28e9fa9e9d9f5e344d5a9e4bcf6509a7f39789f515ab8f92ddbcbd414d940e9332c4ae2c1f1981195f9904466a39c9948fe30bbff2660be1715a4589334c74c7bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a474002df32e52139f0a036f0314702a99c9362c5d80f5c6a038391956cee43da3e88a65439313edff4e5c9c9e962536cbcc51ef35d79646055c0d78442a93c022925d8d0849628d8a507`

**Comment by mysummergit** [comment]
我对cfca的证书也验证通过不了，现在就不知道是ID的原因还是做H=(Z||M)这步时H有误，还是我的sm3计算值有误

**Comment by 1132719438** [comment]
你的计算过程不对
应该是先获取Z值（pkdata）
在计算ZA值：ZA=SM3(Z)
计算M’=ZA||M
计算e=SM3(M')

**Comment by mysummergit** [comment]
噢噢，我现在是直接SM3(Z||M)的，我改下代码试试

**Comment by mysummergit** [comment]
@1132719438 
按照你说的过程改后验签通过了，刚刚重新看了下国密规范，发现自己是根据上回做SM2密钥协商里面写的H=SM3（Z || M）来做了，拿错规范了，谢谢大神

**Comment by mysummergit** [comment]
谢谢大神，搞定了

**Comment by 1132719438** [comment]
我也不是大神，一起交流

**Comment by mysummergit** [comment]
@1132719438 
你是做ssl vpn吗，我是近几个月一直在做国密的ssl vpn
