### ISSUE TITLE
SKF使用问题

### ISSUE THREAD

**Issue by huchuanwen** [guanzhi/GmSSL#34]
作者您好，
       我在GitHub上下载master版本的gmssl，安装在centos7上，需要用到SKF，但是我在用ENGINE加载的时候发现ENGINE_load_skf接口不可见，看了源码后发现是有宏OPENSSL_NO_DYNAMIC_ENGINE控制，重新编译后问题来了。
       问题：编译正常通过，但是编译test程序报SKF_nid_to_encparam、bind_helper接口未定义，我查找源码发现这个接口确实是没有定义，求大神给予解答，指点SKF的使用方法。

**Comment by huchuanwen** [comment]
附注：我的GMSSL编译过程
第一遍编译：
./config && make && make install
第二遍编译：
make clean && ./config shared && make && make install
第三遍编译：
修改Makefile，CFLAGS 增加 -DOPENSSL_NO_DYNAMIC_ENGINE
make clean && make && make install

编译完成后我尝试用libcrypto,a链接test程序，但是报缺少很多定义，这里是需要链接相应的动态是吗，libcrypto,a中没有把所有.so链接进去吗

**Comment by LiTianjue** [comment]
静态链接加上-ldl

**Comment by huchuanwen** [comment]
非常感谢，加-ldl解决了静态库的问题。
请教一下，使用./config shared编译出动态库后，ENGINE_load_skf接口并未编译，有宏控制，请问如何使用ENGINE来应用SKF

**Comment by guanzhi** [comment]
SKF ENGINE的目的是通过SKF接口来调用国密硬件。目前主要代码已经开发完成了，但是还没有调试和测试，特别是没有和一个真正的密码硬件设备对接测试过。

代码中的SKF_nid_to_encparam是SKF_nid_to_encparams的笔误。

**Comment by guanzhi** [comment]
SKF ENGINE下一步考虑接入某款支持SKF接口的国密硬件，来进一步开发调试，请问 @huchuanwen @LiTianjue 对硬件的需求是什么，PCI加密卡还是U盾？是否已经考虑了某个厂商的某个具体产品型号？

**Comment by huchuanwen** [comment]
原来如此，我在编译和测试的过程中发现不少问题。目前我们准备使用
PCI-E加密卡和USB-KEY，使用某厂商的skf.so库进行开发。engines/skf和
crypto/skf有什么区别，另外为什么编译.so(config shared)的时候，OpenSSL要关
闭ENGINE_load_skf，它只能使用ENGINE_dynamic_load？



发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Mention 
<mention@noreply.github.com>
日期:   2016/07/18 08:56
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



SKF ENGINE下一步考虑接入某款支持SKF接口的国密硬件，来进一步开发调试，请问 
@huchuanwen @LiTianjue 对硬件的需求是什么，PCI加密卡还是U盾？是否已经考虑
了某个厂商的某个具体产品型号？
―

**Comment by guanzhi** [comment]
engine/skf用于调用硬件，crypto/skf为应用提供SKF接口。
现在SKF ENGINE还没有做完，但是由于功能代码基本已经完整了，如果有厂商支持的话可以在其基础上做少量修改完善来支持硬件。另外由于SKF标准中可能对一些具体参数未做明确规定，可能需要根据厂商的具体实现来调整SKF的相应代码。

**Comment by huchuanwen** [comment]
非常感谢，SKF ENGINE大概会在什么时间发布出来，我还是很希望能使用你
们的工程，不然我就要自己研究openssl T__T



发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Mention 
<mention@noreply.github.com>
日期:   2016/07/19 06:11
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



engine/skf用于调用硬件，crypto/skf为应用提供SKF接口。
现在SKF ENGINE还没有做完，但是由于功能代码基本已经完整了，如果有厂商支持的
话可以在其基础上做少量修改完善来支持硬件。另外由于SKF标准中可能对一些具体
参数未做明确规定，可能需要根据厂商的具体实现来调整SKF的相应代码。
―

**Comment by huchuanwen** [comment]
大神，你好
        我按照您说的方式调用skf，使用crypto/skf下的接口，并采用ENGINE方式
尝试调用engine/skf下的接口。但是程序进入无限循环调用的BUG中core dump了 
T_T..,大神 你要救救我啊！！！

        环境是这样的：gmssl编译的静态库，使用crypto/skf下的skftest.c文件进
行测试。在skf_enc.c文件的接口SKF_EncryptInit中加载了ENGINE_load_skf,加载代
码如下：
                        ENGINE *e = ENGINE_by_id("SKF");
                       if(!e)
191                     {
192                             ENGINE_load_skf();
193                             e =  ENGINE_by_id("SKF");
194             }
195                     if (!EVP_EncryptInit_ex(ctx, cipher, e, key, iv)) 
{
        调试发现，程序确实运行到了e_skf.c中的skf_cipher接口处，但是
skf_cipher里调用的SKF_EncryptInit和SKF_EncryptUpdate等skf接口还是
crypto/skf下的接口，程序就此陷入了无限循环T_T
        对了，skftest.c的编译命令：gcc -g -o test_skf skftest.c 
-I../../include -L ../.. -lcrypto -ldl -L . -lskf其中skf是我编译
skf_dummy.c生成的库，我希望ENGINE能调用这里面的接口，大神，告诉我是不是我
的使用方式有问题！！！
        我尝试修改skf_cipher中调用的接口名和skf_dummy.c中的接口名，使其保
持一致，如SKF_EncryptInit1，但是这连编译都无法通过，链接时，它好像都不到
skf库中查找。


发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Mention 
<mention@noreply.github.com>
日期:   2016/07/19 06:11
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



engine/skf用于调用硬件，crypto/skf为应用提供SKF接口。
现在SKF ENGINE还没有做完，但是由于功能代码基本已经完整了，如果有厂商支持的
话可以在其基础上做少量修改完善来支持硬件。另外由于SKF标准中可能对一些具体
参数未做明确规定，可能需要根据厂商的具体实现来调整SKF的相应代码。
―

**Comment by guanzhi** [comment]
因为我们没有支持SKF的硬件，无法给出时间表。
如果你不需要硬件，那么应该使用EVP API，这个相对比较稳定可靠。
如果使用某个厂商的硬件，则应优先使用厂商的API。

**Comment by huchuanwen** [comment]
您好，
        经过测试，GMSSL-SKF的ENGINE方式是可用的。我们采用硬件厂商提供给我
们的库，使用ENGINE接口实现SM4和SM1的加解密，在使用过程中发现几个问题，关于
e_skf.c中skf_cipher接口的，希望能给予解答：
        1、skf_cipher是用于调用加解密函数的，但是它并没有给出输出缓冲区中
数据的实际长度？从实现上看，输出数据长度一般回等于输入缓冲区的数据长度，但
这不是绝对的，因此是否考虑把输出缓冲区的实际长度返回给调用者。。
        2、在处理剩余数据block(len - ulDataLen)时，为何没有对解密进行处理
，而是直接返回0？
        3、调用SKF_EncryptUpdate后是需要调用SKF_EncryptFinal来结束加解密的
缓冲区，这里没有调用是否有其他方面的考虑？


以上，新人观点，希望能给予解答~~



发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Mention 
<mention@noreply.github.com>
日期:   2016/07/20 04:01
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



因为我们没有支持SKF的硬件，无法给出时间表。
如果你不需要硬件，那么应该使用EVP API，这个相对比较稳定可靠。
如果使用某个厂商的硬件，则应优先使用厂商的API。
―

**Comment by guanzhi** [comment]
我们没有来自硬件厂商的SKF实现，这部分还没有测试正确性。
没有调用SKF_EncryptFinal应该是不对是。

**Comment by huchuanwen** [comment]
您好，
        咨询你个问题，GMSSL中objects.txt的部分内容如下：
                sm-scheme 104 4         : SMS4-CFB              : sms4-cfb
                sm-scheme 104 5         : SMS4-CFB1             : 
sms4-cfb1 
                sm-scheme 104 6         : SMS4-CFB8             : 
sms4-cfb8
                sm-scheme 104 7         : SMS4-CTR              : sms4-ctr 

                sm-scheme 104 8         : SMS4-GCM              : sms4-gcm 

                sm-scheme 104 9         : SMS4-CCM              : sms4-ccm 

                sm-scheme 104 10        : SMS4-XTS              : sms4-xts 

                sm-scheme 104 11        : SMS4-WRAP             : 
sms4-wrap
        这上面的OID是否是国密标准吗，与AES、DES不一致。还有CTR与CCM有什么
区别？
谢谢！



发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Author 
<author@noreply.github.com>
日期:   2016/07/16 19:24
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



SKF ENGINE的目的是通过SKF接口来调用国密硬件。目前主要代码已经开发完成了，
但是还没有调试和测试，特别是没有和一个真正的密码硬件设备对接测试过。
代码中的SKF_nid_to_encparam是SKF_nid_to_encparams的笔误。
―

**Comment by guanzhi** [comment]
国密标准(GM/T 0006-2012)中的OID只定义到SM4算法这一级，即GmSSL中的 sm-scheme 104，（据我所知）标准中对于分组密码和工作模式的组合没有定义。GmSSL给出了这些OID的定义，这部分不在国密标准中，属于GmSSL对国密标准的扩展。
CTR是一种加密模式。GCM、CCM是认证加密模式，可替代CBC+HMAC。

**Comment by huchuanwen** [comment]
谢谢你的答复，对我非常有用！



发件人:         Zhi Guan <notifications@github.com>
收件人:         guanzhi/GmSSL <GmSSL@noreply.github.com>, 
抄送:   huchuanwen <huchuanwen@kedacom.com>, Mention 
<mention@noreply.github.com>
日期:   2016/10/11 23:49
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



国密标准(GM/T 0006-2012)中的OID只定义到SM4算法这一级，即GmSSL中的 
sm-scheme 104，（据我所知）标准中对于分组密码和工作模式的组合没有定义。
GmSSL给出了这些OID的定义，这部分不在国密标准中，属于GmSSL对国密标准的扩展
。
CTR是一种加密模式。GCM、CCM是认证加密模式，可替代CBC+HMAC。
―

**Comment by 403705726** [comment]
> GMSSL-SKF的ENGINE方式是可用的

你好，想问下您这边是用的gmssl哪个版本，怎么配置的，我这边config  enable-skfeng 报缺少源文件的错误

**Comment by huchuanwen** [comment]
你是？ 
我并非是gmssl的维护人，也没有使用gmssl，只是借鉴过gmssl。
一般SKF engine是和硬件挂钩的，要自己实现到硬件的映射。



胡传文
KEDACOM 视讯产品线/可信云视频 
上海市徐汇区虹梅路2071号远中产业园1号楼4楼(201103) 
Email: ***@***.*** 



发件人:         403705726 ***@***.***>
收件人:         guanzhi/GmSSL ***@***.***>, 
抄送:   huchuanwen ***@***.***>, Mention 
***@***.***>
日期:   2021/11/15 16:58
主题:   Re: [guanzhi/GmSSL] SKF使用问题 (#34)



GMSSL-SKF的ENGINE方式是可用的
你好，想问下您这边是用的gmssl哪个版本，怎么配置的，我这边config 
enable-skfeng 报缺少源文件的错误
―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
