### ISSUE TITLE
SM2验证签名出现"签名验证失败"

### ISSUE THREAD

**Issue by aqinwenky** [guanzhi/GmSSL#340]
在Ubuntu14.04下安装GmSSL成功，然后实验SM2签名出现“签名验证失败”，请问是什么问题。
下面是我操作的步骤

1、生成签名私钥
gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve  -out signkey.pem
2、对test.file进行签名
gmssl pkeyutl -sign -inkey signkey.pem -pkeyopt ec_sign_algor:sm2 -in test.file -out test_sign.sig
3、从签名私钥得到公钥
gmssl pkey -pubout -in signkey.pem -out vrfykey.pem
4、利用公钥验证签名 
gmssl pkeyutl -verify -pubin -inkey vrfykey.pem -pkeyopt ec_sign_algor:sm2 -in test.file -sigfile test_sign.sig
出现的错误是
Signature Verification Failure。
谢谢各位。

**Comment by ZxpKiki** [comment]
生成SM2密钥并签名

$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 \
                -pkeyopt ec_param_enc:named_curve  -out signkey.pem
$ gmssl pkeyutl -sign -pkeyopt ec_sign_algor:sm2 -inkey signkey.pem \
                -in a.txt -out b.sig
可以将公钥从signkey.pem中导出并发发布给验证签名的一方

$ gmssl pkey -pubout -in signkey.pem -out vrfykey.pem
$ gmssl pkeyutl -verify -pubin  -pkeyopt ec_sign_algor:sm2 -inkey vrfykey.pem \
                -in a.txt -sigfile b.sig

验成功了。
