### ISSUE TITLE
GO API 中如何使用SM2

### ISSUE THREAD

**Issue by mxz-scott** [guanzhi/GmSSL#341]
查看了go的API，SM2 签名/验签，加密，解密等都需要 PublicKey 、PrivateKey，而获取这两个的函数都是直接  return nil, errors.New("Not implemented") ，应该如何实现呢，能否给些参考

**Comment by guanzhi** [comment]
master分支中Go接口已经更新，上述功能都已经提供了。

**Comment by guanzhi** [comment]
由于缺乏人手，测试、文档暂时是不会有了，希望Go接口的用户或者爱好者能够参与Go API子项目，丰富测试和文档。
