### ISSUE TITLE
基于gmssl开发国密SSL VPN

### ISSUE THREAD

**Issue by mysummergit** [guanzhi/GmSSL#343]
大家有没有做过国密SSL VPN的，目前我基于gmssl源码，加入了硬件的国密加解密，然后结合openvpn，虽然现在VPN能国密通信，但是openvpn发出的数据包都有openvpn的报文头，感觉不符合ssl vpn国密规范呢？大家有基于openvpn做过吗？下一步是应该去掉openvpn的报文头以及一些不必要的报文还是不应该基于openvpn做呢

**Comment by LiTianjue** [comment]
"感觉不符合ssl vpn国密规范 " ?   , 我感觉很符合, ^_^

**Comment by mysummergit** [comment]
@LiTianjue 你好，前段时间我联系了省密码局的工作人员，他说vpn送检后会和国家密码局标准ssl vpn对通，我理解的对通是我发出的包他能解析，他发来的包我能解析，但是采用openvpn的话，我的数据包在tcp和ssl层之间还有openvpn的报文头，那边服务器如何解析我这个包呢？还有openvpn在发client hello包之前有一个模仿tcp三次握手的过程，这个过程是否需要去掉呢？这部分内容自己理解不透彻，近来很困惑这个问题，谢谢！

**Comment by syr-1** [comment]
> 大家有没有做过国密SSL VPN的，目前我基于gmssl源码，加入了硬件的国密加解密，然后结合openvpn，虽然现在VPN能国密通信，但是openvpn发出的数据包都有openvpn的报文头，感觉不符合ssl vpn国密规范呢？大家有基于openvpn做过吗？下一步是应该去掉openvpn的报文头以及一些不必要的报文还是不应该基于openvpn做呢

请问在GMSSL源码中加入硬件的国密加解密是基于SKF_接口函数实现的吗？

**Comment by wuyan921** [comment]
您好，我也是基于openvpn来做的，目前也遇到这个握手过程tlcp报文中交叉着openvpn报文的问题。我看到的某个ssl vpn检测工具，仅仅是收发和解析tlcp协议握手数据包，不可能与openvpn互通。
请问您后来怎么解决的呢？检测时，需要去掉openvpn的报文头吗？

**Comment by apsara2825** [comment]
你好，请问一下你是用哪个版本的做的
