### ISSUE TITLE
有没有Android下成功进行公钥加密和私钥解密的demo?

### ISSUE THREAD

**Issue by jnuleavin** [guanzhi/GmSSL#345]
我在linux下编译好GmSSL后，在Android项目通过jni中使用时，发现GmSSL Java Wrapper中的部分函数使用不了，例如：getVersion；部分函数返回null，例如：symmetricEncrypt；部分函数可以运行成功。一直在纠结这个问题。

**Comment by xinlong-song** [comment]
诚邀各位国密的开发者和爱好者加入qq群：658887025
大家一起学习交流，共同探讨GmSSL使用过程中遇到的问题

**Comment by pan8664716** [comment]
https://github.com/pan8664716/GmSSLDemo.git

**Comment by pan8664716** [comment]
这个是我自己写的关于GmSSL的加解密的demo，希望对你有用。
