### ISSUE TITLE
windows平台无法编译

### ISSUE THREAD

**Issue by dlynine** [guanzhi/GmSSL#347]
![360 16380523275975](https://user-images.githubusercontent.com/17630531/29755754-24c01cec-8bcf-11e7-8e13-c529b3f31ed4.png)

**Comment by 1132719438** [comment]
vs不支持使用变量定义数组大小，不支持在块中间定义变量
改用malloc分配空间
把变量定义放在函数开始

**Comment by dlynine** [comment]
多谢，我之前编译的是master，后来问了别人说master不行，我改为v1了，现在是报这个错误
![qq 20170828160004](https://user-images.githubusercontent.com/17630531/29764610-60e227a2-8c0a-11e7-9e47-1c4504ef58f8.jpg)

**Comment by 1132719438** [comment]
v1在windows编译问题更多

**Comment by dlynine** [comment]
@1132719438 你好，能把编译好的发我下吗？非常感谢

**Comment by mkvt100** [comment]
@1132719438 ，@dlynine，两位您好！我也正在尝试VS2013编译gmssl-master,遇到的报错和dlynine第一个截图一样，请问dlynine，现在您是否解决了呢？请教两位解决的方法啊，不胜感激~！

**Comment by 1112233445566** [comment]
@1132719438 @dlynine 你好，请问我在perl Configure VC-WIN32后出现MASM not found这个问题当时你们出现了吗？应该怎么解决

**Comment by chengfang0911** [comment]
@1132719438 能把编译好的也发我一份吗？window编译不过

**Comment by chengfang0911** [comment]
这个把代码修改下就行了，没几句话。
