### ISSUE TITLE
加载动态库报错java: symbol lookup error:/libgmssl.so: undefined symbol: OpenSSL_version

### ISSUE THREAD

**Issue by kiddingquan** [guanzhi/GmSSL#349]
已经生成了libgmssl.so，然后java GmSSL 运行时报错java: symbol lookup error: /home/hgq/lib/libgmssl.so: undefined symbol: OpenSSL_version，求助

**Comment by guanzhi** [comment]
先试一下Mac下的二进制版 https://github.com/guanzhi/GmSSL/releases/tag/gmssljni-api-1.1
稍后提供代码更新及Linux版

**Comment by kiddingquan** [comment]
我的时在linux下的，现在调用对称加密symmetricEncrypt这个方法的时候返回null，并且getErrorString方法返回的也是null。查看编译出来的.so文件依赖的动态库时打印出：undefined symbol: OpenSSL_version	(./libgmssl.so)，请问这个情况应该怎么解决？

**Comment by guanzhi** [comment]
此问题在master分支中已解决
