### ISSUE TITLE
对GMSSL的不明白的地方，求解。

### ISSUE THREAD

**Issue by SDquantum** [guanzhi/GmSSL#350]
@guanzhi老师
1.请问gmsslv1.3是不是就是把sm2，sm4等国密算法加到了libcrypto里面，但是在ssl协议里如果想使用国密套件的话，还需要自己手动修改代码添加对应的套件才能支持？改动大不大？
2本月会推出gmsslv2就是吧ssl协议过程也加了国密算法？
3我们目前就是用的openssl进行身份验证和通信时aes的加解密，使用目前的gmssl是否可以做到国密证书身份验证，以及通信时使用国密算法？

**Comment by guanzhi** [comment]
1. 1.3 支持1个国密的套件并且仅支持一个套件
2. 2.0支持多个多个国密套件及所有原有的套件。
3. 可以
