### ISSUE TITLE
SM2的公钥对问题

### ISSUE THREAD

**Issue by Lazysunshine123** [guanzhi/GmSSL#351]
用Ukey生成了公私钥对，如下：
公钥X:C4F0072F8BE009ED349CB2DA9FC48C7C0C19BFD8989AFAB3E8C5D594F1F51BE6
公钥Y:BD968B968DDE8D1F0E5BAA893455F1F27440395ECAAB8B7EF802D77E632B660E
私钥：EDA00D26E0D14F2419D52F1AC56ABAD3292A7102E29DE3E3C790A5AD997A6529
请问怎么将这两个公钥组合起来替换GMSSL中的公钥，来实现签名与验证呢？试了直接拼接起来不可行。

谢谢版主

**Comment by mysummergit** [comment]
国密sm2算法使用规范规定SM2PublicKey=04||X||Y，可能是你连接后没有前面部分04

**Comment by guanzhi** [comment]
鉴于转换原始的SM2公私钥需求比较多，GmSSL会在命令行中增加相应的解析转换命令`sm2`

**Comment by happyycm** [comment]
> 鉴于转换原始的SM2公私钥需求比较多，GmSSL会在命令行中增加相应的解析转换命令`sm2`

老师，源码里有可以把HEX字符串格式的密钥转换成ASN.1/DER格式的函数吗？（JAVA API使用那种）
