### ISSUE TITLE
如何做一个小软件包在ARM平台上来支持SM2/3/4

### ISSUE THREAD

**Issue by liping-wang** [guanzhi/GmSSL#353]
关老师，您好。

我正在作一个项目来支持SM 2/3/4算法. 我只需要支持Generate SM3 digest, SM4 encryption and decryption, SM2 key signing, SM2 signature verification。我试图把SM 2/3/4 functions从GmSSL里面分离出来,做个小软件包。

我已经把crypto/sms4 and test/sms4test.c做成了a standalone program. But when I tried to make crypto/sm3 and test/sm3test.c into a standalone program I got these link errors as follows:

$ make
Building..
gcc  sm3test.o ../crypto/sm3/libsm3.a -ldl -lc -o sm3test_exe 
sm3test.o: In function `main':
/GmSSL-only-sm432/GmSSL/test/sm3test.c:211: undefined reference to `OPENSSL_hexstr2buf'
/GmSSL-only-sm432/GmSSL/test/sm3test.c:219: undefined reference to `EVP_sm3'
/GmSSL-only-sm432/GmSSL/test/sm3test.c:219: undefined reference to `EVP_Digest'
/GmSSL-only-sm432/GmSSL/test/sm3test.c:232: undefined reference to `OPENSSL_free'
collect2: ld returned 1 exit status
make: *** [all] Error 1

Compilation of crypto/sm2 and test/sm2test.c without using openssl Makefile gave me more errors. I need to create my Makefiles to solve the problem, but I am not familiar with OPENSSL source code.

能否请您指教一下，有什么好的方法来生成这样一个小软件包来支持SM 2/3/4？

另一方面，您是否认为我唯一的办法是编译和使用整个GmSSL包来支持SM算法？

非常感谢!

**Comment by tengent** [comment]
我觉得 你可以尝试下 link下 openssl的 -lssl -lcrypto 因为有一部分symbol实际上是在这两个库中
如果编译通过的话 然后 你可以通过 nm 查看具体的EVP_digest 这样的symbol在那个so里面， 然后根据从项目中再一个个抽取函数实现。其实偷懒的话 直接link openssl的静态库就可以了，就是程序会有点大。

**Comment by guanzhi** [comment]
不太可能，因为GmSSL中的SM2和SMS4依赖了很多openssl的模块，如bn, ec, err, mode, evp等等。GmSSL的库文件只有2~3MB，静态链接时通常只让程序增加1MB左右的大小，并不算大。
