### ISSUE TITLE
Ukey中生成的公钥，如何转换成相应的der或者pem格式呢？

### ISSUE THREAD

**Issue by Lazysunshine123** [guanzhi/GmSSL#355]
关老师您好：
    想再次请教您一下关于SM2公钥的问题。
    我在Ukey中生成的公钥是这样：
（PubX:C4F0072F8BE009ED349CB2DA9FC48C7C0C19BFD8989AFAB3E8C5D594F1F51BE6；
  PubY:BD968B968DDE8D1F0E5BAA893455F1F27440395ECAAB8B7EF802D77E632B660E）然后根据04+PubX+PubY将公钥串接起来。得到一个长度为130个字符的16进制公钥。
    我想把Ukey中的签名和公钥送到GMSSL中进行验签。因此，需要把Ukey中生成的公钥转换成der或者pem 格式，但查阅了大量的资料，仍然没有得到正确的转换方式，所以想向您求助一

下。
    以下是我采用的方案，但好像是错的。
    我将在GMSSL中生成的pem格式的公钥转换成der的十六进制格式。如下：
    0000000 5930 1330 0706 862a ce48 023d 0601 2a08

    0000010 1c81 55cf 8201 032d 0042 4704 149f d008

    0000020 c711 7988 c47f fade 97d1 8638 ac83 146e

    0000030 8da3 c274 c11f 7414 bb47 dd80 2b5e 9305

    0000040 9add 98bf c685 de6b b9c3 fb82 7684 1073

    0000050 c3cb 3500 dc85 a029 192e 0041          

    000005b

    观察比较了几组后，我试图将第二行4704与其之后的共132个16进制字符，用Ukey生成的公钥“04+PubX+PubY+00”替换，并交换相邻两对字符的顺序。得到我认为的16进制der格式公钥

，转换成相应的二进制，传入gmssl中，然而系统提示转换之后的der文件不是可读的密钥。

**Comment by guanzhi** [comment]
看来这是个普遍的需求，后续`gmssl`命令行会增加一个独立的`sm2`命令选项来读取和转换这种原始格式，读入的私钥和公钥格式会严格参考GM/T的相关标准。

**Comment by tianlitao** [comment]
@guanzhi 请问现在支持这个功能了吗
