### ISSUE TITLE
perl Configure VC-WIN32运行有问题

### ISSUE THREAD

**Issue by 1112233445566** [guanzhi/GmSSL#356]
安装了ActivePerl，使用管理员身份打开vs2010的Developer Command Prompt执行了perl Configure VC-WIN32，显示结果为
![image](https://user-images.githubusercontent.com/31848948/30415869-91c0ba5a-995c-11e7-9bb4-e1621b568c70.png)
使用vs2015时同样的操作出现的结果显示masm not found，请问下大家怎么解决，谢谢

**Comment by 1112233445566** [comment]
现在这个问题解决之后会出现
![image](https://user-images.githubusercontent.com/31848948/30416341-5ca0c1d8-995e-11e7-85d4-666760748144.png)
需要怎么解决

**Comment by LightYears88** [comment]
下载安装一个NASM,并配置上环境变量
