### ISSUE TITLE
gmssl和自己写的go的证书请求的格式不兼容

### ISSUE THREAD

**Issue by nnsgmsone** [guanzhi/GmSSL#358]
根据crypto的x509改写了证书请求的生成函数。生成的CSR自己可以验证，不过gmssl会提示验证失败，错误信息是

> verify failure
> 140192753948416:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:184:

证书的具体信息如下:

> Certificate Request:
>     Data:
>         Version: 1 (0x0)
>         Subject: O = \CE\A3 Acme Co, CN = test.example.com
>         Subject Public Key Info:
>             Public Key Algorithm: id-ecPublicKey
>                 Public-Key: (256 bit)
>                 pub:
>                     04:dc:59:6c:5d:0d:96:ea:05:b1:eb:7d:ce:49:6d:
>                     c7:d2:67:4e:13:49:c4:bb:6a:81:60:b6:2b:a2:fc:
>                     ce:e0:85:79:9e:22:51:74:5c:d2:04:f9:1e:66:8c:
>                     52:9c:02:60:b1:67:79:2c:47:3f:cd:08:86:a4:bc:
>                     27:ec:59:76:f4
>                 ASN1 OID: sm2p256v1
>         Attributes:
>         Requested Extensions:
>             X509v3 Subject Alternative Name: 
>                 DNS:test.example.com, email:gopher@golang.org, IP Address:127.0.0.1, IP Address:2001:4860:0:2001:0:0:0:68
>     Signature Algorithm: ecdsa-with-SHA256
>          30:44:02:20:5b:3c:73:9e:29:9c:8a:de:03:7c:59:c7:84:06:
>          58:34:b6:7e:82:7c:9c:d6:0d:2c:dc:50:9b:0e:8d:51:bf:60:
>          02:20:01:d7:53:ac:3a:81:0a:8e:4c:33:a5:44:12:dd:99:14:
>          d7:b0:ed:5d:05:8e:a1:d0:cf:09:81:6a:30:7f:47:16
> subject=O = \CE\A3 Acme Co, CN = test.example.com

gmssl生成的证书格式如下:

> Certificate Request:
>     Data:
>         Version: 1 (0x0)
>         Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
>         Subject Public Key Info:
>             Public Key Algorithm: id-ecPublicKey
>                 Public-Key: (256 bit)
>                 pub:
>                     04:dc:59:6c:5d:0d:96:ea:05:b1:eb:7d:ce:49:6d:
>                     c7:d2:67:4e:13:49:c4:bb:6a:81:60:b6:2b:a2:fc:
>                     ce:e0:85:79:9e:22:51:74:5c:d2:04:f9:1e:66:8c:
>                     52:9c:02:60:b1:67:79:2c:47:3f:cd:08:86:a4:bc:
>                     27:ec:59:76:f4
>                 ASN1 OID: sm2p256v1
>         Attributes:
>             a0:00
>     Signature Algorithm: ecdsa-with-SHA256
>          30:45:02:20:1f:f0:bb:7b:e7:f7:79:8b:46:c9:ca:50:8c:2d:
>          81:a2:db:81:3d:97:19:68:e0:ac:c3:21:c4:6b:62:00:a8:7c:
>          02:21:00:da:19:a7:48:4a:ec:a4:8d:9c:dc:88:67:66:93:82:
>          24:c2:9c:60:d3:c2:6d:3a:84:14:16:d4:38:c3:8b:8d:12
> subject=C = AU, ST = Some-State, O = Internet Widgits Pty Ltd

我想知道gmssl的证书请求和一般的有什么差别，或者我的实现有什么问题，具体的代码如下:
`func CreateCertificateRequest(rand io.Reader, template *CertificateRequest, privKey *PrivateKey) ([]byte, error) {
	hashFunc, sigAlgo, err := signingParamsForPublicKey(privKey.Public(),
		template.SignatureAlgorithm)
	if err != nil {
		return nil, err
	}
	var publicKeyAlgorithm pkix.AlgorithmIdentifier
	publicKeyBytes := elliptic.Marshal(privKey.Curve, privKey.X, privKey.Y)
	publicKeyAlgorithm.Algorithm = oidSM2
	publicKeyAlgorithm.Parameters.Class = 0
	publicKeyAlgorithm.Parameters.Tag = 6
	publicKeyAlgorithm.Parameters.IsCompound = false
	publicKeyAlgorithm.Parameters.Bytes = []byte{42, 129, 28, 207, 85, 1, 130, 45}
	publicKeyAlgorithm.Parameters.FullBytes = []byte{6, 8, 42, 129, 28, 207, 85, 1, 130, 45}

	var extensions []pkix.Extension
	if (len(template.DNSNames) > 0 || len(template.EmailAddresses) > 0 ||
		len(template.IPAddresses) > 0) &&
		!oidInExtensions(oidExtensionSubjectAltName, template.ExtraExtensions) {
		sanBytes, err := marshalSANs(template.DNSNames, template.EmailAddresses,
			template.IPAddresses)
		if err != nil {
			return nil, err
		}
		extensions = append(extensions, pkix.Extension{
			Id:    oidExtensionSubjectAltName,
			Value: sanBytes,
		})
	}
	extensions = append(extensions, template.ExtraExtensions...)
	var attributes []pkix.AttributeTypeAndValueSET
	attributes = append(attributes, template.Attributes...)
	if len(extensions) > 0 {
		// specifiedExtensions contains all the extensions that we
		// found specified via template.Attributes.
		specifiedExtensions := make(map[string]bool)
		for _, atvSet := range template.Attributes {
			if !atvSet.Type.Equal(oidExtensionRequest) {
				continue
			}
			for _, atvs := range atvSet.Value {
				for _, atv := range atvs {
					specifiedExtensions[atv.Type.String()] = true
				}
			}
		}
		atvs := make([]pkix.AttributeTypeAndValue, 0, len(extensions))
		for _, e := range extensions {
			if specifiedExtensions[e.Id.String()] {
				// Attributes already contained a value for
				// this extension and it takes priority.
				continue
			}
			atvs = append(atvs, pkix.AttributeTypeAndValue{
				// There is no place for the critical flag in a CSR.
				Type:  e.Id,
				Value: e.Value,
			})
		}
		// Append the extensions to an existing attribute if possible.
		appended := false
		for _, atvSet := range attributes {
			if !atvSet.Type.Equal(oidExtensionRequest) || len(atvSet.Value) == 0 {
				continue
			}
			atvSet.Value[0] = append(atvSet.Value[0], atvs...)
			appended = true
			break
		}

		// Otherwise, add a new attribute for the extensions.
		if !appended {
			attributes = append(attributes, pkix.AttributeTypeAndValueSET{
				Type: oidExtensionRequest,
				Value: [][]pkix.AttributeTypeAndValue{
					atvs,
				},
			})
		}
	}
	asn1Subject := template.RawSubject
	if len(asn1Subject) == 0 {
		asn1Subject, err = asn1.Marshal(template.Subject.ToRDNSequence())
		if err != nil {
			return nil, err
		}
	}
	rawAttributes, err := newRawAttributes(attributes)
	if err != nil {
		return nil, err
	}
	tbsCSR := tbsCertificateRequest{
		Version: 0, // PKCS #10, RFC 2986
		Subject: asn1.RawValue{FullBytes: asn1Subject},
		PublicKey: publicKeyInfo{
			Algorithm: publicKeyAlgorithm,
			PublicKey: asn1.BitString{
				Bytes:     publicKeyBytes,
				BitLength: len(publicKeyBytes) * 8,
			},
		},
		RawAttributes: rawAttributes,
	}
	tbsCSRContents, err := asn1.Marshal(tbsCSR)
	if err != nil {
		return nil, err
	}
	tbsCSR.Raw = tbsCSRContents

	h := hashFunc.New()
	h.Write(tbsCSRContents)
	digest := h.Sum(nil)
	signature, err := privKey.Sign(digest)
	if err != nil {
		return nil, err
	}
	return asn1.Marshal(certificateRequest{
		TBSCSR:             tbsCSR,
		SignatureAlgorithm: sigAlgo,
		SignatureValue: asn1.BitString{
			Bytes:     signature,
			BitLength: len(signature) * 8,
		},
	})
}`

**Comment by nnsgmsone** [comment]
我发现从gmssl生成的证书请求中提取签名的数据以及原始数据并进行Verify会不通过，请问有谁知道gmssl具体到底做了啥？？？？？

**Comment by nnsgmsone** [comment]
大叔也是醉了，gmssl的证书用的ecdsa算法sign和verify，代码看的我真是。。。。。。

**Comment by wangsuo2015** [comment]
想知道你的sm2证书请求文件最后怎么生成sm2证书的，我用gmssl也报同样的错误
140642719459136:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:174:

**Comment by nnsgmsone** [comment]
gmssl req -x509 -key key.pem -in req.pem -out cert.pem

**Comment by nnsgmsone** [comment]
gmssl的证书的格式有点奇怪，没有采用sm2自己的OID，我为了兼容gmssl，在现在公司的项目里面也是这么做的。。。

**Comment by wangsuo2015** [comment]
我想再问一个问题，证书请求文件中签名的原始数据是怎么组成的，有没有相关的文档参考一下

**Comment by nnsgmsone** [comment]
RFC2986, 可以先看看这个，反正就是各种RFC文档。。。

**Comment by nnsgmsone** [comment]
国密的可以查看一些国密的文档，你看的懂go的话可以看这个https://github.com/tjfoc/gmsm，我帮公司写的，写的比较简单，看看结构体就大致明白了

**Comment by wangsuo2015** [comment]
好的，谢谢啦

**Comment by guanzhi** [comment]
目前gmssl主分支(2.0)是可以通过`gmssl verify`命令正确验签CFCA等机构颁发的SM2证书的。如果无法验证通过，可以用`gmssl asn1parse`命令，仔细对比你的证书和CFCA证书的差别，发现问题。

**Comment by nnsgmsone** [comment]
哦， 我后来自己写了一个go版本的符合标准的。。。没参照gmssl了
 
 
------------------ Original ------------------
From: "Zhi Guan"; 
Date: 2017年11月6日(星期一) 上午8:57
To: "guanzhi/GmSSL"; 
Cc: "nnsgmsone"; "Author"; 
Subject: Re: [guanzhi/GmSSL] gmssl和自己写的go的证书请求的格式不兼容 (#358)

 

目前gmssl主分支(2.0)是可以通过gmssl verify命令正确验签CFCA等机构颁发的SM2证书的。如果无法验证通过，可以用gmssl asn1parse命令，仔细对比你的证书和CFCA证书的差别，发现问题。
