### ISSUE TITLE
sm2的用法

### ISSUE THREAD

**Issue by qq575654643** [guanzhi/GmSSL#359]
echo "hello world" > a.txt;

生成SM2密钥并签名
gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve  -out signkey.pem;
gmssl pkeyutl -sign -pkeyopt ec_sign_algor:sm2 -inkey signkey.pem -in a.txt -out b.txt.sig;

可以将公钥从signkey.pem中导出并发发布给验证签名的一方
gmssl pkey -pubout -in signkey.pem -out vrfykey.pem; 
gmssl pkeyutl -verify -pkeyopt ec_sign_algor:sm2 -inkey vrfykey.pem -sigfile b.txt.sig -in a.txt;

最后这条会报错，密钥不对，不是应该用公钥vrfykey.pem吗？
gmssl pkeyutl -verify -pkeyopt ec_sign_algor:sm2 -inkey signkey.pem -sigfile b.txt.sig -in a.txt;
这样才对，然后就不懂了。

期待回复 575654643@qq.com

**Comment by wuyan921** [comment]
验证的命令加上 -pubin

**Comment by zhaoxiaomeng** [comment]
问题已经修复，多谢提醒。
