### ISSUE TITLE
编译sm3test出错，求指教

### ISSUE THREAD

**Issue by yihong731** [guanzhi/GmSSL#36]
没有像openssl，采用-lcrypto的参数，采用如下参数进行编译，提示错误：

chen@debian-chen:~/work/GmSSL/GmSSL/crypto/sm3$ gcc sm3.c sm3test.c -o sm3test
/tmp/ccwkkwmq.o：在函数‘main’中：
sm3test.c:(.text+0x34)：对‘EVP_sm3’未定义的引用
sm3test.c:(.text+0x61)：对‘EVP_Digest’未定义的引用
collect2: error: ld returned 1 exit status
谢谢！

**Comment by yihong731** [comment]
追问，也可以像Openssl一样，采用-lcrypto的参数吗？

**Comment by LiTianjue** [comment]
先编译GmSSL的库，编译测试程序的时候要指定GmSSL的头文件（-I）和库(-L)

**Comment by yihong731** [comment]
谢谢！ 是在编译命令的尾部添加吗？能否具体指导一下。

**Comment by yihong731** [comment]
gcc sm3.c sm3test.c -o sm3test -lcrypto -ldl
这样就可以了。

但是sms4speed.c的编译还是存在问题尚未解决。

**Comment by guanzhi** [comment]
编译sms4speed.c需要安装OpenMP环境
