### ISSUE TITLE
SDF接口提问！！！！！

### ISSUE THREAD

**Issue by zyxx-13** [guanzhi/GmSSL#365]
请问SDF接口中有一部分文件管理接口其中创建文件接口备注为:在密码设备内部创建用于存储用户数据的文件。
那么这个用户数据指什么？（用户名称？密钥备份？）
具体需要开多大空间给这个文件？

**Comment by guanzhi** [comment]
这个存储空间可以用于存储任何用户数据，例如用户的证书，但是不建议作为密钥备份。
这个存储空间有多大是由硬件决定的，产品手册中对这个空间的大小会有说明。

**Comment by zyxx-13** [comment]
@guanzhi 关老师，请问SAF与SDF之间的调度关系是怎样的？
1.各自独立使用？（看接口规范中有些接口功能是重复定义的如：生成ECC密钥对）
2.在SAF接口中调用SDF接口？（如生成ECC密钥对功能即用户直接调用SAF接口，SDF的接口调用写在SAF接口中？）

**Comment by guanzhi** [comment]
在GmSSL中调用关系如下：
SAF->EVP->ENGINE ->SDF->厂商SDF库

**Comment by zyxx-13** [comment]
@guanzhi 关老师，我们公司现在是要脱离GMSSL给我们公司生产的PCIE加密卡提供SDF,SAF接口，现在的主要问题是不知道SAF与SDF接口该如何使用：
猜想调用流程：用户->SAF接口->SDF接口......请问这个调用过程是否是这样？
另外还有人性问题想要向您请教：
1.为什么SDF中只提供了外部密钥ECC公钥加密接口却不提供外部密钥ECC解密接口或者内部密钥ECC解密接口？
2.SAF接口规范ECC公钥加密接口中为什么输入的要是DER编码的公钥（是否是因为密钥不能以明文方式出现）？

**Comment by zyxx-13** [comment]
@guanzhi 关老师，我们公司现在是要脱离GMSSL给我们公司生产的PCIE加密卡提供SDF,SAF接口，现在的主要问题是不知道SAF与SDF接口该如何使用：
猜想调用流程：用户->SAF接口->SDF接口......请问这个调用过程是否是这样？
另外还有一些问题想要向您请教：
1.为什么SDF中只提供了外部密钥ECC公钥加密接口却不提供外部密钥ECC解密接口或者内部密钥ECC解密接口？
2.SAF接口规范ECC公钥加密接口中为什么输入的要是DER编码的公钥（是否是因为密钥不能以明文方式出现）？

**Comment by zyxx-13** [comment]
@guanzhi 关老师，请问GMSSL的saf_base64.c文件中为什么对任意长度数据base64编码接口要放在单块base64编码接口里面调用啊？（代码如下）
/* 7.3.2 */
int SAF_Base64_Encode(
	unsigned char *pucInData,
	unsigned int puiInDataLen,
	unsigned char *pucOutData,
	unsigned int *puiOutDataLen)
{
	int ret = SAR_UnknownErr;
	void *handle = NULL;
	unsigned char *p;
	unsigned int len;

	if (!pucInData || !pucOutData || !puiOutDataLen) {
		SAFerr(SAF_F_SAF_BASE64_ENCODE, ERR_R_PASSED_NULL_PARAMETER);
		return SAR_IndataErr;
	}

	if ((ret = SAF_Base64_CreateBase64Obj(&handle)) != SAR_OK) {
		SAFerr(SAF_F_SAF_BASE64_ENCODE, ERR_R_GMAPI_LIB);
		goto end;
	}

	p = pucOutData;
	len = *puiOutDataLen;

	if ((ret = SAF_Base64_EncodeUpdate(handle, pucInData, puiInDataLen,
		p, &len)) != SAR_OK) {
		SAFerr(SAF_F_SAF_BASE64_ENCODE, ERR_R_GMAPI_LIB);
		goto end;
	}
	p += len;

	len = *puiOutDataLen - len;
	if ((ret = SAF_Base64_EncodeFinal(handle, p, &len)) != SAR_OK) {
		SAFerr(SAF_F_SAF_BASE64_ENCODE, ERR_R_GMAPI_LIB);
		goto end;
	}
	p += len;

	*puiOutDataLen = p - pucOutData;
	ret = SAR_OK;

end:
	SAF_Base64_DestroyBase64Obj(handle);
	return ret;
}

**Comment by guanzhi** [comment]
1. SDF的加密是用来向设备导入私钥的，因此没有解密函数
2. DER编码就是干这个用的
