### ISSUE TITLE
GmSSL通过ENGINE机制访问支持国密SKF API的国产密码硬件问题？？？

### ISSUE THREAD

**Issue by sysbling** [guanzhi/GmSSL#366]
我现在要调用USBKey里面的公私钥对进行数据的非对称加解密，公钥加密通过调用国密SKF API可以实现，但是私钥解密因为私钥不可以出key，而且SKF API里面没有对应的解密接口，所以想通过GmSSL通过ENGINE机制访问支持国密SKF API的国产密码硬件这种方式来实现，想请教各位大神，具体要怎样做？

**Comment by guanzhi** [comment]
标准的SKF接口不支持SM2加解密的功能，只支持SM2签名和密钥交换。但是部分设备厂商对SKF接口做了扩展，引入了新的函数支持解密。由于这不是标准功能，各个厂商的实现方式和接口可能不同，因此需要咨询设备生产厂商。

**Comment by sysbling** [comment]
好的，谢谢

**Comment by boyxuper** [comment]
冒昧问一下，据您了解，哪些厂商有对SKF接口做扩展来支持解密吗？ @guanzhi
