### ISSUE TITLE
gmssl 无法验签ukey中sm2算法生成的签名

### ISSUE THREAD

**Issue by RubicPhil** [guanzhi/GmSSL#369]
已获取ukey生成的公钥（04 | publicX | publicY）；
再通过gmssl pkeyutl -verify -pubin -inkey vrfykey.pem   -pkeyopt ec_sign_algor:sm2 -in test.txt -sigfile test.sig进行验签，结果为验签失败，无出错提示

**Comment by guanzhi** [comment]
首先用X,Y坐标初始化一个椭圆曲线点EC_POINT，然后将该点设置为EC_KEY的公钥，然后将EC_KEY输出为PEM格式，就可以被pkeyutl读取了。以上需要编程实现。
