### ISSUE TITLE
请问SM2证书目前具体是哪里不完善

### ISSUE THREAD

**Issue by zsdev2015** [guanzhi/GmSSL#37]
这个项目很棒，正在学习。不过有个疑问作者说SM2证书和规范的证书还有差距，这个具体是指？
望指教。谢谢

**Comment by zsdev2015** [comment]
我看了下例子 签名算法是ecdsa-with-SHA256， 请问怎么成生sm2sign-with-sm3

**Comment by guanzhi** [comment]
如果您是来自上海安达通(www.adtsec.com)公司的朋友，欢迎您在安达通公司内部或产品中使用GmSSL。
