### ISSUE TITLE
转换java密钥库错误

### ISSUE THREAD

**Issue by jngxx** [guanzhi/GmSSL#370]
#keytool -importkeystore -srckeystore gmserver.p12 -srcstoretype pkcs12 -srcstorepass 123456 
               -destkeystore gmtomcat.jks -deststoretype jks -deststorepass 123456

keytool 错误: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301

**Comment by guanzhi** [comment]
keytool不支持国密，用gmssl命令行工具生成所需密钥和证书

**Comment by jngxx** [comment]
用gmssl生成证书并转换pkcs12格式都没问题，用keytool转换jks格式时报错，即使不转换jks，在tomcat中配置keystore使用pkcs12类型，也是提示上述错误，是java不认识国密算法的oid，怎么才能让它认识？

**Comment by jngxx** [comment]
证书是按如下步骤生成的：
//CA证书
gmssl ecparam -genkey -name sm2p256v1 -out ca.key
gmssl req -new -sm3 -key ca.key -out ca.csr
gmssl x509 -req -sm3 -signkey ca.key -in ca.csr -out ca.crt
//服务端证书
gmssl ecparam -genkey -name sm2p256v1 -out server.key
gmssl req -new -sm3 -key server.key -out server.csr -subj "/C=CN/ST=SD/OU=rn/CN=gxx"
gmssl x509 -req -sm3 -CA ca.crt -CAkey ca.key -CAcreateserial -in server.csr -out server.crt
//转换java承认的pkcs格式
gmssl pkcs12 -export -in server.crt -inkey server.key -out server.p12 -name server

**Comment by guanzhi** [comment]
keytool不识别国密曲线1.2.156.10197.1.301，就不要用keytool了

**Comment by jngxx** [comment]
用gmssl生成的国密证书，在tomcat中配置也不认啊，提示同样的错误，你看我的证书生成步骤有问题吗？你们在tomcat中使用过国密证书吗？

**Comment by guanzhi** [comment]
Java不支持国密算法和国密SSL，别在keytool上浪费时间了。
理论上可以通过Tomcat Native库来接入GmSSL，这样可以绕开Java部分，但是有很多工作量。

**Comment by jngxx** [comment]
java不支持可以通过JSSE组件提供国密算法的实现吧？
还有GmSSL Java Wrapper不是GMSSL的java封装，没有生成证书的接口？

**Comment by guanzhi** [comment]
GmSSL Java部分支持密码功能接口，证书和SSL还不支持

**Comment by Fury-Fox** [comment]
> Java不支持国密算法和国密SSL，别在keytool上浪费时间了。
> 理论上可以通过Tomcat Native库来接入GmSSL，这样可以绕开Java部分，但是有很多工作量。

通过Tomcat Native库来接入GmSSL，是否涉及到APR的改造？
