### ISSUE TITLE
master版本编译后,用双证书做通信,报错

### ISSUE THREAD

**Issue by 27954741** [guanzhi/GmSSL#372]
srv端报错:
140384332015360:error:141AB06E:SSL routines:gmtls_construct_server_key_exchange:not implemented:ssl/statem/statem_gmtls.c:79:

client端报错:
SSL_connect:error in error
140616428889856:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
140616428889856:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto/asn1/tasn_dec.c:1100:
140616428889856:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=X509
140616428889856:error:1416F00D:SSL routines:tls_process_server_certificate:ASN1 lib:ssl/statem/statem_clnt.c:1238:

**Comment by guanzhi** [comment]
不支持双证书

**Comment by 27954741** [comment]
请问gmssl做单向认证的命令是什么
我现在用的:
s_server -gmtls -accept 8443 -cert srv-cert-sm2.pem -key srv-key-sm2.pem  -CAfile ca-cert-sm2.pem -Verify 0 -msg -state -debug

s_client -connect localhost:8443

**Comment by 27954741** [comment]
用1.3.0 openssl 1.0.1d的版本可以正常通讯,

**Comment by guanzhi** [comment]
-gmtls指GM/T 0024的协议，现在还不支持，应该用 -tls1_2

**Comment by gujinqiangggs** [comment]
@guanzhi 也就是说目前拿gmssl直接编译完了，还是不能拿一个签名证书和一个加密证书做服务端是吗？但是我看主页的docs中关于sslvpn的介绍部分说“GmSSL支持国密《GM/T 0024-2014: SSL VPN技术规范》的新增密码套件：”，是我理解有误还是，只是介绍这么写了，但是实际还是不支持？亦或是有付费版本可以支持？谢谢

**Comment by 27954741** [comment]
@guanzhi 编译了最新的master库,在做客户端-服务端通信的时候,服务端报错:
SSL_accept:SSLv3/TLS write server done
read from 0xb1f100 [0xb2a973] (5 bytes => 5 (0x5))
0000 - 15 03 03 00 02                                    .....
<<< ??? [length 0005]
    15 03 03 00 02
read from 0xb1f100 [0xb2a978] (2 bytes => 2 (0x2))
0000 - 02 32                                             .2
<<< TLS 1.2Alert [length 0002], fatal decode_error
    02 32
SSL3 alert read:fatal:decode error
SSL_accept:error in SSLv3/TLS write server done
ERROR
140111878608640:error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:ssl/record/rec_layer_s3.c:1385:SSL alert number 50
shutting down SSL
CONNECTION CLOSED
ACCEPT

**Comment by xuelang2009** [comment]
@27954741 我在ubantu上，编译的，V1.3.0和master，使用上面的命令，也是这样的错误

**Comment by guanzhi** [comment]
@gujinqiangggs GmSSL-2.0 目前的国密套件只能用在TLS 1.2协议中，不能用在SSL3,TLS1.0,1.1。双证书的协议命名为GMTLS-1.1，仅提供给付费用户。

**Comment by yangboyd** [comment]
怎么付费购买呢
