### ISSUE TITLE
双向消息发送问题

### ISSUE THREAD

**Issue by LightYears88** [guanzhi/GmSSL#373]
我写了一个客户端和服务端。客户端向服务端发送消息SSL_write, 然后服务端SSL_read 消息，这样一直单向发送，速度会很快；如果服务端每收到一条消息后，就SSL_write回给客户端一个确认消息，然后客户端SSL_read到这条确认消息后，再继续发送下一条，速度就很慢，原因出在哪了呢？
客户端代码大致如下：
![image](https://user-images.githubusercontent.com/25027143/32587550-08857564-c544-11e7-8fc4-8092a292978e.png)
服务端代码：
![image](https://user-images.githubusercontent.com/25027143/32587636-7405361c-c544-11e7-988a-f031f2d1f11d.png)

**Comment by guanzhi** [comment]
时间都用在通信延迟上了

**Comment by LightYears88** [comment]
那我应该怎么优化呢？走的内网，网络ping速度良好，无丢包延迟现象



wu_lbao@cvicse.com
 
发件人： Zhi Guan
发送时间： 2017-11-11 22:40
收件人： guanzhi/GmSSL
抄送： LightYears88; Author
主题： Re: [guanzhi/GmSSL] 双向消息发送问题 (#373)
时间都用在通信延迟上了

**Comment by guanzhi** [comment]
尽量合并请求和应答，问题主要出在你的应用层协议设计上。
