### ISSUE TITLE
master分支编译不通过，存在/usr/bin/ld:gmssljni.map:1: syntax error in VERSION script错误

### ISSUE THREAD

**Issue by cuisj** [guanzhi/GmSSL#374]
经查，在Makefile.shared文件的198行：
@$(PERL) $(SRCDIR)/util/mkdef.pl $(LIBNAME) linux >$(LIBNAME).map;  make编译到./libgmssljni.so.1.1, 实际上执行的是/usr/bin/perl ./util/mkdef.pl gmssljni linux >gmssljni.map;
而util/mkdef.pl 第一参数只允许是ssl, crypto
usage: ./util/mkdef.pl ( ssl | crypto ) [ 16 | 32 | NT | OS2 | linux | VMS ]

请修正，谢谢！

编译平台 linux

**Comment by guanzhi** [comment]
能否提供一个patch或pull request?

**Comment by hrimfaxi** [comment]
删除java/build.info或改名可绕过此问题

**Comment by guanzhi** [comment]
暂时从编译系统中移除了java接口的编译
