### ISSUE TITLE
无法进行SM2签名，提示pkeyutl: Can't set parameter：

### ISSUE THREAD

**Issue by hrimfaxi** [guanzhi/GmSSL#375]
操作系统：Ubuntu 16.04
最新commit(4d60905e044029d36f8ed02d5c838722d1346319)

0、生成test.file文件
 echo "Hello world" > test.file
1、生成签名私钥
gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out signkey.pem
2、对test.file进行签名
gmssl pkeyutl -sign -inkey signkey.pem -pkeyopt ec_sign_algor:sm2 -in test.file -out test_sign.sig

```
hrimfaxi@ubuntu-build-server:~/GmSSL$ gmssl version
GmSSL 2.0 - OpenSSL 1.1.0d  26 Jan 2017
hrimfaxi@ubuntu-build-server:~/GmSSL$  echo "Hello world" > test.file
hrimfaxi@ubuntu-build-server:~/GmSSL$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out signkey.pem
Using configuration from /usr/local/ssl/openssl.cnf
hrimfaxi@ubuntu-build-server:~/GmSSL$ gmssl pkeyutl -sign -inkey signkey.pem -pkeyopt ec_sign_algor:sm2 -in test.file -out test_sign.sig
Using configuration from /usr/local/ssl/openssl.cnf
pkeyutl: Can't set parameter:
```

**Comment by hrimfaxi** [comment]
是ec_sign_algor改名为b  ec_scheme吗?如果是请更新文档

**Comment by guanzhi** [comment]
我们会对这个问题进行修改，以保持和1.x版本的兼容性。

**Comment by daiziyi** [comment]
我也遇到这个问题. 
软件版本：GmSSL 2.1.1 - OpenSSL 1.1.0d  26 Jan 2018
运行环境：CentOS 7.3 X64
