### ISSUE TITLE
sm2_enc.c 代码问题

### ISSUE THREAD

**Issue by wojiushiwoba** [guanzhi/GmSSL#376]
关博士，您好！
我对代码有点疑问，有什么不对之处还请您指正。有疑问地方如下：
 GmSSL / crypto / sm2 / sm2_enc.c文件中，SM2_encrypt接口中，249行和251行在处理输出字符串长度时，为什么是不一样的？此处代码是否已测试完成？

**Comment by bylively** [comment]
您好 请问一下调用SM2_encrypt接口，得到的加密数据是der格式的。如何能把数据头去掉，得到加密后的裸加密数据。谢谢

**Comment by guanzhi** [comment]
GmSSL的SM2密文是一个ASN1的数据结构，你可以用编程的方式从SM2CiphertextValue中解析原始数据，或者`asn1parse`命令打印DER中的数据
