### ISSUE TITLE
SM2_do_encrypt加密

### ISSUE THREAD

**Issue by bylively** [guanzhi/GmSSL#377]
您好 ，我利用SM2_do_encrypt加密，i2o_SM2CiphertextValue得到加密数据，发送给服务端解密，服务端解密错误。解密错误的原因可能是什么那？搞不懂。。。（服务端不是利用gmssl里边的接口，是他们自己封装的。不知道他们的源码，也能得不到他们的支持，现在很困惑），希望能给我一些提示 谢谢

**Comment by guanzhi** [comment]
不同厂商实现的SM2密文格式并不一样，是导致无法互通的主要原因。你可以向设备厂商了解一下他们的密文格式。好在GmSSL提供源代码，你可以修改GmSSL的相应代码来兼容厂商的格式。

**Comment by bylively** [comment]
谢谢  问题已经解决。
