### ISSUE TITLE
代码编译失败

### ISSUE THREAD

**Issue by lilucpp** [guanzhi/GmSSL#378]
1.查看Travis CI编译结果是失败。
2.当前的代码在Windows 7 vs2015 x64编译失败。错误信息如下：
F:\gmss2-v2\GmSSL\include\openssl/ec.h(712): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存
为 Unicode 格式以防止数据丢失
        nasm -f win64 -DNEAR -Ox -g -ocrypto\x86_64cpuid.obj "crypto\x86_64cpuid.asm"
        cl  /I "." /I "crypto\include" /I "include" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENS
SL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m
 -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_A
SM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM "-DENGINESDIR=\"F:\\gmss2-v2\\buildGMSSL\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"
C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_E
NDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /O2 /Zi /Fdossl_static -c /Foms\uplink.obj "ms\uplink.c"
uplink.c
ms\uplink.c(92): warning C4311: “类型转换”: 从“void *”到“int”的指针截断
        cl  /I "." /I "crypto\include" /I "include" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENS
SL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m
 -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_A
SM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM "-DENGINESDIR=\"F:\\gmss2-v2\\buildGMSSL\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"
C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_E
NDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /O2 /Zi /Fdossl_static -c /Focrypto\dllmain.obj "crypto\dllmai
n.c"
dllmain.c
        "C:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1-x64.def
        "C:\Perl64\bin\perl.exe" -i.tmp -pe "s|^LIBRARY\s+crypto32|LIBRARY libcrypto-1_1-x64|;" libcrypto-1_1-x64.def
        DEL libcrypto-1_1-x64.def.tmp
        "C:\Perl64\bin\perl.exe" "util\mkrc.pl" libcrypto-1_1-x64.dll > libcrypto-1_1-x64.rc
        rc /folibcrypto-1_1-x64.res libcrypto-1_1-x64.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1-x64.dll.manifest DEL /F /Q libcrypto-1_1-x64.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll /def:libcrypto-1_1-x64.def @C:\Users\
ADMINI~1\AppData\Local\Temp\nmB598.tmp || (DEL /Q libcrypto.* libcrypto-1_1-x64.* && EXIT 1)
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_cipher_ctx
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_cipher_status
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_md
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_md_ctx
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_mem_data
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_get_mem_ptr
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_set_md_ctx
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_set_mem_buf
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 BIO_set_mem_eof_return
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_CTX_cleanup
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_CTX_flags
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_CTX_init
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_CTX_mode
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_CTX_type
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_mode
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_CIPHER_name
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_DECODE_LENGTH
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_DigestSignUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_DigestVerifyUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_ENCODE_LENGTH
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_block_size
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_create
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_destroy
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_init
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_size
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_CTX_type
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_name
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_MD_nid
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_OpenUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get0_ecdh_kdf_ukm
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ec_encrypt_param
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ec_scheme
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ecdh_cofactor_mode
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ecdh_kdf_md
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ecdh_kdf_outlen
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_ecdh_kdf_type
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_signature_md
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_signer_id
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_get_signer_zid
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set0_ecdh_kdf_ukm
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ec_encrypt_param
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ec_param_enc
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ec_paramgen_curve_nid
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ec_scheme
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ecdh_cofactor_mode
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ecdh_kdf_md
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ecdh_kdf_outlen
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_ecdh_kdf_type
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_mac_key
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_signature_md
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_CTX_set_signer_id
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_assign_DH
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_assign_DSA
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_assign_EC_KEY
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_assign_PAILLIER
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_PKEY_assign_RSA
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_SealUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_SignInit
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_SignInit_ex
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_SignUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_VerifyInit
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_VerifyInit_ex
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_VerifyUpdate
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_add_cipher_alias
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_add_digest_alias
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_delete_cipher_alias
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_delete_digest_alias
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_get_cipherbynid
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_get_cipherbyobj
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_get_digestbynid
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 EVP_get_digestbyobj
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 OPENSSL_add_all_algorithms_conf
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 OPENSSL_add_all_algorithms_noconf
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 OPENSSL_add_all_digests
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 OpenSSL_add_all_algorithms
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 OpenSSL_add_all_ciphers
libcrypto-1_1-x64.def : error LNK2001: 无法解析的外部符号 SM2_compute_key
libcrypto.lib : fatal error LNK1120: 77 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”
Stop.

**Comment by guanzhi** [comment]
尝试一下最新的更新。

**Comment by lilucpp** [comment]
1.更新后ubuntu64位可以编译过。
2.win7 vs2015 x64 还是编译不过,提示错误如上。无法解析的外部符号都是evp_nomacro.c这个文件中的.

**Comment by lilucpp** [comment]
不知道具体什么原因，能否提示一下，多谢关老师。

**Comment by xuelang2009** [comment]
你好，我也有这个问题，Lnk2001，73个无法解析的外部符号，你解决了吗？望告知解决方案，谢谢

**Comment by lilucpp** [comment]
@xuelang2009 还没有解决。

**Comment by xuelang2009** [comment]
@lilucpp 使用   https://github.com/guanzhi/GmSSL/releases   V1.3.0  倒是可以

**Comment by lilucpp** [comment]
@xuelang2009  嗯嗯，1.3是可以编译过的，最近几次的更新编译不过
