### ISSUE TITLE
X.509证书签名校验失败

### ISSUE THREAD

**Issue by zppet** [guanzhi/GmSSL#379]
你好！打扰了。
我们使用gmSSL生成了x509证书，但是校验失败了。
请问：咱们生成证书时
1. 签名所覆盖的数据范围是什么？ 是不是只覆盖tbsCertificate区域？
2. 签名时，要计算Za值（ENTLA||IDA||a||b||xG||yG||xA||yA)，请问IDA咱们采用的是什么值？GM/T 0009-2012 SM2密码算法使用规范里第10节规定了一个用户身份标识ID的默认值，16字节的，0x31323334454637383132333445463738，请问你们gmssl生成证书签名时，是否也使用这个默认值？

谢谢。

**Comment by guanzhi** [comment]
我们测试了CFCA的大部分CA证书，gmssl能够正确验证这些SM2证书。由于缺乏其他工具，我们无法验证gmssl生成的证书是否可以被其他工具验证。

如果有gmssl验证的SM2证书，请将PEM格式的证书贴上来。

**Comment by guanzhi** [comment]
对于gmssl的具体实现请参考源代码，因为代码更新后逻辑可能发生变化
