### ISSUE TITLE
gmssl增加引擎后无法调用EC算法方法的问题查找

### ISSUE THREAD

**Issue by wojiushiwoba** [guanzhi/GmSSL#380]
关老师，您好！
       我在gmssl中做了rsa引擎算法的engine后，测试调用都正常，但是在做了sm2的硬件引擎后，测试时就不调用我写的engine相关接口，一直调用gmssl项目组实现的SM2接口。经测试发现gmssl项目组在文件crypto\ec\ec_pmeth.c 150行增加了如下代码：
#ifndef OPENSSL_NO_SM2
    if (dctx->ec_scheme == NID_sm_scheme)
        ret = SM2_sign(NID_undef, tbs, tbslen, sig, &sltmp, ec);
    else
#endif
       我在删除这段代码后，测试能够正常调用我实现的sm2的engine接口，调用gmssl项目组实现的SM2相关方法接口也正常。
       另外，相同文件177行类似，其他接口就不一一说了。
       我这里有个疑问：咱这块代码 为了测试方便增加的代码，然后忘记删除，还是就是需要这么设计？有什么不妥之处还请指正！

**Comment by guanzhi** [comment]
如果你用GmSSL的内置SM2实现，不应该删除上述代码；如果调用你自己的Engine那么就无所谓了。GmSSL目前的设计和SM2 Engine并没有冲突。
