### ISSUE TITLE
SM2签名的PKCS7封装

### ISSUE THREAD

**Issue by sysbling** [guanzhi/GmSSL#381]
要怎样把sm2的签名封装成PKCS7的形式，没有找到国密标准中规定的signedData类型的oid

**Comment by guanzhi** [comment]
使用`smime`命令可以生成PKCS#7格式的数据

**Comment by sysbling** [comment]
我是用代码来实现的，调用PKCS7_sign(X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs,
                  BIO *data, int flags);函数，但是最后生成的签名结果的结构体oid是默认的1.2.840.113549.1.7.1，但是国密规定的签名数据类型的oid是1.2.156.10197.6.1.4.2.2，所以想请假一下老师，这个要怎么弄？

**Comment by sysbling** [comment]
还有我是使用USBkey来实现的，所以在函数KCS7_sign(X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs,BIO *data, int flags);中要用到的私钥没办法取出来，这也是一个问题

**Comment by rocedu** [comment]
自己可以添加OID啊，然后添加OID相关的case语句
