### ISSUE TITLE
请教下，SM对称算法模式的OID的来源是哪个规范。

### ISSUE THREAD

**Issue by iceskycn** [guanzhi/GmSSL#382]
比如：1.2.156.10197.1.102.1 是SM1 ECB模式，1.2.156.10197.1.102.2 是SM1 的CBC模式，我记得很早看过一份文档，1.2.156.10197.1.102.1.3 是SM1 的ECB模式。

**Comment by guanzhi** [comment]
公布的GM/T标准里面只有SM1的定义而没有SM1加各个模式的定义，这些带模式的OID都是GmSSL自行定义的。不知道您说的是哪个标准？

**Comment by iceskycn** [comment]
好的，我想问的就是对称算法中各个模式的OID定义是否有规范？谢谢
