### ISSUE TITLE
Suse Linux 编译gmssl报错，提示ld:gmssljni.map:1: syntax error in VERSION script

### ISSUE THREAD

**Issue by chtctc** [guanzhi/GmSSL#386]
make[2]: Leaving directory `/wxhome/soft/gmssl/GmSSL-master'
make -f ./Makefile.shared -e \
                PLATFORM=linux-x86_64 \
                PERL="/usr/bin/perl" SRCDIR='.' DSTDIR="." \
                INSTALLTOP='/usr/local' LIBDIR='lib64' \
                LIBDEPS=' '" -L. -lcrypto"' -ldl ' \
                LIBNAME=gmssljni LIBVERSION=1.1 \
                LIBCOMPATVERSIONS=';' \
                CC='gcc' CFLAGS='-DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib64/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE' \
                LDFLAGS='' \
                SHARED_LDFLAGS='-Wl,-znodelete -m64 ' SHLIB_EXT=.so.1.1 \
                RC='windres' SHARED_RCFLAGS='' \
                link_shlib.linux-shared
make[2]: Entering directory `/wxhome/soft/gmssl/GmSSL-master'
usage: ./util/mkdef.pl ( ssl | crypto ) [ 16 | 32 | NT | OS2 | linux | VMS ]
LD_LIBRARY_PATH=.: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -m64 -shared -Wl,-Bsymbolic -Wl,-soname=libgmssljni.so.1.1 -o ./libgmssljni.so.1.1 -Wl,--whole-archive,--version-script=gmssljni.map ./libgmssljni.a -Wl,--no-whole-archive -L. -lcrypto -ldl
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld:gmssljni.map:1: syntax error in VERSION script
collect2: ld returned 1 exit status
make[2]: *** [link_shlib.linux-shared] Error 1
make[2]: Leaving directory `/wxhome/soft/gmssl/GmSSL-master'
make[1]: *** [libgmssljni.so] Error 2
make[1]: Leaving directory `/wxhome/soft/gmssl/GmSSL-master'
make: *** [all] Error 2

感觉这个库libgmssljni.a没连接上，我在目录下看到有，是否需要放到系统目录下？
有人有碰到类似的问题么?

**Comment by guanzhi** [comment]
你试一下最新的master，这个更新应该已经解决了这个问题，并且在Travis上通过了。如果还出现这个错误尝试`make clean`一下。
