### ISSUE TITLE
gmssl在windows下编译报找不到stdbool.h头文件

### ISSUE THREAD

**Issue by chtctc** [guanzhi/GmSSL#387]
环境 win7 VS2010 ，在编译gmssl的时候报：
    crypto\base58\base58.c(56) : fatal error C1083: 无法打开包括文件:“stdbool.h”:No such file or directory
    NMAKE : fatal error U1077: “"e:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.EXE"”: 
    返回代码“0x2”Stop.

    我搜索了我的VS2010的目录下确实没有这个头文件，是否是VS2010的版本太低，希望有碰到此问题的高手，帮忙解答一下。

**Comment by chtctc** [comment]
是否是windows环境本来就个头文件，如果是这样的话，我还是自己改代码。

**Comment by guanzhi** [comment]
用VS2015
