### ISSUE TITLE
你好,SM2对于iOS开发真机报错

### ISSUE THREAD

**Issue by tongyu123** [guanzhi/GmSSL#39]
你好,这是在mac环境下编译后,导入项目,真机运行时报错:
ld: warning: ld: warning: ignoring file /Users/a123456/Desktop/SM2  SM4/libcrypto.a, file was built for archive which is not the architecture being linked (arm64): /Users/a123456/Desktop/SM2  SM4/libcrypto.aignoring file /Users/a123456/Desktop/SM2  SM4/libssl.a, file was built for archive which is not the architecture being linked (arm64): /Users/a123456/Desktop/SM2  SM4/libssl.a

ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(CharacterKeyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardThird.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(KeyboardTool.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(Keyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(XYKeyboard.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardFirst.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(NumberKeyboardSecond.o)) was built for newer iOS version (9.0) than being linked (7.0)
ld: warning: object file (/Users/a123456/Desktop/SM2  SM4/zhlcs/Classes/SDK/XYKeyboard/libXYKeyboard.a(UIView+LVExtension.o)) was built for newer iOS version (9.0) than being linked (7.0)
Undefined symbols for architecture arm64:
  "_EVP_sm3", referenced from:
      _test_sm2_enc in sm2Plugin.o
  "_EC_POINT_point2hex", referenced from:
      _test_sm2_enc in sm2Plugin.o
  "_EC_KEY_new", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_EC_POINT_point2oct", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_KDF_get_x9_63", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_CRYPTO_malloc", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_GROUP_get_order", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestInit_ex", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_CTX_new", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      -[sm2Plugin sm2:] in sm2Plugin.o
      _test_sm2_enc in sm2Plugin.o
  "_EVP_MD_CTX_create", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_get0_group", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      -[sm2Plugin sm2:] in sm2Plugin.o
      _test_sm2_enc in sm2Plugin.o
  "_EC_GROUP_get_cofactor", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_get0_public_key", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_GROUP_get_degree", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_hex2point", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_BN_rand_range", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_OpenSSLDie", referenced from:
      _SM2_do_encrypt in sm2_enc.o
      _test_sm2_enc in sm2Plugin.o
  "_BN_free", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestUpdate", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_DigestFinal_ex", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_mul", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_free", referenced from:
      _SM2_CIPHERTEXT_VALUE_free in sm2_enc.o
  "_BN_CTX_free", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_BN_num_bits", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_POINT_is_at_infinity", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EVP_MD_CTX_destroy", referenced from:
      _SM2_do_encrypt in sm2_enc.o
  "_EC_KEY_new_by_curve_name", referenced from:
      -[sm2Plugin sm2:] in sm2Plugin.o
  "_CRYPTO_free", referenced from:
      _SM2_CIPHERTEXT_VALUE_free in sm2_enc.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tongyu123** [comment]
静态库不支持arm64

**Comment by tongyu123** [comment]
你好,我今天在自己尝试编译arm64位时,报了个这样的错:
e_skf.c:747:7: error: implicit declaration of function 'bind_helper' is invalid
      in C99 [-Werror,-Wimplicit-function-declaration]
        if (!bind_helper(ret)) {
             ^
1 error generated.
make[1]: *** [e_skf.o] Error 1
make: *** [build_engines] Error 1

**Comment by guanzhi** [comment]
iPhone用不上国密硬件engine，可以直接在e_skf.c所在目录的Makefile中将skf删除。

**Comment by tongyu123** [comment]
你好,
EC_KEY *ec_key = EC_KEY_new();
    ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
    const EC_GROUP *ec_group = EC_KEY_get0_group(ec_key);
    BN_CTX *ctx1 = BN_CTX_new();
    EC_POINT * point1 = EC_POINT_hex2point(ec_group, pubkey, NULL, ctx1);
    ec_key -> pub_key = point1;
    
    SM2_CIPHERTEXT_VALUE *cv = NULL;
    cv = SM2_do_encrypt(EVP_sm3(), EVP_sm3(), (unsigned char *)message1, (size_t)strlen(message1), ec_key);
    OPENSSL_assert(cv);

SM2加密的流程是这样的么?  用模拟器运行时加密成功了.后来 把e_skf.c删除了,以及在几个文件中添加个别头文件后,armv7 和arm64编译通过了,但是运行时会在
cv = SM2_do_encrypt(EVP_sm3(), EVP_sm3(), (unsigned char *)message1, (size_t)strlen(message1), ec_key);
这里崩掉.拜托指导一下下么?🙏

**Comment by guanzhi** [comment]
SM2_do_encrypt传参数错误，请看sm2.h中的定义

**Comment by tongyu123** [comment]
哦哦,已经改了,因为这个是我几个月前做的,没注意方法传参都已经改了.这是我改过后,
NSString * message = dic[@"plainText"];
    NSString * eckey = dic[@"secretkey"];
    const char * pubkey = [eckey UTF8String];
    const char * message1 = [message UTF8String];
    
    EC_KEY *ec_key = EC_KEY_new();
    ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
    const EC_GROUP *ec_group = EC_KEY_get0_group(ec_key);
    BN_CTX *ctx1 = BN_CTX_new();
    EC_POINT * point1 = EC_POINT_hex2point(ec_group, pubkey, NULL, ctx1);
    ec_key -> pub_key = point1;
    
    SM2_CIPHERTEXT_VALUE *cv = NULL;
    SM2_ENC_PARAMS * params = NULL;
    cv = SM2_do_encrypt(params,(unsigned char *)message1, (size_t)strlen(message1), ec_key);
    OPENSSL_assert(cv);
    
那么这个paramas参数是什么意思啊?该传什么啊?因为没有注释,我也还不是太理解.传空进去会崩.

**Comment by tongyu123** [comment]
在SM2_do_encrypt方法中有用到
KDF_FUNC kdf = KDF_get_x9_63(params->kdf_md);
if (!kdf) {
		SM2err(SM2_F_SM2_DO_ENCRYPT, SM2_R_GET_KDF_FAILED);
		goto end;
}
所以这个params应该怎么取得传过去啊?我在GMSSL文件夹里面也没有找到生成或者初始化SM2_ENC_PARAMS的方法.

**Comment by tongyu123** [comment]
好了,解决了,用的5月份下载的GmSSL变异的静态库成功了.因为GmSSL有更新,方法传参,和方法内容有改动,我没发现,造成的崩溃.

**Comment by timgeo4ever** [comment]
@tongyu123 你好，我在当前的master版本下Mac平台编译爆出了一样的问题
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
请问您最终是怎么解决的呢？还有就是如何查看./Configure选项

**Comment by zhao1zhihui** [comment]
您好ios怎么代码生成公私钥
