### ISSUE TITLE
关于Openssl向Gmssl迁移

### ISSUE THREAD

**Issue by xtzxtz** [guanzhi/GmSSL#390]
现在发现Openssl向gmssl迁移时需要改几个配置文件，但是我现在不清楚需要改什么配置文件，求指教，顺便看了下wiki，发现wiki里的数据迁到官网之后之前有一篇迁移的文章消失了。

**Comment by guanzhi** [comment]
http://gmssl.org/docs/openssl-to-gmssl.html

**Comment by xtzxtz** [comment]
好的谢谢您，不知您研究过openvpn融合的方案没有

**Comment by guanzhi** [comment]
没有
