### ISSUE TITLE
想在php语言开发环境下进行sm2算法的验签，可否给出一个参考示例？谢谢

### ISSUE THREAD

**Issue by RubicPhil** [guanzhi/GmSSL#395]
由于在http://gmssl.org/docs/php-api.html页面，只有sm3、sm4的示例，所以不知道sm2算法的具体php代码该如何编写。希望sm2的php代码示例。谢谢！

**Comment by guanzhi** [comment]
SM2有可能需要对PHP的OpenSSL扩展进行少量修改

**Comment by RubicPhil** [comment]
关老师，请问该如何修改php的openssl扩展，您方便提供相应的文档吗？谢谢啦

**Comment by guanzhi** [comment]
需要修改一下PHP openssl_sign()这个函数的实现，或者直接从PHP中调用gmssl的命令行。

**Comment by RubicPhil** [comment]
谢谢您的解答
