### ISSUE TITLE
windows下编译GmSSL执行do_ms卡住

### ISSUE THREAD

**Issue by sinotitan** [guanzhi/GmSSL#4]
你好！

我试着编译GmSSL在windows下：
OS：win10 64位
编译成32位的动态库。
目前情况：
D:\src\GmSSL\guanzhi-GmSSL-cc31670>ms\do_ms

D:\src\GmSSL\guanzhi-GmSSL-cc31670>perl util\mkfiles.pl  1>MINFO

D:\src\GmSSL\guanzhi-GmSSL-cc31670>perl util\mk1mf.pl no-asm VC-WIN32  1>ms\nt.m
ak

D:\src\GmSSL\guanzhi-GmSSL-cc31670>perl util\mk1mf.pl dll no-asm VC-WIN32  1>ms\
ntdll.mak

D:\src\GmSSL\guanzhi-GmSSL-cc31670>if x == x goto skipce

D:\src\GmSSL\guanzhi-GmSSL-cc31670>perl -d util\mkdef.pl 32 libeay  1>ms\libeay3
2.def

然后就卡住了。

请问是什么问题？

**Comment by sinotitan** [comment]
调试了下mkdef.pl发现可能是938这里死循环了

**Comment by sinotitan** [comment]
今天上午又看了下，时候是添加的CPK算法信息有问题，卡住了

**Comment by guanzhi** [comment]
mkdef.pl文件中关于CPK算法的部分可能有问题，因为GmSSL仍在开发中，我们没有在Windows上做任何测试，建议你优先选择Mac作为试用环境。

**Comment by bjgxjob** [comment]
在编译时，忽略了CPK算法（如perl Configure no-cpk VC-WIN64A），还是会出现mkdef.pl卡死的问题。

**Comment by James1256** [comment]
哪位perl熟悉的调一下吧

**Comment by conezxy** [comment]
之前遇到过类似问题，如果do_ms.bat执行长时间无响应，则可能是include目录下的头文件中存在不规范的函数原型：

简单通过grep查了一下：grep -r "()" include/openssl/* | grep -v ":[ #//]"，在cpk.h中发现一个

> X509_ALGOR *CPK_MAP_new_default();

这里要改成
> X509_ALGOR *CPK_MAP_new_default(void);

没有在Windows环境上试过，不知道能否解决问题

**Comment by James1256** [comment]
@conezxy , 这两个定义有区别吗？应该都符合C标准的吧

**Comment by guanzhi** [comment]
非常感谢 @conezxy 发现这个问题！

**Comment by pp-qq** [comment]
@James1256  `void f()`表明`f`可以接收任意数量的参数,如:`f()`,`f(1)`,`f(1,2)`都行.`void f(void)`则指定`f`不能任何参数,只能`f()`.

**Comment by James1256** [comment]
函数改了后，应该不卡死了，但相关的文件都要改动过才能正确运行，并生成编译文件吧
