### ISSUE TITLE
签名验签速度极快

### ISSUE THREAD

**Issue by yeungtuzi** [guanzhi/GmSSL#403]
待签名文件在U盘上而且有700M之大，签名验签都是瞬间完成，这个速度很不正常啊

lf@ubuntu:/media/lf/OTO_INSTDSK/ota$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out skey.pem
lf@ubuntu:/media/lf/OTO_INSTDSK/ota$ gmssl pkey -pubout -in skey.pem -out vkey.pem
lf@ubuntu:/media/lf/OTO_INSTDSK/ota$ gmssl pkeyutl -sign -pkeyopt ec_scheme:sm2 -inkey skey.pem -in openthos_V1.0.zip -out openthos_V1.0.zip.gmsig
lf@ubuntu:/media/lf/OTO_INSTDSK/ota$ gmssl pkeyutl -verify -pkeyopt ec_scheme:sm2 -pubin -inkey vkey.pem -in openthos_V1.0.zip -sigfile openthos_V1.0.zip.gmsig 
Signature Verified Successfully
lf@ubuntu:/media/lf/OTO_INSTDSK/ota$ ls -l
total 1524064
-rw-r--r-- 1 lf lf 777190452 Dec 12 17:31 openthos_V1.0.zip
-rw-r--r-- 1 lf lf        71 Dec 13 00:50 openthos_V1.0.zip.gmsig
-rw-r--r-- 1 lf lf 778862413 Dec 12 09:46 openthos_V1.0.zip.gpg
-rw-r--r-- 1 lf lf       241 Dec 13 00:50 skey.pem
-rw-r--r-- 1 lf lf       178 Dec 13 00:50 vkey.pem

**Comment by yeungtuzi** [comment]
看到您已经修改了说明文档，这下没问题了。另外有个建议，如果用户未指定输出签名文件这个参数的话，默认在待签名文件同一目录下生成同名但是增加扩展名.sig的文件？

**Comment by guanzhi** [comment]
这种行为和gmssl的逻辑是矛盾的，gmssl不会提供类似的默认行为。
