### ISSUE TITLE
如何用密码+对称算法保护私钥？

### ISSUE THREAD

**Issue by yeungtuzi** [guanzhi/GmSSL#404]
输入以下命令后，进入等待用户输入状态，按回车仍然等待，任意输入字符比如safd再按回车，报错退出。

liufeng@dev:~/.gmssl$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out skey1.pem -sms4 -pass pass:mypassword

safd
genpkey: Error on line 3 of config file "<NULL>"

**Comment by guanzhi** [comment]
这个问题暂时不会修复，建议尝试用pkcs12来保护私钥
