### ISSUE TITLE
是否支持国密标准的数字信封？ 

### ISSUE THREAD

**Issue by zouyxdut** [guanzhi/GmSSL#405]

**Comment by guanzhi** [comment]
没试过，你参考命令 `pkcs7` 的手册页试一下，如果有问题后续我们会修复

**Comment by guanzhi** [comment]
参考 #408

**Comment by zouyxdut** [comment]
谢谢关老师。

我把PKCS#7的envelopedData的OID改成国密的之后，发现还有一处不同，就是国密数字信封的样例中有一个NUll对象，但是我自己生成的却没有，请问是什么原因？

图片见https://github.com/zouyxdut/envelopedData
