### ISSUE TITLE
iOS 如何使用

### ISSUE THREAD

**Issue by 907064772** [guanzhi/GmSSL#407]
rt:iOS如何使用这个库进行开发

**Comment by guanzhi** [comment]
首先把库文件编译出来，然后通过c/obj-c来调用这个库，这和在linux/windows环境下并没有任何不同。

**Comment by 907064772** [comment]
我现在已经编译出来了，请问是使用这些吗
include里的头文件和两个.a文件
![425c515b-3e55-47d5-9249-2724f5f2ea84](https://user-images.githubusercontent.com/17975707/34098570-bd1bc928-e417-11e7-88b7-b557a16ea335.png)

**Comment by mixuan** [comment]
http://blog.cocoachina.com/article/38141
