### ISSUE TITLE
sm2签名的pksc#7问题？

### ISSUE THREAD

**Issue by sysbling** [guanzhi/GmSSL#408]
请教一下调用PKCS7_sign(X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs,
BIO *data, int flags);函数，但是最后生成的签名结果的结构体oid是默认的1.2.840.113549.1.7.1，但是国密规定的签名数据类型的oid是1.2.156.10197.6.1.4.2.2，所以想问老师，这个要怎么弄？

**Comment by guanzhi** [comment]
鉴于GM/T 0010除了OID之外数据格式和PKCS#7都是一样的，有什么急迫性一定要替换不同的OID？

**Comment by sysbling** [comment]
嗯嗯，就是要求要按照GM/T 0010上面的规定来。

**Comment by guanzhi** [comment]
GmSSL会在后续的更新中增加对GM/T 0010的支持
