### ISSUE TITLE
使用GMSSL之前需要先安装Openssl吗,发现evp.h下面大量结构体被挪到crypto/evp_locl.h中了

### ISSUE THREAD

**Issue by kingdeviljin** [guanzhi/GmSSL#409]
使用GMSSL之前需要先安装Openssl吗,发现evp.h下面大量结构体被挪到crypto/evp_locl.h中了
evp_cipher_st
evp_cipher_ctx_st
evp_md_st ......
大量的结构体没有定义
请问应该怎么处理?

**Comment by kingdeviljin** [comment]
这个支持boost1.58吗?

**Comment by guanzhi** [comment]
不需要安装OpenSSL。
这些结构体不允许直接访问，这样未来升级后可以保证API的兼容。
部分值可以通过函数接口读取或设置。

**Comment by guanzhi** [comment]
GmSSL和Ubuntu默认的Boost库没有冲突，如果和某些具体版本有冲突，可以报一下

**Comment by kingdeviljin** [comment]
博士,还遇到了一些链接的问题
error LNK2019: unresolved external symbol _OPENSSL_init_crypto referenced
error LNK2019: unresolved external symbol _EVP_MD_CTX_reset referenced
error LNK2019: unresolved external symbol _EVP_CIPHER_CTX_reset referenced
请问博士这几个问题怎么处理?我看了下是在crypto/init.c中进行实现的

**Comment by kingdeviljin** [comment]
在手动编译的boost1.58 中engine.ipp提示

**Comment by guanzhi** [comment]
Boost 1.58 版本太老，升级至最新版本即可。
