### ISSUE TITLE
您好，关于国密ECDHE密钥交换/协商 算法，有几处我觉得描述不太正确，还望指教

### ISSUE THREAD

**Issue by mrpre** [guanzhi/GmSSL#41]
在GM/T 0024-2014中 国密定义了2个完全替换国际标准的加密套件：
ECDHE_SM4_SM3
ECC_SM4_SM3

我再源码中未能找到对两者的实现，仅找到对应的注释。
1：源码的注释：
/*s
 * ECDHE_XXX is the same as ECDHE_ECDSA_XXX in TLS
 * ECC_XXX and RSA_XXX is similar with ECDH_ECDSA_XXX, ECDH_RSA_XXX,
 *	except that the ServerKeyExchange format is not null.
 */

‘ ECDHE_XXX is the same as ECDHE_ECDSA_XXX in TLS’
的意思是说  国密ECDHE_XX 是和 标准ECDHE_ECDSA_xx 对于ECDHE流程是一样，但是 在GM/T 0024-2014 中 对国密ECDHE的描述却 和 标准的 ECDHE流程 不一样：

在GM/T 0024-2014 对ECDHE描述：
/********************************************************************************************/
enum {ECDHE, ECC, IBSDH...}
struct {
    select (KeyExchangeAlg) {
    case ECDHE:
             params
            digitally-signed struct {
                  clnt_random
                  srv_random
                   params;
            }
    case ECC:
            digitally-signed struct {
                  clnt_random
                  srv_random
                   cert;
            }
    }
}params;

服务器的密钥交换参数，当使用SM2算法时，交换的参数参见 GM/T 0009，其中服务器的公钥
不需要交换，客户端直接从服务器的加密证书中获取。
struct {
    curve_params
    point
}params;
如果使用SM2算法，第一个数不校验。
/********************************************************************************************/

从上面的描述来看，ECDHE_SM3_SM4算法所使用的ECDHE密钥协商流程 和 通用的ECDHE密钥协商流程是不一样的，
ECDHE_SM3_SM4它更像 ECDH算法，只是发送了server key exchange。
所以 我 认为 “ECDHE_XXX is the same as ECDHE_ECDSA_XXX in TLS”这句话不正确。

ECC_XXX算法我不是很了解。

忘指正。

**Comment by guanzhi** [comment]
国密SSL VPN标准不仅仅是定义了新的密码套件，而是定义了一个新的安全协议，虽然名称中包含SSL并且参考了TLS 1.1/1.2协议，却是一个完全不同的安全协议，并不完全适用于公共Web网站的HTTPS通信。
GmSSL优先支持标准TLS 1.1/1.2的国密证书和国密套件。

**Comment by mrpre** [comment]
我使用360浏览器访问 https://ebssec.boc.cn，抓包 发现其按照该协议进行访问的，至少其协议号为0x0101，并且使用了ECC_SM4_SM3加密套件。由此我个人觉得 SSL VPN 规范中的SSL协议 和 HTTPS访问中的SSL协议是一样的。
1：如果仅在标准TLS协议下支持国密证书，那么是否意味着客户端也需要自己开发？
2：还有请教一下，密码局 是否 有  ‘’在 标准 TLS 1.1/1.2 协议下使用国密算法 ‘’ 的规范？ 我暂时只有在SSL VPN规范中找到SSL协议相关规范。

**Comment by guanzhi** [comment]
0. 国密SSL VPN协议和TLS 1.1/1.2有很大差异，360和人行同时支持国密协议与国际协议
1. 需要用GmSSL替代OpenSSL重新编译客户端，可能涉及一些客户端的修改
2. 没有此类规范，且该规范的管理权在IETF这个国际标准组织，国密局无此权限

**Comment by mrpre** [comment]
多谢释疑。
最后还有一个疑惑点，也就是最初始的疑惑点：
1：
"ECC_XXX and RSA_XXX is similar with ECDH_ECDSA_XXX, ECDH_RSA_XXX,
except that the ServerKeyExchange format is not null"
这个对ECC_SMxx的解释，是从哪个规范得到的？我并没有找到对ECC的定义（SSL VPN规范中对其一笔带过，没有指出其和ECDH类似）

2：
”ECDHE_XXX is the same as ECDHE_ECDSA_XXX in TLS"
这是按照 标准ECDHE算法 理解的吧？（如果按照SSL VPN，那么应该是 same as ECDH）

**Comment by guanzhi** [comment]
1，2：TLS密码套件的详细工作流程在RFC中有明确的定义。如果对国密SSL中套件的工作方式不清楚，除了参考国密标准文本之外，可能还需要来自权威测试机构（如360浏览器的规范性是由上海格尔测试的）的更详细解读，不要参考GmSSL的内部注释。
3：你的理解是对的，是否支持国密SSL以及何时支持还要看是否有用户的实际需求。GmSSL会优先支持Apache, Nginx, Tomcat等常用服务器。

**Comment by conezxy** [comment]
国密规范里的ECC是指SM2公钥加密算法，也即SM2规范的第4部分。在TLS中找不到类似参照，只能说和RSA的公钥加密/私钥解密类似。

国密规范中的ECDHE是指SM2密钥交换算法，也即SM2规范的第3部分。实际要使用4对密钥完成计算：
1. 发起方加密私钥/公钥
2. 发起方临时私钥/公钥（在服务端构造ServerKeyExchange时产生）
3. 响应方加密私钥/公钥
4. 响应方临时私钥/公钥（在客户端构造ClientKeyExchange时产生）

而美标的ECDHE采用两对密钥（均为临时密钥）进行运算，因此国密的ECDHE也不能类比于TLS的ECDHE。

**Comment by ixp2xxx** [comment]
ECC_SM4_SM3可以理解为类似RSA密钥交换协议，只是使用SM2签名、验签，并使用SM2证书吗？
还是要参考"GM/T 0003 SM2椭圆曲线公钥密码算法-第-3-部分：密钥交换协议"去实现，这样的那就需要请求发送客户端证书。但360浏览器和boc服务器之间交换的时候并没有看到客户端证书哦。
请各位指点。谢谢！
