### ISSUE TITLE
GmSSL 若干问题请教？

### ISSUE THREAD

**Issue by CrazyProgrammer-dong** [guanzhi/GmSSL#410]
1：GmSSL是否已经支持了国密ssl协议，是否支持在ssl握手过程中使用ECDHE-SM4-SM3等加密套件和双证书？
2：如果已经支持了，那使用方式是怎么样的？是否有demo或文档说明？
3：目前我在使用Gmssl编写demo时，使用了GMTLS-method（void）方法，但是在建立TLS链接时报了错，错误如下：tls_contruct_client_hello:no ciphers available :ssl\statem\statem_clnt.c "894的错误。
这是否说明GMSSL不支持国密协议，还是别的什么原因？
4：请问下是否还有付费版的GMSSL？
上面问题虽有些罗嗦，但是我想这都是很多人的疑问，还恳请关博士有时间解答一下，十分感谢！

**Comment by guanzhi** [comment]
GMTLSv1.1协议 (即GM/T 0024 的国密SSL协议+双证书) 还在开发和测试中，因此目前调用相关接口会出错。GmSSL目前没有付费版，不过我们欢迎来自爱好者的watch、加星、fork，和来自商业用户的捐款、付费咨询和定制开发。
