### ISSUE TITLE
GMSSL安卓版本的编译

### ISSUE THREAD

**Issue by wangdongqqqq** [guanzhi/GmSSL#411]
您好,我想编译一个安卓的版本，有相关的操作步骤吗？谢谢。

**Comment by guanzhi** [comment]
请参考OpenSSL的最近Android编译文档，GmSSL不需要特殊的设置。

**Comment by guanzhi** [comment]
请参考 http://gmssl.org/docs/install.html 其中有Android编译的详细说明

**Comment by javake** [comment]
http://gmssl.org/docs/install.html 这里对 Android编译太不友好了，真心不会玩。
