### ISSUE TITLE
自定义库名称

### ISSUE THREAD

**Issue by vanloswang** [guanzhi/GmSSL#412]
默认，GmSSL编译出来的动态库命令与OpenSSL库名称一样，如果定制编译的GmSSL库命令，比如调整为libgmssl.so、libgmcrypto.so？

**Comment by guanzhi** [comment]
因为GmSSL的库就是一个增加了国密算法的OpenSSL库，因此不会修改库的名字和头文件的名字，例如将`include/openssl/`移至`include/gmssl/`，或者将`libcrypto`改为`libgmcrypto`。

**Comment by solomondong** [comment]
me too

**Comment by wuliang142857** [comment]
昨天尝试了一下，成功修改了输出的头文件名和库名，参考我Fork的仓库：[https://github.com/wuliang142857/GmSSL](https://github.com/wuliang142857/GmSSL)

大致描述修改的点有：
 - 修改`include/openssl` 为 `include/gmssl`，以便输出的头文件名是`gmssl`
 - 替换所有的`openssl/`和`include/openssl/`，
 - 修改`./util/mkdef.pl`文件中的`get_openssl_version()`函数，将
 
````perl
my $fn = catfile($config{sourcedir},"include","openssl","opensslv.h")
````

修改为：

````perl
my $fn = catfile($config{sourcedir},"include","gmssl","opensslv.h")
````

经过上述修改后，输出的头文件目录已经从`openssl` 变为了 `gmssl`。

库名的修改略微曲折一点：

 - 先批量替换`libssl`、`libcrypto`为`libgmssl`和`libgmcrypto`
 - 然后将 `libgmssl.num` 和 `libcrypto.num` 全部都改回成 `libssl.num`、`libcrypto.num`
 - 修改`./util/mkdef.pl`文件中的第177行，修改内容如下：

原内容：

````perl
$do_ssl=1 if $_ eq "libssl";
if ($_ eq "ssl") {
    $do_ssl=1; 
    $libname=$_
}
$do_crypto=1 if $_ eq "libcrypto";
if ($_ eq "crypto") {
    $do_crypto=1;
    $libname=$_;
}
````

修改为：

````perl
$do_ssl=1 if $_ eq "libgmssl";
if ($_ eq "gmssl") {
    $do_ssl=1; 
    $libname=$_
}
$do_crypto=1 if $_ eq "libgmcrypto";
if ($_ eq "gmcrypto") {
    $do_crypto=1;
    $libname=$_;
}
````

经过这样修改，输出的库名就分别改成了 `libgmssl.so` 和 `libgmcrypto.so`
