### ISSUE TITLE
我下载了最新的GMSSL-2.0,在window7 64位上编译报以下的错误？

### ISSUE THREAD

**Issue by whbwyj** [guanzhi/GmSSL#416]
include\openssl/lhash.h(198) : warning C4090: 'function' : different 'const' qua
lifiers
include\openssl/lhash.h(198) : warning C4022: 'OPENSSL_LH_insert' : pointer mismatch for actual parameter 2
crypto\bio\bio_lcl.h(144) : error C2061: syntax error : identifier 'BIO_ADDR_sockaddr_size'
crypto\bio\bio_lcl.h(144) : error C2059: syntax error : ';'
crypto\bio\bio_lcl.h(144) : error C2059: syntax error : 'type'
crypto\bio\bio_lcl.h(145) : error C2061: syntax error : identifier 'BIO_ADDRINFO
_sockaddr_size'
crypto\bio\bio_lcl.h(145) : error C2059: syntax error : ';'
crypto\bio\bio_lcl.h(145) : error C2059: syntax error : 'type'
crypto\bio\b_addr.c(137) : error C2027: use of undefined type 'in6_addr'
        crypto\bio\b_addr.c(137) : see declaration of 'in6_addr'
crypto\bio\b_addr.c(142) : error C2115: '=' : incompatible types
crypto\bio\b_addr.c(344) : error C2061: syntax error : identifier 'BIO_ADDR_sock
addr_size'
crypto\bio\b_addr.c(344) : error C2059: syntax error : ';'
crypto\bio\b_addr.c(344) : error C2059: syntax error : 'type'
crypto\bio\b_addr.c(413) : error C2061: syntax error : identifier 'BIO_ADDRINFO_
sockaddr_size'
crypto\bio\b_addr.c(413) : error C2059: syntax error : ';'
crypto\bio\b_addr.c(413) : error C2059: syntax error : 'type'
crypto\bio\b_addr.c(825) : warning C4244: 'function' : conversion from 'long ' t
o 'unsigned short ', possible loss of data
NMAKE : fatal error U1077: 'cl' : return code '0x2'

**Comment by guanzhi** [comment]
Windows编译问题请发在 #399
