### ISSUE TITLE
SM2加密密文的格式如何设定为C1C2C3？

### ISSUE THREAD

**Issue by boguang** [guanzhi/GmSSL#417]
老师您好，通过函数SM2_encrypt、SM2_decrypt，可以顺利进行SM2的加密解密，经过验证密文格式为C1C3C2，请问如何能够得到C1C2C3类型的密文呢？

iRet = SM2_encrypt(NID_sm3,  inbuf, inlen, outbuf, &outlen, ec_key);
iRet = SM2_decrypt(NID_sm3, inbuf, inlen,  outbuf, &outlen, ec_key);

**Comment by guanzhi** [comment]
1. 正式的标准中要求SM2密文按C1,C3,C2的顺序排列，一种可能的原因是SDF/SKF接口中的SM2密文序列化几乎就是SM2 struct的直接输出，因此只能将变长的C2放在最后。
2. 你可以采用`ECIES_CIPHERTEXT_VALUE`来存储SM2的密文，`ECIES_CIPHERTEXT_VALUE`按照C1,C2,C3的方式排列，并且C1支持椭圆曲线点压缩，空间效率更好。
3. 具体操作上先调用`SM2CiphertextValue_get_ECCCipher`将`SM2CiphertextValue`转化为`ECCCipher`，然后调用`ECIES_CIPHERTEXT_VALUE_new_from_ECCCipher`将密文转化为`ECIES_CIPHERTEXT_VALUE`

**Comment by boguang** [comment]
非常感谢老师，由于密文与上层要进行转储后通信，所以修改如下（勉强可以实现）
int SM2_encrypt(int type, const unsigned char *in, size_t inlen,
	unsigned char *out, size_t *outlen, EC_KEY *ec_key)
{
	int ret = 0;
	SM2CiphertextValue *cv = NULL;
	size_t sumlen;
	const char *sumbuf;
	const EVP_MD *md;
	int len;

	if (!(md = EVP_get_digestbynid(type))) {
		SM2err(SM2_F_SM2_ENCRYPT, SM2_R_INVALID_DIGEST_ALGOR);
		return 0;
	}

	if (!(cv = SM2_do_sgcc_encrypt(md, in, inlen, ec_key))) {
		SM2err(SM2_F_SM2_ENCRYPT, SM2_R_ENCRYPT_FAILURE);
		goto end;
	}

	if (!out) {
		*outlen = i2d_SM2CiphertextValue(cv, NULL);
		ret = 1;
	} else if (*outlen < i2d_SM2CiphertextValue(cv, NULL)) {
		SM2err(SM2_F_SM2_ENCRYPT, SM2_R_BUFFER_TOO_SMALL);
		ret = 0;
	} else {
		char *xHex = BN_bn2hex(cv->xCoordinate);
		char *yHex = BN_bn2hex(cv->yCoordinate);
		char *MHex = (char *) malloc(ASN1_STRING_length(cv->hash)*2 + 1);
		memset(MHex, 0, ASN1_STRING_length(cv->hash)*2 + 1);
		char *LHex = (char *) malloc(ASN1_STRING_length(cv->ciphertext)*2 + 1);
		memset(LHex, 0, ASN1_STRING_length(cv->ciphertext)*2 + 1);
		sm2_bin2hex(cv->hash->data, MHex, ASN1_STRING_length(cv->hash));
		sm2_bin2hex(cv->ciphertext->data, LHex, ASN1_STRING_length(cv->ciphertext));

		size_t sumlen = 64 + 64 + 64+strlen(LHex)+2;
		char *sumbuf = (char *) malloc(sumlen + 1);
    		memset(sumbuf, 0, sumlen + 1);
		strcpy(sumbuf,"04");
		int xZero;
		for(xZero = 0; xZero < (64-strlen(xHex)); xZero++) {
			strcat(sumbuf,"0");
		}
  		strcat(sumbuf,xHex);
		int yZero;
		for(yZero = 0; yZero < (64-strlen(yHex)); yZero++) {
			strcat(sumbuf,"0");
		}
		strcat(sumbuf,yHex);
		strcat(sumbuf,LHex);
		strcat(sumbuf,MHex);

		size_t outlen_ = sm2_hex2bin(out,sumbuf);
		*outlen = outlen_;
		//len = i2d_SM2CiphertextValue(cv, &out);
		//*outlen = len;
		ret = 1;
	}

end:
	SM2CiphertextValue_free(cv);
	return ret;
}

**Comment by SecureEngineer** [comment]
我对这个C1C3C2的理解是，在工程实现中进行内存管理时，将变长的数据放在最后面更有利于内存管理。所以在国密后续的标准中都采用这种格式实现。描述的不知是否准确，请谅解。

**Comment by guanzhi** [comment]
从逻辑上说还是C3放在最后比较好，ECIES密文即是将C3放在最后。不过既然目前的标准是这么规定的，`SM2CiphertextValue`也按这个顺序存储。

**Comment by itollei** [comment]
@boguang 楼主您好，请问您将密文转换成04开头格式的完整代码能否发一下？邮箱地址：445826953@qq.com,包括加解密的,非常感谢！！
