### ISSUE TITLE
sm2签名的参数ID是什么？

### ISSUE THREAD

**Issue by mrpre** [guanzhi/GmSSL#42]
老师你好，问一下，SSL握手流程中， 使用非 IBC 时，服务器sign操作需要字符串ID，请问ID应该填什么？TLS中没有ID相关的参照。不可能随便填吧？用户为客户端verify时也需要ID，如果服务器随便填，则verify肯定失败啊。

**Comment by mrpre** [comment]
找到了："SM2数字签名方案中被签名的杂凑值不仅仅是消息的杂凑值，而是签名者身份信息串联上消息的杂凑值，其中签名者身份信息是签名者的可辨别标识字串、椭圆曲线方程系数、生成元和签名者公钥串联后字串的杂凑值。SM2标准中并未说明签名者的可辨别标识字串格式及获得方式，应用可以采用X.509证书中的Subject字段、CN (CommonName)或自行规定。"

**Comment by guanzhi** [comment]
GmSSL中默认ID字符串为16个字节的ASCII字符串`anonym@gmssl.org`，不包含末尾的0。国密标准文本中对默认值应该做了规定，可能是`1234567812345678`，准确值还需购买并参考标准文本。

**Comment by conezxy** [comment]
按照GM/T 0009-2012《SM2算法使用规范》最后一章节的定义。无特殊约定时采用1234567812345678的值。

国密SM2根CA和国密SSLVPN协议均采用此默认值。

建议在需要不同厂商互通的场合中采用该值。

-
掌晓愚

在 2016年8月29日，20:11，Zhi Guan <notifications@github.com<mailto:notifications@github.com>> 写道：


GmSSL中默认ID字符串为16个字节的ASCII字符串anonym@gmssl.org<mailto:anonym@gmssl.org>，不包含末尾的0。国密标准文本中对默认值应该做了规定，可能是1234567812345678，准确值还需购买并参考标准文本。

―

**Comment by mrpre** [comment]
@conezxy @guanzhi  各位老师好，我看规范，在计算签名时，需要id+公钥+..等首先计算哈希值Za。然后再使用私钥进行签名。
那么在ECC流程中，即发送server key exchange 时我们需要签名，此时服务器端可以计算一个临时密钥对（即K 和 KG），使用KG进行哈希，使用K进行签名。但是server key exchange 本身并不会把自己计算的公钥发送给客户端，这意味着，客户端verify时，无法得到Za，即不能验证。

我是不是可以这么理解，ECC_SMxxx加密套件时，不生成临时密钥对，直接使用签名证书中的Point当做公钥KG、签名证书对应的私钥为K。这样客户端就能从证书中获取到KG？若非如此，那么客户端如何获取公钥？

**Comment by Jkinglyf** [comment]
@mrpre 对于ECC序列加密套件，发送”server key exchange “时，利用签名证书对“双方随机数 + 加密证书”进行签名即可。不需要临时密钥对。

           对于 ECDHE序列加密套件，发送”server key exchange “时，需要临时密钥对，用于交换双方的曲线参数。
