### ISSUE TITLE
Clash between crypto/objects/objects.txt and documented OIDs

### ISSUE THREAD

**Issue by levitte** [guanzhi/GmSSL#425]
Just want to point out that there's a clash, visible already in your [OIDs documentation](http://gmssl.org/docs/oid.html)

1.  your translation of GM/T 0006-2012 says

        1.2.156.10197.1.504 | RSA Signing with SM3

    your `crypto/objects/objects.txt` says:

        1.2.156.10197.1.504 SM2Sign-with-SHA511

2.  your translation of GM/T 0006-2012 says

        1.2.156.10197.1.201 | ZUC Stream Cipher

    your `crypto/objects/objects.txt` says:

        1.2.156.10197.1.800 ZUC

**Comment by guanzhi** [comment]
I will check the official documents and fix this problem.
