### ISSUE TITLE
when to release the version of 2.x branch

### ISSUE THREAD

**Issue by vanloswang** [guanzhi/GmSSL#426]
Is there a roadmap or planning of the release version of 2.x branch? Is it stable already?

**Comment by guanzhi** [comment]
The most recent official supported features are listed in the **Release** descriptions. These features are stable. The features not listed can be seen as a reference to the roadmap. As we do not provide any bug fixes for the Released versions, you should always use the master branch.

**Comment by vanloswang** [comment]
@guanzhi 3QU~
