### ISSUE TITLE
谁用命令编译GMSSL时出现一下错误

### ISSUE THREAD

**Issue by whbwyj** [guanzhi/GmSSL#428]
dllmain.c
	"C:\Perl\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1.def
	"C:\Perl\bin\perl.exe" -i.tmp -pe "s|^LIBRARY\s+crypto32|LIBRARY libcrypto-1_1|;" libcrypto-1_1.def
	DEL libcrypto-1_1.def.tmp
	"C:\Perl\bin\perl.exe" "util\mkrc.pl" libcrypto-1_1.dll > libcrypto-1_1.rc
	rc /folibcrypto-1_1.res libcrypto-1_1.rc
Microsoft (R) Windows (R) Resource Compiler Version 6.1.7600.16385

Copyright (C) Microsoft Corporation.  All rights reserved.

	IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
	link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\whb\AppData\Local\Temp\nmA150.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 ASN1_STRING_data
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BIO_accept
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BIO_get_accept_socket
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BIO_get_host_ip
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BIO_get_port
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BIO_gethostbyname
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_generate_prime
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_get_params
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_init
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_is_prime
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_is_prime_fasttest
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 BN_set_params
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 CRYPTO_num_locks
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 DH_generate_parameters
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 DSA_generate_parameters
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 ERR_remove_state
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 ERR_remove_thread_state
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 HMAC_Init
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 OPENSSL_config
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 PKCS12_get_attr
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 RAND_event
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 RAND_pseudo_bytes
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 RAND_screen
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 RSA_generate_key
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 SRP_VBASE_get_by_user
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 X509_CRL_get_lastUpdate
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 X509_CRL_get_nextUpdate
libcrypto.lib : fatal error LNK1120: 27 个无法解析的外部命令

**Comment by guanzhi** [comment]
重新下载并编译可能解决这个问题。
产生的原因是库中只编译了1.1.0 API的函数，没有包含上述已经废弃的符号。

**Comment by muyu1944** [comment]
这个问题还有人遇到并解决了吗？我下载了最新的代码依然是这个错，之前1.3版的时候是能编译过的

**Comment by whbwyj** [comment]
找到相关的源码，删除对于对应函数的宏就行！


whb7807810@126.com
 
发件人： muyu1944
发送时间： 2018-01-19 14:51
收件人： guanzhi/GmSSL
抄送： whbwyj; Author
主题： Re: [guanzhi/GmSSL] 谁用命令编译GMSSL时出现一下错误 (#428)
这个问题还有人遇到并解决了吗？我下载了最新的代码依然是这个错，之前1.3版的时候是能编译过的

**Comment by muyu1944** [comment]
@whbwyj 
函数太多删除起来容易出现纰漏和对整体框架造成影响，看了一下1.1.0的change，编译的时候加上no-deprecated即可不编译1.1.0废弃的函数，这样只需要处理BN_init和CRYPTO_num_locks就很简单了。
CRYPTO_num_locks无论如何都会定义一个，可以注释掉，BN_init虽然注释掉就能编译通过，但是它的声明建立在OPENSSL_API_COMPAT < 0x10100000L条件下，不知道为什么会被声明出来

**Comment by whbwyj** [comment]
好的，一会我试试你的方法。



whb7807810@126.com
 
发件人： muyu1944
发送时间： 2018-01-19 16:20
收件人： guanzhi/GmSSL
抄送： whbwyj; Mention
主题： Re: [guanzhi/GmSSL] 谁用命令编译GMSSL时出现一下错误 (#428)
@whbwyj
函数太多删除起来容易出现纰漏和对整体框架造成影响，看了一下1.1.0的change，编译的时候加上no-deprecated即可不编译1.1.0废弃的函数，这样只需要处理BN_init和CRYPTO_num_locks就很简单了。
CRYPTO_num_locks无论如何都会定义一个，可以注释掉，BN_init虽然注释掉就能编译通过，但是它的声明建立在OPENSSL_API_COMPAT < 0x10100000L条件下，不知道为什么会被声明出来

**Comment by DuGuNiuEr** [comment]
@muyu1944 @whbwyj
你好，BN_init和CRYPTO_num_locks 这两个注释掉还是出错，你是怎么处理的？

**Comment by whbwyj** [comment]
我没有注释函数，只是注释一个宏！



whb7807810@126.com
 
发件人： DuGuNiuEr
发送时间： 2018-01-26 14:03
收件人： guanzhi/GmSSL
抄送： whbwyj; Mention
主题： Re: [guanzhi/GmSSL] 谁用命令编译GMSSL时出现一下错误 (#428)
@muyu1944 @whbwyj
你好，BN_init和CRYPTO_num_locks 这两个注释掉还是出错，你是怎么处理的？

**Comment by muyu1944** [comment]
@DuGuNiuEr 
特意下了最新的master包又编译了一遍，没问题，在bn.h和crypto.h里注释掉那两个函数的声明就可以
