### ISSUE TITLE
libgmssljni.so是如何编译出来的？

### ISSUE THREAD

**Issue by athank2222** [guanzhi/GmSSL#429]

**Comment by guanzhi** [comment]
libgmssljni.so 就是由`java/GmSSL.c`编译的一个普通的 `-fPIC` 动态库，是GmSSL libcryptod的JNI封装，在之前有几个commit中对java的编译是由`./config; make`自动完成的，但是只支持OS X，因此在最近的commits中默认编译从config中移除了。

**Comment by duyangs** [comment]
直接在终端或cmd执行  java/GmSSL.c 吗
