### ISSUE TITLE
关于gmssl官网上申请个人证书的问题

### ISSUE THREAD

**Issue by bochs9** [guanzhi/GmSSL#430]
激活连接点开后，不知道如何使用，只能看到根证书和撤销列表
是不是还没有完成呀，我想搞个个人的国密证书(根证书签名)，请问下如何申请呢@guanzhi

**Comment by guanzhi** [comment]
我们在今年提供两个免费的测试用证书服务，一个mailca可以通过邮件地址来申请客户端证书（界面尚未开发完成）；一个webca可以用于申请Web服务器DV证书（已经基本测试通过）。稍后会将文档提供出来，如果您拥有一个申请了域名的服务器，可以测试GmSSL的DV证书。

在测试阶段两个测试CA均部署在阿里云上，因此无法保证安全可信，只能用于测试！

**Comment by 27954741** [comment]
请问关老师,webca申请服务器端的DV证书啥时候可以使用
