### ISSUE TITLE
关于 o2i_SM2CiphertextValue 函数处理方式

### ISSUE THREAD

**Issue by kinrong** [guanzhi/GmSSL#431]
老师您好！
SM2_encrypt / SM2_decrypt密文进行了ASN.1编码，现实中应用直接用C1C3C2格式，因此改用SM2_do_encrypt / SM2_do_decrypt函数，与这两个函数配套的就是 i2o_SM2CiphertextValue / o2i_SM2CiphertextValue.
SM2加密是正常的：
......
unsigned char cipBuf[1024];
........
    pOut = cipBuf;
     cv = SM2_do_encrypt(EVP_sm3(), chrIn, nInLen, ecKey);
     if(cv){    
        nOutLen = i2o_SM2CiphertextValue(EC_KEY_get0_group(ecKey), cv, &pOut);
        SM2CiphertextValue_free(cv);
     }
........

但是加密结果去解密就出问题了
........
   pIn = cipBuf;
   nInLen = nOutLen;
   cv = o2i_SM2CiphertextValue(EC_KEY_get0_group(ecKey),	EVP_sm3(), NULL, &pIn, nInLen);
   if(cv){
        SM2_do_decrypt(EVP_sm3(), cv, chrOut, &nOutLen, ecKey);
        SM2CiphertextValue_free(cv);
   }
.......
程序执行到 SM2_do_decrypt 就异常终止，在调用o2i_SM2CiphertextValue后直接调用i2o_SM2CiphertextValue也是异常终止。
问题很可能是出在o2i_SM2CiphertextValue函数上，大致看了一下crypto/sm2/sm2_oct.c，发现它是按照C1C2C3次序将数据填充到SM2CiphertextValue结构里，这个流程是不是要改一下？

另外，在SM2接触到的公钥，都是64字节(x,y)，但在gmssl相关函数中，公钥是65字节，首字节都是0x04（非压缩模式？），都需要单独处理一下，这个是不是为了与其它 EC 接口保持一致？

**Comment by kinrong** [comment]
o2i_SM2CiphertextValue函数问题不是出在C1C2C3次序上，是出在函数结尾的 SM2CiphertextValue_free(cv)， SM2CiphertextValue结构被释放了，故造成进程异常终止。

**Comment by zylthinking** [comment]
这个确实是你们的bug
问题出在 
SM2CiphertextValue *o2i_SM2CiphertextValue(const EC_GROUP *group,
	const EVP_MD *md, SM2CiphertextValue **pout,
	const unsigned char **pin, long len)
{
	..............................
        ret = cv;
end:
	SM2CiphertextValue_free(cv);
...........................
	return ret;
}

SM2CiphertextValue_free(cv); 这行不应该存在, 就算是 pout 不为 NULL, 释放也应该是调用者的责任; 更何况如果 pout == NULL 时,  ret 和 cv 指向同一块内存; 返回的压根就是已经释放的内存

**Comment by daisutao** [comment]
问题有人提出了，也没有理会.......
我同样也发现了这个问题。唉。
