### ISSUE TITLE
gmssl怎样从p12文件中提取证书和私钥？

### ISSUE THREAD

**Issue by sine2018** [guanzhi/GmSSL#432]
gmssl怎样从p12文件中提取证书和私钥？
用命令行怎样提取，用程序怎样提取，谢谢！

**Comment by guanzhi** [comment]
请参考`man pkcs12`

**Comment by sine2018** [comment]
收到！谢谢

2018-01-24 

qvb_118 



发件人：Zhi Guan <notifications@github.com>
发送时间：2018-01-24 20:25
主题：Re: [guanzhi/GmSSL] gmssl怎样从p12文件中提取证书和私钥？ (#432)
收件人："guanzhi/GmSSL"<GmSSL@noreply.github.com>
抄送："sine2018"<qvb_118@163.com>,"Author"<author@noreply.github.com>

请参考man pkcs12

**Comment by wuyezhong** [comment]
@sine2018 请问你是怎样读取的？程序读取和命令行。
我读的时候说私钥解码失败
