### ISSUE TITLE
版本计划及是否支持GM/T 0024-2014或者有相应版本规划

### ISSUE THREAD

**Issue by liclicli** [guanzhi/GmSSL#433]
关老师（or 其它贡献者），您好：
请问
1. 目前GMSSL的版本规划在哪可以查看？我再issues中看到GM/T 0024-2014的支持在当时似乎未加入版本规划中，是否近期有相应规划？
2. 使用360国密浏览器是否可以访问用GMSSL编写的服务器端，是否有demo?

**Comment by guanzhi** [comment]
1. 这个协议的一个套件已经初步测试通过了，但是要保证不影响其他功能还有一些整理工作要做，主要的代码并未更新到主分支中。另：实际上我个人不太喜欢这个协议，也不建议用户真的用它。
2. 没有和360测过。一位成员正在做Chromium和GmSSL的集成，节后可能会有一个初步的用于测试的版本。
