### ISSUE TITLE
SMS4使用EVP方式，解密失败EVP_CipherFinal_ex返回0（使用同等密钥长度的aes和des就没问题）

### ISSUE THREAD

**Issue by zhanghuiquan** [guanzhi/GmSSL#435]
你好，
在调用该加密后，再调用该函数解密，解密失败。解密出来的是乱码。使用其它同等密钥长度的aes或者des就没问题，麻烦能帮忙看一下吗？还是说sm4算法还没完全整合到EVP?

int sm4_do_crypt_file(FILE *in, FILE *out, unsigned char *key, unsigned char *iv, int enc)
{
	unsigned char inbuf[1024];
	unsigned char outbuf[1024 + EVP_MAX_BLOCK_LENGTH];
	int inlen, outlen;
	int ret;

	EVP_CIPHER_CTX *ctx = NULL;

	if (!(ctx = EVP_CIPHER_CTX_new()))
	{
		ret = -1;
		goto end;
	}

	EVP_CIPHER_CTX_init(ctx);

	if (1 != EVP_CipherInit_ex(ctx, EVP_sms4_cbc(), NULL, key, iv, enc))
	{
		printf("evp init failed.\r\n");
		goto end;
	}

	fseek(in, 0, SEEK_SET);
	fseek(out, 0, SEEK_SET);
	while (1)
	{
		inlen = fread(inbuf, 1, 1024, in);
		if (inlen <= 0) break;
		if (!EVP_CipherUpdate(ctx, outbuf, &outlen, inbuf, inlen))
		{
			ret = -2;
			goto end;
		}
		fwrite(outbuf, 1, outlen, out);
	}

	if (!EVP_CipherFinal_ex(ctx, outbuf, &outlen))
	{
		ret = -3;
		goto end;
	}

	fwrite(outbuf, 1, outlen, out);
	ret = 0;
end:
	/* Clean up */
	EVP_CIPHER_CTX_cleanup(ctx);
	if (NULL != ctx) EVP_CIPHER_CTX_free(ctx);

	return ret;
}

**Comment by zhaoxiaomeng** [comment]
解密程序是怎样的呢？

**Comment by zhaoxiaomeng** [comment]
我们确认一下。

**Comment by zhaoxiaomeng** [comment]
我这边使用如下的代码可以测试通过。
```
#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>
int main()
{

    unsigned char key[32] = {1};
    unsigned char iv[16] = {0};
    unsigned char *inStr = "this is test string";
    int inLen = strlen(inStr);
    int encLen = 0;
    int outlen = 0;
    unsigned char encData[1024];

    printf("source: %s\n",inStr);

    EVP_CIPHER_CTX *ctx;
    ctx = EVP_CIPHER_CTX_new();
    //Encrypt
    EVP_CipherInit_ex(ctx, EVP_sms4_cbc(), NULL, key, iv, 1);
    EVP_CipherUpdate(ctx, encData, &outlen, inStr, inLen);
    encLen = outlen;
    EVP_CipherFinal(ctx, encData+outlen, &outlen);
    encLen += outlen;
    EVP_CIPHER_CTX_free(ctx);

    //Decrypt
    int decLen = 0;
    outlen = 0;
    unsigned char decData[1024];
    EVP_CIPHER_CTX *ctx2;
    ctx2 = EVP_CIPHER_CTX_new();
    EVP_CipherInit_ex(ctx2, EVP_sms4_cbc(), NULL, key, iv, 0);
    EVP_CipherUpdate(ctx2, decData, &outlen, encData, encLen);
    decLen = outlen;
    EVP_CipherFinal(ctx2, decData+outlen, &outlen);
    decLen += outlen;
    EVP_CIPHER_CTX_free(ctx2);

    decData[decLen] = '\0';
    printf("decrypt: %s\n",decData);
}

```

**Comment by zhanghuiquan** [comment]
首先谢谢你们的回复。
挺有意思的，我在Microsoft Visual Studio Community 2017版本上直接copy你提供的代码，结果打印的是乱码。我在写一个简单的国密签名软件，使用sm2和sm3都没问题，就sm4出了状况。lib是我自己编译的，我现在重新检查一下自己的编译环境，后续有发现再回复。再次感谢你们的无私付出，谢谢。

**Comment by zhanghuiquan** [comment]
我重新从你们官网上下载打包好的代码重新编译，而不是从github克隆，发现sms4运行正常了。

**Comment by zhaoxiaomeng** [comment]
最新的 master 版本一直会有新的特性加入，并不是稳定版本。如果需要在生产环境使用的话，建议使用release 版本。

**Comment by lmxeq5** [comment]
每Update一次outbuf都必须后移outlen个字节
