### ISSUE TITLE
关于随机数检测，是否考虑修改测试用例以符合国密要求？

### ISSUE THREAD

**Issue by zhanghuiquan** [guanzhi/GmSSL#436]
在产品国密认证中，随机数检测是比较核心的一部分，看了一下，gmssl随机数测试代码仍旧沿用FIPS 140-1的标准进行测试，有没有可能对这些测试用例进行修改，以符合国密的要求呢？

**Comment by guanzhi** [comment]
国密产品认证中对随机数检测有哪些具体的要求？

**Comment by conezxy** [comment]
主要是根据 GM/T 0005-2012随机性检测规范

实际的检测项和 Dicelock 的实现基本对应

http://www.dicelocksecurity.com/

-
掌晓愚

在 2018年3月14日，21:40，Zhi Guan <notifications@github.com<mailto:notifications@github.com>> 写道：


国密产品认证中对随机数检测有哪些具体的要求？

**Comment by GaelClichy** [comment]
国密检测规范借鉴的是NIST的标准吧，实际操作起来感觉略微偏强，不错的随机数源亦有一定概率通不过

**Comment by loveadmire** [comment]
国密监测，要求随机数为真随机，通过在ssl握手过程中采集hello消息中的随机数，采集数据，按照规范进行验证随机数的随机性，软件实现，感觉难度会比较大
