### ISSUE TITLE
sm2 曲线哪个是正确的

### ISSUE THREAD

**Issue by zylthinking** [guanzhi/GmSSL#438]
经测试,  ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1); 获得的曲线参数与测试程序代码
EC_GROUP* sm2p256test = new_ec_group(1,
        "8542D69E4C044F18E8B92435BF6FF7DE457283915C45517D722EDB8B08F1DFC3",
        "787968B4FA32C3FD2417842E73BBFEFF2F3C848B6831D7E0EC65228B3937E498",
        "63E4C6D3B23B0C849CF84241484BFE48F61D59A5B16BA06E6E12D1DA27C5249A",
        "421DEBD61B62EAB6746434EBC3CC315E32220B3BADD50BDC4C4E6C147FEDD43D",
        "0680512BCBB42C07D47349D2153B70C4E5D7FDFCBFA36EA1A85841B9E46E09A2",
        "8542D69E4C044F18E8B92435BF6FF7DD297720630485628D5AE74EE7C32E79B7",
        "1"
    );
获得的曲线不同

不知哪个是正确的sm2曲线

**Comment by zhenyuwei** [comment]
0003.5-2012里面的定义了曲线参数，你写的的这个是0003.3-2012里面给的一个验证示例

**Comment by zylthinking** [comment]
抱歉还是不明白是什么意思, 你是说 
EC_GROUP* sm2p256test = new_ec_group(1,
"8542D69E4C044F18E8B92435BF6FF7DE457283915C45517D722EDB8B08F1DFC3",
"787968B4FA32C3FD2417842E73BBFEFF2F3C848B6831D7E0EC65228B3937E498",
"63E4C6D3B23B0C849CF84241484BFE48F61D59A5B16BA06E6E12D1DA27C5249A",
"421DEBD61B62EAB6746434EBC3CC315E32220B3BADD50BDC4C4E6C147FEDD43D",
"0680512BCBB42C07D47349D2153B70C4E5D7FDFCBFA36EA1A85841B9E46E09A2",
"8542D69E4C044F18E8B92435BF6FF7DD297720630485628D5AE74EE7C32E79B7",
"1"
);
是正确的,

而   ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);  里面的参数是不正确的sm2 曲线?

**Comment by zhenyuwei** [comment]
"8542D69E4C044F18E8B92435BF6FF7DE457283915C45517D722EDB8B08F1DFC3",
"787968B4FA32C3FD2417842E73BBFEFF2F3C848B6831D7E0EC65228B3937E498",
"63E4C6D3B23B0C849CF84241484BFE48F61D59A5B16BA06E6E12D1DA27C5249A",
"421DEBD61B62EAB6746434EBC3CC315E32220B3BADD50BDC4C4E6C147FEDD43D",
"0680512BCBB42C07D47349D2153B70C4E5D7FDFCBFA36EA1A85841B9E46E09A2",
"8542D69E4C044F18E8B92435BF6FF7DD297720630485628D5AE74EE7C32E79B7",
这个曲线是《GM/T 0003.3-2012》里面给的一个验证示例，《GM/T 0003.5-2012》里面定义了曲线参数，那个曲线是你真正使用的。你看一下国标文档吧，里面有说明的。
