### ISSUE TITLE
gmssl库能和openssl库同时使用吗？

### ISSUE THREAD

**Issue by wupeili1024** [guanzhi/GmSSL#441]
小弟不才，毕设需要用到sm2算法。通过gmssl实现的sm2能与java的bouncycastle互通。但是需要将sm2的实现部分加到以前用到openssl老项目上。
尝试过用gmssl库代替openssl库，但是会报错，主要问题是openssl很多头文件中的结构体定义，在gmssl中被移除了，没办法兼容，补充定义后编译又会有各种问题。
有什么操作可以让gmssl库和openssl库同时使用，并且不冲突的吗？

**Comment by wupeili1024** [comment]
环境是win7 32bit vs2010

**Comment by zhenyuwei** [comment]
接口名都是一样的，这个好像不可以吧。如果你想要使用gmssl，应该找到你是要的openssl版本，然后看一下和gmssl使用的openssl差异，这样把中间更新的内容添加到你的openssl中就可以，这样很耗时间的。

**Comment by guanzhi** [comment]
gmssl master分支和openssl 1.1 api兼容，不兼容openssl 1.0 api。建议你修改一下自己的程序，这个工作量并不大。

**Comment by zhupc2017** [comment]
openssl 1.0 替换成gmssl  工作量很大吧
