### ISSUE TITLE
SM2将成为国际标准，你们怎么看？

### ISSUE THREAD

**Issue by muyu1944** [guanzhi/GmSSL#443]
[http://www.is.cas.cn/tpxw2016/201711/t20171109_4889656.html](url)

我们领导让我联系openssl希望他们加入国密算法的实现，你们怎么看。。。。。。

**Comment by guanzhi** [comment]
放心吧，早晚都会加的

**Comment by guanzhi** [comment]
openssl-1.1.1已经加了
