### ISSUE TITLE
nginx集成gmssl2.0，握手报“version too low”

### ISSUE THREAD

**Issue by shenchong0235** [guanzhi/GmSSL#445]
编译gmssl2.0，并重新编译nginx，引用gmssl，编译成功，生成证书，启动运行都成功了。但使用360国密专版访问时，nginx日志报
SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) 

用wireshark抓包，则显示 Handshake Failure (40)

是360浏览器支持的加密版本太低还是gmssl支持的版本太低？gmssl的加密算法没有360浏览器支持的？
折腾了两天了！

**Comment by shenchong0235** [comment]
查了下gmssl2.0的版本说明，“TLS 1.2 cipher suite ECDHE_SM2_WITH_SMS4_SM3”。
用wireshark抓包看到360国密版的 Client Hello 包支持的 cipher suite有下列18种：
` Cipher Suites (18 suites)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
                Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA (0xc007)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                Cipher Suite: TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
                Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
                Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)`

没有gmssl使用的 “ECDHE_SM2_WITH_SMS4_SM3” ，是否这个原因导致握手失败？

**Comment by liclicli** [comment]
@shenchong0235 360国密浏览器对国密的支持是在整个协议上的，使用的是GM/T 0024-2014协议，与TLS系列并不兼容；根据之前关老师的说法，目前gmssl支持国密协议还在开发中（且优先级有限），所以目前的gmssl不能做到让360国密浏览器连接到nginx上；
“ECDHE_SM2_WITH_SMS4_SM3”是TLS1.2下的一个自定义的套件，并不是国密协议套件，所以虽然使用了国密算法，却不能被360连上。

**Comment by guanzhi** [comment]
我们正在做GmSSL到Chromium的移植工作，以解决没有可用的国密浏览器的窘境。

**Comment by 27954741** [comment]
请问关老师 gmssl移植到chromium的工作啥时候可以完成 @guanzhi

**Comment by guanzhi** [comment]
让Chrome完全支持国密套件和证书，除了加入GmSSL之外还有很多工作要做。我们会在近期先发布一个用于Mac操作系统的初始版本 (0.1)。

**Comment by liclicli** [comment]
@guanzhi 关老师，再次询问下Chrome支持国密套件和证书的MAC初始版本的最新进展：）

**Comment by ygm521** [comment]
@guanzhi gmssl现在能做到让360国密浏览器访问nginx？谢谢

**Comment by ygm521** [comment]
@guanzhi gmssl现在能做到让360国密浏览器访问nginx？谢谢
