### ISSUE TITLE
谁会用这个有后门的加密体系？

### ISSUE THREAD

**Issue by imlibra** [guanzhi/GmSSL#446]
这个“双证书体系”，不就是公开的后门吗？直接把加密证书的私钥留在CA。所以开发这个给谁用呢？

**Comment by LiTianjue** [comment]
可管控你懂的

**Comment by imlibra** [comment]
关键是谁会希望自己需要加密的东西“可被管控”呢？

**Comment by guanzhi** [comment]
双证书体系在标准文本中的应用范围是SSL VPN，对于员工通过VPN访问企业内网这种场景会有这个需求（相当于密钥托管），但是常见的Web浏览场景，则没有这方面的需求。

**Comment by conezxy** [comment]
加密私钥会加密存放在KM，而不是CA。从国家规范来说，KM和CA要相互独立（常见的组合是CA让一个企业来运营，而KM是政府部门负责）。

而且加密私钥的用途并不只是监管。假设你用数字信封的方式加密了很多业务数据（可能是加密邮件，或者加密磁盘），加密私钥的载体是USBKey或者IC卡，但后来这个设备损坏了，双证书体系就可以保证你可以恢复出原先的数据，这在很多做文档数据保护的场合是必须的。

**Comment by imlibra** [comment]
说白了，这个国密体系不就是要求政府的Key Management持有所有人的加密私钥吗...不谈SM2等有没有可能的数学缺陷这个无法验证的问题，就这一点谁会用？无论是企业还是个人，谁会希望自己想加密的东西可被政府管控？

密钥恢复的问题，很多人都用过OpenSSL、GNUPG这类东西吧？如果没有备份，丢了私钥都是无法恢复的。但无论是否做备份措施，会有人乐意把自己的私钥交给政府的KM吗？据说中国政府打算推广国密体系到全世界，替代PKCS的体系和NIST的算法，那就很滑稽了。

**Comment by chn475111** [comment]
@imlibra 政府强制推广企事业单位使用

**Comment by ZZMarquis** [comment]
私钥实际不是自己“私有”，这总让人感觉怪怪的，如果KM泄露了私钥，谁来为企业止损呢...

**Comment by Byron-Ding** [comment]
> @imlibra 政府会强制要求企事业单位使用.

有没有后门另说，单纯讨论接受度的话
对用户好像目前都没有推开来，Linux内核倒是一定程度支持SM234（过程还磕磕绊绊的），主流浏览器C，F，S，似乎全部不支持，如果强行转换，用户打不开网页，这不是给用户使绊子嘛。
看了好多政府的对用户的网站，都没有SM系列的支持，
我感觉让用户去调教浏览器，就好像是之前的压缩包不会解一样，是没办法中的办法。
所以很多都没必要支持
除了IT部门的人以外，其他人用起来估计太麻烦了，除非能做到用户简单易用，或者试图让C的内核源代码支持(当然这难度很大)，要不然又是一滩浑水。
唉，所以是麻中之麻
