### ISSUE TITLE
有没有接口说明文档

### ISSUE THREAD

**Issue by caoweifeng** [guanzhi/GmSSL#447]

**Comment by mixuan** [comment]
同求，编译好包后都不知道怎么调用，官网的文档有些对不上了，sm2加密的参数都变了。。。

**Comment by shijl80** [comment]
+1，而且官方文档示例还有错误，比如：
![image](https://user-images.githubusercontent.com/37890252/43701597-5e1df356-9989-11e8-9068-08dac95b4ba6.png)
