### ISSUE TITLE
NASM not found

### ISSUE THREAD

**Issue by eidev1** [guanzhi/GmSSL#448]
下载gmssl 2.0 sources后，
安装完执行ActivePerl， perl Configure VC-WIN32

出现NASM not found - please read INSTALL and NOTES.WIN for further details
但是我的NASM也装了，path也设置了

E:\gmssl\GmSSL-gmssl-2.0>perl Configure VC-WIN32
Configuring OpenSSL version 1.1.0d (0x1010004fL)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACK
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-gmieng       [default]  OPENSSL_NO_GMIENG
    no-gmtls        [default]  OPENSSL_NO_GMTLS
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-sdfeng       [default]  OPENSSL_NO_SDFENG
    no-skfeng       [default]  OPENSSL_NO_SKFENG
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default]
    no-zlib-dynamic [default]
    no-zuc          [default]  OPENSSL_NO_ZUC (skip dir)
Configuring for VC-WIN32
NASM not found - please read INSTALL and NOTES.WIN for further details

**Comment by guanzhi** [comment]
请参考 http://gmssl.org/docs/install.html 中的Windows编译常见错误

**Comment by xiaobo93** [comment]
@guanzhi  这个连接里面，并没有提到对“NASM not found - please read INSTALL and NOTES.WIN for further details”的解决方案。
如果提到了，请帮忙指出

**Comment by dontminddontmind** [comment]
用perl Configure VC-WIN32 no-asm
或者重新下载源代码：https://github.com/guanzhi/GmSSL/archive/master.zip
我两个方法都不会显示NASM not found 了
但是之后又报错Can't locate Win32/Console.pm in @INC ...
现在改装Strawberry Perl了......
