### ISSUE TITLE
GmSSL SM2签名验签与UKey, 加密机的兼容性问题

### ISSUE THREAD

**Issue by kevinhe79** [guanzhi/GmSSL#449]
关老师：
  您好！

  工作中有通过UKey签名验签及通过密码服务器签名验签的需求。想转用GmSSL实现软件算法，但测试中发现用UKEY或密码机签出的内容不能用GmSSL验证（UKEY和密码机是能相互验证的)，相反也一样。

  在Issues中查找到有人反应过这个问题，您也做过回应，参见下面Issue号： 
============================================
  gmssl 无法验签ukey中sm2算法生成的签名 
  #369 by RubicPhil was closed on Nov 11 2017 
===========================================

我参考关老师您的建议将X, Y封装为EVP_PKEY结构直接调用，也已保存为PEM做过命令行测试， GmSSL一样不能验证通过。
======================================================
gmssl pkeyutl -verify -pubin -inkey D:\Work\svn\PkiDemoProject\OpenSSL\Debug\publicKey.pem -pkeyopt ec_scheme:sm2 -in D:\Work\svn\PkiDemoProject\OpenSSL\Debug\unsignedData.bin -sigfile D:\Work\svn\PkiDemoProject\OpenSSL\Debug\signedData.bin
Signature Verification Failure

测试代码如下：
===============================================================
bool SM2Verify2(const char* signCert, bool isPem, const unsigned char* toBeSignedData, const unsigned int toBeSignedLen, unsigned char* signedData, unsigned int signedDataLen)
{
	bool ret = false;
	//char key[65] = "\x6d\x63\x5e\x4f\x2d\x62\xd3\x61\xe3\xa5\x07\xa2\x5e\x7a\xae\x12\xbe\xf1\x97\x40\xe7\x5d\xaf\x82\x4d\xec\x28\xb7\x39\x9c\xe5\x5f\x12\x88\x61\xa8\x3e\xaf\xa6\xf5\x08\xcf\xfe\xc4\x43\x25\xf1\x0b\x22\x81\x47\x84\x75\xa7\x27\x7b\x5e\xcf\x3a\x01\xce\xfa\x8e\x6f";
	char keyXStr[65] = "6d635e4f2d62d361e3a507a25e7aae12bef19740e75daf824dec28b7399ce55f";
	char keyYStr[65] = "128861a83eafa6f508cffec44325f10b2281478475a7277b5ecf3a01cefa8e6f";
	BIGNUM *X = NULL, *Y = NULL;
	//BIO *bio = NULL;
	EC_KEY	*ecKey = NULL;
	EVP_PKEY *evpKey = NULL;
	EC_GROUP *group = NULL;

	group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
	if(!group)
	{
		printf("EC_GROUP_new_by_curve_name err.\n");
		goto end;
	}
	ecKey = EC_KEY_new();
	/* 设置密钥参数 */
	if (!ecKey || EC_KEY_set_group(ecKey, group) != 1)
	{
		printf("EC_KEY_set_group err.\n");
		goto end;
	}
	BN_hex2bn(&X, keyXStr);
	BN_hex2bn(&Y, keyYStr);
	if(1 != EC_KEY_set_public_key_affine_coordinates(ecKey, X, Y))
	{
		printf("EC_KEY_set_public_key err.\n");
		goto end;
	}

	/*
	bio = BIO_new_file("public.pem", "wb");
	if (!bio)
	{
		printf("fopen err.\n");
		goto end;
	}

	if(1 != PEM_write_bio_EC_PUBKEY(bio, ecKey))
	{
		printf("fopen err.\n");
		goto end;
	}

	BIO_free_all(bio);
	bio = NULL;
	*/

	evpKey = EVP_PKEY_new();
	if (!evpKey || 1 != EVP_PKEY_set1_EC_KEY(evpKey, ecKey))
	{
		printf("EVP_PKEY_new or EVP_PKEY_set1_EC_KEY err.\n");
		goto end;
	}

	ret = SM2VerifyByKey(evpKey, toBeSignedData, toBeSignedLen, signedData, signedDataLen);

end:
	if (X)
		BN_free(X);
	if (Y)
		BN_free(Y);
	if (group)
		EC_GROUP_free(group);
	if (ecKey)
		EC_KEY_free(ecKey);
	if (evpKey)
		EVP_PKEY_free(evpKey);
	/*
	if (bio)
		BIO_free_all(bio);
	*/

	return ret;
}

SM2VerifyByKey的实现代码如下：
================================================================
bool SM2VerifyByKey(EVP_PKEY *pkey, const unsigned char* toBeSignedData, const unsigned int toBeSignedLen, unsigned char* signedData, unsigned int signedDataLen)
{
	bool ret = false;

	EVP_MD_CTX *mdctx = NULL;

	/* verify the sign */
	mdctx = EVP_MD_CTX_create();
	if (!(mdctx)) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		goto end;
	}

	const EVP_MD *md = EVP_sm3();
	if (!EVP_VerifyInit_ex(mdctx, md, NULL)) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		goto end;
	}

	if (!EVP_VerifyUpdate(mdctx, toBeSignedData, toBeSignedLen)) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		goto end;
	}

	int i = EVP_VerifyFinal(mdctx, signedData, signedDataLen, pkey);
	if (i != 1) {
		fprintf(stderr, "EVP_VerifyFinal return %d, error: %s %d\n", i, __FILE__, __LINE__);
		goto end;
	}

	ret = true;

end:
	if (mdctx)
		EVP_MD_CTX_free(mdctx);

	return ret;
}

我还尝试过SM2 demo中的模式，问题一样
=============================================
bool SM2Verify(const char* signCert, bool isPem, const unsigned char* toBeSignedData, const unsigned int toBeSignedLen, unsigned char* signedData, unsigned int signedDataLen)
{
	sm3_ctx_t sm3;
	sm3_init(&sm3);
	sm3_update(&sm3, toBeSignedData, toBeSignedLen);
	unsigned char digest[SM3_DIGEST_LENGTH];
	sm3_final(&sm3, digest);

	bool ret = false;
	EVP_PKEY *pkey = NULL;
	EVP_MD_CTX *mdctx = NULL;

	/* get the pub key from the cert*/
	X509 *cert = NULL;
	if (isPem)
		cert = fileio_read_pem_cert(signCert);
	else
		cert = fileio_read_der_cert(signCert);
	if (!cert)
		goto end;
	pkey = X509_get_pubkey(cert);
	if (pkey == NULL) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		goto end;
	}

	int vRet = SM2_verify(0, digest, SM3_DIGEST_LENGTH, signedData, signedDataLen, pkey->pkey.ec);
	printf("SM2_verify return %d.\n", vRet);
	if (1 == vRet)
	{
		ret = true;
	}
	else {
		printf_error();
	}

end:
	if (cert)
		X509_free(cert);
	if (pkey)
		EVP_PKEY_free(pkey);

	return ret;
}

我附上了测试数据和公钥
请关老师指出我代码的问题，谢谢！

[Debug.zip](https://github.com/guanzhi/GmSSL/files/1787721/Debug.zip)

**Comment by guanzhi** [comment]
你应该使用EVP_DigestSignInit/Update/Final接口，而不是EVP_SignInit/Update/Final

**Comment by kevinhe79** [comment]
验证的确是这个问题，谢谢！

**Comment by faushine** [comment]
typedef struct Struct_ECCSIGNATUREBLOB{
	BYTE	r[ECC_MAX_XCOORDINATE_BITS_LEN/8];
	BYTE	s[ECC_MAX_YCOORDINATE_BITS_LEN/8];
} ECCSIGNATUREBLOB, *PECCSIGNATUREBLOB;
typedef struct Struct_ECCPUBLICKEYBLOB{
	ULONG	BitLen;
	BYTE	XCoordinate[ECC_MAX_XCOORDINATE_BITS_LEN/8];
	BYTE	YCoordinate[ECC_MAX_YCOORDINATE_BITS_LEN/8];
}ECCPUBLICKEYBLOB, *PECCPUBLICKEYBLOB;
请教一下老师，我也是使用ukey去生成SM2签名，再把公钥Struct_ECCPUBLICKEYBLOB的x和y写进SM2_KEY的public_key中，把签名Struct_ECCSIGNATUREBLOB的r和s写进SM2_SIGNATURE中，调用如下：
`int main(void)
{
	SM2_KEY pub_key;
	SM2_SIGN_CTX sign_ctx;
	int ret;

	uint8_t x[64];
	size_t len;
	if (load_bytes1("00000000000000000000000000000000000000000000000000000000000000003869743ADF456544A121D1FC51BDCBFBC32CC9670333C44C9522B6F5AFF18E77", x, &len) != 1) {
		fprintf(stderr, "Failed to load bytes.\n");
		return -1;  // Or handle the error in other ways.
	}
	uint8_t y[64];
	if (load_bytes1("000000000000000000000000000000000000000000000000000000000000000029B39C27065DFD3B9B6B2651C0E56D7896B60317F2B8DEA2CA720D879C76EFC6", y, &len) != 1) {
		fprintf(stderr, "Failed to load bytes.\n");
		return -1;  // Or handle the error in other ways.
	}
	uint8_t dgst[32];
	if (load_bytes("55E12E91650D2FEC56EC74E1D3E4DDBFCE2EF3A65890C2A19ECF88A307E76A23", dgst, &len) != 1) {
		fprintf(stderr, "Failed to load bytes.\n");
		return -1;  // Or handle the error in other ways.
	}
	uint8_t r[64]; 
	if (load_bytes("000000000000000000000000000000000000000000000000000000000000000071E536B59C9D3889DD05B7386A6DAF1474180CF5F0E52679618FF3E7CD269C0A", r, &len) != 1) {
		fprintf(stderr, "Failed to load bytes.\n");
		return -1;  // Or handle the error in other ways.
	}
	uint8_t s[64]; 
	if (load_bytes("0000000000000000000000000000000000000000000000000000000000000000083810A435B7EE11F8D81D3E9E5227094F4599D9FD2428E455FDC0C24DCB94F0", s, &len) != 1) {
		fprintf(stderr, "Failed to load bytes.\n");
		return -1;  // Or handle the error in other ways.
	}
	memcpy(pub_key.public_key.x, x, 32);
	memcpy(pub_key.public_key.y, y, 32);
	SM2_SIGNATURE sig;
	memcpy(sig.r, r, 32);
	memcpy(sig.s, s, 32);
	format_bytes(stdout, 0, 0, "x", pub_key.public_key.x, 32);
	format_bytes(stdout, 0, 0, "y", pub_key.public_key.y, 32);
	format_bytes(stdout, 0, 0, "to be signed digest", dgst, sizeof(dgst));
	
	if ((ret = sm2_do_verify(&pub_key, dgst, &sig)) != 1) {
		fprintf(stderr, "verify failed\n");
	} else {
		printf("verify success\n");
	}
	return 0;
}
`
输出是：
/mnt/d/GmSSL/src/sm2_lib.c:162:sm2_do_verify():
verify failed
老师可以帮忙看下是为什么吗？ukey是小端序，load_bytes转成了大端序

**Comment by ck1223256744** [comment]
> typedef struct Struct_ECCSIGNATUREBLOB{ BYTE r[ECC_MAX_XCOORDINATE_BITS_LEN/8]; BYTE s[ECC_MAX_YCOORDINATE_BITS_LEN/8]; } ECCSIGNATUREBLOB, *PECCSIGNATUREBLOB; typedef struct Struct_ECCPUBLICKEYBLOB{ ULONG BitLen; BYTE XCoordinate[ECC_MAX_XCOORDINATE_BITS_LEN/8]; BYTE YCoordinate[ECC_MAX_YCOORDINATE_BITS_LEN/8]; }ECCPUBLICKEYBLOB, *PECCPUBLICKEYBLOB; 请教一下老师，我也是使用ukey去生成SM2签名，再把公钥Struct_ECCPUBLICKEYBLOB的x和y写进SM2_KEY的public_key中，把签名Struct_ECCSIGNATUREBLOB的r和s写进SM2_SIGNATURE中，调用如下：
> 
> ```c++
> int main(void)
> {
> 	SM2_KEY pub_key;
> 	SM2_SIGN_CTX sign_ctx;
> 	int ret;
> 
> 	uint8_t x[64];
> 	size_t len;
> 	if (load_bytes1("00000000000000000000000000000000000000000000000000000000000000003869743ADF456544A121D1FC51BDCBFBC32CC9670333C44C9522B6F5AFF18E77", x, &len) != 1) {
> 		fprintf(stderr, "Failed to load bytes.\n");
> 		return -1;  // Or handle the error in other ways.
> 	}
> 	uint8_t y[64];
> 	if (load_bytes1("000000000000000000000000000000000000000000000000000000000000000029B39C27065DFD3B9B6B2651C0E56D7896B60317F2B8DEA2CA720D879C76EFC6", y, &len) != 1) {
> 		fprintf(stderr, "Failed to load bytes.\n");
> 		return -1;  // Or handle the error in other ways.
> 	}
> 	uint8_t dgst[32];
> 	if (load_bytes("55E12E91650D2FEC56EC74E1D3E4DDBFCE2EF3A65890C2A19ECF88A307E76A23", dgst, &len) != 1) {
> 		fprintf(stderr, "Failed to load bytes.\n");
> 		return -1;  // Or handle the error in other ways.
> 	}
> 	uint8_t r[64]; 
> 	if (load_bytes("000000000000000000000000000000000000000000000000000000000000000071E536B59C9D3889DD05B7386A6DAF1474180CF5F0E52679618FF3E7CD269C0A", r, &len) != 1) {
> 		fprintf(stderr, "Failed to load bytes.\n");
> 		return -1;  // Or handle the error in other ways.
> 	}
> 	uint8_t s[64]; 
> 	if (load_bytes("0000000000000000000000000000000000000000000000000000000000000000083810A435B7EE11F8D81D3E9E5227094F4599D9FD2428E455FDC0C24DCB94F0", s, &len) != 1) {
> 		fprintf(stderr, "Failed to load bytes.\n");
> 		return -1;  // Or handle the error in other ways.
> 	}
> 	memcpy(pub_key.public_key.x, x, 32);
> 	memcpy(pub_key.public_key.y, y, 32);
> 	SM2_SIGNATURE sig;
> 	memcpy(sig.r, r, 32);
> 	memcpy(sig.s, s, 32);
> 	format_bytes(stdout, 0, 0, "x", pub_key.public_key.x, 32);
> 	format_bytes(stdout, 0, 0, "y", pub_key.public_key.y, 32);
> 	format_bytes(stdout, 0, 0, "to be signed digest", dgst, sizeof(dgst));
> 	
> 	if ((ret = sm2_do_verify(&pub_key, dgst, &sig)) != 1) {
> 		fprintf(stderr, "verify failed\n");
> 	} else {
> 		printf("verify success\n");
> 	}
> 	return 0;
> }
> ```
> 
> 输出是： /mnt/d/GmSSL/src/sm2_lib.c:162:sm2_do_verify(): verify failed @guanzhi 老师可以帮忙看下是为什么吗？ukey是小端序，load_bytes转成了大端序

请问你解决了吗 我也是这个问题
