### ISSUE TITLE
360 的 ClientkeyExchange 貌似不能直接用 SM2_decrypt_with_recommended 进行解密

### ISSUE THREAD

**Issue by mrpre** [guanzhi/GmSSL#45]
下面是 360 发送的  ClientkeyExchange  （我手动分割了C1 C2 C3）
很明显是 Asn1 编码的，如果直接用 SM2_CIPHERTEXT_VALUE_decode 进行解码，会失败。

/****************************/
30 81 9a
02 21 
00 c4 fe ba 1f
07 e0 d3 7c d2 b4 21 18 cc 31 51 d1 33 06 43 5d
ce fe 19 2d 58 04 5b 2d 06 6e ee 14 

02 21 
00 86
e3 3d 0f d3 83 5d 52 17 ce 2e 9f e8 d0 82 d2 4a
0d dd ef ff 1b 94 80 05 a6 c3 0e c9 51 e0 79 

04 20 
d1 b9 96 54 96 2a 5c d6 fe bd 3f 5c e1 ae c5
31 47 8f dc d6 27 17 e0 13 e6 f0 e3 f3 d5 c1 53
82 

04 30 
4d bf 48 13 84 bf 11 18 56 31 4e e7 da
d0 76 32 53 93 f0 0d bd 32 b2 e2 e0 48 12 bb d9
42 7d 3a 75 00 5c 29 12 3a 3e 55 ef 39 c0 40 2a
37 d5 90
/****************************/

还有一事不解，
GM/T 0024 -2014 SSLVPN技术规范中，对ClientkeyExchange 如下描述
case ECC:
    opaque ECCEncryptedPreMasterSecret<...>

ECCEncryptedPreMasterSecret:
使用ECC加密算法时，用服务端加密公钥加密预主密钥

也意味着，加密的结果也即 ECCEncryptedPreMasterSecret<...> 应该满足
GM/T 0003.4-2012  SM2椭圆曲线公钥密码算法 第4部分：公钥加密算法 6.1节 的 C = C1 || C2 || C3格式

但是360抓包的结果，怎么看都和规范描述的不一致啊。

**Comment by conezxy** [comment]
请看GM/T 0009-2012 SM2算法使用规范

-
掌晓愚

在 2016年9月2日，18:00，Jiayuan Chen <notifications@github.com<mailto:notifications@github.com>> 写道：


下面是 360 发送的 ClientkeyExchange （我手动分割了C1 C2 C3）
很明显是 Asn1 编码的，如果直接用 SM2_CIPHERTEXT_VALUE_decode 进行解码，会失败。

/****************************/
30 81 9a
02 21
00 c4 fe ba 1f
07 e0 d3 7c d2 b4 21 18 cc 31 51 d1 33 06 43 5d
ce fe 19 2d 58 04 5b 2d 06 6e ee 14

02 21 00 86
e3 3d 0f d3 83 5d 52 17 ce 2e 9f e8 d0 82 d2 4a
0d dd ef ff 1b 94 80 05 a6 c3 0e c9 51 e0 79

04 20
d1 b9 96 54 96 2a 5c d6 fe bd 3f 5c e1 ae c5
31 47 8f dc d6 27 17 e0 13 e6 f0 e3 f3 d5 c1 53
82

04 30
4d bf 48 13 84 bf 11 18 56 31 4e e7 da
d0 76 32 53 93 f0 0d bd 32 b2 e2 e0 48 12 bb d9
42 7d 3a 75 00 5c 29 12 3a 3e 55 ef 39 c0 40 2a
37 d5 90
/****************************/

还有一事不解，
GM/T 0024 -2014 SSLVPN技术规范中，对ClientkeyExchange 如下描述
case ECC:
opaque ECCEncryptedPreMasterSecret<...>

ECCEncryptedPreMasterSecret:
使用ECC加密算法时，用服务端加密公钥加密预主密钥

也意味着，加密的结果也即 ECCEncryptedPreMasterSecret<...> 应该满足
GM/T 0003.4-2012 SM2椭圆曲线公钥密码算法 第4部分：公钥加密算法 6.1节 的 C = C1 || C2 || C3格式

但是360抓包的结果，怎么看都和规范描述的不一致啊。

―

**Comment by mrpre** [comment]
@conezxy  谢谢，已在 GM/T 0009-2012  7. 2节中找到报文对应的格式。
但是不解 GM/T 0003.4-2012 中 SM2公钥加密输出密文（ C=C1 || C2 || C3 ）难道不就是 指 GM/T 0009-2012  的 ‘加密数据格式’，两者难道含义不一样？

@guanzhi GMSSL有函数可以 decode&decrypt  GM/T 0009-2012  7. 2 中定义的密文数据吗？（没有的话我自己写也行）

**Comment by conezxy** [comment]
对应同样的数据，在不同场景和层次中的表达和定义不同：
1. GM/T 0003-2012的定义（ C=C1 || C2 || C3 ）是数学意义上的表达。如果要对应到编程实现，则需要将其定义为C语言的结构。

2. GM/T 0016/0017/0018-2012（SDF和SKF规范）中的定义是基于C编程的表达
`
typedef struct Struct_ECCCIPHERBLOB{
	BYTE	XCoordinate[ECC_MAX_XCOORDINATE_BITS_LEN/8];
	BYTE	YCoordinate[ECC_MAX_YCOORDINATE_BITS_LEN/8];
	BYTE    HASH[32]; 
	ULONG	CipherLen;
	BYTE    Cipher[128];
} ECCCIPHERBLOB, *PECCCIPHERBLOB;
`

3. 但仅有C编程上的定义，还无法解决不同系统之间数据互通的问题（比如大小端问题）。因此在GM/T 0009-2012中定义了适用于序列化的表达（ASN.1）

**Comment by guanzhi** [comment]
@mrpre 还没有，请参考 `sm2/sm2_asn1.c`
