### ISSUE TITLE
Go语言无法编译

### ISSUE THREAD

**Issue by Nanguang** [guanzhi/GmSSL#450]
GMSSL version  2.1.1

pkey.go 文件里好像很多内容像encrypt的c语言部分是还没有写好吗？

编译始终无法通过，请问有相关的教程或者测试文件参考一下吗？

**Comment by guanzhi** [comment]
Go语言接口部分由一位来自BAT的志愿者参加更新维护，可能还需要一些时间才能更新。
pkey.go 无法通过可以先从代码中删除。

**Comment by ajeecai** [comment]
import "github.com/guanzhi/GmSSL/go/gmssl"

产生很多错误如：
could not determine kind of name for C.EVP_MD_CTX_free 
could not determine kind of name for C.EVP_MD_CTX_new
