### ISSUE TITLE
加密解密

### ISSUE THREAD

**Issue by jh531207323** [guanzhi/GmSSL#453]
我想请教一个问题OpenVPN采用的是OpenSSL库，如果我想换成国密算法，是不是直接将OpenVPN中对OpenSSL的调用换成GmSSL即可.
  另外，我看了你们2018的计划提到了加密卡的硬件支持，那我如果想在GMSSL中将加密解密换成PIC-E加密卡的话，是不是改变相应代码，调用硬件的驱动就行！

**Comment by guanzhi** [comment]
通常来说依赖OpenSSL的主流开源项目都可以用GmSSL代替OpenSSL完成编译。但是让其使用国密算法和证书还需要通过配置文件或者输入参数来启用。同样，通过PCI-E等密码硬件实现加解密也需要按类似的方式启用。理想情况下不需要在软件的代码上进行修改。

具体到OpenVPN，还需要查看OpenVPN的文档确认。

**Comment by jh531207323** [comment]
openvpn 本身也有加密算法的配置选项，我尝试配入GMSSL，才发现，但是它本身只有openssl和MBEDTLS这两个，这当然是最理想的情况
在c++中是，好像这样引用的，
#include <openssl/ssl.h> 

也可以这样引用gmssl吗？

**Comment by jh531207323** [comment]
EVP API是GmSSL密码服务接口。
Openssl 也是这个接口，
我看include的名称都是一样的，这样如何区分，
openssl迁移到gmssl是一个经常预见的问题，
我查了下issues，有迁移的案例，是替换代码，有没有比较快速的替换方案？
当然只是建议，不知道是否具有可行性
