### ISSUE TITLE
OpenVPN集成GmSSL

### ISSUE THREAD

**Issue by jh531207323** [guanzhi/GmSSL#455]
编辑脚本
./configure OPENSSL_LIBS="-L/usr/local/openvpn/gmssl/ssl/ -lssl -lcrypto" OPENSSL_CFLAGS="-I/usr/local/openvpn/gmssl/include/" --includedir=/usr/local/openvpn/gmssl/include --libdir=/usr/local/openvpn/gmssl/lib

make时候报错
![image](https://user-images.githubusercontent.com/15181617/37645018-97acf108-2c60-11e8-9818-dc5855954ab8.png)

**Comment by guanzhi** [comment]
你贴的错误实际上已经说明了原因，但是不建议你就这个问题再做修改了。由于最新的OpenVPN和最新的GmSSL一起编译没有任何问题，在Ubuntu 16.04和Mac操作系统上无需指定任何configure选项都能顺利通过。

你可以查看一下：
1. 你的OpenVPN是否版本太老，请换至OpenVPN和GmSSL的master分支最新代码。
2. 你的环境下OpenVPN是否能和OpenSSL-1.1.0版本顺利编译，如果不能，检查你自己编译环境的问题。
