### ISSUE TITLE
SM3算法bug问题

### ISSUE THREAD

**Issue by lijk8090** [guanzhi/GmSSL#457]
SS1 = ROTATELEFT((ROTATELEFT(A,12) + E + ROTATELEFT(T[j],j)), 7);
应改为:
SS1 = ROTATELEFT((ROTATELEFT(A,12) + E + ROTATELEFT(T[j],j%32)), 7);

**Comment by chn475111** [comment]
sm3.c 180行

**Comment by guanzhi** [comment]
你愿意的话可以提交一个pull request

**Comment by chn475111** [comment]
@guanzhi 我不太会用pull request

**Comment by liclicli** [comment]
@chn475111 #360 好像和这个问题类似

**Comment by chn475111** [comment]
@liclicli 差不多
