### ISSUE TITLE
关于skf问题

### ISSUE THREAD

**Issue by robindai518** [guanzhi/GmSSL#458]
@guanzhi 
Configure默认并没有启用skf，尝试修改Configure，注释掉
                  "skfeng"              => "default",
编译出错，提示找不到e_skf.c，查了下engine目录下的确没有此文件，问：

1 如何启用skfeng
2 最新release的assets中的skf.so和skf_dummy.so是如何配置编译得来的

**Comment by guanzhi** [comment]
SKF目前只提供了Linux动态库，你可以用厂商的skf动态库或者skf_dummy来测试
