### ISSUE TITLE
希望能支持C89

### ISSUE THREAD

**Issue by ZZMarquis** [guanzhi/GmSSL#459]
可能还是有一些比较老的或者比较特殊的项目是要求C89的，希望作者能做一下这方面的支持

**Comment by guanzhi** [comment]
如何指定C89编译？

**Comment by ZZMarquis** [comment]
Linux下我是这么弄的：
先执行./config
会有如下输出：
![image](https://user-images.githubusercontent.com/7624583/38012414-f8e96454-3293-11e8-8279-096e926b554a.png)

然后执行make的时候扩展CFLAGS:
make 'CFLAGS=-std=c89 -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack'

**Comment by guanzhi** [comment]
应该可以了
