### ISSUE TITLE
./include/openssl/srp.h

### ISSUE THREAD

**Issue by duanwujie** [guanzhi/GmSSL#462]
2.0 make update 时出现一下错误

unable to open ./include/openssl/srp.h:No such file or directory
make: *** [ordinals] 错误 2

**Comment by kingsurprise** [comment]
有解决吗？

**Comment by yanjingtu** [comment]
我这边版本是2.5.4，按说明./config然后make的时候出现报错，看着是要编译libcrypto.so.x的时候，操作系统是deepin20.9社区版，后来发现在操作系统的头文件目录有这个文件（/usr/include/openssl/srp.h），就把它拷贝了一份到源码目录的include/openssl子目录中，再make结果就编译成功了
