### ISSUE TITLE
请教 iOS 怎么使用 完全看不懂 

### ISSUE THREAD

**Issue by LanCat** [guanzhi/GmSSL#465]
请教 iOS 怎么使用 完全看不懂

**Comment by guanzhi** [comment]
如果你只是需要SSL通信的话，例如通过HTTPS访问服务器的REST接口，建议你将GmSSL和libcurl编译到一起，然后用libcurl的简单接口去访问服务。

**Comment by timeforasong** [comment]
> 如果你只是需要SSL通信的话，例如通过HTTPS访问服务器的REST接口，建议你将GmSSL和libcurl编译到一起，然后用libcurl的简单接口去访问服务。
iOS平台需要禁用no-async,但是编译不出来
Non-public API usage:
The app references non-public symbols in : _getcontext, _makecontext, _setcontext

**Comment by kedu** [comment]
> 如果你只是需要SSL通信的话，例如通过HTTPS访问服务器的REST接口，建议你将GmSSL和libcurl编译到一起，然后用libcurl的简单接口去访问服务。

有demo吗?
