### ISSUE TITLE
使用sms4对称加密，16个Byte的原文加密后长度为32个Byte

### ISSUE THREAD

**Issue by RoronoaZoro1665** [guanzhi/GmSSL#466]
origin.length: 16
origin: 48 49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 
ciphertext.length: 32
Ciphertext: 60 -66 -31 46 13 85 6 91 60 -43 122 -2 -24 -46 6 -13 -121 58 38 -54 -11 60 -95 115 90 57 -51 -65 -10 -116 78 102

使用   byte[] ciphertext = gmssl.symmetricEncrypt("SMS4", origin, key, iv);

16个Byte的原文加密后长度本来应该时为16个Byte吧？

**Comment by guanzhi** [comment]
`SMS4`是`sms4-cbc`的别名，`sms4-cbc`加密时会默认采用填充模式，当明文长度不是整数个块时，会填充至整数个块，如果明文是整数个块长，那么会填充1个块。你的例子中输入为1个块，因此输出长度为2个块长。
