### ISSUE TITLE
关于nginx使用sm2证书进行双向认证的问题

### ISSUE THREAD

**Issue by HyoukaLL** [guanzhi/GmSSL#467]
尝试了在配置nginx时指定openssl路径为gmssl的各种版本,也试了更改openssl源码,认证时可以弹出选择客户端证书,但选完之后网页就崩溃了,nginx日志中也没有相应的访问和错误.
`ERR_SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY`
我想问一下这是nginx认证证书时出现了问题还是浏览器的问题?
环境是Ubuntu16.04和谷歌浏览器
或者哪位大神有配置过nginx+sm2的指点一下,不胜感激!

**Comment by liclicli** [comment]
@HyoukaLL 你的ERR_SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY这个错误是在浏览器上报的吗？

**Comment by HyoukaLL** [comment]
@liclicli 错误是在浏览器报的,我导入的证书格式是pfx,在chrome中也能看到证书的各种信息

**Comment by liclicli** [comment]
@HyoukaLL 字面上是因为证书上没有找到私钥。建议可以先使用openssl s_client尝试去连服务器，看看究竟是什么问题。
