### ISSUE TITLE
OpenSSL 1.1.1预览版已经开始支持SM2/SM3/SM4算法

### ISSUE THREAD

**Issue by liuqun** [guanzhi/GmSSL#468]
OpenSSL 1.1.1 的预览版本最近6个月添加了许多新特性, 包括对中国SM2/SM3/SM4算法的支持.
以下是GitHub上的提交日志:

SM2椭圆曲线: https://github.com/openssl/openssl/pull/4793
SM3哈希摘要: https://github.com/openssl/openssl/pull/4616
SM4对称加密: https://github.com/openssl/openssl/pull/4552

从OpenSSL 1.1.1预览版从pre1开始支持SM4和SM3, 从pre3起开始提供内置的SM2椭圆曲线算法. 当前最新的预览版本是OpenSSL 1.1.1-pre5, 链接地址 https://openssl.org/source/

**Comment by J-Feng** [comment]
@guanzhi 
请问这对GmSSL有什么影响？是否会继续开发？是否会针对这些做调整（比如合入OpenSSL1.1.1后移除GmSSL的相关算法，转而使用官方上游分支的实现）？

**Comment by guanzhi** [comment]
对GmSSL没有什么影响，我们也不会用OpenSSL-1.1.1的实现替换现有的SM2/3/4实现。GmSSL是否继续开发取决于我们是否要继续将某些新的密码特性和新的国密标准引入到GmSSL中，以及GmSSL是否能有持续的应用和资助。
