### ISSUE TITLE
请问SKF、SDF、SAF、SOF这些缩写的全称是什么？

### ISSUE THREAD

**Issue by yangtianfang** [guanzhi/GmSSL#469]
SKF C API: GM/T 0016-2012 Smart token cryptography application interface specification.
SDF C API: GM/T 0018-2012 Interface specifications of cryptography device application.
SAF C API: GM/T 0019-2012 Universal cryptography service interface specification.
SOF C/Java API: GM/T 0020-2012 Certificate application integrated service interface specification.

K大概可以和key搭上，D大概可以和device搭上，其他的字母实在想不出来了。。。

**Comment by guanzhi** [comment]
SKF/SDF/SAF/SOF来自于标准中接口函数的前缀，至于是什么的缩写实在没有必要深究。

**Comment by liouxiao** [comment]
SKF = Smart/Secure Key Function
SDF = Smart/Secure Device Function
SAF = Smart/Secure Application Function
SOF = Smart/Secure [Object??]/Open??]/[Operational??] Function
