### ISSUE TITLE
t1_enc.obj : error LNK2019: 无法解析的外部符号 _EVP_DigestSignUpdate

### ISSUE THREAD

**Issue by baggiowangyu** [guanzhi/GmSSL#47]
t1_enc.obj : error LNK2019: 无法解析的外部符号 _EVP_DigestSignUpdate，该符号在函数 _tls1_P_hash 中被引用
out32dll\ssleay32.dll : fatal error LNK1120: 1 个无法解析的外部命令

有人遇到过这个问题吗？
我是在Win7 x64 系统下使用VS2008 32位命令行工具编译的
编译命令如下：

perl Configure VC-WIN32 no-asm
ms\do_ms
nmake -f ms\ntdll.mak

代码是用SVN check out出来的。求解。

**Comment by LiTianjue** [comment]
方法1： 直接在crypto.def 文件中加入这个未导出的函数，只用加入函数名

方法2： 使用MinGW编译，
./config
make
make test

  这个方法在编译skf的时候还是有问题，我不用skf，我编译的时候把skf去掉了，不过这个问题我看在新的commit 中提到应该解决了，我还没测试过，你可以试一下

**Comment by newdible** [comment]
我在编译时，出现同样的问题。另外，修改crypto.def是指crypto头文件吗？具体怎样添加，能详细说明下吗？

**Comment by newdible** [comment]
在用ms\do_nasm编译时，也会出现如下的warning信息，请问是什么原因呢？哪位大神帮忙指导下啊？非常感谢
C:\GitHub\GmSSL>ms\do_nasm

C:\GitHub\GmSSL>perl util\mkfiles.pl  1>MINFO

C:\GitHub\GmSSL>perl util\mk1mf.pl nasm VC-WIN32  1>ms\nt.mak

C:\GitHub\GmSSL>perl util\mk1mf.pl dll nasm VC-WIN32  1>ms\ntdll.mak

C:\GitHub\GmSSL>perl util\mk1mf.pl nasm BC-NT  1>ms\bcb.mak

C:\GitHub\GmSSL>perl util\mkdef.pl 32 libeay  1>ms\libeay32.def
Warning: EVP_DigestSignUpdate does not have a number assigned
Warning: EVP_DigestVerifyUpdate does not have a number assigned

C:\GitHub\GmSSL>perl util\mkdef.pl 32 ssleay  1>ms\ssleay32.def

**Comment by LiTianjue** [comment]
我不熟悉windows的编译系统，我现在都用mingw编译了，大概是在 libeay32.def 文件中，参照其他函数的格式，手动加入EVP_DigestSignUpdate ，EVP_DigestVerifyUpdate ，后面的number可以不写，或者递增写，大概就是那么回事，具体你在看看

**Comment by newdible** [comment]
嗯嗯，谢谢您的答复。我也想用mingw编译，可是在安装时把我难住了，好多的installation选项，我都不知选择哪一个，您那儿有关于这个的安装使用说明吗？谢谢

**Comment by LiTianjue** [comment]
执行ms\do_nasm.bat 后，会生成libeay32.def 文件，直接在这个文件尾手动加入这两个未导出的符号即可（这两个函数本来是个宏，GmSSL将它改成函数了，具体什么原因我没研究过），vc 编译问题也不大，只不过我都是在ubuntu上编译的，如果你和我一样习惯在linux下工作，可以参考这个连接，使用交叉编译在linux上编译windows的库和执行文件
https://community.openvpn.net/openvpn/wiki/BuildingUsingGenericBuildsystem

**Comment by baggiowangyu** [comment]
我之前也是找到了这两个函数的定义区别之后加到libeay32.def文件里面去的，后来编译过程中修改了一些测试代码之后就能完全编译通过了。

**Comment by newdible** [comment]
一波未平，一波又起。
.\engines\e_skf.c(782) : warning C4028: 形参 5 与声明不同
        link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll\skf.
ll  @C:\Users\niudb\AppData\Local\Temp\nmDAC.tmp
   正在创建库 out32dll\skf.lib 和对象 out32dll\skf.exp
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_GetDevInfo@8，该符号在函数 _
pen_dev 中被引用
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_ConnectDev@8，该符号在函数 _
pen_dev 中被引用
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_DevAuth@12，该符号在函数 _de
_auth 中被引用
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_GenRandom@12，该符号在函数 _
ev_auth 中被引用
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_OpenApplication@12，该符号在
函数 _open_app 中被引用
e_skf.obj : error LNK2019: 无法解析的外部符号 _SKF_VerifyPIN@16，该符号在函数 _
erify_pin 中被引用
问下这个有谁遇到过吗？

**Comment by baggiowangyu** [comment]
你引用了SKF库，那么链接的时候必须把你要用的SKF.lib加进去

**Comment by newdible** [comment]
我是用windows 编译的，不知环境是否和您的编译环境一样呢？如果windows不支持的话我就暂时不调试了

**Comment by baggiowangyu** [comment]
我也是Windows环境编译的 Win7 x64 旗舰版 + VS2008。可以编译成功。编译过程参考VS + openssl的编译过程。

**Comment by newdible** [comment]
我执行完ms\do_nasm，然后在libeay32.def添加了两个未定义函数，再执行nmake -f ms\ntdll.mak -a，按说此时还没有开始用VS啊，怎么链接skf.lib呢？求指导啊。非常感谢啊！

**Comment by baggiowangyu** [comment]
我当时只增加了EVP_DigestSignUpdate这个函数的导出，就编译过了。还有，编译时用VS的命令行工具来编译

**Comment by newdible** [comment]
我是用的VS的命令行工具，我增加了EVP_DigestSignUpdate和EVP_DigestVerifyUpdate两个函数。编译时就报上面的错误了，我再试试您说的这种情形吧，非常感谢。
