### ISSUE TITLE
lua怎么调用gmssl

### ISSUE THREAD

**Issue by HyoukaLL** [guanzhi/GmSSL#470]
我尝试直接把编译出来的libcrypto.so放到lua相关文件夹下,然后require "libcrypto"
执行代码报错
`lua5.3: error loading module 'libcrypto' from file './libcrypto.so':
	./libcrypto.so: undefined symbol: luaopen_libcrypto`
我在网上查好像是要写一个注册函数的c文件再编译,有没有前辈指点一下!
另:我用luajit的ffi调用libcrypto,在cdef[[]]中声明sm2.h中的函数后有几个数据类型没有定义(EVP_MD等),这种情况该怎么办呢?

或者有其他调用方法,跪谢!!

**Comment by guanzhi** [comment]
跨语言调用的开发要求非常熟悉GmSSL的接口。如果对性能开销的要求不高，建议直接通过类似exec的方式调用gmssl的命令行。gmssl的命令行对内部密码功能和SSL功能的封装是非常完备的，不存在功能缺失的问题，对调用方而言只要了解命令行接口即可，难度要低很多。

**Comment by HyoukaLL** [comment]
@guanzhi 谢谢关老师回答! 那么gmssl的命令行接口有相关的文档么,我之前试好像只有sm4的加密命令

**Comment by J-Feng** [comment]
> 那么gmssl的命令行接口有相关的文档么,我之前试好像只有sm4的加密命令

看到了就顺便回答下

http://gmssl.org/docs/docindex.html

这里的文档，“密码算法”小节下边的各个链接，基本覆盖了大部分gmssl扩展出来的密码算法，其他的命令参考openssl即可。

另外，通过`gmssl XXX -help`能获取子命令的说明。
