### ISSUE TITLE
请问GMBrowser v0.1支持的套件

### ISSUE THREAD

**Issue by liclicli** [guanzhi/GmSSL#472]
请问是否支持ECDHE-SM2-WITH-SMS4-SM3等国密TLS1.2套件？ @zhaoxiaomeng

**Comment by zhaoxiaomeng** [comment]
您好，浏览器中对于目前 GmSSL 中的 SSL 链路中的所有套件都支持。
譬如：
ECDHE-SM2-WITH-SMS4-SM3

**Comment by memdumper** [comment]
@zhaoxiaomeng 请问下GMBrowser会开源吗？

**Comment by memdumper** [comment]
安装提示，无可装载的文件系统。

**Comment by zhaoxiaomeng** [comment]
GMBrowser 目前还在测试开发阶段，未来是否开源有待于进一步考虑。
另外您这边的操作系统是 macOS 的哪个版本？

**Comment by memdumper** [comment]
@zhaoxiaomeng macos 10.10

**Comment by YongqingYu** [comment]
@zhaoxiaomeng  ,您好，请问您是应用mac OS哪一个版本安装GM Browser的？    我 也是采用 mac 10.10，出现 安装提示，无可装载的文件系统
