### ISSUE TITLE
sudo make install有错误！安装GmSSL不成功

### ISSUE THREAD

**Issue by didiyou** [guanzhi/GmSSL#473]
安装不成功

**Comment by didiyou** [comment]
安装不成功，提示不能打开 libssl.so.1.1 共享库

**Comment by zhaoxiaomeng** [comment]
如果报缺少 libsssl libcrypto ，请将 libssl.so.1.1 libcrypto.so.1.1 做软连接到系统动态库目录下。

**Comment by didiyou** [comment]
谢谢赵老师，问题已解决
