### ISSUE TITLE
请问怎么使用SM2生成数字证书

### ISSUE THREAD

**Issue by didiyou** [guanzhi/GmSSL#475]

**Comment by guanzhi** [comment]
http://gmssl.org/docs/quickstart.html

**Comment by zhaoxiaomeng** [comment]
参看文档 http://gmssl.org/docs/quickstart.html

**Comment by sslvpn007** [comment]
@zhaoxiaomeng 

请问下，怎么用代码生成证书请求？

我用代码尝试试了下，是有问题的

EC_GROUP *sm2p256v1_group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
	
EC_KEY * ec_key           = EC_KEY_new();
EC_KEY_set_group(ec_key,sm2p256v1_group);

EC_KEY_generate_key(ec_key);
 if (!(req = X509_REQ_new()))   
        printf("Failed to create X509_REQ object");   
 X509_REQ_set_pubkey(req, pkey); 

后续的过程，就不写了。

生成的证书请求，根本识别不了、

**Comment by bylively** [comment]
> @zhaoxiaomeng
> 
> 请问下，怎么用代码生成证书请求？
> 
> 我用代码尝试试了下，是有问题的
> 
> EC_GROUP *sm2p256v1_group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
> 
> EC_KEY * ec_key = EC_KEY_new();
> EC_KEY_set_group(ec_key,sm2p256v1_group);
> 
> EC_KEY_generate_key(ec_key);
> if (!(req = X509_REQ_new()))
> printf("Failed to create X509_REQ object");
> X509_REQ_set_pubkey(req, pkey);
> 
> 后续的过程，就不写了。
> 
> 生成的证书请求，根本识别不了、

请问一下，您现在实现了证书请求功能了吗？方便提供一下代码吗？

**Comment by bylively** [comment]
> @zhaoxiaomeng
> 
> 请问下，怎么用代码生成证书请求？
> 
> 我用代码尝试试了下，是有问题的
> 
> EC_GROUP *sm2p256v1_group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
> 
> EC_KEY * ec_key = EC_KEY_new();
> EC_KEY_set_group(ec_key,sm2p256v1_group);
> 
> EC_KEY_generate_key(ec_key);
> if (!(req = X509_REQ_new()))
> printf("Failed to create X509_REQ object");
> X509_REQ_set_pubkey(req, pkey);
> 
> 后续的过程，就不写了。
> 
> 生成的证书请求，根本识别不了、

请问下，怎么用代码生成证书请求？

我用代码尝试试了下，是有问题的

EC_GROUP *sm2p256v1_group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);

EC_KEY * ec_key = EC_KEY_new();
EC_KEY_set_group(ec_key,sm2p256v1_group);

EC_KEY_generate_key(ec_key);
if (!(req = X509_REQ_new()))
printf("Failed to create X509_REQ object");
X509_REQ_set_pubkey(req, pkey);

后续的过程，就不写了。

生成的证书请求，根本识别不了、

请问一下，您现在实现了证书请求功能了吗？方便提供一下代码吗？谢谢

**Comment by bylively** [comment]
@sslvpn007 请问一下，您现在实现了证书请求功能了吗？方便提供一下代码吗？
