### ISSUE TITLE
GMSSL利用ENGINE:skf.so调用Ukey的动态库时候，SKF_SetSymmKey出错

### ISSUE THREAD

**Issue by cyncyncyncyncyn** [guanzhi/GmSSL#476]
[Failure]: OPEN_DEV:ES3000GM VCR 1
140131315058496:error:400B1086:SKF routines:SKF_SetSymmKey:invalid parameter:crypto/skf/skf_lib.c:2227:
140131315058496:error:80082040:lib(128):skf_open_dev:fatal:engines/e_skf.c:511:

请问你们自己遇到过这个问题吗  这样导致我OPEN_DEV都不过去，后面的也没法做！
请求帮忙

（ps： skf.so的源码啥时候开源啊？)

**Comment by guanzhi** [comment]
主要可能导致`invalid parameter`错误的原因是传递给`SKF_SetSymmKey`的算法ID不对，一个可能的原因是厂商对算法的定义和GmSSL不一致（GmSSL主要参考了最新的SKF标准，算法定义见头文件`include/openssl/sgd.h`）。GmSSL在SKF模块中`crypto/skf/`中对部分厂商的部分产品（如飞天诚信）做了支持，但是考虑到不同厂商的实现不同，以及同一个厂商的不同产品型号及库版本有差异，因此无法做到对所有产品都做到良好的支持。GmSSL需要和厂商或者用户一起测试此类兼容性原因。这也是GmSSL不开放SKF、SDF Engine源码的原因之一，开源之后，硬件兼容性的问题很难反馈回来。

**Comment by cyncyncyncyncyn** [comment]
我使用的是飞天诚信的ePass3000GM，我按照您的思路对比了GMSSL和Ukey对应开发包的头文件，对SGD_***等几个常用算法ID的定义值是一样的，如SGD_SM1_ECB：0x00000101,  SGD_SSF33_ECB: 0x00000201, SGD_SM4_ECB:0x00000401。  我阅读ePass3000GM的sample例子代码，它里面是先通过SKF_GetDevInfo(,&devInfo); SKF_SetSymmkey(,,devIndo.DevAuthAlgId,,)；进行设置的，它默认获得的devIndo.DevAuthAlgId值为0x00000201,对应是SGD_SSF33_ECB； 我按照你的思路直接设置一个不在sgd.h头文件定义的算法ID值得话确实是会报告invalid param错误。  所以我想问下，skf.so里面也是通过与ePass3000GM类似的方法获取设备的算法ID,再设置的吗？？？还是说写死？？

**Comment by guanzhi** [comment]
另外DevAuthAlgId不应该采用SM1/SSF33等硬实现算法，这样应用必须将认证密钥以明文传递给SKF设备，违背了SKF设备认证的安全初衷。
