### ISSUE TITLE
SM2_encrypt存在内存泄漏

### ISSUE THREAD

**Issue by 77kris** [guanzhi/GmSSL#479]
`
int SM2_encrypt(int type, const unsigned char *in, size_t inlen,
	unsigned char *out, size_t *outlen, EC_KEY *ec_key)
{
	const EVP_MD *md;
	SM2CiphertextValue *cv;

	if (!(md = EVP_get_digestbynid(type))) {
		SM2err(SM2_F_SM2_ENCRYPT, SM2_R_INVALID_DIGEST_ALGOR);
		*outlen = 0;
		return 0;
	}

	RAND_seed(in, inlen);
	if (!(cv = SM2_do_encrypt(md, in, inlen, ec_key))) {
		*outlen = 0;
		return 0;
	}

	*outlen = i2d_SM2CiphertextValue(cv, &out);
	SM2CiphertextValue_free(cv);
	return 1;
}
`

    调用 sm2_enc.c: SM2_encrypt，参数 out 设置为 NULL 时，存在内存泄露。

    i2d_SM2CiphertextValue 函数在 out 为 NULL 时将主动为 out 分配内存，之后没有释放。

**Comment by chenwenjing1234** [comment]
我也遇到了这个问题，这个接口应该接收一个二级指针unsigned char **out，如果只是取长度的时候out传NULL即可。
