### ISSUE TITLE
gmssl算法是否支持椭圆曲线上点的压缩与解压缩

### ISSUE THREAD

**Issue by zypeng1221** [guanzhi/GmSSL#483]
您好，我在查看《GBT 32918.1-2016 SM2椭圆曲线公钥密码算法 第1部分：总则》，第四章节提到椭圆曲线上点的压缩与解压缩。这样SM2的公钥将可以占用更少的字节数。
《GMT 0009-2012 SM2密码算法使用规范》对SM2PublicKey做出规定，使用非压缩方式，Bit String类型，内容是04||X||Y。
$ gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -out private.pem
$ gmssl pkey -pubout -in private.pem -out public.pem
解析了一下我们的公钥部分，与《SM2密码算法使用规范》一致。

我查了一下GmSSL的文档，没有发现有关公钥压缩的内容，我想了解一下，我们的GmSSL是否能够输出压缩形式的SM2公钥(PC=02 或 03)？或者有相关接口支持点的压缩和解压缩？

**Comment by zypeng1221** [comment]
已找到函数，感谢。

**Comment by x-serializer** [comment]
请问那个解压缩的函数叫什么名字。。非常感谢.

**Comment by wushengqiang1** [comment]
同问，调用方法

**Comment by xudogn** [comment]
`    const char *hex = EC_POINT_point2hex(grp, p, POINT_CONVERSION_UNCOMPRESSED, NULL);
    EC_POINT_point2bn(grp, p, POINT_CONVERSION_UNCOMPRESSED, n, NULL);`
压缩未压缩 通过第三个参数来控制：
压缩   POINT_CONVERSION_COMPRESSED， POINT_CONVERSION_UNCOMPRESSED未压缩
