### ISSUE TITLE
GmSSL不支持SHA3吗？

### ISSUE THREAD

**Issue by wdx7266** [guanzhi/GmSSL#484]
在Openssl中提供了：EVP_sha3_224、EVP_sha3_256、EVP_sha3_384等，但是在GmSSL中会提示未定义，所以GmSSL没有提供对SHA3的支持吗？

**Comment by guanzhi** [comment]
目前OpenSSL的正式版本里还没有SHA-3，等正式版本发布后GmSSL会把SHA-3加进来。

**Comment by wdx7266** [comment]
明白了，非常感谢！

**Comment by wdx7266** [comment]
明白了，非常感谢！
