### ISSUE TITLE
使用SM2_do_encrypt得到的结果为乱码

### ISSUE THREAD

**Issue by HyoukaLL** [guanzhi/GmSSL#485]
我用c写了一个供lua调用的动态库,用来实现sm2的加解密,代码如下
`cv = SM2_do_encrypt(EVP_sm3(), (unsigned char *)message1, (size_t)strlen(message1), ec_key);` 
然后问题出现了,不管是`cv->ciphertext->data`还是`i2d_SM2CiphertextValue(cv, &out)`以及`i2o_SM2CiphertextValue(ec_group, cv, &out)`,得到的结果都是一堆乱码
我一开始认为可能是需要把传入信息转换为uft-8编码,但是还是没有用,得到的仍然是乱码
所以想请问下这个函数正确应该怎么用,才能得到正确的加密字符串?

**Comment by zypeng1221** [comment]
加密的结果是乱码不能说明结果就是错的，加密后的unsign char的值从0x00-0xFF，而打印不乱码只有0x00-0x79。

**Comment by HyoukaLL** [comment]
@zypeng1221 但是我把得到的乱码作为参数传入
`cv = d2i_SM2CiphertextValue(NULL, &p, (long)inlen);`
`SM2_do_decrypt(EVP_sm3(),cv,out,outlen,ec_key);`得到的结果是空,如果得到的乱码是正确的结果的话,我应该怎么使用它呢

**Comment by aStudyer** [comment]
@HyoukaLL 我现在也遇到了这个问题 请问你解决了吗  朋友？

**Comment by itollei** [comment]
我也碰到相同的问题，请问最后怎么结局的？

**Comment by Youcai98** [comment]
我也是乱码，加密的结果
