### ISSUE TITLE
gmssl编译问题的相关请教

### ISSUE THREAD

**Issue by Rafaelxue** [guanzhi/GmSSL#488]
我现在写了一个加密库，里面包含国密加密算法，然后我想把我的这个库作为一个静态库提供出去，所以我想问问**怎么把gmssl编译成静态库**，这样可以一次性都包含在我封装好的加密库里面，对外提供也会更简洁

**Comment by Nanguang** [comment]
请问下您解决了这个问题吗？

**Comment by Rafaelxue** [comment]
@Nanguang 你在执行perl Configure VC-WIN32或perl Configure VC-WIN64A指令时在后面加上“no-shared”就可以编译成静态库了，例如：perl Configure VC-WIN32 no-shared或perl Configure VC-WIN64A no-shared
