### ISSUE TITLE
sm2签名算法的一些疑问

### ISSUE THREAD

**Issue by Guokeeng** [guanzhi/GmSSL#489]
@guanzhi 老师您好，我需要用bouncycastle库实现java版，有几个问题请教一下
1.sm2签名算法流程是否与下图一致
2.计算杂凑值时AID是否为默认值1234567812345678
3.是否可以公开一下椭圆参数曲线：p，a，b，xG，yG，n
![sm](https://user-images.githubusercontent.com/39049121/39694456-f849d5ec-5219-11e8-9893-8822c1143784.png)

**Comment by fortime** [comment]
http://www.sca.gov.cn/sca/xwdt/2010-12/17/1002386/files/b965ce832cc34bc191cb1cde446b860d.pdf 官方推荐参数
http://www.sca.gov.cn/sca/xwdt/2010-12/17/1002386/files/b791a9f908bb4803875ab6aeeb7b4e03.pdf 文档第二部分有流程

**Comment by ZZMarquis** [comment]
我们也遇到了这个问题，BC SM2签名GMSSL验不过，GMSSL签名BC验不过，请问你们找到问题所在了吗？

**Comment by ZZMarquis** [comment]
我们同事发现了问题所在：BC是在签名的时候自动做了预处理的。GMSSL需要自己调用SM2_compute_message_digest先做预处理再调用验签接口。签名同理。

**Comment by fortime** [comment]
@ZZMarquis 印象中GMSSL的签名默认是没有计算Z值的，BC里有算。

**Comment by ZZMarquis** [comment]
@fortime 对。GMSSL要自己主动调接口做预处理，我们把这个加上，BC和GMSSL就可以互相签名验签了。
