### ISSUE TITLE
centos下make编译报错，需要什么前提条件吗？

### ISSUE THREAD

**Issue by workcheng** [guanzhi/GmSSL#493]
**系统环境**：CentOS Linux release 7.4.1708 (Core)
**gmssl版本**：https://github.com/guanzhi/GmSSL/archive/gmbrowser-v0.1.tar.gz

**config正常**：
[root@localhost GmSSL-gmbrowser-v0.1]# ./config no-saf no-sdf no-skf no-sof no-zuc
Operating system: x86_64-whatever-linux2
Configuring for linux-x86_64
Configuring GmSSL version 2.3.1 (0x1010004fL)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-gmieng       [default]  OPENSSL_NO_GMIENG
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-saf          [option]   OPENSSL_NO_SAF (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-sdf          [option]   OPENSSL_NO_SDF (skip dir)
    no-sdfeng       [default]  OPENSSL_NO_SDFENG
    no-skf          [option]   OPENSSL_NO_SKF (skip dir)
    no-skfeng       [default]  OPENSSL_NO_SKFENG
    no-sof          [option]   OPENSSL_NO_SOF (skip dir)
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default]
    no-zlib-dynamic [default]
    no-zuc          [option]   OPENSSL_NO_ZUC (skip dir)
Configuring for linux-x86_64
CC            =gcc
CFLAG         =-Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack
SHARED_CFLAG  =-fPIC -DOPENSSL_USE_NODELETE
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_STATIC_ENGINE OPENSSL_PIC OPENSSL_IA32_SSE2 OPENSSL_BN_ASM_MONT OPENSSL_BN_ASM_MONT5 OPENSSL_BN_ASM_GF2m SHA1_ASM SHA256_ASM SHA512_ASM RC4_ASM MD5_ASM AES_ASM VPAES_ASM BSAES_ASM GHASH_ASM ECP_NISTZ256_ASM PADLOCK_ASM GMI_ASM POLY1305_ASM
LFLAG         =
PLIB_LFLAG    =
EX_LIBS       =-ldl
APPS_OBJ      =
CPUID_OBJ     =x86_64cpuid.o
UPLINK_OBJ    =
BN_ASM        =asm/x86_64-gcc.o x86_64-mont.o x86_64-mont5.o x86_64-gf2m.o rsaz_exp.o rsaz-x86_64.o rsaz-avx2.o
EC_ASM        =ecp_nistz256.o ecp_nistz256-x86_64.o
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes-x86_64.o vpaes-x86_64.o bsaes-x86_64.o aesni-x86_64.o aesni-sha1-x86_64.o aesni-sha256-x86_64.o aesni-mb-x86_64.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4-x86_64.o rc4-md5-x86_64.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =md5-x86_64.o
SHA1_OBJ_ASM  =sha1-x86_64.o sha256-x86_64.o sha512-x86_64.o sha1-mb-x86_64.o sha256-mb-x86_64.o
RMD160_OBJ_ASM=
CMLL_ENC      =cmll-x86_64.o cmll_misc.o
MODES_OBJ     =ghash-x86_64.o aesni-gcm-x86_64.o
PADLOCK_OBJ   =e_padlock-x86_64.o
GMI_OBJ       =e_gmi-x86_64.o
CHACHA_ENC    =chacha-x86_64.o
POLY1305_OBJ  =poly1305-x86_64.o
BLAKE2_OBJ    =
PROCESSOR     =
RANLIB        =ranlib
ARFLAGS       =
PERL          =/usr/bin/perl

SIXTY_FOUR_BIT_LONG mode

Configured for linux-x86_64.

**报错信息如下**：

make[2]: Entering directory `/root/gmssl/GmSSL-gmbrowser-v0.1'
LD_LIBRARY_PATH=.: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib64/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -Wl,-znodelete -m64 -shared -Wl,-Bsymbolic -Wl,-soname=padlock.so -o engines/padlock.so engines/e_padlock-x86_64.o engines/e_padlock.o -L. -lcrypto -ldl
make[2]: Leaving directory `/root/gmssl/GmSSL-gmbrowser-v0.1'
gcc  -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DGMI_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib64/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -Wa,--noexecstack -fPIC -DOPENSSL_USE_NODELETE -MMD -MF engines/sdf_dummy.d.tmp -MT engines/sdf_dummy.o -c -o engines/sdf_dummy.o engines/sdf_dummy.c
engines/sdf_dummy.c: In function 'SDF_OpenDevice':
engines/sdf_dummy.c:209:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:209:10: note: each undeclared identifier is reported only once for each function it appears in
engines/sdf_dummy.c:212:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_CloseDevice':
engines/sdf_dummy.c:218:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_OpenSession':
engines/sdf_dummy.c:226:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:228:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_CloseSession':
engines/sdf_dummy.c:234:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:246:2: error: unknown type name 'DEVICEINFO'
  DEVICEINFO *pstDeviceInfo)
  ^
engines/sdf_dummy.c: In function 'SDF_GenerateRandom':
engines/sdf_dummy.c:274:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_GetPrivateKeyAccessRight':
engines/sdf_dummy.c:283:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_ReleasePrivateKeyAccessRight':
engines/sdf_dummy.c:290:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:296:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey)
  ^
engines/sdf_dummy.c:307:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey)
  ^
engines/sdf_dummy.c:318:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:319:2: error: unknown type name 'RSArefPrivateKey'
  RSArefPrivateKey *pucPrivateKey)
  ^
engines/sdf_dummy.c: In function 'SDF_GenerateKeyWithIPK_RSA':
engines/sdf_dummy.c:337:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:341:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:347:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c: In function 'SDF_ImportKeyWithISK_RSA':
engines/sdf_dummy.c:368:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:370:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:376:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:391:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey)
  ^
engines/sdf_dummy.c:402:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey)
  ^
engines/sdf_dummy.c:414:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:415:2: error: unknown type name 'ECCrefPrivateKey'
  ECCrefPrivateKey *pucPrivateKey)
  ^
engines/sdf_dummy.c:428:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucKey,
  ^
engines/sdf_dummy.c:441:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:442:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucKey,
  ^
engines/sdf_dummy.c:454:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucKey,
  ^
engines/sdf_dummy.c:470:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucSponsorPublicKey,
  ^
engines/sdf_dummy.c:471:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucSponsorTmpPublicKey,
  ^
engines/sdf_dummy.c:486:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucResponsePublicKey,
  ^
engines/sdf_dummy.c:487:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucResponseTmpPublicKey,
  ^
engines/sdf_dummy.c:506:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucSponsorPublicKey,
  ^
engines/sdf_dummy.c:507:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucSponsorTmpPublicKey,
  ^
engines/sdf_dummy.c:508:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucResponsePublicKey,
  ^
engines/sdf_dummy.c:509:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucResponseTmpPublicKey,
  ^
engines/sdf_dummy.c:523:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:524:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucEncDataIn,
  ^
engines/sdf_dummy.c:525:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucEncDataOut)
  ^
engines/sdf_dummy.c: In function 'SDF_GenerateKeyWithKEK':
engines/sdf_dummy.c:540:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:542:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_ImportKeyWithKEK':
engines/sdf_dummy.c:554:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:556:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_DestroyKey':
engines/sdf_dummy.c:563:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:568:2: error: unknown type name 'RSArefPublicKey'
  RSArefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:582:2: error: unknown type name 'RSArefPrivateKey'
  RSArefPrivateKey *pucPrivateKey,
  ^
engines/sdf_dummy.c: In function 'SDF_InternalPrivateKeyOperation_RSA':
engines/sdf_dummy.c:603:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:605:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:611:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:614:2: error: unknown type name 'ECCSignature'
  ECCSignature *pucSignature)
  ^
engines/sdf_dummy.c:624:2: error: unknown type name 'ECCSignature'
  ECCSignature *pucSignature)
  ^
engines/sdf_dummy.c:634:2: error: unknown type name 'ECCSignature'
  ECCSignature *pucSignature)
  ^
engines/sdf_dummy.c:642:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c:645:2: error: unknown type name 'ECCCipher'
  ECCCipher *pucEncData)
  ^
engines/sdf_dummy.c: In function 'SDF_Encrypt':
engines/sdf_dummy.c:664:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:666:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_Decrypt':
engines/sdf_dummy.c:680:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:682:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_CalculateMAC':
engines/sdf_dummy.c:696:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:698:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:704:2: error: unknown type name 'ECCrefPublicKey'
  ECCrefPublicKey *pucPublicKey,
  ^
engines/sdf_dummy.c: In function 'SDF_HashUpdate':
engines/sdf_dummy.c:716:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_HashFinal':
engines/sdf_dummy.c:724:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:726:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_CreateFile':
engines/sdf_dummy.c:735:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_ReadFile':
engines/sdf_dummy.c:747:10: error: 'SDR_INARGERR' undeclared (first use in this function)
   return SDR_INARGERR;
          ^
engines/sdf_dummy.c:748:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_WriteFile':
engines/sdf_dummy.c:759:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: In function 'SDF_DeleteFile':
engines/sdf_dummy.c:767:9: error: 'SDR_OK' undeclared (first use in this function)
  return SDR_OK;
         ^
engines/sdf_dummy.c: At top level:
engines/sdf_dummy.c:59:14: warning: 'agreementHandle' defined but not used [-Wunused-variable]
 static char *agreementHandle = "SDF Agreement Handle";
              ^
engines/sdf_dummy.c: In function 'SDF_OpenDevice':
engines/sdf_dummy.c:213:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_CloseDevice':
engines/sdf_dummy.c:219:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_OpenSession':
engines/sdf_dummy.c:229:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_CloseSession':
engines/sdf_dummy.c:235:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_GenerateRandom':
engines/sdf_dummy.c:275:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_GetPrivateKeyAccessRight':
engines/sdf_dummy.c:284:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_ReleasePrivateKeyAccessRight':
engines/sdf_dummy.c:291:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_GenerateKeyWithIPK_RSA':
engines/sdf_dummy.c:342:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_ImportKeyWithISK_RSA':
engines/sdf_dummy.c:371:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_GenerateKeyWithKEK':
engines/sdf_dummy.c:543:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_ImportKeyWithKEK':
engines/sdf_dummy.c:557:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_DestroyKey':
engines/sdf_dummy.c:564:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_InternalPrivateKeyOperation_RSA':
engines/sdf_dummy.c:606:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_Encrypt':
engines/sdf_dummy.c:667:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_Decrypt':
engines/sdf_dummy.c:683:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_CalculateMAC':
engines/sdf_dummy.c:699:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_HashUpdate':
engines/sdf_dummy.c:717:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_HashFinal':
engines/sdf_dummy.c:727:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_CreateFile':
engines/sdf_dummy.c:736:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_ReadFile':
engines/sdf_dummy.c:749:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_WriteFile':
engines/sdf_dummy.c:760:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
engines/sdf_dummy.c: In function 'SDF_DeleteFile':
engines/sdf_dummy.c:768:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [engines/sdf_dummy.o] Error 1
make[1]: Leaving directory `/root/gmssl/GmSSL-gmbrowser-v0.1'
make: *** [all] 错误 2

**Comment by Danbuth** [comment]
我也是这个问题

**Comment by guanzhi** [comment]
似乎问题都是来自于engines目录下的代码.
把./Configure 文件中的`$config{dirs} = [ "crypto", "ssl", "engines", "util" ];`中的engines删掉试试

**Comment by YoungHu** [comment]
> 似乎问题都是来自于engines目录下的代码.
> 把./Configure 文件中的`$config{dirs} = [ "crypto", "ssl", "engines", "util" ];`中的engines删掉试试

去掉以后确实可以编译通过了。
