### ISSUE TITLE
关于SM3WithSM2安全性的疑问

### ISSUE THREAD

**Issue by fortime** [guanzhi/GmSSL#495]
![screenshot from 2018-05-11 10-28-38](https://user-images.githubusercontent.com/532864/39903522-229212d0-5506-11e8-85b6-ff39f7b177be.png)
各位老师好！在进行签名时，若没有进行第一步拼接Z的值，直接对待签名信息进行hash，这样子安全性有区别吗？我们对接的一些厂商就是没有进行第一步。

**Comment by ZZMarquis** [comment]
这应该就是加盐HASH吧，目的是为了不那么容易被字典攻击
