### ISSUE TITLE
java.publicKeyEncrypt 中 EVP_PKEY_encrypt return 0

### ISSUE THREAD

**Issue by huangchouchou** [guanzhi/GmSSL#496]
再使用公钥加密时，sm2encrypt-with-sm3算法名称，加密字节数较小则正常加密，当加密字节数较大，比如我加密了一个7000多个字节时，EVP_PKEY_encrypt 返回0，失败。我保证outbuff是足够大的，并且，我试了除了国密以外的加密算法，感觉正常。
从sm2test中的例子中，可以看到，加密的数据太短，居然还是对数据的描述进行加密，并没有得到验证。目前，我没有找到更好的方法

**Comment by huangchouchou** [comment]
有没有什么接口是，可以设置的呢？

**Comment by guanzhi** [comment]
这个函数是用来加密对称密钥的，因此一般来说不应该输入这么长的数据，如果需要加密数据请用EVP_Seal函数。OpenSSL的EVP_PKEY_encrypt最初只支持RSA加密，加密的数据长度是由RSA模长决定的，比如128字节、256字节，接口上不支持设定输入数据长度。虽然ECIES和SM2加密都支持任意长的数据，但是由于上面的历史原因，导致通过上层接口调用SM2加密时，数据太长会出错，并且底层也没法做判断。

**Comment by AndyWebJava** [comment]
老师。。sm2encrypt-with-sm3这个算法有没有C代码实现。。。

**Comment by AndyWebJava** [comment]
我要死了。。额。。太难了。。
