### ISSUE TITLE
请问一下gmssl命令行加密时出现的问题

### ISSUE THREAD

**Issue by Meepoing** [guanzhi/GmSSL#497]
我使用官方的命令加密
echo "Top Secret" | gmssl pkeyutl -encrypt -pkeyopt ec_scheme:sm2 -pubin -inkey ekey.pem -out ciphertext.sm2

然后报错信息如下：
-pkeyopt command before -inkey
Usage: pkeyutl [options]
-in file        input file
-out file       output file
-sigfile file signature file (verify operation only)
-inkey file     input key
-keyform arg    private key format - default PEM
-pubin          input is a public key
-certin         input is a certificate carrying a public key
-pkeyopt X:Y    public key options
-sign           sign with private key
-verify         verify with public key
-verifyrecover  verify with public key, recover original data
-encrypt        encrypt with public key
-decrypt        decrypt with private key
-derive         derive shared secret
-hexdump        hex dump output
-engine e       use engine e, possibly a hardware device.
-passin arg     pass phrase source

问下这是怎么回事？
在另外的ubuntu16.04下报错信息如下：
140142103422720:error:42067068:BASE58 routines:SM2_encrypt:invalid digest algor:crypto/sm2/sm2_enc.c:237:
140142103422720:error:101030BD:elliptic curve routines:pkey_ec_encrypt:sm2 encrypt failed:crypto/ec/ec_pmeth.c:198:
Public Key operation error

**Comment by suishixingkong** [comment]
我也一样的错

**Comment by suishixingkong** [comment]
找到解决办法了
修改crypto/ec/ec_pmeth.c第66行为dctx->ec_encrypt_param = NID_sm3;
重新编译安装，然后就可以了

**Comment by jydxx61** [comment]
我也遇到这个问题, 按照上面的修改ec_pmeth.c的方法, 解决了加密的问题.

**Comment by pengtianabc** [comment]
增加参数即可，看命令行最后的sm3参数

`gmssl pkeyutl -encrypt -in openvpnserver.tar.gz -inkey vrfykey.pem -pubin -out fjalfkja.enc2  -pkeyopt ec_scheme:sm2 -pkeyopt  ec_encrypt_param:sm3 `
