### ISSUE TITLE
请问下对国密双证书，以及TLS协议的支持情况

### ISSUE THREAD

**Issue by suxiaoyv** [guanzhi/GmSSL#498]
请教下几个问题
当前版本 pre-release 2.0 

1. 是否支持国密双证书的生成？具体如何生成，有没有相关的demo？
2. 文档中介绍 gmssl 遵循《GM/T 0024-2014 SSL VPN 技术规范》，但是规范上是参照TLSv1.1协议，引入双证书体制，但是 gmssl release 中是说 使用的是 TLSv1.2 的协议，这方面的支持情况呢？

多谢~

**Comment by duoluodexiaokeke** [comment]
也有同样的问题，感觉现在通信貌似是不支持国密的一样
因为也没有再代码中找到相关的信息

**Comment by duoluodexiaokeke** [comment]
如果使用加密卡，根据国密局的相关文档，可以是单向证书应该没有问题

发件人: strongbug <notifications@github.com>
发送时间: 2018年7月4日 9:28
收件人: guanzhi/GmSSL <GmSSL@noreply.github.com>
抄送: Liu, Lei <lei.liu@esgyn.cn>; Comment <comment@noreply.github.com>
主题: Re: [guanzhi/GmSSL] 请问下对国密双证书，以及TLS协议的支持情况 (#498)


国密规范中要求的必须是双证书体系吗？@suxiaoyv<https://github.com/suxiaoyv>
