### ISSUE TITLE
gmssl和openssl混用的问题

### ISSUE THREAD

**Issue by calvinwilliams** [guanzhi/GmSSL#50]
我的redhat linux安装时系统已经预置了openssl-0.9.8，为了不妨碍原有openssl使用，我把gmssl编译安装到了普通用户里，应用链接普通用户里的gmssl（ln -s ~/lib/openssl-1.0.1-gmssl.so ~/lib/libcrypto.so），使用没问题，但是系统自带的ssh、sftp一直报错：“OpenSSL version mismatch , Built against 90802f , you have 10201000”，因为ssh、sftp发现链接的gmssl和系统预置的openssl版本不对，请问怎么解决？我的应用链接了第三方共享库，这个库ldd出来链接了libcrypto。

**Comment by LiTianjue** [comment]
静态编译是最好的办法，毕竟GmSSL只用在特定的程序上
况且即使原版的openssl 通过源码升级也会有你这个问题的

**Comment by calvinwilliams** [comment]
静态编译进可执行程序也有问题，我的应用链接了第三方共享库，这个库ldd出来链接了libcrypto(openssl)

**Comment by LiTianjue** [comment]
等于说你要用GmSSL ，又要用openssl 了？ 
那你把这个第三方库也用GmSSL编译一遍行不行

**Comment by calvinwilliams** [comment]
第三方库和可执行程序属于一个公司的产品，不可能给我源代码 ^_^

**Comment by LiTianjue** [comment]
1. 试试编译时指定链接的动态库路径的方法看看行不行，让程序只链到GmSSL库，GmSSL应该完整保留了OpenSSL的功能
2. 将用到的GmSSL的接口再封装一层API出来用

这是我能想到的，你试试看吧

**Comment by calvinwilliams** [comment]
第三方公司的产品平台已经链接了-lcrypto，这个我没办法修改（同上如果做了crypto链接指向gmssl库将会影响ssh、sftp等系统自带软件），我的应用程序（在第三方公司平台上跑的）为了实现国密编译链接了改名后的libcrypto-1.0.1-gmssl.so，现在运行暂时没问题，但是一个进程同时挂接了包含相同符号的两个openssl库将来会不会出问题就难说了，呵呵。

**Comment by LiTianjue** [comment]
1. 如果不在编译的时候指定路径，那么在运行之前可以增加一个用户链接库路径（export LD_LIBRARY_PATH=），指向GmSSL库的路径，系统会优先加载用户路径，再去找系统路径，
所以
不要改名字，
不要改名字，
不要改名字，
,第三方连接了-lcrypto 不妨碍你指定用哪个库，这样无论是你自己的代码，还是第三方库，都会使用GmSSL的库，且不会影响ssh,stp等

2.另外我上面说的方法二应该是可行的，你先编译得到静态的GmSSL库，再把你需要的API做二次封装成动态库，导出不一样的函数名，就不会有命名冲突了，但这实在是太笨了

两个都是我想当然的回答，没有实践过，等大神来回答你，我退下了

**Comment by calvinwilliams** [comment]
指定了LD_LIBRARY_PATH会影响ssh,sftp。我再想想。谢谢你 ^_^

**Comment by LiTianjue** [comment]
sorry i have no pinyin input method here
i mean do not put " export LD_LIBRARY_PATH= " to .bashrc  or /ect/profile or other  global setting ,you can write it in an script with you cmd program . like
'''c
#!/bin/bash
export LD_LIBRARY_PATH=path_to_your_lib
yourCMD   cmdopt
'''
or just export it by hand ,

**Comment by calvinwilliams** [comment]
我们是应用于一个平台，上面有很多应用和脚本，每个前后都临时改变LD_LIBRARY_PATH改造工作量很大，而且会让代码很难看 ^_^

**Comment by guanzhi** [comment]
我们可以尝试为RedHat等发行版提供安装包来解决这个问题。

**Comment by calvinwilliams** [comment]
赞
