### ISSUE TITLE
编译通过，Java调用失败

### ISSUE THREAD

**Issue by workcheng** [guanzhi/GmSSL#500]
编译成功，console正常使用：
![image](https://user-images.githubusercontent.com/9999969/40595960-6f840000-626a-11e8-8fc8-878745465da0.png)
执行源码中Java目录下的test.sh
![image](https://user-images.githubusercontent.com/9999969/40596012-c28c129c-626a-11e8-9b5a-aa2dd398bc5c.png)
报错如下：
 `Exception in thread "main" java.lang.UnsatisfiedLinkError: no gmssljni in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at GmSSL.<clinit>(GmSSL.java:241)`

**Comment by shijl80** [comment]
同样的问题，centos7.4下，按照文档java编译那段修改后编译不通过，不编译java就可以编译成功。
![image](https://user-images.githubusercontent.com/37890252/43701238-073ccba8-9988-11e8-8cd8-638d0de1b2ab.png)

**Comment by workcheng** [comment]
建议对GmSSL.java中的方法进行注释说明一下是做什么用的

**Comment by yskcoder** [comment]
> 同样的问题，centos7.4下，按照文档java编译那段修改后编译不通过，不编译java就可以编译成功。
> ![image](https://user-images.githubusercontent.com/37890252/43701238-073ccba8-9988-11e8-8cd8-638d0de1b2ab.png)

我这边的问题和你是一样的，请问你有解决了没有

**Comment by shijl80** [comment]
> > 同样的问题，centos7.4下，按照文档java编译那段修改后编译不通过，不编译java就可以编译成功。
> > ![image](https://user-images.githubusercontent.com/37890252/43701238-073ccba8-9988-11e8-8cd8-638d0de1b2ab.png)
> 
> 我这边的问题和你是一样的，请问你有解决了没有

已放弃，换成bc-java了

**Comment by knull-cn** [comment]
> 同样的问题，centos7.4下，按照文档java编译那段修改后编译不通过，不编译java就可以编译成功。
> ![image](https://user-images.githubusercontent.com/37890252/43701238-073ccba8-9988-11e8-8cd8-638d0de1b2ab.png)

![image](https://user-images.githubusercontent.com/5057528/56705158-67e3de00-6742-11e9-9a98-d23d6db2f227.png)
这个问题报错是因为那个map，直接把语句拷贝出来，删除红框部分，就可以编译通过了
