### ISSUE TITLE
SAF_EccPublicKeyEnc

### ISSUE THREAD

**Issue by zgrztzy** [guanzhi/GmSSL#501]
![default](https://user-images.githubusercontent.com/9442737/40637001-f7dbdd4a-6334-11e8-94f5-d99fc8968512.png)

if (uiPublicKeyLen != sizeof(ECCrefPublicKey)) 
pucPublicKey 是asn编码的证书，长度！=sizeof(ECCrefPublicKey)

**Comment by guanzhi** [comment]
请参考 #709
