### ISSUE TITLE
能否提供完整的国密证书生成和s_client/server系列命令

### ISSUE THREAD

**Issue by iF2007** [guanzhi/GmSSL#503]
已有issue中集中了很多国密证书生成和s_client、s_server测试失败的问题
能否以某个release或master branch给出一个完整的国密证书生成和s_client/server系列命令？

@guanzhi 
@zhaoxiaomeng

**Comment by liclicli** [comment]
刚刚用master(commit:0adf4ce)试验了一下
server端
./gmssl s_server -gmtls -accept 8443 -cert /root/TASSL-master/Tassl_demo/mk_tls_cert/sm2Certs/SS.cert.pem -key /root/TASSL-master/Tassl_demo/mk_tls_cert/sm2Certs/SS.key.pem -dcert /root/TASSL-master/Tassl_demo/mk_tls_cert/sm2Certs/SE.cert.pem -dkey /root/TASSL-master/Tassl_demo/mk_tls_cert/sm2Certs/SE.key.pem -msg -debug
client端
./gmssl s_client -connect 127.0.0.1:8443 -msg -debug -gmtls
可以通讯成功；注意s_server证书顺序一定是先签名证书再加密证书

**Comment by iF2007** [comment]
@liclicli 验证可以正常通信。感谢，解决了长久以来困扰我的问题。这个命令真应该加到readme信息中

**Comment by liclicli** [comment]
@iF2007 但是GMSSL和TASSL相互之间不能通讯，肯定是至少有一方的实现有问题...

**Comment by liclicli** [comment]
@iF2007 能否测看看TASSL是否可以和中行的握手呢？

**Comment by loveyou30** [comment]
@iF2007 请问如何跟中行的测试呢？中行是有个对外的地址么？多谢

**Comment by iF2007** [comment]
@loveyou30 https://ebssec.boc.cn

**Comment by loveyou30** [comment]
@iF2007 好的，收到，多谢

**Comment by xiejianjun417** [comment]
@liclicli 请问一下，什么是签名证书呀？gmssl怎么生成呢？

**Comment by zhaoxiaomeng** [comment]
@xiejianjun417  gmssl 编译后 apps 目录下有 gmca，可以使用相关命令生成签名证书，详细参看 .apps/gmca/test.sh

**Comment by bethewind** [comment]
今天最新的代码，在wireshark里可以抓到tls成功的包，供大家参考
先执行apps/gmca/里的test.sh生成ca，然后执行下面的命令启动server/client
-verify参数是是否验证对方的证书
-cipher指定加密套件算法

GmSSL/apps$./gmssl s_server -accept 4333 -CAfile gmca/.ca/cacert.pem -cert gmca/.ca/certs/01.pem -key gmca/.ca/keys/alice@pku.edu.cn.key -tls1_2 -debug -msg -verify 1 -cipher ECDHE-SM2-WITH-SMS4-SM3

GmSSL/apps$ ./gmssl s_client -connect localhost:4333 -CAfile gmca/.ca/cacert.pem -cert gmca/.ca/certs/02.pem -key gmca/.ca/keys/bob@pku.edu.cn.key -tls1_2 -showcerts -msg -debug -verify 1

**Comment by xiejianjun417** [comment]
@zhaoxiaomeng 好的，谢谢

**Comment by Stan1987** [comment]
@bethewind 你好，我想问一下debug打印出来的内容中，Master-Key指的是预主密钥吗？有没有办法看到主密钥是什么呢？
