### ISSUE TITLE
GmSSL-2.3.1没有找到skf.so，修改configure使能skf后编译报错，请问skf.so怎么获得，怎么进行硬件测试？谢谢

### ISSUE THREAD

**Issue by abgceagle** [guanzhi/GmSSL#504]
GmSSL-2.3.1默认没有sfk，修改configure注释掉"skfeng"              => "default", 后编译报错，看之前有个issues有提到skf.so，但是 2.3.1版本没有找到，请问skf.so怎么获得，怎么进行ukey的硬件测试？谢谢

**Comment by guanzhi** [comment]
单位可以申请一个测试的U盾和配套的SKF动态库(U盾厂商的)和SKF引擎动态库(skf.so)
