### ISSUE TITLE
网络抓包，验证签名失败，求解？

### ISSUE THREAD

**Issue by Jason0401** [guanzhi/GmSSL#505]
加密套件用的是ECDHE-SM2-WITH-SMS4-SM3（0xE102），签名算法用的是0x0707

1. 
-----BEGIN CERTIFICATE-----
MIIB1DCCAXqgAwIBAgIJAJ18vCvqycz4MAoGCCqGSM49BAMCMEUxCzAJBgNVBAYT
AkNOMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRn
aXRzIFB0eSBMdGQwHhcNMTgwNTE0MTkwMjUwWhcNMTgwNjEzMTkwMjUwWjBFMQsw
CQYDVQQGEwJDTjETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJu
ZXQgV2lkZ2l0cyBQdHkgTHRkMFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEAZc6
emmWX1b50rqB8+uIZzTLjw6mfJMZLecCml7KhY4YynNPBdyQY1oT8cHiJuUPNfV7
TzhEFl2QNRXtlNNW5aNTMFEwHQYDVR0OBBYEFNUHkuwbsBSxwNjzF/C1/Al7gZZs
MB8GA1UdIwQYMBaAFNUHkuwbsBSxwNjzF/C1/Al7gZZsMA8GA1UdEwEB/wQFMAMB
Af8wCgYIKoZIzj0EAwIDSAAwRQIgWacgWuVeqfcnd0vxypnrDVkwSTHzw+SWdWZj
myMvZWQCIQDF8a91jahrRqTDtJ9KkGmRwTRCGD/PGqN+eguWWplGVw==
-----END CERTIFICATE-----
2. ClientHello客户端随机数
0xaf19135787537118c1821eda4c62bad7c58398ba3111b96c5a90056af8225aa2
3. ServerHello服务端随机数
0xc20e6c9e03e4f9b0db25bbe6a1d46e8543ee35dee2253b57d6fed06beda86ff5
4. ServerkeyExchange服务端ECDH参数0x03001e410492f52a5d8bf9d7dfa8d0b752821940f2b5516bc0ca0b36817b32fa4618d1af7f23460d00bd098d3311627005e35d8e07cd1501ea1ffd518883c5c9af8a912717
5. ServerKeyExchange服务端签名（不包括签名的长度，长度是0x48）
0x3046022100e6b61ef52f86997943d8c1115e3bbd6b9b2e14a52b51e8f768cbe311be0d6b65022100887f6ed7457aad33d7838e6f5695b3d04513d3d21f93144959e53dff519cd594

我有看gmssl的源码，不确定是不是用的static int gmtls_construct_ske_sm2(SSL *s, unsigned char **p, int *l, int *al)这个函数？我自己还原了好几次摘要都验证签名失败了....T_T

求大神帮我还原一下进行sm2签名前的摘要！！！
网络上抓取的签名，我将其从HEX一一转为ASCII码形式，是否可以用于gmssl verify命令的验签？

**Comment by duoluodexiaokeke** [comment]
请问一下这个加密套件怎么使用的呢？
我的代码
   n = SSL_CTX_use_certificate_file(pMachine->pCtx, szCertificateFile, SSL_FILETYPE_PEM);
    die_unless(n > 0);

    n = SSL_CTX_use_PrivateKey_file(pMachine->pCtx, szKeyFile, SSL_FILETYPE_PEM);
    die_unless(n > 0);

    pMachine->pSSL = SSL_new(pMachine->pCtx);
    die_unless(pMachine->pSSL);

    /* n = SSL_set_cipher_list(pMachine->pSSL, "SM2-SM4-SM3"); */
    n = SSL_set_cipher_list(pMachine->pSSL, GMTLS_TXT_ECDHE_SM2_WITH_SMS4_SM3);

但是客户端不知道为什么一直不能和服务端建立连接

**Comment by iF2007** [comment]
@Jason0401 你的问题解决了吗？我有很相似的问题

**Comment by Jason0401** [comment]
@iF2007  解决了

**Comment by iF2007** [comment]
@Jason0401 请问你是如何解决的？修改了哪些文件？

**Comment by Jason0401** [comment]
先算z值，再算摘要，根据私钥验证签名

**Comment by iF2007** [comment]
@Jason0401 gmtls_process_ske_sm2函数中也是先算SM3(Z)，然后加上两个随机数和加密证书后进行SM3进行验证的。但是对测试网站的签名无法验证。

你用的哪个测试网站？

**Comment by Jason0401** [comment]
我是用公司自己的后台和客户端抓得包，使用的版本是gmssl2.0，加密套件如题，可以参考源码/test/sm2test.c这个文件，里面有一个函数SM2_compute_message_digest()可以一步算出待签名数据，该函数内部包含了SM2_compute_id_digest()计算了Z值，你不用单独计算Z值了，SM2_compute_message_digest()入口参数比较多，你准备好就行。
后面再用SM2_verify验证。

**Comment by iF2007** [comment]
@Jason0401 谢谢回复。我也用到这个函数了，只是比较奇怪和中国银行的握手签名验证一直失败。。你用gmssl的s_client/s_server成功握手过吗？或者，有没有比较好的能测试成功gmssl的握手的方法建议？谢谢

**Comment by Jason0401** [comment]
我没用过s_client和s_server
函数没返回错误不代表摘要就计算对了
你应该是数据的格式没写对，导致摘要算错了
