### ISSUE TITLE
请教命令行生成sm2签名的问题，非常感谢

### ISSUE THREAD

**Issue by wumingyuan** [guanzhi/GmSSL#508]
arm平台，已编译成功。
拿到了私钥字符串，形如“C9F699DC1EB82AC8A0F508F045D70D70887AF5D532C7C08A8F6AB3A6243978B3”，现在要对32字节的数据进行签名，产生64字节的签名信息，请教该如何操作？

试了Quick Start中提到的类似命令，结果报错（但没有进一步错误信息）：
host:# gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -out signkey.pem
host:# gmssl pkeyutl -sign -pkeyopt ec_sign_algor:sm2 -inkey signkey.pem -in /msg  -out msg.sig
pkeyutl: Can't set parameter:
host:#

**Comment by wumingyuan** [comment]
补充：不带userid

**Comment by Jason0401** [comment]
我去掉了-pkeyopt选项及其后面的参数就可以了

**Comment by wumingyuan** [comment]
非常感谢，果然如此。
生成的sm2签名中，请教哪部分是真正的64字节签名数据？

**Comment by zypeng1221** [comment]
签名数据是长度 71 - 72 字节的一串数据。
64签名数据应该是指r||s模式，这个需要转换，使用ECDSA_SIG_get0函数将rs分量提取出来。
命令行如何操作不太了解。

**Comment by wumingyuan** [comment]
去掉“-pkeyopt 选项及参数”后，生成的sm2签名，用“sm2算法验证工具”进行验证，结果失败，不知道跟这个有没有关联

**Comment by Jason0401** [comment]
-pkeyopt ec_scheme:sm2

**Comment by wumingyuan** [comment]
验证了一下，增加“-pkeyopt ec_scheme:sm2”后，还是验证失败。
不知道生成sm2签名时，内部是否自动进行了sm3摘要计算？

**Comment by wumingyuan** [comment]
最后没用命令行，api调用搞定了，非常感谢楼上各位。
