### ISSUE TITLE
请问怎样将hex格式的sm2私钥，转换为常用的秘钥文件并用密码保护起来？

### ISSUE THREAD

**Issue by wumingyuan** [guanzhi/GmSSL#510]
用“sm2算法工具”生成的sm2私钥，hex格式，形如：DBA95F75B596826B4E41AE8F43BE2BD5F27433339EAFCA98911CA94EA6993BA5，想转成gmssl/openssl常用的秘钥文件（带密码保护），该怎样转换呢？谢谢。

**Comment by guanzhi** [comment]
目前命令行不支持这个功能。
可以先通过`EC_KEY_new_by_curve_name(NID_sm2p256v1)`生成一个SM2密钥，然后用`EC_KEY_set_private_key()`设置私钥，并导出为一个不加密的EC私钥。然后再用命令行去转化为PKCS#12格式。

**Comment by ChiTatZhang** [comment]
> 从2.4版开始，GmSSL提供了sm2、sm2utl命令用于SM2相关的计算。
>将SM2私钥整数值转换为PEM格式的私钥
> gmssl sm2 -inform t -in skey.txt -out skey.pem
@guanzhi 老师你好，我尝试使用命令行模式将SM2私钥整数值转换为PEM格式的私钥会出现下列错误
`140672328255232:error:0F076066:common libcrypto routines:OPENSSL_hexstr2buf:illegal hex digit:crypto/o_str.c:178:`
使用的私钥整数值即hex格式，形如：
DBA95F75B596826B4E41AE8F43BE2BD5F27433339EAFCA98911CA94EA6993BA5
请问我的理解是否有误？亦或使用方法和环境有误
