### ISSUE TITLE
请问使用ECDHE_SM2_WITH_SMS4_SM3这个加密套件，“偷听者”还有办法得到预备主密钥以及工作密钥吗？

### ISSUE THREAD

**Issue by Jason0401** [guanzhi/GmSSL#513]
我用gmssl ciphers -V查看该加密套件，发现kx=ECDH，难道不应该是ECDHE吗？
ECDH使用的是固定的DH key，而ECDHE使用的是一次性的DH key，所以这个加密套件到底用的是ECDH，还是ECDHE

如果是ECDHE，“偷听者”还有办法得到预备主密钥以及工作密钥吗？
@guanzhi

**Comment by iF2007** [comment]
看国密SSL标准对于ServerKeyExchange的定义，应该是固定的ECDH Key，而不是ephemeral的。
所以一直以来，我对这个名称也有疑问，更准确的应该是ECDH_SM2_WITH_SMS4_SM3

**Comment by Jason0401** [comment]
我每次运行获得的ServerKeyExchange以及ClientKeyExchange里的pubkey是不一样的，我依据这一点判断应该还是ECDHE的，具备前向安全性
