### ISSUE TITLE
这里SM4_XTS算法的key_len是否应该为128bit*2？参照AES_XTS_128的设置，里面会取结构体定义的密钥长度的一半来取key2

### ISSUE THREAD

**Issue by kerry0417** [guanzhi/GmSSL#515]
https://github.com/guanzhi/GmSSL/blob/0adf4ce188bde5f9bdfcdf2b5859b1f0c687e64f/crypto/evp/e_sms4_xts.c#L170

**Comment by troyseed** [comment]
我这边将这个定义修改为SMS4_KEY_LENGTH*2之后，计算结果正确，没修改之前XTS计算结果是错误的

**Comment by guanzhi** [comment]
你可以提供一个pull request吗？
