### ISSUE TITLE
GMTLS对tlsext的支持

### ISSUE THREAD

**Issue by liclicli** [guanzhi/GmSSL#517]
@guanzhi @zhaoxiaomeng 
GM/T 0024-2014没有对tlsext的使用情况进行说明，在GMSSL中针对s->version != GMTLS_VERSION避免了tlsext的产生，但是没有去除TLS_EMPTY_RENEGOTIATION_INFO_SCSV SCSV该虚套件；
由于虚套件的存在，实际使用其他国密SSL软件时，可能在server_hello中增加rfc5746规定的重协商扩展；而GMSSL作为客户端时，会跳过server_hello扩展部分，导致SSL_R_BAD_PACKET_LENGTH错误；
建议修改 ssl_parse_serverhello_tlsext 函数，对国密协商尝试进行扩展处理，可达到更高的兼容性；
```C
int ssl_parse_serverhello_tlsext(SSL *s, PACKET *pkt)
{
    int al = -1;

    if (!SSL_IS_GMTLS(s) && s->version < SSL3_VERSION) //版本为GMTLS应尝试解析tlsext而不是跳过
        return 1;

    if (ssl_scan_serverhello_tlsext(s, pkt, &al) <= 0) {
        ssl3_send_alert(s, SSL3_AL_FATAL, al);
        return 0;
    }

    if (ssl_check_serverhello_tlsext(s) <= 0) {
        SSLerr(SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT, SSL_R_SERVERHELLO_TLSEXT);
        return 0;
    }
    return 1;
}
```
另外GMSSL与TASSL通讯时还存在其它问题，将继续排查

**Comment by liclicli** [comment]
@guanzhi @zhaoxiaomeng 
GMSSL作为服务端时，对client_hello中的tlsext会进行处理，但是construct_server_hello时，直接跳过产生tlsext；导致的问题是处理client_hello的时候已经将某些扩展标志位置入，但是未发送在sever_hello中的相关tlsext；最终导致发送冗余握手信息导致握手失败；
典型的例子是tlsext_ticket_key。client携带tlsext_ticket_key，GMSSL接收后tlsext_ticket_expected置为1，但是却没有发送相应的tls_ext，导致GMSSL发送NewSessionTicket时客户端无法识别，连接断开；
建议GMSSL服务端保留处理tlsext能力
statem_srvr.c:1656
```C
    if ((s->version != GMTLS_VERSION) && (p =                                          //去掉对GMTLS的判断，保留tlsext
         ssl_add_serverhello_tlsext(s, p, buf + SSL3_RT_MAX_PLAIN_LENGTH,
                                    &al)) == NULL) {
        ssl3_send_alert(s, SSL3_AL_FATAL, al);
        SSLerr(SSL_F_TLS_CONSTRUCT_SERVER_HELLO, ERR_R_INTERNAL_ERROR);
        ossl_statem_set_error(s);
        return 0;
    }
```

**Comment by liclicli** [comment]
gmtls_new_cert_packet这个函数有bug，
*l = n + 3;而不是*l = n;

几点修改后可以与TASSL建连并互发消息

**Comment by liclicli** [comment]
GMSSL会尝试从证书中读取一部分内容作为zid，而不是直接使用默认的zid。这个和其它产商的实现也不一样，如果对接的时候需要注意这部分也得修改

**Comment by guanzhi** [comment]
@liclicli 是否可以邀请你加入GmSSL项目组来开发SSL部分？

**Comment by 403705726** [comment]
@liclicli 您好，方便给个联系方式吗，想咨询下关于tls扩展项的问题，比如encrypt_then_mac还有session_ticket
