### ISSUE TITLE
有谁把SM2 从Openssl 里面分离出来的没有？

### ISSUE THREAD

**Issue by iwkoo** [guanzhi/GmSSL#518]

**Comment by zhenyuwei** [comment]
SM2本身就是椭圆曲线换了一个点，分离出来不是要把整个椭圆曲线的流程全部实现？

**Comment by zhenyuwei** [comment]
http://www.scctc.org.cn/templates/Download/index.aspx?nodeid=71
这个网址看一下，是否符合你的需求。

**Comment by guanzhi** [comment]
目前SM2的代码依赖BN、EC、RAND、ASN.1等组件，因此不能单独把SM2的代码移出来。
