### ISSUE TITLE
GmSSL 2.3.1 支持读取基于国密生成的证书吗?

### ISSUE THREAD

**Issue by jovijovi** [guanzhi/GmSSL#519]
GmSSL版本: GmSSL 2.3.1 - OpenSSL 1.1.0d  30 Mar 2018
Linux版本: 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

使用如下命令可正确查看证书的所有信息吗? 其中, cert.pem 使用sm2sign-with-sm3算法签名.
gmssl x509 -in cert.pem -text

**Comment by zhenyuwei** [comment]
可以的。
