### ISSUE TITLE
GmSSL 2.3.1 可以和 openssl 1.1.0d 及以上版本共存吗？

### ISSUE THREAD

**Issue by jovijovi** [guanzhi/GmSSL#520]
开发环境: ubuntu 16.04 LTS(64位)
重现步骤:
1. 编译并安装 openssl 1.1.0d
2. 编译并安装 gmssl 2.3.1
3. 调用 openssl 时会报如下错误。调用 gmssl 正常。
openssl: /usr/local/lib/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openssl)

所以，GmSSL 2.3.1 可以和 openssl 1.1.0d 及以上版本共存吗？还是需要什么操作？谢谢！

**Comment by iF2007** [comment]
可以自己指定`--prefix`

**Comment by guanzhi** [comment]
你可以用`./config no-shared`来指定以静态编译，这样编译出来的可执行文件不依赖动态库。

**Comment by jydxx61** [comment]
我也遇到这个问题, 谢谢关老师, 也解决了我的问题.

**Comment by iF2007** [comment]
@MagShadow ./Configure 编译时
