### ISSUE TITLE
Encrypted Handshake Message为什么长度是80个字节？

### ISSUE THREAD

**Issue by Jason0401** [guanzhi/GmSSL#522]
Finished消息是4字节的头部+12字节的verify_data，共计16字节；
client_write_key是16字节；
使用sms4加密（是cbc模式吗？）后，密文长度是多少字节？16字节还是80字节？

**Comment by Jason0401** [comment]
static unsigned char finished_msg[DTLS1_HM_HEADER_LENGTH +
                                      TLS1_FINISH_MAC_LENGTH] = {
        0x14, /* Finished */
        0x00, 0x00, 0x0c, /* Length */
        0x00, 0x03, /* Seq# 3 */
        0x00, 0x00, 0x00, /* Fragment offset */
        0x00, 0x00, 0x0c, /* Fragment length */
        /* Finished MAC (12 bytes) */
    };
finished消息是24字节？

**Comment by wojiushiwoba** [comment]
在发送finished消息时，已采用加密消息。在加密消息时，TLS协议采用的是一般使用encrypot-then-mac，就是说在做消息加密前，会先计算消息鉴别码，放在明文消息之后，然后做对称加密。比如明文数据是16字节，最后加密的数据长度是16+MAC长度。AMC长度我了解的是64字节。
以上是我个人见解，如有错误还望看到的同学们指正。

**Comment by yunlai** [comment]
finish的加密消息是不是要参考AEAD_SM4_128_CCM 手册，这个资料怎么404了
