### ISSUE TITLE
sm4 ecb加密的问题

### ISSUE THREAD

**Issue by zhangzq71** [guanzhi/GmSSL#523]
sm4 ecb加密16个全是0xFF的字节，Key也是16个字节，加密的结果应该也是16个字节长度才对吧，但我得到48个字节，我是用下面的命令加密的
gmssl enc -sms4-ecb -in in.sm4 -out out.sm4 -kfile key -nosalt

in.sm4和key都是16个全是0xFF的文件。命令完成后out.sm4的长度是32个字节。

**Comment by zhangzq71** [comment]
这个是算法选择的问题，我现在不搞这个了。做了一个FPGA的SM4 IP.

**Comment by zjhzzz** [comment]
他这个ECB要怎么选择呢

**Comment by zjhzzz** [comment]
老哥 能说详细点吗

**Comment by zhangzq71** [comment]
就是不要选sms4-ecb，选其他SM4的算法

**Comment by zjhzzz** [comment]
。。。好吧  我就是需要ECB模式的 一个项目要求

**Comment by zjhzzz** [comment]
那估计只能去 找C源码  然后嵌入python了
