### ISSUE TITLE
o2i_SM2CiphertextValue 函数说明

### ISSUE THREAD

**Issue by bylively** [guanzhi/GmSSL#526]
关老师您好
请问一下SM2CiphertextValue *o2i_SM2CiphertextValue(const EC_GROUP *group, const EVP_MD *md,
	SM2CiphertextValue **cv, const unsigned char **pin, long len);这个函数的len表示什么含义？我该如何传参。谢谢指导

**Comment by guanzhi** [comment]
SM2加密算法的早期文本中的密文直接是几个部分的拼接，在正式的标准中改为采用ASN.1/DER编码。这组函数主要是在SM2CipherValue和老式编码之间做转换，这个函数是将编码的数据转为SM2CipherValue内部类型，pin是输入的编码字节，len是输入的长度，cv是返回值。

**Comment by guanzhi** [comment]
这组函数是用来支持测试用的，应用应该调用`i2d_SM2CipherValue`和`d2i_SM2CipherValue`做编解码

**Comment by pengtianabc** [comment]
关老师您好，我在使用`i2d_SM2CiphertextValue`的时候出现了一个问题，生成的DER数据x分量的长度为0x21(多了一个00)，y分量为0x20，这个结果传给sm2解密的时候就出错了。疑问就是

1. 为什么会多一个00
2. 为什么多一个00会解密失败

![j43786i md0g3x v8 8z o](https://user-images.githubusercontent.com/13852782/43950336-9e981042-9cc2-11e8-91f6-ba13cd55b14f.png)
