### ISSUE TITLE
为什么tls1_PRF()使用的摘要算法是SHA256，而非SM3

### ISSUE THREAD

**Issue by Jason0401** [guanzhi/GmSSL#527]
我使用的是gmssl2.0，加密套件为ECDHE_SM2_WITH_SM4_SM3，
我找了下原因，是因为版本不是gmtls1_1，但是为什么不是呢

**Comment by merlinxcy** [comment]
我也遇到这个问题，看了资料说PRF计算Master_secret是使用SM3的算法，但不知道该怎么做。
