### ISSUE TITLE
命令行指令问题

### ISSUE THREAD

**Issue by oilime** [guanzhi/GmSSL#53]
生成sm2密钥指令：
`gmssl genkey -algorithm EC -out sm2key.pem \
        -pkeyopt ec_paramgen_curve:sm2p256v1 \
        -pkeyopt ec_param_enc:named_curve`

此处 genkey 是否应为 genpkey?

**Comment by songgeng87** [comment]
非对称的密钥都是成对生成的，单独生成public key没有意义~~~

**Comment by oilime** [comment]
1.此处genpkey生成的是私钥
2.openssl或gmssl的命令行指令并没有'genkey'这样一个接口
