### ISSUE TITLE
条件编译时OPENSSL_NO_GMTLS要不要使用？

### ISSUE THREAD

**Issue by Jason0401** [guanzhi/GmSSL#530]

**Comment by Jason0401** [comment]
您好，关老师！
有个问题请教一下...
gmssl2.0时在编译时默认是定义了OPENSSL_NO_GMTLS，那就是没有使用gmtls
这样的话在构造server key exchange时使用的摘要算法是sm3，
而在使用函数tls1_PRF()生成master_secret、key_block、verify_data时使用的摘要算法是SHA256，
这是否有悖于我所选择的加密套件ECDHE_SM2_WITH_SM4_SM3呢？
@guanzhi

**Comment by strongbug** [comment]
我是没有定义这个，选择用的gmtls套件，算法选择的是SM2_WITH_SMS4_SM3
