### ISSUE TITLE
编译出的库支持Python调用吗？

### ISSUE THREAD

**Issue by liujiong63** [guanzhi/GmSSL#54]
老师，您好

请问GmSSL编译出的库支持python语言调用吗？

谢谢

**Comment by guanzhi** [comment]
Python可以通过pyOpenSSL访问OpenSSL：https://pyopenssl.readthedocs.io/en/stable/
你可以试一下

**Comment by guanzhi** [comment]
通常这些wrapper封装了OpenSSL的EVP API，调用某个具体算法采用传入算法名称字符串的方式，因此支持新算法不存在大的问题。但是通常需要少量的修改。如果你能说明你的实际应用场合，和支持Python的价值，我们可以考虑在未来的更新里让pyOpenSSL可以调用GmSSL。
