### ISSUE TITLE
gmssl sms4加密不支持doc、ppt、mp3等文档类型？

### ISSUE THREAD

**Issue by einking** [guanzhi/GmSSL#542]
本人最近在学习国密算法，首先十分感谢Gmssl的开发者们！你们辛苦了。
我遇到的问题就是使用gmssl sms4 -e -in test.doc -out test.sms4的时候，加密可以，但是解密却失败了，根本解密不出来。请问这是由于目前还不支持这些文件类型么？或者有别的指令形式。
谢谢老师。

**Comment by einking** [comment]
前脚一问，后脚自己就尝试出来了，只要指定输出的文件类型就可以解密成功的。如下：
gmssl sms4 -d -in test.sms4 -out test.doc

**Comment by einking** [comment]
还是希望官方可以省去后面这一步骤，加密的时候记下文件的类型，解密的时候要方便一些。不过官方有自己的考虑，使用者可以后期自己添加。

**Comment by ZZMarquis** [comment]
对于加解密算法来说，它只认识二进制，不管你是什么类型的文件它都把它当成一堆二进制给加密了，所以文件类型（其实只是扩展名的问题）要你自己去注意
