### ISSUE TITLE
交互模式下，多次查看CSR会报错

### ISSUE THREAD

**Issue by razeencheng** [guanzhi/GmSSL#544]
当我在交互模式，多次运行如以下命令：
> req -pubkey -noout -inform DER ...

第一次能正常的工作，但再次运行同样命令，则出现以下错误：

> problem creating object tsa_policy1=1.2.3.4.1 6812:error:08064066:object identifier > > routines:OBJ_create:oid exists:crypto\objects\obj_dat.c:689:

**Comment by razeencheng** [comment]
看到openssl 1.1.0也有同样的问题==。
openssl's interactive mode can't work for multiple commands #6292

貌似1.1.1后解决了，GM啥时候能更。
期待。

**Comment by Leejiter** [comment]
你好，我也遇到这样的问题，我是下载的GMSSL 的windows exe运行时出现的，openssl版本未1.1.0d 不知道是不是这个版本有问题

**Comment by guanzhi** [comment]
希望有志愿者能够参考OpenSSL提交这个问题的Bugfix。
