### ISSUE TITLE
ECC_SM4_SM3  按照国密标准是不是也支持双向认证？

### ISSUE THREAD

**Issue by xuelang2009** [guanzhi/GmSSL#546]
ECC_SM4_SM3 可以支持单向认证，是不是按照国密协议也可以支持双向认证？
ECDHE_SM4_SM3 仅支持双向认证。

**Comment by liclicli** [comment]
请问在哪里说明了ECDHE_SM4_SM3只支持了双向认证？如果从套件字面意思上来看，做双向认证和做单向认证都是没有问题的呀

**Comment by guanzhi** [comment]
国密有关的套件和协议我们稍后会写一个更明确的文档，对标准和GmSSL的实现做进一步的解释。另外后面的升级会为部分GmSSL套件定义一个永久的且和标准SSL套件不冲突的16位编号。

**Comment by zhenyuwei** [comment]
ECDHE_SM4_SM3这个国密标准有问题的，SM2_compute_share_key里面没有计算预主密钥，这个地方需要改，如果直接使用sm2_exch.c里面提供SM2_KAP_CTX_init/SM2_KAP_prepare/SM2_KAP_compute_key三组接口，需要修改一下里面的流程，好像客户端处理完服务器证书后，加密证书和签名证书的顺序有问题，证书链这块目前还没测，Z值计算国标使用的是GmSSL的SM2_DEFAULT_ID这个值，大致应该就这几个地方有问题需要调整。
SM2_KAP_compute_key计算密钥过程值，参考《GM/T 0009-2012》和密钥交换协议部分，A端代表服务器Server，B端代码Client客户端，这个地方在拼接Z值是遇到了坑，导致和格尔机器测试一直出错，希望大家不会遇到。

**Comment by LoadLife** [comment]
> 请问在哪里说明了ECDHE_SM4_SM3只支持了双向认证？如果从套件字面意思上来看，做双向认证和做单向认证都是没有问题的呀

烦请指教，理解的话，ecdhe-sm4-sm3的密钥交换是不是也只是依赖双方交换的临时公私钥计算预主密钥，与双向认证无关？

**Comment by mazhenke** [comment]
请教一个问题，关于使用ECC_SM4_SM3 的SSL中，如果采用SM2密钥交换算法的话，client和server的临时公钥（Rb和Ra）在什么时候发送给对方的？如果ECDHE_SM4_SM3支持单向认证的话，Client的临时公钥怎么发送给server？谢谢！

**Comment by romanzsh** [comment]
Ecc不支持双向验证，没有临时公私钥的交换。只有ecdhe才有双向认证和临时公私钥交换。

Sent from my iPhone

On May 20, 2020, at 16:31, Zhenke Ma <notifications@github.com> wrote:

﻿

请教一个问题，关于使用ECC_SM4_SM3 的SSL中，如果采用SM2密钥交换算法的话，client和server的临时公钥（Rb和Ra）在什么时候发送给对方的？如果ECDHE_SM4_SM3支持单向认证的话，Client的临时公钥怎么发送给server？谢谢！

**Comment by zhenyuwei** [comment]
> 请教一个问题，关于使用ECC_SM4_SM3 的SSL中，如果采用SM2密钥交换算法的话，client和server的临时公钥（Rb和Ra）在什么时候发送给对方的？如果ECDHE_SM4_SM3支持单向认证的话，Client的临时公钥怎么发送给server？谢谢！

ecc的这个密码套件是参考当时的rsa加密方式，这块由客户端生成的48字节随机数作为预主密钥，用于双方后续工作密钥计算，因此整个流程中的密钥协商和你说的临时公钥没关系
所谓的双向验证，就是客户端校验服务器，服务器也要校验客户端身份，这里校验身份用的就是双方的证书。

**Comment by mazhenke** [comment]
@romanzsh 不好意思写错了，ECDHE_SM4_SM3在使用SM2密钥交换算法时，临时密钥是在什么阶段发送给对方的？是不是 ECDHE_SM4_SM3只支持双向认证，ECC_SM4_SM3只支持单向认证？为什么呢？

**Comment by romanzsh** [comment]
Server key exchange和client key exchange阶段。
Ecc密钥交换相对简单，适合类似于https这种场合。


Sent from my iPhone

On May 20, 2020, at 18:29, Zhenke Ma <notifications@github.com> wrote:

﻿

@romanzsh<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fromanzsh&data=02%7C01%7C%7C5cd58317d128409dbece08d7fca8a5da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637255673570320103&sdata=Vez4RUTMMXMtqp2CrkNKgZukokqyPaAHZXiJ8HWlAjI%3D&reserved=0> 不好意思写错了，ECDHE_SM4_SM3在使用SM2密钥交换算法时，临时密钥是在什么阶段发送给对方的？是不是 ECDHE_SM4_SM3只支持双向认证，ECC_SM4_SM3只支持单向认证？为什么呢？
