### ISSUE TITLE
SM2 加密error 失败

### ISSUE THREAD

**Issue by jydxx61** [guanzhi/GmSSL#549]
在debian 9上编译安装master之后,根据README的文件文件, 尝试sm2加密但失败, 命令如下:

加密命令:
$ echo "Top Secret" | gmssl pkeyutl -encrypt -pkeyopt ec_scheme:sm2 -pubin -inkey pubkey.pem -out ciphertext.sm2
140536357410560:error:42067068:SM2 routines:SM2_encrypt:invalid digest algor:crypto/sm2/sm2_enc.c:237:
140536357410560:error:101030BD:elliptic curve routines:pkey_ec_encrypt:sm2 encrypt failed:crypto/ec/ec_pmeth.c:198:
Public Key operation error

 请问有人知道该如何解决? 谢谢.

**Comment by jydxx61** [comment]
参考 issue/497 的方法解决了.
修改crypto/ec/ec_pmeth.c第66行为dctx->ec_encrypt_param = NID_sm3;
重新编译安装，然后就可以了
感谢suishixingkong

**Comment by guanzhi** [comment]
通过命令行选项 `-pkeyopt ec_encrypt_param:sm3` 来设置加密的参数。
如果是编程实现，需要调用函数`EVP_PKEY_CTX_set_ec_encrypt_param()`设置。
