### ISSUE TITLE
WIN64(MINGW+MSYS)  make  Error

### ISSUE THREAD

**Issue by newdible** [guanzhi/GmSSL#55]
我在用 WIN64(MINGW+MSYS)操作系统 编译时，make指令后，出现如下错误，谁知道是什么原因吗？谢谢。
make[2]: Leaving directory `/c/GmSSL/crypto/objects'
making all in crypto/md2...
make[2]: Entering directory`/c/GmSSL/crypto/md2'
gcc -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -DOPENSSL_THREAD
S -D_MT -DDSO_WIN32 -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -fomit-frame-pointer -O3 -m
arch=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM
_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD
160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM   -c -o md2_dgst.o md2
_dgst.c
In file included from md2_dgst.c:62:0:
../../include/openssl/md2.h:64:4: error: #error MD2 is disabled.
 #  error MD2 is disabled.
    ^
make[2]: **\* [md2_dgst.o] Error 1
make[2]: Leaving directory `/c/GmSSL/crypto/md2'
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory`/c/GmSSL/crypto'
make: **\* [build_crypto] Error 1

**Comment by newdible** [comment]
![image](https://cloud.githubusercontent.com/assets/21231480/19228819/6633289e-8efb-11e6-9a9f-9c31282399c0.png)
有谁知道是什么原因啊？十分感谢

**Comment by guanzhi** [comment]
MD2是被禁用的，因此编译到的时候会触发一个编译器警告。可以设定编译选项不编译MD2。
不建议使用MD2，但是如果你一定要使用MD2，可以注释掉`include/openssl/md2.h`中的这一行(第64行)。

**Comment by newdible** [comment]
不好意思，我是菜鸟，连如何禁止编译MD2都不知怎么样操作，汗......能详细指点下吗？非常感谢。是通过修改makefile文件吗？谢谢

**Comment by guanzhi** [comment]
1. 禁止编译MD2，运行 `./config no-md2`，然后会生成相应的Makefile
2. （不推荐）或者在代码`include/openssl/md2.h`中删除`# error MD2 is disabled.`这一句

**Comment by newdible** [comment]
十分感谢，已经编译通过了。我原本以为编译完成后，会生成可以调用的lib库，可实际上没有啊。还需要再执行什么指令吗？ 编译openssl的ms\do_ms那套指令，在这个环境下好像用不了啊。谢谢
