### ISSUE TITLE
GmSSL最新master上能够支持ASN.1/DER么?

### ISSUE THREAD

**Issue by jydxx61** [guanzhi/GmSSL#551]
请问目前在master上编译出来的gmssl使用ASN.1/DER格式密钥进行加密时, unable to load Public Key
pkeyutl: Error initializing context, 那么GmSSL什么时候支持ASN.1/DER的编码格式呢?
谢谢.

**Comment by guanzhi** [comment]
命令行默认读取PEM格式的密钥，如果要读DER，应该指定`-keyform DER`

**Comment by jydxx61** [comment]
好的, 谢谢关老师
