### ISSUE TITLE
node n-api 调用 gmssl 解析 PKCS#12 报错，但是 java jni调用 是正常

### ISSUE THREAD

**Issue by zhongguoliqi** [guanzhi/GmSSL#553]
140383553435328:error:2306B076:lib(35):func(107):reason(118):../deps/openssl/openssl/crypto/pkcs12/p12_mutl.c:90:
140383553435328:error:2307E06D:lib(35):func(126):reason(109):../deps/openssl/openssl/crypto/pkcs12/p12_mutl.c:123:
140383553435328:error:23076071:lib(35):func(118):reason(113):../deps/openssl/openssl/crypto/pkcs12/p12_kiss.c:120:
./run.sh: line 7:  9091 Segmentation fault      (core dumped) node ./test.js

如题，已经确认调用的参数 完全相同， 报错信息如上。

调用的大致过程是， 用c 调用 gmssl 接口 实现解析 PKCS#12 的功能，并生成一个 动态库（.so）.
node 通过 n-api 调用， java 通过jni 调用， 前者 抛出 上面的错误， 后者 执行完全正常。 

node版本 V8.11.3

node 本身集成openssl 和这个有关系？

能帮忙看下吗

**Comment by guanzhi** [comment]
看返回的错误，可能的原因是链接的是OpenSSL而不是GmSSL。
重新编译一下Node.js，并且指定和GmSSL链接，有可能解决你的问题

**Comment by zhongguoliqi** [comment]
用 dlopen 加载库，可以解决
