### ISSUE TITLE
2.3.1 版本 在windows 上编译不了？？

### ISSUE THREAD

**Issue by zhongguoliqi** [guanzhi/GmSSL#558]
环境
win7 sp1
vs2017 

返回错误：

ssl\statem\statem_gmtls.c(878): warning C4018: “<”: 有符号/无符号不匹配
ssl\statem\statem_gmtls.c(1057): warning C4819: 该文件包含不能在当前代码页(936)
中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
ssl\statem\statem_gmtls.c(1387): error C2449: 在文件范围内找到“{”(是否缺少函数
头?)
ssl\statem\statem_gmtls.c(1485): error C2059: 语法错误:“}”
ssl\statem\statem_gmtls.c(1585): warning C4013: “gmtls_sm2_derive”未定义；假设
外部返回 int
ssl\statem\statem_gmtls.c(2164): warning C4013: “gmtls_construct_cke_sm2dhe”未
定义；假设外部返回 int
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\201
7\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.EXE"”: 返回代码“0x2”

Stop.

**Comment by ThomasDrTang** [comment]
在c1387的函数和上面的注释之间空一行试试

**Comment by hyperiris** [comment]
这是如下两行注释导致的：
// SM2密钥交换实际上不仅仅
// 实际上还需要知道我是客户端还是服务器

要解决这个问题，有两个办法
1 把这个文件用utf8 with bom保存，vs就可以编译了
2 修改makefile，增加全局的编译选项：/source-charset:utf-8
