### ISSUE TITLE
gmssl.org这几天打不开？

### ISSUE THREAD

**Issue by feitian0920** [guanzhi/GmSSL#56]
gmssl.org这几天打不开？

**Comment by shenak47** [comment]
同问，我这也打不开，不知道是怎么回事

**Comment by itollei** [comment]
还是打不开，顺便问下SM2开发文档在哪里可以找到

**Comment by guanzhi** [comment]
目前还没有开发者文档，SM2的开发请参考
https://github.com/guanzhi/GmSSL/blob/master/crypto/sm2/sm2test.c
https://wiki.openssl.org/index.php/EVP_Asymmetric_Encryption_and_Decryption_of_an_Envelope
https://wiki.openssl.org/index.php/EVP_Signing_and_Verifying
