### ISSUE TITLE
关于如何解压SM2压缩过的公钥

### ISSUE THREAD

**Issue by x-serializer** [guanzhi/GmSSL#564]
找了很久没有找到，库内有这样的函数么

**Comment by xudogn** [comment]
`    const char *pubhex = pk.UTF8String;
    EC_GROUP *grp = EC_GROUP_new_by_curve_name(kDefaultEllipticCurveType);
    EC_POINT *p = EC_POINT_new(grp);
    EC_POINT_hex2point(grp, pubhex, p, NULL);
    // 转16进制
    const char *hex = EC_POINT_point2hex(grp, p, POINT_CONVERSION_UNCOMPRESSED, NULL);
    // 或者 bignum
    BIGNUM *n = NULL;
    EC_POINT_point2bn(grp, p, POINT_CONVERSION_UNCOMPRESSED, n, NULL);`
压缩未压缩 通过第三个参数来控制：
压缩   POINT_CONVERSION_COMPRESSED， POINT_CONVERSION_UNCOMPRESSED未压缩
