### ISSUE TITLE
ssl 不能正常工作

### ISSUE THREAD

**Issue by hyperiris** [guanzhi/GmSSL#566]
关博士您好，

我修改了浏览器用Gmssl连接大宝CA测试平台（https://140.143.247.42/）和中国银行（https://ebssec.boc.cn/），发现不能正常工作。调试后发现有两个地方不是很理解：
1. statem_gmtls.c的gmtls_process_ske_sm2函数内，调用了gmtls_new_cert_packet，gmtls_new_cert_packet内部分配内存的时候，从实现上看应该是多分配了三个字节用来保存x509PEM的证书长度，但是后续调用EVP_VerifyUpdate(md_ctx, buf, n) 的时候，n并没有加上这三个字节，是否需要加上？

2. 和GMT0024-2014的说明比较，0024上没有说EVP_VerifyUpdate(md_ctx, z, zlen)这一个是什么。请不吝指教，谢谢！

补充：
3. gmtls_construct_cke_sm2这个SM2公钥加密出来的packet也不能通过服务端验证。看了一下GM/T 0009，好像client key exchange的不是简单SM2公钥加密？迷茫了，我继续看标准。

**Comment by zhenyuwei** [comment]
1. 给你一个证书数据包的格式，[Header 16 01 01 XX XX] + [Certificate type 0b] + [Certificate packet length 00 XX XX] + [Certificate length 00 XX XX] + [sign cert length 00 XX XX ] + [sign cert] + [enc cert length 00 XX XX] + [enc cert] + [cert chain length 00 XX XX] + [cert chain]，EVP_VerifyUpdate(md_ctx, buf, n) 里面的buf部分是 [enc cert length 00 XX XX] + [enc cert]，XX代表长度。
2. EVP_VerifyUpdate(md_ctx, z, zlen)这个Z值目前计算使用的是1234567812345678，GmSSL里面定义SM2_DEFAULT_ID
3. 0024里面的6.4.4.7部分描述了ECC时使用的预主密钥格式， 48字节的PreMasterSecret，前2字节为协议版本[01 01] + 后46字节为随机数random[46]，

**Comment by ji04xiaogang** [comment]
> 是否有人愿意加入到项目组来参与开发维护SSL协议？

请问老师，需要什么条件呢？ 我想试一试。

**Comment by guanzhi** [comment]
欢迎加入，贡献文档、代码和测试，并且被接收，你就自动被GitHub列入贡献者名单了。

**Comment by guanzhi** [comment]
GmSSL已经维护了很多年，并且还将长期存在下去，对于国密SSL协议的互联互通问题，我认为主要的问题是缺乏一个明确规范文档以及配合的完整测试数据，因此我建议先整理一下GM/T 0024这个文档，把其中所有未明确定义的项目都标注出来。后续第三方闭源代实现也可以参考我们的测试数据完成兼容性测试。

**Comment by zhenyuwei** [comment]
@guanzhi 是对GM/T 0024这块？SM1/2/3/4测试做过，SM9的密码套件没做过，不知道现在检测中心那边的机器升级了吗，是否也要对SM9的密码套件做检测，RSA的套件不做检测。

**Comment by conezxy** [comment]
SM9的套件目前不检测

-
掌晓愚

在 2018年11月3日，14:58，zhenyuwei <notifications@github.com<mailto:notifications@github.com>> 写道：


@guanzhi<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fguanzhi&data=02%7C01%7C%7Cdb58fccc428f4951214908d64159d266%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636768251365490896&sdata=aP2QeOIvUJBhyf%2FZwfBE6WsMYgwHHRP51HdRQr%2FDdsU%3D&reserved=0> 是对GM/T 0024这块？SM1/2/3/4测试做过，SM9的密码套件没做过，不知道现在检测中心那边的机器升级了吗，是否也要对SM9的密码套件做检测，RSA的套件不做检测。

**Comment by conezxy** [comment]
规范相关的疑问可以作为issue发出来，我来解答。

-
掌晓愚

在 2018年11月2日，10:57，Zhi Guan <notifications@github.com<mailto:notifications@github.com>> 写道：


GmSSL已经维护了很多年，并且还将长期存在下去，对于国密SSL协议的互联互通问题，我认为主要的问题是缺乏一个明确规范文档以及配合的完整测试数据，因此我建议先整理一下GM/T 0024这个文档，把其中所有未明确定义的项目都标注出来。后续第三方闭源代实现也可以参考我们的测试数据完成兼容性测试。
