### ISSUE TITLE
关于SDF引擎

### ISSUE THREAD

**Issue by duoluodexiaokeke** [guanzhi/GmSSL#569]
根据说明文档，在编译的时候编译成静态库使用
具体有一下几个问题：
1.直接./config不能编译进去吗？不能编译成动态库吗？
2.在使用时碰到如下错误：
   gmssl engine sdf -pre SO_PATH:/lib64/libswsds.so -pre OPEN_DEV -c
Using configuration from /usr/local/ssl/openssl.cnf
139884781266688:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/local/lib64/engines-1.1/sdf.so): /usr/local/lib64/engines-1.1/sdf.so: cannot open shared object file: No such file or directory
139884781266688:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
139884781266688:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
139884781266688:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=sdf
[trafodion@dev06 GmSSL]$ ls -l /usr/local/lib64/engines-1.1/sdf.so
ls: cannot access /usr/local/lib64/engines-1.1/sdf.so: No such file or directory
请问这个时因为编译安装的时候不完全引起的吗

**Comment by guanzhi** [comment]
SKF/SDF Engine不随源代码发布。
下面二进制版本中包含内置的引擎，你的计算机需要安装SDF卡（三未信安的卡通过测试)，并且需要准备卡厂商的SDF动态库。
https://github.com/guanzhi/GmSSL/releases/tag/v2.3.1

**Comment by lisongopg** [comment]
关老师，SDF  Engine，https://github.com/guanzhi/GmSSL/releases/tag/v2.3.1  这个地址现在没有相关资源，请问哪里还可以下载到呢

**Comment by xiejianjun417** [comment]
@guanzhi 请问现在SKF/SDF engine能否提供源码或dll？

**Comment by fidderdan** [comment]
我已完成sdf  skf引擎的开发需要帮助发邮件523665380@qq.com
