### ISSUE TITLE
Linux环境下make编译报错

### ISSUE THREAD

**Issue by newdible** [guanzhi/GmSSL#57]
我在Linux环境下编译时，出错，请问谁知道是什么原因呢？非常感谢。

原来是在windows下编译，一直没有编译成功。后安装了RedHat的虚拟机。
大体步骤如下：
unzip  Gmssl.zip
./config no-idea no-mdc2 no-rc5 no-asm shared --prefix=/test/lib
make depend 
make
之后就报如下图所示的错误了，非常感谢您的答复。

**Comment by newdible** [comment]
![image](https://cloud.githubusercontent.com/assets/21231480/19432130/c3d3ad42-948d-11e6-846a-8d934c1b55e7.png)

**Comment by LiTianjue** [comment]
现在的代码有些条件编译支持的不是很好，最好先不要加条件编译选项，直接./config 来编译，
这是我找到的一个地方，当时因为用了第三方的编译脚本，改起来比较复杂，所以改了代码文件
https://github.com/guanzhi/GmSSL/pull/52
如果你对条件编译真的有需求，那么你在要仔细检查一下代码文件中的条件编译部分。
