### ISSUE TITLE
导入证书错误， SKF_ImportCertificate 返回 A0x000011

### ISSUE THREAD

**Issue by MariShunxiang** [guanzhi/GmSSL#570]
Android jni 导入证书。
接口： SKF_ImportCertificate 返回 A0x000011， 
看文档错误码： A0x000011 是  SAR_INDATAERR ，输入数据错误。
有大神遇到过吗？

**Comment by zhenyuwei** [comment]
7.5.8 导入数字证书
函数原型    ULONG DEVAPI SKF_ImportCertificate(HCONTAINER hContainer, BOOL bSignFlag,
BYTE* pbCert, ULONG ulCertLen)
功能描述    向容器内导入数字证书。
参数    hContainer [IN] 容器句柄。
            bSignFlag [IN] TRUE 表示签名证书，FALSE 表示加密证书。
            pbCert [IN] 指向证书内容缓冲区。
            ulCertLen [IN] 证书长度。
返回值    SAR_OK： 成功。
其他：     错误码。
上面是国标给的接口说明，参数部分你需求确定导入证书是PEM还是DER格式。测试DER格式的证书导入正常。
