### ISSUE TITLE
TLS握手失败

### ISSUE THREAD

**Issue by eksea** [guanzhi/GmSSL#576]
### 执行的命令
> `gmssl.exe s_client -connect ebssec.boc.cn:443 -gmtls -debug`
### client hello
> 16 01 01 00 39 01 00 00 35 01 01 cf a8 a5 df 7a
2e 29 02 5f 04 c2 58 0d 55 c9 2c 60 c1 d0 48 6f
8e 9c d7 df e4 b2 de 82 d1 84 4d 00 00 0e e0 17
e0 15 e0 13 e0 11 e0 1a e0 19 00 ff 01 00

各个字段的信息都对
### sever client
> 02 00 00 2d 01 01 5b 90 e0 91 80 c2 1f 6a 6a cf
18 de 14 a2 17 55 2c e6 c0 48 c3 51 c5 51 58 93
4f 5a 3d 04 c1 a2 00 e0 13 00 00 05 ff 01 00 01
00

从结果上看，服务端选定的cipher suite是e013(即GMTLS_CK_SM2_WITH_SMS4_SM3),压缩算法为00，但是后面还跟了7个多余的字节，导致server hello解析出错， 出错信息为：
> error:14171073:SSL routines:tls_process_server_hello:bad packet length:ssl\statem\statem_clnt.c:1222

**Comment by gggin** [comment]
@liclicli 求助啊，遇到同样的问题。

**Comment by liclicli** [comment]
见#517 的第一个问题

**Comment by Nu1i** [comment]
@liclicli 照您在#517中的方法修改重新编译后，程序执行访问大宝CA的测试页面会发生内存泄露，请问此问题如何解决？是否有详细的修改说明？
