### ISSUE TITLE
ee key too small

### ISSUE THREAD

**Issue by jixuduxing** [guanzhi/GmSSL#579]
测试兼容性发现的，使用之前的openssl证书，之前的代码，采用最新的gmssl库，服务端会出现SSL_accept失败，
ERR_print_errors_fp(stderr)打印的结果如下：
SSL routines:gmtls_output_cert_chain:ee key too small:ssl/statem/statem_gmtls.c:128
如果调用SSL_CTX_set_security_level(ctx, 0);在SSL_accept处会直接异常挂掉。

gmssl version
GmSSL 2.3.1 - OpenSSL 1.1.0d  30 Mar 2018

**Comment by jixuduxing** [comment]
对了 ，是linux环境下，windows下正常

**Comment by littleMagikarp** [comment]
您好，请问您解决了吗？我也遇到了相同的错误
