### ISSUE TITLE
双证书在服务端怎么使用？

### ISSUE THREAD

**Issue by jixuduxing** [guanzhi/GmSSL#581]
开发语言c,
怎么指定签名证书和加密证书，签名密钥和加密密钥？
TaSSL 添加了新的api：SSL_use_enc_PrivateKey  SSL_CTX_use_enc_PrivateKey_file
gmssl应该怎么设置呢？
@guanzhi @zhaoxiaomeng

**Comment by HaoXuan40404** [comment]
请问你这个问题解决了吗，我们之前用的是TaSSL，现在想要用GmSSL也实现这里 也遇到了一些问题

**Comment by jixuduxing** [comment]
> 请问你这个问题解决了吗，我们之前用的是TaSSL，现在想要用GmSSL也实现这里 也遇到了一些问题

直接设置两个sm2证书和密钥就可以，没有新增接口，代码里自己会适配
注意，必须先设置签名证书。。然后才是加密证书
