### ISSUE TITLE
请教关老师：由于OpenSSL版本不同导致的兼容问题

### ISSUE THREAD

**Issue by timgeo4ever** [guanzhi/GmSSL#582]
关老师，您好！
在将GMSSL库导入至我已有工程中进行调试时，我注意到GMSSL使用的是OpenSSL 1.1.0d  26 Jan 2017，而已有工程中之前使用的是OpenSSL 1.0.1e 11 Feb 2013，这就导致了一些废弃API或重命名变量的不兼容如：[stack.h](https://github.com/openssl/openssl/commit/739a1eb1961cdc3b1597a040766f3cb359d095f6#diff-2f5d1d8e91db188f05a70aee7eecf742)内的rename操作，同时我也注意到该文件中的# if OPENSSL_API_COMPAT < 0x10100000L 这行代码，但好像GMSSL依然不兼容已有工程中对于旧变量名的使用。
升级工程中已有的对于OpenSSL库的使用是一个好方法，但是同时还有许多第三方库对于OpenSSL有着依赖使用，不能保证这些三方库的作者都可以修改代码以支持新的API及变量名。
在此想请教关老师这种情况下应当如何操作呢？
感谢关老师及团队对于GMSSL库的辛勤付出，希望能够尽快得到您的指点

**Comment by guanzhi** [comment]
如果使用的是开源项目(如Nginx)，比较流行的项目都会在最近2年的版本中支持OpenSSL-1.1 API，更换至新的版本即可。
如果是自己的项目，可以尝试`config --api=XXX`来兼容老版本的库，这样不用改应用的代码。我建议直接修改应用的代码，将对老API的调用改为调用新版本的API。

**Comment by timgeo4ever** [comment]
> 如果使用的是开源项目(如Nginx)，比较流行的项目都会在最近2年的版本中支持OpenSSL-1.1 API，更换至新的版本即可。
> 如果是自己的项目，可以尝试`config --api=XXX`来兼容老版本的库，这样不用改应用的代码。我建议直接修改应用的代码，将对老API的调用改为调用新版本的API。

感谢关老师的回复！是这样的，当前是在iOS工程内调试，可能会有一些其他三方厂商提供的SDK对低版本OpenSSL库的依赖，所以这部分的代码是无法修改的，厂商愿不愿意修改也是不可控的。
关于`config --api=XXX`具体XXX版本是0x1000208fL这样的 OPENSSL_VERSION_NUMBER 吗

**Comment by timgeo4ever** [comment]
`GmSSL-master tim$ ./config --api=0x1000208fL
Operating system: x86_64-apple-darwinDarwin Kernel Version 17.5.0: Mon Mar 5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
WARNING! If you wish to build 32-bit library, then you have to
         invoke 'KERNEL_BITS=32 ./config  --api=0x1000208fL'.
         You have about 5 seconds to press Ctrl-C to abort.
Configuring for darwin64-x86_64-cc
Configuring OpenSSL version 1.1.0d (0x1010004fL)
***** Unsupported api compatibility level: 0x1000208fL`

配置了一下，显示不支持，是我配置的写法不对还是需要兼容的版本过低呢？如果是需要兼容的版本太低了，烦请关老师告知所支持的最低兼容版本

**Comment by guanzhi** [comment]
1.1 API隐藏了很多常用的EVP对象，`--api`编译指令解决不了兼容性问题。
或者让第三方厂商升级一下，这个工作量不算大；或者你自己修改一下GmSSL，把隐藏的EVP对象重新暴露出来，不过这个工作量更大，并且由于某些EVP对象的实现已经变了，未必容易搞定。

**Comment by timgeo4ever** [comment]
> 1.1 API隐藏了很多常用的EVP对象，`--api`编译指令解决不了兼容性问题。
> 或者让第三方厂商升级一下，这个工作量不算大；或者你自己修改一下GmSSL，把隐藏的EVP对象重新暴露出来，不过这个工作量更大，并且由于某些EVP对象的实现已经变了，未必容易搞定。

好的，再次感谢关老师百忙之中的回复！祝项目越做越好！
