### ISSUE TITLE
make时提示出错

### ISSUE THREAD

**Issue by landhuang** [guanzhi/GmSSL#584]
1 wget https://github.com/guanzhi/GmSSL/archive/master.zip
2 ./config no-saf no-sdf no-skf no-sof no-zuc
3 make
提示：
make[1]: *** No rule to make target `crypto/ec/ecp_sm2z256-x86.s', needed by `crypto/ec/ecp_sm2z256-x86.o'.  Stop.
make[1]: Leaving directory `/root/install/GmSSL/GmSSL-master'
make: *** [all] Error 2
本人操作系统版本：CentOS release 6.10 (Final)
下面是CPU信息------------------------------------------------------------------------------
[root@land GmSSL-master]# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version (cpu64-rhel6)
stepping	: 3
microcode	: 0x1
cpu MHz		: 2599.998
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep xsaveopt
bugs		:
bogomips	: 5199.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

下面是内存信息------------------------------------------------------------------------------

[root@land GmSSL-master]# cat /proc/meminfo
MemTotal:         520132 kB
MemFree:          130440 kB
MemAvailable:     474780 kB
Buffers:           70156 kB
Cached:           270028 kB
SwapCached:         2728 kB
Active:           196284 kB
Inactive:         156144 kB
Active(anon):      10760 kB
Inactive(anon):     1572 kB
Active(file):     185524 kB
Inactive(file):   154572 kB
Unevictable:           0 kB
Mlocked:               0 kB
HighTotal:             0 kB
HighFree:              0 kB
LowTotal:         520132 kB
LowFree:          130440 kB
SwapTotal:        135164 kB
SwapFree:         123032 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:         11144 kB
Mapped:            16468 kB
Shmem:                88 kB
Slab:              26292 kB
SReclaimable:      17644 kB
SUnreclaim:         8648 kB
KernelStack:         984 kB
PageTables:         1064 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      395228 kB
Committed_AS:     112280 kB
VmallocTotal:     491528 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       51184 kB
DirectMap2M:      491520 kB

**Comment by guanzhi** [comment]
暂时不要在虚拟机里编译，或no-asm

**Comment by zhenyuwei** [comment]
把汇编部分使用.c文件替换编出.o就可以。

**Comment by songqingri** [comment]
有点源码会有问题，下载GmSSL-master.zip这个包。

**Comment by landhuang** [comment]
使用这个版本可以
wget https://github.com/guanzhi/GmSSL/archive/v2.3.1.tar.gz
