### ISSUE TITLE
对‘SSLv2_client_method’未定义的引用

### ISSUE THREAD

**Issue by xlj** [guanzhi/GmSSL#585]
在使用gmssl的libcrypto.so替换原openssl的动态库作为编译连接库编译我们的程序时出现了很多未定义的引报错。报错信息如下：
../bin/libt2sdk.so：对‘SSLv2_client_method’未定义的引用
../bin/libt2sdk.so：对‘sk_pop’未定义的引用
../bin/libt2sdk.so：对‘SSLv23_client_method’未定义的引用
../bin/libt2sdk.so：对‘SSLv3_client_method’未定义的引用
../bin/libt2sdk.so：对‘SSL_library_init’未定义的引用
../bin/libt2sdk.so：对‘OPENSSL_add_all_algorithms_noconf’未定义的引用
../bin/libt2sdk.so：对‘CRYPTO_set_id_callback’未定义的引用
../bin/libt2sdk.so：对‘CRYPTO_set_locking_callback’未定义的引用
../bin/libt2sdk.so：对‘sk_free’未定义的引用
../bin/libt2sdk.so：对‘sk_push’未定义的引用

我们nm去看国密的动态库确实不存在上述方法，哪位大神能科普一下，这个问题是我编译时候少带了什么参数导致的吗？

**Comment by zhenyuwei** [comment]
比较一下你使用的openssl版本，gmssl是使用openssl 1.1.0d，如果你的版本比较老，接口应该有很多地方做了调整。

**Comment by xlj** [comment]
> 比较一下你使用的openssl版本，gmssl是使用openssl 1.1.0d，如果你的版本比较老，接口应该有很多地方做了调整。
我同一套程序在另外一台机器上编译是没问题的，我在想这就说明我们程序不用改吧，我看两台机器的gcc版本不太一样，我在考虑是这个gcc版本的问题吗？

**Comment by xlj** [comment]
我在另外一台编译能通过的机器上查看动态连接库关联关系如下：
ldd: 警告: 你没有执行权限  `../bin/libt2sdk.so'
	linux-vdso.so.1 =>  (0x00007fff56a8d000)
	libcrypto.so => /root/ec_jec_gmt_c/bin/libcrypto.so (0x00007ffe32e70000)
	libssl.so => /usr/local/gmssl/libssl.so (0x00007ffe32bf8000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffe329c9000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007ffe327b0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffe325ab000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ffe322a4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ffe3209c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ffe31d99000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffe319d8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffe317c2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffe335aa000)
undefined symbol: CRYPTO_set_id_callback	(../bin/libt2sdk.so)
undefined symbol: SSL_library_init	(../bin/libt2sdk.so)
undefined symbol: OPENSSL_add_all_algorithms_noconf	(../bin/libt2sdk.so)
undefined symbol: sk_pop	(../bin/libt2sdk.so)
undefined symbol: sk_push	(../bin/libt2sdk.so)
undefined symbol: sk_free	(../bin/libt2sdk.so)
undefined symbol: SSLv23_client_method	(../bin/libt2sdk.so)
undefined symbol: CRYPTO_set_locking_callback	(../bin/libt2sdk.so)
undefined symbol: SSLv3_client_method	(../bin/libt2sdk.so)
undefined symbol: SSLv2_client_method	(../bin/libt2sdk.so)

也存在不识别的符号，但是它编译通过了
