### ISSUE TITLE
android 怎么生成公私钥对

### ISSUE THREAD

**Issue by JIANGsssss** [guanzhi/GmSSL#586]
android 怎么生成公私钥对

**Comment by JIANGsssss** [comment]
需要在客户端生成公私钥对，接口里好像没有

**Comment by JIANGsssss** [comment]
`keyPairGenerator = KeyPairGenerator.getInstance("EC", "BC");`
 `keyPairGenerator.initialize(256, new SecureRandom());`

**Comment by zhao1zhihui** [comment]
请问你知道c语言怎么生成码
