### ISSUE TITLE
对于gmapi_skf_ec.c中ECDSA_SIG_new_from_ECCSIGNATUREBLOB(const ECCSIGNATUREBLOB *blob)的问题

### ISSUE THREAD

**Issue by bruce-sunshine** [guanzhi/GmSSL#588]
gmapi_skf_ec.c文件中有函数
ECDSA_SIG *ECDSA_SIG_new_from_ECCSIGNATUREBLOB(const ECCSIGNATUREBLOB *blob)
{
	ECDSA_SIG *ret = NULL;

	if (!(ret = ECDSA_SIG_new())) {
		GMAPIerr(GMAPI_F_ECDSA_SIG_NEW_FROM_ECCSIGNATUREBLOB,
			GMAPI_R_MALLOC_FAILED);
		return NULL;
	}

	if (!ECDSA_SIG_set_ECCSIGNATUREBLOB(ret, blob)) {
		GMAPIerr(GMAPI_F_ECDSA_SIG_NEW_FROM_ECCSIGNATUREBLOB,
			GMAPI_R_INVALID_SIGNATURE);
		ECDSA_SIG_free(ret);
		return NULL;
	}

	return ret;
}
上面函数中调用了ECDSA_SIG_set_ECCSIGNATUREBLOB(ret, blob), 前面ret = ECDSA_SIG_new(); 即会使得sig->r = 0; sig->s = 0; 但ECDSA_SIG_set_ECCSIGNATUREBLOB中的断言会判断	OPENSSL_assert(sig->r);
OPENSSL_assert(sig->s);
使得函会报错,不能正常返回ECDSA_SIG类别的变量.

**Comment by guanzhi** [comment]
把OPENSSL_assert删掉即可，你可以修改一下提交一个pull request
