### ISSUE TITLE
证书请求文件生成过程报错@关老师 请帮忙解答一下

### ISSUE THREAD

**Issue by bylively** [guanzhi/GmSSL#590]
gmssl x509 -req -days 3650 -sm3 -in user.req -signkey user.key -out user.crt 每次执行这条命令的时候都会报错 
140107189659456:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:  请问什么原因引起的错误

**Comment by bylively** [comment]
pkey->type为408

**Comment by bylively** [comment]
printf("md->pkey_type:%d\n",EVP_MD_type(md));
printf("pkey->type:%d\n",pkey->type);
结果为：
md->pkey_type:1126
pkey->type:408

不知道结果对不对  执行X509_REQ_sign(pX509Req, pkey, md);  报错140107189659456:error:0D0DC0C6:asn1 encoding routines:ASN1_item_sign_ctx:digest and key type not supported:crypto/asn1/a_sign.c:183:

**Comment by guanzhi** [comment]
你可以直接使用`apps/gmca/gmca`这个工具来建立国密CA签发SM2，请参考 http://gmssl.org/docs/ca.html

`gmca`是脚本，你可以参考其中的写法和你自己的对比一下看看是什么问题。
