### ISSUE TITLE
请教老师，SM2加密测试程序的随机数实现的，用自己生成的时常会使密文变短，解密不成功，谢谢。

### ISSUE THREAD

**Issue by lennie6063** [guanzhi/GmSSL#593]
请问，test/sm2test.c SM2加密程序中，在SM2_do_encrypt（）函数里生成随机数k，为啥还要在main函数加一个随机数字符串
/* ***************rand k in [1, n-1]************************ */
		do {
			BN_rand_range(k, n);
		} while (BN_is_zero(k));
随机数怎么用的，请指教，谢谢！

**Comment by guanzhi** [comment]
使用预设的随机数这样才能生成和标准文本一样的数据，否则无法达到测试的效果。通过设置随机数生成器也比在函数中加入硬编码的测试数据要好。

**Comment by lennie6063** [comment]
>           使用预设的随机数这样才能生成和标准文本一样的数据，否则无法达到测试的效果。通过设置随机数生成器也比在函数中加入硬编码的测试数据要好。

谢谢老师回复！

老师，我现在想在加密时使用随机数生成器生成k，替换掉main函数的随机数字符串  应该怎么做，请老师指教。
