### ISSUE TITLE
请教老师，chrome该如何操作才能加入SKF接口支持呢？

### ISSUE THREAD

**Issue by huangwenjun06** [guanzhi/GmSSL#594]
论坛上看360浏览器保密版加入了SKF接口支持，是通过调用GmSSL实现的吗？
chrome浏览器能直接使用GmSSL，来加入SKF接口支持吗？
我看现在chrome浏览器使用的是boringssl，如果不能直接使用GmSSL，可否通过修改boringssl代码，加入SKF接口支持？
我是一个只会编译chrome浏览器的新手，希望得到您的指点。谢谢

**Comment by guanzhi** [comment]
360浏览器没有使用GmSSL，360浏览器实现的国密协议比GmSSL要早。但是是否基于BoringSSL实现的国密SSL协议，我也不知道。
在Chrome或者其他浏览器里加入SKF/SDF等硬件支持可以直接在生成签名处调用SKF/SDF接口，相对来说会简单一些。

**Comment by yunlai** [comment]
有人说360用的是代理

**Comment by huangwenjun06** [comment]
谢谢您的耐心回答 @guanzhi 。
不太理解您这句话的意思：“”在Chrome或者其他浏览器里加入SKF/SDF等硬件支持“
是说参照https://github.com/guanzhi/GmSSL/tree/master/crypto/skf
在各个浏览器的类似目录里面加入skf接口的实现函数：
例如chrome的：chromium-60.0.3096.2/third_party/boringssl/src/crypto
Firefox的：mozilla-esr52/security/nss/lib （同级目录下有pkcs11）

然后，接下来需要做什么呢？
