### ISSUE TITLE
golang接口调用gmssl连接测试报错

### ISSUE THREAD

**Issue by Nu1i** [guanzhi/GmSSL#595]
您好：
      使用GmSSL-master的go接口包中的测试程序gmssltest.go测试连接大宝CA（https://140.143.247.42）报错，错误内容如下：error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl\statem\statem_gmtls.c:894:；
       另外，使用在windows7下用vs2015编译的gmssl.exe程序连接服务端也会发生相同错误，错误如下：20024:error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl\statem
\statem_gmtls.c:894:
write to 0x93f750 [0x968480] (7 bytes => 7 (0x7))
0000 - 15 01 01 00 02 02 33                              ......3
write:errno=0
        请教如何解决此问题？万分感谢!

**Comment by guanzhi** [comment]
打印的错误信息里已经包含了错误原因，即“bad signature”，即对方的SM2签名验证不通过。可能的原因是测试的服务器对协议的实现和GmSSL有一定差别。你可以修改GmSSL(毕竟是开源的比较好改)，修改服务器的实现(可能不太容易)，或者替换CA。GmSSL项目中提供了一个简易的CA脚本工具可以建立一个自己的CA.  

http://gmssl.org/docs/ca.html
https://github.com/guanzhi/GmSSL/tree/master/apps/gmca
