### ISSUE TITLE
ZUC支持问题

### ISSUE THREAD

**Issue by cqchengdan** [guanzhi/GmSSL#597]
关老师，您好，我想问问有没有全面支持ZUC（EEA3，EIA3）的计划

**Comment by guanzhi** [comment]
ZUC加解密已经通过`EVP_zuc()`对象支持，下一步是ZUC的MAC。
由于EEA3/EIA3的特殊性，其实现会放在ZUC模块内，可能不会通过EVP接口实现，也可能暂时不会实现。
对于这2个算法的典型应用场景，直接使用国密标准中的代码就可以满足要求。

**Comment by cqchengdan** [comment]
> ZUC加解密已经通过`EVP_zuc()`对象支持，下一步是ZUC的MAC。
> 由于EEA3/EIA3的特殊性，其实现会放在ZUC模块内，可能不会通过EVP接口实现，也可能暂时不会实现。
> 对于这2个算法的典型应用场景，直接使用国密标准中的代码就可以满足要求。
好的，谢谢关老师
