### ISSUE TITLE
TLS1.3打算支持吗

### ISSUE THREAD

**Issue by zhenyuwei** [guanzhi/GmSSL#602]
TLS1.3的RFC文档已经公布，OpenSSL以及其它软件已经添加了支持，请问这个版本还会对TLS1.3升级吗，后续的OpenSSL更新GmSSL还会跟进吗？@conezxy

**Comment by guanzhi** [comment]
TLS 1.3 (以及TLS 1.3的国密套件) 会随着和OpenSSL-1.1.1同步时。

当前GmSSL-2.4.x周期内的目标：
 - 完善SM9/BF-IBE/BB1-IBE，并将这些Identity-Based方案融入到EVP框架中。
 - 完善GM/T 0024 SSL VPN协议中，增加SM9的套件
 - 完善SM2/3/4/9/ZUC的优化和Intel X86_64汇编实现

**Comment by zhenyuwei** [comment]
好的，谢谢。
