### ISSUE TITLE
fatal error U1073: don't know how to make '"crypto\ec\ecp_sm2z256-x86.asm"'

### ISSUE THREAD

**Issue by yunlai** [guanzhi/GmSSL#603]
vs2015 x86 Native tools command prompt

perl configure VC-WIN32
nmake

...
fatal error U1073: don't know how to make '"crypto\ec\ecp_sm2z256-x86.asm"'

**Comment by cqchengdan** [comment]
你加一个no-asm就行了，我就是这样解决的

**Comment by yunlai** [comment]
master，加no-asm试了，也有错误
libcrypto-1_1.def : error LNK2001: unresolved external symbol CRYPTO_memcmp

**Comment by Shun87** [comment]
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\ADMINI~1\AppData\Local\Temp\nm27B.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: unresolved external symbol CRYPTO_memcmp
libcrypto.lib : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'

**Comment by iamgossh** [comment]
> vs2015 x86 Native tools command prompt
> 
> perl configure VC-WIN32
> nmake
> 
> ...
> fatal error U1073: don't know how to make '"crypto\ec\ecp_sm2z256-x86.asm"'

请问，这个问题您解决了吗？

**Comment by guanzhi** [comment]
sm2z256的问题已经解决，请测试
