### ISSUE TITLE
gmssl 2.4在32位Linux系统下编译报错

### ISSUE THREAD

**Issue by zafir2012** [guanzhi/GmSSL#608]
C -DOPENSSL_USE_NODELETE -MMD -MF crypto/ec/ecp_oct.d.tmp -MT crypto/ec/ecp_oct.o -c -o crypto/ec/ecp_oct.o crypto/ec/ecp_oct.c
make[1]: *** No rule to make target `crypto/ec/ecp_sm2z256-x86.s', needed by `crypto/ec/ecp_sm2z256-x86.o'.  Stop.
make[1]: Leaving directory `/opt/GmSSL-master'

**Comment by guanzhi** [comment]
问题已经修复，请测试
