### ISSUE TITLE
 check下来 代码VS2012编译报错

### ISSUE THREAD

**Issue by Shun87** [guanzhi/GmSSL#609]
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\ADMINI~1\AppData\Local\Temp\nm27B.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: unresolved external symbol CRYPTO_memcmp
libcrypto.lib : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'

**Comment by guanzhi** [comment]
`CRYPTO_memcmp`的实现是由生成的汇编提供的，你看看为什么你的编译环境下生成汇编的时候出了问题
