### ISSUE TITLE
对于不再通过GitHub的Release发布版本更新的说明

### ISSUE THREAD

**Issue by guanzhi** [guanzhi/GmSSL#610]
为了更够让用户用到更新、更快、更安全、支持标准更全面的GmSSL，Code Release 中除了浏览器外的Release版本都已经删除。主分支的代码在默认配置下在最新的macOS和Travis CI的默认Linux环境下都可以编译通过。

**Comment by captain888888** [comment]
可以再Windows下编译吗？
