### ISSUE TITLE
【功能请求】ECDHE-SM2-WITH-SMS4-GCM-SM3

### ISSUE THREAD

**Issue by kevinis** [guanzhi/GmSSL#613]
您好，我是百度安全实验室[MesaLink](https://github.com/mesalock-linux/mesalink) TLS项目的负责人。最近我们使用Rust语言在[*ring*](https://github.com/mesalock-linux/ring/tree/bincat-sm)密码库和[rustls](https://github.com/mesalock-linux/rustls/tree/bincat-sm)两个项目中实现了SM2/3/4和ECDHE-SM2-WITH-SMS4-GCM-SM3，其中SM4使用GCM模式。

现在GmSSL已有ECDHE-SM2-WITH-SMS4-SM3，我们的代码和gmssl s_server握手可以通过证书验签和密钥交换，但是在gmssl解密报文时出错。问下关老师可不可以考虑近期实现带GCM的ECDHE-SM2-WITH-SMS4-GCM-SM3？之后我们可以联调测试一下。多谢！

**Comment by liclicli** [comment]
@kevinis @guanzhi Hi，既然考虑互联，顺便借个楼讨论一下：
1. 国密SM2曲线编号没有正式分配，GMSSL用的31会与IANA规定的group冲突(在supported groups扩展中使用)
2. SM2withSM3签名算法在GMSSL中为0x0707，这个目前还不会存在冲突；
这两个是否应该注册一下，或者按照IANA规定使用private use范围的值呢？

**Comment by guanzhi** [comment]
如 @liclicli 所说，目前SSL这部分的一个主要问题是算法编号的问题，如套件编号、签名-哈希算法编号、扩展编号等，以及SM1/2/3/4/9/ZUC在内的算法及各种模式的OID，对项目的长期维护和不同实现的互联都带来问题。虽然IANA有private use范围，但是把国密的编号放在这个范围内是否恰当还需要探讨，GmSSL想出一个稳定版本也需要首先把这些ID确定下来。另外对于TLS 1.2的国密套件和GM/T 0024 SSL VPN 1.1的国密套件，也需要一个类似RFC形式的文档描述协议的一些细节。

**Comment by kevinis** [comment]
同意。我们开发过程确实遇到了很多类似的问题。例如TLS NamedCurve中，gmssl的sm2p256v1使用0x001e，与x448曲线冲突；我们请求的ECDHE-SM2-WITH-SMS4-GCM-SM3也不是GM/T SSL-VPN标准规定的ciphersuite。但我们觉得以AES-GCM和为代表的AEAD是大势所趋，国密标准必然会跟进，所以我们想与国密开源社区的领头羊gmssl项目合作先把这一块做起来用起来。

gmtls.h中定义了GMTLS_CK_ECDHE_SM2_WITH_SMS4_GCM_SM3为0x0300E107，我们现在也是参照gmssl实现的。
https://github.com/guanzhi/GmSSL/blob/952321677f56a73191f55510e45d7b9c7240b4ea/include/openssl/gmtls.h#L91

**Comment by guanzhi** [comment]
由于项目进度的需求，我们近期可能会优先完善SM9算法。
GmSSL中目前已经有GCM的模块`EVP_sms4_gcm()`，增加SM4的GCM套件不会太复杂，如果 @kevinis 你有时间的话，欢迎你加入到GmSSL项目中，提供GCM套件的Pull Request，有问题我会协助你。

**Comment by kevinis** [comment]
@guanzhi 关于TLS 1.2的国密套件和RFC文档，您有什么想法我们可以帮忙推动么。我们正在起草这样一个RFC，借助合作高校的力量在国内推动标准化。

**Comment by guanzhi** [comment]
@kevinis 现在最需要的就是TLS 1.2、1.3的国密套件RFC，以及在AINA注册密码套件和扩展需要的编号。不过听你说百度已经开始做这件事了，不知道进展如何？

**Comment by kevinis** [comment]
我在https://github.com/guanzhi/GmSSL/blob/1c00e47681678afc16cb1bc04fe814adf732b4b3/ssl/s3_lib.c
加入了如下代码开启ECDHE_SM2_WITH_SMS4_GCM_SM3

```c
{
1,
GMTLS_TXT_ECDHE_SM2_WITH_SMS4_GCM_SM3,
GMTLS_CK_ECDHE_SM2_WITH_SMS4_GCM_SM3,
SSL_kECDHE,
SSL_aSM2,
SSL_SMS4GCM,
SSL_AEAD,
TLS1_2_VERSION, TLS1_2_VERSION,
DTLS1_BAD_VER, DTLS1_2_VERSION,
SSL_HIGH,
SSL_HANDSHAKE_MAC_SM3 | TLS1_PRF_SM3,
128,
128,
},
```

然后使用如下命令测试
```shell
gmssl s_server -key server.key -cert server.fullchain -accept 8443 -www

gmssl s_client -CAfile server.chain  -tls1_2 -cipher ECDHE-SM2-WITH-SMS4-GCM-SM3 -connect localhost:8443
```

测试证书在：https://gist.github.com/kevinis/58c6825b47093ffe94d73ad2fc0ffca6

客户端在加密报文时在如下位置出错：
https://github.com/guanzhi/GmSSL/blob/1c00e47681678afc16cb1bc04fe814adf732b4b3/crypto/evp/e_sms4_gcm.c#L306-L309

目前有点怀疑是IV长度的问题，求各位老师指点一二
