### ISSUE TITLE
NMAKE : fatal error U1073: 不知道如何生成“"crypto\ec\ecp_sm2z256-x86.asm"”

### ISSUE THREAD

**Issue by iamgossh** [guanzhi/GmSSL#615]
刚刚在编译时，遇到错误：
NMAKE : fatal error U1073: 不知道如何生成“"crypto\ec\ecp_sm2z256-x86.asm"”  

我看到下面也有朋友问这个问题，不知道解决了没有？

**Comment by iamgossh** [comment]
刚才看了看源代码，在crypto/ec/asm目录下，只有ecp_sm2z256-x86_64.pl文件，没有x86版本，难道只能编译64位的？

**Comment by guanzhi** [comment]
问题应该已经尝试修复，请下载最新代码测试。
x86汇编暂不提供32位。

**Comment by iamgossh** [comment]
> 问题应该已经尝试修复，请下载最新代码测试。
> x86汇编暂不提供32位。

关老师好，今天早上我下载了新版本，编译测试，出现下面的情况：
IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\think\AppData\Local\Temp\nm83D0.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 d2i_SM9PublicKey_fp
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 i2d_PublicParameters_fp
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 i2d_SM9PublicKey_fp
libcrypto.lib : fatal error LNK1120: 3 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”
Stop.
