### ISSUE TITLE
arm64编译失败

### ISSUE THREAD

**Issue by ghost** [guanzhi/GmSSL#617]
![snip20181123_1](https://user-images.githubusercontent.com/15758428/48934266-3e7a1880-ef3e-11e8-89f1-975ee0a57634.png)

**Comment by zhaoxiaomeng** [comment]
可能是你这边的编译器的问题，gmssl代码中使用的某些特性超出了 c99的范围。

**Comment by lewendy** [comment]
arm64在编译时，编译器现在默认会将隐式声明的warning直接当做error报出，所以有这个问题。
暂时没有找到很好的解决方案，应该可以在编译的时候添加-Wno-implicit-function-declaration，或者是当前报错是在test中，可以先注释掉报错的这两句，并不影响最终生成的库。
