### ISSUE TITLE
关于SM2-WITH-SMS4-SM3 

### ISSUE THREAD

**Issue by bruce-sunshine** [guanzhi/GmSSL#618]
TLS1.2下, 利用SM2-WITH-SMS4-SM3 cipher时, SSL会话会报错,错误为:
1078505472:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1385:SSL alert number 40

**Comment by zhenyuwei** [comment]
这个是国标VPN密码套件，和TLS协议握手，密码套件支持吗？

**Comment by bruce-sunshine** [comment]
如果初始化使用SSL_CTX_new(GMTLS_method)时,客户端程序会报错,错误为:
1078849536:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:

1078849536:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto/asn1/tasn_dec.c:1100:

1078849536:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=X509

1078849536:error:1416F00D:SSL routines:tls_process_server_certificate:ASN1 lib:ssl/statem/statem_clnt.c:1290:

**Comment by guanzhi** [comment]
GmSSL 支持两类套件，一类是用于 TLS 1.2 (以及未来的TLS 1.3）的套件，一类是 GM/T 0024 SSL VPN标准中定义的套件。由于 GM/T 0024 这个协议可以视为是和IETF TLS协议完全不同的协议，因此GmSSL中的GM/T 0024套件仅能应用GM/T 0024协议，在 TLS 1.2 协议中用了 GM/T 0024 的套件，就会报错。

**Comment by zhenyuwei** [comment]
这个是证书问题，查一下国密证书格式是否异常，不要使用SM2-SHA1的证书，GmSSL这个oid有问题，推荐使用SM2-SM3的证书。

**Comment by bruce-sunshine** [comment]
现在主要是想测试利用国密算法实现服务端和客户端通信, TLS1.2现在已经实现了ECDHE-SM2-WITH-SMS4-SM3, 其中key exchange algorithm算法采用的是ECDHE, 这边的目标是key exchange algorithm算法想采用SM2作为秘钥交换算法, 再就是库里面有利用GMTLS_method进行国密VPN通信的demo吗?

**Comment by HaoXuan40404** [comment]
问下这种方式如何加载双证书呢，密钥交换时应该用对方SM2的公钥加密，本地应该如何加载加密证书的私钥进行验证

**Comment by zhenyuwei** [comment]
GmSSL的GMTLS测试方式如下：
gmssl s_server -gmtls -accept port -cert sign.pem -key signkey.pem -dcert enc.pem -dkey enckey.pem -msg -debug
gmssl s_client -gmtls -connect ip:port -msg -debug
我觉得你需要看一下GM/T 0009的9.6密钥协商部分，SM2的密钥协商中有四组密钥对参与计算，当然你可以一组使用两次参与计算，这样就需要两组密钥对，应该能达到你的预期要求。如果使用四组不同密钥对，客户端就需要发送证书进行双向认证。

**Comment by bruce-sunshine** [comment]
OK，非常感谢指教。

**Comment by bing2018** [comment]
@zhenyuwei 请教下，4组密钥对进行双证书的双向认证需要怎样调试
使用：
gmssl s_server -gmtls -Verify 1 -accept ip:port -cert SS.pem -key SS.key -dcert SE,pem -dkey SE.key -msg debug
gmssl s_client gmtls -connect ip:port -cert CS.pem -key CS.key -xcert CE,pem -xkey CE.key -msg debug

一直有 
error:SSL routines:gmtls_output_cert_chaine: ee key too small:ssl/statem/statem_gmtls.c:128
error:gmtls_construct_client_certificate:internal error:ssl/statem/statem_gmtls.c:1347,
谢谢

**Comment by elitetony** [comment]
> 
> 
> @zhenyuwei 请教下，4组密钥对进行双证书的双向认证需要怎样调试
> 使用：
> gmssl s_server -gmtls -Verify 1 -accept ip:port -cert SS.pem -key SS.key -dcert SE,pem -dkey SE.key -msg debug
> gmssl s_client gmtls -connect ip:port -cert CS.pem -key CS.key -xcert CE,pem -xkey CE.key -msg debug
> 
> 一直有
> error:SSL routines:gmtls_output_cert_chaine: ee key too small:ssl/statem/statem_gmtls.c:128
> error:gmtls_construct_client_certificate:internal error:ssl/statem/statem_gmtls.c:1347,
> 谢谢

双向认证调试问题解决了吗？你是怎么测试的。我也遇到了同样的问题。

**Comment by zhenyuwei** [comment]
@bing2018 GmSSL暂时不支持国标GM/T 0024双向认证，流程没有完全实现，需要自己实现缺省的部分功能。

**Comment by huangyehui** [comment]
遇到类似问题，先mark借鉴下

**Comment by huangyehui** [comment]
> 用SM2-SHA1



> 使用GMTLS_method就变成国密VPN通信，这个需要参考国标GM/T 0024，服务端需要使用国密证书；
> 报错是证书问题，查一下服务器使用的是否为国密证书，不要使用SM2-SHA1的证书，GmSSL这个oid有问题，推荐使用SM2-SM3的证书；
> 不太清楚你想测什么，为什么在TLS1.2下测试国密VPN套件？

用了国密证书，还是会报header too long。 请问是否遇到类似情况？

**Comment by zhenyuwei** [comment]
拿TaSSL的测一下，单向的好像没问题，不用客户端发送证书，单向调试完了在去调试双向，没多大差异的 @huangyehui

**Comment by huangyehui** [comment]
> 户端发送证书，单向调试完了

好的，谢谢 ~ 刚刚用TASSL试了单向，也通了:)

**Comment by zhenyuwei** [comment]
> > 户端发送证书，单向调试完了
> 
> 好的，谢谢 ~ 刚刚用TASSL试了单向，也通了:)

gdb调试看看吧，可以编译Debug版本的，在对应的接口数据里面看一下错误信息，这个错误看不出来哪里出了问题。双向的gmssl需要调整的部分稍微有几处，慢慢看一下吧，尤其是数据长度那一块，好像是有问题。gmtls_construct_server_key_exchange/gmtls_construct_ske_sm2/gmtls_output_cert_chain 这几个接口里面的长度看一下有没有问题，这块应该很好修改的，双向好像DHE的SM2_compute_share_key接口是空实现的，这块自己参考sm2_exch.c和国标0009的内容实现就好了，代码都有，就是需要把调用逻辑实现一下就可以了。

**Comment by tengliu0929** [comment]
现在的gmssl版本是否完全支持国密的双向认证了，按照google搜出来的方法，抓包看的话，还是单向认证。如果支持双向认证，能否告知一个gmssl使用示例
