### ISSUE TITLE
我用360国密浏览器访问国密服务器，双方使用ECC_SM4_SM3算法，但是server-key-exchange包360始终验证失败

### ISSUE THREAD

**Issue by zhangshuang01** [guanzhi/GmSSL#62]
国密服务器发送时是把server hello, server certificate, server key exchange 三个记录放在一个包里发送的，我仔细看了server hello, server certificate的内容，都没有问题，我觉得问题只能出在server key exchange的签名上了，我按照以下方式进行签名都试过了360还是会返回错误。
1. M = client random(32) + server random(32) + 加密证书长度（3） + 加密证书的内容（变长）,只对M内容进行签名
2. Z = sm3(entl || id || a || b || Xg  ||Yg  || Xa || Ya),  对Z||M进行SM2签名，
以上两种方式签名360验证都失败， 我服务器端的加密证书签名证书用的是一个 。 
有哪位朋友遇到与我相似的问题，还请讨论赐教下，万分感谢！

**Comment by guanzhi** [comment]
你访问的这个国密服务器的链接什么？

**Comment by mrpre** [comment]
SM2_DEFAULT_ID用的是 SM2_DEFAULT_ID_GMT09还是SM2_DEFAULT_ID_GMSSL

**Comment by zhangshuang01** [comment]
@guanzhi 
我没有用gmssl开源包，国密服务器没有链接，是我自己搭建的环境，openssl也是自己改的加了国密算法套件的功能。

**Comment by zhangshuang01** [comment]
@mrpre 
我没有使用SM2_DEFAULT_ID_GMSSL，因为我用的不是gmssl。 我的ID使用“1234567812345678”与“31323334353637383132333435363738”都试过，后者ID是在国密规范里看到的。

**Comment by guanzhi** [comment]
@zhangshuang01 你的问题需要咨询360，或者360浏览器的测试方上海格尔

**Comment by zhangshuang01** [comment]
@guanzhi 嗯，好的，谢谢你！

**Comment by zhangshuang01** [comment]
@mrpre 
你好，我看你提过类似的问题，客户端是360浏览器，服务器端用的gmssl吧，测试通过了吗？

**Comment by conezxy** [comment]
采用第二种方式（带Z值计算）是对的，请把你的代码贴出来

或者把以下数据贴出来：
- 签名密钥/证书
- 加密密钥/证书
- Z值的计算过程（包括SM3之前的输入，SM3之后的结果也即Z值）
- SM2签名时每次SM3摘要(EVP_SignUpdate)的输入
- SM2签名结果

**Comment by gujinqiangggs** [comment]
@zhangshuang01 你好，你的360浏览器是怎么发送出来国密的client hello的，按我的理解，如果是国密的协商，起码在client hello里的cipher suites里应该包含类似ECC_SM4_SM3 （代码0xe013）或者ECDHE_SM1_SM3（0xe011）这样的密码套件，但是我抓包跟本没有看到。我用的http://se.360.cn/event/gmzb.html这个网址下载的360浏览器，直接安装使用的，也没有导入证书和Ukey等，页面介绍的用法我也没看太懂，我就直接访问我的服务端的。还请详述你使用360浏览器的操作步骤，以便我能进行国密的ssl协商，多谢！

**Comment by zhangshuang01** [comment]
@gujinqiangggs 你好，不好意思我好久没有登录github了，安装国密版的360后会有一个文件， smwl, 你需要在里面添加自己要访问的ip以及端口。

**Comment by gujinqiangggs** [comment]
@zhangshuang01 恩，找到了，谢谢

**Comment by zhangshuang01** [comment]
@conezxy 现在我又换了一种角度，不去实现服务器如何发送server key exchange了， 我现在想要验证服务器发过来的国密server key exchange包， 还是先计算了Z值，对Z||message 做SM3摘要，其中消息就是客户端随机数，服务器随机数，三字节证书长度，加密证书内容。对收到的签名内容做验证。也是一直验证失败。服务器是标准的国密服务器。身份标识id ,0x31323334353637383132333435363738, 0x1234567812345678都试过，始终找不到原因，还请帮忙想想，我是否还有忽略的内容！谢谢！

**Comment by zhangshuang01** [comment]
@conezxy 
以下是对服务器端server key exchange的签名验证代码，请帮忙看下：
                        enc_cert = sk_X509_value(s->session->sess_cert->cert_chain, 1);
                        enc_cert_len = i2d_X509(enc_cert, NULL);
                       
                        /*for preprocess1 mem buf*/
                        if ((tempbuf1 = BUF_MEM_new()) == NULL)
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }
                        if (!BUF_MEM_grow(tempbuf1,SSL3_RT_MAX_PLAIN_LENGTH))
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }

                        /*for cert len mem buf*/
                        if ((tempbuf2 = BUF_MEM_new()) == NULL)
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }
                        if (!BUF_MEM_grow(tempbuf2,SSL3_RT_MAX_PLAIN_LENGTH))
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }
                     
                        /*for enc cert content mem buf*/
                        if ((tempbuf = BUF_MEM_new()) == NULL)
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }
                        if (!BUF_MEM_grow(tempbuf,SSL3_RT_MAX_PLAIN_LENGTH))
                        {
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }

                        cert_buff = tempstart = (unsigned char *)&(tempbuf->data[0]);
                        preprocess_step1 = (unsigned char *)&(tempbuf1->data[0]);
                        cert_len_ptr = (unsigned char *)&(tempbuf2->data[0]);
                        
                        /*tempstart pos will change after i2d_X509, SO with cert_buff to save origin pos*/
                        i2d_X509(enc_cert, &(tempstart));
                        
                        //cert_len present;
                        cert_len_ptr[0] = (enc_cert_len >> 16) & 0xff;
                        cert_len_ptr[1] = (enc_cert_len >> 8) & 0xff;
                        cert_len_ptr[2] = enc_cert_len & 0xff;
                       
                        /*prepare verify signature work */
                        /*compute z first*/
                        SM3HashWithPreprocess1(preprocess_step1);   
                        
                        EVP_VerifyInit_ex(&md_ctx, md, NULL);
                        /*copy preprocess z value*/
                        EVP_VerifyUpdate(&md_ctx,preprocess_step1,SSL3_RANDOM_SIZE);
                        /*the following is real message content*/
                        EVP_VerifyUpdate(&md_ctx,&(s->s3->client_random[0]),SSL3_RANDOM_SIZE);
                        EVP_VerifyUpdate(&md_ctx,&(s->s3->server_random[0]),SSL3_RANDOM_SIZE);

                        EVP_VerifyUpdate(&md_ctx, cert_len_ptr, 3);
                      
                        EVP_VerifyUpdate(&md_ctx, cert_buff, enc_cert_len);
                        /*p is signature and n is signature len*/                      
                        if (EVP_VerifyFinal(&md_ctx,p,(int)n,pkey) <= 0)
                        {
                                /* bad signature */
                                al=SSL_AD_DECRYPT_ERROR;
                                SSLerr(SSL_F_SSL3_GET_KEY_EXCHANGE,SSL_R_BAD_SIGNATURE);
                                goto f_err;
                        }        
                        
                        
／*预处理，计算Z值*／                        
int SM3HashWithPreprocess1(unsigned char *hash_value)
{
  unsigned short ID_bit_len;
  unsigned char *step1_input;
  unsigned int step1_input_byte_len;
  unsigned int signer_ID_byte_len = SIGNER_ID_DEFAULT_LEN;

  unsigned char a[32]={0xFF, 0xFF, 0xFF, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF,
                       0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
                       0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
                       0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFC};

  unsigned char b[32]={0x28, 0xE9, 0xFA, 0x9E, 0x9D, 0x9F, 0x5E, 0x34,
                       0x4D, 0x5A, 0x9E, 0x4B, 0xCF, 0x65, 0x09, 0xA7,
                       0xF3, 0x97, 0x89, 0xF5, 0x15, 0xAB, 0x8F, 0x92,
                       0xDD, 0xBC, 0xBD, 0x41, 0x4D, 0x94, 0x0E,  0x93};

  unsigned char x_G[32]={0x32, 0xC4, 0xAE, 0x2C, 0x1F, 0x19, 0x81, 0x19,
                         0x5F, 0x99, 0x4,  0x46, 0x6A, 0x39, 0xC9, 0x94,
                         0x8F, 0xE3, 0xB,  0xBF, 0xF2, 0x66, 0xB,  0xE1,
                         0x71, 0x5A, 0x45, 0x89, 0x33, 0x4C, 0x74, 0xC7};

  unsigned char y_G[32]={0xBC, 0x37, 0x36, 0xA2, 0xF4, 0xF6, 0x77, 0x9C,
                         0x59, 0xBD, 0xCE, 0xE3, 0x6B, 0x69, 0x21, 0x53,
                         0xD0, 0xA9, 0x87, 0x7C, 0xC6, 0x2A, 0x47, 0x40,
                         0x2,  0xDF, 0x32, 0xE5, 0x21, 0x39, 0xF0, 0xA0};

  unsigned char ID[16] ={0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
                             0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38};

  /*enc cert public key*/
  unsigned char publickey[64] = {0xfe, 0x6a, 0x9e, 0x2b, 0xb0, 0x4d, 0x4b, 0x4c, 0x77, 0x5b, 0x57, 0xc4, 0xa9, 0x17, 0x55, 0x06,
                                                0x67, 0x15, 0x22, 0x11, 0xb2, 0xd1, 0xee, 0x3a, 0x8a, 0xad, 0xc6, 0x6f, 0xda, 0x36, 0x58, 0xa0,
                                                0xbd, 0x66, 0xe1, 0x19, 0xce, 0x8f, 0xbb, 0x56, 0x19, 0x79, 0xcc, 0x18, 0xa9, 0xa3, 0x5a, 0x5e,
                                                0x80, 0x31, 0x65, 0x3d, 0x7c, 0xb1, 0x2f, 0x02, 0xd1, 0x57, 0xed, 0x6a, 0xce, 0x13, 0x87, 0x60};

 step1_input_byte_len = (2 + signer_ID_byte_len + 32 * 6);
  if ( !(step1_input = (unsigned char *)malloc(step1_input_byte_len)) )
  {
    return (-1);
  }
  memset(step1_input, 0 , step1_input_byte_len);
/* 预处理1 */
  ID_bit_len = (unsigned short)(signer_ID_byte_len*8);

    memcpy(step1_input, (unsigned char *)(&ID_bit_len) + 1, 1);
    memcpy((step1_input + 1), (unsigned char *)(&ID_bit_len), 1);
 
  memcpy((step1_input + 2), ID, signer_ID_byte_len);
  memcpy((step1_input + 2) + signer_ID_byte_len, a, 32);
  memcpy((step1_input + 2) + signer_ID_byte_len + 32, b, 32);
  memcpy((step1_input + 2 + signer_ID_byte_len + 64), x_G, 32);
  memcpy((step1_input + 2 + signer_ID_byte_len + 96), y_G, 32);
  memcpy((step1_input + 2 + signer_ID_byte_len + 128), publickey, 64);
  sm3(step1_input, step1_input_byte_len, hash_value);    
  
  free(step1_input);
  return 0;
}        
为了避免不必要的麻烦，签名证书与加密证书用的同一个证书。

**Comment by conezxy** [comment]
@zhangshuang01 
1. 国密服务器也是你自己的实现吗？你是说你自己验证自己的实现也不通过？
2. 从你后面贴的代码上看不出明显的问题，请确认你的SM2/SM3实现是否正确，可以尝试验证标准的国密证书（用根证书的公钥验证下级的签名）来确认这一点。

**Comment by zhangshuang01** [comment]
@conezxy 
国密服务器是符合国密标准的，由别家提供的，并且人家已经验证没问题的，我现在就是自己在实现一个客户端，这个客户端验证服务器的server key exchange签名一直有问题，服务器肯定没有问题，证书也是标准的。那就只可能是客户端的SM2/Sm3实现的有点问题。
另外我想确认一下，
1.做摘要预处理时，我用的那个64字节的公钥，是通过openssl x509 -in enc.pem -text命令查看，取的里面的公钥部分，取这个做预处理没有问题吧？（签名，加密同一个证书）
2.预处理时用的用户身份标识ID是0x31323334353637383132333435363738吗？

**Comment by zhangshuang01** [comment]
谢谢各位的回复，问题已经解决！

**Comment by eva520** [comment]
@zhangshuang01 怎么解决的哦 我也遇到这个问题

**Comment by xiejianjun417** [comment]
@zhangshuang01 请问，是怎么解决的呀？
