### ISSUE TITLE
openssl 1.1.1 国密通信

### ISSUE THREAD

**Issue by HaoXuan40404** [guanzhi/GmSSL#620]
关老师，请问下11月20日openssl1.1.1新特性中提到支持的国密算法包括通信吗，看到只有加解密的接口

**Comment by zhaoxiaomeng** [comment]
您好，根据对 openssl1.1.1源代码的分析，没有发现国密算法通信的相关代码，官方的公告中也没有提到国密通信组件。

**Comment by HaoXuan40404** [comment]
好的，谢谢
