### ISSUE TITLE
在windows下编译，出现下面的问题：

### ISSUE THREAD

**Issue by iamgossh** [guanzhi/GmSSL#622]
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\think\AppData\Local\Temp\nm9D8C.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 d2i_SM9PublicKey_fp
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 i2d_PublicParameters_fp
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 i2d_SM9PublicKey_fp
libcrypto.lib : fatal error LNK1120: 3 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”
Stop.

**Comment by cntpro** [comment]
perl Configure  VC-WIN64A no-asm no-shared  参数时可以编译通过

**Comment by cuzz** [comment]
源代码里面缺少这三个函数的实现，自己手动加上就行
源文件：crypto\sm9\sm9_asn1.c

int i2d_SM9PublicKey_fp(FILE *fp, SM9PublicKey *a)
{
	return ASN1_item_i2d_fp(ASN1_ITEM_rptr(SM9PublicKey), fp, a);
}
 
int i2d_PublicParameters_fp(FILE *fp, SM9PublicParameters *a)
{
	return ASN1_item_i2d_fp(ASN1_ITEM_rptr(SM9PublicParameters), fp, a);
}

SM9PublicKey *d2i_SM9PublicKey_fp(FILE *fp, SM9PublicKey **pp)
{
	return ASN1_item_d2i_fp(ASN1_ITEM_rptr(SM9PublicKey), fp, pp);
}

**Comment by guanzhi** [comment]
这个问题在master分支中已经修复了，请下载最新代码试一下

**Comment by iamgossh** [comment]
> 这个问题在master分支中已经修复了，请下载最新代码试一下

关老师，又要打扰您了，我下载了最近的代码，编译又出现新的如下问题：

        "C:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1.def
Error: ACCESS_DESCRIPTION_free does not have a number assigned
NMAKE : fatal error U1077: “"C:\Perl64\bin\perl.exe"”: 返回代码“0x19”
Stop.

**Comment by zhaoxiaomeng** [comment]
目前我们在 vs2017上测试是没问题的，可以看 appveyor 的编译记录。 @Nu1i

**Comment by Baymini-zx** [comment]
`dllmain.c
        "D:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1.def
        "D:\Perl64\bin\perl.exe" -i.tmp -pe "s|^LIBRARY\s+crypto32|LIBRARY libcrypto-1_1|;" libcrypto-1_1.def
        DEL libcrypto-1_1.def.tmp
        "D:\Perl64\bin\perl.exe" "util\mkrc.pl" libcrypto-1_1.dll > libcrypto-1_1.rc
        rc /folibcrypto-1_1.res libcrypto-1_1.rc
Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\ZHAOXI~1\AppData\Local\Temp\nmE5AE.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_ciphernames
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_digestnames
libcrypto.lib : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”
Stop.`
