### ISSUE TITLE
gmssl网页链接404

### ISSUE THREAD

**Issue by HaoXuan40404** [guanzhi/GmSSL#623]
**Describe the bug**
此[网页](http://gmssl.org/docs/java-api.html)中java api合入到代码中后，此[链接](
https://github.com/guanzhi/GmSSL-Java-Wrapper)打不开

**Expected behavior**
修改此处描述

**Comment by HaoXuan40404** [comment]
想问下关于libssl库调用的接口有相关文档吗，想用boost库去调用libssl实现一个通信的demo，有参考文档吗

**Comment by HaoXuan40404** [comment]
好的，十分感谢

**Comment by zhaoxiaomeng** [comment]
问题已经修复。
