### ISSUE TITLE
请问在申威411平台上编译GMSSL 需要添加什么参数吗？

### ISSUE THREAD

**Issue by JackLee889** [guanzhi/GmSSL#624]

**Comment by JackLee889** [comment]
关老师您好，我在申威411平台上用GMSSL做sm3，结果和在x86平台下做的结果不一样，请问是不是有什么编译参数需要修改？
以下是对“1234567812345678”做sm3的数据：
申威411：
bd 10 dc d2 80 f9 89 26 34 83 e5 c8 a7 43 5e 40 
4b 84 9c 5c dc f0 2a 5f 95 e1 97 ab 30 d8 1b 20 
x86平台：
93 cc 77 fb a0 df 95 ec cf 9f 03 84 da 1a ad 95 
71 bb cf c1 6a e6 65 72 f7 dc 8c ff 89 5d 45 30
谢谢！

**Comment by guanzhi** [comment]
config时加上`-DCPU_BIGENDIAN`应该可以解决这个问题。
通过test/sm3test 可以检查SM3运算是否正确
