### ISSUE TITLE
麻烦老师帮忙看看，编译出错，windows, 已排除常规问题

### ISSUE THREAD

**Issue by qfcfm** [guanzhi/GmSSL#626]
"C:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1.def
Error: ACCESS_DESCRIPTION_free does not have a number assigned

util\libcrypto.num util\libssl.num两个文件大小为0， 不知是否和这个相关。

**Comment by qfcfm** [comment]
"C:\Perl64\bin\perl.exe" "util\mkdef.pl" "crypto" 32 > libcrypto-1_1.def
Error: ACCESS_DESCRIPTION_free does not have a number assigned

util\libcrypto.num  util\libssl.num两个文件大小为0， 不知是否和这个相关。

**Comment by shanxueyi** [comment]
我也是这样 不知道什么情况

**Comment by guanzhi** [comment]
这个问题已经尝试解决了，最新的master分支还有这个问题吗？

**Comment by shanxueyi** [comment]
在新版本上应该解决了  我再也没有遇到这样的问题

**Comment by qfcfm** [comment]
调用make clean时报错，
-del /Q /F $(PROGRAMS)  $(ENGINES) $(SCRIPTS)
此命令超过了make的最大长度。 

另外windows下想要编译/MT模式的，有没有直接的相关命令， 还是必须手动改makefile?
