### ISSUE TITLE
SM9算法

### ISSUE THREAD

**Issue by newdible** [guanzhi/GmSSL#63]
有没有最近在研究SM9的朋友啊？有些问题想要讨论下，有兴趣的可以一起探讨啊。

**Comment by guanzhi** [comment]
能否提供一份SM9的标准文本（正式的国密纸版）？

**Comment by newdible** [comment]
是这样的，正式的国密纸质我咨询过出版社，目前还没有。各图书网站上也没有，我只是在网上看到一个电子版本的，但是不带GB标识。目前我就是看的这个版本。阅读过程中发现一些地方不是很明白，想找个明白人请教请教啊。网址是：http://dacas.cn/column.aspx?id=152，可以参考啊

**Comment by wanghs09** [comment]
我最近也在看，有什么问题吗？

**Comment by newdible** [comment]
看到一些计算结果不知具体是怎么运算的？可以一起交流下吗？我的QQ 357173036，可以加我啊

**Comment by wanghs09** [comment]
嗯，你在这写一下吧，我们都看看，有明白的就给你说了

**Comment by newdible** [comment]
群G2中的点坐标满足扭曲线方程，即P2点坐标(XP2,YP2)满足 
其中 ,群G2的域特征也是q，P2点坐标的表示形式是：ai+b形式，即复数域表示形式。
	即：
a=0x85AEF3D078640C98597B6027B441A01FF1DD2C190F5E93C454806C11D8806141;
b=0x3722755292130B08D2AAB97FD34EC120EE265948D19C17ABF9B7213BAF82D65B;
XP2=ai+b;
同理
c=0x17509B092E845C1266BA0D262CBEE6ED0736A96FA347C8BD856DC76B84EBEB96;
d=0xA7CF28D519BE3DA65F3170153D278FF247EFBA98A71A08116215BBA5C999A7C7;
YP2=ci+d
1、	但是我将上述值代入扭曲线方程，该方程并不成立？我的理解或者操作哪里有什么错误吗？
2、	点乘[k2]P2的计算也不正确，不知问题出在哪里？我用同样的工具计算[k1]P1是正确的。
谢谢

**Comment by guanzhi** [comment]
中科院的SM9文档在第一部分上不是很详细，并且这个版本也不是正式的出版物。如果已经有了正式的文档(GM/T 0044?)，基于正式出版物讨论为好。

**Comment by guanzhi** [comment]
@newdible 由于这个标准是中科院做的，您（的单位）可以直接联系中科院这个标准的作者

**Comment by guanzhi** [comment]
GmSSL (version 2.0) 在SM9会首先基于更简单的超奇异曲线上的Tate对来做，标准中的256-bit BN曲线在2.0版中暂不会支持。

**Comment by newdible** [comment]
嗯嗯，好的，谢谢。我也在时刻咨询呢，也希望能尽快拿到正式版本。

**Comment by wanghs09** [comment]
嗯，这个我也验证了一下，不过我对扩域运算不是很熟悉。
你看参数那个pdf 第2页，里面约化多项式\alpha=-2，也就意味着i^2=-2（在你的式子里）。第3页，表示成向量的扩域元素，左边是第1维。
那么假如我们写成xp2=(xp2r, xp2i), yp2=(yp2r, yp2i)
测试如下等式是成立的
(2*yp2i*yp2r - 3*(xp2i^2)*xp2r+2*xp2r^3-b)%q=0
(yp2i^2-2*yp2r^2 +6*(xp2r^2)*xp2i-xp2i^3)%q=0
你可以试试，有什么我们再讨论。

**Comment by newdible** [comment]
@wanghs09 非常感谢，我按照你说的重新梳理了一遍，成功验证P2为扭曲线上的一点。我之前的理解错误点在于约化多项式搞错了，非常感谢。我接下来要验证G2上的点乘，我目前所用的工具，非有理数的好像计算不出来，我再想想其他办法验证一下

**Comment by newdible** [comment]
@wanghs09 我一般都是用Mathematic工具验证大数据运算，我现在用这个工具验证此扩域中的运算始终会卡死，估计计算带有sqrt[2]的数据时，计算量较大。即计算[k]P2=[k](xpr*sqrt[2]*i+xpi, ypr*sqrt[2]*i+ypi)时，计算不出来。你有好的验证工具或者验证方法吗？谢谢

**Comment by wanghs09** [comment]
@newdible 我主要用python，做模运算很方便，只是我太忙了，很少做实现
