### ISSUE TITLE
不能在php5.6中使用吗？是否只能在php7以上版本才可以？

### ISSUE THREAD

**Issue by MrCPF** [guanzhi/GmSSL#632]
在php5.6源码中ext/openssl替换成GmSSL对应的php/openssl目录后编译安装失败，是因为php版本太低原因吗

**Comment by guanzhi** [comment]
这个模块是直接在PHP 7中的openssl模块上改的，可能无法直接用在PHP 5.6中。
因为修改的代码量非常少，你可以把这些修改移植到 PHP 5.6 的openssl模块中。
