### ISSUE TITLE
crypto/aes/aes_core.c:39:10: fatal error: 'assert.h' file not found

### ISSUE THREAD

**Issue by yazhouZhang** [guanzhi/GmSSL#633]
编译与安装
在Linux和Mac下的编译和安装
./config
make
make test
sudo make install
按这个操作，结果到make
AsiaZhang:GmSSL-master zhangyazhou$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _all
clang  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl-ios64/ssl\"" -DENGINESDIR="\"/usr/local/openssl-ios64/lib/engines-1.1\"" -O3 -D_REENTRANT -arch arm64 -mios-version-min=7.0.0 -isysroot /SDKs/ -fno-common  -fPIC -MMD -MF crypto/aes/aes_core.d.tmp -MT crypto/aes/aes_core.o -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
clang-6.0: warning: no such sysroot directory: '/SDKs/' [-Wmissing-sysroot]
crypto/aes/aes_core.c:39:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [crypto/aes/aes_core.o] Error 1
make: *** [all] Error 2

我的openssl version
GmSSL 2.4.2 - OpenSSL 1.1.0d  3 Dec 2018
整个文件都找不到assert.h

**Comment by guanzhi** [comment]
assert.h 是C语言的标准头文件

**Comment by yisRookie** [comment]
你好 我这边编译 i386 和 x86_64 的包的时候，也报了你这个错误，想问下你有没有解决了这个问题
