### ISSUE TITLE
关于GmSSL Java API编译

### ISSUE THREAD

**Issue by shanxueyi** [guanzhi/GmSSL#634]
我在windows10下成功编译静态库（no-shared）gmssl和JAVA版本，但是因为是静态库在执行GmSSL\java\GmSSL.java    System.loadLibrary("gmssljni");
会无法加载库（好像在windos下库的加载名和方式和unix下不一样）。

所以我改成System.load（“D:\GmSSL\java|\libgmssljni.lib”）；又报 java.lang.UnsatisfiedLinkError:   %1 不是有效的 Win32 应用程序

之后我又改成共享库方式编译 但是又报“ NMAKE : fatal error U1073: 不知道如何生成“""””

我查看makefile在这个地方有问题
libgmssljni.lib: java\GmSSL.obj libcrypto.lib "" "util\mkdef.pl"
我换成 
libgmssljni.lib: java\GmSSL.obj libcrypto.lib "util\mkdef.pl"
又有其他错误 所以我真不知道怎么解决了

@guanzhi 希望能解决下

**Comment by guanzhi** [comment]
在Mac/Linux下可以通过在Configure文件的`$config{dirs}`中增加`java`，自动通过make编译java模块，但是不支持Windows。Java模块实际上就是一个简单的JNI模块，首先编译出libcrypto的dll动态库或者lib静态库，然后把GmSSL.c编译成libgmssljni.dll的动态库就可以被Java LoadLibrary了。因为我们项目组没有熟悉Windows的人员，因此在Windows编译的支持上会有一些问题，还希望社区里熟悉Windows开发的用户能够加入项目Windows编译的维护工作。

**Comment by shanxueyi** [comment]
我最后使用Visual Studio 2017 成功编译出Windows版本库。
有三点需要注意的 
1、jni.h和jni_md.h要换成JDK下的.h 如（C:\Program Files\Java\jdk1.8.0_181\include）
2、jni_md.h 内的内容要使用extern "C" {}
3、需要连接ws2_32.lib库

我虽然编译和运行成功了  但是在部署上有点问题 在没有vs上的机器会缺少依赖
希望有懂的人能联系我
@guanzhi

**Comment by cntpro** [comment]
@shanxueyi   配置是加上no-shared静态编译试试，好像不需要依赖VS的库文件 
如 perl Configure VC-WIN64A-masm no-asm no-shared

**Comment by DuanZPeng** [comment]
> 我最后使用Visual Studio 2017 成功编译出Windows版本库。
> 有三点需要注意的
> 1、jni.h和jni_md.h要换成JDK下的.h 如（C:\Program Files\Java\jdk1.8.0_181\include）
> 2、jni_md.h 内的内容要使用extern "C" {}
> 3、需要连接ws2_32.lib库
> 
> 我虽然编译和运行成功了 但是在部署上有点问题 在没有vs上的机器会缺少依赖
> 希望有懂的人能联系我
> @guanzhi

怎么编译的，可以说详细点儿吗

**Comment by cntpro** [comment]
> 我最后使用Visual Studio 2017 成功编译出Windows版本库。
> 有三点需要注意的
> 1、jni.h和jni_md.h要换成JDK下的.h 如（C:\Program Files\Java\jdk1.8.0_181\include）
> 2、jni_md.h 内的内容要使用extern "C" {}
> 3、需要连接ws2_32.lib库
> 
> 我虽然编译和运行成功了 但是在部署上有点问题 在没有vs上的机器会缺少依赖
> 希望有懂的人能联系我
> @guanzhi

libcrypto.lib和gmssljni.dll都静态编译

**Comment by shanxueyi** [comment]
> > 我最后使用Visual Studio 2017 成功编译出Windows版本库。
> > 有三点需要注意的
> > 1、jni.h和jni_md.h要换成JDK下的.h 如（C:\Program Files\Java\jdk1.8.0_181\include）
> > 2、jni_md.h 内的内容要使用extern "C" {}
> > 3、需要连接ws2_32.lib库
> > 我虽然编译和运行成功了 但是在部署上有点问题 在没有vs上的机器会缺少依赖
> > 希望有懂的人能联系我
> > @guanzhi
> 
> 怎么编译的，可以说详细点儿吗

使用vs的 “现有代码创建项目" 
在设置 include 和链接的lib  中间缺少什么再去搜索 添加上 最后生成了gmssljni.so

**Comment by yskcoder** [comment]
> 在Mac/Linux下可以通过在Configure文件的`$config{dirs}`中增加`java`，自动通过make编译java模块，但是不支持Windows。Java模块实际上就是一个简单的JNI模块，首先编译出libcrypto的dll动态库或者lib静态库，然后把GmSSL.c编译成libgmssljni.dll的动态库就可以被Java LoadLibrary了。因为我们项目组没有熟悉Windows的人员，因此在Windows编译的支持上会有一些问题，还希望社区里熟悉Windows开发的用户能够加入项目Windows编译的维护工作。

最新版本的master用linux也生成不了gmssljni.so，安装编译是成功的，开启java就失败了

**Comment by knull-cn** [comment]
> 我最后使用Visual Studio 2017 成功编译出Windows版本库。
> 有三点需要注意的
> 1、jni.h和jni_md.h要换成JDK下的.h 如（C:\Program Files\Java\jdk1.8.0_181\include）
> 2、jni_md.h 内的内容要使用extern "C" {}
> 3、需要连接ws2_32.lib库
> 
> 我虽然编译和运行成功了 但是在部署上有点问题 在没有vs上的机器会缺少依赖
> 希望有懂的人能联系我
> @guanzhi
我碰上过这个问题：可能系统中默认安装了openssl库，导致运行的时候用的是openssl库，而不是gmssl库。所以，在load的时候，需要指定库：System.load("D:\\mine\\src\\github.com\\GmSSL\\blockchain\\libs\\libcrypto-1_1-x64.dll");
