### ISSUE TITLE
请问Gmssl用到了哪些依赖库？

### ISSUE THREAD

**Issue by 1178209138** [guanzhi/GmSSL#635]
如题

**Comment by guanzhi** [comment]
GmSSL不依赖第三方的库

**Comment by 1178209138** [comment]
那请问除了c标准库还用到了那些库？ 用到的库跟OpenSSL是一样的吗？

**Comment by guanzhi** [comment]
从一般意义上说，GmSSL是不依赖第三方库的。比如有些SM2/SM9的实现依赖GMP库或MIRACL库，而GmSSL包含这些算法的完整实现，因此不依赖第三方的库。严格来说，依赖这些库：

1. 标准C库
2. 如果要支持动态库载入，需要系统的dl库
3. 如果要支持多线程，需要系统的线程库，如pthread
4. 如果要使用某个ENGINE，需要ENGINE的库以及（可能需要）密码硬件供应商的库

**Comment by 1178209138** [comment]
谢谢你的回复，
因为我打算移植gmssl到sgx中运行sm4算法，除标准c库外的库需要移植，需要绕过OS API用sgx sdk APIS实现。  而openssl已有移植版本，也就是完成了它的依赖库（如pthread）的移植，那么只有gmssl用到的额外的库需要移植了。 所以我想确认一下sm4算法有额外的依赖库吗？

**Comment by bingzhux** [comment]
> 谢谢你的回复， 我打算移植gmssl到sgx中运行sm4算法，除标准c库外的库需要移植，需要绕过OS API用sgx sdk APIS实现。 即重写依赖库里用到的OS API，再重新生成静态库，因为SGX不支持不可信动态库。想请教一下这个方案的可行性，可行的话 能否评估一下工作量。

@1178209138 你这个想法，后来有进展吗？+ @nntp4 @jnxxhzz @yang8621

**Comment by nntp4** [comment]
> > 谢谢你的回复， 我打算移植gmssl到sgx中运行sm4算法，除标准c库外的库需要移植，需要绕过OS API用sgx sdk APIS实现。 即重写依赖库里用到的OS API，再重新生成静态库，因为SGX不支持不可信动态库。想请教一下这个方案的可行性，可行的话 能否评估一下工作量。
> 
> @1178209138 你这个想法，后来有进展吗？+ @nntp4 @jnxxhzz @yang8621

第一，SM2/SM3/SM4算法已经在openssl当中实现了，intel 实现了一个支持SGX的openssl分支 https://github.com/intel/intel-sgx-ssl
如果只需要使用SM2/SM3/SM4系列算法推荐使用sgx-ssl，对于SM9/ZUC算法目前仍需要将GmSSL移植到SGX当中
第二，关于如何移植GmSSL，及工作进展
目前除socket模块的相关syscall其他部分均已完成，并在enclave中通过了一部分单元测试，完成全部的移植工作还需要一定时间。以我目前的时间安排，预计端午节以后就可以完成工作，或者端午节过后的下一周。@bingzhux
