### ISSUE TITLE
windows系统，编译java

### ISSUE THREAD

**Issue by DuanZPeng** [guanzhi/GmSSL#637]
windows下不能编译java jni所需动态库。
最终生成的 makefile 如下：
libgmssljni.lib: java\GmSSL.obj libcrypto.lib "" "util\mkdef.pl"  空格中是否缺少.num文件？
不能正确执行nmake，生成不了def文件。

希望解决一下，谢谢

**Comment by guanzhi** [comment]
请看 #634
