### ISSUE TITLE
请问一下，gmssl 命令行工具支不支持 生成国密的公私钥，以及采用国密算法的证书？

### ISSUE THREAD

**Issue by tobiaswang** [guanzhi/GmSSL#64]
如题，请问一下，gmssl 命令行工具支不支持 生成国密的公私钥，以及采用国密算法的证书，
看帮助没看出来，如果支持的话具体参数是什么？多谢

**Comment by guanzhi** [comment]
源码中的`demo/gmssl/selfsign.c`可以生成一个自签名的SM2证书，并且将密钥和证书都打印出来。
