### ISSUE TITLE
请教下大家，使用sm2加密， SM2_encrypt函数返回的加密数据为空~ ~~ 加密失败~~~

### ISSUE THREAD

**Issue by yiqingyu** [guanzhi/GmSSL#641]
/* 加密 */
unsigned char* encrypt_with_sm2(const cipher_in_t *in, EC_KEY *ec_key)
{
    unsigned char *out_buf = NULL;
    size_t out_len, ret;
    //分配待加密数据空间，为16字节整数倍。
    out_buf = (unsigned char *) malloc(65535);
    memset(out_buf, 0, 65535);
    out_len = 0;		
    ret = SM2_encrypt(NID_sm3, in->in_data, in->in_data_len, out_buf, &out_len, ec_key);
    if (ret == 0) 
    {
	printf("SM2_encrypt error!! \n");
    }
    //打印密文
    printData(out_buf,strlen((char*)out_buf));		
	
    return out_buf;
}

ec_key 是由 以下获得：
EC_KEY* generate_ec_key()
{
   EC_KEY *sm2key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
   EC_KEY_generate_key(sm2key); 
   EC_KEY_print_fp(stdout, sm2key, 1);
   return sm2key;
}

SM2_encrypt函数参数感觉传的没有问题，我只是加密了几十个字节的数据，  唯一疑惑的是，SM2_encrypt的参数ec_key 不能由EC_KEY_generate_key自动生成嘛？

**Comment by YWTL** [comment]
> **我使用如下代码加密解密都成功。**
> 
> ```
> #include <stdio.h>
> #include <time.h>
> #include <openssl\sms4.h>
> #include <openssl\sm3.h>
> #include <openssl\sm2.h>
> #include <openssl\ec.h>
> #include <openssl\crypto.h>
> #include <openssl\evp.h>
> #include <openssl\err.h>
> #include <openssl\conf.h>
> #include <openssl\obj_mac.h>
> 
> void PrintData(uint8_t* data, uint32_t len)
> {
> 	for (uint32_t i = 0; i < len; i++)
> 	{
> 		printf("%02X ", data[i]);
> 		if ((i % 16) == 15 && (i != (len - 1)))
> 		{
> 			puts("");
> 		}
> 	}
> 	puts("");
> }
> 
> void test_enc_dec_sm2()
> {
> 	//EC_GROUP *sm2p256v1 = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
> 	EC_KEY *sm2key = NULL;
> 	int type = NID_sm3;
> 	uint8_t inBuf[200] = { "123456789aaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccccccccddddddddddddddddddddeeeeeeeeeeeeeeeeeeefffffffffffffffffffff123456789" };
> 	uint8_t outBuf[200] = { 0 };
> 	uint8_t tmpBuf[200] = { 0 };
> 	size_t inLen = 50;
> 	size_t outLen = 0;
> 	size_t tmpLen = 0;
> 	int ret = 0;
> 
> 
> 	puts("PlainText:"); PrintData(inBuf, inLen); puts("");
> 
> 	// Get sm2 key
> 	sm2key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
> 	ret = EC_KEY_generate_key(sm2key);
> 	if (ret != 1)
> 	{
> 		puts("EC_KEY_generate_key failed!");
> 		return;
> 	}
> 
> 	// Encrypt
> 	ret = SM2_encrypt(type, inBuf, inLen, outBuf, &outLen, sm2key);
> 	if (ret != 1)
> 	{
> 		printf("SM2_encrypt failed! [0x%08X]\n", ERR_get_error());
> 		ERR_print_errors_fp(stderr);
> 		return;
> 	}
> 	else
> 	{
> 		puts("Encrypt success!");
> 		puts("CipherText:"); PrintData(outBuf, outLen); puts("");
> 	}
> 
> 	// Get output length
> 	tmpLen = 0;
> 	ret = SM2_decrypt(type, outBuf, outLen, NULL, &tmpLen, sm2key);
> 	if (ret != 1)
> 	{
> 		puts("SM2_decrypt failed on get output-length!");
> 		return;
> 	}
> 
> 	// Decrypt
> 	ret = SM2_decrypt(type, outBuf, outLen, tmpBuf, &tmpLen, sm2key);
> 	if (ret != 1 && inLen != tmpLen && 0 != CRYPTO_memcmp(tmpBuf, inBuf, tmpLen))
> 	{
> 		puts("SM2_decrypt failed!");
> 		return;
> 	}
> 	else
> 	{
> 		puts("Decrypt success!");
> 		puts("DecryptedText:"); PrintData(tmpBuf, tmpLen); puts((char*)tmpBuf); puts("");
> 	}
> }
> 
> int main()
> {
> 	test_enc_dec_sm2();
> 	return 0;
> }
> ```
> 输出结果为：
> 
> ```
> PlainText:
> 31 32 33 34 35 36 37 38 39 61 61 61 61 61 61 61
> 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 62
> 62 62 62 62 63 63 63 63 63 63 63 63 63 63 63 63
> 63 63
> 
> Encrypt success!
> CipherText:
> 30 81 9C 02 21 00 F8 78 13 F5 E8 82 69 17 9C 7F
> A2 F5 70 9A 14 46 87 11 F0 A7 9F 1A 1B 99 15 72
> A6 F2 7A 97 D9 65 02 21 00 84 04 51 D6 7B 9B 8C
> 2D F5 6B 67 27 33 98 C5 11 3B EB C2 2D D0 7F 41
> 11 D5 2F 8C F8 43 71 26 D7 04 20 CA 19 60 D3 1D
> 6A 81 F1 7F E3 34 9C 55 65 AF 8C B2 FC F6 14 83
> A2 D6 B4 F7 69 21 18 26 4F 6D 97 04 32 BC 84 56
> 3B 0A 05 48 DA 2D 5A 5C 27 34 A8 0E E6 59 05 26
> 46 A9 F7 C1 2E 6C 0E F0 3D 2A 54 C4 C4 3F FB 24
> 1A 69 68 1A 92 7E AD 0D 56 87 25 C1 6D 24 35
> 
> Decrypt success!
> DecryptedText:
> 31 32 33 34 35 36 37 38 39 61 61 61 61 61 61 61
> 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 62
> 62 62 62 62 63 63 63 63 63 63 63 63 63 63 63 63
> 63 63
> 123456789aaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccc
> ```

你好，我使用你同样的源代码加密也没有返回数据，加密失败

**Comment by YWTL** [comment]
你好，我使用同样的代码加密无返回结果，加密失败
![image](https://user-images.githubusercontent.com/45708366/54924030-66a67200-4f46-11e9-9956-caa77068787d.png)

**Comment by gthanwu** [comment]
你好，我用你的代码出现SM2_encrypt failed! [0x42067064]的错误，你知道是因为什么吗，可以发一份你编译好的库给我吗1901821458@qq.com，谢谢

**Comment by gthanwu** [comment]
> 我使用如下代码加密解密都成功。
> #include <stdio.h>
> #include <time.h>
> #include <openssl\sms4.h>
> #include <openssl\sm3.h>
> #include <openssl\sm2.h>
> #include <openssl\ec.h>
> #include <openssl\crypto.h>
> #include <openssl\evp.h>
> #include <openssl\err.h>
> #include <openssl\conf.h>
> #include <openssl\obj_mac.h>
> 
> void PrintData(uint8_t* data, uint32_t len)
> {
> 	for (uint32_t i = 0; i < len; i++)
> 	{
> 		printf("%02X ", data[i]);
> 		if ((i % 16) == 15 && (i != (len - 1)))
> 		{
> 			puts("");
> 		}
> 	}
> 	puts("");
> }
> 
> void test_enc_dec_sm2()
> {
> 	//EC_GROUP *sm2p256v1 = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
> 	EC_KEY *sm2key = NULL;
> 	int type = NID_sm3;
> 	uint8_t inBuf[200] = { "123456789aaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccccccccddddddddddddddddddddeeeeeeeeeeeeeeeeeeefffffffffffffffffffff123456789" };
> 	uint8_t outBuf[200] = { 0 };
> 	uint8_t tmpBuf[200] = { 0 };
> 	size_t inLen = 50;
> 	size_t outLen = 0;
> 	size_t tmpLen = 0;
> 	int ret = 0;
> 
> 
> 	puts("PlainText:"); PrintData(inBuf, inLen); puts("");
> 
> 	// Get sm2 key
> 	sm2key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
> 	ret = EC_KEY_generate_key(sm2key);
> 	if (ret != 1)
> 	{
> 		puts("EC_KEY_generate_key failed!");
> 		return;
> 	}
> 
> 	// Encrypt
> 	ret = SM2_encrypt(type, inBuf, inLen, outBuf, &outLen, sm2key);
> 	if (ret != 1)
> 	{
> 		printf("SM2_encrypt failed! [0x%08X]\n", ERR_get_error());
> 		ERR_print_errors_fp(stderr);
> 		return;
> 	}
> 	else
> 	{
> 		puts("Encrypt success!");
> 		puts("CipherText:"); PrintData(outBuf, outLen); puts("");
> 	}
> 
> 	// Get output length
> 	tmpLen = 0;
> 	ret = SM2_decrypt(type, outBuf, outLen, NULL, &tmpLen, sm2key);
> 	if (ret != 1)
> 	{
> 		puts("SM2_decrypt failed on get output-length!");
> 		return;
> 	}
> 
> 	// Decrypt
> 	ret = SM2_decrypt(type, outBuf, outLen, tmpBuf, &tmpLen, sm2key);
> 	if (ret != 1 && inLen != tmpLen && 0 != CRYPTO_memcmp(tmpBuf, inBuf, tmpLen))
> 	{
> 		puts("SM2_decrypt failed!");
> 		return;
> 	}
> 	else
> 	{
> 		puts("Decrypt success!");
> 		puts("DecryptedText:"); PrintData(tmpBuf, tmpLen); puts((char*)tmpBuf); puts("");
> 	}
> }
> 
> int main()
> {
> 	test_enc_dec_sm2();
> 	return 0;
> }
> 
> 输出结果为：
> PlainText:
> 31 32 33 34 35 36 37 38 39 61 61 61 61 61 61 61
> 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 62
> 62 62 62 62 63 63 63 63 63 63 63 63 63 63 63 63
> 63 63
> 
> Encrypt success!
> CipherText:
> 30 81 9C 02 21 00 F8 78 13 F5 E8 82 69 17 9C 7F
> A2 F5 70 9A 14 46 87 11 F0 A7 9F 1A 1B 99 15 72
> A6 F2 7A 97 D9 65 02 21 00 84 04 51 D6 7B 9B 8C
> 2D F5 6B 67 27 33 98 C5 11 3B EB C2 2D D0 7F 41
> 11 D5 2F 8C F8 43 71 26 D7 04 20 CA 19 60 D3 1D
> 6A 81 F1 7F E3 34 9C 55 65 AF 8C B2 FC F6 14 83
> A2 D6 B4 F7 69 21 18 26 4F 6D 97 04 32 BC 84 56
> 3B 0A 05 48 DA 2D 5A 5C 27 34 A8 0E E6 59 05 26
> 46 A9 F7 C1 2E 6C 0E F0 3D 2A 54 C4 C4 3F FB 24
> 1A 69 68 1A 92 7E AD 0D 56 87 25 C1 6D 24 35
> 
> Decrypt success!
> DecryptedText:
> 31 32 33 34 35 36 37 38 39 61 61 61 61 61 61 61
> 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 62
> 62 62 62 62 63 63 63 63 63 63 63 63 63 63 63 63
> 63 63
> 123456789aaaaaaaaabbbbbbbbbbbbbbbbbbcccccccccccccc

你好，我用你的代码出现SM2_encrypt failed! [0x42067064]的错误，你知道是因为什么吗，可以发一份你编译好的库给我吗1901821458@qq.com，谢谢
