### ISSUE TITLE
tomcat中的tcnative这个动态库使用gmssl编译有没有遇到不能访问类似问题的老哥

### ISSUE THREAD

**Issue by LoadLife** [guanzhi/GmSSL#646]
在tomcat的tcnative库的编译时指定了gmssl，同时使用gmssl生成了一个服务器端的证书，在开启tomcat后使用国密版360浏览器无法访问，使用Chrome返回的错误为
ERR_SSL_VERSION_OR_CIPHER_MISMATCH，现在卡在这里不知道该怎么办了

**Comment by guanzhi** [comment]
建议使用本项目 Code/Release 中提供的Mac版国密浏览器先行测试，这个浏览器可以和GmSSL服务端建立连接并通信的。

**Comment by springxu0800** [comment]
tcnative库有GMSSL的版本？能开源吗？

**Comment by LoadLife** [comment]
> tcnative库有GMSSL的版本？能开源吗？
只是自己编译tcnative时候选择了gmssl替代openssl，内部代码没有动过，所以能否使用我不知道

**Comment by springxu0800** [comment]
那您提的这问题就是出在了"TLS_ECDHE_SM2_WITH_SMS4_SM3" 这种套件没有从TOMCAT向gmssl中设置了。

**Comment by LoadLife** [comment]
> 那您提的这问题就是出在了"TLS_ECDHE_SM2_WITH_SMS4_SM3" 这种套件没有从TOMCAT向gmssl中设置了。

是的，所以为了能使tomcat支持gmssl国密套件我觉得tomcat本身以及tcnative都需要修改，这两个东西我都不太了解，有些无从下手

**Comment by springxu0800** [comment]
我和您遇到了同样的问题了。 还请关老师指教了。 如何让netty在GMSSL上实现TLS_ECDHE_SM2_WITH_SMS4_SM3这个参数设置?

**Comment by guanzhi** [comment]
我们给一个国产的应用服务器做过国密升级，这个应用服务器是在JBoss上开发的，其中通过一个JBoss修改后的tcnative链接老版本OpenSSL。这里我们主要做的是把tcnative的C代码修改兼容OpenSSL-1.1 API，把证书的配置、SSL套件设置为国密版本，并且加入了国产密码机的支持。这里面主要的工作量来自于系统配置。

**Comment by fuzzmaker** [comment]
> 我们给一个国产的应用服务器做过国密升级，这个应用服务器是在JBoss上开发的，其中通过一个JBoss修改后的tcnative链接老版本OpenSSL。这里我们主要做的是把tcnative的C代码修改兼容OpenSSL-1.1 API，把证书的配置、SSL套件设置为国密版本，并且加入了国产密码机的支持。这里面主要的工作量来自于系统配置。

请问现在netty支持gmssl

> 我和您遇到了同样的问题了。 还请关老师指教了。 如何让netty在GMSSL上实现TLS_ECDHE_SM2_WITH_SMS4_SM3这个参数设置?

请问这个问题你解决了么？能否分享一下呢，我也遇到同样问题

**Comment by whitezdm** [comment]
> 

同问，要命呀
