### ISSUE TITLE
关于把加密卡中的加密函数（SM2、SM3、SM4）到GMSSL底层的网络通信中的疑惑？

### ISSUE THREAD

**Issue by lisongopg** [guanzhi/GmSSL#648]
老师好！我们在做基于GMSSL网络安全隧道的加密通讯，基于GMSSL软加密通讯已经实现；目前卡在基于GMSSL及硬件加密接口（计划在GMSSL的底层握手及读写数据中用到加密算法调用硬件加密接口），请老师指教，万分谢谢！

**Comment by zhenyuwei** [comment]
可以看一下openssl engine方式，可以满足你的需求。
