### ISSUE TITLE
GMSSLv1协议

### ISSUE THREAD

**Issue by mafei6868** [guanzhi/GmSSL#65]
你好，请问现在GMSSLv1协议开发完成可以用了吗？

**Comment by guanzhi** [comment]
TLS协议可能可以使用国密的套件，但是我还没有测试过。至于GM/T 0024定义的SSL VPN协议(version 1.1)则还没有实现。目前的GmSSL 1.x版本主要是提供SM2/3/4的基本实现及基于EVP接口的调用，其他功能不在该版本的预订功能之内，即使有部分的代码。GmSSL目前开发中的2.0版本会支持国密算法套件的TLS 1.1/1.2通信，但不会支持GM/T 0024的国密协议。

**Comment by LiTianjue** [comment]
使用TLS1.1/1.2协议，使用国密算法套件是可行的
https://github.com/guanzhi/GmSSL/commit/5c315bca3f08e706e6a81a133575cda315012e4d

**Comment by junfx** [comment]
@guanzhi 关于sm2密钥交换, 我看了sm2_kap.c这个文件, 似乎在这里实现, 但是那几个函数除了在sm2test.c中调用外, GmSSL中其它地方似乎没用到. ECDH_compute_key等也没有被修改.
所以请教一下, sm2的密钥交换在哪里实现, 哪里被调用.
