### ISSUE TITLE
SM2生成的16进制的公钥字符串转PEM证书格式问题

### ISSUE THREAD

**Issue by ycathi** [guanzhi/GmSSL#651]
`    public static String generateKeyPair(){  
        SM2 sm2 = SM2.Instance();  
        AsymmetricCipherKeyPair key = sm2.ecc_key_pair_generator.generateKeyPair();  
        ECPrivateKeyParameters ecpriv = (ECPrivateKeyParameters) key.getPrivate();  
        ECPublicKeyParameters ecpub = (ECPublicKeyParameters) key.getPublic();  
        BigInteger privateKey = ecpriv.getD();  
        ECPoint publicKey = ecpub.getQ();  
        System.out.println("公钥: " + Util.byteToHex(publicKey.getEncoded())+"\n私钥: " + Util.byteToHex(privateKey.toByteArray()));
          return "公钥: " + Util.byteToHex(publicKey.getEncoded())+"私钥: " + Util.byteToHex(privateKey.toByteArray());
    } `
![_20181222201407](https://user-images.githubusercontent.com/38828027/50374261-363cf800-0626-11e9-92bc-4bc7a4c7d3f0.png)

java通过以上代码生成的SM2 16进制的公钥字符串，怎么转成PHP这边需要的PEM格式的公钥证书。

真诚请教，请各位老师指教，谢谢。

**Comment by guanzhi** [comment]
可以通过`gmssl pkey`命令DER和PEM格式之间进行转换

**Comment by ycathi** [comment]
@guanzhi 谢谢老师，我还有个问题，如您方便，请为我解惑。

我研究DER证书，希望知道在只有pub 公钥字符串 的时候，怎么构造GMSSL能识别的DER证书，因为我最终想到处PEM格式的证书。
![_20181227130414](https://user-images.githubusercontent.com/38828027/50466352-f4ba9d00-09d7-11e9-9487-4cc1e2fed71f.png)

目前只知道： `0406108493459880a569c42d65079b36d25a9f4d7923e96e44d741047fa9a60db4cd596a89c3ef0ee9f468824259851bcfacc318c3861e6ea38ac8f54fe0f8f1bd`

我尝试分析了，GMSSL导出的DER格式的证书，使用PHP读取文件并`unpack('H*', 文件内容)`之后，获得如下结果：
`3059301306072a8648ce3d020106082a811ccf5501822d0342000406108493459880a569c42d65079b36d25a9f4d7923e96e44d741047fa9a60db4cd596a89c3ef0ee9f468824259851bcfacc318c3861e6ea38ac8f54fe0f8f1bd`

前面的这串字符，我不知道在哪里来的，老师可否指导如何构造这部分，万分感谢。
`3059301306072a8648ce3d020106082a811ccf5501822d034200`

**Comment by ycathi** [comment]
@guanzhi  老师我成功了。我直接把`3059301306072a8648ce3d020106082a811ccf5501822d034200`拼接到16进制的公钥前面，然后打包`pack('H*', 拼接后字符)`，保存成为文件后，GMSSL就可以识别了。再次感谢。

**Comment by Steeeeeven** [comment]
老师你好- -  我想问一下已知32位sm2私钥  怎么生成pem那个121字节的私钥呀   同样用的gmssl
