### ISSUE TITLE
我只需要国密SM2/SM3/SM4算法，我编译哪部分代码就行

### ISSUE THREAD

**Issue by liangruxing** [guanzhi/GmSSL#652]

**Comment by guanzhi** [comment]
SM3/SM4代码大体上可以单独编译，SM2还依赖大整数和椭圆曲线
建议你在配置时关闭不需要的模块，如 `./config no-rsa no-dsa no-dh ....`

**Comment by liangruxing** [comment]
> SM3/SM4代码大体上可以单独编译，SM2还依赖大整数和椭圆曲线
> 建议你在配置时关闭不需要的模块，如 `./config no-rsa no-dsa no-dh ....`

好的，谢谢
