### ISSUE TITLE
在linux 下执行go run gmssltest.go 提示如下问题

### ISSUE THREAD

**Issue by Wdiviner** [guanzhi/GmSSL#654]
**在linux 下执行go run gmssltest.go 提示如下问题：**

/tmp/go-build516647647/b026/_x002.o：在函数‘_BIO_get_mem_data’中：
gmssl/build.go:60：对‘BIO_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x002.o：在函数‘_OPENSSL_free’中：
gmssl/build.go:64：对‘CRYPTO_free’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_ASN1_INTEGER_to_BN’中：
/tmp/go-build/cgo-gcc-prolog:44：对‘ASN1_INTEGER_to_BN’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_free’中：
/tmp/go-build/cgo-gcc-prolog:63：对‘BIO_free’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_new’中：
/tmp/go-build/cgo-gcc-prolog:81：对‘BIO_new’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_new_mem_buf’中：
/tmp/go-build/cgo-gcc-prolog:101：对‘BIO_new_mem_buf’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_s_mem’中：
/tmp/go-build/cgo-gcc-prolog:118：对‘BIO_s_mem’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BN_bn2hex’中：
/tmp/go-build/cgo-gcc-prolog:136：对‘BN_bn2hex’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_PEM_read_bio_X509’中：
/tmp/go-build/cgo-gcc-prolog:181：对‘PEM_read_bio_X509’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_NAME_oneline’中：
/tmp/go-build/cgo-gcc-prolog:202：对‘X509_NAME_oneline’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_check_private_key’中：
/tmp/go-build/cgo-gcc-prolog:222：对‘X509_check_private_key’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_get0_serialNumber’中：
/tmp/go-build/cgo-gcc-prolog:252：对‘X509_get0_serialNumber’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_get_issuer_name’中：
/tmp/go-build/cgo-gcc-prolog:270：对‘X509_get_issuer_name’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_get_pubkey’中：
/tmp/go-build/cgo-gcc-prolog:288：对‘X509_get_pubkey’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_get_subject_name’中：
/tmp/go-build/cgo-gcc-prolog:306：对‘X509_get_subject_name’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_print’中：
/tmp/go-build/cgo-gcc-prolog:326：对‘X509_print’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_BN_free’中：
/tmp/go-build/cgo-gcc-prolog:151：对‘BN_free’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_free’中：
/tmp/go-build/cgo-gcc-prolog:163：对‘EVP_PKEY_free’未定义的引用
/tmp/go-build516647647/b026/_x003.o：在函数‘_cgo_5dddde98d76a_Cfunc_X509_free’中：
/tmp/go-build/cgo-gcc-prolog:237：对‘X509_free’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘cb_cipher_names’中：
gmssl/cipher.go:70：对‘EVP_CIPHER_nid’未定义的引用
gmssl/cipher.go:70：对‘OBJ_nid2sn’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘cb_cipher_names_len’中：
gmssl/cipher.go:60：对‘EVP_CIPHER_nid’未定义的引用
gmssl/cipher.go:60：对‘OBJ_nid2sn’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_CTX_block_size’中：
/tmp/go-build/cgo-gcc-prolog:44：对‘EVP_CIPHER_CTX_block_size’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_CTX_new’中：
/tmp/go-build/cgo-gcc-prolog:73：对‘EVP_CIPHER_CTX_new’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_block_size’中：
/tmp/go-build/cgo-gcc-prolog:92：对‘EVP_CIPHER_block_size’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_iv_length’中：
/tmp/go-build/cgo-gcc-prolog:111：对‘EVP_CIPHER_iv_length’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_key_length’中：
/tmp/go-build/cgo-gcc-prolog:130：对‘EVP_CIPHER_key_length’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CipherFinal’中：
/tmp/go-build/cgo-gcc-prolog:151：对‘EVP_CipherFinal’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CipherInit’中：
/tmp/go-build/cgo-gcc-prolog:175：对‘EVP_CipherInit’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CipherUpdate’中：
/tmp/go-build/cgo-gcc-prolog:199：对‘EVP_CipherUpdate’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_get_cipherbyname’中：
/tmp/go-build/cgo-gcc-prolog:217：对‘EVP_get_cipherbyname’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘get_cipher_names’中：
gmssl/cipher.go:77：对‘EVP_CIPHER_do_all_sorted’未定义的引用
gmssl/cipher.go:78：对‘CRYPTO_zalloc’未定义的引用
gmssl/cipher.go:81：对‘EVP_CIPHER_do_all_sorted’未定义的引用
/tmp/go-build516647647/b026/_x004.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_CIPHER_CTX_free’中：
/tmp/go-build/cgo-gcc-prolog:59：对‘EVP_CIPHER_CTX_free’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘cb_digest_names’中：
gmssl/digest.go:73：对‘EVP_MD_type’未定义的引用
gmssl/digest.go:73：对‘OBJ_nid2sn’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘cb_digest_names_len’中：
gmssl/digest.go:63：对‘EVP_MD_type’未定义的引用
gmssl/digest.go:63：对‘OBJ_nid2sn’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_DigestFinal_ex’中：
/tmp/go-build/cgo-gcc-prolog:46：对‘EVP_DigestFinal_ex’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_DigestInit_ex’中：
/tmp/go-build/cgo-gcc-prolog:67：对‘EVP_DigestInit_ex’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_DigestUpdate’中：
/tmp/go-build/cgo-gcc-prolog:88：对‘EVP_DigestUpdate’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_MD_CTX_md’中：
/tmp/go-build/cgo-gcc-prolog:118：对‘EVP_MD_CTX_md’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_MD_CTX_new’中：
/tmp/go-build/cgo-gcc-prolog:135：对‘EVP_MD_CTX_new’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_MD_block_size’中：
/tmp/go-build/cgo-gcc-prolog:154：对‘EVP_MD_block_size’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_MD_size’中：
/tmp/go-build/cgo-gcc-prolog:173：对‘EVP_MD_size’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_get_digestbyname’中：
/tmp/go-build/cgo-gcc-prolog:191：对‘EVP_get_digestbyname’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘get_digest_names’中：
gmssl/digest.go:80：对‘EVP_MD_do_all_sorted’未定义的引用
gmssl/digest.go:81：对‘CRYPTO_zalloc’未定义的引用
gmssl/digest.go:84：对‘EVP_MD_do_all_sorted’未定义的引用
/tmp/go-build516647647/b026/_x005.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_MD_CTX_free’中：
/tmp/go-build/cgo-gcc-prolog:103：对‘EVP_MD_CTX_free’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_by_id’中：
/tmp/go-build/cgo-gcc-prolog:43：对‘ENGINE_by_id’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_ctrl_cmd_string’中：
/tmp/go-build/cgo-gcc-prolog:66：对‘ENGINE_ctrl_cmd_string’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_finish’中：
/tmp/go-build/cgo-gcc-prolog:85：对‘ENGINE_finish’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_free’中：
/tmp/go-build/cgo-gcc-prolog:104：对‘ENGINE_free’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_get_first’中：
/tmp/go-build/cgo-gcc-prolog:121：对‘ENGINE_get_first’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_get_id’中：
/tmp/go-build/cgo-gcc-prolog:139：对‘ENGINE_get_id’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_get_next’中：
/tmp/go-build/cgo-gcc-prolog:157：对‘ENGINE_get_next’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_init’中：
/tmp/go-build/cgo-gcc-prolog:176：对‘ENGINE_init’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_load_private_key’中：
/tmp/go-build/cgo-gcc-prolog:209：对‘ENGINE_load_private_key’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_load_public_key’中：
/tmp/go-build/cgo-gcc-prolog:230：对‘ENGINE_load_public_key’未定义的引用
/tmp/go-build516647647/b026/_x006.o：在函数‘_cgo_5dddde98d76a_Cfunc_ENGINE_load_builtin_engines’中：
/tmp/go-build/cgo-gcc-prolog:191：对‘ENGINE_load_builtin_engines’未定义的引用
/tmp/go-build516647647/b026/_x007.o：在函数‘_cgo_5dddde98d76a_Cfunc_ERR_print_errors’中：
/tmp/go-build/cgo-gcc-prolog:40：对‘ERR_print_errors’未定义的引用
/tmp/go-build516647647/b026/_x008.o：在函数‘_cgo_5dddde98d76a_Cfunc_HMAC_CTX_new’中：
/tmp/go-build/cgo-gcc-prolog:54：对‘HMAC_CTX_new’未定义的引用
/tmp/go-build516647647/b026/_x008.o：在函数‘_cgo_5dddde98d76a_Cfunc_HMAC_Final’中：
/tmp/go-build/cgo-gcc-prolog:75：对‘HMAC_Final’未定义的引用
/tmp/go-build516647647/b026/_x008.o：在函数‘_cgo_5dddde98d76a_Cfunc_HMAC_Init_ex’中：
/tmp/go-build/cgo-gcc-prolog:99：对‘HMAC_Init_ex’未定义的引用
/tmp/go-build516647647/b026/_x008.o：在函数‘_cgo_5dddde98d76a_Cfunc_HMAC_Update’中：
/tmp/go-build/cgo-gcc-prolog:120：对‘HMAC_Update’未定义的引用
/tmp/go-build516647647/b026/_x008.o：在函数‘_cgo_5dddde98d76a_Cfunc_HMAC_CTX_free’中：
/tmp/go-build/cgo-gcc-prolog:40：对‘HMAC_CTX_free’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘get_pke_info’中：
gmssl/pkey.go:225：对‘OBJ_txt2nid’未定义的引用
gmssl/pkey.go:250：对‘OBJ_txt2nid’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘new_pkey_keygen_ctx’中：
gmssl/pkey.go:75：对‘EVP_PKEY_asn1_find_str’未定义的引用
gmssl/pkey.go:78：对‘EVP_PKEY_asn1_get0_info’未定义的引用
gmssl/pkey.go:79：对‘ENGINE_finish’未定义的引用
gmssl/pkey.go:80：对‘EVP_PKEY_CTX_new_id’未定义的引用
gmssl/pkey.go:86：对‘EVP_PKEY_CTX_free’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘pem_write_bio_privatekey’中：
gmssl/pkey.go:100：对‘PEM_write_bio_PrivateKey’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘pk_encrypt’中：
gmssl/pkey.go:411：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:414：对‘EVP_PKEY_CTX_new’未定义的引用
gmssl/pkey.go:417：对‘EVP_PKEY_encrypt_init’未定义的引用
gmssl/pkey.go:420：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:427：对‘EVP_PKEY_encrypt’未定义的引用
gmssl/pkey.go:430：对‘CRYPTO_zalloc’未定义的引用
gmssl/pkey.go:433：对‘EVP_PKEY_encrypt’未定义的引用
gmssl/pkey.go:421：对‘EVP_PKEY_get0_EC_KEY’未定义的引用
gmssl/pkey.go:420：对‘EC_KEY_get0_group’未定义的引用
gmssl/pkey.go:420：对‘EC_GROUP_get_curve_name’未定义的引用
gmssl/pkey.go:422：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:423：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:440：对‘EVP_PKEY_CTX_free’未定义的引用
gmssl/pkey.go:441：对‘CRYPTO_free’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘sk_decrypt’中：
gmssl/pkey.go:455：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:458：对‘EVP_PKEY_CTX_new’未定义的引用
gmssl/pkey.go:461：对‘EVP_PKEY_decrypt_init’未定义的引用
gmssl/pkey.go:464：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:471：对‘EVP_PKEY_decrypt’未定义的引用
gmssl/pkey.go:474：对‘CRYPTO_zalloc’未定义的引用
gmssl/pkey.go:477：对‘EVP_PKEY_decrypt’未定义的引用
gmssl/pkey.go:465：对‘EVP_PKEY_get0_EC_KEY’未定义的引用
gmssl/pkey.go:464：对‘EC_KEY_get0_group’未定义的引用
gmssl/pkey.go:464：对‘EC_GROUP_get_curve_name’未定义的引用
gmssl/pkey.go:466：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:467：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:483：对‘EVP_PKEY_CTX_free’未定义的引用
gmssl/pkey.go:484：对‘CRYPTO_free’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘sk_sign’中：
gmssl/pkey.go:494：对‘EVP_PKEY_CTX_new’未定义的引用
gmssl/pkey.go:497：对‘EVP_PKEY_sign_init’未定义的引用
gmssl/pkey.go:500：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:506：对‘EVP_PKEY_size’未定义的引用
gmssl/pkey.go:509：对‘EVP_PKEY_size’未定义的引用
gmssl/pkey.go:509：对‘CRYPTO_zalloc’未定义的引用
gmssl/pkey.go:512：对‘EVP_PKEY_size’未定义的引用
gmssl/pkey.go:513：对‘EVP_PKEY_sign’未定义的引用
gmssl/pkey.go:501：对‘EVP_PKEY_get0_EC_KEY’未定义的引用
gmssl/pkey.go:500：对‘EC_KEY_get0_group’未定义的引用
gmssl/pkey.go:500：对‘EC_GROUP_get_curve_name’未定义的引用
gmssl/pkey.go:502：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:519：对‘EVP_PKEY_CTX_free’未定义的引用
gmssl/pkey.go:520：对‘CRYPTO_free’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘pk_verify’中：
gmssl/pkey.go:529：对‘EVP_PKEY_CTX_new’未定义的引用
gmssl/pkey.go:533：对‘EVP_PKEY_verify_init’未定义的引用
gmssl/pkey.go:538：对‘EVP_PKEY_id’未定义的引用
gmssl/pkey.go:544：对‘EVP_PKEY_verify’未定义的引用
gmssl/pkey.go:550：对‘EVP_PKEY_CTX_free’未定义的引用
gmssl/pkey.go:539：对‘EVP_PKEY_get0_EC_KEY’未定义的引用
gmssl/pkey.go:538：对‘EC_KEY_get0_group’未定义的引用
gmssl/pkey.go:538：对‘EC_GROUP_get_curve_name’未定义的引用
gmssl/pkey.go:540：对‘EVP_PKEY_CTX_ctrl’未定义的引用
gmssl/pkey.go:546：对‘ERR_print_errors_fp’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_CTX_ctrl_str’中：
/tmp/go-build/cgo-gcc-prolog:58：对‘EVP_PKEY_CTX_ctrl_str’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_get0_EC_KEY’中：
/tmp/go-build/cgo-gcc-prolog:76：对‘EVP_PKEY_get0_EC_KEY’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_id’中：
/tmp/go-build/cgo-gcc-prolog:95：对‘EVP_PKEY_id’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_keygen’中：
/tmp/go-build/cgo-gcc-prolog:115：对‘EVP_PKEY_keygen’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_keygen_init’中：
/tmp/go-build/cgo-gcc-prolog:134：对‘EVP_PKEY_keygen_init’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_paramgen’中：
/tmp/go-build/cgo-gcc-prolog:154：对‘EVP_PKEY_paramgen’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_paramgen_init’中：
/tmp/go-build/cgo-gcc-prolog:173：对‘EVP_PKEY_paramgen_init’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_print_private’中：
/tmp/go-build/cgo-gcc-prolog:196：对‘EVP_PKEY_print_private’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_PKEY_print_public’中：
/tmp/go-build/cgo-gcc-prolog:219：对‘EVP_PKEY_print_public’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_des_ede3_cbc’中：
/tmp/go-build/cgo-gcc-prolog:236：对‘EVP_des_ede3_cbc’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_EVP_sm3’中：
/tmp/go-build/cgo-gcc-prolog:253：对‘EVP_sm3’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_PEM_read_bio_PrivateKey’中：
/tmp/go-build/cgo-gcc-prolog:274：对‘PEM_read_bio_PrivateKey’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_PEM_write_bio_PrivateKey’中：
/tmp/go-build/cgo-gcc-prolog:300：对‘PEM_write_bio_PrivateKey’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_SM2_compute_id_digest’中：
/tmp/go-build/cgo-gcc-prolog:324：对‘SM2_compute_id_digest’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘pem_read_bio_pubkey’中：
gmssl/pkey.go:91：对‘PEM_read_bio_PUBKEY’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘pem_write_bio_pubkey’中：
gmssl/pkey.go:95：对‘PEM_write_bio_PUBKEY’未定义的引用
/tmp/go-build516647647/b026/_x009.o：在函数‘_cgo_5dddde98d76a_Cfunc_ERR_print_errors_fp’中：
/tmp/go-build/cgo-gcc-prolog:40：对‘ERR_print_errors_fp’未定义的引用
/tmp/go-build516647647/b026/_x010.o：在函数‘_cgo_5dddde98d76a_Cfunc_RAND_bytes’中：
/tmp/go-build/cgo-gcc-prolog:46：对‘RAND_bytes’未定义的引用
/tmp/go-build516647647/b026/_x010.o：在函数‘_cgo_5dddde98d76a_Cfunc_RAND_seed’中：
/tmp/go-build/cgo-gcc-prolog:63：对‘RAND_seed’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_new_ssl_connect’中：
/tmp/go-build/cgo-gcc-prolog:43：对‘BIO_new_ssl_connect’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_read’中：
/tmp/go-build/cgo-gcc-prolog:65：对‘BIO_read’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_BIO_write’中：
/tmp/go-build/cgo-gcc-prolog:87：对‘BIO_write’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_load_verify_locations’中：
/tmp/go-build/cgo-gcc-prolog:120：对‘SSL_CTX_load_verify_locations’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_new’中：
/tmp/go-build/cgo-gcc-prolog:138：对‘SSL_CTX_new’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_set_options’中：
/tmp/go-build/cgo-gcc-prolog:157：对‘SSL_CTX_set_options’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_get_peer_certificate’中：
/tmp/go-build/cgo-gcc-prolog:204：对‘SSL_get_peer_certificate’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_get_verify_result’中：
/tmp/go-build/cgo-gcc-prolog:222：对‘SSL_get_verify_result’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_set_cipher_list’中：
/tmp/go-build/cgo-gcc-prolog:242：对‘SSL_set_cipher_list’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_TLS_client_method’中：
/tmp/go-build/cgo-gcc-prolog:259：对‘TLS_client_method’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_BIO_do_connect’中：
gmssl/ssl.go:61：对‘BIO_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_BIO_get_ssl’中：
gmssl/ssl.go:65：对‘BIO_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_BIO_set_conn_hostname’中：
gmssl/ssl.go:69：对‘BIO_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_SSL_CTX_set_max_proto_version’中：
gmssl/ssl.go:77：对‘SSL_CTX_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_SSL_CTX_set_min_proto_version’中：
gmssl/ssl.go:73：对‘SSL_CTX_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_SSL_set_tlsext_host_name’中：
gmssl/ssl.go:81：对‘SSL_ctrl’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_free’中：
/tmp/go-build/cgo-gcc-prolog:102：对‘SSL_CTX_free’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_set_verify’中：
/tmp/go-build/cgo-gcc-prolog:175：对‘SSL_CTX_set_verify’未定义的引用
/tmp/go-build516647647/b026/_x011.o：在函数‘_cgo_5dddde98d76a_Cfunc_SSL_CTX_set_verify_depth’中：
/tmp/go-build/cgo-gcc-prolog:189：对‘SSL_CTX_set_verify_depth’未定义的引用
/tmp/go-build516647647/b026/_x012.o：在函数‘_cgo_5dddde98d76a_Cfunc_OpenSSL_version’中：
/tmp/go-build/cgo-gcc-prolog:44：对‘OpenSSL_version’未定义的引用

**Comment by duxin40** [comment]
请问这个问题解决了么，我也遇到了
