### ISSUE TITLE
实现国密的https一定要使用双证书吗？

### ISSUE THREAD

**Issue by LoadLife** [guanzhi/GmSSL#655]
实现国密的https，一定需要两张证书吗？都是sm2证书还是怎么样，我在tomcat中遇到的错误实在不知道怎么解决了

**Comment by zhenyuwei** [comment]
国标里面有详细的说明，客户端或服务端发送证书时，需要使用双证书。但ECC-*这个套件比较特殊，客户端可以不发送证书。

**Comment by LoadLife** [comment]
> 国标里面有详细的说明，客户端或服务端发送证书时，需要使用双证书。但ECC-*这个套件比较特殊，客户端可以不发送证书。
我直接生成的sm2证书，加密套件可以直接指定ecc-sm4-sm3吗

**Comment by zhenyuwei** [comment]
可以啊，客户端有个设置加密套件的接口SSL_CTX_set_cipher_list，设置成你想用的密码套件就可以了。

**Comment by LoadLife** [comment]
> gmssl里面定义的sm2-*代表着ecc套件，sm2dh-*代表ecdh的套件，这个套件名称没有影响吧，openssl里面是根据定义的e001来匹配算法的，这个国标里面有定义每个算法的标志。或者你留联系方式，我加你吧

谢谢您，我的QQ是932166299，麻烦您指导啦

**Comment by yunlai** [comment]
双证书是指Server发给Client密钥 证书、签名证书，两个证书，而不是双向认证的意思
关老师提倡在这里交流，方便大家学习研究，在这里讨论吧

**Comment by yunlai** [comment]
应该是和rsa类似，我也是才学习，还没调通，卡到搞不清finish的80字节怎么生成的这里了
