### ISSUE TITLE
我只需要SM4的部分，请问可以单独编译吗？

### ISSUE THREAD

**Issue by jnxxhzz** [guanzhi/GmSSL#656]
![image](https://user-images.githubusercontent.com/33682882/50502140-f2b81300-0a97-11e9-80e7-e647295feb6d.png)

请问应该如何单独编译SM4的部分？

**Comment by zhenyuwei** [comment]
建议你直接拷贝openssl的sm4代码，那个更简单点。

**Comment by jnxxhzz** [comment]
谢谢
