### ISSUE TITLE
在mac电脑上编译错误

### ISSUE THREAD

**Issue by liangruxing** [guanzhi/GmSSL#659]
我使用官方的编译方式：
export CC=clang
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export CROSS_SDK=iPhoneOS.sdk
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"
./Configure ios64-cross no-shared --prefix=/usr/local/openssl-ios64
make

报以下错误：
crypto/ec/ec_ameth.c:503:13: error: implicit declaration of function
      'EC_KEY_is_sm2p256v1' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        if (EC_KEY_is_sm2p256v1(EVP_PKEY_get0_EC_KEY(pkey))) {
            ^
1 error generated.
make[1]: *** [crypto/ec/ec_ameth.o] Error 1
make: *** [all] Error 2

**Comment by liangruxing** [comment]
不能用c99编译？

**Comment by cocoafei** [comment]
我也是这个错误，编辑几遍了

**Comment by WeightZhang** [comment]
尝试在ec_ameth.c文件中引入
#include "../include/openssl/sm2.h"
或者
# include <openssl/sm2.h>

**Comment by lu02122765** [comment]
我遇到同样的问题，谢谢WeightZhang，按照你的提示解决了问题！
