### ISSUE TITLE
Mac编译iOS目标文件报错

### ISSUE THREAD

**Issue by WeightZhang** [guanzhi/GmSSL#660]
按照官方文档执行命令：
```
export CC=clang
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export CROSS_SDK=iPhoneOS.sdk
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"
./Configure ios64-cross no-shared --prefix=/usr/local/openssl-ios64
make

```
错误信息-error info：
```
Undefined symbols for architecture arm64:
  "_EC_GFp_sm2z256_method", referenced from:
      _curve_list in libcrypto.a(ec_curve.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_app.] Error 1
make[1]: *** [apps/gmssl] Error 2
make: *** [all] Error 2
```

**Environments**
- OS: macos 10.13
- Compiler:
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Xcode Version: Xcode9.4.1 || Xcode10.0.1

**Comment by lu02122765** [comment]
我也遇到了同样的问题，有解决方法吗

**Comment by lu02122765** [comment]
> > 我也遇到了同样的问题，有解决方法吗
> 
> 木有哇～
ec_cureve.c中3133行左右注释掉EC_GFp_sm2z256_method能够编译通过，然后真机调试调用keypair = EC_KEY_new_by_curve_name(NID_sm2p256v1);就崩了。。果然不能病急乱投医，这个是sm2生成密钥对时要用到的，绕不过去，我们现在项目正好要用sm2，急死了～希望关老师能够给予帮助

**Comment by lu02122765** [comment]
另外我下载了最新发布的gmssl代码，编译真机arm64的库遇到了更多的报错，吓得我赶紧还原到上一个版本了。。

**Comment by lu02122765** [comment]
现在情况是模拟器下功能都调试好了，真机静态库编不出，无法打包app。。

**Comment by guanzhi** [comment]
EC_GFp_sm2z256_method 这个是针对X86_64的汇编实现，在其他平台上不能执行

**Comment by WeightZhang** [comment]
> 现在情况是模拟器下功能都调试好了，真机静态库编不出，无法打包app。。

编译模拟器用库没问题，真机库就报着错。看关大的回复是没太明白咱的问题。您那搞定没？

**Comment by GXLR** [comment]
@guanzhi 按照文档编译arm64报错，
Undefined symbols for architecture arm64:
  "_EC_GFp_sm2z256_method", referenced from:
      _curve_list in libcrypto.a(ec_curve.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_app.] Error 1
make[1]: *** [apps/gmssl] Error 2
make: *** [all] Error 2

.a库已经生成了是否有影响，谢谢

**Comment by GXLR** [comment]
@WeightZhang @lu02122765 @yazhouZhang 请问这个问题你们解决了吗，可以请教下吗

**Comment by lu02122765** [comment]
> > 现在情况是模拟器下功能都调试好了，真机静态库编不出，无法打包app。。
> 
> 编译模拟器用库没问题，真机库就报着错。看关大的回复是没太明白咱的问题。您那搞定没？

不好意思，前阵子没上网，这个问题没解决，后面我们换了一种解决思路，这个问题暂时搁置了

**Comment by lu02122765** [comment]
> @guanzhi 按照文档编译arm64报错，
> Undefined symbols for architecture arm64:
> "_EC_GFp_sm2z256_method", referenced from:
> _curve_list in libcrypto.a(ec_curve.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [link_app.] Error 1
> make[1]: *** [apps/gmssl] Error 2
> make: *** [all] Error 2
> 
> .a库已经生成了是否有影响，谢谢

还没解决，这个是关键函数，生成密钥对的时候要用到，所以这个问题不解决，生成.a库也无法正常使用，会报错的

**Comment by yazhouZhang** [comment]
> @WeightZhang @lu02122765 @yazhouZhang 请问这个问题你们解决了吗，可以请教下吗

没有解决。然后采用OpenSSL把2，3，4，zuc各种架构都搞定了。但是没有sm9。GMSSL有，模拟器可以，所以我又绕回来编译GMSSL了

**Comment by guanzhi** [comment]
EC_GFp_sm2z256_method 只适用于Intel的CPU，可以`./config no-asm`屏蔽一下。这个问题稍后会解决。

**Comment by GXLR** [comment]
@yazhouZhang 我编译出的openssl库，x86_64的报错，真机的不支持bitcode，不知道该怎么解决

**Comment by guanzhi** [comment]
最近的更新应该解决了这个问题：

- 在X86_64环境中用默认的`./config`，可以利用SM2的汇编实现
- 在非X86_64环境中用`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`

如果编译环境不支持`enable-ec_nistp_64_gcc_128`
- `./config -DGMSSL_NO_TURBO`

**Comment by amovexu** [comment]
最近的更新应该解决了这个问题：

* 在X86_64环境中用默认的`./config`，可以利用SM2的汇编实现
* 在非X86_64环境中用`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`

如果编译环境不支持`enable-ec_nistp_64_gcc_128`

* `./config -DGMSSL_NO_TURBO`
加这个会报找不到'assert.h'，不用这个选项又落入之前"_EC_GFp_sm2z256_method"了。。。。

**Comment by xuxu1397** [comment]
> 最近的更新应该解决了这个问题：
> 
> * 在X86_64环境中用默认的`./config`，可以利用SM2的汇编实现
> * 在非X86_64环境中用`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`
> 
> 如果编译环境不支持`enable-ec_nistp_64_gcc_128`
> 
> * `./config -DGMSSL_NO_TURBO`

我用了最新版本，按照export CC=clang
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export CROSS_SDK=iPhoneOS.sdk
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"
./Configure ios64-cross no-shared --prefix=/usr/local/openssl-ios64
make
发现还是报同样的错误，是我哪里命令写错了吗？

**Comment by xuxu1397** [comment]
> > 现在情况是模拟器下功能都调试好了，真机静态库编不出，无法打包app。。
> 
> 编译模拟器用库没问题，真机库就报着错。看关大的回复是没太明白咱的问题。您那搞定没？

你这边解决了吗？

**Comment by timeforasong** [comment]
> 最近的更新应该解决了这个问题：
> 
> * 在X86_64环境中用默认的`./config`，可以利用SM2的汇编实现
> * 在非X86_64环境中用`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`
> 
> 如果编译环境不支持`enable-ec_nistp_64_gcc_128`
> 
> * `./config -DGMSSL_NO_TURBO`

ios上线提示Non-public API usage:
The app references non-public symbols in : _getcontext, _makecontext, _setcontext，这个怎么解决？大佬

**Comment by GXLR** [comment]
> > @WeightZhang @lu02122765 @yazhouZhang 请问这个问题你们解决了吗，可以请教下吗
> 
> 没有解决。然后采用OpenSSL把2，3，4，zuc各种架构都搞定了。但是没有sm9。GMSSL有，模拟器可以，所以我又绕回来编译GMSSL了

我现在openssl的sm2可以了，能否指导下sm3的用法，谢谢
