### ISSUE TITLE
调用ECDSA_SIG_st 报错

### ISSUE THREAD

**Issue by HaoXuan40404** [guanzhi/GmSSL#661]
**Describe the bug**
我的代码如下：
```
ECDSA_SIG* signData = NULL;
char* rData = NULL;
rData = BN_bn2hex(signData->r);
```
编译时出现了
```
invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
```
发现编译器编译时在ec.h 1048行报错。
修改ec.h 1048行
```
typedef struct ECDSA_SIG_st {
    BIGNUM *r;
    BIGNUM *s;
} ECDSA_SIG;
```
并注释掉ec_lcl.h 65行的ECDSA_SIG_st后代码正常
**Expected behavior**

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by guanzhi** [comment]
1. 应用不应该直接设置ECDSA_SIG的值
2. 建议你用 SM2_sign/SM2_verify 这两个函数

**Comment by HaoXuan40404** [comment]
好的，感谢

**Comment by HaoXuan40404** [comment]
signData = SM2_do_sign(zValue, zValueLen, sm2Key);
