### ISSUE TITLE
SM2_compute_share_key 没有实现？

### ISSUE THREAD

**Issue by xuebo2215** [guanzhi/GmSSL#662]
sm2_exch.c 中的SM2_compute_share_key函数
int SM2_compute_share_key(unsigned char *out, size_t *outlen,
	const EC_POINT *peer_ephem, EC_KEY *ephem,
	const EC_POINT *peer_pk, const unsigned char *peer_z, size_t peer_zlen,
	const unsigned char *z, size_t zlen, EC_KEY *sk, int initiator)
{
	memset(out, 1, *outlen);
	return 1;
}

**Comment by guanzhi** [comment]
1. 这个函数还没有实现
2. 这个函数可能会被改为内部函数，仅用于SSL
3. 你应该用SM2_KAP_xxxx 系列函数实现SM2密钥交换

**Comment by mkp4211** [comment]
请问golang api有实现sm2秘钥交换算法么？

**Comment by mkp4211** [comment]
请问golang api有实现sm2秘钥交换算法么？
在gmssltest，test.go中示例代码，
![image](https://user-images.githubusercontent.com/53291890/62505805-b3715200-b830-11e9-8ece-dae4438cec3b.png)
生成的EC的秘钥对，如果要使用sm2秘钥交换，是否要使用
![image](https://user-images.githubusercontent.com/53291890/62505873-e9aed180-b830-11e9-890c-ed45b5059b09.png)
