### ISSUE TITLE
使用PHP 编译后执行不了，显示没用使用GMSSL库，没有相关的算法

### ISSUE THREAD

**Issue by Wdiviner** [guanzhi/GmSSL#663]
使用的是PHP api，编译成功后，执行提示找不到国密算范，求指点

**Comment by guanzhi** [comment]
你得先编译安装GmSSL，PHP的这个扩展模块依赖libcrypto库

**Comment by Wdiviner** [comment]
老师您好，我是按照 http://gmssl.org/docs/php-api.html 这个连接里的说明文档安装的php，执行php的api就是提示找不到国密算法

**Comment by huangxiao4542** [comment]
你好，请问解决了吗？我也遇到同样的问题。

**Comment by LazyBenches** [comment]
编译安装php7.2.27 失败 gmssl 已安装 版本GmSSL 2.5.4 - OpenSSL 1.1.0d
/usr/bin/ld: /usr/local/lib/libcrypto.a(threads_pthread.o): undefined reference to symbol 'pthread_rwlock_unlock@@GLIBC_2.2.5'
/usr/bin/ld: //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:276: sapi/cli/php] Error 1
