### ISSUE TITLE
engine使用sm1算法

### ISSUE THREAD

**Issue by 942685826** [guanzhi/GmSSL#664]
engine机制已经把sm4替换成sm1算法了，但是如何直接使用 ECDHE-SM2-WITH-SM1-SM3这个加密套件

**Comment by guanzhi** [comment]
用不了，暂不支持这个套件

**Comment by zhenyuwei** [comment]
参考调用sms4算法方式，自己在gmssl里面添加需要调用的接口

**Comment by yyl123456** [comment]
现在支持sm1的加密套件么
