### ISSUE TITLE
golang 动态编译通过，静态编译报错”

### ISSUE THREAD

**Issue by zyf7862634** [guanzhi/GmSSL#666]
关老师您好， 请教一个 问题。 我用golang 执行gmssltest 测试时，发现 直接 go build 可以正常编译通过，并且测试通过，
但是 静态编译时 go build --ldflags "-extldflags -static"

/opt/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/local/lib/libcrypto.a(b_addr.o): In function BIO_lookup': b_addr.c:(.text+0xc9c): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking /usr/local/lib/libcrypto.a(b_sock.o): In function BIO_gethostbyname':
b_sock.c:(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function dlfcn_globallookup': dso_dlfcn.c:(.text+0x11): undefined reference to dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to dlsym' dso_dlfcn.c:(.text+0x2f): undefined reference to dlclose'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':

会有这种错误，是什么原因？

**Comment by guanzhi** [comment]
Go API 需要调用GmSSL的二进制动态库，你这里是静态编译的，因此失败。

**Comment by zyf7862634** [comment]
GO API 怎么可以修改成调用GMSSL 的静态库的方式呢？

**Comment by zyf7862634** [comment]
> Go API 需要调用GmSSL的二进制动态库，你这里是静态编译的，因此失败。

那如果我想用GO API 调用GMSSL 的静态库的方式，我需要怎么修改呢？ 项目需要静态库的形式。

**Comment by Wdiviner** [comment]
请问一下您是怎么执行成功的呢？我在centos7.5下，各种环境已经配置好了，gmssl库也安装好了，按照文档的步骤，使用go build 后就提示以下各种问题：
```
/tmp/go-build460159370/b023/_x002.o：在函数‘_BIO_get_mem_data’中：
../gmssl/build.go:60：对‘BIO_ctrl’未定义的引用
/tmp/go-build460159370/b023/_x002.o：在函数‘_OPENSSL_free’中：
../gmssl/build.go:64：对‘CRYPTO_free’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_ASN1_INTEGER_to_BN’中：
/tmp/go-build/cgo-gcc-prolog:41：对‘ASN1_INTEGER_to_BN’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_free’中：
/tmp/go-build/cgo-gcc-prolog:59：对‘BIO_free’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new’中：
/tmp/go-build/cgo-gcc-prolog:76：对‘BIO_new’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new_mem_buf’中：
/tmp/go-build/cgo-gcc-prolog:95：对‘BIO_new_mem_buf’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_s_mem’中：
/tmp/go-build/cgo-gcc-prolog:111：对‘BIO_s_mem’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BN_bn2hex’中：
/tmp/go-build/cgo-gcc-prolog:128：对‘BN_bn2hex’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_PEM_read_bio_X509’中：
/tmp/go-build/cgo-gcc-prolog:172：对‘PEM_read_bio_X509’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_NAME_oneline’中：
/tmp/go-build/cgo-gcc-prolog:192：对‘X509_NAME_oneline’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_check_private_key’中：
/tmp/go-build/cgo-gcc-prolog:211：对‘X509_check_private_key’未定义的引用
/tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_get0_serialNumber’中：
/tmp/go-build/cgo-gcc-prolog:240：对‘X509_get0_serialNumber’未定义的引用
```
等等提示，请问您是怎么go build 通过的呢？感谢您的帮助！

**Comment by zyf7862634** [comment]
> 请问一下您是怎么执行成功的呢？我在centos7.5下，各种环境已经配置好了，gmssl库也安装好了，按照文档的步骤，使用go build 后就提示以下各种问题：
> 
> ```
> /tmp/go-build460159370/b023/_x002.o：在函数‘_BIO_get_mem_data’中：
> ../gmssl/build.go:60：对‘BIO_ctrl’未定义的引用
> /tmp/go-build460159370/b023/_x002.o：在函数‘_OPENSSL_free’中：
> ../gmssl/build.go:64：对‘CRYPTO_free’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_ASN1_INTEGER_to_BN’中：
> /tmp/go-build/cgo-gcc-prolog:41：对‘ASN1_INTEGER_to_BN’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_free’中：
> /tmp/go-build/cgo-gcc-prolog:59：对‘BIO_free’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new’中：
> /tmp/go-build/cgo-gcc-prolog:76：对‘BIO_new’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new_mem_buf’中：
> /tmp/go-build/cgo-gcc-prolog:95：对‘BIO_new_mem_buf’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_s_mem’中：
> /tmp/go-build/cgo-gcc-prolog:111：对‘BIO_s_mem’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BN_bn2hex’中：
> /tmp/go-build/cgo-gcc-prolog:128：对‘BN_bn2hex’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_PEM_read_bio_X509’中：
> /tmp/go-build/cgo-gcc-prolog:172：对‘PEM_read_bio_X509’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_NAME_oneline’中：
> /tmp/go-build/cgo-gcc-prolog:192：对‘X509_NAME_oneline’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_check_private_key’中：
> /tmp/go-build/cgo-gcc-prolog:211：对‘X509_check_private_key’未定义的引用
> /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_get0_serialNumber’中：
> /tmp/go-build/cgo-gcc-prolog:240：对‘X509_get0_serialNumber’未定义的引用
> ```
> 等等提示，请问您是怎么go build 通过的呢？感谢您的帮助！

你这个看着是 指定的连接库路径不对

**Comment by Wdiviner** [comment]
> > 请问一下您是怎么执行成功的呢？我在centos7.5下，各种环境已经配置好了，gmssl库也安装好了，按照文档的步骤，使用go build 后就提示以下各种问题：
> > ```
> > /tmp/go-build460159370/b023/_x002.o：在函数‘_BIO_get_mem_data’中：
> > ../gmssl/build.go:60：对‘BIO_ctrl’未定义的引用
> > /tmp/go-build460159370/b023/_x002.o：在函数‘_OPENSSL_free’中：
> > ../gmssl/build.go:64：对‘CRYPTO_free’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_ASN1_INTEGER_to_BN’中：
> > /tmp/go-build/cgo-gcc-prolog:41：对‘ASN1_INTEGER_to_BN’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_free’中：
> > /tmp/go-build/cgo-gcc-prolog:59：对‘BIO_free’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new’中：
> > /tmp/go-build/cgo-gcc-prolog:76：对‘BIO_new’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new_mem_buf’中：
> > /tmp/go-build/cgo-gcc-prolog:95：对‘BIO_new_mem_buf’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_s_mem’中：
> > /tmp/go-build/cgo-gcc-prolog:111：对‘BIO_s_mem’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BN_bn2hex’中：
> > /tmp/go-build/cgo-gcc-prolog:128：对‘BN_bn2hex’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_PEM_read_bio_X509’中：
> > /tmp/go-build/cgo-gcc-prolog:172：对‘PEM_read_bio_X509’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_NAME_oneline’中：
> > /tmp/go-build/cgo-gcc-prolog:192：对‘X509_NAME_oneline’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_check_private_key’中：
> > /tmp/go-build/cgo-gcc-prolog:211：对‘X509_check_private_key’未定义的引用
> > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_get0_serialNumber’中：
> > /tmp/go-build/cgo-gcc-prolog:240：对‘X509_get0_serialNumber’未定义的引用
> > ```
> > 等等提示，请问您是怎么go build 通过的呢？感谢您的帮助！
> 
> 你这个看着是 指定的连接库路径不对

这个我不懂，想请问一下您，这个该怎么指定连接库的路径呢？谢谢您！

**Comment by zyf7862634** [comment]
> > > 请问一下您是怎么执行成功的呢？我在centos7.5下，各种环境已经配置好了，gmssl库也安装好了，按照文档的步骤，使用go build 后就提示以下各种问题：
> > > ```
> > > /tmp/go-build460159370/b023/_x002.o：在函数‘_BIO_get_mem_data’中：
> > > ../gmssl/build.go:60：对‘BIO_ctrl’未定义的引用
> > > /tmp/go-build460159370/b023/_x002.o：在函数‘_OPENSSL_free’中：
> > > ../gmssl/build.go:64：对‘CRYPTO_free’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_ASN1_INTEGER_to_BN’中：
> > > /tmp/go-build/cgo-gcc-prolog:41：对‘ASN1_INTEGER_to_BN’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_free’中：
> > > /tmp/go-build/cgo-gcc-prolog:59：对‘BIO_free’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new’中：
> > > /tmp/go-build/cgo-gcc-prolog:76：对‘BIO_new’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_new_mem_buf’中：
> > > /tmp/go-build/cgo-gcc-prolog:95：对‘BIO_new_mem_buf’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BIO_s_mem’中：
> > > /tmp/go-build/cgo-gcc-prolog:111：对‘BIO_s_mem’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_BN_bn2hex’中：
> > > /tmp/go-build/cgo-gcc-prolog:128：对‘BN_bn2hex’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_PEM_read_bio_X509’中：
> > > /tmp/go-build/cgo-gcc-prolog:172：对‘PEM_read_bio_X509’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_NAME_oneline’中：
> > > /tmp/go-build/cgo-gcc-prolog:192：对‘X509_NAME_oneline’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_check_private_key’中：
> > > /tmp/go-build/cgo-gcc-prolog:211：对‘X509_check_private_key’未定义的引用
> > > /tmp/go-build460159370/b023/_x003.o：在函数‘_cgo_ef009d61cfde_Cfunc_X509_get0_serialNumber’中：
> > > /tmp/go-build/cgo-gcc-prolog:240：对‘X509_get0_serialNumber’未定义的引用
> > > ```
> > > 等等提示，请问您是怎么go build 通过的呢？感谢您的帮助！
> > 
> > 
> > 你这个看着是 指定的连接库路径不对
> 
> 这个我不懂，想请问一下您，这个该怎么指定连接库的路径呢？谢谢您！

你把生成的动态库， 放到  /usr/lib 下  在编译试试

**Comment by Wdiviner** [comment]
> 你把生成的动态库， 放到 /usr/lib 下 在编译试试
您好，请问一下生成的动态库是libcrypto.so 和 libssl.so 这两个文件吗？我按照您说的把这两个动态库放在、usr/lib目录下还是报同样的错误。

**Comment by zyf7862634** [comment]
> > 你把生成的动态库， 放到 /usr/lib 下 在编译试试
> 
> 您好，请问一下生成的动态库是libcrypto.so 和 libssl.so 这两个文件吗？我按照您说的把这两个动态库放在/usr/lib目录下还是报同样的错误。

build.go 里面cgo 指定的方式修改一下

**Comment by Wdiviner** [comment]
> > 您好，请问一下生成的动态库是libcrypto.so 和 libssl.so 这两个文件吗？我按照您说的把这两个动态库放在/usr/lib目录下还是报同样的错误。
> 
> build.go 里面cgo 指定的方式修改一下

您好，我已经按照您说的方式把动态库添加到/usr/lib 下，并且也修改build.go 里cgo方式为：
`#cgo darwin LDFLAGS: -L /usr/lib -lcrypto -lssl`
还是继续报同样的错误，请教下您，您是在什么环境下，怎么编译gmssl到go build 成功的，能方便简单写一个操作流程嘛？谢谢您！

**Comment by zyf7862634** [comment]
> > > 您好，请问一下生成的动态库是libcrypto.so 和 libssl.so 这两个文件吗？我按照您说的把这两个动态库放在/usr/lib目录下还是报同样的错误。
> > 
> > 
> > build.go 里面cgo 指定的方式修改一下
> 
> 您好，我已经按照您说的方式把动态库添加到/usr/lib 下，并且也修改build.go 里cgo方式为：
> `#cgo darwin LDFLAGS: -L /usr/lib -lcrypto -lssl`
> 还是继续报同样的错误，请教下您，您是在什么环境下，怎么编译gmssl到go build 成功的，能方便简单写一个操作流程嘛？谢谢您！

#cgo  LDFLAGS: -L /usr/lib -lcrypto -lssl
darwin 是mac 版的

**Comment by Wdiviner** [comment]
> #cgo LDFLAGS: -L /usr/lib -lcrypto -lssl
> darwin 是mac 版的
谢谢您，问题解决了，感谢。

**Comment by guanzhi** [comment]
是否有人可以提交一个pull request，来解决CGO支持多平台编译的问题？
