### ISSUE TITLE
ssl认证

### ISSUE THREAD

**Issue by 942685826** [guanzhi/GmSSL#668]
SSL_connect如何设置超时应答不阻塞在哪里

**Comment by zhenyuwei** [comment]
openssl里面有大量的demo用来测试，你可以参考s_client.c或者s_server.c文件自己研究

**Comment by pengtianabc** [comment]
对于`SSL *`类型：`SSL_set_timeout(SSL_get_session(ssl), timeout)`；
 对于`SSL_CTX *`类型：`SSL_CTX_set_timeout(ctx, timeout)`;
