### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by tan00** [guanzhi/GmSSL#669]
**Describe the bug**
  windows编译失败 
步骤
- perl Configure VC-WIN64A no-asm
- nmake

报错如下
`ssl\statem\statem_gmtls.c(1391): error C2449: 在文件范围内找到“{”(是否缺少函数头?)
`
报错行代码:
`
static int gmtls_sm2_derive(SSL *s, EVP_PKEY *privkey, EVP_PKEY *pubkey, int initiator)
`
libcrypto-1_1-x64.dll 文件已经编译成功 libssl编译失败

**Environments**
- OS: [win10 x64 ]
- Compiler: [vs2017 x64]

**Comment by guanzhi** [comment]
参考 #670
