### ISSUE TITLE
windows下编译错误

### ISSUE THREAD

**Issue by LoadLife** [guanzhi/GmSSL#670]
\statem\statem_gmtls.c"
statem_gmtls.c
ssl\statem\statem_gmtls.c(878): warning C4018: “<”: 有符号/无符号不匹配
ssl\statem\statem_gmtls.c(1059): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
ssl\statem\statem_gmtls.c(1391): error C2449: 在文件范围内找到“{”(是否缺少函数头?)
ssl\statem\statem_gmtls.c(1489): error C2059: 语法错误:“}”
ssl\statem\statem_gmtls.c(1589): warning C4013: “gmtls_sm2_derive”未定义；假设外部返回 int
ssl\statem\statem_gmtls.c(2158): warning C4013: “gmtls_construct_cke_sm2dhe”未定义；假设外部返回 int
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
编译环境：
vs 2015
activepeal 5.26.3

**Comment by guanzhi** [comment]
GmSSL目前集成了 AppVeyor 用于Windows环境下的编译测试。
你可以参考一下 appveyor.yml 的配置。
如果觉得我们用的 AppVeyor 配置不足以涵盖你的环境，请提交对 appveyor.yml 的Pull Request。

**Comment by LoadLife** [comment]
> GmSSL目前集成了 AppVeyor 用于Windows环境下的编译测试。
> 你可以参考一下 appveyor.yml 的配置。
> 如果觉得我们用的 AppVeyor 配置不足以涵盖你的环境，请提交对 appveyor.yml 的Pull Request。

6404:error:0200274D:system library:connect:reason(1869):crypto\bio\b_sock2.c:108:
6404:error:2008A067:BIO routines:BIO_connect:connect error:crypto\bio\b_sock2.c:109:
6404:error:0200274D:system library:connect:reason(1869):crypto\bio\b_sock2.c:108:
6404:error:2008A067:BIO routines:BIO_connect:connect error:crypto\bio\b_sock2.c:109:
connect:errno=0
error in s_client
我在使用s_client时候遇到这个错误，请问关老师这是由于什么导致的，操作系统接口的原因吗？
