### ISSUE TITLE
golang版本静态编译失败问题

### ISSUE THREAD

**Issue by zyf7862634** [guanzhi/GmSSL#673]
关老师您好， 我想问一下如果我想基于gmssl的静态库来编译 golang 代码， 编译出来不依赖动态gmssl库的go程序，我需要怎么修改？谢谢了！

**Comment by knull-cn** [comment]
最近正好搞区块链适配，正好做了golang的封装。可以参考：https://github.com/knull-cn/GmSSL/tree/master/blockchain。下面的gosm2就是golang的功能，用的就是静态库。
