### ISSUE TITLE
新人提问，windows下想要能用skf设备要怎么做啊

### ISSUE THREAD

**Issue by lzy123123** [guanzhi/GmSSL#678]
下载下来编译，安装完了。
在skf密码设备文档里面只提了：
GmSSL提供了一个通用的SKF引擎可以。
厂商提供硬件。
后面就是一些命令了，直接用有报错。
新人一个，不知道要怎么弄啊 ToT

**Comment by guanzhi** [comment]
在使用SKF功能的时候，除了计算机上安装设备，你还需要厂商会给你的动态库，一般名字类似于`libskf.so`。这样你可以可以通过`gmssl skf`命令行访问设备的信息，并且做初始化、密钥生成等设置操作，可以通过`#include <openssl/skf.h>`中的SKF C接口编程访问设备的功能。

GmSSL项目还有一个收费的SKF ENGINE，通过这个ENGINE，你可以用常规的EVP接口来做签名等密码操作，或者在`sm2utl`、`pkeyutl`等命令中调用SKF设备，或者在SSL中调用SKF设备。

**Comment by lzy123123** [comment]
有动态库，在使用前要做什么操作吗？要修改什么地方的代码吗？或者说做什么操作？我在尝试中：
gmssl
skf -lib 动态库名
显示error in skf
再加其他选项就直接退出

**Comment by rongbingzhou** [comment]
我在windows上，按照gmssl skf -lib <vendor's-skf-dynmic-lib> -listdevs，没有得到任何结果。但用代码直接调用接口时可以获取到数据的。

**Comment by Findlyzhu** [comment]
> 在使用SKF功能的时候，除了计算机上安装设备，你还需要厂商会给你的动态库，一般名字类似于`libskf.so`。这样你可以可以通过`gmssl skf`命令行访问设备的信息，并且做初始化、密钥生成等设置操作，可以通过`#include <openssl/skf.h>`中的SKF C接口编程访问设备的功能。
> 
> GmSSL项目还有一个收费的SKF ENGINE，通过这个ENGINE，你可以用常规的EVP接口来做签名等密码操作，或者在`sm2utl`、`pkeyutl`等命令中调用SKF设备，或者在SSL中调用SKF设备。

想请问一下，这个收费engine，需要多少费用可以提供源码
