### ISSUE TITLE
linux下java编译出错

### ISSUE THREAD

**Issue by zhaoming0018** [guanzhi/GmSSL#679]
你好，我在尝试使用GmSSL的java库的时候，参考了文档的方法，在Configure文件中添加了java的编译选项，但是最后编译出错了：
![image](https://user-images.githubusercontent.com/13400903/51230863-716be600-199c-11e9-93ca-9e871e8378aa.png)
这是issues374中的问题，提出的方法尝试了但是没有解决问题，请教如何正确编译java的jni，谢谢！

**Comment by ThomasDrTang** [comment]
遇到一模一样的情况，请问有办法解决么 @zhaoming0018 @guanzhi

**Comment by zhaoming0018** [comment]
@ThomasDrTang 搞定了，但是不是直接加java选项的，而是通过java文件夹底下的文件单独编译jni的功能的，要是还没解决欢迎讨论。

**Comment by ThomasDrTang** [comment]
嗯，我也是直接在那个文件夹里面写cmake编译出来的~ @zhaoming0018

**Comment by ThomasDrTang** [comment]
当时忘记再来回复下了

**Comment by kingshowbei** [comment]
@zhaoming0018 老哥，请教怎么单独编译java的jni，感谢！

**Comment by knull-cn** [comment]
![image](https://user-images.githubusercontent.com/5057528/56704873-649c2280-6741-11e9-8507-fba7ae3723f0.png)
把语句拷贝下来，红色的那部分去掉就可以了（报错就提示了：gmssljni.map格式有问题，所以直接不要这个map就可以了）

**Comment by AndyWebJava** [comment]
> @ThomasDrTang 搞定了，但是不是直接加java选项的，而是通过java文件夹底下的文件单独编译jni的功能的，要是还没解决欢迎讨论。

给个联系方式呗，我这里还是不行。

**Comment by AndyWebJava** [comment]
> ![image](https://user-images.githubusercontent.com/5057528/56704873-649c2280-6741-11e9-8507-fba7ae3723f0.png)
> 把语句拷贝下来，红色的那部分去掉就可以了（报错就提示了：gmssljni.map格式有问题，所以直接不要这个map就可以了）

可以说的再详细些吗？红色那部分在哪里去掉？

**Comment by AndyWebJava** [comment]
> ![image](https://user-images.githubusercontent.com/5057528/56704873-649c2280-6741-11e9-8507-fba7ae3723f0.png)
> 把语句拷贝下来，红色的那部分去掉就可以了（报错就提示了：gmssljni.map格式有问题，所以直接不要这个map就可以了）

可以留个联系方式么

**Comment by knull-cn** [comment]
> > ![image](https://user-images.githubusercontent.com/5057528/56704873-649c2280-6741-11e9-8507-fba7ae3723f0.png)
> > 把语句拷贝下来，红色的那部分去掉就可以了（报错就提示了：gmssljni.map格式有问题，所以直接不要这个map就可以了）
> 
> 可以留个联系方式么

qq:2560495279
Makefile最后执行的语句拷贝下来，并且把",--version-script=gmssljni.map"删除，再执行一遍，就可以了

**Comment by zhaoming0018** [comment]
很久没看回复，有人提问比较抱歉，我写了个文档，仅供参考[笔记](http://note.youdao.com/noteshare?id=f258f9666b18f9a384bdeec75b2c8f07)
