### ISSUE TITLE
建议添加id-sm2PublicKey的oid

### ISSUE THREAD

**Issue by GoldSaintEagle** [guanzhi/GmSSL#682]
**Is your feature request related to a problem? Please describe.**
国密算法是为了替代美国的EC系列算法。因此，我认为SM系列是与美国的EC算法家族并列关系。在SM2的证书中，采用了1.2.840.10045.2.1标识该证书是SM2系列的公钥（与ECDSA证书的该域相同）。当然，可以通过Curve OID来进一步区分是SM2 PubKey还是EC PubKey。但是我认为需要申请id-sm2PublicKey（如1.2.156.10197.2.1）来表示该域，因为“1.2.156”是ISO-CN（中国标准）的算法OID；而“1.2.840”是ISO-US（美国标准）算法的OID。

严格地讲，尽管美国标准定义的id-ecPublicKey表示“椭圆曲线上某点作为公钥”，我们也不能使用该OID，因为该OID的前缀是美国标准。

**Describe the solution you'd like**
添加id-sm2PublicKey的oid为1.2.156.10197.2.1，该OID表示“椭圆曲线上某点作为公钥”（中国标准）

**Describe alternatives you've considered**
因为我只关注了SM2的证书，不知道id-sm9PublicKey是否也表示“椭圆曲线上某点作为公钥”。是否可以与id-sm9PublicKey的OID通用可以进一步讨论。

**Additional context**
是否需要同时申请1.2.156.10197.1.1表示“素域”？（替代1.2.840.10045.1.1 prime-field，为了扩展性）

**Comment by emmansun** [comment]
**OpenSSL 3+** 使用了SM2公钥密码算法OID```1.2.156.10197.1.301```, 《GB/T 33560-2017 信息安全技术 密码应用标识规范》附录A,导致后向兼容性问题，这是常被人诟病的标准落后于实践的问题。

- https://github.com/openssl/openssl/discussions/22184
- https://github.com/openssl/openssl/pull/22529
- https://github.com/openssl/openssl/issues/20973
- https://github.com/openssl/openssl/pull/11328
- https://github.com/Tongsuo-Project/Tongsuo/issues/477
- https://github.com/emmansun/gmsm/issues/197

**Comment by andylee521** [comment]
最主要的问题是，市场上大量应用了使用EC OID的证书，导致修正的成本太高，而最终导致糊里糊涂的无法更正为正确的OID。

**Comment by Junfou** [comment]
> **OpenSSL 3+** 使用了SM2公钥密码算法OID`1.2.156.10197.1.301`, 《GB/T 33560-2017 信息安全技术 密码应用标识规范》附录A,导致后向兼容性问题，这是常被人诟病的标准落后于实践的问题。
> 
> * [SM2 CSR public key OID error openssl/openssl#22184](https://github.com/openssl/openssl/discussions/22184)
> * [Fix the encoding of SM2 keys openssl/openssl#22529](https://github.com/openssl/openssl/pull/22529)
> * [Which SM2 private key PEM file generated by openssl 3.x is correct? openssl/openssl#20973](https://github.com/openssl/openssl/issues/20973)
> * [EC  param / key generation openssl/openssl#11328](https://github.com/openssl/openssl/pull/11328)
> * [SM2证书的AlgorithmIdentifier与标准定义不一致 Tongsuo-Project/Tongsuo#477](https://github.com/Tongsuo-Project/Tongsuo/issues/477)
> * [OpenSSL generated SM2 key throws error on parsing emmansun/gmsm#197](https://github.com/emmansun/gmsm/issues/197)

老哥专业，我使用botan也遇到了这个问题，这个汇总很有用，基本上明白了这个ec和sm2 oid的来龙去脉~
