### ISSUE TITLE
关于wireshark抓包解析问题

### ISSUE THREAD

**Issue by johncol001** [guanzhi/GmSSL#683]
关老师，我用wireshark抓包，分析clienthello的时候，cipher suite:unknown(0xe102).可能这块的没分析出来，我想问一下，这块对应的加密套件是ECDHE-SM2-WITH-SMS4-SM3吗？我用的是GMSSL2.0代码，在
GMT 0024-2014 SSL VPN里面没有相关的定义，所以这块比较迷茫，能帮忙确认一下吗？

**Comment by guanzhi** [comment]
我不确定 wireshark 是否支持对国密相关协议、算法的解析。
建议你使用gmssl来做解析，gmssl s_server 和 s_client 两个指令支持  -trace 选项，可以打印详细的交互信息。

**Comment by LoadLife** [comment]
> 关老师，我用wireshark抓包，分析clienthello的时候，cipher suite:unknown(0xe102).可能这块的没分析出来，我想问一下，这块对应的加密套件是ECDHE-SM2-WITH-SMS4-SM3吗？我用的是GMSSL2.0代码，在
> GMT 0024-2014 SSL VPN里面没有相关的定义，所以这块比较迷茫，能帮忙确认一下吗？

https://github.com/pengtianabc/wireshark-gm这个有个支持国密的wireshark，官方版本的无法解析

**Comment by guanzhi** [comment]
建议直接使用gmssl来调试，gmssl可解析并打印详细的交互数据

**Comment by huangyehui** [comment]
> 建议直接使用gmssl来调试，gmssl可解析并打印详细的交互数据

关老师， 请问debug版本要怎么设置，我现在是用vscode 编译时 使用./config -d 。  虽然可以单步跟踪到apps/gmssl但是无法debug到ssl目录下的核心代码
