### ISSUE TITLE
sm2_exchange_key

### ISSUE THREAD

**Issue by 942685826** [guanzhi/GmSSL#685]
sm2秘钥交换算法是哪个接口

**Comment by guanzhi** [comment]
#include <openssl/sm2.h>

SM2_KAP_ 开头的一组函数

**Comment by ygm521** [comment]
我使用的ECC-SM4-SM3，在server key exchange节段gmssl生成的长度和之前我正常使用的包中长度不一样，导致握手失败。不知道需要改哪里？

**Comment by ygm521** [comment]
正常是77 ，73，而gmssl中长度是78 ，74
