### ISSUE TITLE
为什么SM2加解密要限制长度为SM2_MAX_PLAINTEXT_LENGTH（1024）？

### ISSUE THREAD

**Issue by ZZMarquis** [guanzhi/GmSSL#686]
为什么SM2加解密要限制长度为SM2_MAX_PLAINTEXT_LENGTH（1024）？

**Comment by guanzhi** [comment]
GmSSL不希望用户用SM2_encrypt()这个接口来加密密钥以外的数据，因此加了限制，看起来1024可能还是过长了。

**Comment by ZZMarquis** [comment]
国密过检有一项检测是：检测使用SM2加解密4096字节数据的性能(┬＿┬)
