### ISSUE TITLE
gmssl算的sm2签名用tassl没法验签

### ISSUE THREAD

**Issue by lvmengkeji** [guanzhi/GmSSL#687]
gmssl sm2utl -sign -inkey privkey.pem -in indata -out signdata -id 1234567812345678

tassl pkeyutl -verify -in indata -pubin -inkey pubkey.pem -sigfile signdata 

提示Signature Verification Failure

@guanzhi 用的最新master代码

**Comment by lvmengkeji** [comment]
gmssl version -a
GmSSL 2.4.3 - OpenSSL 1.1.0d  12 Jan 2019

tassl version
OpenSSL/TaSSL 1.0.2o  27 Mar 2018

**Comment by guanzhi** [comment]
`sm2utl`是直接对任意长的消息签名验签，而`pkeyutl`是对哈希值签名验签，这两个命令的功能并不对等。

**Comment by lvmengkeji** [comment]
gmssl pkeyutl -sign -in indata -inkey privkey.pem -out signdata
tassl pkeyutl -verify -in indata -pubin -inkey pubkey.pem -sigfile signdata
Signature Verification Failure
这样也不行 @guanzhi
