### ISSUE TITLE
GMSSL创建ctx环境以及客户端得到serverhello之后的操作

### ISSUE THREAD

**Issue by johncol001** [guanzhi/GmSSL#689]
关老师，我在调试GM2.0这块遇到几个问题。
1  SSL_CTX_new在创建ctx会话环境时，我选择的会话协议版本是TLS_method。我用wireshark抓包时发现现实的协议是TLS 1.0，不是GM的2.0。怀疑是我这里的取版本函数不对，如果我要用GM SSL2.0的话，这块的取协议版本函数应该是什么呢？
2  调试GM SSL2.0时的签名算法应该怎么设置呢？
3  调试GM SSL2.0时的加密套件应该怎么设置呢？

**Comment by johncol001** [comment]
还有就是客户端在接收到服务器端server hello（包含一个证书）之后，要验证其证书的合法性。这块是如何认证的呢？什么样的条件满足了，就可以说是认证通过了呢？

**Comment by zhenyuwei** [comment]
1. 握手使用的协议你可以在ssl.h文件内找到，例如使用TLS1.1，你可以设置SSL_CTX_new(TLSv1_1_client_method)即可。设置密码套件可以使用SSL_CTX_set_cipher_list。
2. 关于客户端对服务器发送证书的校验，可以使用.crl文件或者ocsp协议，在tls_process_client_certificate或gmtls_process_client_certificate接口里添加对应的处理方式。证书链的校验，在接口内部有，可以看一下代码或者debug调试。
