### ISSUE TITLE
master主分支JNI调用SM2 解密算法在多线程下失败！

### ISSUE THREAD

**Issue by alangong114** [guanzhi/GmSSL#69]
通过java调用gmssl提供的jni接口，jni接口中有很多为实现完全的空实现和一些错误，通过修改/jni/GmSSL.c
以及d2i_pu.c文件，对jni接口做了一些修改。

针对SM2的JNI修改如下：
                 
在d2i_pu.c中 115行
### 
    case EVP_PKEY_EC:
		ret->pkey.ec = EC_KEY_new_by_curve_name(NID_sm2p256v1);
        if (!o2i_ECPublicKey(&(ret->pkey.ec),
                             (const unsigned char **)pp, length)) {
            ASN1err(ASN1_F_D2I_PUBLICKEY, ERR_R_ASN1_LIB);
            goto err;
        }

 在GmSSL.c中 主要将 非对称解密算法中加密修改为解密

###
	if (!(pkctx = EVP_PKEY_CTX_new(pkey, NULL))) {
		PRINT_ERROR();
		goto end;
	}

	if (!EVP_PKEY_decrypt_init(pkctx)) {
		PRINT_ERROR();
		goto end;
	}

	if (EVP_PKEY_base_id(pkey) == EVP_PKEY_EC) {
		if (!EVP_PKEY_CTX_ctrl_str(pkctx, "ec_encrypt_algor", alg)) {
			PRINT_ERROR();
			goto end;
		}
	}

	if (!EVP_PKEY_decrypt(pkctx, outbuf, &outlen, inbuf, inlen)) {
		PRINT_ERROR();
		goto end;
	}

	if (!(ret = (*env)->NewByteArray(env, outlen))) {
		PRINT_ERROR();
		goto end;
	}

	(*env)->SetByteArrayRegion(env, ret, 0, outlen, (jbyte *)outbuf);
 

然后在加解密的过程中，传入ECDSA的秘钥对，在单线程中加解密成功，在多线程加解密会一直失败。
失败定位在：
###
     if (!EC_KEY_generate_key(ec_key)) {
		SM2err(SM2_F_SM2_CIPHERTEXT_VALUE_SIZE, ERR_R_EC_LIB);
		goto end;
	}

跟进去后发现，又生成了一个秘钥对，不太明白这个地方会什么要生成秘钥对。
且一个线程加解密是成功的，在多线程下解密过程中总是失败！！

我通过jni接口传入的 秘钥提供如下，经过Base64处理：
###
  下列曲线为十进制
 x:83562887310023777431211267345807569129283531908450921808646780158279864491634
 y:21277637101274402015581541777637620753728439488341179042143600366339609205863
d:15761843262983943278147177638552496754524683565812944318274353335483126703111
秘钥编码做了Base64
 ec_pub_key：BLi+6wvLn2D2Q8YVUcTFEqKu1nkHLV+Z0YQmH3KMPx5yLwq3QBTX3hCf0lPa9J9hU67KBjACSanZeotSyumeHGc=
ec_pri_key:
MIICBQIBADCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8wRAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqeS89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvhcVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7///////////////9yA99rIcYFK1O79Ak51UEjAgEBBIIBDzCCAQsCAQEEICLY4xvFtjLS9yIM4nI7Q9/lmAlnWBdR6JAFNbJ6FuQHoIHjMIHgAgEBMCwGByqGSM49AQECIQD////+/////////////////////wAAAAD//////////zBEBCD////+/////////////////////wAAAAD//////////AQgKOn6np2fXjRNWp5Lz2UJp/OXifUVq4+S3by9QU2UDpMEQQQyxK4sHxmBGV+ZBEZqOcmUj+MLv/JmC+FxWkWJM0x0x7w3NqL09necWb3O42tpIVPQqYd8xipHQALfMuUhOfCgAiEA/////v///////////////3ID32shxgUrU7v0CTnVQSMCAQE=

**Comment by alangong114** [comment]
d2i_pu.c修改部分，只是为了针对jni接口的sm2算法临时做的修改.

**Comment by guanzhi** [comment]
为什么要这么修改？是否能够提供您的多线程测试完整程序代码？

**Comment by conezxy** [comment]
OpenSSL库在多线程环境下，需要自己实现CRYPTO lock相关的callback，可以参考
http://stackoverflow.com/questions/3919420/tutorial-on-using-openssl-with-pthreads

否则在随机数等多个环节都会出错（有静态变量）
比如 https://github.com/guanzhi/GmSSL/blob/develop/crypto/rand/md_rand.c 这里就有一堆静态变量，不锁是不行的。
