### ISSUE TITLE
PHP7.2.14 CentOS 7.6.1810 x64扩展编译报错

### ISSUE THREAD

**Issue by wongchy** [guanzhi/GmSSL#691]
gmssl version显示 GmSSL 2.4.4 - OpenSSL 1.1.0d  26 Jan 2019

php-7.2.14 ext/openssl替换为 master分支下的ext/openss

编译命令为./configure --prefix=/usr/local/php/php-7.2.14 --with-config-file-path=/usr/local/php/php-7.2.14/etc --with-openssl

configure正常通过 make时报以下错误：

ext/openssl/.libs/openssl.o: In function `zm_startup_openssl':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1495: undefined reference to `OPENSSL_init_ssl'
ext/openssl/.libs/openssl.o: In function `zm_info_openssl':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1655: undefined reference to `OpenSSL_version'
ext/openssl/.libs/openssl.o: In function `php_openssl_asn1_time_to_time_t':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:989: undefined reference to `ASN1_STRING_get0_data'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1004: undefined reference to `ASN1_STRING_get0_data'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1004: undefined reference to `ASN1_STRING_get0_data'
ext/openssl/.libs/openssl.o: In function `sk_X509_pop':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_pop'
ext/openssl/.libs/openssl.o: In function `php_openssl_is_private_key':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4153: undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4116: undefined reference to `EVP_PKEY_get0_DSA'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4120: undefined reference to `DSA_get0_pqg'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4125: undefined reference to `DSA_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4134: undefined reference to `EVP_PKEY_get0_DH'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4138: undefined reference to `DH_get0_pqg'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4143: undefined reference to `DH_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4099: undefined reference to `EVP_PKEY_get0_RSA'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4103: undefined reference to `RSA_get0_factors'
ext/openssl/.libs/openssl.o: In function `zif_openssl_spki_export_challenge':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2137: undefined reference to `ASN1_STRING_get0_data'
ext/openssl/.libs/openssl.o: In function `php_openssl_add_assoc_name_entry':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:925: undefined reference to `ASN1_STRING_get0_data'
ext/openssl/.libs/openssl.o: In function `zif_openssl_x509_parse':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2402: undefined reference to `X509_get_version'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2429: undefined reference to `X509_getm_notBefore'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2430: undefined reference to `X509_getm_notAfter'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2432: undefined reference to `X509_getm_notBefore'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2433: undefined reference to `X509_getm_notAfter'
ext/openssl/.libs/openssl.o: In function `sk_GENERAL_NAME_pop_free':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_pop_free'
ext/openssl/.libs/openssl.o: In function `sk_GENERAL_NAME_num':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_GENERAL_NAME_value':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `openssl_x509v3_subjectAltName':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:2332: undefined reference to `ASN1_STRING_get0_data'
ext/openssl/.libs/openssl.o: In function `sk_X509_new_null':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_new_null'
ext/openssl/.libs/openssl.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_INFO_free':
/usr/local/include/openssl/x509.h:267: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_INFO_shift':
/usr/local/include/openssl/x509.h:267: undefined reference to `OPENSSL_sk_shift'
ext/openssl/.libs/openssl.o: In function `sk_X509_push':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_push'
ext/openssl/.libs/openssl.o: In function `sk_X509_INFO_num':
/usr/local/include/openssl/x509.h:267: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_pop_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_pop_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_new_null':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_new_null'
ext/openssl/.libs/openssl.o: In function `sk_X509_push':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_push'
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_push'
ext/openssl/.libs/openssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_pop':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_pop'
ext/openssl/.libs/openssl.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `zif_openssl_csr_get_subject':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:3683: undefined reference to `X509_REQ_get_subject_name'
ext/openssl/.libs/openssl.o: In function `zif_openssl_pkey_get_details':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4866: undefined reference to `EVP_PKEY_get0_DH'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4873: undefined reference to `DH_get0_pqg'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4874: undefined reference to `DH_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4888: undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4897: undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4844: undefined reference to `EVP_PKEY_get0_DSA'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4851: undefined reference to `DSA_get0_pqg'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4852: undefined reference to `DSA_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4815: undefined reference to `EVP_PKEY_get0_RSA'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4822: undefined reference to `RSA_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4823: undefined reference to `RSA_get0_factors'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4824: undefined reference to `RSA_get0_crt_params'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4933: undefined reference to `EVP_PKEY_get0_EC_KEY'
ext/openssl/.libs/openssl.o: In function `zif_openssl_dh_compute_key':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4976: undefined reference to `EVP_PKEY_get0_DH'
ext/openssl/.libs/openssl.o: In function `sk_X509_value':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_new_null':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_new_null'
ext/openssl/.libs/openssl.o: In function `sk_X509_push':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_push'
ext/openssl/.libs/openssl.o: In function `sk_X509_pop_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_pop_free'
ext/openssl/.libs/openssl.o: In function `sk_X509_push':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_push'
ext/openssl/.libs/openssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_value':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `sk_X509_CRL_num':
/usr/local/include/openssl/x509.h:241: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_X509_CRL_value':
/usr/local/include/openssl/x509.h:241: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `sk_X509_pop_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_pop_free'
ext/openssl/.libs/openssl.o: In function `zif_openssl_private_encrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5678: undefined reference to `EVP_PKEY_get0_RSA'
ext/openssl/.libs/openssl.o: In function `zif_openssl_private_decrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5740: undefined reference to `EVP_PKEY_get0_RSA'
ext/openssl/.libs/openssl.o: In function `zif_openssl_public_encrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5808: undefined reference to `EVP_PKEY_get0_RSA'
ext/openssl/.libs/openssl.o: In function `zif_openssl_public_decrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5871: undefined reference to `EVP_PKEY_get0_RSA'
ext/openssl/.libs/openssl.o: In function `zif_openssl_sign':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5980: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6017: undefined reference to `EVP_MD_CTX_free'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5994: undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6006: undefined reference to `EVP_MD_CTX_free'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:5989: undefined reference to `EVP_MD_CTX_free'
ext/openssl/.libs/openssl.o: In function `zif_openssl_verify':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6070: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6093: undefined reference to `EVP_MD_CTX_free'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6097: undefined reference to `EVP_MD_CTX_free'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6082: undefined reference to `EVP_PKEY_get0_EC_KEY'
ext/openssl/.libs/openssl.o: In function `zif_openssl_seal':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6184: undefined reference to `EVP_CIPHER_CTX_reset'
ext/openssl/.libs/openssl.o: In function `zif_openssl_digest':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6415: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6438: undefined reference to `EVP_MD_CTX_free'
ext/openssl/.libs/openssl.o: In function `zif_openssl_encrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6734: undefined reference to `EVP_CIPHER_CTX_reset'
ext/openssl/.libs/openssl.o: In function `zif_openssl_decrypt':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6821: undefined reference to `EVP_CIPHER_CTX_reset'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:6821: undefined reference to `EVP_CIPHER_CTX_reset'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_num':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_value':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `zif_openssl_csr_sign':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:3514: undefined reference to `X509_REQ_get_subject_name'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:3523: undefined reference to `X509_getm_notBefore'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:3524: undefined reference to `X509_getm_notAfter'
ext/openssl/.libs/openssl.o: In function `php_openssl_make_REQ':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:3151: undefined reference to `X509_REQ_get_subject_name'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_num':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_value':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_num':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_num'
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/openssl.o: In function `sk_CONF_VALUE_value':
/usr/local/include/openssl/conf.h:31: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_and_assign_rsa':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4200: undefined reference to `RSA_set0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4206: undefined reference to `RSA_set0_factors'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_dsa':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4234: undefined reference to `DSA_set0_pqg'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4241: undefined reference to `DSA_set0_key'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_dh':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4311: undefined reference to `DH_set0_pqg'
ext/openssl/.libs/openssl.o: In function `php_openssl_dh_pub_from_priv':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4288: undefined reference to `BN_with_flags'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_dh':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4325: undefined reference to `DH_set0_key'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_dsa':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4253: undefined reference to `DSA_get0_key'
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4254: undefined reference to `BN_is_zero'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_dh':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4318: undefined reference to `DH_set0_key'
ext/openssl/.libs/openssl.o: In function `php_openssl_pkey_init_and_assign_rsa':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4213: undefined reference to `RSA_set0_crt_params'
ext/openssl/.libs/openssl.o: In function `zif_openssl_pkey_export_to_file':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4603: undefined reference to `EVP_PKEY_get0_EC_KEY'
ext/openssl/.libs/openssl.o: In function `zif_openssl_pkey_export':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:4680: undefined reference to `EVP_PKEY_get0_EC_KEY'
ext/openssl/.libs/openssl.o: In function `php_openssl_get_evp_md_from_algo':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1404: undefined reference to `EVP_sm3'
ext/openssl/.libs/openssl.o: In function `sk_X509_free':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_free'
ext/openssl/.libs/openssl.o: In function `php_openssl_get_evp_cipher_from_algo':
/usr/local/src/php-7.2.14/ext/openssl/openssl.c:1452: undefined reference to `EVP_sms4_cbc'
ext/openssl/.libs/xp_ssl.o: In function `php_openssl_create_sni_server_ctx':
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1369: undefined reference to `TLS_server_method'
ext/openssl/.libs/xp_ssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/xp_ssl.o: In function `sk_X509_value':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_value'
ext/openssl/.libs/xp_ssl.o: In function `sk_X509_num':
/usr/local/include/openssl/x509.h:112: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/xp_ssl.o: In function `php_openssl_setup_crypto':
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1619: undefined reference to `TLS_client_method'
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1673: undefined reference to `SSL_CTX_set_security_level'
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1714: undefined reference to `SSL_CTX_set_options'
ext/openssl/.libs/xp_ssl.o: In function `php_openssl_set_server_specific_opts':
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1300: undefined reference to `SSL_CTX_get_options'
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1327: undefined reference to `SSL_CTX_set_options'
ext/openssl/.libs/xp_ssl.o: In function `php_openssl_setup_crypto':
/usr/local/src/php-7.2.14/ext/openssl/xp_ssl.c:1619: undefined reference to `TLS_server_method'
ext/openssl/.libs/xp_ssl.o: In function `sk_GENERAL_NAME_num':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_num'
ext/openssl/.libs/xp_ssl.o: In function `sk_GENERAL_NAME_value':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_value'
ext/phar/.libs/util.o: In function `phar_verify_signature':
/usr/local/src/php-7.2.14/ext/phar/util.c:1563: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/php-7.2.14/ext/phar/util.c:1595: undefined reference to `EVP_MD_CTX_free'
/usr/local/src/php-7.2.14/ext/phar/util.c:1586: undefined reference to `EVP_MD_CTX_free'
ext/phar/.libs/util.o: In function `phar_create_signature':
/usr/local/src/php-7.2.14/ext/phar/util.c:1860: undefined reference to `EVP_MD_CTX_new'
/usr/local/src/php-7.2.14/ext/phar/util.c:1892: undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1

**Comment by guanzhi** [comment]
似乎是编译系统没有找到 libcrypto 这个库

**Comment by oceanLiang** [comment]
请问这个问题有解决么？同样遇到了。。。

**Comment by lnlg** [comment]
您好，这个问题解决了没有？一样的问题，上面说系统没有找到 libcrypto 这个库。我这边查看/lib64/下面有 我又把它ln -s 到/lib/下面。编译还是同样的错误。

**Comment by kuailu123** [comment]
今天我要炫一下自己，因为我现在完美的解决了这一问题，那就是再生成makefile后，将makefile进行修改，将gcc连接的动态库指向gmssl安装完成后生成的动态库，即libcrypto.so和libssl.so.  对于gcc如何连接，就要问一下百度了，gcc学了几年了，忘的都差不多了。

**Comment by yuesir** [comment]
> 今天我要炫一下自己，因为我现在完美的解决了这一问题，那就是再生成makefile后，将makefile进行修改，将gcc连接的动态库指向gmssl安装完成后生成的动态库，即libcrypto.so和libssl.so. 对于gcc如何连接，就要问一下百度了，gcc学了几年了，忘的都差不多了。

@kuailu123 能说下怎么解决的么，遇到了同样的问题

**Comment by HunterKou** [comment]
请问这个问题解决了吗？ 我遇到了一模一样的问题，报错都一样。 PHP 7.2.18

**Comment by phpha** [comment]
我这边也遇到了，后来发现是openssl与自带的openssl-devel版本不一致，把自带的openssl-devel卸载了重新make就通过了。

**Comment by woodycc** [comment]
先到/usr/local/lib64目录下，把libcrypto.a改名成libgmcrypto,把libssl.a改成libgmssl.a
configure完以后，修改Makefile文件，找到-lssl -lcrypto 修改成 -lgmssl -lgmcrypto，最后make

**Comment by gpython** [comment]
CentOS6 
~]# openssl version
OpenSSL 1.1.1i  8 Dec 2020

export PKG_CONFIG_PATH=/xxx/xxx/openssl/lib/pkgconfig
编译升级过openssl 指定编译后的openssl路径 --with-openssl=/xxx/xxx/openssl  --with-openssl-dir=/xxx/xxx/openssl 编译通过
参考 https://stackoverflow.com/questions/50052339/compiling-php-7-2-with-openssl
