### ISSUE TITLE
gmssl 不支持国密数字信封

### ISSUE THREAD

**Issue by ypiker** [guanzhi/GmSSL#695]
PKCS7_RECIP_INFO *p7recipinfo = PKCS7_add_recipient(p7, cert);  如果证书是sm2格式会报错不支持的密钥类型 同样 BIO * v_p7bio = PKCS7_dataDecode(p7, pkey, NULL, cert);  解密也是同样提示。

请问是否gmssl 提供了对应的国密数字信封生成方式

**Comment by guanzhi** [comment]
更新至最新的master分支（2.5.0）可以支持国密的PKCS#7和S/MIME功能。

**Comment by wangyongzx** [comment]
> PKCS7_RECIP_INFO *p7recipinfo = PKCS7_add_recipient(p7, cert); 如果证书是sm2格式会报错不支持的密钥类型 同样 BIO * v_p7bio = PKCS7_dataDecode(p7, pkey, NULL, cert); 解密也是同样提示。
> 
> 请问是否gmssl 提供了对应的国密数字信封生成方式

请教下，国密的数字信封怎么解密呀 ？
