### ISSUE TITLE
gmssl在HP-UX上能编译吗，如果可以需要怎样的config命令

### ISSUE THREAD

**Issue by lmx-hub** [guanzhi/GmSSL#696]
不知道关老师在UNIX系统上编译过gmssl没，
我最近在HP-UX11.31上编译gmssl，总是不成功，用的是aCC编译器，make执行一会后总是提示rm: crypto/rc4/rc4-ia64.s.* non-existent

**Comment by lmxeq5** [comment]
用./config no-asm可以了

**Comment by guanzhi** [comment]
如果要启用asm的话，需要有对应的汇编器
