### ISSUE TITLE
arm64库生成失败的问题

### ISSUE THREAD

**Issue by amovexu** [guanzhi/GmSSL#698]
关老师您好，按您之前的提示，最近的更新应该解决了这个问题：
在非X86_64环境中试过用`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`
也试过* `./config -DGMSSL_NO_TURBO`会报找不到'assert.h'，而那两个都不采用，采用配置成arm64还是报"_EC_GFp_sm2z256_method"，能否帮忙看看？

**Comment by xuxu1397** [comment]
同样的问题，我也卡在这里了，你解决了吗？

**Comment by guanzhi** [comment]
目前编译的时候默认用`EC_GFp_sm2z256_method`，这个实现提供超过4倍的性能提升，但是这个实现只在比较新的X86_64环境下可用，理想情况下应该判断当前硬件环境，但是目前的编译系统里面还没来得及做这个判断。
`-DGMSSL_NO_TURBO`可以显式指定不要用`EC_GFp_sm2z256_method`这个快速实现。
`ec_nistp_64_gcc_128`可以启用SM2的纯C优化实现，这个优化实现可以提供2倍的性能提升，可以用在所有64位的系统里面，但是需要较高版本编译器的支持，这个选项默认是不开启的，因此需要enable显式打开。
找不到`assert.h`说明你的编译环境或交叉编译环境设置有问题，连基本的C库头文件都没有找到

**Comment by xuxu1397** [comment]
老师，我的设备是mac pro，是X86_64，遇到了_EC_GFp_sm2z256_method这个错误，我要怎么来生成arm64的包呢？

**Comment by WilongChen** [comment]
> mac

解决了嘛？
我也遇到这个问题，
不知怎么着手
总不能重装系统吧
