### ISSUE TITLE
SM9编译

### ISSUE THREAD

**Issue by bencanber** [guanzhi/GmSSL#699]
您好，请问一下如果我想单独linux下编译SM9，应该如何操作，在您的test文件中运行了
SM9的测试文件，可以正常运行，但是修改了一下源码，不知道怎么重新编译，期待您的回复

**Comment by guanzhi** [comment]
重新运行一下make即可

**Comment by l-h-d** [comment]
> 您好，请问一下如果我想单独linux下编译SM9，应该如何操作，在您的test文件中运行了
> SM9的测试文件，可以正常运行，但是修改了一下源码，不知道怎么重新编译，期待您的回复

您好，请问在使用sm9生成对应的密钥串，然后通过生成的密钥串在进行相应的api调用，您那可以吗？谢谢

**Comment by bencanber** [comment]
在成功安装了GMSSL之后，如果我想在我的C程序里调用SM9的签名验签算法，应该如何操作？谢谢
