### ISSUE TITLE
用脚本生成的证书貌似有误

### ISSUE THREAD

**Issue by zzbghost** [guanzhi/GmSSL#7]
使用sm2-initca.sh和sm2-initca.sh生成的证书貌似还是ecc的，与例子不一样，请问有其他的产生sm2证书的方式么?
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 17722149558807527987 (0xf5f1b920b5118233)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=CN, ST=SF, L=SDF, O=S, OU=D, CN=S/emailAddress=F
        Validity
            Not Before: Nov  6 07:11:49 2015 GMT
            Not After : Nov  3 07:11:49 2025 GMT
        Subject: C=CN, ST=SF, L=SDF, O=S, OU=D, CN=S/emailAddress=F
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:91:8f:59:3d:ec:83:43:2a:d4:e4:50:13:28:60:
                    55:06:2b:af:4a:14:43:c0:4d:0c:38:21:81:34:5f:
                    98:13:fd:cf:43:cf:67:1a:cf:fd:74:3a:00:fe:94:
                    a4:1a:6a:d1:70:95:2f:a2:3d:31:19:7d:e3:99:50:
                    3c:c5:6a:f8:20
                ASN1 OID: sm2p256v1
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                E6:82:F8:15:EE:54:E0:E5:97:2F:FB:B8:AA:6D:DD:88:94:05:AF:D9
            X509v3 Authority Key Identifier: 
                keyid:E6:82:F8:15:EE:54:E0:E5:97:2F:FB:B8:AA:6D:DD:88:94:05:AF:D9

```
        X509v3 Basic Constraints: 
            CA:TRUE
Signature Algorithm: ecdsa-with-SHA256
     30:45:02:21:00:85:1f:c4:35:43:25:d9:9e:76:a9:e7:dd:dc:
     58:b5:b0:2c:88:22:c2:d6:22:58:19:f3:13:9e:eb:07:34:96:
     3c:02:20:06:aa:d8:9b:7e:7b:d9:74:ab:85:2e:1f:b0:17:b2:
     ac:40:c2:13:89:5c:2a:54:fa:76:fa:b9:24:7a:40:13:ba
```

**Comment by guanzhi** [comment]
当前GmSSL中的ECDSA实现被替换为SM2签名了，因此这个证书中的签名实际上是sm2sign-with-SHA256，所在曲线是sm2p256v1。GmSSL当前版本已经启用了独立的SM2模块(crypto/sm2/)，支持通过EVP_PKEY_sign_init/sign()接口调用SM2签名验证功能，因此对ECDSA的修改会在后面的更新中复原。

目前gmssl命令行暂时还不支持SM2的密钥生成和密码计算。近期的更新还是会集中在对EVP API的全面支持和密码库中新算法的加入，X.509部分的更新不会很快。由于生成SM2的所有底层功能都已经完备，因此目前可以基于EVP API编写生成SM2的X509格式证书。
