### ISSUE TITLE
关于SM2加密后结果验证的咨询

### ISSUE THREAD

**Issue by LightYears88** [guanzhi/GmSSL#70]
今天上午我对SM2的加密和解密指令进行了使用，并且也进行了签名认证等。windows环境下都可正常运行。
   我有个问题是，怎么验证SM2的结果呢。因为没有第三方生成的加密结果。 解密也是按照指令解密。
   算法中有一个随机数，每次加密的结果都不一样。我拿到的国家保密管理局的文档，里面也是他们给定的随机数。 想通过赋值随机数来验证，看了下测试程序，不好修改。
   请我你有比较好的验证方法吗？

**Comment by guanzhi** [comment]
`test/sm2test.c`中包含了对标准中测试数据的加解密测试，请阅读这个源文件的代码。

**Comment by andylau004** [comment]
厉害了

**Comment by andylau004** [comment]
windows能编译过？

**Comment by LightYears88** [comment]
可以，不过要修改很多....






在 2017-01-14 16:49:11，"andylau004" <notifications@github.com> 写道：


windows能编译过？

**Comment by chunheinanzi** [comment]
有一个在线的sm2加解密网址  可以验证 不过你用例子里的解密函数解密后打印输出就可以知道结果

**Comment by LightYears88** [comment]
麻烦 网址能发下吗？ 我没搜到啊，谢谢！！






在 2017-01-16 09:38:20，"chunheinanzi" <notifications@github.com> 写道：


有一个在线的sm2加解密网址 可以验证 不过你用例子里的解密函数解密后打印输出就可以知道结果

**Comment by disillusion028** [comment]
加密之后把密文再进行解密，如果结果和预期结果一致不就可以得到验证了么

**Comment by hustms** [comment]
为什么按照标准对sm2的实现会出现不能对通的情况?网上下载了好多sm2的检测工具，a工具生成的密文，b工具就解密失败。没有一套统一的检测标准么?
