### ISSUE TITLE
SM3和SM2目前是不是还不支持在端序不同的机器间使用

### ISSUE THREAD

**Issue by lmxeq5** [guanzhi/GmSSL#701]
我是在windows和hpux之间作密钥协商和身份验证，Windows运行在x86上，是小端序，hpux运行在i64上，是大端序，其中用到了sm2证书和sm3签名，发现在这两个机器间进行签名验证和身份验证的时候都不能通过，在同一个机器上同样的代码却没有问题，是不是有其他要注意的地方，求解答？

**Comment by lmxeq5** [comment]
感谢关老师的回复，您的意思是不是说windows上用原来的方式(小端序)编译，hpux上用大端序编译，这样他们之间就可以正常进行链路协商和身份验证了。

**Comment by guanzhi** [comment]
是的。目前大部分常用的处理器（X86、ARM）都是小端的，少数处理器（比如Power）是大端的，目前SM3的实现需要在大端处理器上显式指定这个编译选项，算法才正确。编译后可以执行`test/sm3test`来检测是否所有测试向量都通过。

**Comment by lmxeq5** [comment]
再次感谢关老师的及时帮助，也提一点小建议: 今天因为别的问题仔细看了一下config和10-main.conf文件，无意间发现config可以自动识别大小端机器，如果是大端会添加-DB_ENDIAN选项，所以我们byteorder.h里的宏CPU_BIGENDIAN替换成B_ENDIAN就支持自动识别了, 这样就避免了不知道这个宏的人编译出错误的版本了。

**Comment by guanzhi** [comment]
请发一个Pull Request，我可以将您的这个贡献合并到代码库中
