### ISSUE TITLE
在自己的程序中调用SM9算法

### ISSUE THREAD

**Issue by bencanber** [guanzhi/GmSSL#703]
在成功安装了GMSSL之后，如果我想在我的C程序里调用SM9的签名验签算法，应该如何操作？谢谢

**Comment by guanzhi** [comment]
SM9的C接口请参考`include/openssl/sm9.h`这个头文件，如果你基本了解SM9的功能的话，以及OpenSSL/GmSSL函数的一般命名方式，这个头文件中的函数名和参数名基本都是自解释的，SM9签名验签的函数原型和SM2/ECDSA的是非常类似的。

因为SM9的密码功能绝大部分都已经加入到EVP框架中，因此你也可以直接用EVP接口，或者命令行中的`pkeyutl`命令实现签名、验签、加密、解密等操作，通过`genpkey`实现SM9的主密钥生成等操作。稍后我们还会在网上提供一个在线的SM9的密钥分发服务示例。

**Comment by son012** [comment]
> SM9的C接口请参考`include/openssl/sm9.h`这个头文件，如果你基本了解SM9的功能的话，以及OpenSSL/GmSSL函数的一般命名方式，这个头文件中的函数名和参数名基本都是自解释的，SM9签名验签的函数原型和SM2/ECDSA的是非常类似的。
> 
> 因为SM9的密码功能绝大部分都已经加入到EVP框架中，因此你也可以直接用EVP接口，或者命令行中的`pkeyutl`命令实现签名、验签、加密、解密等操作，通过`genpkey`实现SM9的主密钥生成等操作。稍后我们还会在网上提供一个在线的SM9的密钥分发服务示例。

您好,我调用sm9_encrypt和sm9_decrypt就报错,找到报错在c3校验哪里,猜测是sk的问题,但两次生成的sk所需要的参数一样,实在不知道怎么解决

**Comment by abxcd111** [comment]
> SM9的C接口请参考`include/openssl/sm9.h`这个头文件，如果你基本了解SM9的功能的话，以及OpenSSL/GmSSL函数的一般命名方式，这个头文件中的函数名和参数名基本都是自解释的，SM9签名验签的函数原型和SM2/ECDSA的是非常类似的。
> 
> 因为SM9的密码功能绝大部分都已经加入到EVP框架中，因此你也可以直接用EVP接口，或者命令行中的`pkeyutl`命令实现签名、验签、加密、解密等操作，通过`genpkey`实现SM9的主密钥生成等操作。稍后我们还会在网上提供一个在线的SM9的密钥分发服务示例。

关教授您好，请问这个在线的SM9密钥分发示例您能给一个链接吗，我总也找不到

**Comment by abxcd111** [comment]
> SM9的C接口请参考`include/openssl/sm9.h`这个头文件，如果你基本了解SM9的功能的话，以及OpenSSL/GmSSL函数的一般命名方式，这个头文件中的函数名和参数名基本都是自解释的，SM9签名验签的函数原型和SM2/ECDSA的是非常类似的。
> 
> 因为SM9的密码功能绝大部分都已经加入到EVP框架中，因此你也可以直接用EVP接口，或者命令行中的`pkeyutl`命令实现签名、验签、加密、解密等操作，通过`genpkey`实现SM9的主密钥生成等操作。稍后我们还会在网上提供一个在线的SM9的密钥分发服务示例。

关老师您好，我想请问这个genkey是属于哪个命令的参数，因为sm9 ，sm9utl,pkey和pkeyutl都没有genkey参数，我实在是找不到生成SM9证书的方法如该官方文档 [http://gmssl.org/docs/sm9-pkg.html](url) 中提到的SM9证书。并且您部署的密钥生成服务器 [https://sm9.gmssl.org:8888/](url)也一直连接不上。
