### ISSUE TITLE
php使用sm2解密问题!

### ISSUE THREAD

**Issue by parenth** [guanzhi/GmSSL#705]
对方使用sm2对数据进行加密，我在收到数据后用PHP对数据进行解密为null
PHP使用sm2解密方式如下：

$ivlen = openssl_cipher_iv_length("sms4");
$iv = openssl_random_pseudo_bytes($ivlen);
openssl_open($sealed, $opened, $pubkey, $prikey, "sms4", $iv);

$opened为空，是否解密方式使用有问题？

**Comment by parenth** [comment]
公私匙的生成方法

利用 linux 环境下 openssl 生成
生成 2048 长度的私钥
* 1.openssl genrsa -out rsa_private_key.pem 2048
* #转成 pkcs8 格式 标准输出即使用到的私钥
* 2.openssl pkcs8 -topk8 -nocrypt -inform PEM -in rsa_private_key.pem -outform PEM outform >
pkcs8_rsa_private_key.pem
* #输出公钥
* 3.openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem

**Comment by guanzhi** [comment]
你这里生成的是RSA密钥，不是SM2密钥

**Comment by parenth** [comment]
知道了，谢谢！另外问下，openssl_open($sealed, $opened, $pubkey, $prikey, "sms4", $iv); 解码可以不用$pubkey这个公钥吗？有只用私钥的方法吗？

**Comment by guanzhi** [comment]
你对openssl_open()这个函数的理解是错的，请看`GmSSL/php/gmssltest.php`这个例子，或者阅读PHP手册中关于这个函数的文档。

**Comment by parenth** [comment]
我现在的问题是，合作方用sm2加密生成$sealed（但不是php），返回数据只有$sealed（加密数据）和$prikey（私钥）给我，我不知道怎么用PHP的sm2解密。还请指教，官方文档openssl_open ( $sealed ,  $open ,  $env_key ,  $pkeyid )  里的$env_key没有可以解密吗？

**Comment by guanzhi** [comment]
PHP中的openssl_open/seal()函数是对GmSSL中EVP_Open/Seal等函数的直接封装，因此如果对方也是用GmSSL生成的加密数据，那么至少可以判断不会出现格式兼容的问题。否则，很可能密文消息的格式都是不同的，没有正确解密的可能。

**Comment by hustms** [comment]
老大，我也遇到了一个sm2的加解密对接问题。我们用gmsslsm2加密，对方自己的算法库解密失败，报invalid ciphertext。请问为什么对出现对接不通的情况，怎么解决?

**Comment by hustms** [comment]
而且我们发现gmssl的sm2加密结果总是30开头的，而有些sm2算法加密结果是04开头的，好奇怪，参数有啥不一样么

**Comment by guanzhi** [comment]
参考 #707

**Comment by hustms** [comment]
多谢关老师的指导

**Comment by parenth** [comment]
谢谢。
