### ISSUE TITLE
为什么我用隐式加载libcrypto.so的时候总是链接到了libcrypto.so.1.1

### ISSUE THREAD

**Issue by liangruxing** [guanzhi/GmSSL#706]
我自己写测试sm2接口函数的时候，通过隐式加载libcrypto.so动态库，但是一直都是链接到了libcrypto.so.1.1；不知道为何，对c不是很熟悉.....
我编译的时候是这个命令：gcc testso.c ./libcrypto.so -I./include
然后执行：a.out
[root@izwz998ua89dqj70p6i29nz gmssl]# ./a.out 
./a.out: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
[root@izwz998ua89dqj70p6i29nz gmssl]# ldd a.out 
        linux-vdso.so.1 =>  (0x00007ffc0651d000)
        libcrypto.so.1.1 => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007faff7e99000)
        /lib64/ld-linux-x86-64.so.2 (0x00005584c692e000)

**Comment by guanzhi** [comment]
你可以直接用静态库 `gcc test.c ./libcrypto.a`暂时回避动态库的问题

**Comment by liangruxing** [comment]
好，谢谢，请问下sm2/3/4之类的函数接口有文档吗？
