### ISSUE TITLE
移除SAF和SOF接口

### ISSUE THREAD

**Issue by guanzhi** [guanzhi/GmSSL#709]
SAF (include/openssl/saf.h, crypto/saf/) 和 SOF (include/openssl/sof.h, crypto/sof) 这两个接口相对于GmSSL的原生接口来说是重复的，打算将这两个模块的实现移除。

不知道是否有人使用这两个接口？
或听说有人真的使用这两个接口？
或者有提供这两个接口的产品？

**Comment by xiaoyi971520** [comment]
为什么要移除呢

**Comment by Shitaibin** [comment]
`./config no-saf no-sdf no-skf no-sof no-zuc` 中已经没有对saf和sdf选项的支持，运行时报错。

这个文档要修改了：http://gmssl.org/docs/quickstart.html
