### ISSUE TITLE
x86_64环境下生成arm64库失败的问题

### ISSUE THREAD

**Issue by xuxu1397** [guanzhi/GmSSL#710]
关老师，我下载了最新的代码，然后用以下命令来生成arm64库
export CC=clang
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export CROSS_SDK=iPhoneOS.sdk
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"
./Configure ios64-cross no-shared --prefix=/usr/local/openssl-ios64
make
发现报错：
Undefined symbols for architecture arm64:
"_EC_GFp_sm2z256_method", referenced from:
_curve_list in libcrypto.a(ec_curve.o)
然后我看您在其他相同问题里面有讲过，说在X86_64环境中用默认的./config可以解决，意思是用./config命令来替换./Configure ios64-cross no-shared --prefix=/usr/local/openssl-ios64这个命令吗？编译硬件是mac pro，系统是macos mojave最新版本。

**Comment by sampson-wang** [comment]
方法1：
./Configure 时 加上  no-asm
方法2：
./Configure后，   打开Makefile，找到CFLAGS，加上-DGMSSL_NO_TURBO
其实，这个问题，打开源代码找一下_EC_GFp_sm2z256_method在哪调用，很快就明白了。
