### ISSUE TITLE
A question about ID used to generate Z value and a bug on hash input of SKE when use SM2-WITH-SMS4-SM3 is wrong

### ISSUE THREAD

**Issue by caogw279** [guanzhi/GmSSL#712]
**Describe the bug**
A question about ID used to generate Z value and a bug on hash input of SKE when use SM2-WITH-SMS4-SM3

**Expected behavior**
SM2-ECC 算法中server 发送SKE 时 加密证书作为digest输入，但是却截断了n-3个字节的内容，也就是最后三个字节被丢弃了

./gmssl version
GmSSL 2.5.0 - OpenSSL 1.1.0d  24 Feb 2019
**Screenshots**

**Environments**
- OS: linux
- Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)  

**Additional context**
另外：计算Z值的ID 不是
{0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38};

**Comment by guanzhi** [comment]
我会检查这个问题并在下一次更新时修复这个问题

**Comment by softblade-c** [comment]
> **Describe the bug**
> A question about ID used to generate Z value and a bug on hash input of SKE when use SM2-WITH-SMS4-SM3
> 
> **Expected behavior**
> SM2-ECC 算法中server 发送SKE 时 加密证书作为digest输入，但是却截断了n-3个字节的内容，也就是最后三个字节被丢弃了
> 
> ./gmssl version
> GmSSL 2.5.0 - OpenSSL 1.1.0d 24 Feb 2019
> **Screenshots**
> 
> **Environments**
> 
> * OS: linux
> * Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
> 
> **Additional context**
> 另外：计算Z值的ID 不是
> {0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
> 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38};

你好，我在使用gmssl（GmSSL 2.5.0 - OpenSSL 1.1.0d 28 Feb 2019）对接国密fabric（使用的国密加密包来自tjfoc）时，使用gmssl 客户端验证fabric发过来的ServerKeyExchange消息时也是失败了，双方协商的加密套件是ECDHE-SM2-WITH-SMS4-GCM-SM3，曲线也是正确的。不知你提的这个issue是否已经确认是问题了？你自己是怎么处理这个问题的呢？谢谢。

**Comment by softblade-c** [comment]
> **Describe the bug**
> A question about ID used to generate Z value and a bug on hash input of SKE when use SM2-WITH-SMS4-SM3
> 
> **Expected behavior**
> SM2-ECC 算法中server 发送SKE 时 加密证书作为digest输入，但是却截断了n-3个字节的内容，也就是最后三个字节被丢弃了
> 
> ./gmssl version
> GmSSL 2.5.0 - OpenSSL 1.1.0d 24 Feb 2019
> **Screenshots**
> 
> **Environments**
> 
> * OS: linux
> * Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
> 
> **Additional context**
> 另外：计算Z值的ID 不是
> {0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
> 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38};

另外请问一下，具体的错误在哪个位置，谢谢。
