### ISSUE TITLE
Android编译库给不同的CPU构架

### ISSUE THREAD

**Issue by xuxu1397** [guanzhi/GmSSL#717]
关老师，根据你的文档编译出来的是armeabi这个架构，我想编译出多架构的，比如：armeabiv-v7a、arm64-v8a、mips、x86_64。那具体怎么个命令行？现有的以下armeabi命令：

ANDROID_PATH=/path/to/android/sdf/
PLATFORM_VERSION=22

MAKE_TOOLCHAIN=$ANDROID_PATH/sdk/ndk-bundle/build/tools/make-standalone-toolchain.sh
export TOOLCHAIN_PATH=$ANDROID_PATH/android-toolchain-arm
$MAKE_TOOLCHAIN --arch=arm --platform=android-$PLATFORM_VERSION --install-dir=$TOOLCHAIN_PATH

export MACHINE=armv7
export SYSTEM=android
export ARCH=arm
export CROSS_SYSROOT=$TOOLCHAIN_PATH/sysroot
export TOOL_BASENAME=$TOOLCHAIN_PATH/bin/arm-linux-androideabi
export CC=$TOOL_BASENAME-gcc
export CXX=$TOOL_BASENAME-g++
export LD=$TOOL_BASENAME-ld
export LINK=$CXX
export AR=$TOOL_BASENAME-ar
export RANLIB=$TOOL_BASENAME-ranlib
export STRIP=$TOOL_BASENAME-strip

./config
make

**Comment by uikiu** [comment]
怎么解决了呢？armeabli-v7a能编译了么？
