### ISSUE TITLE
win7 环境编译64位gmssl报错，perl Configure no-asm VC-WIN64A 然后nmake install,报cversion.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突

### ISSUE THREAD

**Issue by developerdujunjie** [guanzhi/GmSSL#723]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by knull-cn** [comment]
这个需要指定编译器类型/库类型（都需要指定64位）。所以，最好的方式就是选择vc自带的命令行，我选择的是这个“Visual C++ 2015 x64 Native Build Tools Command Prompt”。这里面cl/link等相关的环境配置、头文件、库文件都指定好了，是64位的。

**Comment by Fury-Fox** [comment]
> 这个需要指定编译器类型/库类型（都需要指定64位）。所以，最好的方式就是选择vc自带的命令行，我选择的是这个“Visual C++ 2015 x64 Native Build Tools Command Prompt”。这里面cl/link等相关的环境配置、头文件、库文件都指定好了，是64位的。

具体怎么做的能说说吗？

**Comment by knull-cn** [comment]
另外，你可以参考下我fork的gmssl(https://github.com/knull-cn/GmSSL)，windows/linux都编译通过了，照着原文档做应该是没问题的

**Comment by Fury-Fox** [comment]
谢谢，都编译通过了。不过在想办法往netty里面集成了，有什么思路吗？

**Comment by knull-cn** [comment]
> 谢谢，都编译通过了。不过在想办法往netty里面集成了，有什么思路吗？

不好意思啊，这个关注不多，回复也比较慢（也许你已经搞定了吧）这个我没搞过，具体不清楚；

**Comment by Fury-Fox** [comment]
集成到netty的方法找到了。github有人上传了。发现好复杂。



fury_fox
 
发件人： knull-cn
发送时间： 2020-10-09 09:54
收件人： guanzhi/GmSSL
抄送： FuryFox; Comment
主题： Re: [guanzhi/GmSSL] win7 环境编译64位gmssl报错，perl Configure no-asm VC-WIN64A 然后nmake install,报cversion.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突 (#723)
谢谢，都编译通过了。不过在想办法往netty里面集成了，有什么思路吗？
不好意思啊，这个关注不多，回复也比较慢（也许你已经搞定了吧）这个我没搞过，具体不清楚；

**Comment by whitezdm** [comment]
> 集成到netty的方法找到了。github有人上传了。发现好复杂。 fury_fox 发件人： knull-cn 发送时间： 2020-10-09 09:54 收件人： guanzhi/GmSSL 抄送： FuryFox; Comment 主题： Re: [guanzhi/GmSSL] win7 环境编译64位gmssl报错，perl Configure no-asm VC-WIN64A 然后nmake install,报cversion.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突 (#723) 谢谢，都编译通过了。不过在想办法往netty里面集成了，有什么思路吗？ 不好意思啊，这个关注不多，回复也比较慢（也许你已经搞定了吧）这个我没搞过，具体不清楚； — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

同求一下gmssl 在netty里的集成，难呀

**Comment by Fury-Fox** [comment]
> > 集成到netty的方法找到了。github有人上传了。发现好复杂。 fury_fox 发件人： knull-cn 发送时间： 2020-10-09 09:54 收件人： guanzhi/GmSSL 抄送： FuryFox; Comment 主题： Re: [guanzhi/GmSSL] win7 环境编译64位gmssl报错，perl Configure no-asm VC-WIN64A 然后nmake install,报cversion.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突 (#723) 谢谢，都编译通过了。不过在想办法往netty里面集成了，有什么思路吗？ 不好意思啊，这个关注不多，回复也比较慢（也许你已经搞定了吧）这个我没搞过，具体不清楚； — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 同求一下gmssl 在netty里的集成，难呀

参考 https://github.com/JulongChain/julongchain-netty-infosec
