### ISSUE TITLE
iOS Gmssl:Non-public API usage:  The app references non-public symbols in  _getcontext, _makecontext, _setcontext

### ISSUE THREAD

**Issue by timeforasong** [guanzhi/GmSSL#725]
使用GMOpenSSL2.5.0，编译iOS端成功后加入工程，上传App Store后不出现构建版本，收到邮件提示Non-public API usage:  The app references non-public symbols in  _getcontext, _makecontext, _setcontext，查阅资料说是配置no-async，但是配置后未能编译成功

**Comment by timeforasong** [comment]
上传到App Store会受到苹果邮件
Non-public API usage:
The app references non-public symbols in : _getcontext, _makecontext, _setcontext
说是要禁用no-async,在config中加入no-async后各种报错

**Comment by Panda-2009** [comment]
同求 解决方案

**Comment by itollei** [comment]
@guanzhi 老师您好，我项目中也遇到这个问题，因为iOS客户端中密码键盘加密使用了SM2，我在编译时没添加no-async的情况下，可以编译成功且加解密功能也正常，但是提交审核时被拒，苹果邮件中也是说使用了_getcontext、_setcontext私有api。尝试重新编译时添加no-async后，编译就无法通过，报apps/apps.o apps/apps.c:2578:5: error: use of undeclared identifier 'OSSL_ASYNC_FD'错误，请问要如何处理？

如果其他老师有解决方案、思路，也请告知下，谢谢

**Comment by vulgarcoder** [comment]
@itollei 是否解决这个问题了
