### ISSUE TITLE
在Window下编译java接口失败

### ISSUE THREAD

**Issue by yskcoder** [guanzhi/GmSSL#731]
1.在Window下的编译和安装 成功
2.在Window下编译java接口失败，看了官网现在只能支持Mac编译java接口，想问下什么时候可以支持windows或者有作者能不能提供编译到的java动态库，谢谢
3.目前报错
![_ %A27 2F T6R%@(G{I2PEC](https://user-images.githubusercontent.com/18064302/55131235-b492c400-5158-11e9-84f8-23b410d0abbd.png)
4.试了一下linux的，环境 Centos6x86_64 make报错
![image](https://user-images.githubusercontent.com/18064302/55138471-86b87a00-516e-11e9-91b8-ebe08608e991.png)

**Comment by yskcoder** [comment]
![image](https://user-images.githubusercontent.com/18064302/55138378-3e00c100-516e-11e9-82dd-61fda2a38560.png)

**Comment by cntpro** [comment]
你用windows下的jni.h和jni_md.h替换掉jni目录中的两个文件试试

**Comment by yskcoder** [comment]
> 你用windows下的jni.h和jni_md.h替换掉jni目录中的两个文件试试

还是不可以，报错，你在windows下可以生成java版的dll文件吗，请问

**Comment by cntpro** [comment]
> > 你用windows下的jni.h和jni_md.h替换掉jni目录中的两个文件试试
> 
> 还是不可以，报错，你在windows下可以生成java版的dll文件吗，请问

可以的。
>2019-04-02  16:44             5,674 GmSSL.class
>2019-04-02  16:44            38,400 gmssljni.dll
>2019-04-02  16:42         3,772,928 libcrypto-1_1-x64.dll
>2019-01-08  14:12             1,173 winmake
编译好 libcrypto-1_1-x64.dll后，你在java目录可以试试nmake -f winmake 和nmake -f winmake test

**Comment by whutsongy** [comment]
> 你用windows下的jni.h和jni_md.h替换掉jni目录中的两个文件试试
> 
> 还是不可以，报错，你在windows下可以生成java版的dll文件吗，请问
@yskcoder 在进行GmSSL编译安装时，Java接口编译并没有一起进行编译，之前按照官方文档修改Configure文件，增加对java的编译，在Linux平台会报错。最后，我是这样处理的，希望对你有所帮助。
有gmssl全部编译安装完成之后，再单独编译java目录下的C代码和Java代码，并生成libgmssljni动态库和GmSSL.class。执行gcc对C代码进行编译，完整代码如下：
gcc -I. -I../include -Ijni -I$JAVA_HOME/include -lcrypto GmSSL.c -fPIC -shared -o libgmssljni.so
将生成的libgmssljni.so拷贝到/usr/lib64目录。
编译Java代码
javac GmSSL.java
执行Java代码，并指定动态链接库的目录
java -Djava.library.path=/usr/lib64 GmSSL

**Comment by guanzhi** [comment]
GmSSL的java部分本身是一个依赖libcrypto的JNI模块，如果你能够正确完成JNI的编译（比如某个Hello world例子），那么编译GmSSL的java不会有什么难度。反之 。。。。

**Comment by knull-cn** [comment]
最近搞blockchain支持，正好接触到。
建议你先把环境配置好，即jni目录下文件之间删除，用java库中的：makefile会指定"$(JAVA_HOME)\include" -I "$(JAVA_HOME)\include\win32"，这个就是java相关的jni的c头文件。

**Comment by zhxjgithub** [comment]
@cntpro 我也遇到相同的错误， 你是在什么环境下生成的？我是VS2017 加 jdk8.

**Comment by xinyannna** [comment]
![SWQZZ%T_EU@QI@Z3TFCQ }5](https://user-images.githubusercontent.com/72131340/94669139-6f4de480-0343-11eb-9e1e-640abc43706d.png)
