### ISSUE TITLE
请问如何编译标准TLS+sm2证书

### ISSUE THREAD

**Issue by softblade-c** [guanzhi/GmSSL#732]
你好，我的项目正好是使用SM2证书但不修改SSL/TLS协议的情况，GMSSL支持这种场景，我看代码里面使用了OPENSSL_NO_GMTLS宏开关，不知要怎么才能完整剥离GMTLS协议？尝试过在Makefile里面增加 -DOPENSSL_NO_GMTLS，编译不过。
另外，在windows下调试时，应该怎样去掉GMTLS协议？

谢谢！

**Comment by softblade-c** [comment]
现在通过宏开关关闭了GMTLS协议，但是在tls_process_server_certificate函数中报错：
error:1416F17F:SSL routines:tls_process_server_certificate:wrong certificate type
相关的代码：
```c
    i = ssl_cert_type(x, pkey);
    if (i < 0) {
        x = NULL;
        al = SSL3_AL_FATAL;
        SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
               SSL_R_UNKNOWN_CERTIFICATE_TYPE);
        goto f_err;
    }

    exp_idx = ssl_cipher_get_cert_index(s->s3->tmp.new_cipher);
    if (exp_idx >= 0 && i != exp_idx
        && (exp_idx != SSL_PKEY_GOST_EC ||
            (i != SSL_PKEY_GOST12_512 && i != SSL_PKEY_GOST12_256
             && i != SSL_PKEY_GOST01))) {
        x = NULL;
        al = SSL_AD_ILLEGAL_PARAMETER;
        SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
               SSL_R_WRONG_CERTIFICATE_TYPE);
        goto f_err;
    }
```
出错时i = 7，exp_idx=3，代码的这个地方认为不应该出现这种情况。
对于标准的TLS协议，没有国密算法，server端仍然是发过来的签名算法是ECDSA，在TLS协议中有这样的描述：
```
ECDSA algorithms  Indicates a signature algorithm using ECDSA
      [ECDSA], the corresponding curve as defined in ANSI X9.62 [X962]
      and FIPS 186-4 [DSS], and the corresponding hash algorithm as
      defined in [SHS].  
```
我理解对于标准TLS协议，ECDSA并没有限定哪种曲线，对于国密来说，只是曲线类型不一样，签名算法仍然属于ECDSA，这样可以保持协议的兼容性。在协商签名算法时，如果证书类型是sm2，签名算法是ECDSA，应该是正常的。请问在GMSSL中，是如何处理标准TLS协议下国密的握手的呢？

**Comment by needkane** [comment]
> 
> 
> 现在通过宏开关关闭了GMTLS协议，但是在tls_process_server_certificate函数中报错：
> error:1416F17F:SSL routines:tls_process_server_certificate:wrong certificate type
> 相关的代码：
> 
> ```c
>     i = ssl_cert_type(x, pkey);
>     if (i < 0) {
>         x = NULL;
>         al = SSL3_AL_FATAL;
>         SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
>                SSL_R_UNKNOWN_CERTIFICATE_TYPE);
>         goto f_err;
>     }
> 
>     exp_idx = ssl_cipher_get_cert_index(s->s3->tmp.new_cipher);
>     if (exp_idx >= 0 && i != exp_idx
>         && (exp_idx != SSL_PKEY_GOST_EC ||
>             (i != SSL_PKEY_GOST12_512 && i != SSL_PKEY_GOST12_256
>              && i != SSL_PKEY_GOST01))) {
>         x = NULL;
>         al = SSL_AD_ILLEGAL_PARAMETER;
>         SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
>                SSL_R_WRONG_CERTIFICATE_TYPE);
>         goto f_err;
>     }
> ```
> 
> 出错时i = 7，exp_idx=3，代码的这个地方认为不应该出现这种情况。
> 对于标准的TLS协议，没有国密算法，server端仍然是发过来的签名算法是ECDSA，在TLS协议中有这样的描述：
> 
> ```
> ECDSA algorithms  Indicates a signature algorithm using ECDSA
>       [ECDSA], the corresponding curve as defined in ANSI X9.62 [X962]
>       and FIPS 186-4 [DSS], and the corresponding hash algorithm as
>       defined in [SHS].  
> ```
> 
> 我理解对于标准TLS协议，ECDSA并没有限定哪种曲线，对于国密来说，只是曲线类型不一样，签名算法仍然属于ECDSA，这样可以保持协议的兼容性。在协商签名算法时，如果证书类型是sm2，签名算法是ECDSA，应该是正常的。请问在GMSSL中，是如何处理标准TLS协议下国密的握手的呢？

sm2 只能说和ecdsa类似，但不是一样的，甚至说标准形式都有些区别，sm2诞生就是为了对抗ecdsa

**Comment by softblade-c** [comment]
> > 现在通过宏开关关闭了GMTLS协议，但是在tls_process_server_certificate函数中报错：
> > error:1416F17F:SSL routines:tls_process_server_certificate:wrong certificate type
> > 相关的代码：
> > ```c
> >     i = ssl_cert_type(x, pkey);
> >     if (i < 0) {
> >         x = NULL;
> >         al = SSL3_AL_FATAL;
> >         SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
> >                SSL_R_UNKNOWN_CERTIFICATE_TYPE);
> >         goto f_err;
> >     }
> > 
> >     exp_idx = ssl_cipher_get_cert_index(s->s3->tmp.new_cipher);
> >     if (exp_idx >= 0 && i != exp_idx
> >         && (exp_idx != SSL_PKEY_GOST_EC ||
> >             (i != SSL_PKEY_GOST12_512 && i != SSL_PKEY_GOST12_256
> >              && i != SSL_PKEY_GOST01))) {
> >         x = NULL;
> >         al = SSL_AD_ILLEGAL_PARAMETER;
> >         SSLerr(SSL_F_TLS_PROCESS_SERVER_CERTIFICATE,
> >                SSL_R_WRONG_CERTIFICATE_TYPE);
> >         goto f_err;
> >     }
> > ```
> > 
> > 
> > 出错时i = 7，exp_idx=3，代码的这个地方认为不应该出现这种情况。
> > 对于标准的TLS协议，没有国密算法，server端仍然是发过来的签名算法是ECDSA，在TLS协议中有这样的描述：
> > ```
> > ECDSA algorithms  Indicates a signature algorithm using ECDSA
> >       [ECDSA], the corresponding curve as defined in ANSI X9.62 [X962]
> >       and FIPS 186-4 [DSS], and the corresponding hash algorithm as
> >       defined in [SHS].  
> > ```
> > 我理解对于标准TLS协议，ECDSA并没有限定哪种曲线，对于国密来说，只是曲线类型不一样，签名算法仍然属于ECDSA，这样可以保持协议的兼容性。在协商签名算法时，如果证书类型是sm2，签名算法是ECDSA，应该是正常的。请问在GMSSL中，是如何处理标准TLS协议下国密的握手的呢？
> 
> sm2 只能说和ecdsa类似，但不是一样的，甚至说标准形式都有些区别，sm2诞生就是为了对抗ecdsa

sm2确实和ecdsa是不一样的，但可以认为都属于椭圆曲线算法，在处理标准TLS的时候，基于现有的算法字段，只有ecdsa可选，然后根据证书类型，可以协商到对应具体曲线类型的算法。如果在标准TLS中增加sm相关的取值，协议也就不兼容了。  
下面以hyperledger fabric的go语言为例看看相应的处理。  
golang在crypto/tls/common.go中定义了SignatureScheme的取值，数值依据的是TLS协议https://tools.ietf.org/html/draft-ietf-tls-tls13-18#section-4.2.3：
```go
const (
	PKCS1WithSHA1   SignatureScheme = 0x0201
	PKCS1WithSHA256 SignatureScheme = 0x0401
	PKCS1WithSHA384 SignatureScheme = 0x0501
	PKCS1WithSHA512 SignatureScheme = 0x0601

	PSSWithSHA256 SignatureScheme = 0x0804
	PSSWithSHA384 SignatureScheme = 0x0805
	PSSWithSHA512 SignatureScheme = 0x0806

	ECDSAWithP256AndSHA256 SignatureScheme = 0x0403
	ECDSAWithP384AndSHA384 SignatureScheme = 0x0503
	ECDSAWithP521AndSHA512 SignatureScheme = 0x0603

	// Legacy signature and hash algorithms for TLS 1.2.
	ECDSAWithSHA1 SignatureScheme = 0x0203
)
```
可见里面没有国密相关的定义。如果增加国密定义，代码中其他地方做很少量的修改，也能正确完成TLS的功能。但是，如果在TLS握手消息中增加了自定义的签名方案，虽然在fabric内部通信是没有问题的，但对于外部要对接fabric的系统来说，无法和fabric协商出一致的签名算法，从而无法建立TLS连接。  
在pickSignatureAlgorithm()函数中选择签名算法的时候，是依次根据对端发过来的可用签名算法，再根据证书类型，选择和证书类型匹配的签名算法。而国密的证书类型是可以和ECDSA区分开的，然后再判断如果对端有ECDSA这种算法，就选择国密相关的算法。所以我觉得证书类型是ecdsa、证书类型是sm2，这在标准TLS+国密证书场景应该算正确的。GMSSL是如何处理这种情况呢？

**Comment by guanzhi** [comment]
GmSSL中把ECDSA、SM2、EC-Schnorr这些视为EC_KEY的可选的、不同的算法，在crypto库和ssl库都保持这个逻辑。
相反，有的实现会把SM2伪装成ECDSA在某些情况下的一个特例。

**Comment by softblade-c** [comment]
> GmSSL中把ECDSA、SM2、EC-Schnorr这些视为EC_KEY的可选的、不同的算法，在crypto库和ssl库都保持这个逻辑。
> 相反，有的实现会把SM2伪装成ECDSA在某些情况下的一个特例。

谢谢关老师回复。
目前我在Hyperledger Fabric中，已经改为和gmssl一致（原来是在TLS握手阶段把sm2当成ECDSA的一种曲线），可以顺利和gmssl client协商出正确的加密套件ECDHE-SM2-WITH-SMS4-GCM-SM3，以及sm2曲线，与gmssl自己的server和client的协商结果一致，但是在client验证ServerKeyExchange签名时失败了，暂时不清楚原因。
我看到一个issue（https://github.com/guanzhi/GmSSL/issues/712），不知您是否已经确认是问题？因为项目紧张的缘故，想知道如果是问题的话，不知什么时候可以修复？或者问题出在哪个地方？
谢谢！

**Comment by needkane** [comment]
> 
> 
> > GmSSL中把ECDSA、SM2、EC-Schnorr这些视为EC_KEY的可选的、不同的算法，在crypto库和ssl库都保持这个逻辑。
> > 相反，有的实现会把SM2伪装成ECDSA在某些情况下的一个特例。
> 
> 谢谢关老师回复。
> 目前我在Hyperledger Fabric中，已经改为和gmssl一致（原来是在TLS握手阶段把sm2当成ECDSA的一种曲线），可以顺利和gmssl client协商出正确的加密套件ECDHE-SM2-WITH-SMS4-GCM-SM3，以及sm2曲线，与gmssl自己的server和client的协商结果一致，但是在client验证ServerKeyExchange签名时失败了，暂时不清楚原因。
> 我看到一个issue（[https://github.com/guanzhi/GmSSL/issues/712），不知您是否已经确认是问题？因为项目紧张的缘故，想知道如果是问题的话，不知什么时候可以修复？或者问题出在哪个地方？](https://github.com/guanzhi/GmSSL/issues/712%EF%BC%89%EF%BC%8C%E4%B8%8D%E7%9F%A5%E6%82%A8%E6%98%AF%E5%90%A6%E5%B7%B2%E7%BB%8F%E7%A1%AE%E8%AE%A4%E6%98%AF%E9%97%AE%E9%A2%98%EF%BC%9F%E5%9B%A0%E4%B8%BA%E9%A1%B9%E7%9B%AE%E7%B4%A7%E5%BC%A0%E7%9A%84%E7%BC%98%E6%95%85%EF%BC%8C%E6%83%B3%E7%9F%A5%E9%81%93%E5%A6%82%E6%9E%9C%E6%98%AF%E9%97%AE%E9%A2%98%E7%9A%84%E8%AF%9D%EF%BC%8C%E4%B8%8D%E7%9F%A5%E4%BB%80%E4%B9%88%E6%97%B6%E5%80%99%E5%8F%AF%E4%BB%A5%E4%BF%AE%E5%A4%8D%EF%BC%9F%E6%88%96%E8%80%85%E9%97%AE%E9%A2%98%E5%87%BA%E5%9C%A8%E5%93%AA%E4%B8%AA%E5%9C%B0%E6%96%B9%EF%BC%9F)
> 谢谢！

你改服务端的同时，还需要考虑客户端，跨语言问题

“原来是在TLS握手阶段把sm2当成ECDSA的一种曲线”，个人觉得这里会有些问题，secp256k1 你可以看做是ECDSA的一种曲线，但是sm2其实除了曲线因子，里面还是有些实现与ECDSA不一样，如果只是更改曲线因子，很容易出问题
