### ISSUE TITLE
请问nginx怎么和GmSSL一起使用？

### ISSUE THREAD

**Issue by jialeens** [guanzhi/GmSSL#736]
老师，想问一下nginx怎么和GmSSL一起使用，以及证书如何生成和在nginx中配置，现在还是一头雾水。有没有相关的集成文档？

**Comment by zhaoxiaomeng** [comment]
需要把Nginx和GmSSL一起重新编译即可。
然后证书可以先用自签名的证书。

**Comment by LoadLife** [comment]
> 需要把Nginx和GmSSL一起重新编译即可。
> 然后证书可以先用自签名的证书。

Tomcat也是同理吗？很久之前我就有这个问题了

**Comment by ygm521** [comment]
想问一下nginx怎么和GmSSL一起使用，以及证书如何生成和在nginx中配置，现在还是一头雾水。

**Comment by skyStart91** [comment]
我现在也遇到apache和GmSSL不知道怎么配置的，弄了好几天了，还没弄好，用GmSSL生成好了pem证书，但是放到httpd-ssl.conf中就会报以下错误
[Thu May 16 10:51:54.065543 2019] [ssl:emerg] [pid 8136:tid 139640716625792] AH02562: Failed to configure certificate 127.0.0.1:443:0 (with chain), check /usr/local/apache/conf/cert.pem
[Thu May 16 10:51:54.065701 2019] [ssl:emerg] [pid 8136:tid 139640716625792] SSL Library Error: error:100D7010:elliptic curve routines:ECKEY_PUB_DECODE:EC lib
[Thu May 16 10:51:54.065723 2019] [ssl:emerg] [pid 8136:tid 139640716625792] SSL Library Error: error:0B07707D:x509 certificate routines:X509_PUBKEY_get:public key decode error
[Thu May 16 10:51:54.065734 2019] [ssl:emerg] [pid 8136:tid 139640716625792] SSL Library Error: error:140BF10C:SSL routines:SSL_SET_CERT:x509 lib
真的很懵，

**Comment by simongdong** [comment]
https://gist.github.com/simongdong/b011d0a010275e70c4e676c202399535.js

**Comment by ygm521** [comment]
@simongdong 你发的link不对。

**Comment by tmaccs** [comment]
同问，
http://gmssl.org/docs/ca.html 里面写的"签发的证书可以用于集成了GmSSL的Apache、Nginx等主流Web服务器。"
Apache这么集成GmSSL,
我用的httpd，还没搞明白这么一起编译。

**Comment by renshuainan** [comment]
> 
> 
> 需要把Nginx和GmSSL一起重新编译即可。
> 然后证书可以先用自签名的证书。

请问关老师有没有详细说明如何集成GMSSL至Nginx，请您费心解答具体如何使用！谢谢！
