### ISSUE TITLE
请教sm2曲线ID是在哪里定义的

### ISSUE THREAD

**Issue by softblade-c** [guanzhi/GmSSL#737]
你好，在GMSSL中，sm2p256v1定义的是30，而同济大学维护的go语言的国密算法中这个id是31。
我找了一下国密的标准，没有看到这个的定义。
在TLS的标准中，https://www.iana.org/assignments/tls-parameters/tls-parameters.xml#tls-parameters-8，30、31都已经被占用了。请问这个曲线id应该取什么才是正确的？谢谢。

**Comment by guanzhi** [comment]
国密的sm2p256v1在IANA中未注册，取什么都是错的

**Comment by yryz** [comment]
@guanzhi @softblade-c 现在有定义了：https://www.rfc-editor.org/rfc/rfc8998.html#section-2-6.1
