### ISSUE TITLE
php 使用解密问题

### ISSUE THREAD

**Issue by gz4z2b** [guanzhi/GmSSL#738]
请问openssl_open这个方法内部工作流程是什么样的呢？对方给了一个密文，一个信封密文，和一个字符串形式的私钥。对方要求的解密流程是用sm2，利用私钥解密信封密文，然后用解密出来的信封对密文用sm4进行解密。这个是不是和openssl_open这个方法一致的？如果是字符串形式的私钥怎么导出成为$prikey的形式？

**Comment by guanzhi** [comment]
openssl_open 是 EVP_Open系列函数的封装，可以man EVP_OpenInit 来了解其功能。
大致是用SM4密钥对数据加密，再用SM2公钥对SM4密钥加密。
具体PHP的实现以及对私钥的表示请参考PHP的OpenSSL手册以及本想木 php/ext/openssl 下面的代码
