### ISSUE TITLE
咨询：openvpn 2.4.6集成GmSSL 2.5.0

### ISSUE THREAD

**Issue by jadeCheng2017** [guanzhi/GmSSL#739]
**Describe the bug**
**ubuntu 16.04，gsmssl 和 openvpn均编译正常，gmssl和openssl命令行可以正常执行，但是openvpn启动时，提示如下错误：**
jade@jade-u18:~/work/code$ openvpn --version
openvpn: /usr/lib/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn)
openvpn: /usr/lib/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn)
jade@jade-u18:~/work/code$ openvpn --help
openvpn: /usr/lib/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn)
openvpn: /usr/lib/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn)

**gmssl编译命令：**
./config shared --prefix=/usr --openssldir=/usr/lib/openssl
make
sudo make install

**libcrypto和libssl的so在/usr/lib目录下：**
jade@jade-u18:~/work/code$ ll /usr/lib/libcrypto.*
-rw-r--r-- 1 root root 6340296 4月   8 21:25 /usr/lib/libcrypto.a
lrwxrwxrwx 1 root root      16 4月   8 21:25 /usr/lib/libcrypto.so -> libcrypto.so.1.1*
-rwxr-xr-x 1 root root 3713272 4月   8 21:38 /usr/lib/libcrypto.so.1.1*
-rwxr-xr-x 1 root root 3713272 4月   8 21:27 /usr/lib/libcrypto.so.1.1_gmssl*
jade@jade-u18:~/work/code$ ll /usr/lib/libssl.*
-rw-r--r-- 1 root root 841468 4月   8 21:25 /usr/lib/libssl.a
lrwxrwxrwx 1 root root     13 4月   8 21:25 /usr/lib/libssl.so -> libssl.so.1.1*
-rwxr-xr-x 1 root root 566304 4月   8 21:32 /usr/lib/libssl.so.1.1*
-rwxr-xr-x 1 root root 566304 4月   8 21:27 /usr/lib/libssl.so.1.1_gmssl*

**# openssl命令行可以执行：**
jade@jade-u18:~/work/code$ openssl version
GmSSL 2.5.0 - OpenSSL 1.1.0d  28 Feb 2019
jade@jade-u18:~/work/code$ openssl enc -help
Usage: enc [options]
Valid options are:
 -help          Display this summary
 -ciphers       List ciphers
 -in infile     Input file
 -out outfile   Output file

**#gmssl命令行可以正常执行：**
jade@jade-u18:~/work/code$ gmssl version
GmSSL 2.5.0 - OpenSSL 1.1.0d  28 Feb 2019
jade@jade-u18:~/work/code$ gmssl enc -help
Usage: enc [options]
Valid options are:
 -help          Display this summary
 -ciphers       List ciphers
 -in infile     Input file

请指教，多谢。
如需要其他信息，我再补充。

**Comment by guanzhi** [comment]
你这个是链接错误，openvpn没有正确链接到gmssl

**Comment by GT119119** [comment]
我也遇到过这个问题 记得是重启系统就好了

**Comment by syr-1** [comment]
> **Describe the bug** **ubuntu 16.04，gsmssl 和 openvpn均编译正常，gmssl和openssl命令行可以正常执行，但是openvpn启动时，提示如下错误：** jade@jade-u18:~/work/code$ openvpn --version openvpn: /usr/lib/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn) openvpn: /usr/lib/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn) jade@jade-u18:~/work/code$ openvpn --help openvpn: /usr/lib/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn) openvpn: /usr/lib/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by openvpn)
> 
> **gmssl编译命令：** ./config shared --prefix=/usr --openssldir=/usr/lib/openssl make sudo make install
> 
> **libcrypto和libssl的so在/usr/lib目录下：** jade@jade-u18:~/work/code$ ll /usr/lib/libcrypto.* -rw-r--r-- 1 root root 6340296 4月 8 21:25 /usr/lib/libcrypto.a lrwxrwxrwx 1 root root 16 4月 8 21:25 /usr/lib/libcrypto.so -> libcrypto.so.1.1* -rwxr-xr-x 1 root root 3713272 4月 8 21:38 /usr/lib/libcrypto.so.1.1* -rwxr-xr-x 1 root root 3713272 4月 8 21:27 /usr/lib/libcrypto.so.1.1_gmssl* jade@jade-u18:~/work/code$ ll /usr/lib/libssl.* -rw-r--r-- 1 root root 841468 4月 8 21:25 /usr/lib/libssl.a lrwxrwxrwx 1 root root 13 4月 8 21:25 /usr/lib/libssl.so -> libssl.so.1.1* -rwxr-xr-x 1 root root 566304 4月 8 21:32 /usr/lib/libssl.so.1.1* -rwxr-xr-x 1 root root 566304 4月 8 21:27 /usr/lib/libssl.so.1.1_gmssl*
> 
> **# openssl命令行可以执行：** jade@jade-u18:~/work/code$ openssl version GmSSL 2.5.0 - OpenSSL 1.1.0d 28 Feb 2019 jade@jade-u18:~/work/code$ openssl enc -help Usage: enc [options] Valid options are: -help Display this summary -ciphers List ciphers -in infile Input file -out outfile Output file
> 
> **#gmssl命令行可以正常执行：** jade@jade-u18:~/work/code$ gmssl version GmSSL 2.5.0 - OpenSSL 1.1.0d 28 Feb 2019 jade@jade-u18:~/work/code$ gmssl enc -help Usage: enc [options] Valid options are: -help Display this summary -ciphers List ciphers -in infile Input file
> 
> 请指教，多谢。 如需要其他信息，我再补充。

请问这个问题解决了吗？如果解决了，还想请教一下怎么解决的？
