### ISSUE TITLE
gmssl-1.3.0.tar.gz下载

### ISSUE THREAD

**Issue by cophey** [guanzhi/GmSSL#74]
为何没有gmssl-1.3.0.tar.gz分支下载链接呢？

**Comment by cophey** [comment]
![koyrbu 4f c1p 4y q9 t7](https://cloud.githubusercontent.com/assets/7555270/22062034/a47e1888-ddb2-11e6-84ad-bf6a58b0f11d.png)

如图，用master版本和v1.2.1版本，都出现这个问题，求帮忙解决

**Comment by guanzhi** [comment]
还有些小bug，1.3实际上就是目前的master。
另外你的截图不太清楚，你也没有描述到底遇到了什么问题

**Comment by cophey** [comment]
按照以下命令进行安装，安装后没有gmssl工具
`$ ./config
$ make
$ sudo make install`

**Comment by cophey** [comment]
![image](https://cloud.githubusercontent.com/assets/7555270/22096620/95a797ee-de57-11e6-88e9-b575394199d8.png)

**Comment by cophey** [comment]
make过程中出现上图问题，应该有好多这种问题，我的是ubuntu-1404 3.13.0-86-generic的系统

**Comment by LiTianjue** [comment]
你这是什么问题，根本看不到问题啊。。。。

**Comment by gujinqiangggs** [comment]
@LiTianjue 我怀疑他的意思是编译完成了，但是直接运行gmssl提示:-bash: gmssl: command not found，然后以为是编译过程中出现的Warnning导致。 @cophey 如果编译完成，是上述原因的话，直接在profile里export PATH=$PATH:/usr/local/ssl/bin 应该就可以了。

**Comment by andylau004** [comment]
gmssl: command not found


环境变量添加下既可以。
添加完成后 记得 source /etc/profile

**Comment by cophey** [comment]
谢谢各位！就是环境变量的问题！
