### ISSUE TITLE
关于配置过程中去掉不需要的模块

### ISSUE THREAD

**Issue by SaylovEU** [guanzhi/GmSSL#740]
关老师，你好！我刚刚接触Gmssl，我在Ubuntu上参照wiki试过了它的各个功能。现在，我想在我们自己的嵌入式开发板上运行gmssl试试效果。因为我们的文件系统大小有限，我需要编译一份尽可能小的同时能够支持国密SM2/SM3/SM4算法的Gmssl。但是我在配置的时候，对各个模块不熟悉，试了很多配置，目前静态编译出来的Gmssl，strip完了之后最小为3M，依然无法放到我们的文件系统上。请问，你能给个详细的配置命令，让我配置一份尽可能小同时支持国密SM2/SM3/SM4算法的Gmssl吗？

**Comment by guanzhi** [comment]
1. 保留或者禁用哪些模块跟你的应用需求有关
2. 提供特殊的剪裁和编译需要收费
3. 保留SM2/3/4和证书等核心功能，去掉无关算法，大约可以将libcrypto缩小至1.7MB左右，进一步缩小可能会比较困难
