### ISSUE TITLE
Mac下编译Android目标文件报错

### ISSUE THREAD

**Issue by ciqinga123** [guanzhi/GmSSL#741]
关老师，我在Mac下按照官方文档编译Android目标文件，编译出错，希望您百忙之中抽出点时间帮我解惑，不胜感激！

以下是问题描述：

按照官方文档执行命令：

> 
---------------------
ANDROID_PATH=/Users/zhangguanjun/Library/Android
PLATFORM_VERSION=22

MAKE_TOOLCHAIN=$ANDROID_PATH/sdk/ndk-bundle/build/tools/make-standalone-toolchain.sh
export TOOLCHAIN_PATH=$ANDROID_PATH/android-toolchain-arm
$MAKE_TOOLCHAIN --arch=arm --platform=android-$PLATFORM_VERSION --install-dir=$TOOLCHAIN_PATH

export MACHINE=armv7
export SYSTEM=android
export ARCH=arm
export CROSS_SYSROOT=$TOOLCHAIN_PATH/sysroot
export TOOL_BASENAME=$TOOLCHAIN_PATH/bin/arm-linux-androideabi
export CC=$TOOL_BASENAME-gcc
export CXX=$TOOL_BASENAME-g++
export LD=$TOOL_BASENAME-ld
export LINK=$CXX
export AR=$TOOL_BASENAME-ar
export RANLIB=$TOOL_BASENAME-ranlib
export STRIP=$TOOL_BASENAME-strip

./config
make

------------------------

Configure文件中

`
config{dirs} = [ "crypto", "ssl", "engines", "apps", "util", "tools", "fuzz", "test" ];

可编译通过，不报错
`

但是改为官方文档中的：

`
config{dirs} = [ "crypto", "ssl", "engines", "apps", "util", "tools", "fuzz", "test", "java" ];
`
则会报错

错误信息-error info：

> 

clang80: warning: argument unused during compilation: '-Wa,--noexecstack' [-Wunused-command-line-argument]
/Users/zhangguanjun/Library/Android/android-toolchain-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: gmssljni.map:1:1: syntax error, unexpected $end, expecting STRING or QUOTED_STRING or '{'
/Users/zhangguanjun/Library/Android/android-toolchain-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: unable to parse version script file gmssljni.map
clang80: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_shlib.linux-shared] Error 1
make[1]: *** [libgmssljni.so] Error 2
make: *** [all] Error 2

> 

----------------------

Environments:

- OS: macos 10.13

- Compiler:
           NDK r19c-darwin-X86_64

**Comment by guanzhi** [comment]
java 只在Linux/Mac环境下可用。
Android需要根据NDK的要求编译，因为Android NDK的变化略频繁，我们提供的说明未必适合当前版本。一般严格参考Google Android NDK文档一步步配置环境和编译，都能比较顺利编译成功。

**Comment by ciqinga123** [comment]
👌，谢谢老师回复，我去试一下
