### ISSUE TITLE
golang能否支持私钥输出为文本，文本反推私钥

### ISSUE THREAD

**Issue by needkane** [guanzhi/GmSSL#743]
**Is your feature request related to a problem? Please describe.**
目前GetText方式，无法反推私钥
GetPEM方式，然后根据PEM内容，调用NewPrivateKeyFromPEM，必须双方填写一致密码，而且PEM内容较长

**Describe the solution you'd like**
希望可以有更便捷的方式，可以将私钥内容转换成string或者[]byte，同时可以反推出私钥

**Describe alternatives you've considered**

**Additional context**

**Comment by guanzhi** [comment]
默认私钥以PEM和PKCS #8口令加密的方式存储在磁盘上，也就是所谓的私钥不落地。
“便捷”的方法容易导致不安全的行为。

**Comment by needkane** [comment]
> 
> 
> 默认私钥以PEM和PKCS #8口令加密的方式存储在磁盘上，也就是所谓的私钥不落地。
> “便捷”的方法容易导致不安全的行为。

**Comment by needkane** [comment]
> 
> 
> 默认私钥以PEM和PKCS #8口令加密的方式存储在磁盘上，也就是所谓的私钥不落地。
> “便捷”的方法容易导致不安全的行为。

麻烦看下pr：https://github.com/guanzhi/GmSSL/pull/734
