### ISSUE TITLE
SM9 私钥导出公钥时，崩溃

### ISSUE THREAD

**Issue by mskj-zhangxiangsheng** [guanzhi/GmSSL#744]
在IPhone模拟器上(x86_64) 调用 SM9PrivateKey_get_public_key 函数时崩溃
Thread 1: EXC_BAD_ACCESS (code=1, address=0x4)

<img width="330" alt="屏幕快照 2019-04-12 下午5 20 01" src="https://user-images.githubusercontent.com/10367702/56026703-4f89c180-5d47-11e9-8bcc-0f1ccc6eda90.png">
<img width="523" alt="屏幕快照 2019-04-12 下午5 20 33" src="https://user-images.githubusercontent.com/10367702/56026709-5284b200-5d47-11e9-8d6f-67819b64272a.png">

**Additional context**
我的代码如下
```C
    SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
                                                                NID_sm9sign,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
                                                                NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
                                                                );
    
    SM9PrivateKey * privateKey = SM9_extract_private_key(masterSecret, "123456", 6);
    SM9PublicKey * publicKey = SM9PrivateKey_get_public_key(privateKey);
```

**Comment by son012** [comment]
> 在IPhone模拟器上(x86_64) 调用 SM9PrivateKey_get_public_key 函数时崩溃
> Thread 1: EXC_BAD_ACCESS (code=1, address=0x4)
> 
> <img alt="屏幕快照 2019-04-12 下午5 20 01" width="330" src="https://user-images.githubusercontent.com/10367702/56026703-4f89c180-5d47-11e9-8bcc-0f1ccc6eda90.png">
> 
> <img alt="屏幕快照 2019-04-12 下午5 20 33" width="523" src="https://user-images.githubusercontent.com/10367702/56026709-5284b200-5d47-11e9-8d6f-67819b64272a.png">
> 
> **Additional context**
> 我的代码如下
> 
> ```c
>     SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
>                                                                 NID_sm9sign,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
>                                                                 NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
>                                                                 );
>     
>     SM9PrivateKey * privateKey = SM9_extract_private_key(masterSecret, "123456", 6);
>     SM9PublicKey * publicKey = SM9PrivateKey_get_public_key(privateKey);
> ```

你好,我看到你这边已经换成sm9数据加密了,能否告知怎么确认两方产生的密钥MSKA MSKB是一样的呢,我这边就差最后解码的时候校验失败,一直提示evp lib

**Comment by holdsky** [comment]
https://github.com/guanzhi/GmSSL/issues/748

**Comment by holdsky** [comment]
#748

由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
这个协议不支持A和B来自不同的PKG
https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG

**Comment by son012** [comment]
> #748
> 
> 由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
> 这个协议不支持A和B来自不同的PKG
> https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG

这个连接我打不开，是需要科学么

**Comment by holdsky** [comment]
> > #748
> > 由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
> > 这个协议不支持A和B来自不同的PKG
> > https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG
> 
> 这个连接我打不开，是需要科学么

时好时不好，这是他们搭建的一个测试服务。

**Comment by holdsky** [comment]
> > #748
> > 由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
> > 这个协议不支持A和B来自不同的PKG
> > https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG
> 
> 这个连接我打不开，是需要科学么

自己生成主密钥

   SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
                                                                sm9_scheme,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
                                                                NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
                                                                );

**Comment by son012** [comment]
> > > #748
> > > 由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
> > > 这个协议不支持A和B来自不同的PKG
> > > https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG
> > 
> > 
> > 这个连接我打不开，是需要科学么
> 
> 自己生成主密钥
> 
> ```c
>  SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
>                                                                 sm9_scheme,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
>                                                                 NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
>                                                                 );
> ```
这个主密钥的生成是随机的还是固定的，我这边通过调用sm9_setup函数生成的主密钥，但是我是网络传输，我现在两边都调用了setup函数，但是校验数据 mac的时候就出错了

**Comment by holdsky** [comment]
> > > > #748
> > > > 由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
> > > > 这个协议不支持A和B来自不同的PKG
> > > > https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG
> > > 
> > > 
> > > 这个连接我打不开，是需要科学么
> > 
> > 
> > 自己生成主密钥
> > ```c
> >  SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
> >                                                                 sm9_scheme,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
> >                                                                 NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
> >                                                                 );
> > ```
> 
> 这个主密钥的生成是随机的还是固定的，我这边通过调用sm9_setup函数生成的主密钥，但是我是网络传输，我现在两边都调用了setup函数，但是校验数据 mac的时候就出错了

SM9的密钥交换是这样的
1、SM9的密钥，分为主密钥，公钥、私钥；其中，主密钥由类似CA的机构持有（目前，你可以自己持有）
2、私钥均由主密钥中导出，公钥由私钥导出；主密钥可以导出多组公私钥对。通信双方持有不同的公私钥对
3、例如，主密钥Master，导出公私钥对KeyPairA和KeyPairB；
4、通信方A持有公私钥KeyPairA，通信方B持有KeyPairB。机构持有Master（目前，你自己就是机构）
5、通信方A和通信方B按照规定的步骤进行密钥交换即可

SM9其实包含：签名和验签，密钥封装和解封，加密和解密，密钥交换

**Comment by guanzhi** [comment]
sm9.gmssl.org 目前在我们自己的机房内，不稳定主要原因是校内网络的问题
后期可能会转移至阿里云（存在安全问题，阿里云可以拿到主密钥）
或者以物理主机的方式托管出去

**Comment by wangxj4268** [comment]
> 在IPhone模拟器上(x86_64) 调用 SM9PrivateKey_get_public_key 函数时崩溃
> Thread 1: EXC_BAD_ACCESS (code=1, address=0x4)
> 
> <img alt="屏幕快照 2019-04-12 下午5 20 01" width="330" src="https://user-images.githubusercontent.com/10367702/56026703-4f89c180-5d47-11e9-8bcc-0f1ccc6eda90.png">
> 
> <img alt="屏幕快照 2019-04-12 下午5 20 33" width="523" src="https://user-images.githubusercontent.com/10367702/56026709-5284b200-5d47-11e9-8d6f-67819b64272a.png">
> 
> **Additional context**
> 我的代码如下
> 
> ```c
>     SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
>                                                                 NID_sm9sign,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
>                                                                 NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
>                                                                 );
>     
>     SM9PrivateKey * privateKey = SM9_extract_private_key(masterSecret, "123456", 6);
>     SM9PublicKey * publicKey = SM9PrivateKey_get_public_key(privateKey);
> ```

你好，请问你这边有找到关于SM9用法的文档么，或者SM9的Demo也行，我也是做iOS开发的，关于SM9怎么调用不太明白，求教...

**Comment by mskj-zhangxiangsheng** [comment]
> > 在IPhone模拟器上(x86_64) 调用 SM9PrivateKey_get_public_key 函数时崩溃
> > Thread 1: EXC_BAD_ACCESS (code=1, address=0x4)
> > <img alt="屏幕快照 2019-04-12 下午5 20 01" width="330" src="https://user-images.githubusercontent.com/10367702/56026703-4f89c180-5d47-11e9-8bcc-0f1ccc6eda90.png">
> > <img alt="屏幕快照 2019-04-12 下午5 20 33" width="523" src="https://user-images.githubusercontent.com/10367702/56026709-5284b200-5d47-11e9-8d6f-67819b64272a.png">
> > **Additional context**
> > 我的代码如下
> > ```c
> >     SM9MasterSecret * masterSecret = SM9_generate_master_secret(NID_sm9bn256v1 ,//pairing
> >                                                                 NID_sm9sign,/*scheme  NID_[sm9sign | sm9encrypt | sm9keyagreement] */
> >                                                                 NID_sm9hash1_with_sm3 /* hash1  NID_sm9hash1_with_[sm3 | sha256] */
> >                                                                 );
> >     
> >     SM9PrivateKey * privateKey = SM9_extract_private_key(masterSecret, "123456", 6);
> >     SM9PublicKey * publicKey = SM9PrivateKey_get_public_key(privateKey);
> > ```
> 
> 你好，请问你这边有找到关于SM9用法的文档么，或者SM9的Demo也行，我也是做iOS开发的，关于SM9怎么调用不太明白，求教...

SM9的密钥交换是这样的
1、SM9的密钥，分为主密钥，公钥、私钥；其中，主密钥由类似CA的机构持有（目前，你可以自己持有）
2、私钥均由主密钥中导出，公钥由私钥导出；主密钥可以导出多组公私钥对。通信双方持有不同的公私钥对
3、例如，主密钥Master，导出公私钥对KeyPairA和KeyPairB；
4、通信方A持有公私钥KeyPairA，通信方B持有KeyPairB。机构持有Master（目前，你自己就是机构）
5、通信方A和通信方B按照规定的步骤进行密钥交换即可

SM9其实包含：签名和验签，密钥封装和解封，加密和解密，密钥交换。
密钥交换部分，不要使用GmSSL中给的示例，它那个示例仅仅步骤上示例，不能实际应用。
