### ISSUE TITLE
openvpn集成GmSSL，openvpn错误提示The server has no TLS ciphersuites in common with the client

### ISSUE THREAD

**Issue by Po1lux** [guanzhi/GmSSL#745]
openvpn 2.4.6
GmSSL 2.5.0
在服务端客户端配置文件配置，指定密码套件
tls-cipher ECDHE-SM2-WITH-SMS4-SM3
然后握手失败，服务端错误提示
TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.
如果不指定密码套件，抓包查看clientHello中的密码套件
![image](https://user-images.githubusercontent.com/20920394/56088033-a6f47280-5eaa-11e9-9b65-11b8bd2ee76b.png)
但是服务端还是提示上述错误
想通过修改openvpn实现双证书，现在想测试下单证书，遇到上述问题，还请指点一下，谢谢！

**Comment by Po1lux** [comment]
解决了...之前证书的生成用的gmssl的，出现这个问题，看这个连接https://if2007.github.io/2018/06/07/gmssl_s_client_s_server_handshake_sm2_sm4_sm3/
握手时也和我出现了一样的问题，换成tassl的证书后，就可以正常握手了

**Comment by guanzhi** [comment]
用gmssl生成的证书完全可以用于gmssl加持后的openvpn，而且有重要行业用户已经在他们的系统里用了openvpn + gmssl + skf engine + TF SKF卡这个组合了。只要编译一下，就可以申请二级资质了。

**Comment by cklxmu** [comment]
实测，用GmSSL-master/apps/gmca/test.sh 脚本生成的证书，是没问题的。把 GmSSL-master/apps/gmca/.ca/cacert.pem 作为CA证书，把 GmSSL-master/apps/gmca/.ca/certs/01.pem 作为server端证书，把 GmSSL-master/apps/gmca/.ca/keys/alice@pku.edu.cn.key 作为server端的私钥。
用 openvpn-2.4.8 + gmssl-2.5.4 验证了是可以的。

**Comment by Pirate17** [comment]
> 实测，用GmSSL-master/apps/gmca/test.sh 脚本生成的证书，是没问题的。把 GmSSL-master/apps/gmca/.ca/cacert.pem 作为CA证书，把 GmSSL-master/apps/gmca/.ca/certs/01.pem 作为server端证书，把 GmSSL-master/apps/gmca/.ca/keys/alice@pku.edu.cn.key 作为server端的私钥。
> 用 openvpn-2.4.8 + gmssl-2.5.4 验证了是可以的。

请教一下，openvpn如何使用gmssl国密加密套件？
