### ISSUE TITLE
GmSSL.java 中调用公钥加密 publicKeyEncrypt() 方法崩溃

### ISSUE THREAD

**Issue by ciqinga123** [guanzhi/GmSSL#746]
关老师您好，我在调试Java接口的时候，调用GmSLL.java类中的公钥加密publicKeyEncrypt()方法时，方法出错导致应用崩溃。应用中错误信息为

`
E/HAL: load: id=gralloc != hmi->id=gralloc
`

无法准确定位问题，期待老师解惑！

**Comment by guanzhi** [comment]
我猜你可能输入的数据太长了

**Comment by ciqinga123** [comment]
> 我猜你可能输入的数据太长了

下面是GmSLL.java中的代码示例
`
int i;
        GmSSL gmssl = GmSSL.getInstance();
        byte[] dgst = gmssl.digest("SM3", "abc".getBytes());

        byte[] sm2PrivateKey = new byte[] {
                (byte)0x30,(byte)0x77,(byte)0x02,(byte)0x01,(byte)0x01,(byte)0x04,(byte)0x20,(byte)0x28,
                (byte)0x7d,(byte)0x3f,(byte)0xb9,(byte)0xf4,(byte)0xbb,(byte)0xc8,(byte)0xbd,(byte)0xe1,
                (byte)0x54,(byte)0x75,(byte)0x87,(byte)0x9f,(byte)0x08,(byte)0x61,(byte)0x20,(byte)0xe3,
                (byte)0x65,(byte)0xf8,(byte)0xb2,(byte)0xca,(byte)0x14,(byte)0x26,(byte)0x81,(byte)0xf6,
                (byte)0x1e,(byte)0xd8,(byte)0x7f,(byte)0xc0,(byte)0x66,(byte)0x20,(byte)0x29,(byte)0xa0,
                (byte)0x0a,(byte)0x06,(byte)0x08,(byte)0x2a,(byte)0x81,(byte)0x1c,(byte)0xcf,(byte)0x55,
                (byte)0x01,(byte)0x82,(byte)0x2d,(byte)0xa1,(byte)0x44,(byte)0x03,(byte)0x42,(byte)0x00,
                (byte)0x04,(byte)0xb1,(byte)0x1e,(byte)0x4c,(byte)0x8c,(byte)0xa9,(byte)0x02,(byte)0xf2,
                (byte)0x8d,(byte)0x8b,(byte)0x98,(byte)0xd2,(byte)0xd0,(byte)0xc4,(byte)0xf1,(byte)0x60,
                (byte)0x91,(byte)0xfb,(byte)0x61,(byte)0x62,(byte)0x00,(byte)0xcf,(byte)0x93,(byte)0x4e,
                (byte)0x3f,(byte)0xca,(byte)0xfd,(byte)0xf7,(byte)0x9d,(byte)0x76,(byte)0xb8,(byte)0x2b,
                (byte)0xb3,(byte)0x30,(byte)0x98,(byte)0x65,(byte)0xf5,(byte)0x12,(byte)0xab,(byte)0x45,
                (byte)0x78,(byte)0x29,(byte)0x87,(byte)0xdc,(byte)0x74,(byte)0x07,(byte)0x75,(byte)0xd0,
                (byte)0x68,(byte)0xad,(byte)0x85,(byte)0x71,(byte)0x08,(byte)0xc2,(byte)0x19,(byte)0xf0,
                (byte)0xf4,(byte)0xca,(byte)0x6e,(byte)0xe1,(byte)0xea,(byte)0x86,(byte)0xe6,(byte)0x21,
                (byte)0x76};

        byte[] sm2PublicKey = new byte[] {
                (byte)0x30,(byte)0x59,(byte)0x30,(byte)0x13,(byte)0x06,(byte)0x07,(byte)0x2a,(byte)0x86,
                (byte)0x48,(byte)0xce,(byte)0x3d,(byte)0x02,(byte)0x01,(byte)0x06,(byte)0x08,(byte)0x2a,
                (byte)0x81,(byte)0x1c,(byte)0xcf,(byte)0x55,(byte)0x01,(byte)0x82,(byte)0x2d,(byte)0x03,
                (byte)0x42,(byte)0x00,(byte)0x04,(byte)0xb1,(byte)0x1e,(byte)0x4c,(byte)0x8c,(byte)0xa9,
                (byte)0x02,(byte)0xf2,(byte)0x8d,(byte)0x8b,(byte)0x98,(byte)0xd2,(byte)0xd0,(byte)0xc4,
                (byte)0xf1,(byte)0x60,(byte)0x91,(byte)0xfb,(byte)0x61,(byte)0x62,(byte)0x00,(byte)0xcf,
                (byte)0x93,(byte)0x4e,(byte)0x3f,(byte)0xca,(byte)0xfd,(byte)0xf7,(byte)0x9d,(byte)0x76,
                (byte)0xb8,(byte)0x2b,(byte)0xb3,(byte)0x30,(byte)0x98,(byte)0x65,(byte)0xf5,(byte)0x12,
                (byte)0xab,(byte)0x45,(byte)0x78,(byte)0x29,(byte)0x87,(byte)0xdc,(byte)0x74,(byte)0x07,
                (byte)0x75,(byte)0xd0,(byte)0x68,(byte)0xad,(byte)0x85,(byte)0x71,(byte)0x08,(byte)0xc2,
                (byte)0x19,(byte)0xf0,(byte)0xf4,(byte)0xca,(byte)0x6e,(byte)0xe1,(byte)0xea,(byte)0x86,
                (byte)0xe6,(byte)0x21,(byte)0x76};

        byte[] sig = gmssl.sign("sm2sign", dgst, sm2PrivateKey);
        Log.i(TAG, "SM2 Signature : ");
        for (i = 0; i < sig.length; i++) {
            System.out.printf("%02X", sig[i]);
        }
        Log.i(TAG, "\n");

        int vret = gmssl.verify("sm2sign", dgst, sig, sm2PublicKey);
        Log.i(TAG, "Verification result = " + vret);

        byte[] sm2Ciphertext = gmssl.publicKeyEncrypt("sm2encrypt-with-sm3", dgst, sm2PublicKey);
`

我在GmSSL.c中加入了log，去定位错误的位置，log输出如下：

`
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 0 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 1 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 2 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 3 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 4 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 5 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 6 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 6 
04-18 14:03:58.977 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 7 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 8 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 9 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 10 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 11 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 12 
04-18 14:03:58.978 5457-5457/? I/GmSSL_Test: Java_GmSSL_publicKeyEncrypt ----------- 13 
`

GmSSL.c中，publicKeyEncrypt方法中，引发崩溃前后的代码如下：

`
	if (pkey_type == EVP_PKEY_EC) {
#if !defined(OPENSSL_NO_ECIES) || !defined(OPENSSL_NO_SM2)
		if (!EVP_PKEY_CTX_set_ec_scheme(pkctx, ec_scheme)) {
			JNIerr(JNI_F_JAVA_GMSSL_PUBLICKEYENCRYPT, ERR_R_EC_LIB);
			goto end;
		}
		LOGI("Java_GmSSL_publicKeyEncrypt ----------- 12 ");
		if (!EVP_PKEY_CTX_set_ec_encrypt_param(pkctx, ec_encrypt_param)) {
			JNIerr(JNI_F_JAVA_GMSSL_PUBLICKEYENCRYPT, ERR_R_EC_LIB);
			goto end;
		}
		LOGI("Java_GmSSL_publicKeyEncrypt ----------- 13 ");
#endif
	}

# 在此发生崩溃，加密失败
	if (EVP_PKEY_encrypt(pkctx, outbuf, &outlen, inbuf, inlen) <= 0) {
		JNIerr(JNI_F_JAVA_GMSSL_PUBLICKEYENCRYPT, ERR_R_EVP_LIB);
		goto end;
	}
LOGI("Java_GmSSL_publicKeyEncrypt ----------- 14 ");
	if (!(ret = (*env)->NewByteArray(env, outlen))) {
		JNIerr(JNI_F_JAVA_GMSSL_PUBLICKEYENCRYPT, JNI_R_JNI_MALLOC_FAILURE);
		goto end;
	}
LOGI("Java_GmSSL_publicKeyEncrypt ----------- 15 ");
	(*env)->SetByteArrayRegion(env, ret, 0, outlen, (jbyte *)outbuf);

`

关老师，这样能定位出问题吗？
