### ISSUE TITLE
SM9 not implement

### ISSUE THREAD

**Issue by rain2fog** [guanzhi/GmSSL#747]
SM9到底实现没实现啊？公司老板想用，如果SM9还没实现，那就得砍掉了。

运行GmSSL的SM9时提示未实现.....

```
root@os-dev:~/GmSSL# gmssl
GmSSL> sm9
sm9 not implemented
GmSSL> exit
root@os-dev:~/GmSSL# gmssl sm9
sm9 not implemented

```

**Comment by holdsky** [comment]
实现了一部分，签名、封装、加密；密钥交换不确定，感觉密钥交换没有实现

**Comment by guanzhi** [comment]
1. SM9的C API已经全部实现了，这个API在功能覆盖上是非常不错的，包括SM9公开参数、口令加密私钥等非常有用的功能都已经实现了，可以说对应用来说是非常友好的。
2. SM9的`pkey` `pkeyutl`命令行接口实现了除密钥生成之外的功能
3. SM9专有的`sm9` `sm9utl` 可能未完全实现

GmSSL一直在更新中，具体哪些功能实现了没有以源代码为准。

**Comment by needkane** [comment]
> 
> 
>     1. SM9的C API已经全部实现了，这个API在功能覆盖上是非常不错的，包括SM9公开参数、口令加密私钥等非常有用的功能都已经实现了，可以说对应用来说是非常友好的。
> 
>     2. SM9的`pkey` `pkeyutl`命令行接口实现了除密钥生成之外的功能
> 
>     3. SM9专有的`sm9` `sm9utl` 可能未完全实现
> 
> 
> GmSSL一直在更新中，具体哪些功能实现了没有以源代码为准。

麻烦看下PR：https://github.com/guanzhi/GmSSL/pull/734
