### ISSUE TITLE
SM9 密钥交换的API设计是否完成？

### ISSUE THREAD

**Issue by holdsky** [guanzhi/GmSSL#748]
在文件 test/sm9test.c 中，学习SM9密钥交换的api使用，没弄明白是否使用了SM9公钥
342-347行，方法sm9test_exch
``` C
if (!SM9_setup(NID_sm9bn256v1, NID_sm9keyagreement, NID_sm9hash1_with_sm3, &mpk, &msk)
		|| !(skA = SM9_extract_private_key(msk, idA, strlen(idA)))
		|| !(skB = SM9_extract_private_key(msk, idB, strlen(idB)))) {
		ERR_print_errors_fp(stderr);
		goto end;
	}
```
发起方的私钥skA，响应方的私钥skB都是从同一个主密钥msk中导出的。
我比较疑惑的是：在实际的网络通信中，发起方A和响应方B是如何共同拥有主密钥msk的？
我实际测试的结果是：如果skA，skB从不同的主密钥中导出，那么发起方和响应方密钥交换不成功。

**Comment by guanzhi** [comment]
由一个类似CA的机构PKG持有msk，A和B要到共同的这个机构申请各自的私钥
这个协议不支持A和B来自不同的PKG
https://sm9.gmssl.org:8888 可以参考这个以邮件为ID的PKG
