### ISSUE TITLE
skf.cfg文件应放在那个路径下，需要配置哪些地方

### ISSUE THREAD

**Issue by rollie123** [guanzhi/GmSSL#749]
你好，我编译完后用调用key国标接口生成csr，发现需要用到-config skf.cfg，请问skf.cfg应该放到哪个目录下（LINUX系统），然后需要配置哪些文件，谢谢。

**Comment by guanzhi** [comment]
放在哪个目录下都可以，配置文件是需要通过`-config`来显式指定路径的。

**Comment by rollie123** [comment]
你好，我执行下面的命令报错，我编译的时候执行了./config enable-skfeng
[root@localhost sm2cert]# gmssl req -new -sm3 -subj "/C=CN/ST=BJ/L=BJ/O=PKU/OU=Sign/CN=AKTest" -keyform engine -keygen_engine skf -engine skf -key sm2.sign -config /usr/local/ssl/skf.cnf -out csr.pem
Can't find keygen engine req
req: Use -help for summary.
139882942162752:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/local/lib64/engines-1.1/skf.so): /usr/local/lib64/engines-1.1/skf.so: undefined symbol: bio_err
139882942162752:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
139882942162752:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
139882942162752:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=skf

**Comment by guanzhi** [comment]
Github的分支上没有SKF引擎的代码，因此enable-skfeng会出错。

**Comment by rollie123** [comment]
我是在这个网站上下载的：GmSSL 2.5.0 - OpenSSL 1.1.0d  28 Feb 2019，如果不支持，请问支持的版本在哪里下载，谢谢。
