### ISSUE TITLE
VS2013环境下编译报错，没找到原因

### ISSUE THREAD

**Issue by roy19831015** [guanzhi/GmSSL#75]
IF EXIST out32\heartbeat_test.exe.manifest mt -nologo -manifest out32\heartbeat_test.exe.manifest -outputresource:out32\heartbeat_test.exe;1
        cl /Fotmp32\igetest.obj -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_DYNAMIC_ENGINE /Zi /Fdtmp32/app -c .\test\igetest.c
igetest.c
.\test\igetest.c(1) : error C2061: 语法错误: 标识符“dummytest”
.\test\igetest.c(1) : error C2059: 语法错误:“;”
.\test\igetest.c(1) : error C2059: 语法错误:“.”
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.

 @guanzhi 大概的报错地点在这里，打开igetest.c，就一行内容如下
link dummytest.c
路径什么的也应该没问题，不知道是什么个原因

**Comment by roy19831015** [comment]
把dummytest.c的内容拷贝到igetest.c之后已经OK
自己结贴

**Comment by guanzhi** [comment]
可能的原因是OpenSSL-1.0.2中用了一些符号link，在Windows上需要格外处理。如果没有处理，文件内容仍为文件的路径，那么就会出现编译错误。OpenSSL已经意识到了符号链接的麻烦，OpenSSL-1.1不再用符号链接了，因此GmSSL后续基于OpenSSL-1.1的版本应该不会再出现类似的问题了。
