### ISSUE TITLE
能提供一个SM9命令行下的参考教程吗？

### ISSUE THREAD

**Issue by rain2fog** [guanzhi/GmSSL#752]
gmssl命令行模式下如何创建一个用户的SM9公私钥对？

文档里面都是如何生成加密解密的.... 那怎么生成SM9的公私钥？

**Comment by rain2fog** [comment]
公司的PHP开发，貌似不会弄C API

**Comment by abxcd111** [comment]
您好请问您解决了吗？我也想知道SM9命令行是如何调用的，光看-help参数，它是如何生成KGC的加密及签名主公钥和主私钥，如何生成用户的加密/签名公私钥，又如何写入.pem文件，都没有介绍=。=完全不会用

**Comment by wangxj4268** [comment]
> 您好请问您解决了吗？我也想知道SM9命令行是如何调用的，光看-help参数，它是如何生成KGC的加密及签名主公钥和主私钥，如何生成用户的加密/签名公私钥，又如何写入.pem文件，都没有介绍=。=完全不会用

你好，请问你找到了，我也不会用SM9的命令行...
