### ISSUE TITLE
gmssl命令行如何生成私钥？

### ISSUE THREAD

**Issue by herobigdata2099** [guanzhi/GmSSL#758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by herobigdata2099** [comment]
gmssl命令行如何生成私钥？

**Comment by github-amazingboy** [comment]
@herobigdata2099  gmssl sm2 -genkey -out skey.pem
