### ISSUE TITLE
ssl握手失败， 客户端没有加载国密套件， 请问都用什么可靠的客户端测试呢？

### ISSUE THREAD

**Issue by TheRoadToSuccess** [guanzhi/GmSSL#764]
我用nginx + gmssl 做服务端， 
配置中使用 ssl_ciphers RSA-WITH-SMS4-SHA1

使用wireshark 抓包， 发现客户端没有加载gm密钥， 不存在0xe012

想知道大家都用什么客户端来测试https 中的ssl的。

**Comment by zhaoxiaomeng** [comment]
可以使用GmSSL自带的s_client
