### ISSUE TITLE
skf eng linux下编译错误

### ISSUE THREAD

**Issue by fidderdan** [guanzhi/GmSSL#765]
**Describe the bug**
下载最新代码
./config enable-skfeng
make
出现编译错误，*** No rule to make target `engines/e_skf.c', needed by `engines/e_skf.o'.  Stop. 查看engines目录下没有e_skf.c文件。

请问老师，这个e_skf.c文件从哪里获取呢？谢谢。

**Comment by yujj20160217** [comment]
这个问题有人解决的嘛？ 遇到相同问题

**Comment by fidderdan** [comment]
因为不提供skf 代码 了
