### ISSUE TITLE
关于SKF引擎如何有偿提供问题

### ISSUE THREAD

**Issue by fidderdan** [guanzhi/GmSSL#766]
我们最近做国密加密相关，服务端使用Nginx+gmssl+ukey方式，实现国密ssl协议传输。再使用中发现缺少SKF engine，看到其他的iss，有提供有偿的SKF engine。但没有找到联系方式，问下我该怎么联系您，或者联系我 我邮箱523665380@qq.com

**Comment by xbguo** [comment]
开发者可能不会帮你修改Nginx，引擎的主要目的应该是适配不同厂商的ukey，我的理解是Nginx的代码也要修改才行，一旦Nginx代码修改好，使用引擎可以做到修改配置文件就支持不同厂商的ukey

**Comment by fidderdan** [comment]
Nginx不需要改，只要替换gmssl就可以了，现在想用gm ukey，但没有SFK的引擎

**Comment by zhenyuwei** [comment]
服务器用的是sdf吧，怎么用skf的？

**Comment by guanzhi** [comment]
GmSSL中包含SKF和SDF的管理命令`gmssl skf`和`gmssl sdf`，如需要SKF和SDF引擎请由贵公司或单位的邮箱给 guan@pku.edu.cn 发邮件。由于厂商的SKF或SDF实现通常并没有严格遵守标准文档，因此SKF和SDF引擎通常无法完美适配不同厂商的产品，需要针对具体厂商的产品做测试和适配。
