### ISSUE TITLE
能否给出一个关于sm9 通过c调用的demo

### ISSUE THREAD

**Issue by sz777** [guanzhi/GmSSL#768]
能否给出一个关于sm9 通过c调用的demo

**Comment by son012** [comment]
源码里面有一个,/test/sm9test.c,不过我这边也在做sm9加密数据以后在另外一个函数去接收该数据的时候就报错了,我猜应该是两次生成的sk不同,但我不知道怎么去解决

**Comment by sz777** [comment]
你可以关注一下https://github.com/songgeng87/SM9_FREE，我现在在用这个，你gmssl成功了吗

**Comment by sz777** [comment]
请问下你用的什么语言呢？

**Comment by son012** [comment]
> 请问下你用的什么语言呢？

我用的是c语言,我需要用gmssl提供的库来完成sm9加密工作,

**Comment by abxcd111** [comment]
请问你有解决sm9test.c的问题吗，我编译通过后，解密操作不通过，但是在make编译整个gmssl时，它会自动编译test中的所有文件包括sm9test.c，生成的sm9test直接运行又是能够通过的，就完全搞不懂原因 具体我也提交了issue了 #927
