### ISSUE TITLE
make test 的时候出现很多测试错误。

### ISSUE THREAD

**Issue by Yean-Feng** [guanzhi/GmSSL#771]
**Describe the bug**
下载源码后根据安装提示进行安装时，发现在make test这步有大量的报错信息，并且在
`3../test/recipes/30-test_ffx.t ..............`这一步骤中无法顺利测试完成。

**Expected behavior**

**Screenshots**

**Environments**
- OS: MacOS 10.14.3
- Compiler: CC

**Additional context**

**Comment by dds2333** [comment]
可能缺少依赖或版本不对吧，https://blog.csdn.net/weixin_42037232/article/details/86661958，链接是centos7的，希望有帮助
