### ISSUE TITLE
国密SSL双向认证问题

### ISSUE THREAD

**Issue by awen162** [guanzhi/GmSSL#773]
关教授，您好！
我在使用gmssl的国密SSL功能，测试双向认证时，在服务端一直报客户端证书长度为0的错误。
经过跟踪gmssl程序源码和网络抓包，发现客户端在发送客户端证书给服务端时，发送的证书内容长度为0。这就导致服务端做认证客户端证书时失败。
gmssl源码中有段这样的注释：

> /*
> * For TLS, cert_req is set to 2, so a cert chain of nothing is
> * sent, but no verify packet is sent
> */
> /*
> * XXX: For now, we do not support client authentication in ECDH
> * cipher suites with ECDH (rather than ECDSA) certificates. We
> * need to skip the certificate verify message when client's
> * ECDH public key is sent inside the client certificate.
> */

是不是说明目前国密的SSL双向认证还没有实现？
请问有打算近期实现国密的SSL双向认证功能吗？
麻烦解答下疑问，谢谢！

**Comment by zhenyuwei** [comment]
流程基本上都实现完了，细节部分自己参考国标调整一下，有些部分每个厂商实现之间都有差异的。

**Comment by awen162** [comment]
谢谢您的回复！目前我还没有这个能力实现这个细节，您有什么好的资源和建议吗？

**Comment by zhenyuwei** [comment]
去参考天安开源的那个项目，对比一下差异

**Comment by Jianfeng-Du** [comment]
参考这个修改的第二处 #716 
716 修改的两处与这两个 issue 相同 #850  #854

因为这是 google 搜索 “gmssl 双向认证” 的第一个结果，所以补充一下他人的修改
