### ISSUE TITLE
使用gmssl中的sm2编写了一下C++demo，但是报错sm2_encrypt未定义？

### ISSUE THREAD

**Issue by iliveforfun** [guanzhi/GmSSL#775]
`/tmp/ccfw678r.o：在函数‘Encrypt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：`
`3625sm2demo1.cpp:(.text+0x5f1)：对‘SM2_encrypt’未定义的引用
/tmp/ccfw678r.o：在函数‘Decrypt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：`
`3625sm2demo1.cpp:(.text+0x77d)：对‘SM2_decrypt’未定义的引用
collect2: error: ld returned 1 exit status`

**Comment by son012** [comment]
头文件没包含,还有你编译的时候 后边没跟-lcrypto

**Comment by iliveforfun** [comment]
> 头文件没包含,还有你编译的时候 后边没跟-lcrypto

都包含了

**Comment by guanzhi** [comment]
在源代码里 `#include <openssl/is_gmssl.h>`看看
