### ISSUE TITLE
何时更新openssl上游版本

### ISSUE THREAD

**Issue by zzm3145** [guanzhi/GmSSL#778]
gmssl当前版本基于openssl1.1.0d，已经有点老了，主要的问题如：
1. SSL_OP_NO_RENGOTIATION的flag不可用，需要>=1.1.0h  这个会在ssl漏洞检测体现出来
2. openssh当前版本编译也需要openssl >=1.1.0g

**Comment by guanzhi** [comment]
会在某个版本更新到openssl-1.1.1上面。
建议社区中能够有志愿者贡献力量完成同步和Bug Fix这样的重要且枯燥的工作。
