### ISSUE TITLE
国密SM4的汇编语言如何实现？

### ISSUE THREAD

**Issue by SJjinlixu** [guanzhi/GmSSL#780]
想问下老师，现在有可参考的国密系列的汇编语言的实现例子吗？SM4最好了，网上能找到的相关资料太少，希望老师能帮忙推荐一下国密汇编实现的相关资料，谢谢老师啦。

**Comment by guanzhi** [comment]
SM4有针对AVX2/KNC-NI等SIMD指令集的汇编实现代码，这部分没有默认集成在编译系统中，但是都是可以通过icc或gcc编译通过的
