### ISSUE TITLE
php7.3编译扩展报错

### ISSUE THREAD

**Issue by denept** [guanzhi/GmSSL#782]
/home/php-7.3.0/ext/openssl/xp_ssl.c:1022:3: 警告：不建议使用‘TLSv1_2_client_method’(声明于 /usr/local/include/openssl/ssl.h:1697) [-Wdeprecated-declarations]
   return is_client ? TLSv1_2_client_method() : TLSv1_2_server_method();
   ^
/home/php-7.3.0/ext/openssl/xp_ssl.c:1022:3: 警告：不建议使用‘TLSv1_2_server_method’(声明于 /usr/local/include/openssl/ssl.h:1696) [-Wdeprecated-declarations]
/home/php-7.3.0/ext/openssl/xp_ssl.c: 在函数‘php_openssl_tcp_sockop_accept’中:
/home/php-7.3.0/ext/openssl/xp_ssl.c:2342:29: 错误：自增操作数必须是左值
     GC_REFCOUNT(stream->ctx)++;
                             ^
/home/php-7.3.0/ext/openssl/xp_ssl.c: 在函数‘php_openssl_get_url_name’中:
/home/php-7.3.0/ext/openssl/xp_ssl.c:2632:23: 警告：从不兼容的指针类型初始化 [默认启用]
   const char * host = url->host;
                       ^
make: *** [ext/openssl/xp_ssl.lo] 错误 1

**Comment by fxlijun** [comment]
你的问题解决了没，最终有没有在项目上使用GmSSL， 若有替代方案也麻烦指点下， 我需要使用SM3算法，

**Comment by amosmz** [comment]
UP,同样遇到了，问题解决了吗？  能麻烦看看这个问题吗？ @guanzhi

**Comment by chinazj** [comment]
问题解决方案：修改/home/php-7.3.0/ext/openssl/xp_ssl.c:2342，将GC_REFCOUNT(stream->ctx)++;替换成GC_ADDREF(stream->ctx);。工作人员粗心了呀，7.3.1原版里面就是GC_ADDREF

**Comment by bblmj** [comment]
> 你的问题解决了没，最终有没有在项目上使用GmSSL， 若有替代方案也麻烦指点下， 我需要使用SM3算法，

PHP 7.2.32 测试成功了

**Comment by uptutu** [comment]
> 你的问题解决了没，最终有没有在项目上使用GmSSL， 若有替代方案也麻烦指点下， 我需要使用SM3算法，

现在的 openssl 1.1.1 已经支持了 sm3

**Comment by denept** [comment]
没有解决，目前用其它语言做中间件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "龚一涛"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 下午5:01
收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com&gt;; 
抄送: "请叫我大表哥"<denept@talknept.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [guanzhi/GmSSL] php7.3编译扩展报错 (#782)





  
你的问题解决了没，最终有没有在项目上使用GmSSL， 若有替代方案也麻烦指点下， 我需要使用SM3算法，
  
现在的 openssl 1.1.1 已经支持了 sm3

**Comment by chinazj** [comment]
@denept @uptutu 试试我的解决方法。目前我们正在用。未发现问题。https://github.com/guanzhi/GmSSL/pull/866。作者并未确认PR，但是我觉得确实是这样解决的

**Comment by linzi007** [comment]
7.3 同样遇到了
