### ISSUE TITLE
关于SM2DHE-WITH-SMS4-SM3 双向认证时，提几个bug和解决方法

### ISSUE THREAD

**Issue by fidderdan** [guanzhi/GmSSL#786]
1. ECDHE-SM4-SM3 报错
140737354012480:error:1010C067:elliptic curve routines:SM2_compute_id_digest:buffer too small:crypto/sm2/sm2_id.c:235:
140737354012480:error:141CF044:SSL routines:gmtls_sm2_derive:internal error:ssl/statem/statem_gmtls.c:1451:
140737354012480:error:141B6044:SSL routines:gmtls_construct_cke_sm2dhe:internal error:ssl/statem/statem_gmtls.c:1520:‘’
stetem_gmtls.c ：gmtls_sm2_derive函数在调用SM2_compute_id_digests时zlen未初始化，默认是0，增加 
zlen = EVP_MAX_MD_SIZE;
代码解决
2. stetem_gmtls.c ：gmtls_sm2_derive函数调用SM2_compute_share_key coredump ，原因pms未申请空间，传入为空指针，memset时 coredump。
增加
       pms = OPENSSL_malloc(pmslen);
	if(pms == NULL){
		SSLerr(SSL_F_GMTLS_SM2_DERIVE, ERR_R_INTERNAL_ERROR);
		goto end;
	}
代码解决 coredump问题。
3.SM2_compute_share_key 函数实现 是memset(out, 1, *outlen);   教授这是真心的吗？真的打算用GMSSL 商用呢。当前版本开发到什么阶段呢？什么时候能出稳定版本？

**Comment by devilhry** [comment]
你好，请问你如何配置双向认证呢？能否提供一下配置方法给我，谢谢!
