### ISSUE TITLE
请顺手为`include/openssl/ecschnorr.h`补好条件宏

### ISSUE THREAD

**Issue by lddfg** [guanzhi/GmSSL#787]
**Describe the bug**
`include/openssl/ecschnorr.h`文件中部分之定义了`#ifndef`，未曾使用`#endif`结束条件宏，导致7.4.1版本gcc出现问题

**Expected behavior**
编译通过

**Screenshots**
无需

**Environments**
- OS: [openSUSE Leap 15.0]
- Compiler: [gcc (SUSE Linux) 7.4.1 20190424 [gcc-7-branch revision 270538]]

**Additional context**
无需

**Comment by pengtianabc** [comment]
+1
You can add two `#endif` to fix it custom.

**Comment by guanzhi** [comment]
最近的更新已经将EC-Schnorr签名以及其他一些非基础算法的模块从GmSSL中移除了
