### ISSUE TITLE
stunnel支持gmssl tls/ssl

### ISSUE THREAD

**Issue by JiandongLu** [guanzhi/GmSSL#788]
我单位的软件现在想通过stunnel软件
https://www.stunnel.org/
来添加对国密tls/ssl的支持。
我们希望秘钥交换过程中使用sm2加密算法，数据通信使用sm4加密算法，hash函数使用sm3算法。
我的理解是，需要选用SM2-WITH-SMS4-SM3这个密码套件。此密码套件可以通过如下命令来查看
openssl ciphers -v | grep SM2
我现在遇到的问题：
1）不知道这个密码套件的证书如何生成。
（使用gmssl req试验了很久，没有成功）
2）证书是只在服务器部署还是服务器、客户端都部署？
3）stunnel本身是支持openssl tls/ssl的，我这里使用sha256WithRSAEncryption算法的pem证书已经验证通过了。如果要支持SM2-WITH-SMS4-SM3，是不是只要生成相应的证书部署上就可以了？并不需要修改stunnel本身的代码。

烦请各位老师、同行指教。

**Comment by JiandongLu** [comment]
gmssl ecparam -genkey -name sm2p256v1 -text -out user.key
gmssl req -new -key user.key -out user.req
gmssl x509 -req -days 3650 -sm3 -in user.req -signkey user.key -out user.crt

当前使用以上命令，生成了
Signature Algorithm: sm2sign-with-sm3
这样的证书。

**Comment by xiejianjun417** [comment]
> 我单位的软件现在想通过stunnel软件
> https://www.stunnel.org/
> 来添加对国密tls/ssl的支持。
> 我们希望秘钥交换过程中使用sm2加密算法，数据通信使用sm4加密算法，hash函数使用sm3算法。
> 我的理解是，需要选用SM2-WITH-SMS4-SM3这个密码套件。此密码套件可以通过如下命令来查看
> openssl ciphers -v | grep SM2
> 我现在遇到的问题：
> 1）不知道这个密码套件的证书如何生成。
> （使用gmssl req试验了很久，没有成功）
> 2）证书是只在服务器部署还是服务器、客户端都部署？
> 3）stunnel本身是支持openssl tls/ssl的，我这里使用sha256WithRSAEncryption算法的pem证书已经验证通过了。如果要支持SM2-WITH-SMS4-SM3，是不是只要生成相应的证书部署上就可以了？并不需要修改stunnel本身的代码。
> 
> 烦请各位老师、同行指教。

就我的理解是不行的
1.现有的openssl不支持国密通信，所以相应的应用对openssl调用必须换成gmssl
2.服务端和客户端有关openssl的API调用，替换成gmssl时可能需要做额外调整
3.证书验证，有单向和双向验证。单向只需要服务器有证书，双向需要服务器和客户端都有证书

**Comment by pengtianabc** [comment]
1. build stunnel with gmssl
2. add stunnel gmtls support
3. add double cert support
 I tried to implement stunnel with gmssl last year, but faild because of gmssl ssl layer double cert verify(verify cert fail), so my [stunnel-gm repo](https://github.com/pengtianabc/stunnel-gm) is empy. but now you can fix it custom.
Good luck.

**Comment by JiandongLu** [comment]
> > 我单位的软件现在想通过stunnel软件
> > https://www.stunnel.org/
> > 来添加对国密tls/ssl的支持。
> > 我们希望秘钥交换过程中使用sm2加密算法，数据通信使用sm4加密算法，hash函数使用sm3算法。
> > 我的理解是，需要选用SM2-WITH-SMS4-SM3这个密码套件。此密码套件可以通过如下命令来查看
> > openssl ciphers -v | grep SM2
> > 我现在遇到的问题：
> > 1）不知道这个密码套件的证书如何生成。
> > （使用gmssl req试验了很久，没有成功）
> > 2）证书是只在服务器部署还是服务器、客户端都部署？
> > 3）stunnel本身是支持openssl tls/ssl的，我这里使用sha256WithRSAEncryption算法的pem证书已经验证通过了。如果要支持SM2-WITH-SMS4-SM3，是不是只要生成相应的证书部署上就可以了？并不需要修改stunnel本身的代码。
> > 烦请各位老师、同行指教。
> 
> 就我的理解是不行的
> 1.现有的openssl不支持国密通信，所以相应的应用对openssl调用必须换成gmssl
> 2.服务端和客户端有关openssl的API调用，替换成gmssl时可能需要做额外调整
> 3.证书验证，有单向和双向验证。单向只需要服务器有证书，双向需要服务器和客户端都有证书

我前面生成的证书能用吗？那个是单向的还是双向的？我怎么知道是单向证书还是双向证书？

**Comment by JiandongLu** [comment]
> 1. build stunnel with gmssl
> 2. add stunnel gmtls support
> 3. add double cert support
>    I tried to implement stunnel with gmssl last year, but faild because of gmssl ssl layer double cert verify(verify cert fail), so my [stunnel-gm repo](https://github.com/pengtianabc/stunnel-gm) is empy. but now you can fix it custom.
>    Good luck.

你的半成品软件可以开源吗？

**Comment by xiejianjun417** [comment]
> > > 我单位的软件现在想通过stunnel软件
> > > https://www.stunnel.org/
> > > 来添加对国密tls/ssl的支持。
> > > 我们希望秘钥交换过程中使用sm2加密算法，数据通信使用sm4加密算法，hash函数使用sm3算法。
> > > 我的理解是，需要选用SM2-WITH-SMS4-SM3这个密码套件。此密码套件可以通过如下命令来查看
> > > openssl ciphers -v | grep SM2
> > > 我现在遇到的问题：
> > > 1）不知道这个密码套件的证书如何生成。
> > > （使用gmssl req试验了很久，没有成功）
> > > 2）证书是只在服务器部署还是服务器、客户端都部署？
> > > 3）stunnel本身是支持openssl tls/ssl的，我这里使用sha256WithRSAEncryption算法的pem证书已经验证通过了。如果要支持SM2-WITH-SMS4-SM3，是不是只要生成相应的证书部署上就可以了？并不需要修改stunnel本身的代码。
> > > 烦请各位老师、同行指教。
> > 
> > 
> > 就我的理解是不行的
> > 1.现有的openssl不支持国密通信，所以相应的应用对openssl调用必须换成gmssl
> > 2.服务端和客户端有关openssl的API调用，替换成gmssl时可能需要做额外调整
> > 3.证书验证，有单向和双向验证。单向只需要服务器有证书，双向需要服务器和客户端都有证书
> 
> 我前面生成的证书能用吗？那个是单向的还是双向的？我怎么知道是单向证书还是双向证书？

证书没有单向还是双向的说法，只有证书验证才有单向验证和双向验证。

**Comment by JiandongLu** [comment]
gmssl tls的例子，我现在只有哦
apps/s_client.c apps/s_server.c这两个
感觉比较复杂。有没有比较简单的例子？

**Comment by pengtianabc** [comment]
> > 1. build stunnel with gmssl
> > 2. add stunnel gmtls support
> > 3. add double cert support
> >    I tried to implement stunnel with gmssl last year, but faild because of gmssl ssl layer double cert verify(verify cert fail), so my [stunnel-gm repo](https://github.com/pengtianabc/stunnel-gm) is empy. but now you can fix it custom.
> >    Good luck.
> 
> 你的半成品软件可以开源吗？

I have not code it for a long time, so i am not sure it worked ok. i'will push it to my repo after test over if i am not busy.

**Comment by JiandongLu** [comment]
> > > 1. build stunnel with gmssl
> > > 2. add stunnel gmtls support
> > > 3. add double cert support
> > >    I tried to implement stunnel with gmssl last year, but faild because of gmssl ssl layer double cert verify(verify cert fail), so my [stunnel-gm repo](https://github.com/pengtianabc/stunnel-gm) is empy. but now you can fix it custom.
> > >    Good luck.
> > 
> > 
> > 你的半成品软件可以开源吗？
> 
> I have not code it for a long time, so i am not sure it worked ok. i'will push it to my repo after test over if i am not busy.

我这里主要是没有gmtls的例子。
你那个有bug的软件，至少大体流程是对的吧。我估计改改就成了。

前面有朋友提到"现有的openssl不支持国密通信，所以相应的应用对openssl调用必须换成gmssl"
我看了看代码，好像两个库的API没什么不同，也许差异很细微。但是我现在不知道，也找不到文档

**Comment by xiejianjun417** [comment]
> > > > 1. build stunnel with gmssl
> > > > 2. add stunnel gmtls support
> > > > 3. add double cert support
> > > >    I tried to implement stunnel with gmssl last year, but faild because of gmssl ssl layer double cert verify(verify cert fail), so my [stunnel-gm repo](https://github.com/pengtianabc/stunnel-gm) is empy. but now you can fix it custom.
> > > >    Good luck.
> > > 
> > > 
> > > 你的半成品软件可以开源吗？
> > 
> > 
> > I have not code it for a long time, so i am not sure it worked ok. i'will push it to my repo after test over if i am not busy.
> 
> 我这里主要是没有gmtls的例子。
> 你那个有bug的软件，至少大体流程是对的吧。我估计改改就成了。
> 
> 前面有朋友提到"现有的openssl不支持国密通信，所以相应的应用对openssl调用必须换成gmssl"
> 我看了看代码，好像两个库的API没什么不同，也许差异很细微。但是我现在不知道，也找不到文档

参考一下这里的指导：
http://gmssl.org/docs/openssl-to-gmssl.html

**Comment by pengtianabc** [comment]
if you want to use gmssl to replace openssl.
1th way: rebuild your program with gmssl
2nd way: 
  1. try to use gmssl libssl.so and libcrypto.so to replace openssl lib.
  2. if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD

**Comment by JiandongLu** [comment]
> if you want to use gmssl to replace openssl.
> 1th way: rebuild your program with gmssl
> 2nd way:
> 
> 1. try to use gmssl libssl.so and libcrypto.so to replace openssl lib.
> 2. if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD

我这里已经使用gmssl代替openssl重新编译过stunnel了。
我使用我上面那样生成的证书，部署在服务端。运行的时候，报错了：
在函数tls_post_process_client_hello里面调用函数ssl3_choose_cipher出错，
客户端服务器没有弓没有cipher.
**不知道是我生成的证书不对，还是因为需要修改api调用。**

**Comment by pengtianabc** [comment]
> > if you want to use gmssl to replace openssl.
> > 1th way: rebuild your program with gmssl
> > 2nd way:
> > 
> > 1. try to use gmssl libssl.so and libcrypto.so to replace openssl lib.
> > 2. if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD
> 
> 我这里已经使用gmssl代替openssl重新编译过stunnel了。
> 我使用我上面那样生成的证书，部署在服务端。运行的时候，报错了：
> 在函数tls_post_process_client_hello里面调用函数ssl3_choose_cipher出错，
> 客户端服务器没有弓没有cipher.
> **不知道是我生成的证书不对，还是因为需要修改api调用。**

use tcpdump or wireshark to checkyour cipher, this is because you config, i rememberd that i meet this problem, simple to fix it.

**Comment by xiejianjun417** [comment]
> > if you want to use gmssl to replace openssl.
> > 1th way: rebuild your program with gmssl
> > 2nd way:
> > 
> > 1. try to use gmssl libssl.so and libcrypto.so to replace openssl lib.
> > 2. if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD
> 
> 我这里已经使用gmssl代替openssl重新编译过stunnel了。
> 我使用我上面那样生成的证书，部署在服务端。运行的时候，报错了：
> 在函数tls_post_process_client_hello里面调用函数ssl3_choose_cipher出错，
> 客户端服务器没有弓没有cipher.
> **不知道是我生成的证书不对，还是因为需要修改api调用。**
关于证书生成和验证，你可以参考我下面的文章
https://blog.csdn.net/xiejianjun417/article/details/90768899

**Comment by JiandongLu** [comment]
> > > if you want to use gmssl to replace openssl.
> > > 1th way: rebuild your program with gmssl
> > > 2nd way:
> > > 
> > > 1. try to use gmssl libssl.so and libcrypto.so to replace openssl lib.
> > > 2. if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD
> > 
> > 
> > 我这里已经使用gmssl代替openssl重新编译过stunnel了。
> > 我使用我上面那样生成的证书，部署在服务端。运行的时候，报错了：
> > 在函数tls_post_process_client_hello里面调用函数ssl3_choose_cipher出错，
> > 客户端服务器没有弓没有cipher.
> > **不知道是我生成的证书不对，还是因为需要修改api调用。**
> > 关于证书生成和验证，你可以参考我下面的文章
> > https://blog.csdn.net/xiejianjun417/article/details/90768899


非常感谢！
我参照你的文章生成了证书，使用gmssl s_client, gmssl s_server两个命令已经测试通过了。基本搞清楚了怎么使用gmssl tls的api了。

还有一个问题：
生成证书的过程中使用了sm2, sm3, sm4三个算法。
gmssl s_client, gmssl s_server两个程序协商以后的密码套件是ECDHE-SM2-WITH-SMS4-GCM-SM3,
不过使用如下命令查看这个密码的套件的描述：
openssl ciphers -v | grep ECDHE-SM2-WITH-SMS4-GCM-SM3
结果是
ECDHE-SM2-WITH-SMS4-GCM-SM3    TLSv1.2    Kx=ECDH     Au=SM2    Enc=SMS4GCM(128)            Mac=AEAD
为什么没有出现sm3，而是mac=aead？

**Comment by xiejianjun417** [comment]
这个问题我也不太清楚，你要去问gmssl的负责人。内部的算法我也不懂


 
---原始邮件---
发件人: "Jiandong Lu"<notifications@github.com>
发送时间: 2019年6月7日(星期五) 下午5:37
收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com>;
抄送: "xiejianjun417"<xiejianjun417@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [guanzhi/GmSSL] stunnel支持gmssl tls/ssl (#788)


   
if you want to use gmssl to replace openssl.
 1th way: rebuild your program with gmssl
 2nd way:
  
try to use gmssl libssl.so and libcrypto.so to replace openssl lib. 

if occured error: cant find OPENSSL_1_1_0 or OPENSSL_1_1_0d in libcrpto.so.1.1, edit gmssl version headers to change OPENSSL_1_1_0d to OPENSSL_1_1_0 or use LD_PRELOAD 
  
我这里已经使用gmssl代替openssl重新编译过stunnel了。
 我使用我上面那样生成的证书，部署在服务端。运行的时候，报错了：
 在函数tls_post_process_client_hello里面调用函数ssl3_choose_cipher出错，
 客户端服务器没有弓没有cipher.
 不知道是我生成的证书不对，还是因为需要修改api调用。
 关于证书生成和验证，你可以参考我下面的文章
 https://blog.csdn.net/xiejianjun417/article/details/90768899
   
非常感谢！
 我参照你的文章生成了证书，使用gmssl s_client, gmssl s_server两个命令已经测试通过了。基本搞清楚了怎么使用gmssl tls的api了。
 
还有一个问题：
 生成证书的过程中使用了sm2, sm3, sm4三个算法。
 gmssl s_client, gmssl s_server两个程序协商以后的密码套件是ECDHE-SM2-WITH-SMS4-GCM-SM3,
 不过使用如下命令查看这个密码的套件的描述：
 openssl ciphers -v | grep ECDHE-SM2-WITH-SMS4-GCM-SM3
 结果是
 ECDHE-SM2-WITH-SMS4-GCM-SM3    TLSv1.2    Kx=ECDH     Au=SM2    Enc=SMS4GCM(128)            Mac=AEAD
 为什么没有出现sm3，而是mac=aead？

**Comment by guanzhi** [comment]
对于GmSSL和现有系统集成的工作，我们可以提供商业性的支持

**Comment by JiandongLu** [comment]
> 对于GmSSL和现有系统集成的工作，我们可以提供商业性的支持

谢谢关老师的回复。
我暂时解决了问题。

**Comment by pengtianabc** [comment]
@JiandongLu https://github.com/pengtianabc/stunnel-gm

**Comment by xiejianjun417** [comment]
> 对于GmSSL和现有系统集成的工作，我们可以提供商业性的支持

我这边需要使用GmSSL结合硬件SDF卡，请问怎么联系您呢？

**Comment by taochuanhui** [comment]
> > 对于GmSSL和现有系统集成的工作，我们可以提供商业性的支持
> 
> 谢谢关老师的回复。 我暂时解决了问题。

请问这个问题您是如何解决的？ 能否分享一下？ 我也使用了stunnel-gm编译后运行，遇到了跟您一样的问题。。。
