### ISSUE TITLE
SM9存在大量的内存泄漏，特别是签名验签

### ISSUE THREAD

**Issue by tangrt129** [guanzhi/GmSSL#797]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by yangboyd** [comment]
sm9test不能运行，全是segmentfault
