### ISSUE TITLE
关于SM2-WITH-SMS4-SM3 套件的握手信息hash值计算的算法问提

### ISSUE THREAD

**Issue by kengao2010** [guanzhi/GmSSL#799]
下载最新的gmssl版本，在linux下编译完成，测试服务器和客户端，使用下面命令：
server: gmssl s_server -gmtls -no_ssl3 -accept 4333 -cert SS.cert.pem -key SS.key.pem -dcert SE.cert.pem -dkey SE.key.pem -msg -debug –state
client:  gmssl s_client -connect 127.0.0.1:4333 -msg -debug -gmtls -state
调试发现计算finished消息时传入PRF算法hash值参数是用MD5+SHA1算法计算出来的,而不是标准里要求的SM3算法，而PRF里的HMAC算法用的是SM3，从而导至了用国密浏览器连接不上上面的这个国密服务程序。
不知道是命令参数用的不对还是gmssl程序的bug

**Comment by guanzhi** [comment]
如果是这样的话，那就是一个Bug。
