### ISSUE TITLE
国密SSL

### ISSUE THREAD

**Issue by hbbbs** [guanzhi/GmSSL#80]
非常感谢guanzhi和其他贡献者！ 建议每位使用者都积极的为项目加个星！

请问国密SSL的支持有没有相关的时间计划？
现在GMSSL已经支持使用SM2作为加密算法进行SSL通讯了吗？不知道有没有相关的DEMO?

**Comment by guanzhi** [comment]
国密SSL VPN不在近期规划内。
目前可以支持基于SM2的通信，相关的文档和DEMO之后会逐渐放到主页上。

**Comment by hbbbs** [comment]
非常感谢！ 祝项目越做做好！
