### ISSUE TITLE
用这个做tcp ssl通信加密这块的功能  拜托大神提供个思路 或者demo

### ISSUE THREAD

**Issue by BuildWu19940706** [guanzhi/GmSSL#801]
用这个做tcp ssl通信加密这块的功能  拜托大神提供个思路 或者demo

**Comment by BuildWu19940706** [comment]
Java语言的

**Comment by guanzhi** [comment]
可以将GmSSL和Tomcat编译到一起，提供服务端过密SSL支持。
客户端直接通过Java编程实现客户端SSL似乎不是一个典型的需求。

**Comment by lurenjia528** [comment]
同求

**Comment by abxcd111** [comment]
请问您做出来了吗？

**Comment by beykery** [comment]
@guanzhi 我们也有这需求，如何实现一个java的国密版ssl客户端？

**Comment by zhk56** [comment]
@beykery 我也想知道,有例子么,大哥哥
