### ISSUE TITLE
文件GmSSL/crypto/ec/ec_pmeth.c中的一个符号的询问

### ISSUE THREAD

**Issue by FrozenFort** [guanzhi/GmSSL#805]
我搜到的GmSSL安装使用指导里看到有人说要将文件crypto/ec/ec_pmeth.c中的一个NID_undef改成NID_sm3，位置如下图。
![企业微信截图_15629016677043](https://user-images.githubusercontent.com/5959416/61100035-263c1700-a497-11e9-8f49-1d7383070311.png)
我查到这个指导的时间是在2018年底了，但是在2019年6月提交的新代码上看到这里没有修改，所以想确认一下是否需要做这样的修改。 我看到#799 中的问题，觉得可能相关。

**Comment by guanzhi** [comment]
由于GmSSL无差别的支持ECIES加密和SM2加密，因此在通过EVP接口调用加密时，应该显式地指定算法（ECIES或SM2）和参数（ECIES和SM2有各自的可选参数）；如不指定，那么EVP的行为是未定义的。

**Comment by FrozenFort** [comment]
> 由于GmSSL无差别的支持ECIES加密和SM2加密，因此在通过EVP接口调用加密时，应该显式地指定算法（ECIES或SM2）和参数（ECIES和SM2有各自的可选参数）；如不指定，那么EVP的行为是未定义的。

这里显示指定算法是指加解密接口入参中的算法名称字符串吗？
