### ISSUE TITLE
gmssl是否支持skf engine？

### ISSUE THREAD

**Issue by suishixingkong** [guanzhi/GmSSL#806]
./config  enable-skfeng  shared
make;的时候报错
No rule to make target `engines/e_skf.c', needed by `engines/e_skf.o'
请问怎么解决？是目前还不支持skf吗？

**Comment by guanzhi** [comment]
不要启用 enable-skfeng

**Comment by zhenyuwei** [comment]
可以把skf.c文件单独编译，就可以使用了
