### ISSUE TITLE
sm4 pad 补全问题

### ISSUE THREAD

**Issue by zyf7862634** [guanzhi/GmSSL#808]
关老师您好：   我想问一下 sm4 补全问题， 我用gmssl sms4 加密时 发现原文如果为16位倍数长度，  密文也会在后面再增加16位， 我想问一下 这个补全规则是有什么标准吗？ 谢谢！

**Comment by guanzhi** [comment]
这种叫做PKCS #7 Padding，最初在RSA实验室的PKCS #7标准中定义。

**Comment by zyf7862634** [comment]
sm4加密补全中  是有标准要求 应该用 PKCS #7 Padding 吗？

**Comment by guanzhi** [comment]
下面的解释不一定是十分准确的：

CBC加密模式的标准中通常不涉及填充方案的选择，填充是由应用决定的。

如果应用中需要填充，那么就需要明确指定一种填充方案，如果应用中数据恰好是整数个分组，那么就不需要指定填充方案。例如，GmSSL中默认的PKCS7填充方案是PKCS7密码消息格式中要求的填充方案，主要用在电子邮件加密中，而SSL/TLS的CBC模式的填充就又有所不同。

GmSSL中可以指定CBC填充方式的，默认采用PKCS7填充，但是你也可以选择不填充或者其他的填充方案。具体细节参考evp.h头文件以及手册页。
