### ISSUE TITLE
win10使用mingw编译报错：类型冲突： conflicting types for '*'

### ISSUE THREAD

**Issue by woxihuanjia** [guanzhi/GmSSL#810]
使用mingw64编译静态库的时候，出现了很多错误，如下：
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:352:16: error: **conflicting types for 'BOOL'**
 typedef long   BOOL;
                ^~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:131:15: note: previous declaration of 'BOOL' was here
   typedef int BOOL;
               ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:354:17: error: **conflicting types for 'CHAR'**
 typedef UINT8   CHAR;
                 ^~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:163,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winnt.h:285:16: note: previous declaration of 'CHAR' was here
   typedef char CHAR;
                ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:358:17: error: **conflicting types for 'LONG'**
 typedef INT32   LONG;
                 ^~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:163,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winnt.h:287:20: note: previous declaration of 'LONG' was here
   typedef __LONG32 LONG;
                    ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:359:18: error: **conflicting types for 'ULONG'**
 typedef UINT32   ULONG;
                  ^~~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:24:29: note: previous declaration of 'ULONG' was here
   typedef unsigned __LONG32 ULONG;
                             ^~~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:366:18: error: **conflicting types for 'DWORD'**
 typedef UINT32   DWORD;
                  ^~~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:141:29: note: previous declaration of 'DWORD' was here
   typedef unsigned __LONG32 DWORD;
                             ^~~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:368:18: error: **conflicting types for 'LPSTR'**
 typedef CHAR *   LPSTR;
                  ^~~~~
In file included from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/minwindef.h:163,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windef.h:8,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/windows.h:69,
                 from /opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
/opt/gmsm/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winnt.h:336:24: note: previous declaration of 'LPSTR' was here
   typedef CHAR *NPSTR,*LPSTR,*PSTR;
                        ^~~~~
make[1]: *** [crypto/gmapi/gmapi_sdf_ec.o] Error 1

**Comment by guanzhi** [comment]
./config -DWIN32 试一下

**Comment by woxihuanjia** [comment]
@guanzhi 关老师，加上这个参数还是报错。我用的win10,msys2,gcc版本是：x86_64-w64-mingw32-gcc.exe (Rev3, Built by MSYS2 project) 9.1.0

In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:352:16: error: conflicting types for 'BOOL'
  352 | typedef long   BOOL;
      |                ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:131:15: note: previous declaration of 'BOOL' was here
  131 |   typedef int BOOL;
      |               ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:354:17: error: conflicting types for 'CHAR'
  354 | typedef UINT8   CHAR;
      |                 ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:285:16: note: previous declaration of 'CHAR' was here
  285 |   typedef char CHAR;
      |                ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:358:17: error: conflicting types for 'LONG'
  358 | typedef INT32   LONG;
      |                 ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:287:20: note: previous declaration of 'LONG' was here
  287 |   typedef __LONG32 LONG;
      |                    ^~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:359:18: error: conflicting types for 'ULONG'
  359 | typedef UINT32   ULONG;
      |                  ^~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:24:29: note: previous declaration of 'ULONG' was here
   24 |   typedef unsigned __LONG32 ULONG;
      |                             ^~~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:366:18: error: conflicting types for 'DWORD'
  366 | typedef UINT32   DWORD;
      |                  ^~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:141:29: note: previous declaration of 'DWORD' was here
  141 |   typedef unsigned __LONG32 DWORD;
      |                             ^~~~~
In file included from include/openssl/gmsdf.h:57,
                 from crypto/gmapi/gmapi_sdf_ec.c:68:
include/openssl/sgd.h:368:18: error: conflicting types for 'LPSTR'
  368 | typedef CHAR *   LPSTR;
      |                  ^~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ./e_os.h:190,
                 from crypto/include/internal/cryptlib.h:16,
                 from crypto/gmapi/gmapi_sdf_ec.c:62:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:336:24: note: previous declaration of 'LPSTR' was here
  336 |   typedef CHAR *NPSTR,*LPSTR,*PSTR;
      |                        ^~~~~
make[1]: *** [Makefile:3862: crypto/gmapi/gmapi_sdf_ec.o] Error 1

**Comment by woxihuanjia** [comment]
各位老师，问题还没解决，有没有人可以帮帮我啊？

**Comment by hqhangyu** [comment]
怎么办我也遇到了

**Comment by guanzhi** [comment]
把sgd.h skf.h sdf.h 这几个头文件中出现冲突的typedef就注释掉，可暂时解决你的问题。

**Comment by woxihuanjia** [comment]
我把这几个冲突的改成mingw自带的，这个地方就可以编译通过了，但是会有新的问题，会出现一些类似：apps/skf.o:skf.c:undefined reference to `SKF_*@*'的错误

**Comment by xiaocongsen** [comment]
我通过删除这些定义 全部替换解决了问题
