### ISSUE TITLE
SM9 go语言接口

### ISSUE THREAD

**Issue by zycj123sy** [guanzhi/GmSSL#814]
想使用go语言调用SM9算法，但发现没有相关接口，提供的一些加解密都是SM2的，请问可以增加一些go语言的文档，把给出的加解密等函数封装好么？

**Comment by guanzhi** [comment]
SM9的Go接口已经有人在做了

**Comment by zycj123sy** [comment]
嗯嗯感谢回复~因为发现/go/gmssl提供的加解密函数都是SM2的，所以希望能够有SM9接口使用




------------------ 原始邮件 ------------------
发件人: "Zhi Guan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 上午9:58
收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com>; 
抄送: "天涯翼影客"<1085868033@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [guanzhi/GmSSL] SM9 go语言接口 (#814)




SM9的Go接口已经有人在做了
