### ISSUE TITLE
什么时候出js版？是js版可以实现吗？是否有什么限制？

### ISSUE THREAD

**Issue by simei1** [guanzhi/GmSSL#816]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guanzhi** [comment]
你要用在Node.js里面还是用在浏览器里面？

**Comment by shiwenna** [comment]
浏览器里面，有可用的js版吗

**Comment by dev-zl** [comment]
> 你要用在Node.js里面还是用在浏览器里面？

浏览器
