### ISSUE TITLE
gmssl 现在支持周期密钥更新吗？如何设置呢？

### ISSUE THREAD

**Issue by xiaobingxianzi** [guanzhi/GmSSL#817]
RT

**Comment by guanzhi** [comment]
不支持，需要应用来维护会话密钥的声明周期。
一般需要为对称密钥维护计时器和已处理数据的长度。如果会话密钥使用时间超过最大允许时长（比如一个VPN会话已经超过24小时）时，或密钥处理的数据长度超过了算法允许的最大长度（不同算法有所不同），那么就需要更新这个密钥。
一般不需要在密码库层面做密钥生命周期管理，在应用层做更自然，例如限制VPN的TCP会话最大时长和SESSION数据的维护时间，使用不同的密钥加密每个文件等等。

**Comment by xiaobingxianzi** [comment]
谢谢关老师，我也是计划在应用层维护会话密钥的生命周期，但是如果密钥生命周期到达，我该如何在不中断链接，不二次鉴别的基础上调用gmssl接口或者某接口发起密钥更新呢
