### ISSUE TITLE
服务器双证书，客户端单证书，双向鉴别时客户端发送证书信息长度非法

### ISSUE THREAD

**Issue by xiaobingxianzi** [guanzhi/GmSSL#821]
**Describe the bug**
服务器双证书，客户端单证书，双向鉴别时客户端发送证书信息长度非法

**Expected behavior**
客户端因为不支持dkey，dcert参数，所以只有一套证书。应该可以正常发送证书长度，完成鉴别

**Screenshots**

**Environments**
- OS:  ubuntu12.04LTS x64
- Compiler:gcc

**Additional context**

**Comment by xiaobingxianzi** [comment]
客户端向服务器发送证书请求时，发送超长包，导致服务器丢包。具体原因经查是因为客户端构造证书报文的函数gmtls_construct_client_certificate中，调用gmtls_construct_sm2_certs前没有对输入参数l（长度）初始化。经过比对，服务器端调用该函数构造证书报文时，通过l = 3 + SSL_HM_HEADER_LENGTH(s);进行了变量初始化（参见gmtls_construct_server_certificate）。为什么同一个函数调用服务器和客户端在变量初始化时操作不同呢？

**Comment by cuiyilu** [comment]
困扰了好久o(╥﹏╥)o

**Comment by yangcy001** [comment]
具体如何修改呢？

**Comment by xiaobingxianzi** [comment]
就照着上面说的方法修改就好了呀

**Comment by yangcy001** [comment]
方便写一下第二个修正如何判空的代码吗，非常感谢

**Comment by xiaobingxianzi** [comment]
不好意思，这是在公司工作时进行的。 公司有保密要求。 不能提供。

**Comment by yangcy001** [comment]
只是学习，不存在竞争的

**Comment by xiaobingxianzi** [comment]
我理解，可是领导已经明确要求不提供，我也很难啊。不好意思

**Comment by yangcy001** [comment]
能加个微信(17712911162)向您学习其他相关知识吗
