### ISSUE TITLE
请问一下，gmssl如何处理国密的数字信封。

### ISSUE THREAD

**Issue by ZMHCL** [guanzhi/GmSSL#825]
我这边有一份国密服务器给的数字信封，是经过base64编码，解码后使用d2i_PKCS7_bio或者不解码直接使用PEM_read_bio_PKCS7，都是失败的。

**Comment by ZMHCL** [comment]
@guanzhi

**Comment by guanzhi** [comment]
把PEM文本贴出来看看（不要包含机密信息）
