### ISSUE TITLE
我在调试 SM2-WITH-SMS4-SM3通信，函数gmtls_construct_ske_sm2实现和标准一样，但是为何和360国密浏览器通信失败，抓包看Server Key Exchange返回的数据应该客户端无法解密导致。

### ISSUE THREAD

**Issue by ygm521** [guanzhi/GmSSL#826]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environments**
- OS: [e.g. ubuntu16.04LTS x64]
- Compiler: [e.g. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]

**Additional context**

**Comment by ygm521** [comment]
我没有找到： SM2_set_id(ec_key, "1234567812345678"); 有这个函数应该就可以握手成功了。

**Comment by ygm521** [comment]
if(id){
	if (!SM2_set_id(ec_key, id)){
		goto err;
	}
}
	

int SM2_set_id(EC_KEY *ec_key, const char *id)
{
	char *pid;

	if (strlen(id) > SM2_MAX_ID_LENGTH) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}

	if ((pid = EC_KEY_get_key_method_data(ec_key, sm2_data_dup,
		sm2_data_free, sm2_data_free)) != NULL) {
		if(strncmp(pid, "1234567812345678", 16) ==  0){
			 return 1; 
		}
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}

	if (!(pid = OPENSSL_strdup(id))) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		return 0;
	}

	if (EC_KEY_insert_key_method_data(ec_key, pid, sm2_data_dup,
		sm2_data_free, sm2_data_free)) {
		fprintf(stderr, "error: %s %d\n", __FILE__, __LINE__);
		//ERR_print_errors_fp(stderr);
		//OPENSSL_free(pid);
		return 0;
	}

	return 1;
}

**Comment by ygm521** [comment]
我的解决方法如下也不行，麻烦指点谢谢
```
static int gmtls_construct_ske_sm2(SSL *s, unsigned char **p, int *l, int *al)
{
	int ret = 0;
	EVP_PKEY *pkey;
	X509 *x509;
	unsigned char *buf = NULL;
	int n;
	EVP_MD_CTX *md_ctx = NULL;
	char *id = NULL;
	unsigned char z[EVP_MAX_MD_SIZE];
	size_t zlen;
	unsigned char *d;
	unsigned int siglen;

	*al = SSL_AD_INTERNAL_ERROR;

	/* prepare sign key */
	if (!(pkey = s->cert->pkeys[SSL_PKEY_SM2].privatekey)) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}

	/* prepare encrypt cert buffer */
	if (!(x509 = s->cert->pkeys[SSL_PKEY_SM2_ENC].x509)) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}
	if (!(buf = gmtls_new_cert_packet(x509, &n))) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}

    unsigned char *tbs, *sig_tmp;
    unsigned int tbs_len;
    if (!(tbs = OPENSSL_malloc(3+n + 32*2))) {
		return -1;
	}

    sig_tmp = tbs;
    memcpy(sig_tmp, s->s3->client_random, 32);
    sig_tmp += 32;
    memcpy(sig_tmp, s->s3->client_random, 32);
    sig_tmp += 32;
    memcpy(sig_tmp, buf, n+3);
    sig_tmp += n+3;

    tbs_len = (unsigned int)(sig_tmp - tbs);
    d = *p;

    if (!SM2_compute_message_digest(EVP_sm3(), EVP_sm3(),
        (const unsigned char *)tbs, tbs_len, "1234567812345678", strlen("1234567812345678"),
        z, &zlen, EVP_PKEY_get0_EC_KEY(pkey))) {
        fprintf(stderr, "error: %s %d\n", __FUNCTION__, __LINE__);
        goto end;
    }
    if (!SM2_sign(NID_undef, z, zlen, &(d[2]), &siglen, EVP_PKEY_get0_EC_KEY(pkey))) {
		fprintf(stderr, "error: %s %d\n", __FUNCTION__, __LINE__);
		goto end;
	}       

   s2n(siglen, d);
   *l = 2 + siglen;
   *p += *l;

	*al = -1;
	ret = 1;

end:
	OPENSSL_free(buf);
	return ret;
}
```

**Comment by zhenyuwei** [comment]
static int gmtls_construct_ske_sm2(SSL *s, unsigned char **p, int *l, int *al)
{
	int n, ret = 0;
	EVP_PKEY *pkey;
	X509 *x509;
	unsigned char *d, *buf, z[SM3_DIGEST_LENGTH];
	EVP_MD_CTX *md_ctx = NULL;	
	unsigned int siglen;
	size_t zlen = SM3_DIGEST_LENGTH;

	*al = SSL_AD_INTERNAL_ERROR;

	/* prepare sign key */
	if (!(pkey = s->cert->pkeys[SSL_PKEY_SM2].privatekey)) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}

	/* prepare encrypt cert buffer */
	if (!(x509 = s->cert->pkeys[SSL_PKEY_SM2_ENC].x509)) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}
	if (!(buf = gmtls_new_cert_packet(x509, &n))) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_INTERNAL_ERROR);
		return 0;
	}

	/* mallco ctx */
	if (!(md_ctx = EVP_MD_CTX_new())) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_MALLOC_FAILURE);
		goto end;
	}

	if (!SM2_compute_id_digest(EVP_sm3(), SM2_DEFAULT_ID, SM2_DEFAULT_ID_LENGTH, z, &zlen,
		EVP_PKEY_get0_EC_KEY(pkey))) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_SM2_LIB);
		goto end;
	}

	/* sign digest of {client_random, server_random, enc_cert} */
	if (EVP_SignInit_ex(md_ctx, EVP_sm3(), NULL) <= 0) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_EVP_LIB);
		goto end;
	}

#ifdef GMTLS_DEBUG
	{
        int i;
        printf("Z=");
        for (i = 0; i< zlen; i++)
            printf("%02X",z[i]);
        printf("\n");

        printf("C=");
        for (i = 0; i < n; i++)
            printf("%02X",buf[i]);
        printf("\n");
    }
#endif

	if (EVP_SignUpdate(md_ctx, z, zlen) <= 0
		|| EVP_SignUpdate(md_ctx, &(s->s3->client_random[0]),
			SSL3_RANDOM_SIZE) <= 0
		|| EVP_SignUpdate(md_ctx, &(s->s3->server_random[0]),
			SSL3_RANDOM_SIZE) <= 0
		|| EVP_SignUpdate(md_ctx, buf, n) <= 0) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_EVP_LIB);
		goto end;
	}

	/* generate signature */
	if (EVP_PKEY_size(pkey) < 0) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_EVP_LIB);
		goto end;
	}
	d = *p;
	siglen = EVP_PKEY_size(pkey);
	if (EVP_SignFinal(md_ctx, &(d[2]), &siglen, pkey) <= 0) {
		SSLerr(SSL_F_GMTLS_CONSTRUCT_SKE_SM2, ERR_R_EVP_LIB);
		goto end;
	}
    s2n(siglen, d);

	*l += 2 + siglen;
	*al = -1;
	ret = 1;

end:
	OPENSSL_free(buf);
	EVP_MD_CTX_free(md_ctx);
	return ret;
}
这个是我改过后的内容，你可以测一下，如果还有问题，查一下你的其它流程。

**Comment by ygm521** [comment]
@zhenyuwei  验证了 问题依旧。说不定是别的地方问题。 @guanzhi

**Comment by ygm521** [comment]
@zhenyuwei tassl直接启动都报错。

**Comment by zhenyuwei** [comment]
不要用最新的，有个老版本的，你主要是分析数据流，老版本的没问题

**Comment by ygm521** [comment]
@zhenyuwei 你用哪个版本，我试了最新版和TASSL-openssl_1.0.2o.rar均不行。报错： failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by zhenyuwei** [comment]
tassl有测试代码，你可以用测试代码，或者直接分析ssl流程，查看与你有出入的部门，这块之前我测过，ecc-sm4的套件好像可以，另外一个有点问题，后来我这边改完了就没有继续查下去

**Comment by ygm521** [comment]
@zhenyuwei 你说的版本现在都找不到了，我之前问了他们维护人员说不支持此套件。

**Comment by zhenyuwei** [comment]
这个就不好办了，其实gmssl的ecc-sm4套件改的代码量不多的，我晚上回去看一下吧，最近有段时间没有看这个了

**Comment by ygm521** [comment]
@zhenyuwei 方便加下qq或者微信？谢谢

**Comment by zhenyuwei** [comment]
你的QQ是账号上面的那个？我加你吧

**Comment by fidderdan** [comment]
server_key_exchange 在和浏览器或者tassl 连试时，签名错误，签名时椭圆曲线ID 获取的不对 改成1234567812345678就可以了

**Comment by ygm521** [comment]
@fidderdan 我这还没到握手呢，启动nginx时候就错了。

**Comment by bethewind** [comment]
今天最新的代码，在wireshark里可以抓到tls成功的包，供大家参考
先执行apps/gmca/里的test.sh生成ca，然后执行下面的命令启动server/client
-verify参数是是否验证对方的证书
-cipher指定加密套件算法

GmSSL/apps$./gmssl s_server -accept 4333 -CAfile gmca/.ca/cacert.pem -cert gmca/.ca/certs/01.pem -key gmca/.ca/keys/alice@pku.edu.cn.key -tls1_2 -debug -msg -verify 1 -cipher ECDHE-SM2-WITH-SMS4-SM3

GmSSL/apps$ ./gmssl s_client -connect localhost:4333 -CAfile gmca/.ca/cacert.pem -cert gmca/.ca/certs/02.pem -key gmca/.ca/keys/bob@pku.edu.cn.key -tls1_2 -showcerts -msg -debug -verify 1

**Comment by ygm521** [comment]
@guanzhi 老哥从不吭声 敢问健在。@……@

**Comment by xwqiu** [comment]
> @zhenyuwei 你用哪个版本，我试了最新版和TASSL-openssl_1.0.2o.rar均不行。报错： failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 我套件选择是：ECC_SM4_SM3

tassl的要想ECC和ECDHE都通，还需要改一些，但改动不大，如果需要借鉴，建议用最新1.1.1b的，毕竟openssl现在都到1.1.1c了

**Comment by ygm521** [comment]
@xwqiu 可以给tassl官方提个修复代码？

**Comment by xwqiu** [comment]
> @xwqiu 可以给tassl官方提个修复代码？

个人感觉bug还是比较多的，不好提
比如加载双证书的接口的逻辑：
if (x && (X509_get_extension_flags(x)& EXFLAG_KUSAGE) && (X509_get_key_usage(x) & (X509v3_KU_KEY_ENCIPHERMENT | X509v3_KU_DATA_ENCIPHERMENT | X509v3_KU_KEY_AGREEMENT))){
            i = SSL_PKEY_ECC_ENC;  

如果要用最好自己二次开发

**Comment by ygm521** [comment]
@xwqiu 您那边有修改好的 tassl 代码？ 我结合nginx调试下cfca的证书和自签名的证书，只要单向认证通了就行。

**Comment by Nu1i** [comment]
@zhenyuwei 请问要使用360国密浏览器访问的话需要修改哪些地方？

**Comment by zhenyuwei** [comment]
调试的地方好像有几处要修改，具体的内容我这边记得不太详细，你去查一下数据包的格式应该就可以解决了，调整的地方不是太多，都是几处细节调整
