### ISSUE TITLE
SM2DHE-WITH-SMS4-SM3密钥套件不能正常完成握手过程

### ISSUE THREAD

**Issue by xiaobingxianzi** [guanzhi/GmSSL#828]
LINUX平台，使用SM2-WITH-SMS4-SM3可以完成握手，但是改成SM2DHE-WITH-SMS4-SM3就不行了。是还需要补充什么参数吗？
使用命令为：
gmssl s_server -verify 1 -gmtls -cert srvcrt.pem -key srvkey.pem -dcert srvcrt1.pem -dkey srvkey1.pem -msg -debug –state -CAfile demoCA/cacert.pem -cipher SM2DHE-WITH-SMS4-SM3
和
gmssl s_client -msg -debug -gmtls -state -verify 1 -CAfile demoCA/cacert.pem -key clikey.pem -cert clicrt.pem -cipher SM2DHE-WITH-SMS4-SM3
出错原因是客户端计算masterkey的时候s->s3->peer_tmp为空。

**Comment by zhenyuwei** [comment]
这个套件之前好像没有完全实现，计算主密钥接口是空，现在实现了？

**Comment by xiaobingxianzi** [comment]
1.目前计算主密钥int tls1_generate_master_secret(SSL *s, unsigned char *out, unsigned char *p,
                                int len)内部实现是
{
    printf("file:%s,line:%d,func:%s\n",
		   __FILE__,__LINE__,__func__);

    if (s->session->flags & SSL_SESS_FLAG_EXTMS) {
        unsigned char hash[EVP_MAX_MD_SIZE * 2];
        int hashlen;
        /*
         * Digest cached records keeping record buffer (if present): this wont
         * affect client auth because we're freezing the buffer at the same
         * point (after client key exchange and before certificate verify)
         */
        if (!ssl3_digest_cached_records(s, 1))
            return -1;
        hashlen = ssl_handshake_hash(s, hash, sizeof(hash));
#ifdef SSL_DEBUG
        fprintf(stderr, "Handshake hashes:\n");
        BIO_dump_fp(stderr, (char *)hash, hashlen);
#endif
        tls1_PRF(s,
                 TLS_MD_EXTENDED_MASTER_SECRET_CONST,
                 TLS_MD_EXTENDED_MASTER_SECRET_CONST_SIZE,
                 hash, hashlen,
                 NULL, 0,
                 NULL, 0,
                 NULL, 0, p, len, s->session->master_key,
                 SSL3_MASTER_SECRET_SIZE);
        OPENSSL_cleanse(hash, hashlen);
    } else {
        tls1_PRF(s,
                 TLS_MD_MASTER_SECRET_CONST,
                 TLS_MD_MASTER_SECRET_CONST_SIZE,
                 s->s3->client_random, SSL3_RANDOM_SIZE,
                 NULL, 0,
                 s->s3->server_random, SSL3_RANDOM_SIZE,
                 NULL, 0, p, len, s->session->master_key,
                 SSL3_MASTER_SECRET_SIZE);
    }
#ifdef SSL_DEBUG
    fprintf(stderr, "Premaster Secret:\n");
    BIO_dump_fp(stderr, (char *)p, len);
    fprintf(stderr, "Client Random:\n");
    BIO_dump_fp(stderr, (char *)s->s3->client_random, SSL3_RANDOM_SIZE);
    fprintf(stderr, "Server Random:\n");
    BIO_dump_fp(stderr, (char *)s->s3->server_random, SSL3_RANDOM_SIZE);
    fprintf(stderr, "Master Secret:\n");
    BIO_dump_fp(stderr, (char *)s->session->master_key,
                SSL3_MASTER_SECRET_SIZE);
#endif

#ifdef OPENSSL_SSL_TRACE_CRYPTO
    if (s->msg_callback) {
        s->msg_callback(2, s->version, TLS1_RT_CRYPTO_PREMASTER,
                        p, len, s, s->msg_callback_arg);
        s->msg_callback(2, s->version, TLS1_RT_CRYPTO_CLIENT_RANDOM,
                        s->s3->client_random, SSL3_RANDOM_SIZE,
                        s, s->msg_callback_arg);
        s->msg_callback(2, s->version, TLS1_RT_CRYPTO_SERVER_RANDOM,
                        s->s3->server_random, SSL3_RANDOM_SIZE,
                        s, s->msg_callback_arg);
        s->msg_callback(2, s->version, TLS1_RT_CRYPTO_MASTER,
                        s->session->master_key,
                        SSL3_MASTER_SECRET_SIZE, s, s->msg_callback_arg);
    }
#endif

    return (SSL3_MASTER_SECRET_SIZE);
}
2.我用的是apps\s_client.c这个例程，它不支持双证书的-dcert参数导入。协商还居然成功了。我也很崩溃。

**Comment by huangyehui** [comment]
GMSSL是可以支持ECHDE算法的。 不过某些命令不支持 可能会导致代码中的变量都没设置正确。
