### ISSUE TITLE
serverkeyexchange计算问题

### ISSUE THREAD

**Issue by eva520** [guanzhi/GmSSL#83]
大家好 刚接触国密 有个问题想请教下

我在应答客户端时包含server hello + server certificate + serverkeyexchange + certificate request + server done的请求，该请求到达客户端后报解密失败警告。

有谁可以帮我看看原因：
server certificate：
服务器证书 +　根证书

serverkeyexchange计算：
H=SM3(Z || 客户端随机数||服务器随机数||根证书3字节长度||根证书）
然后对H签名作为EXCHANGE数据

**Comment by conezxy** [comment]
解密失败说明双方协商出的工作密钥不一致，你在两端都把PreMasterSecret，MasterSecret以及推导出的工作密钥都打印出来对比一下。

**Comment by LiTianjue** [comment]
1. 使用签名证书进行签名
2. 密钥交换方式不同，签名内容也是不同的

具体可以看文档6.4.4.3的最后一段话

**Comment by iF2007** [comment]
使用master的最新代码，仍然遇到相同问题，即使加上了根证书 3 字节长度进行计算
