### ISSUE TITLE
最近更新修改的sm3_update的BUG，引发的一系列BUG（SM2/SM9）

### ISSUE THREAD

**Issue by iMrYang** [guanzhi/GmSSL#830]
问题引出：
因为要测试SM9，但是test目录下的sm2test，sm9test均段错误，所以和同事一起来找问题。

直接看代码
crypto/sm3/sm3.c

问题函数：
void sm3_update(sm3_ctx_t *ctx, const unsigned char *data, size_t data_len);

简单描述一下此函数里的这个BUG（分四部分）：

// 计算本次待update的数据的block数（第一部分）
size_t blocks = data_len / SM3_BLOCK_SIZE;

// 这段代码，若是还有剩余的数据，那么就把本次update的数据的一部分填充到之前剩余的数据里，组成一个block进行摘要。（第二部分）
if (ctx->num) {
		unsigned int left = SM3_BLOCK_SIZE - ctx->num;
		if (data_len < left) {
			memcpy(ctx->block + ctx->num, data, data_len);
			ctx->num += data_len;
			return;
		} else {
			memcpy(ctx->block + ctx->num, data, left);
			sm3_compress(ctx->digest, ctx->block);
			ctx->nblocks++;
			data += left;
			data_len -= left;
		}
	}

// 这一部分代码，是对本次update的数据进行摘要（第三部分）
	sm3_compress_blocks(ctx->digest, data, blocks);

// 这一部分，是保存剩余数据到ctx结构体（第四部分）
	ctx->nblocks += blocks;
	data += SM3_BLOCK_SIZE * blocks;
	data_len -= SM3_BLOCK_SIZE * blocks;

	ctx->num = data_len;
	if (data_len) {
		memcpy(ctx->block, data, data_len);
	}

问题在哪呢？
如果整个摘要只调用一次 EVP_DigestUpdate()，那么第二段代码根本不会运行，第三段代码此时就是正确的。
如果是多次调用EVP_DigestUpdate()，如果上一次update不是SM3_BLOCK_SIZE的整数倍，必定会残留数据，那么本次调用，必然会把一部分数据填充到上一次，然后摘要。这么一看第二段代码也没问题。
问题来了，此时再跑第三段代码，因为数据已经少了一部分了，那么你之前计算的block，有很大可能不再准确了。
（举例：比如你本次摘要update 384字节，那么就是刚好6个block。如果因为前一次update剩余了63个字节，那么第二段代码会把1个字节填充到上一次的块里，再进行一次块摘要。此时，你应该摘要剩余的383个字节，但此时，383/64=5，应该是5个block，第三段代码仍然是摘要的6个block，你的数据越界了）

再然后，第四步代码
data_len -= SM3_BLOCK_SIZE * blocks;
（还是上面的例子，因为第二部填充，你的data_len由384字节变为383字节，但blocks还是6，此处的结构就是 data_len = 383-384 =-1，注意，data_len是sizet_t类型的，那么这个数无限大... ）

再往后走两步
memcpy(ctx->block, data, data_len);

你说能不段错误么...

我第一反应的解决方案：
在第三部分前重新算一下block就行了（代码：blocks = data_len / SM3_BLOCK_SIZE;）

完整代码：
void sm3_update(sm3_ctx_t *ctx, const unsigned char *data, size_t data_len)
{
	size_t blocks = data_len / SM3_BLOCK_SIZE;

	if (ctx->num) {
		unsigned int left = SM3_BLOCK_SIZE - ctx->num;
		if (data_len < left) {
			memcpy(ctx->block + ctx->num, data, data_len);
			ctx->num += data_len;
			return;
		} else {
			memcpy(ctx->block + ctx->num, data, left);
			sm3_compress(ctx->digest, ctx->block);
			ctx->nblocks++;
			data += left;
			data_len -= left;
		}
	}

	blocks = data_len / SM3_BLOCK_SIZE;
	
	sm3_compress_blocks(ctx->digest, data, blocks);
	ctx->nblocks += blocks;
	data += SM3_BLOCK_SIZE * blocks;
	data_len -= SM3_BLOCK_SIZE * blocks;

	ctx->num = data_len;
	if (data_len) {
		memcpy(ctx->block, data, data_len);
	}
}

还有一个解决方案，把这一部分代码改回以前（所以改这一段是为了什么！）

**Comment by zhenyuwei** [comment]
昨天测试的时候发现192的长度直接memcpy崩溃了，不知道改的时候有没有测试过:joy:

**Comment by luohua-xyz** [comment]
@iMrYang 我也碰到了同样的问题，谢谢。

**Comment by xwqiu** [comment]
已经修复了

**Comment by guanzhi** [comment]
该问题已经解决
