### ISSUE TITLE
执行sm2命令coredump

### ISSUE THREAD

**Issue by gokerwin** [guanzhi/GmSSL#831]
**Describe the bug**
linux环境下，编译成功，执行sm2相关的命令会出现coredump，执行其他命令没问题。
怀疑跟ComputeSM2IDDigest 生成Z value有关。

**Screenshots**
[
![image](https://user-images.githubusercontent.com/7880683/63586024-02f6a280-c5d3-11e9-91fa-963126995cf6.png)
](url)

**Comment by guanzhi** [comment]
该问题已经解决

**Comment by SteveGuo99** [comment]
您好，能否问一下您的问题最终定位到了什么错误吗？我在调用sm2 密钥交换相关的函数时，调用sm2_compute_id_digest时出现错误，我检查了输入，包括id字符串末尾的null，gdb无法显示函数内的错误位置，请问您是否发现sm2_compute_id_digest中有什么问题吗？
