### ISSUE TITLE
nmake 无法编译

### ISSUE THREAD

**Issue by Thefallenleaves88** [guanzhi/GmSSL#834]
AppData\Local\Temp\nm94D3.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 ZUC256_set_key
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 ZUC256_set_mac_key
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 sms4_avx2_ctr32_encrypt_blocks
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 sms4_avx2_ecb_encrypt_blocks
libcrypto.lib : fatal error LNK1120: 4 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”

**Comment by mao** [comment]
linux下编译通过，windows平台有你这个错误。
我们的临时解决方案如下：
修改  include/openssl/sms4.h 添加：
# define SMS4_AVX2				16

执行 :
perl Configure -VC-WIN64A -no-zuc -no-evp
nmake
nmake install

**Comment by guanzhi** [comment]
该问题已经解决
