### ISSUE TITLE
SM9性能这么低吗，1秒签名只能签3次

### ISSUE THREAD

**Issue by xwqiu** [guanzhi/GmSSL#835]
Doing sm9 sign                 for 10s:  33 times sign SM9's in 9.99s
Doing sm9 exch tests        for 10s:  10 times exch SM9's in 9.98s
Doing sm9 key wrap tests for 10s:  20 times key wrap SM9's in 9.99s
Doing sm9 encrypt tests   for 10s:  20 times encrypt SM9's in 9.85s

**Comment by guanzhi** [comment]
GmSSL的SM9实现还没有优化。
