### ISSUE TITLE
[建议]加强工程化支持

### ISSUE THREAD

**Issue by J-Feng** [guanzhi/GmSSL#836]
首先感谢GmSSL团队及其他贡献者的付出，为推动国密的工程化应用以及生态圈建立做出了贡献。本人在使用过程中遇到一些问题，有所感，有所想，在此给出一些建议。

GmSSL一直基于master分支做迭代，这就导致有时候clone的节点可能存在问题，而除了git log，又没有一个版本间的差异信息。

查看项目branch和tag信息可以看到早期的GmSSL对一些milestone打了tag，后来就没有对应的分支或tag了。这就导致没有办法区分某个节点所属的版本（除了编译后通过version命令查看或者查看源码），与别人沟通时，只能报出自己编译所基于的节点hash，而不是对应的版本。

举个例子：某次更新到节点[246867f](https://github.com/guanzhi/GmSSL/tree/246867fd2b32019809c4e271f54c82e4c114c717)出现了build error（按理说项目有CI，不应该出现这种情况），所以认为2.5.0版本有问题，但是别人的2.5.0版本可能是正常的。还有一种情况是相反的，某些开发者说自己在x.y.z版本验证某个功能可用，但是其他人通过log找到对应的版本checkout过去发现不行，因为虽然是同样的版本号，但是所处的节点可能不同。

建议GmSSL在工程化方面做一些流程上的提升，**这样能够大大加强项目在工程实践中的可用性和可维护性，相信会大大增加项目在实际工程中的使用率，从而进一步增加项目在国密生态中的影响力。**

可以先从打tag开始，GmSSL项目的核心维护者认可的release版本节点，可以随手打上一个版本tag，然后建议使用者clone项目后checkout到某个tag上，从而区分了release版和dev版，这样可以解决大部分问题，一般不会出现release节点的build error或者由于测试没有覆盖到而导致的某些功能缺陷。

最后，再次感谢贡献者的辛苦付出。

**Comment by mao** [comment]
很好的建议，现在只有一个master版本，拿下来的代码编译不通过的情况比较多。

**Comment by guanzhi** [comment]
非常好的建议！年底前发布一个“稳定版”吧

**Comment by HuKeping** [comment]
太好了。
