### ISSUE TITLE
Gmssl在arm设备端编译失败

### ISSUE THREAD

**Issue by AndyWebJava** [guanzhi/GmSSL#843]
报错如下图：
![1568701823(1)](https://user-images.githubusercontent.com/22862566/65016854-de82b180-d957-11e9-8c09-a9d631a468e5.jpg)
环境是arm-v8
具体报错信息如下：
make[2]: Leaving directory '/home/openailab/GmSSL-master'
gcc  -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF engines/afalg/e_afalg.d.tmp -MT engines/afalg/e_afalg.o -c -o engines/afalg/e_afalg.o engines/afalg/e_afalg.c
engines/afalg/e_afalg.c: In function 'eventfd':
engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function); did you mean 'eventfd'?
     return syscall(__NR_eventfd, n);
                    ^~~~~~~~~~~~
                    eventfd
engines/afalg/e_afalg.c:110:20: note: each undeclared identifier is reported only once for each function it appears in
engines/afalg/e_afalg.c:111:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [Makefile:6518: engines/afalg/e_afalg.o] Error 1
make[1]: Leaving directory '/home/openailab/GmSSL-master'
make: *** [Makefile:128: all] Error 2

**Comment by AndyWebJava** [comment]
我的解决办法是：sudo ./config -DGMSSL_NO_TURBO no-afalgeng

**Comment by AndyWebJava** [comment]
失败编译结果：sudo ./config no-afalgeng
错误信息：./libcrypto.so: undefined reference to `EC_GFp_sm2z256_method' collect2: error: ld returned 1 exit status
原因：该函数只支持Inter CPU

**Comment by AndyWebJava** [comment]
失败编译结果：sudo ./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128 no-afalgeng
错误信息：PEM_read_bio_EC_PUBKEY返回null
原因：该函数只支持Inter CPU

**Comment by AndyWebJava** [comment]
最终成功编译方案：sudo ./config -DGMSSL_NO_TURBO no-afalgeng

**Comment by AndyWebJava** [comment]
我的板子是：Linux localhost.localdomain 4.4.126 #15 SMP Mon Nov 12 05:07:46 EST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by AndyWebJava** [comment]
失败编译方案：sudo ./config no-afalgeng
错误信息：./libcrypto.so: undefined reference to `EC_GFp_sm2z256_method' collect2: error: ld returned 1 exit status
原因：该函数只支持Inter CPU

**Comment by AndyWebJava** [comment]
失败编译方案：sudo ./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128 no-afalgeng
错误信息：PEM_read_bio_EC_PUBKEY返回null
原因：该函数只支持Inter CPU

**Comment by AndyWebJava** [comment]
最终成功编译方案：sudo ./config -DGMSSL_NO_TURBO no-afalgeng

**Comment by Likeit-pr** [comment]
谢谢！

**Comment by CodeManager-zhangjin** [comment]
@AndyWebJava 感谢给出解决方案
