### ISSUE TITLE
java 接口 解密sm2 报错

### ISSUE THREAD

**Issue by slwcm** [guanzhi/GmSSL#845]
您好 我在使用java接口使用sm2解密时遇到问题。希望能够得到您的帮助。
   1 我得到sm2 16进制的私钥，请问如何传入publicKeyDecrypt进行解密？
   2 我得到sm2私钥byte数组，解密时报错如下，
Errors:
1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:

1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=EC_PRIVATEKEY

1960:error:10068010:elliptic curve routines:d2i_ECPrivateKey:EC lib:crypto\ec\ec_asn1.c:922:

1960:error:1010706F:elliptic curve routines:old_ec_priv_decode:decode error:crypto\ec\ec_ameth.c:493:

1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:

1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=PKCS8_PRIV_KEY_INFO

1960:error:8007506C:lib(128):Java_GmSSL_publicKeyDecrypt:invalid private key:GmSSL.c:1318:
希望得到您的帮助。

**Comment by happyycm** [comment]
> 您好 我在使用java接口使用sm2解密时遇到问题。希望能够得到您的帮助。
> 1 我得到sm2 16进制的私钥，请问如何传入publicKeyDecrypt进行解密？
> 2 我得到sm2私钥byte数组，解密时报错如下，
> Errors:
> 1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:
> 
> 1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=EC_PRIVATEKEY
> 
> 1960:error:10068010:elliptic curve routines:d2i_ECPrivateKey:EC lib:crypto\ec\ec_asn1.c:922:
> 
> 1960:error:1010706F:elliptic curve routines:old_ec_priv_decode:decode error:crypto\ec\ec_ameth.c:493:
> 
> 1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:
> 
> 1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=PKCS8_PRIV_KEY_INFO
> 
> 1960:error:8007506C:lib(128):Java_GmSSL_publicKeyDecrypt:invalid private key:GmSSL.c:1318:
> 希望得到您的帮助。

您的问题解决了吗？我现在也碰到java上密钥格式转换的问题了，不知道怎么把密钥转成ASN.1格式的。

**Comment by slwcm** [comment]
解决了------------------ 原始邮件 ------------------
发件人: "happyycm"<notifications@github.com>
发送时间: 2020年5月12日(星期二) 上午9:34
收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com>;
抄送: "slwcm"<164170384@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guanzhi/GmSSL] java 接口 解密sm2 报错 (#845)




  
您好 我在使用java接口使用sm2解密时遇到问题。希望能够得到您的帮助。
 1 我得到sm2 16进制的私钥，请问如何传入publicKeyDecrypt进行解密？
 2 我得到sm2私钥byte数组，解密时报错如下，
 Errors:
 1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:
 
1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=EC_PRIVATEKEY
 
1960:error:10068010:elliptic curve routines:d2i_ECPrivateKey:EC lib:crypto\ec\ec_asn1.c:922:
 
1960:error:1010706F:elliptic curve routines:old_ec_priv_decode:decode error:crypto\ec\ec_ameth.c:493:
 
1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112:
 
1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=PKCS8_PRIV_KEY_INFO
 
1960:error:8007506C:lib(128):Java_GmSSL_publicKeyDecrypt:invalid private key:GmSSL.c:1318:
 希望得到您的帮助。
  
您的问题解决了吗？我现在也碰到java上密钥格式转换的问题了，不知道怎么把密钥转成ASN.1格式的。
 
&mdash;

**Comment by HyoukaLL** [comment]
> 
> 解决了------------------ 原始邮件 ------------------ 发件人: "happyycm"<notifications@github.com> 发送时间: 2020年5月12日(星期二) 上午9:34 收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com>; 抄送: "slwcm"<164170384@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [guanzhi/GmSSL] java 接口 解密sm2 报错 (#845) 您好 我在使用java接口使用sm2解密时遇到问题。希望能够得到您的帮助。 1 我得到sm2 16进制的私钥，请问如何传入publicKeyDecrypt进行解密？ 2 我得到sm2私钥byte数组，解密时报错如下， Errors: 1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112: 1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=EC_PRIVATEKEY 1960:error:10068010:elliptic curve routines:d2i_ECPrivateKey:EC lib:crypto\ec\ec_asn1.c:922: 1960:error:1010706F:elliptic curve routines:old_ec_priv_decode:decode error:crypto\ec\ec_ameth.c:493: 1960:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1112: 1960:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=PKCS8_PRIV_KEY_INFO 1960:error:8007506C:lib(128):Java_GmSSL_publicKeyDecrypt:invalid private key:GmSSL.c:1318: 希望得到您的帮助。 您的问题解决了吗？我现在也碰到java上密钥格式转换的问题了，不知道怎么把密钥转成ASN.1格式的。 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

能请教下怎么解决的么,我也遇到这个问题了
