### ISSUE TITLE
sm2签名结果不是64字节的

### ISSUE THREAD

**Issue by churuxu** [guanzhi/GmSSL#85]
要跟别的厂商对接，对方做签名，我方做验证，但我们双方技术人员对这块都不太熟。

对方签名结果是64字节的，
我方签名结果却是70多字节的
算法不匹配

目前我方调gmssl大概流程：
签名：
EVP_PKEY* pkey = PEM_read_bio_PrivateKey(...)
const EVP_MD* provider = EVP_get_digestbyname("sm3");
EVP_MD_CTX     md_ctx;  
EVP_SignInit   (&md_ctx, provider);  
EVP_SignUpdate (&md_ctx, text, len); 
EVP_SignFinal(&md_ctx, buf, &buflen, pkey);

验证:
X509* cert = PEM_read_bio_X509(...) 
EVP_PKEY* pkey = X509_get_pubkey(cert)
const EVP_MD* provider = EVP_get_digestbyname("sm3");
EVP_MD_CTX md_ctx;  
EVP_VerifyInit   (&md_ctx, provider);  
EVP_VerifyUpdate (&md_ctx, text, len);  
EVP_VerifyFinal(&md_ctx, ..., pkey); 

得到的签名结果不是64字节的，不知道如何正确调用gmssl的api？

**Comment by conezxy** [comment]
70字节的应该是带上ASN.1编码的签名结果（0009-2012《SM2算法使用规范》中定义的格式），64字节的应该是硬件密码设备直接返回的结果，将其拆分为两个32字节的BIGNUM就可以比对。

**Comment by churuxu** [comment]
谢谢楼上，ASN.1解码后就可以了

**Comment by luoyanwu** [comment]
@churuxu 这种怎么ASN.1解码是啥，对71个字节的进行ASN.1解码？

**Comment by churuxu** [comment]
@luoyanwu  我传了个代码示例：https://github.com/churuxu/codesnippets/tree/master/sm2asn1

**Comment by luoyanwu** [comment]
@churuxu 谢谢，麻烦了  #后来去了解知道了，我这边用java基于bc去实现的，跟c的对接。对这块第一次搞。目前pkcs7的格式还有点问题= =

**Comment by huangchouchou** [comment]
慎用  https://github.com/churuxu/codesnippets/tree/master/sm2asn1
bn转asn1时，不一定都是大端小端32个字节，也就是说，这个代码返回会是失败，并不是签名失败，而是转asn1失败。测试时，可以连续调用几十次，现象就出现了。更加要注意的是如果单纯的修复了<32也是不对的。校验时，解码同样存在这个问题。
还是希望官网能够给予稳定的示例
