### ISSUE TITLE
java sm2 私钥格式问题

### ISSUE THREAD

**Issue by slwcm** [guanzhi/GmSSL#852]
我得到16进制的sm2私钥字符串，请问如何把私钥转换为java可用的私钥格式。

**Comment by happyycm** [comment]
> 我得到16进制的sm2私钥字符串，请问如何把私钥转换为java可用的私钥格式。

你转换成功了吗？

**Comment by slwcm** [comment]
成功了，我的微信。chufeiwoyoumi 有什么问题可以联系我------------------ 原始邮件 ------------------
发件人: "happyycm"<notifications@github.com>
发送时间: 2020年5月12日(星期二) 下午4:52
收件人: "guanzhi/GmSSL"<GmSSL@noreply.github.com>;
抄送: "slwcm"<164170384@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guanzhi/GmSSL] java sm2 私钥格式问题 (#852)




  
我得到16进制的sm2私钥字符串，请问如何把私钥转换为java可用的私钥格式。
  
你转换成功了吗？
 
&mdash;
