### ISSUE TITLE
sm9test.c 中密钥协商的测试函数里，判断条件是否有误？

### ISSUE THREAD

**Issue by luohua-xyz** [guanzhi/GmSSL#853]
在 [sm9test.c](https://github.com/guanzhi/GmSSL/blob/master/test/sm9test.c#L359) 的函数 `sm9test_exch(const char *idA, const char *idB) ` 中
目前是第359行处：

`if` (memcmp(SKA, SKA, sizeof(SKA)) != 0 || memcmp(SA, S2, sizeof(SA)) != 0) `

应当为：

`memcmp(SKA, SKB, sizeof(SKA)) != 0`

**Comment by guanzhi** [comment]
是的，您可以发一个pull request来修改这个Bug
