### ISSUE TITLE
GMTLS双向认证CertificateVerify阶段失败

### ISSUE THREAD

**Issue by J-Feng** [guanzhi/GmSSL#854]
使用gmtls协议，双向认证，客户端发送CertificateVerify消息，服务端验证失败：
```
140181017206784:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_srvr.c:2941
```
**环境**
- OS: ubuntu18.04LTS x64
- Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- GmSSL版本：基于节点a097e49719ac736e5a895ff3ddd25e26578d378f（GmSSL 2.5.4 - OpenSSL 1.1.0d  3 Sep 2019）

**Comment by J-Feng** [comment]
原因已经找到：tls_construct_client_verify方法中，pkey = s->cert->key->privatekey，而在使用SM2双证时s->cert->key不指向&s->cert->pkeys[SSL_PKEY_SM2]而是指向&s->cert->pkeys[SSL_PKEY_SM2_ENC]，导致签名密钥与服务端验签时使用的公钥不匹配

**Comment by J-Feng** [comment]
与[issue #850](https://github.com/guanzhi/GmSSL/issues/850)均为gmtls双证双向验证测试时发现的问题，本地测试修复这两个问题即可使当前基于SM2-WITH-SMS4-SM3的gmtls双向验证握手成功

**Comment by xiejianjun417** [comment]
@J-Feng 请问你有没有用GMSSL和TASSL进行过双向认证？我这边用gmssl作为服务端，tassl作为客户端，tassl一直报bad signature

**Comment by J-Feng** [comment]
tassl我还没开始搞，目前思路是先把gmssl测过再开始测与其他国密ssl实现的互通

报bad signature的话，我建议查两个地方：先看两边哈希算法用的一样否（因为密码套件已经协商过了，所以哈希不一致的可能性比较小）；再看签名用的密钥对不对（因为是双证，很可能是密钥用的不对）；如果都没问题，那就只能追一下被签名的消息内容和长度是否一致了，我是用openssl s_server和openssl s_client调试的，它们会dump所有的通信消息，也可以直接挂gdb追一下，我觉得比抓包方便点（我个人觉得这个可能性较小，因为获取消息数据的代码基本是原生openssl能支持的，只要都用原有的实现，一般不会出问题）

以上，希望对你有帮助

在 2019年9月30日，11:45，xiejianjun417 <notifications@github.com<mailto:notifications@github.com>> 写道：


@J-Feng<https://github.com/J-Feng> 请问你有没有用GMSSL和TASSL进行过双向认证？我这边用gmssl作为服务端，tassl作为客户端，tassl一直报bad signature

**Comment by maxiaoxiong123** [comment]
> @ J-Feng请问你有没有用GMSSL和TASSL进行过双向认证？我这边用gmssl作为服务端，tassl作为客户端，tassl一直报错误签名

**Comment by maxiaoxiong123** [comment]
> @ J-Feng请问你有没有用GMSSL和TASSL进行过双向认证？我这边用gmssl作为服务端，tassl作为客户端，tassl一直报错误签名

您好，我们是北京创安致真科技有限公司，我们公司有过开发GMSSL的经验，期望与您合作，方便的话加您个微信与您继续沟通。

**Comment by maxiaoxiong123** [comment]
@https://github.com/xiejianjun417您好，我们是北京创安致真科技有限公司，我们公司有过开发GMSSL的经验，期望与您合作，方便的话加上您个微信与您继续沟通。

**Comment by maxiaoxiong123** [comment]
> @ J-Feng请问你有没有用GMSSL和TASSL进行过双向认证？我这边用gmssl作为服务端，tassl作为客户端，tassl一直报错误签名

@xiejianjun417 您好，我们是北京创安致真科技有限公司，我们公司有过开发GMSSL的经验，很期望与您进行合作，方便的话希望加您个微信与您继续沟通。

**Comment by WindsOfWorld** [comment]
@J-Feng 您好，请问下进行双向认证的时候，客户端证书组包失败，报错如下：
139914243950336:error:141B518F:SSL routines:gmtls_output_cert_chain:ee key too small:ssl/statem/statem_gmtls.c:165:
139914243950336:error:141B7044:SSL routines:gmtls_construct_client_certificate:internal error:ssl/statem/statem_gmtls.c:1409:

**Comment by J-Feng** [comment]
> @J-Feng 您好，请问下进行双向认证的时候，客户端证书组包失败，报错如下：
> 139914243950336:error:141B518F:SSL routines:gmtls_output_cert_chain:ee key too small:ssl/statem/statem_gmtls.c:165:
> 139914243950336:error:141B7044:SSL routines:gmtls_construct_client_certificate:internal error:ssl/statem/statem_gmtls.c:1409:

@WindsOfWorld https://github.com/guanzhi/GmSSL/pull/851
合入这个提交试试看

**Comment by WindsOfWorld** [comment]
@J-Feng 非常感谢，困扰一周的问题终于解决了

**Comment by J-Feng** [comment]
@guanzhi 建议尽快合入https://github.com/guanzhi/GmSSL/pull/851
可以肯定的是，这确实是一个bug

**Comment by glfov** [comment]
你好，请问遇到的是服务端在收到certificate verify后报decrypt error的问题吗？
