### ISSUE TITLE
GM/T0024中主密钥计算用PRF实现，这个PRF可以直接借用tls1_generate_master_secert吗？

### ISSUE THREAD

**Issue by zhangshuang01** [guanzhi/GmSSL#86]

**Comment by zsdev2015** [comment]
留个qq 1433438864 我也在搞方便互加下

**Comment by eva520** [comment]
https://github.com/guanzhi/GmSSL/issues/62
这个问题搞好了能说下原因吗，我也遇到这个问题了。

另外，方便加个qq一起讨论下1433438864

**Comment by LiTianjue** [comment]
这部分代码上实现上应该是一样的，只是要注意gmssl v1.1 版本只使用的了sm3算法做摘要，某个老的版本ssl 的 PRF 实现是两种摘要算法(MD5,SHA1) 的结果做异或，你代码跟进去，确保只使用了一种摘要算法即可（sm3）,我有重新写过tls1_PRF（t1_enc.c）函数，但刚才查看了一下，似乎是没有区别的，时间久记不住了，你代码跟踪的时候检查一下摘要的数据是否被分成多片，

tls1_PRF

```
  count = 0;
    for (idx = 0; ssl_get_handshake_digest(idx, &m, &md); idx++) {
        if ((m << TLS1_PRF_DGST_SHIFT) & digest_mask)
            count++;
    }
    if (!count) {
        /* Should never happen */
        SSLerr(SSL_F_TLS1_PRF, ERR_R_INTERNAL_ERROR);
        goto err;
    }
    len = slen / count;
    if (count == 1)     //这里要保证只使用了一种摘要算法
        slen = 0;
    S1 = sec;
```

**Comment by zhangshuang01** [comment]
@LiTianjue 谢谢你的答复，ssl源码里tls1_PRF确实是用了两种摘要算法（MD5，SHA），我是需要把这两种都换成SM3吗？根据ssl vpn国密规范实现国密的时候，是基于ssl3还是tls协议？

**Comment by gujinqiangggs** [comment]
@zhangshuang01 实现国密协议，我感觉只能是结合标准的ssl协议中的某个，没有一个是完全符合GM/T0024的，目前我在实现Ecc-sm3-sm4时，就是按照GM/T0024去修改ssl3来做的，哪里不符合就改掉哪里，先去模拟整个ssl握手过程的每一步。也正像“guan-master”说的国密协议是完全不同于标准ssl的协议，但是我感觉它又和标准的ssl协议有关联，所以甭管哪个，只要最后改成符合GM/T0024的要求的就可以了。可以先拿一个来改，改的过程中会越来越明晰基于哪个更合适。Correct me if i was wrong!

**Comment by conezxy** [comment]
国密协议的PRF协商是采用TLS 1.2的单hash方式（不是TLS 1.0/1.1的双HASH方式）
Hash算法为SM3算法，见规范的5.1.3和5.1.4小节：

![image](https://cloud.githubusercontent.com/assets/12557190/23149158/120aed7c-f825-11e6-8a14-ddc8022456f4.png)

**Comment by zhangshuang01** [comment]
@gujinqiangggs 非常感谢你的回复，你说的很对没有一个是完全符合GM/T0024规范的。我目前也是想先简单的实现ECC_SM4-SM3，刚开始是基于ssl3改的，改到发送client finish这块时发现这块的实现与tls比较接近。我作为客户端在发送client key exchange, change cipher spec, client finish 时总是收到来自服务器的alert bad record mac, 我也不能确定是发送的key change 哪里不对还是finish哪里不对，现在是各种实验，因为服务器我也改不了，只能摸索着改客户端。不知道你调试进展到哪一步了？还请指点一下

**Comment by gujinqiangggs** [comment]
@zhangshuang01 呵呵，真是巧了，我现在在拿360当客户端，然后在实现server端，目前只到了server_key_exchange 这步，目前在算如何签出这个签名，刚才看到你的另一个问题是有关这个的看你已经解决了。我先弄弄，不行再问你。等你客户端好了，我服务端好了，咱俩可以handshake一把，哈哈

**Comment by zhangshuang01** [comment]
@gujinqiangggs 我前段时间是研究过做服务器端的开发，还提了问题，后来因为项目需要就改成先做客户端了！相应的问题也关闭了，有问题再讨论！

**Comment by zhangshuang01** [comment]
@conezxy 非常感谢你的解惑，正如你上面贴出来的图，我应该基于SM3算法自己实现P_SM3.
 tls1.2的单hash实现在openssl里有没有具体的实现？

**Comment by conezxy** [comment]
目前GmSSL中的tls1_PRF已支持TLS 1.2的单HASH模式，也同时支持TLS 1.0/1.1的双HASH模式

**Comment by LiTianjue** [comment]
楼上说的对，新的ssl版本是支持单hash的，但是你是基于哪个版本来进行改造的我不确定，所以只是提醒一下，在这一步中需要留意单hash ，另外P_SM3也不是需要你实现的，GMSSL已经实现了SM3算法，同样在我贴出来的代码中，
```c
	for(idx = 0; ssl_get_handshake_digest(idx,&m,&md);idx++) {

```
取出算法idx,然后通过标准的EVP接口进行计算（tls1_P_hash），对照GM文档，这里应该也是不需要改其他东西的

**Comment by zhangshuang01** [comment]
@conezxy  @LiTianjue 谢谢各位的回复，在我所用的openssl代码中找到了ssl_get_algorithm2()函数，是使用单hash,还是双hash是由它返回的值决定的，如果我要实现国密的话改造一下它的返回值，让它返回sm3， 这样我用tls1_PRF的时候就是单hash，且是p_sm3. 我还有一点疑惑，当是sm3单hash时，tls1_PRF函数里的out1[i] ^=out2[i]; 是否就不需要做异或了？

**Comment by zhangshuang01** [comment]
out1的初值都初始化为0了，异或也没有什么影响！

**Comment by gujinqiangggs** [comment]
应该不需要了,我今天也正好用到这个地方了。另外ssl_get_algorithm2()这个函数你不用修改返回值，直接修改初始换密码套件的第三个参数地方就行s3_lib.c中。
/* (GmSSL Specific) */
        {
                1,
                GM1_TXT_SM2_SM4_SM3,
                GM1_CK_SM2_SM4_SM3,
                SSL_kSM2,
                SSL_aSM2,
                SSL_SM4,
                SSL_SM3,
                SSL_TLSV1_2,
                SSL_NOT_EXP|SSL_HIGH,
                SSL_HANDSHAKE_MAC_SM3|TLS1_PRF_SM3,
                256,
                256,
        }
另外，我的服务端马上要好了，呵呵

**Comment by zhangshuang01** [comment]
@gujinqiangggs 恭喜呦，你计算主密钥，工作密钥也会用到这些讨论的内容！呵呵

**Comment by zhangshuang01** [comment]
各位我再请教一个问题，客户端发送过去的key exchange，以及change cipher spec, encrypted handshake message,但是一直收到服务器端的告警，说是bad record mac, 我用什么办法来确定是我的key exchange有问题，还是encrypted handshake message有问题？

**Comment by gujinqiangggs** [comment]
这两个中用到mac校验的，有key exchange 的解密预主密钥时校验数据的完整性和encrypted handshake message 中的校验12个字节的finish消息。单从bad record mac理解，应该是record有问题，key exchange那个应该不叫一个record，而是record的一个字段，finish消息才是一个握手的record。所以我怀疑是后者有问题。另外客户端是否可以只发送到change cipher spec 就结束，看服务端啥反应？我这有服务端，你来跟我连，我告诉你哪步有问题吧，哈哈

**Comment by zhangshuang01** [comment]
@gujinqiangggs 我不知道该如何只发送到change cipher spec 就结束，因为他自动就把三个记录都发送出去了。我现在就是想先找出问题出在哪个包上。你有qq吗，我加你，看连连你的服务器怎么样！加上QQ比较方便

**Comment by gujinqiangggs** [comment]
592581567

**Comment by guanzhi** [comment]
@zhangshuang01 @gujinqiangggs 请尽可能在公开的issues 系统中进行交流，这也是对本开源项目的支持。

**Comment by gujinqiangggs** [comment]
@guanzhi 好的，关大。支持肯定是支持，但是有时一些小问题，这个交流不太方便。另外我们也怕烦扰到大家。

**Comment by zhangshuang01** [comment]
@guanzhi  好的，那么好的平台当然要支持，我当时也是怕打扰到大家。

**Comment by AivenYoung** [comment]
@gujinqiangggs 您好，我看到您也在实现国密ssl握手，请问您当前用来测试的证书和私钥可以从哪里获取到呢？我当前调试，总是报错，怀疑跟证书和私钥相关。

**Comment by gujinqiangggs** [comment]
我是自己生成的证书和私钥。这个可以用来和360浏览器进行ssl握手，通过抓包也可以正常看到整个握手流程正常结束。但是360浏览器会显示一堆乱码，而不是server端发送的数据，360提示错误，但是其实已经握手成功了。你通过抓包来确定什么问题吧。至于360认识哪些证书，我也不清楚。

**Comment by 1132719438** [comment]
@gujinqiangggs 您是否已经实现了使用ECC_SM4_SM3套件的ssl通信，基于GMSSL-v1还是GMSSL-master分支？
