### ISSUE TITLE
GMTLS单向认证ServerKeyExchange阶段失败

### ISSUE THREAD

**Issue by dean-gh** [guanzhi/GmSSL#862]
使用gmtls协议，单向认证，Ciphers Suite协商选择ECC_SM4_SM3，服务器发送ServerKeyExchange消息，客户端验证失败:

crypto\sm2\sm2_sign.c 504: sm2_do_verify
 6720:error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl\statem\statem_gmtls.c:895:

![result-1](https://user-images.githubusercontent.com/9319779/66725171-392d0180-ee61-11e9-9af4-9d686ad4c08f.png)
![result-2](https://user-images.githubusercontent.com/9319779/66725172-39c59800-ee61-11e9-99ad-304b21ab74c3.png)
![brower-visit-result](https://user-images.githubusercontent.com/9319779/66725263-c6248a80-ee62-11e9-82b3-d0270a92c6e3.png)

**环境**

- Server OS:windows server 2012 + 沃通支持国密ssl的ngnix + 沃通国密SM2数字证书(使用国密密信浏览器可以正常访问搭建好的web服务器)

- Client OS: win7 x64 命令行：gmssl s_client -connect 172.16.22.125:443 -gmtls

- Compiler: cl.exe(vs2013)

- GmSSL版本：基于节点a097e49719ac736e5a895ff3ddd25e26578d378f（GmSSL 2.5.4 - OpenSSL 1.1.0d 6 Sep 2019）

**Comment by abxcd111** [comment]
请问，gmssl是怎么指定使用什么加密套件的？

**Comment by wuyougongzi** [comment]
请问下您该问题解决了，同样遇到了。

**Comment by wuyougongzi** [comment]
具体跟进去看着是验签不过，但是我这边使用的不是这个版本是另一个tassl的版本

**Comment by wuyougongzi** [comment]
使用gmssl连接报了同样的错误。
