### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by github-zhongjiaxiang** [guanzhi/GmSSL#863]
**Describe the bug**
engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function)
     return syscall(__NR_eventfd, n);

**Environments**
aarch64 kylin

**Comment by github-zhongjiaxiang** [comment]
> **Describe the bug**
> engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function)
> return syscall(__NR_eventfd, n);
> 
> **Environments**
> aarch64 kylin

replace with __NR_eventfd2 to fix it.

**Comment by liyuzhao** [comment]
./libcrypto.so: undefined reference to `EC_GFp_sm2z256_method'

zen me ban ?
