### ISSUE TITLE
linux下编码32位gmssl

### ISSUE THREAD

**Issue by Dillon14281118** [guanzhi/GmSSL#873]
请问如何在64位linux系统里编译出32位gmssl动态链接库？

**Comment by xiaobingxianzi** [comment]
https://blog.csdn.net/whatday/article/details/96995767 试试

**Comment by Dillon14281118** [comment]
> https://blog.csdn.net/whatday/article/details/96995767 试试

按这个博客试了还是没有成功，官方有编译好的库吗
