### ISSUE TITLE
openwrt交叉编译后在解析证书时获取SHA1指纹时崩溃

### ISSUE THREAD

**Issue by yaoyuanyylyy** [guanzhi/GmSSL#876]
这可能不算是个bug，但确实是个问题。

在用openwrt的编译器交叉编译后用于openvpn中时，握手时证书验证失败，程序退出，提示Segmentation fault。
原因是openvpn中的x509_get_sha1_fingerprint调用X509_digest获取证书SHA1指纹时，在gmssl的x_all.c的X509_digest代码中：
#ifndef OPENSSL_NO_SHA
    if (type == EVP_sha1() && (data->ex_flags & EXFLAG_SET) != 0) {
        /* Asking for SHA1 and we already computed it. */
        if (len != NULL)
            *len = sizeof(data->sha1_hash);
        memcpy(md, data->sha1_hash, sizeof(data->sha1_hash));
        return 1;
    }
#endif
sizeof(data->sha1_hash)的长度变成了32，导致内存溢出，程序崩溃。
data->sha1_hash字段的长度是在sha.h中定义的一个宏，值为20。通过在编译时打印宏的值来查看，也的确是20。但是openwrt的openvpn中解析证书后data->sha1_hash的内存空间为32字节，于是在X509_digest的快速拷贝后，内存溢出，从而使得openvpn的gc出错。到底是在什么时候从20字节变更到32字节，还不清楚。

解决方法：
1.可以去掉X509_digest中的直接拷贝sha1指纹的代码；
2.可以在openvpn的x509_get_sha1_fingerprint给sha1哈希值申请更大的buffer；

**Comment by libradoge** [comment]
您好，请问您在使用openwrt交叉编译器编译时是否碰到这样的错误？
./libcrypto.a(async_posix.o): In function `ASYNC_is_capable':
async_posix.c:(.text+0x10): undefined reference to `getcontext'
async_posix.c:(.text+0x1c): undefined reference to `getcontext'
./libcrypto.a(async_posix.o): In function `async_fibre_makecontext':
async_posix.c:(.text+0x4c): undefined reference to `getcontext'
async_posix.c:(.text+0x60): undefined reference to `getcontext'
async_posix.c:(.text+0xbc): undefined reference to `makecontext'
async_posix.c:(.text+0xd4): undefined reference to `makecontext'
./libcrypto.a(async.o): In function `async_fibre_swapcontext.constprop.4':
async.c:(.text+0x54): undefined reference to `setcontext'
async.c:(.text+0x5c): undefined reference to `setcontext'

如果没有的话是否可以分享一下您是如何生成makefile文件的？

**Comment by libradoge** [comment]
> 这可能不算是个bug，但确实是个问题。
> 
> 在用openwrt的编译器交叉编译后用于openvpn中时，握手时证书验证失败，程序退出，提示Segmentation fault。
> 原因是openvpn中的x509_get_sha1_fingerprint调用X509_digest获取证书SHA1指纹时，在gmssl的x_all.c的X509_digest代码中：
> #ifndef OPENSSL_NO_SHA
> if (type == EVP_sha1() && (data->ex_flags & EXFLAG_SET) != 0) {
> /* Asking for SHA1 and we already computed it. */
> if (len != NULL)
> *len = sizeof(data->sha1_hash);
> memcpy(md, data->sha1_hash, sizeof(data->sha1_hash));
> return 1;
> }
> #endif
> sizeof(data->sha1_hash)的长度变成了32，导致内存溢出，程序崩溃。
> data->sha1_hash字段的长度是在sha.h中定义的一个宏，值为20。通过在编译时打印宏的值来查看，也的确是20。但是openwrt的openvpn中解析证书后data->sha1_hash的内存空间为32字节，于是在X509_digest的快速拷贝后，内存溢出，从而使得openvpn的gc出错。到底是在什么时候从20字节变更到32字节，还不清楚。
> 
> 解决方法：
> 1.可以去掉X509_digest中的直接拷贝sha1指纹的代码；
> 2.可以在openvpn的x509_get_sha1_fingerprint给sha1哈希值申请更大的buffer；

您好，请问您在使用openwrt交叉编译器编译时是否碰到这样的错误？
./libcrypto.a(async_posix.o): In function ASYNC_is_capable': async_posix.c:(.text+0x10): undefined reference to getcontext'
async_posix.c:(.text+0x1c): undefined reference to getcontext' ./libcrypto.a(async_posix.o): In function async_fibre_makecontext':
async_posix.c:(.text+0x4c): undefined reference to getcontext' async_posix.c:(.text+0x60): undefined reference to getcontext'
async_posix.c:(.text+0xbc): undefined reference to makecontext' async_posix.c:(.text+0xd4): undefined reference to makecontext'
./libcrypto.a(async.o): In function async_fibre_swapcontext.constprop.4': async.c:(.text+0x54): undefined reference to setcontext'
async.c:(.text+0x5c): undefined reference to `setcontext'

如果没有的话是否可以分享一下您是如何生成makefile文件的？
