### ISSUE TITLE
SDF引擎使用

### ISSUE THREAD

**Issue by wepe912** [guanzhi/GmSSL#878]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
按照官网上的SDF方法无法使用SDF:

gmssl engine sdf
Using configuration from /usr/local/ssl/openssl.cnf
140611799078656:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/local/lib64/engines-1.1/sdf.so): /usr/local/lib64/engines-1.1/sdf.so: cannot open shared object file: No such file or directory
140611799078656:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
140611799078656:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
140611799078656:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=sd

**Comment by wepe912** [comment]
编译出来的没有sdf.so这个文件，请问一哈是在编译前需要做什么配置吗

**Comment by fidderdan** [comment]
Sdk  skf 不带的，需要自己写

**Comment by wepe912** [comment]
> Sdk skf 不带的，需要自己写

哦，谢谢哈，有没有例子或者示例之类的，第一次接触，啥子都不懂，还望指教

**Comment by fidderdan** [comment]
例子可以看engines下的代码，可以提供有偿帮助

**Comment by zhangyingsk8** [comment]
> 例子可以看engines下的代码，可以提供有偿帮助
怎么联系

**Comment by changguangsheng** [comment]
> 例子可以看engines下的代码，可以提供有偿帮助

怎么联系阿
