### ISSUE TITLE
关老师好，GmSSL的SM2的签名算法 有对Za进行拼接做 hash 吗？

### ISSUE THREAD

**Issue by YYQuae** [guanzhi/GmSSL#879]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ccjinghang** [comment]
Can I ask you a question？
Whether the evp framework supports sm2？
Can I have some routines?
Thank you！

**Comment by YYQuae** [comment]
@ccjinghang 编译出来的动态链接库 直接调用其中的签名接口，好像 没有调用到 底层的SM2（sm2_sign.c文件）实现，所以签名出来的结果 不是SM2签名该有的结果，不知道是不是我这边编译的问题，我之前做过Java版本的SM2签名验签，

**Comment by ccjinghang** [comment]
@YYQuae  我实现了SM2的签名，代码如下
struct AlgorithmParams
{
	const char *public_key;
	const char *private_key;
	int pri_key_len;
	int pub_key_len;
	const char *str_in;
	int str_in_len;
	char *str_out;
	int str_out_len;
	const char *iv;
	int  pendding;   //0 不填充  默认填充
};
int sm2_sign(struct AlgorithmParams *param)
{
	if(NULL == param)
	{
		fprintf(stderr, "%s() failed to sm2_sign\n", __func__);
		return -1;
	}
	char szErr[1024];
	int nRet = 0;
	int value = 0;
	EVP_PKEY *pkey = NULL;
	const EVP_MD *md = NULL;
    EVP_MD_CTX *mdctx = NULL;
	if(!(pkey = covert_string_evp_pkey_new(param->private_key,0)))
	{
		printf("__LINE__=%d\n",__LINE__);
		return -1;
	}

	md = EVP_sm3();
	if(!(mdctx=EVP_MD_CTX_new()))
	{
		fprintf(stderr, "%s() failed to call EVP_MD_CTX_new\n", __func__);
		nRet = -1;
		goto sign_ret;
	}

	if(!EVP_SignInit_ex(mdctx, md, NULL))
	{
		value  = ERR_get_error();
        ERR_error_string( value, szErr );
        fprintf( stderr,"OpenSSL_Sign: EVP_SignUpdate failed: \nopenssl return %d, %s\n", value, szErr );
		nRet = -1;
		goto sign_ret;
	}

	if(!EVP_SignUpdate(mdctx, param->str_in, param->str_in_len))
	{
		value  = ERR_get_error();
        ERR_error_string( value, szErr );
        fprintf( stderr,"OpenSSL_Sign: EVP_SignUpdate failed: \nopenssl return %d, %s\n", value, szErr );
		nRet = -2;
		goto sign_ret;
	}

	if(!EVP_SignFinal(mdctx, param->str_out, &(param->str_out_len),pkey))
	{
		value  = ERR_get_error();
        ERR_error_string( value, szErr );
        fprintf( stderr,"OpenSSL_Sign: EVP_SignFinal failed: \nopenssl return %d, %s\n", value, szErr );
		nRet = -3;
		goto sign_ret;
	}

sign_ret:
    /*if( !EVP_MD_CTX_cleanup(mdctx) ) {
        value  = ERR_get_error();
        ERR_error_string( value, szErr );
        fprintf( stderr,"OpenSSL_Sign: EVP_ctx_cleanup failed: \nopenssl return %d, %s\n", value, szErr );
    }*/
	EVP_PKEY_free(pkey);
    EVP_MD_CTX_destroy(mdctx);
    return nRet;
}
但是，我现在遇到个问题，PEM格式的秘钥可以生成EVP_PKEY内部结构。原始字符串秘钥（hex编码）无法生成EVP_PKEY内部结构，你有什么好的解决办法么？
