### ISSUE TITLE
SM2_do_encrypt或SM2_encrypt加密结果都是30开头的，怎么转换成04开头了？

### ISSUE THREAD

**Issue by itollei** [guanzhi/GmSSL#880]
大家好，我在用SM2进行加解密时，使用如下代码可以正常加解密，得到的加密结果是30开头的。但是我想将加密结果转换成04开头的，请问如何转换？
int sm2_encrypt(const char *xP, const char *yP,
                    const char *M, const char *k,
                    unsigned char *output, unsigned long *olen) {
    int ret = 1;
    const EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
    EC_KEY *pub_key = NULL;
    SM2CiphertextValue *cv = NULL;
    unsigned char *mbuf = NULL;
    unsigned char cbuf[sizeof(mbuf) + 256] = {0};
    size_t clen;
    unsigned char *p;
    
    if (!(pub_key = new_ec_key(group, NULL, xP, yP, NULL, NULL))) {
        goto end;
    }
    
    change_rand(k);
    if (!(cv = SM2_do_encrypt(EVP_sm3(), (unsigned char *)M, strlen(M), pub_key))) {
        goto end;
    }

    p = cbuf;
    if ((clen = i2o_SM2CiphertextValue(group, cv, &p)) <= 0) {
        goto end;
    }

    if (!(*olen = i2d_SM2CiphertextValue(cv, &output))) {
        goto end;
    }

    ret = 0;
end:
    ERR_print_errors_fp(stderr);
    restore_rand();
    EC_KEY_free(pub_key);
    return ret;
}

int sw_sm2_decrypt(const char *priKey, const unsigned char *pin, unsigned long inLen, unsigned char *output, unsigned long *olen)
{
    int ret = 1;
    const EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_sm2p256v1);
    SM2CiphertextValue *cv = NULL;
    EC_KEY *pri_key = NULL;

    if (!(pri_key = new_ec_key(group, priKey, NULL, NULL, NULL, NULL))) {
        goto end;
    }
    
    if (!(cv = d2i_SM2CiphertextValue(&cv, &pin, inLen))) {
        goto end;
    }

    if (!SM2_do_decrypt(EVP_sm3(), cv, output, olen, pri_key)) {
        goto end;
    }
    
    ret = 0;

end:
    ERR_print_errors_fp(stderr);
    restore_rand();
    EC_KEY_free(pri_key);
    SM2CiphertextValue_free(cv);
    return ret;
}

**Comment by itollei** [comment]
哪位老师知道，请告知下，谢谢！

**Comment by Mojicode** [comment]
我使用的GmSSL版本出来的也是04开头，现在别人给我的即不是04开头，也不是30开头，我在别人给我的密文前加04，然后解密仍然不行，不知是否有方法了？
[使用场景](https://github.com/guanzhi/GmSSL/issues/707#issuecomment-662923112)

**Comment by ArbitraryToYou** [comment]
You should describe it with English! And would you resolve it?Please help me.
