### ISSUE TITLE
使用GMTLS进行双向认证的问题

### ISSUE THREAD

**Issue by WindsOfWorld** [guanzhi/GmSSL#881]
使用GMTLS进行双向认证时，在客户端回服务器端证书时出现如下现象：
140653455197952:error:141B518F:SSL routines:gmtls_output_cert_chain:ee key too small:ssl/statem/statem_gmtls.c:128:
140653455197952:error:141B7044:SSL routines:gmtls_construct_client_certificate:internal error:ssl/statem/statem_gmtls.c:1347:

系统版本：Linux ubuntu 4.15.0-66-generic #75~16.04.1-Ubuntu
使用命令：
gmssl s_server -gmtls -accept 1112 -cert server1sm2.crt -key server1sm2.key -dcert server2sm2.crt -dkey server2sm2.key -verify 1 -CAfile ca.crt -msg -debug
gmssl s_client -gmtls -connect 127.0.0.1:1112 -CAfile ca.crt -cert client1sm2.crt -key client1sm2.key -xcert client2sm2.crt -xkey client2sm2.key -msg -debug

**Comment by tengliu0929** [comment]
如何解决呢，试了好几个版本了

**Comment by chenshiruchao** [comment]
你解决了吗？我也是这个问题。

**Comment by changguangsheng** [comment]
> 你解决了吗？我也是这个问题。

请问解决了么

**Comment by Chadlucc** [comment]
我也是，请问啥情况
