### ISSUE TITLE
请问有什么工具可以测试nginx gmssl的性能吗？

### ISSUE THREAD

**Issue by liqiaochu-happy** [guanzhi/GmSSL#884]
现在已经搭建好了nginx依赖于gmssl的服务器，使用360国密浏览器能正常访问nginx。目前想要测试nginx的性能，请问我可以使用什么测试工具来测试呢？

**Comment by Nu1i** [comment]
请问使用360国密浏览器访问都需要修改哪些地方？

**Comment by liqiaochu-happy** [comment]
> 请问使用360国密浏览器访问都需要修改哪些地方？

gmssl对协议的实现和360的稍微有些不同，需要改几处源码。
nginx就主要让它能识别GMTLS协议就可以，也是稍微改一下源码即可。

**Comment by Nu1i** [comment]
能否提供下您修改完的GMSSL？

**Comment by liqiaochu-happy** [comment]
> 能否提供下您修改完的GMSSL？

有需要咨询修改好的gmssl加我qq 2725329937

**Comment by neighbads** [comment]
测试性能有用过  siege ，更换 gmssl 重新编译使支持 gmtls 协议。
