### ISSUE TITLE
aarch64下test出错

### ISSUE THREAD

**Issue by iamwjia** [guanzhi/GmSSL#887]
**Describe the bug**
编译通过，make test未通过，环境如下：
编译参数：
./config -DGMSSL_NO_TURBO no-afalgeng

编译通过，但执行make test报错，有较多的失败项，其中../test/recipes/30-test_evp.t报double free，../test/recipes/70-test_sslcbcpadding.t卡住。

**Expected behavior**
make test正常

**Screenshots**
../test/recipes/30-test_evp.t .............. *** Error in `./evp_test': double free or corruption (!prev): 0x00000000004427e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d67c)[0x7f9a5bb67c]
../util/../libcrypto.so.1.1(EVP_CIPHER_CTX_reset+0x50)[0x7f9a86c3d4]
../util/../libcrypto.so.1.1(EVP_CIPHER_CTX_free+0x14)[0x7f9a86c468]
./evp_test[0x4062b4]
./evp_test[0x404928]
./evp_test[0x402700]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7f9a55f714]
./evp_test[0x402b2c]
======= Memory map: ========
00400000-00409000 r-xp 00000000 fe:02 101609038                          /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/test/evp_test
0041f000-00420000 r--p 0000f000 fe:02 101609038                          /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/test/evp_test
00420000-00421000 rw-p 00010000 fe:02 101609038                          /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/test/evp_test
00421000-00463000 rw-p 00000000 00:00 0                                  [heap]
7f94000000-7f94021000 rw-p 00000000 00:00 0
7f94021000-7f98000000 ---p 00000000 00:00 0
7f9a4f4000-7f9a507000 r-xp 00000000 fe:00 39327245                       /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f9a507000-7f9a523000 ---p 00013000 fe:00 39327245                       /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f9a523000-7f9a524000 r--p 0001f000 fe:00 39327245                       /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f9a524000-7f9a525000 rw-p 00020000 fe:00 39327245                       /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f9a53e000-7f9a6a5000 r-xp 00000000 fe:00 33774679                       /usr/lib64/libc-2.17.so
7f9a6a5000-7f9a6ba000 ---p 00167000 fe:00 33774679                       /usr/lib64/libc-2.17.so
7f9a6ba000-7f9a6be000 r--p 0016c000 fe:00 33774679                       /usr/lib64/libc-2.17.so
7f9a6be000-7f9a6c0000 rw-p 00170000 fe:00 33774679                       /usr/lib64/libc-2.17.so
7f9a6c0000-7f9a6c4000 rw-p 00000000 00:00 0
7f9a6c4000-7f9a6db000 r-xp 00000000 fe:00 33723252                       /usr/lib64/libpthread-2.17.so
7f9a6db000-7f9a6f3000 ---p 00017000 fe:00 33723252                       /usr/lib64/libpthread-2.17.so
7f9a6f3000-7f9a6f4000 r--p 0001f000 fe:00 33723252                       /usr/lib64/libpthread-2.17.so
7f9a6f4000-7f9a6f5000 rw-p 00020000 fe:00 33723252                       /usr/lib64/libpthread-2.17.so
7f9a6f5000-7f9a6f9000 rw-p 00000000 00:00 0
7f9a6f9000-7f9a6fc000 r-xp 00000000 fe:00 33621698                       /usr/lib64/libdl-2.17.so
7f9a6fc000-7f9a718000 ---p 00003000 fe:00 33621698                       /usr/lib64/libdl-2.17.so
7f9a718000-7f9a719000 r--p 0000f000 fe:00 33621698                       /usr/lib64/libdl-2.17.so
7f9a719000-7f9a71a000 rw-p 00010000 fe:00 33621698                       /usr/lib64/libdl-2.17.so
7f9a723000-7f9a733000 rw-p 00000000 00:00 0
7f9a733000-7f9a9c8000 r-xp 00000000 fe:02 67999069                       /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/libcrypto.so.1.1
7f9a9c8000-7f9a9e5000 ---p 00295000 fe:02 67999069                       /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/libcrypto.so.1.1
7f9a9e5000-7f9aa03000 r--p 002a2000 fe:02 67999069                       /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/libcrypto.so.1.1
7f9aa03000-7f9aa0e000 rw-p 002c0000 fe:02 67999069                       /home/gwi/work/SVN/03 code/OS_Src/gmssl/GmSSL/libcrypto.so.1.1
7f9aa0e000-7f9aa10000 rw-p 00000000 00:00 0
7f9aa10000-7f9aa2e000 r-xp 00000000 fe:00 33774672                       /usr/lib64/ld-2.17.so
7f9aa37000-7f9aa3d000 rw-p 00000000 00:00 0
7f9aa3d000-7f9aa3e000 r--p 00000000 00:00 0                              [vvar]
7f9aa3e000-7f9aa3f000 r-xp 00000000 00:00 0                              [vdso]
7f9aa3f000-7f9aa40000 r--p 0001f000 fe:00 33774672                       /usr/lib64/ld-2.17.so
7f9aa40000-7f9aa41000 rw-p 00020000 fe:00 33774672                       /usr/lib64/ld-2.17.so
7f9aa41000-7f9aa42000 rw-p 00000000 00:00 0
7fdf015000-7fdf036000 rw-p 00000000 00:00 0                              [stack]

**Environments**
- OS：CentOS 7.6
- CPU： aarch64（飞腾）
- 软件版本：
openssl-1.0.2k-19.el7.aarch64
openssl-libs-1.0.2k-19.el7.aarch64
openssl-pkcs11-0.4.8-2.el7.aarch64
openssl-devel-1.0.2k-19.el7.aarch64
gcc-4.8.5-39.el7.aarch64
glibc-2.17-292.el7.aarch64

**Additional context**
non

**Comment by simon28li** [comment]
@iamwjia 到目前为止，你的问题有得到解决吗？我也遇到了相同的问题，是不是因为测试用例还有许多待改进的地方才导致这么多测试不过的呢，我看社区好像不太活跃，2016年之后就没有发布过正式版本了。

**Comment by iamwjia** [comment]
> @iamwjia 到目前为止，你的问题有得到解决吗？我也遇到了相同的问题，是不是因为测试用例还有许多待改进的地方才导致这么多测试不过的呢，我看社区好像不太活跃，2016年之后就没有发布过正式版本了。

我现在在使用openssl3.0来进行SM相关的处理了
