### ISSUE TITLE
现在Github上最新的master版本编译错误

### ISSUE THREAD

**Issue by sslvpn007** [guanzhi/GmSSL#89]
如下：

crypto/saf/saf_ec.c:360:31: error: use of undeclared identifier 'ECCrefPublic';
      did you mean 'ECCrefPublicKey'?
        if (uiPublicKeyLen != sizeof(ECCrefPublic)) {
                                     ^
include/openssl/sdf.h:120:3: note: 'ECCrefPublicKey' declared here
} ECCrefPublicKey;
  ^
crypto/saf/saf_ec.c:411:31: error: use of undeclared identifier 'ECCrefPublic';
      did you mean 'ECCrefPublicKey'?
        if (uiPublicKeyLen != sizeof(ECCrefPublic)) {
                                     ^
include/openssl/sdf.h:120:3: note: 'ECCrefPublicKey' declared here
} ECCrefPublicKey;
  ^
crypto/saf/saf_ec.c:445:2: error: use of undeclared identifier 'ret'
        ret = SAR_Ok;
        ^
crypto/saf/saf_ec.c:448:9: error: use of undeclared identifier 'ret'
        return ret;
               ^
crypto/saf/saf_ec.c:477:23: error: expected ';' after return statement
                return SAR_IndataErr);
                                    ^
                                    ;
crypto/saf/saf_ec.c:479:31: error: use of undeclared identifier 'uiCertificate';
      did you mean 'pucCertificate'?
        if (uiCertificateLen <= 0 || uiCertificate > INT_MAX) {
                                     ^~~~~~~~~~~~~
                                     pucCertificate
crypto/saf/saf_ec.c:461:17: note: 'pucCertificate' declared here
        unsigned char *pucCertificate,
                       ^
crypto/saf/saf_ec.c:479:45: warning: ordered comparison between pointer and
      integer ('unsigned char *' and 'int')
        if (uiCertificateLen <= 0 || uiCertificate > INT_MAX) {
                                     ~~~~~~~~~~~~~ ^ ~~~~~~~
crypto/saf/saf_ec.c:550:23: error: expected ';' after return statement
                return SAR_IndataErr);
                                    ^
                                    ;
crypto/saf/saf_ec.c:552:31: error: use of undeclared identifier 'uiCertificate';
      did you mean 'pucCertificate'?
        if (uiCertificateLen <= 0 || uiCertificate > INT_MAX) {
                                     ^~~~~~~~~~~~~
                                     pucCertificate
crypto/saf/saf_ec.c:461:17: note: 'pucCertificate' declared here
        unsigned char *pucCertificate,
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
5 warnings and 20 errors generated.
make[1]: *** [crypto/saf/saf_ec.o] Error 1
make: *** [all] Error 2

**Comment by sslvpn007** [comment]
之前的版本 编译安装没问题

**Comment by crawfishvv** [comment]
我也遇到这个错误，编译参数加上no-saf no-skf 不编译这2个模块，最后还是遇到EVP_PKEY_CTX_set_ec_sign_type未定义，好像这个新版本比之前修改了非常多东西。

**Comment by guanzhi** [comment]
./config shared 可以编译动态库
