### ISSUE TITLE
使用自签名sm2证书，浏览器提示“使用了不受支持的协议”

### ISSUE THREAD

**Issue by tmaccs** [guanzhi/GmSSL#894]
我编译apache httpd的时候设置了--with-ssl=/usr/local/gmssl
试用Gmssl生成的server.key和server.crt， httpd能够正常启动，但是使用密信浏览器访问这个服务器的时候，一直显示：

此网站无法提供安全连接
10.22.2.112 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

我的ssl.conf配置:
Listen 443
<VirtualHost *:443>
ServerName localhost
DocumentRoot "/var/www/web_console"
ErrorLog logs/ssl_error_log
TransferLog logs/ssl_access_log
LogLevel warn
SSLEngine on
SSLCertificateFile /usr/local/httpd/conf/10.22.2.112.crt
SSLCertificateKeyFile /usr/local/httpd/conf/10.22.2.112.key
SSLProtocol all -SSLv2 -SSLv3
#SSLCipherSuite EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:SM2-WITH-SMS4-SM3:ECDH:AESGCM:HIGH:!RC4:!DH:!MD5:!aNULL:!eNULL
SSLCipherSuite ECDHE-SM2-WITH-SMS4-GCM-SM3:SM2-WITH-SMS4-SM3:ECDH:AESGCM:HIGH:!RC4:!DH:!MD5:!aNULL:!eNULL
#SSLCipherSuite ECDHE-SM4-SM3:SM2-WITH-SMS4-SM3:ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!3DES:!MD5:!ADH:!RC4:!DH:!DHE
SSLHonorCipherOrder on
<Directory "/var/www/web_console">
Options -Indexes -FollowSymLinks +ExecCGI
AllowOverride None
Order allow,deny
Allow from all
Require all granted

有遇到过这个问题吗？
谢谢！

**Comment by sunlongxiang** [comment]
用Nginx也遇到同样的问题，不知道如何解决

**Comment by tmaccs** [comment]
> 用Nginx也遇到同样的问题，不知道如何解决

最后我用nginx + tls了
https://blog.csdn.net/tmaccs/article/details/103293957

**Comment by sunlongxiang** [comment]
我编译好了，但按照这个方法nginx一直无法成功配置，能麻烦告知一下nginx如何配置stream吗？我使用的是自带的sm2证书

**Comment by tmaccs** [comment]
> 我编译好了，但按照这个方法nginx一直无法成功配置，能麻烦告知一下nginx如何配置stream吗？我使用的是自带的sm2证书

stream就按照文档里面那样配置应该没问题吧
