### ISSUE TITLE
gmssl可以使用指定已有的sm2公钥生成证书吗

### ISSUE THREAD

**Issue by tugangkai** [guanzhi/GmSSL#895]
gmssl可以使用指定已有的sm2公钥生成证书吗

**Comment by xiaobingxianzi** [comment]
没看懂。如果手边已经有了SM2的CA证书以及对应的私钥，是可以用来指定生成新的证书的

**Comment by tugangkai** [comment]
我目前通过加密机生成了一对sm2公私钥对，现在需要根据sm2公钥生成证书，因为私钥是加密机保护的密文，所以不能导出来，目前工具是自己先生成私钥，在根据私钥生成公钥，然后生成证书

**Comment by neighbads** [comment]
肯定可以，直接拼X509结构，然后用 CA 私钥签名

或者用加密机签名封装的 P10，然后用CA签发

**Comment by zhengshundong01** [comment]
大佬们请教一个问题：
