### ISSUE TITLE
计算SM3，window的结算结果和linux下不一致

### ISSUE THREAD

**Issue by chtctc** [guanzhi/GmSSL#896]
各位大神好：
     有个问题请教一下：
     我做了一个计算SM3的函数，发现window(32位)的结果和linux(64位)下的结果不一致。
    函数：
    int IccSm_Sm3Digest(unsigned int In_UserIdLen, unsigned char* In_UserId,
	                unsigned int In_X_Len, unsigned char* In_X, unsigned int In_Y_Len, unsigned char* In_Y,
	                unsigned int In_HashDataLen, unsigned char* In_HashData, unsigned int* Out_Hash_Len, unsigned char* Out_Hash)
{
	unsigned char dgst[SM3_DIGEST_LENGTH+1];
	unsigned int dgstlen = 0;

	sm3_ctx_t ctx;
	memset(&ctx, 0, sizeof(sm3_ctx_t));	
		
	memset(dgst, 0, sizeof(dgst));
	if (In_UserIdLen > 0 && In_X_Len > 0 && In_Y_Len > 0)
	{
		printf((char*)"In_UserId[%d][%s]\n", (int)strlen((char*)In_UserId), In_UserId);	
		printf((char*)"In_X[%d][%s]\n",  (int)strlen((char*)In_X), In_X);	
		printf((char*)"In_Y[%d][%s]\n",  (int)strlen((char*)In_Y), In_Y);	
		if (!sm3_sm2_init(&ctx, (const char*)In_UserId, In_X, In_Y))
			return -1;
	}
	else
	{
		sm3_init(&ctx);
	}

	sm3_update(&ctx, In_HashData, In_HashDataLen);
	sm3_final(&ctx, dgst);

	*Out_Hash_Len = dgstlen = SM3_DIGEST_LENGTH;
	memcpy(Out_Hash, dgst, *Out_Hash_Len);
	
	return 0;
}

用一下测试数据发现windows下和linux下结果不一致
用户ID:1234567812345678
公钥X:ADEEC44552D8EF22A965FCBFC72F50DACBAE27C2FBF35BD5D177E06DBB2EC329
公钥Y:780D57A10B21BBD71092A1011CC6197409882BCFF829A50EAD547FD7A4BDDC83
数据HEX:1122334455667788

window下出来是0C6B4D88AF779A1ECF031C2246DDF9D51A61580D9AF6C116D8F1C6570E4498F7
linux下出来是150C285D35CFD506B8D250CF45F8772B7E6999DD97E883C7950F5BC5FCA53DC4

linux下的日志：
in_id_data[16][1234567812345678]
in_x_data[64][ADEEC44552D8EF22A965FCBFC72F50DACBAE27C2FBF35BD5D177E06DBB2EC329]
in_y_data[64][780D57A10B21BBD71092A1011CC6197409882BCFF829A50EAD547FD7A4BDDC83]
[in_hash_data]:1122334455667788
[outhash]:150C285D35CFD506B8D250CF45F8772B7E6999DD97E883C7950F5BC5FCA53DC4

帮忙大神分析一下，是什么原因

**Comment by UMU618** [comment]
@chtctc 不是非要一样的。

PS: 你这标题不明确，其实是 SM2 ECC + SM3 hash，不只是 SM3 hash

**Comment by chtctc** [comment]
@UMU618 好的，谢谢

**Comment by Mr-watermelon** [comment]
解决了么？
