### ISSUE TITLE
您好，我在执行 gmssl version 命令的时候报错。

### ISSUE THREAD

**Issue by CavaPhPy** [guanzhi/GmSSL#899]
**bug详情**
安装完成之后，执行 `gmssl version` 命令，提示以下错误：

`gmssl: symbol BIO_debug_callback version OPENSSL_1_1_0d not defined in file libcrypto.so.1.1 with link time reference`

**环境**
- OS: Ubuntu 18.04.2 LTS
- Compiler: Linux version 4.15.0-70-generic (buildd@lgw01-amd64-055) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))

**临时解决方案**
目前在开发当中，使用网上提供的这个方案能暂时解决 [链接](https://www.cnblogs.com/wangzihong0213/p/10856875.html) ，但是需要覆盖掉系统原本OpenSSL的部分文件。

请问我应该做些什么，或者说修改哪些源文件，来真正解决这个异常呢？

**Comment by JasonHonor** [comment]
I had the same problem, anyone help ?

**Comment by zhaoxiaomeng** [comment]
root@calgroup:~# export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
将动态库位置加入 LD_LIBRARY_PATH。
