### ISSUE TITLE
centos 64bits编译失败

### ISSUE THREAD

**Issue by lvmengkeji** [guanzhi/GmSSL#9]
centos 6.5 x86_64，make的时候失败：

       link_app.${shlib_target}
make[2]: Entering directory `/root/tmp/GmSSL-master/apps'
( :; LIBDEPS="${LIBDEPS:--L.. -lssl  -L.. -lcrypto -ldl}"; LDCMD="${LDCMD:-gcc}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM}"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=gmssl} gmssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o ${LIBDEPS} )
../libcrypto.a(ecp_nistz256.o): In function `ecp_nistz256_points_mul':
ecp_nistz256.c:(.text+0x67c): undefined reference to `ecp_nistz256_select_w7'
ecp_nistz256.c:(.text+0x699): undefined reference to `ecp_nistz256_neg'
ecp_nistz256.c:(.text+0x857): undefined reference to `ecp_nistz256_select_w7'
ecp_nistz256.c:(.text+0x867): undefined reference to `ecp_nistz256_neg'
ecp_nistz256.c:(.text+0x90e): undefined reference to `ecp_nistz256_point_add_affine'
ecp_nistz256.c:(.text+0xc06): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xea0): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xeba): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xee0): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xef0): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xf0c): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xf23): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xf42): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xf63): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xf7a): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xf91): undefined reference to `ecp_nistz256_point_add'
ecp_nistz256.c:(.text+0xfa1): undefined reference to `ecp_nistz256_point_double'
ecp_nistz256.c:(.text+0xfbd): undefined reference to `ecp_nistz256_point_double'

**Comment by lanzhiwen** [comment]
编译的时候先要删除这个文件才可编译通过
rm crypto/ec/ecp_nistz256-x86_64.s

**Comment by lvmengkeji** [comment]
编过了，感谢
