### ISSUE TITLE
macos 下 编译 arm64 ，报错 ERR_load_ASYNC_strings

### ISSUE THREAD

**Issue by Panda-2009** [guanzhi/GmSSL#900]
输入命令：
ppLo@bogon:ggg/GmSSL-gmbrowser-v0.1 $ ./Configure ios64-cross no-shared -DOPENSSL_NO_ASYNC
ppLo@bogon:ggg/GmSSL-gmbrowser-v0.1 $ make

报错信息：
rypto/err/err_all.c:175:9: error: implicit declaration of function 'ERR_load_ASYNC_strings' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ERR_load_ASYNC_strings() == 0 ||
        ^
crypto/err/err_all.c:175:9: note: did you mean 'ERR_load_ASN1_strings'?
include/openssl/asn1.h:882:5: note: 'ERR_load_ASN1_strings' declared here
int ERR_load_ASN1_strings(void);
    ^
1 error generated.
make[1]: *** [crypto/err/err_all.o] Error 1
make: *** [all] Error 2

**Comment by itollei** [comment]
我也遇到同样的问题。因为苹果审核要求不能使用私有api，通过检测，发现在async_posix.c有使用过，编译时增加DOPENSSL_NO_ASYNC参数控制不编译异步，但是make时报错了。
