### ISSUE TITLE
客户端连接服务器失败

### ISSUE THREAD

**Issue by jxdeng3264** [guanzhi/GmSSL#906]
失败的错误码如下：
140568036109184:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1385:SSL alert number 80

想问下这个地方一般是什么原因

**Comment by zhaoxiaomeng** [comment]
请问是用 s_client 和 s_server 链接的么？

**Comment by jxdeng3264** [comment]
> 
> 
> 请问是用 s_client 和 s_server 链接的么？

自己写的一个demo，同样的编译方式，在不同的机器上编译，一个可以运行，一个不行。

**Comment by zhaoxiaomeng** [comment]
不同机器的操作系统分别是什么呢？

**Comment by xiejianjun417** [comment]
https://github.com/guanzhi/GmSSL/issues/716

**Comment by jxdeng3264** [comment]
> 
> 
> #716

和我的情况不一样

**Comment by jxdeng3264** [comment]
@zhaoxiaomeng 你需要看操作系统的哪些参数？  
编译后不能用的 OS，centos-release-7-6.1810.2.el7.centos.x86_64
编译后正常，可以用的OS， centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by zhaoxiaomeng** [comment]
是不是 gcc 的版本不一样，或者是某些动态库缺失导致的 。

**Comment by jxdeng3264** [comment]
> 
> 
> 是不是 gcc 的版本不一样，或者是某些动态库缺失导致的 。

gcc 需要哪个版本？如果动态库错误，会直接运行不起来。

**Comment by changguangsheng** [comment]
> > 是不是 gcc 的版本不一样，或者是某些动态库缺失导致的 。
> 
> gcc 需要哪个版本？如果动态库错误，会直接运行不起来。

请问解决了吗,我也遇到这个问题
