### ISSUE TITLE
今天使用中出现一个新问题，关于PKCS7解析

### ISSUE THREAD

**Issue by roy19831015** [guanzhi/GmSSL#91]
之前的VS2013工程是基于openssl1.0.1f，
关于RSA证书的PKCS7签名的接口是用cryptoapi的CryptSignMessage实现的
而验签是由openssl来做的PKCS7拆包工作，组合成skf库规范的结构体，然后使用设备的skf国密库进行验签。
现在替换成gmssl之后，发现使用CryptSignMessage产生的p7签名值在gmssl下使用下面代码拆包时出现异常，代码和错误信息如下：
代码：
```
	PKCS7 *p7 = NULL;
	p7 = PKCS7_new();
	d2i_PKCS7(&p7, (const unsigned char **)&pbp7, cbp7);
```
此时p7为空指针，gmssl错误信息
OPENSSL_ERROR
error data: Field=d.sign, Type=PKCS7

麻烦帮看下什么问题

**Comment by sslvpn007** [comment]
楼主，现在的版本能在windows 编译？

**Comment by roy19831015** [comment]
我是1月23日下的，现在好像是基于openssl1.1改的吧，之前似乎不是，现在的版本不清楚能不能编译，之前改改就能编译了

**Comment by sslvpn007** [comment]
1月23的版本号，是什么？

我最近编译的版本：

bash-3.2$ gmssl version
GmSSL 1.3.0 - OpenSSL 1.0.2d
在linux和Mac下都试了下，都能成功。

就是win下不行。

**Comment by guanzhi** [comment]
可以试试：
使用`ERR_print_errors()`打印错误栈
使用 `gmssl asn1parse`解析一下pkcs7包格式是否错误

**Comment by roy19831015** [comment]
14284:error:0D0C40D8:lib(13):func(196):reason(216):.\crypto\asn1\a_object.c:283:
14284:error:0D08303A:lib(13):func(131):reason(58):.\crypto\asn1\tasn_dec.c:694:Field=type, Type=PKCS7
14284:error:0D08303A:lib(13):func(131):reason(58):.\crypto\asn1\tasn_dec.c:694:Field=contents, Type=PKCS7_SIGNED
14284:error:0D08303A:lib(13):func(131):reason(58):.\crypto\asn1\tasn_dec.c:694:
14284:error:0D08403A:lib(13):func(132):reason(58):.\crypto\asn1\tasn_dec.c:557:Field=d.sign, Type=PKCS7


以上就是用ERR_print_errors()输出的错误信息

**Comment by roy19831015** [comment]
我发现这是pkcs7组包时候关于【detached的原文】有差异引起的
因为是detached，所以一定不会有原文，但是这一空项在您这个组包之后得到的是
06 00
而正常的是06 01 00
06是类型，00表示空，是不是掉了表示长度的01引起的
是不是因为类型是06,表示OBJECT IDENTIFIER的时候如果用空值，必须加上长度？

**Comment by guanzhi** [comment]
14284:error:0D0C40D8:lib(13):func(196):reason(216):.\crypto\asn1\a_object.c:283:
这个错误是OID不能为空，因此 06 00 不能通过OID格式检查

**Comment by guanzhi** [comment]
这个 06 00 是Windows的CryptSignMessage生成的?

**Comment by roy19831015** [comment]
这个 06 00 是gmssl编译生成的libeay32.lib库中的i2d_pkcs7生成的值，原版生成的是06 01 00

**Comment by roy19831015** [comment]
我先试试改改a_object.c能不能OK
生成是您这个生成的，不是cryptsignmessage
我提到cryptsignmessage只是用来比对

**Comment by roy19831015** [comment]
ASN1_OBJECT *c2i_ASN1_OBJECT(ASN1_OBJECT **a, const unsigned char **pp,
                             long len)

检查了一下这个函数，和原版1.0.1f中的对比发现您最前面多了一行关于len判断的，而原版似乎无视了这个，我替换成原版的之后已经能正常运行了

十分感谢~~~~~
