### ISSUE TITLE
GmSSL cannot interwork with TaSSL

### ISSUE THREAD

**Issue by NaveenShivanna86** [guanzhi/GmSSL#913]
**Problem Description:**

Hi,

This issue is regarding the interoperability between GmSSL and TaSSL for cipher ECC_SM4_SM3.

TaSSL: https://github.com/jntass/TASSL-1.1.1b  
GmSSL: https://github.com/guanzhi/GmSSL

GmSSL client with method as GMTLS_client_method() starts the handshake. 
TaSSL server responds back with 'Server Hello, Certificate, Server Key Exchange, Server Hello Done'

GmSSL client fails to process the message 'Server Key Exchange' and the failure location is "crypto/sm2/sm2_sign.c 504: sm2_do_verify".

![image](https://user-images.githubusercontent.com/20736089/72515840-9d9f9880-3876-11ea-8c99-41fa53d44e79.png)

Further the error log is "140737353991936:error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl/statem/statem_gmtls.c:895:"

![image](https://user-images.githubusercontent.com/20736089/72515901-c2940b80-3876-11ea-9cee-b59d7acfb89a.png)

Please help to solve this issue.

**Expected Behaviour:** 
Handshake should have been success.

**Environments:**
OS: unbuntu
Compiler: GCC 
This issue is not related to platform. It happens in all platforms.

**Additional context:**

![image](https://user-images.githubusercontent.com/20736089/72516520-d12ef280-3877-11ea-87eb-b7bef5b31ce6.png)

Please let me know if need further information.

Rgds,
Navi

**Comment by suishixingkong** [comment]
> **Problem Description:**
> 
> Hi,
> 
> This issue is regarding the interoperability between GmSSL and TaSSL for cipher ECC_SM4_SM3.
> 
> TaSSL: https://github.com/jntass/TASSL-1.1.1b
> GmSSL: https://github.com/guanzhi/GmSSL
> 
> GmSSL client with method as GMTLS_client_method() starts the handshake.
> TaSSL server responds back with 'Server Hello, Certificate, Server Key Exchange, Server Hello Done'
> 
> GmSSL client fails to process the message 'Server Key Exchange' and the failure location is "crypto/sm2/sm2_sign.c 504: sm2_do_verify".
> 
> ![image](https://user-images.githubusercontent.com/20736089/72515840-9d9f9880-3876-11ea-8c99-41fa53d44e79.png)
> 
> Further the error log is "140737353991936:error:141C907B:SSL routines:gmtls_process_ske_sm2:bad signature:ssl/statem/statem_gmtls.c:895:"
> 
> ![image](https://user-images.githubusercontent.com/20736089/72515901-c2940b80-3876-11ea-9cee-b59d7acfb89a.png)
> 
> Please help to solve this issue.
> 
> **Expected Behaviour:**
> Handshake should have been success.
> 
> **Environments:**
> OS: unbuntu
> Compiler: GCC
> This issue is not related to platform. It happens in all platforms.
> 
> **Additional context:**
> 
> ![image](https://user-images.githubusercontent.com/20736089/72516520-d12ef280-3877-11ea-87eb-b7bef5b31ce6.png)
> 
> Please let me know if need further information.
> 
> Rgds,
> Navi

Because gmssl has a bug about gmtls, you need to solve the bug

**Comment by wuyougongzi** [comment]
这个代码看着没用合进去，有个 疑问这个加3的作用是干什么的。

**Comment by davidkhala** [comment]
> I have raised PR for this issue: #915

Why the `n+3 ` could fix the bug? is it really a GMSSL bug? Or simply algorithm mismatch between these two crypto libraries?

**Comment by guozesheng** [comment]
`n+3`是因为之前的`gmtls_new_cert_packet()`函数返回证书长度时，少返回了3个字节，这3个字节是buf最前面表示证书长度的3个字节。  
但是目前的这个函数已经修复了这个问题，见https://github.com/guanzhi/GmSSL/commit/09e2d791a8668faea06dcf798f281f07a3ae887d。
