### ISSUE TITLE
请问nginx如何集成GMSSL？

### ISSUE THREAD

**Issue by renshuainan** [guanzhi/GmSSL#914]
现在已经将GMSSL移植至我们的嵌入式设备上，后续需要将设备连接到后台服务器，准备使用nginx作为反向代理服务器集成GMSSL，请问关老师和各位大佬如何在nginx上集成GMSSL？有没有相关的较为详细的说明文档？有没有大佬做过相关的事情能够指导我一下，谢谢！

**Comment by fidderdan** [comment]
需要修改代码

**Comment by renshuainan** [comment]
> 
> 
> 需要修改代码

您方便具体指导一下吗，具体修改哪些代码？不胜感激！

**Comment by fidderdan** [comment]
国密和nginx都需要修改的

**Comment by cwt9562** [comment]
> 国密和nginx都需要修改的

是否可以详细说明下？

**Comment by huzhengxing** [comment]
同问，兄弟解决没？

**Comment by cloudingding** [comment]
一起关注下这个问题

**Comment by zedyasuotalong** [comment]
> 
> 
> > 国密和nginx都需要修改的
> 
> 是否可以详细说明下？

我将GmSSL当成nginx的SSL模块配置下，编译成功，启动nginx之前需要修改配置文件，配置下你想要的服务端证书以及对客户端的验证细节，然后就能在nginx上使用GmSSL，不需要修改代码

**Comment by DWFLZXJ** [comment]
> > > 国密和nginx都需要修改的
> > 
> > 
> > 是否可以详细说明下？
> 
> 我将GmSSL当成nginx的SSL模块配置下，编译成功，启动nginx之前需要修改配置文件，配置下你想要的服务端证书以及对客户端的验证细节，然后就能在nginx上使用GmSSL，不需要修改代码



> > > 国密和nginx都需要修改的
> > 
> > 
> > 是否可以详细说明下？
> 
> 我将GmSSL当成nginx的SSL模块配置下，编译成功，启动nginx之前需要修改配置文件，配置下你想要的服务端证书以及对客户端的验证细节，然后就能在nginx上使用GmSSL，不需要修改代码

能详细说一下吗，具体怎么配置的
