### ISSUE TITLE
sha256 SM2 数字签名，命令行验签成功，第三方工具（已验证）验签失败

### ISSUE THREAD

**Issue by langxing08** [guanzhi/GmSSL#917]
我有个几十KB的文件，先生成私钥，然后计算摘要＋签名，最后验签。用命令行的方式是可以验签成功的。

生成私钥
gmssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:sm2p256v1 -pkeyopt ec_param_enc:named_curve -out skey.pem

摘要+签名
$ gmssl sha256 -binary test.bin | gmssl pkeyutl -sign -pkeyopt ec_scheme:sm2 -inkey skey.pem -out test.bin.sig

摘要＋验签
$ gmssl sha256 -binary test.bin | gmssl pkeyutl -verify -pkeyopt ec_scheme:sm2 -pubin -inkey vkey.pem -sigfile test.bin.sig

但是用第三方软件测试时，计算出来的哈希值与命令行一样，根据私钥提取出来的公钥信息也对，但是验签是失败的。这个第三方软件验签的结果跟我使用的加密芯片是一致的。

我做了如下测试：
解析私钥
$ gmssl asn1parse -in skey.pem -inform PEM
    0:d=0  hl=3 l= 135 cons: SEQUENCE          
    3:d=1  hl=2 l=   1 prim: INTEGER           :00
    6:d=1  hl=2 l=  19 cons: SEQUENCE          
    8:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   17:d=2  hl=2 l=   8 prim: OBJECT            :sm2p256v1
   27:d=1  hl=2 l= 109 prim: OCTET STRING      [HEX DUMP]:306B0201010420A82B98028C72EFFA9E6EE0ED6328B488180FABD7BF83F6518C384B2B1A07BE78A144034200046425AB8EFAEF6B01AE7C9B0F36592B3116B45BBF185E393CC9CD2BB3470D8D99A9430EC14DB071EE24A00605056B0E2763534DF384C6E05E154AF5B851EA7E35
根据ASN.1格式解析，提取出私钥和公钥
私钥：
A82B98028C72EFFA9E6EE0ED6328B488180FABD7BF83F6518C384B2B1A07BE78
公钥：
6425AB8EFAEF6B01AE7C9B0F36592B3116B45BBF185E393CC9CD2BB3470D8D99
A9430EC14DB071EE24A00605056B0E2763534DF384C6E05E154AF5B851EA7E35

签名信息中获取有效的64字节：
$ gmssl asn1parse -in test.bin.sig -inform DER
    0:d=0  hl=2 l=  69 cons: SEQUENCE          
    2:d=1  hl=2 l=  33 prim: INTEGER           :B5E199591E6065EC6DB6BBD7F81ED4E288ED95C191DEFF841FA89F675E201D0C
   37:d=1  hl=2 l=  32 prim: INTEGER           :4ACB3A9550FA3C40FBDC0384928294FB4D673E8C73031868667254B9E6ECDCC3
即签名值：
B5E199591E6065EC6DB6BBD7F81ED4E288ED95C191DEFF841FA89F675E201D0C
4ACB3A9550FA3C40FBDC0384928294FB4D673E8C73031868667254B9E6ECDCC3

请问是我哪里做错了呢？应该怎么修改？

**Comment by LiuxyData** [comment]
请问博主解决了吗，我用gmssl sm2sign生成的签名，用gmssl sm2verify可以验签成功，但是用第三方验签的工具就验签失败。
