### ISSUE TITLE
gmssl+openvpn客户端与服务器端协商建立隧道的问题

### ISSUE THREAD

**Issue by gsc521** [guanzhi/GmSSL#92]
通过gmssl的sm2、sm3算法产生证书，然后通过openvpn在两台主机上建立隧道，协商的过程中有一个问题：服务器端和客户端有一次签名验签竟然是用sha512产生的结果做的而不是sm3，可是我在生成证书的时候都是指定的sm2+sm3的呀，有大神知道这里为什么会这样吗？

**Comment by sslvpn007** [comment]
请教下楼主，你的国密的ssl vpn 是在哪个平台下 测试的？

**Comment by gsc521** [comment]
就是普通的x86主机

**Comment by sslvpn007** [comment]
windows?还是linux？

**Comment by gsc521** [comment]
linux

**Comment by gsc521** [comment]
我现在已经解决了。在走SSL握手协议的时候，原来的ecdsa签名算法默认绑定的就是sha512，现在在gmssl中走这个握手协议的时候ecdsa已经被替换成sm2了，所以把代码改成绑定sm3算法就ok了，也符合国密的ssl规范。

**Comment by gmfix001x** [comment]
满足双证书吗？？？
各项参数都符合国密的那套标准吗？

能不能共享下啊。
