### ISSUE TITLE
安装GmSSL后会将openssl也自动链接到gmssl，还导致openssl不可用

### ISSUE THREAD

**Issue by fqliao** [guanzhi/GmSSL#920]
请问下，安装GmSSL后会将openssl也自动链接到gmssl，还导致openssl不可用，如下图所示，如何解决？
![clipboard](https://user-images.githubusercontent.com/16574664/74654652-c4c6ee00-51c5-11ea-84b6-cee17df0220f.png)

**Comment by jiangzhengdu** [comment]
同样的问题，有一次还导致无法链接wifi,,,

**Comment by zhaoxuyan** [comment]
同问！！

**Comment by zhaoxuyan** [comment]
> 请问下，安装GmSSL后会将openssl也自动链接到gmssl，还导致openssl不可用，如下图所示，如何解决？
> ![clipboard](https://user-images.githubusercontent.com/16574664/74654652-c4c6ee00-51c5-11ea-84b6-cee17df0220f.png)

请问你解决了吗

**Comment by tpu01yzx** [comment]
我出现同样的问题，`make uninstall`之后会破坏原有已安装的openssl。具体地，会删除了/usr/local/bin/openssl，但没有正确还原已有的openssl，导致如下出错提示：
> $ openssl
> -bash: /usr/local/bin/openssl: No such file or directory

以下这些卸载命令都是危险的，不应该出现`rmdir /usr/local/bin`，`rm -f -r -v /usr/local/share/doc/openssl`，`rmdir /usr/local/include/openssl`，`rmdir /usr/local/include`, `rmdir /usr/local/lib`。

GmSSL应该是尝试替代了系统中的Openssl动态库，但卸载的时候没有进行恢复原有的Openssl动态库，从而导致出错。重新安装或者编译openssl，并用`libcrypto.so.1.1`生成的替换掉`/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1`和`/usr/local/lib/libcrypto.so.1.1`, 之后openssl正常使用。

正如项目介绍说的一样，这是openssl的一个分支（As a branch of the OpenSSL project）。同一个项目同时安装两个不同分支，是容易产生冲突的，需要小心处理。
