### ISSUE TITLE
在使用gmssl链接skf密码设备的时候遇到设备名称存在空格，请问一下这种情况命令该怎么输入

### ISSUE THREAD

**Issue by otie2011** [guanzhi/GmSSL#924]
smb@smb-S410:~/cui$ gmssl skf -lib ./libskf.so -vendor wisec -listdevs
  Device 0 : ES3000GM VCR 1

设备名字如上所示，目前卡在这个设备名称不知道该怎么在命令中输入，已经试过网上说的各种输入空格的方法，请各位帮忙看看指点一下，在此谢谢各位了

**Comment by liuqun** [comment]
![image](https://user-images.githubusercontent.com/64795/97384015-cc6c9400-1909-11eb-98cb-e94f662fa143.png)

**Comment by liuqun** [comment]
https://www.cnblogs.com/zz-1226/p/10963833.html

**Comment by liuqun** [comment]
![image](https://user-images.githubusercontent.com/64795/97385293-63d2e680-190c-11eb-8874-4e52bce09969.png)
