### ISSUE TITLE
国密SSL协议标准定义疑问

### ISSUE THREAD

**Issue by mogoweb** [guanzhi/GmSSL#926]
国标 GM/T 0024-2014中定义的密码套件：

```
ECDHE_SM1_SM3           0xe0, 0x01
ECC_SM1_SM3             0xe0, 0x03
IBSDH_SM1_SM3           0xe0, 0x05
IBC_SM1_SM3             0xe0, 0x07
RSA_SM1_SM3             0xe0, 0x09
RSA_SM1_SHA1            0xe0, 0x0a
ECDHE_SM4_SM3           0xe0, 0x11
ECC_SM4_SM3             0xe0, 0x13
IBSDH_SM4_SM3           0xe0, 0x15
IBC_SM4_SM3             0xe0, 0x17
RSA_SM4_SM3             0xe0, 0x19
RSA_SM4_SHA1            0xe0, 0x1a
```
但我看到GMSSL的代码中密码套件定义有：

```c++
    /* GM/T [SM2DHE|SM2|SM9DHE|SM9|RSA]-WITH-[SM1|SMS4]-[SM3|SHA1] */
    {0xE001, "GMTLS_SM2DHE_WITH_SM1_SM3"},
    {0xE003, "GMTLS_SM2_WITH_SM1_SM3"},
    {0xE005, "GMTLS_SM9DHE_WITH_SM1_SM3"},
    {0xE007, "GMTLS_SM9_WITH_SM1_SM3"},
    {0xE009, "GMTLS_RSA_WITH_SM1_SM3"},
    {0xE00A, "GMTLS_RSA_WITH_SM1_SHA1"},
    {0xE011, "GMTLS_SM2DHE_WITH_SMS4_SM3"},
    {0xE013, "GMTLS_SM2_WITH_SMS4_SM3"},
    {0xE015, "GMTLS_SM9DHE_WITH_SMS4_SM3"},
    {0xE017, "GMTLS_SM9_WITH_SMS4_SM3"},
    {0xE019, "GMTLS_RSA_WITH_SMS4_SM3"},
    {0xE01A, "GMTLS_RSA_WITH_SMS4_SHA1"},

    {0xE101, "GMTLS_ECDHE_SM2_WITH_SM1_SM3"},
    {0xE102, "GMTLS_ECDHE_SM2_WITH_SMS4_SM3"},
    {0xE103, "GMTLS_ECDHE_SM2_WITH_SSF33_SM3"},
    {0xE105, "GMTLS_ECDHE_SM2_WITH_SMS4_SHA256"},
    {0xE107, "GMTLS_ECDHE_SM2_WITH_SMS4_GCM_SM3"},
    {0xE108, "GMTLS_ECDHE_SM2_WITH_SMS4_CCM_SM3"},

    {0xE10D, "GMTLS_ECDHE_SM2_WITH_ZUC_SM3"},
    {0xE10E, "GMTLS_ECDHE_SM2_WITH_ZUC256_SM3"},
    {0xE201, "GMTLS_SM2DHE_SM2_WITH_SM1_SM3"},
    {0xE202, "GMTLS_SM2DHE_SM2_WITH_SMS4_SM3"},
    {0xE203, "GMTLS_SM2DHE_SM2_WITH_SSF33_SM3"},
    {0xE204, "GMTLS_SM2DHE_SM2_WITH_ZUC_SM3"},
    {0xE205, "GMTLS_SM2DHE_SM2_WITH_SMS4_GCM_SM3"},
    {0xE206, "GMTLS_SM2DHE_SM2_WITH_SMS4_CCM_SM3"},
    {0xE209, "GMTLS_SM2DHE_SM2_WITH_ZUC256_SM3"},
    {0xF101, "GMTLS_PSK_WITH_SMS4_CBC_SM3"},
    {0xF102, "GMTLS_PSK_WITH_SMS4_GCM_SM3"},
    {0xF103, "GMTLS_PSK_WITH_SMS4_CCM_SM3"},
    {0xF10B, "GMTLS_SM2DHE_PSK_WITH_SMS4_CBC_SM3"},
    {0xF10C, "GMTLS_SM2DHE_PSK_WITH_SMS4_GCM_SM3"},
    {0xF10D, "GMTLS_SM2DHE_PSK_WITH_SMS4_CCM_SM3"},
    {0xF10E, "GMTLS_PSK_WITH_SM1_CBC_SM3"},
    {0xF117, "GMTLS_PSK_WITH_SSF33_CBC_SM3"},
    {0xF120, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
    {0xF121, "GMTLS_ECDHE_PSK_WITH_SMS4_GCM_SM3"},
    {0xF122, "GMTLS_ECDHE_PSK_WITH_SMS4_CCM_SM3"},
    {0xF123, "GMTLS_PSK_WITH_ZUC_SM3"},
    {0xF124, "GMTLS_PSK_WITH_ZUC256_SM3"},
    {0xF125, "GMTLS_ECDHE_PSK_WITH_ZUC_SM3"},
    {0xF126, "GMTLS_ECDHE_PSK_WITH_ZUC256_SM3"},
    {0xF127, "GMTLS_SM2DHE_PSK_WITH_ZUC_SM3"},
    {0xF128, "GMTLS_SM2DHE_PSK_WITH_ZUC256_SM3"},
    {0xF201, "GMTLS_SRP_SM3_WITH_SMS4_CBC_SM3"},
    {0xF202, "GMTLS_SRP_SM3_WITH_SMS4_GCM_SM3"},
    {0xF203, "GMTLS_SRP_SM3_WITH_SMS4_CCM_SM3"},
    {0xFEFE, "SSL_RSA_FIPS_WITH_DES_CBC_SHA"},
    {0xFEFF, "SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA"},

#ifndef OPENSSL_NO_GMTLS
    {0xF10E, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
#endif
```

是后来的标准更新了吗？ 我是从 https://github.com/guanzhi/GM-Standards.git 获得的标准文档。

**Comment by rongzedong** [comment]
我也不太懂，但是我觉得 gmssl 和 单独的 sm3 实现方法可能是存在不同的。 前者是遵循了openssl的一些东西。
但是加密的算法和结果应该是相同的。

就好比 c语言写的， java写的，代码不同一样。

**Comment by mogoweb** [comment]
我后来看了gmssl.org上的说明：
`
GmSSL还包含两个专有的密码套件，以兼容某些仅使用SM2证书但不修改SSL/TLS协议的SSL VPN产品。

13 ECDHE-SM2-SM4-SM3
14 SM2-SM4-SM3
`
这个确实是他们自己加的

**Comment by Alice47962** [comment]
> 国标 GM/T 0024-2014中定义的密码套件：
> 
> ```
> ECDHE_SM1_SM3           0xe0, 0x01
> ECC_SM1_SM3             0xe0, 0x03
> IBSDH_SM1_SM3           0xe0, 0x05
> IBC_SM1_SM3             0xe0, 0x07
> RSA_SM1_SM3             0xe0, 0x09
> RSA_SM1_SHA1            0xe0, 0x0a
> ECDHE_SM4_SM3           0xe0, 0x11
> ECC_SM4_SM3             0xe0, 0x13
> IBSDH_SM4_SM3           0xe0, 0x15
> IBC_SM4_SM3             0xe0, 0x17
> RSA_SM4_SM3             0xe0, 0x19
> RSA_SM4_SHA1            0xe0, 0x1a
> ```
> 
> 但我看到GMSSL的代码中密码套件定义有：
> 
> ```c++
>     /* GM/T [SM2DHE|SM2|SM9DHE|SM9|RSA]-WITH-[SM1|SMS4]-[SM3|SHA1] */
>     {0xE001, "GMTLS_SM2DHE_WITH_SM1_SM3"},
>     {0xE003, "GMTLS_SM2_WITH_SM1_SM3"},
>     {0xE005, "GMTLS_SM9DHE_WITH_SM1_SM3"},
>     {0xE007, "GMTLS_SM9_WITH_SM1_SM3"},
>     {0xE009, "GMTLS_RSA_WITH_SM1_SM3"},
>     {0xE00A, "GMTLS_RSA_WITH_SM1_SHA1"},
>     {0xE011, "GMTLS_SM2DHE_WITH_SMS4_SM3"},
>     {0xE013, "GMTLS_SM2_WITH_SMS4_SM3"},
>     {0xE015, "GMTLS_SM9DHE_WITH_SMS4_SM3"},
>     {0xE017, "GMTLS_SM9_WITH_SMS4_SM3"},
>     {0xE019, "GMTLS_RSA_WITH_SMS4_SM3"},
>     {0xE01A, "GMTLS_RSA_WITH_SMS4_SHA1"},
> 
>     {0xE101, "GMTLS_ECDHE_SM2_WITH_SM1_SM3"},
>     {0xE102, "GMTLS_ECDHE_SM2_WITH_SMS4_SM3"},
>     {0xE103, "GMTLS_ECDHE_SM2_WITH_SSF33_SM3"},
>     {0xE105, "GMTLS_ECDHE_SM2_WITH_SMS4_SHA256"},
>     {0xE107, "GMTLS_ECDHE_SM2_WITH_SMS4_GCM_SM3"},
>     {0xE108, "GMTLS_ECDHE_SM2_WITH_SMS4_CCM_SM3"},
> 
>     {0xE10D, "GMTLS_ECDHE_SM2_WITH_ZUC_SM3"},
>     {0xE10E, "GMTLS_ECDHE_SM2_WITH_ZUC256_SM3"},
>     {0xE201, "GMTLS_SM2DHE_SM2_WITH_SM1_SM3"},
>     {0xE202, "GMTLS_SM2DHE_SM2_WITH_SMS4_SM3"},
>     {0xE203, "GMTLS_SM2DHE_SM2_WITH_SSF33_SM3"},
>     {0xE204, "GMTLS_SM2DHE_SM2_WITH_ZUC_SM3"},
>     {0xE205, "GMTLS_SM2DHE_SM2_WITH_SMS4_GCM_SM3"},
>     {0xE206, "GMTLS_SM2DHE_SM2_WITH_SMS4_CCM_SM3"},
>     {0xE209, "GMTLS_SM2DHE_SM2_WITH_ZUC256_SM3"},
>     {0xF101, "GMTLS_PSK_WITH_SMS4_CBC_SM3"},
>     {0xF102, "GMTLS_PSK_WITH_SMS4_GCM_SM3"},
>     {0xF103, "GMTLS_PSK_WITH_SMS4_CCM_SM3"},
>     {0xF10B, "GMTLS_SM2DHE_PSK_WITH_SMS4_CBC_SM3"},
>     {0xF10C, "GMTLS_SM2DHE_PSK_WITH_SMS4_GCM_SM3"},
>     {0xF10D, "GMTLS_SM2DHE_PSK_WITH_SMS4_CCM_SM3"},
>     {0xF10E, "GMTLS_PSK_WITH_SM1_CBC_SM3"},
>     {0xF117, "GMTLS_PSK_WITH_SSF33_CBC_SM3"},
>     {0xF120, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
>     {0xF121, "GMTLS_ECDHE_PSK_WITH_SMS4_GCM_SM3"},
>     {0xF122, "GMTLS_ECDHE_PSK_WITH_SMS4_CCM_SM3"},
>     {0xF123, "GMTLS_PSK_WITH_ZUC_SM3"},
>     {0xF124, "GMTLS_PSK_WITH_ZUC256_SM3"},
>     {0xF125, "GMTLS_ECDHE_PSK_WITH_ZUC_SM3"},
>     {0xF126, "GMTLS_ECDHE_PSK_WITH_ZUC256_SM3"},
>     {0xF127, "GMTLS_SM2DHE_PSK_WITH_ZUC_SM3"},
>     {0xF128, "GMTLS_SM2DHE_PSK_WITH_ZUC256_SM3"},
>     {0xF201, "GMTLS_SRP_SM3_WITH_SMS4_CBC_SM3"},
>     {0xF202, "GMTLS_SRP_SM3_WITH_SMS4_GCM_SM3"},
>     {0xF203, "GMTLS_SRP_SM3_WITH_SMS4_CCM_SM3"},
>     {0xFEFE, "SSL_RSA_FIPS_WITH_DES_CBC_SHA"},
>     {0xFEFF, "SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA"},
> 
> #ifndef OPENSSL_NO_GMTLS
>     {0xF10E, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
> #endif
> ```
> 
> 是后来的标准更新了吗？ 我是从 https://github.com/guanzhi/GM-Standards.git 获得的标准文档。

您好，国标 GM/T 0024-2014中定义密码套件后还有这么一句：本标准中实现ECC和ECDHE的算法为SM2。我想请问一下这句话是什么意思？谢谢。

**Comment by mogoweb** [comment]
> > 国标 GM/T 0024-2014中定义的密码套件：
> > ```
> > ECDHE_SM1_SM3           0xe0, 0x01
> > ECC_SM1_SM3             0xe0, 0x03
> > IBSDH_SM1_SM3           0xe0, 0x05
> > IBC_SM1_SM3             0xe0, 0x07
> > RSA_SM1_SM3             0xe0, 0x09
> > RSA_SM1_SHA1            0xe0, 0x0a
> > ECDHE_SM4_SM3           0xe0, 0x11
> > ECC_SM4_SM3             0xe0, 0x13
> > IBSDH_SM4_SM3           0xe0, 0x15
> > IBC_SM4_SM3             0xe0, 0x17
> > RSA_SM4_SM3             0xe0, 0x19
> > RSA_SM4_SHA1            0xe0, 0x1a
> > ```
> > 
> > 
> > 但我看到GMSSL的代码中密码套件定义有：
> > ```c++
> >     /* GM/T [SM2DHE|SM2|SM9DHE|SM9|RSA]-WITH-[SM1|SMS4]-[SM3|SHA1] */
> >     {0xE001, "GMTLS_SM2DHE_WITH_SM1_SM3"},
> >     {0xE003, "GMTLS_SM2_WITH_SM1_SM3"},
> >     {0xE005, "GMTLS_SM9DHE_WITH_SM1_SM3"},
> >     {0xE007, "GMTLS_SM9_WITH_SM1_SM3"},
> >     {0xE009, "GMTLS_RSA_WITH_SM1_SM3"},
> >     {0xE00A, "GMTLS_RSA_WITH_SM1_SHA1"},
> >     {0xE011, "GMTLS_SM2DHE_WITH_SMS4_SM3"},
> >     {0xE013, "GMTLS_SM2_WITH_SMS4_SM3"},
> >     {0xE015, "GMTLS_SM9DHE_WITH_SMS4_SM3"},
> >     {0xE017, "GMTLS_SM9_WITH_SMS4_SM3"},
> >     {0xE019, "GMTLS_RSA_WITH_SMS4_SM3"},
> >     {0xE01A, "GMTLS_RSA_WITH_SMS4_SHA1"},
> > 
> >     {0xE101, "GMTLS_ECDHE_SM2_WITH_SM1_SM3"},
> >     {0xE102, "GMTLS_ECDHE_SM2_WITH_SMS4_SM3"},
> >     {0xE103, "GMTLS_ECDHE_SM2_WITH_SSF33_SM3"},
> >     {0xE105, "GMTLS_ECDHE_SM2_WITH_SMS4_SHA256"},
> >     {0xE107, "GMTLS_ECDHE_SM2_WITH_SMS4_GCM_SM3"},
> >     {0xE108, "GMTLS_ECDHE_SM2_WITH_SMS4_CCM_SM3"},
> > 
> >     {0xE10D, "GMTLS_ECDHE_SM2_WITH_ZUC_SM3"},
> >     {0xE10E, "GMTLS_ECDHE_SM2_WITH_ZUC256_SM3"},
> >     {0xE201, "GMTLS_SM2DHE_SM2_WITH_SM1_SM3"},
> >     {0xE202, "GMTLS_SM2DHE_SM2_WITH_SMS4_SM3"},
> >     {0xE203, "GMTLS_SM2DHE_SM2_WITH_SSF33_SM3"},
> >     {0xE204, "GMTLS_SM2DHE_SM2_WITH_ZUC_SM3"},
> >     {0xE205, "GMTLS_SM2DHE_SM2_WITH_SMS4_GCM_SM3"},
> >     {0xE206, "GMTLS_SM2DHE_SM2_WITH_SMS4_CCM_SM3"},
> >     {0xE209, "GMTLS_SM2DHE_SM2_WITH_ZUC256_SM3"},
> >     {0xF101, "GMTLS_PSK_WITH_SMS4_CBC_SM3"},
> >     {0xF102, "GMTLS_PSK_WITH_SMS4_GCM_SM3"},
> >     {0xF103, "GMTLS_PSK_WITH_SMS4_CCM_SM3"},
> >     {0xF10B, "GMTLS_SM2DHE_PSK_WITH_SMS4_CBC_SM3"},
> >     {0xF10C, "GMTLS_SM2DHE_PSK_WITH_SMS4_GCM_SM3"},
> >     {0xF10D, "GMTLS_SM2DHE_PSK_WITH_SMS4_CCM_SM3"},
> >     {0xF10E, "GMTLS_PSK_WITH_SM1_CBC_SM3"},
> >     {0xF117, "GMTLS_PSK_WITH_SSF33_CBC_SM3"},
> >     {0xF120, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
> >     {0xF121, "GMTLS_ECDHE_PSK_WITH_SMS4_GCM_SM3"},
> >     {0xF122, "GMTLS_ECDHE_PSK_WITH_SMS4_CCM_SM3"},
> >     {0xF123, "GMTLS_PSK_WITH_ZUC_SM3"},
> >     {0xF124, "GMTLS_PSK_WITH_ZUC256_SM3"},
> >     {0xF125, "GMTLS_ECDHE_PSK_WITH_ZUC_SM3"},
> >     {0xF126, "GMTLS_ECDHE_PSK_WITH_ZUC256_SM3"},
> >     {0xF127, "GMTLS_SM2DHE_PSK_WITH_ZUC_SM3"},
> >     {0xF128, "GMTLS_SM2DHE_PSK_WITH_ZUC256_SM3"},
> >     {0xF201, "GMTLS_SRP_SM3_WITH_SMS4_CBC_SM3"},
> >     {0xF202, "GMTLS_SRP_SM3_WITH_SMS4_GCM_SM3"},
> >     {0xF203, "GMTLS_SRP_SM3_WITH_SMS4_CCM_SM3"},
> >     {0xFEFE, "SSL_RSA_FIPS_WITH_DES_CBC_SHA"},
> >     {0xFEFF, "SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA"},
> > 
> > #ifndef OPENSSL_NO_GMTLS
> >     {0xF10E, "GMTLS_ECDHE_PSK_WITH_SMS4_CBC_SM3"},
> > #endif
> > ```
> > 
> > 
> > 是后来的标准更新了吗？ 我是从 https://github.com/guanzhi/GM-Standards.git 获得的标准文档。
> 
> 您好，国标 GM/T 0024-2014中定义密码套件后还有这么一句：本标准中实现ECC和ECDHE的算法为SM2。我想请问一下这句话是什么意思？谢谢。

SM2 就是一种椭圆曲线密码算法。
