### ISSUE TITLE
sm2长稳测试出现概率性验签错误

### ISSUE THREAD

**Issue by victortanjh** [guanzhi/GmSSL#928]
调用C接口SM2_do_sign()产生签名
调用C接口SM2_verify去验签，长稳测试时，大约经过几十万次签名之后，就会出现一次验签失败的情况。但不是很稳定，有时候，经过几千次签名验签，也会出来一次。
但验签失败的概率还是挺高的，不到半小时，必然出现一次。
@guanzhi
请关老师及各位同学帮忙分析一下，这可能是什么原因？感谢

另外，还有个问题：
使用EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_sm2p256v1); 生成的group填充到密钥结构里，比使用sm2_test.c测试程序中，使用new_ec_group方法传入外部参数生成的group再填充到密钥结构里，在签名验签时会快好几倍。其实参数都是相同的，都是国密推荐参数。但不知道这个性能差异的原因是啥。
希望百忙之中，不吝赐教，多谢多谢

**Comment by xpkingstudent** [comment]
不知道你解决了吗？我在测试中发现调用C接口SM2_sign()产生签名，调用C接口SM2_verify去验签，也是出现类似的情况。 检查了好久也不知道是怎么回事，看测试代码用法也没啥问题。
另外，SM2_encrypt 加密 ，SM2_decrypt 解密也出现类似的情况。
还请关老师 及各位高手同学帮忙分析指点，不胜感激！

**Comment by FrozenFort** [comment]
我也遇到了这个问题，我开始是用的go接口，但后来单测C接口发现也有同样的问题。sign算法概率生成不合法签名。
还望大家帮忙找出问题原因~

**Comment by okerivy** [comment]
@victortanjh  @xpkingstudent @FrozenFort  
不清楚是否和这个问题有关, 因为我用的以前的sm2加密,生成的串是以04开头的.
提供下一个可能, 供各位参考

我这遇到一个问题, 找到是cpp封装的OC的Sm2加密, 用的是sm2推荐的参数, 但是iOS加密的串到服务器会出现概率性的解不开, 而服务器java加密的串我都是能解开的.

经过调试, 发现iOS生成的随机数有问题: 当出现服务器解密不开的情况时, 我便把这个**随机数**记录下来, 然后在代码中写死这个随机数, 发现用这个随机数加密的任何东西服务器都解不开.

不清楚是iOS的问题,还是java的问题, 因为java加密的我都是能解开的, iOS加密的串,我自己本地能解开, 但是java就解不开. 

目前没有找到解决方案.
如果各位解决了, 麻烦告知下原因和解决方案

**Comment by xianrenqiu** [comment]
@victortanjh @xpkingstudent @FrozenFort @okerivy 

不知道和我刚刚提交的 [issues](https://github.com/guanzhi/GmSSL/issues/951) 是否有关联，各位可以试试在 config 时增加 -no-asm 选项，试一下之前验证失败的签名是否可以验证通过，但这个参数会导致性能下降非常严重。
