### ISSUE TITLE
想问一下，为啥engine去掉SKF

### ISSUE THREAD

**Issue by sinotitan** [guanzhi/GmSSL#93]
如题

我们想调用加密卡

谢谢

**Comment by sinotitan** [comment]
如题

我们想调用加密卡

谢谢

**Comment by guanzhi** [comment]
openssl-1.1 engine api有一些改动，skf engine后面加入。
你们用的是什么型号的加密卡？我们现在没有在Linux/macOS上可以测试的SKF加密卡。

**Comment by conezxy** [comment]
加密卡加密机应该使用《密码设备应用接口规范》定义的SDF接口，怎么会使用SKF接口？
SKF接口是给USBKey，智能卡等终端上使用的设备用的。

**Comment by sinotitan** [comment]
我记错了，是应该SDF

**Comment by guanzhi** [comment]
SDF密码设备在这个版本也会支持
