### ISSUE TITLE
请问我用nginx安装证书，使用gmssl库，启动nginx，但是出错，请问这是什么原因？怎样解决

### ISSUE THREAD

**Issue by lxkg** [guanzhi/GmSSL#936]
nginx: [emerg] SSL_CTX_use_certificate("/tmp/nginx/client.crt") failed (SSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak)

**Comment by pengtianabc** [comment]
Try this. 
https://github.com/pengtianabc/nginx-gm
