### ISSUE TITLE
Nginx搭配Gmssl使用国密浏览器连接不成功

### ISSUE THREAD

**Issue by Mer1997** [guanzhi/GmSSL#939]
我在nginx上开启https服务，配置sm2签名和加密证书
```
[GMTLS_DEBUG] set sm2 signing certificate
[GMTLS_DEBUG] set sm2 signing private key
[GMTLS_DEBUG] set sm2 encryption certificate
[GMTLS_DEBUG] set sm2 decryption private key
```

但是使用国密浏览器连接时无法正确连接，抓包结果显示流程进行到Server Hello Done,选择的加密套件为ECC_SM4_SM3
```
Secure Sockets Layer
    GMSSLv1 Record Layer: Handshake Protocol: Server Hello
        Content Type: Handshake (22)
        Version: GMSSL 1.0 (0x0101)
        Length: 42
        Handshake Protocol: Server Hello
            Handshake Type: Server Hello (2)
            Length: 38
            Version: GMSSL 1.0 (0x0101)
            Random: e050b01077a24a83eb1ad58008bc4488a5de14a036f37ff0...
            Session ID Length: 0
            Cipher Suite: ECC_SM4_SM3 (0xe013)
            Compression Method: null (0)
    GMSSLv1 Record Layer: Handshake Protocol: Certificate
        Content Type: Handshake (22)
        Version: GMSSL 1.0 (0x0101)
        Length: 1099
        Handshake Protocol: Certificate
            Handshake Type: Certificate (11)
            Length: 1095
            Certificates Length: 1092
            Certificates (1092 bytes)
                Certificate Length: 543
                Certificate: 3082021b308201c1a003020102020900962156f6576dfa3b... 
                Certificate Length: 543
                Certificate: 3082021b308201c0a003020102020900962156f6576dfa3c...
    GMSSLv1 Record Layer: Handshake Protocol: Server Key Exchange
        Content Type: Handshake (22)
        Version: GMSSL 1.0 (0x0101)
        Length: 77
        Handshake Protocol: Server Key Exchange
            Handshake Type: Server Key Exchange (12)
            Length: 73
    GMSSLv1 Record Layer: Handshake Protocol: Server Hello Done
        Content Type: Handshake (22)
        Version: GMSSL 1.0 (0x0101)
        Length: 4
        Handshake Protocol: Server Hello Done
            Handshake Type: Server Hello Done (14)
            Length: 0
```

接着客户端就返回错误
```
Secure Sockets Layer
    GMSSLv1 Record Layer: Alert (Level: Fatal, Description: Decrypt Error)
        Content Type: Alert (21)
        Version: GMSSL 1.0 (0x0101)
        Length: 2
        Alert Message
            Level: Fatal (2)
            Description: Decrypt Error (51)

```

**Comment by Mer1997** [comment]
从网上查了一些资料，有尝试过在`gmtls_construct_ske_sm2`函数中将
`EVP_SignUpdate(md_ctx, buf, n)`改为
`EVP_SignUpdate(md_ctx, buf, n+3)`

但是还是不行，有什么其他地方需要修改的吗

**Comment by Nu1i** [comment]
遇到相同的错误

**Comment by Mer1997** [comment]
> 遇到相同的错误
@Nu1i 
问题已解决，参照 #762 
重点是ID使用默认的"1234567812345678"以及`EVP_SignUpdate(md_ctx,buf, n+3)`
使用360浏览器的话要使用带CA链的证书并信任即可

**Comment by Nu1i** [comment]
@Mer1997 照着这个修改重新编译后还是报错，
14196:error:141CA17A:SSL routines:gmtls_process_ske_sm2dhe:wrong curve:ssl\statem\statem_gmtls.c:580:

**Comment by Nu1i** [comment]
@Mer1997 解决了，谢谢！

**Comment by Nu1i** [comment]
按照那个修改后，gmssl做客户端连接别的服务端使用ECC_SM4_SM3能通，但是GMSSL做服务端使用360浏览器访问报错，Decrypt Error，内容大概如下：
1684:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
抓包发现是客户端响应了这个错误。

**Comment by Mer1997** [comment]
> 按照那个修改后，gmssl做客户端连接别的服务端使用ECC_SM4_SM3能通，但是GMSSL做服务端使用360浏览器访问报错，Decrypt Error，内容大概如下：
> 1684:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
> 抓包发现是客户端响应了这个错误。

应该是证书的问题，使用带CA链的签名和加密证书，连接失败以后要选择信任证书即可

**Comment by Nu1i** [comment]
> > 按照那个修改后，gmssl做客户端连接别的服务端使用ECC_SM4_SM3能通，但是GMSSL做服务端使用360浏览器访问报错，Decrypt Error，内容大概如下：
> > 1684:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
> > 抓包发现是客户端响应了这个错误。
> 
> 应该是证书的问题，使用带CA链的签名和加密证书，连接失败以后要选择信任证书即可

证书我是用的是CFCA的测试证书，在别的平台上测试都没有问题。还有可能是哪里的问题？您除了修改上面提到的东西还修改别的地方了吗？

**Comment by Nu1i** [comment]
> > > 按照那个修改后，gmssl做客户端连接别的服务端使用ECC_SM4_SM3能通，但是GMSSL做服务端使用360浏览器访问报错，Decrypt Error，内容大概如下：
> > > 1684:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
> > > 抓包发现是客户端响应了这个错误。
> > 
> > 
> > 应该是证书的问题，使用带CA链的签名和加密证书，连接失败以后要选择信任证书即可
> 
> 证书我是用的是CFCA的测试证书，在别的平台上测试都没有问题。还有可能是哪里的问题？您除了修改上面提到的东西还修改别的地方了吗？

ssl_get_algorithm2=0x08x
ERROR
1664:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
shutting down SSL
CONNECTION CLOSED
ACCEPT

这是报错内容，似乎是获取到的摘要算法不对吗？

**Comment by Mer1997** [comment]
总结一下你的问题@Nu1i ，现在有点乱，看一下你的抓包信息，进行到哪步了，如果在参数协商出问题，考虑是否正确按照#762修改以及是否使用了带CA链的签名和加密证书，如果在SSL连接建立完成之后考虑360需要信任证书。另外你的测试方法我不太理解，我只用gmssl做过服务端，浏览器作为客户端。
代码除了#762 以外没有其他修改。
密信浏览器也可以作为测试浏览器

**Comment by Nu1i** [comment]
> 总结一下你的问题@Nu1i ，现在有点乱，看一下你的抓包信息，进行到哪步了，如果在参数协商出问题，考虑是否正确按照#762修改以及是否使用了带CA链的签名和加密证书，如果在SSL连接建立完成之后考虑360需要信任证书。另外你的测试方法我不太理解，我只用gmssl做过服务端，浏览器作为客户端。
> 代码除了#762 以外没有其他修改。
> 密信浏览器也可以作为测试浏览器

使用GMSSL做服务端，使用360浏览器做客户端，在握手阶段server hello done之后，客户端立即发送了decrypt error

**Comment by yalifeng** [comment]
@Mer1997 请问您的国密证书怎么生成的还有用的哪个版本的gmssl
①我直接使用修改后的GmSSL-patch-3版本
②生成证书方法
           生成证书的脚本来源- 
                git clone https://github.com/jntass/TASSL/
                cd ./TASSL/Tassl_demo/mk_tls_cert
           1.先生成CA证书：
           2.生成服务器签名证书并使用上面生成的CA签名
           3.生成服务端加密证书并使用上面生成的CA签名 
③在GmSSL-patch-3/apps下面启动服务端
          ./gmssl s_server -gmtls -accept 443 -cert ./sm2Certs/SS.cert.pem -key ./sm2Certs/SS.key.pem -dcert ./sm2Certs/SE.cert.pem -dkey ./sm2Certs/SE.key.pem -state
④使用360浏览器访问

--------------------------------
gmssl出现报错：
        
![image](https://user-images.githubusercontent.com/22927731/79179641-adf5ee00-7e3a-11ea-98a1-4a3b35aac91d.png)

抓包：
![image](https://user-images.githubusercontent.com/22927731/79179734-e1387d00-7e3a-11ea-8b5d-e5b3ee39a678.png)

**Comment by Mer1997** [comment]
> @Mer1997 请问您的国密证书怎么生成的还有用的哪个版本的gmssl
> ①我直接使用修改后的GmSSL-patch-3版本
> ②生成证书方法
> 生成证书的脚本来源-
> git clone https://github.com/jntass/TASSL/
> cd ./TASSL/Tassl_demo/mk_tls_cert
> 1.先生成CA证书：
> 2.生成服务器签名证书并使用上面生成的CA签名
> 3.生成服务端加密证书并使用上面生成的CA签名
> ③在GmSSL-patch-3/apps下面启动服务端
> ./gmssl s_server -gmtls -accept 443 -cert ./sm2Certs/SS.cert.pem -key ./sm2Certs/SS.key.pem -dcert ./sm2Certs/SE.cert.pem -dkey ./sm2Certs/SE.key.pem -state
> ④使用360浏览器访问
> 
> gmssl出现报错：
> 
> ![image](https://user-images.githubusercontent.com/22927731/79179641-adf5ee00-7e3a-11ea-98a1-4a3b35aac91d.png)
> 
> 抓包：
> ![image](https://user-images.githubusercontent.com/22927731/79179734-e1387d00-7e3a-11ea-8b5d-e5b3ee39a678.png)

天安脚本生成的证书不带证书链，360没法设置信任，我使用https://www.gmcert.org/生成的证书进行测试
Gmssl使用的master版本
从抓包的情况看密钥协商还没有完成，服务端报错，这里应该不只是证书的问题，仔细再查查

**Comment by yalifeng** [comment]
好的，谢谢您




| |
13716097002
邮箱：13716097002@163.com
|

Signature is customized by Netease Mail Master

在2020年04月15日 01:30，Mer1997 写道：

@Mer1997 请问您的国密证书怎么生成的还有用的哪个版本的gmssl
①我直接使用修改后的GmSSL-patch-3版本
②生成证书方法
生成证书的脚本来源-
git clone https://github.com/jntass/TASSL/
cd ./TASSL/Tassl_demo/mk_tls_cert
1.先生成CA证书：
2.生成服务器签名证书并使用上面生成的CA签名
3.生成服务端加密证书并使用上面生成的CA签名
③在GmSSL-patch-3/apps下面启动服务端
./gmssl s_server -gmtls -accept 443 -cert ./sm2Certs/SS.cert.pem -key ./sm2Certs/SS.key.pem -dcert ./sm2Certs/SE.cert.pem -dkey ./sm2Certs/SE.key.pem -state
④使用360浏览器访问

gmssl出现报错：

抓包：


天安脚本生成的证书不带证书链，360没法设置信任，我使用https://www.gmcert.org/生成的证书进行测试
Gmssl使用的master版本
从抓包的情况看密钥协商还没有完成，服务端报错，这里应该不只是证书的问题，仔细再查查

**Comment by yalifeng** [comment]
@Mer1997  好的，谢谢您

**Comment by reclock** [comment]
> 按照那个修改后，gmssl做客户端连接别的服务端使用ECC_SM4_SM3能通，但是GMSSL做服务端使用360浏览器访问报错，Decrypt Error，内容大概如下：
> 1684:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:ssl\record\rec_layer_s3.c:1385:SSL alert number 51
> 抓包发现是客户端响应了这个错误。

你是怎么改的能和其他服务器使用ECC_SM4_SM3通信，我这边还是报解密失败啊

**Comment by ChaosExplorer** [comment]
> > 遇到相同的错误
> > @Nu1i
> > 问题已解决，参照 #762
> > 重点是ID使用默认的"1234567812345678"以及`EVP_SignUpdate(md_ctx,buf, n+3)`
> > 使用360浏览器的话要使用带CA链的证书并信任即可

hi，我遇到了相同的decrypt error问题。

参照762修改后，问题依旧；
gmtls_construct_ske_sm2 继续改EVP_SignUpdate(md_ctx,buf, n+3)， 不是ssl3_read_bytes:tlsv1 alert decrypt error ， 而变为 bad signature 错误。

最新代码 gmtls_construct_client_certificate 里有Handshake header 长度+3的操作 ： int l = 3 + SSL_HM_HEADER_LENGTH(s);

**Comment by ChaosExplorer** [comment]
仔细看了下，最新代码 https://github.com/guanzhi/GmSSL/pull/762 的更改已经应用

**Comment by Mer1997** [comment]
> 仔细看了下，最新代码 #762 的更改已经应用

你好，我已经很长时间没有从事安全相关工作，可能没法进一步帮到你，抱歉

**Comment by ChaosExplorer** [comment]
> > 仔细看了下，最新代码 #762 的更改已经应用
> 
> 你好，我已经很长时间没有从事安全相关工作，可能没法进一步帮到你，抱歉

没事的，谢谢回复

**Comment by syr-1** [comment]
> > > 仔细看了下，最新代码 #762 的更改已经应用
> > 
> > 
> > 你好，我已经很长时间没有从事安全相关工作，可能没法进一步帮到你，抱歉
> 
> 没事的，谢谢回复

请问这个问题最终解决了吗？

**Comment by ChaosExplorer** [comment]
后面发现是版本不一致，gmssl 基于 openssl 1.1.0d 好像，client基于新的1.1.1 之后版本，layer层有更改。
回退 client版本可用

**Comment by 841194253** [comment]
现在解决了嘛
