### ISSUE TITLE
Bad Record MAC

### ISSUE THREAD

**Issue by jxdeng3264** [guanzhi/GmSSL#943]
抓包 SSL 握手，出现以下错误
`Alert (Level: Fatal, Description: Bad Record MAC)`

用 gmssl 替换了以前 客户端的 ssl， 就报上述错误。

![图片](https://user-images.githubusercontent.com/47386978/79103693-a8979580-7d9f-11ea-8c6e-590e993b3fa8.png)
![图片](https://user-images.githubusercontent.com/47386978/79103729-b8af7500-7d9f-11ea-9163-09816869f761.png)

**Comment by reclock** [comment]
这个问题没有解决吗？在国密平台测试也报这个错误了
