### ISSUE TITLE
sm2 公私钥转为16进制

### ISSUE THREAD

**Issue by ethancheung1990** [guanzhi/GmSSL#950]
请问怎样将pem格式的公私钥转换为16进制格式

**Comment by happyycm** [comment]
> 请问怎样将pem格式的公私钥转换为16进制格式

你的密钥格式转换有进展吗？我现在有16进制的，不知道怎么转成java能用的的ASN.1格式的

**Comment by slwcm** [comment]
我这边已经解决

**Comment by langrybird** [comment]
> 我这边已经解决

请问大佬怎么解决的？我有个16进制的字符串，不知道怎么转成pem格式的私钥

**Comment by slwcm** [comment]
chufeiwoyoumi微信 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;langrybird&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月21日(星期天) 上午10:34
收件人:&nbsp;&quot;guanzhi/GmSSL&quot;<GmSSL@noreply.github.com&gt;;
抄送:&nbsp;&quot;slwcm&quot;<164170384@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [guanzhi/GmSSL] sm2 公私钥转为16进制 (#950)
