### ISSUE TITLE
sm2 验签失败

### ISSUE THREAD

**Issue by xianrenqiu** [guanzhi/GmSSL#951]
各位老师好，GmSSL 真的是一个很棒的开源项目，在工作和学习过程中会经常使用到，希望可以在大家的共同努力下越做越好。最近在使用 GmSSL SM2 签名/验签进行压力测试时，发现有几率出现正确的签名无法通过验证(sm2算法)，我将出现问题的数据记录下来并在不同平台和不同编译选项下进行了测试，现象如下，请各位老师一起帮忙分析一下问题出在了哪里。

## 现象描述
1. 在 DELL OPTIPLEX 3040 MT 主机上使用固定的数据执行 SM2 验签操作，验签成功；
2. 在 Dell EMC PowerEdge T440 主机上使用固定的数据执行 SM2 验签操作，验签失败；
3. 在 Dell EMC PowerEdge T440 主机环境下，Gmssl 编译时配置选项中添加 -no-asm 后，验签成功；

> 上面描述的固定数据为：正确的 SM2 公钥，正确的 SM2 签名，正确的 SM2 消息摘要

## gmssl 版本
```
$ git log
commit a097e49719ac736e5a895ff3ddd25e26578d378f (HEAD -> master, origin/master, origin/HEAD, all)
Merge: 8e4e4ea 6011f0a
Author: Zhi Guan <guanzhi1980@gmail.com>
Date:   Fri Sep 6 16:08:52 2019 +0800

    Merge pull request #837 from Gorachya/master

    speed-update
```

## 测试代码
```
/* 测试代码可以直接链接 libcrypto 进行编译调试 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

#include <openssl/conf.h>
#include <openssl/evp.h>
#include <openssl/bn.h>
#include <openssl/sm2.h>

#define  CRYPTO_RET_FAILED       0
#define  CRYPTO_RET_SUCCESS      1
#define crypto_assert(cond)                                                  \
    do                                                                              \
    {                                                                               \
        if (!(cond))                                                                \
        {                                                                           \
            return CRYPTO_RET_FAILED;                                                             \
        }                                                                           \
    } while (0)


int crypto_key_to_eckey(uint8_t prikey[32], uint8_t pubkey[64], EC_KEY **eckey)
{
    if(pubkey)
    {
        uint8_t temp[65] = {0x04,};
        memcpy(temp + 1, pubkey, 64);
        uint8_t *p = temp;
        *eckey = o2i_ECPublicKey(eckey, (const uint8_t **)(&p), 65);
        crypto_assert(*eckey != 0);
    }
    
    if(prikey)
        EC_KEY_oct2priv(*eckey, prikey, 32);

    return CRYPTO_RET_SUCCESS;
}


int crypto_key2pkey(int nid, uint8_t prikey[32], uint8_t pubkey[64], EVP_PKEY *pkey)
{
    EC_KEY *ec_key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
    crypto_assert(ec_key != 0);
    EC_KEY_set_asn1_flag(ec_key, OPENSSL_EC_NAMED_CURVE);
    crypto_assert(crypto_key_to_eckey(prikey, pubkey, &ec_key) == CRYPTO_RET_SUCCESS);
    crypto_assert(EVP_PKEY_set1_EC_KEY(pkey, ec_key) != 0);

    EC_KEY_free(ec_key);
    return CRYPTO_RET_SUCCESS;
}

int crypto_bin2sigder(uint8_t *der, size_t *derlen, uint8_t sign[64])
{
    BIGNUM *rr = BN_new();
    BIGNUM *ss = BN_new();
    BN_bin2bn(sign, 32, rr);
    BN_bin2bn(sign + 32, 32, ss);
    ECDSA_SIG *s = ECDSA_SIG_new();
    ECDSA_SIG_set0(s, rr, ss);
    uint8_t *p = der;
    *derlen = i2d_ECDSA_SIG(s, &p);
    ECDSA_SIG_free(s);

    return CRYPTO_RET_SUCCESS;
}

int crypto_ecc_verify_internal(int nid, uint8_t pubkey[64], uint8_t digest[32], uint8_t sign[64])
{
    uint8_t sig_der[128];
    size_t sig_der_size = 128;

    EVP_PKEY *pkey = EVP_PKEY_new();
    crypto_assert(crypto_key2pkey(nid, NULL, pubkey, pkey) == CRYPTO_RET_SUCCESS);

    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new(pkey, NULL);
    crypto_assert(crypto_bin2sigder(sig_der, &sig_der_size, sign) == CRYPTO_RET_SUCCESS);
    crypto_assert(EVP_PKEY_verify_init(ctx) == 1);

    if(nid == NID_sm2p256v1)
        crypto_assert(EVP_PKEY_CTX_set_ec_scheme(ctx, NID_sm_scheme) == 1);
    
    crypto_assert(EVP_PKEY_verify(ctx, sig_der, sig_der_size, digest, 32) == 1);

    EVP_PKEY_free(pkey);
    EVP_PKEY_CTX_free(ctx);

    return CRYPTO_RET_SUCCESS;
}

int crypto_sm2_verify(uint8_t pubkey[64], uint8_t digest[32], uint8_t sign[64])
{
    return crypto_ecc_verify_internal(NID_sm2p256v1, pubkey, digest, sign);
}

int main(void)
{    
    uint8_t sm2_msg[32] =
    {
        0x54, 0x90, 0xFC, 0x4D, 0xF4, 0x6A, 0xA3, 0x3F, 0xC0, 0x8B, 0x40, 0x31, 0x6D, 0x2D, 0x5D, 0x1F,
        0x42, 0x66, 0xFB, 0xF5, 0x62, 0xB8, 0x08, 0xCA, 0x68, 0x51, 0xF6, 0xB0, 0x21, 0x78, 0x50, 0x75
    };

    uint8_t sm2_pubkey[64] =
    {
        0xD8, 0x6F, 0x33, 0x2E, 0x49, 0x6D, 0x85, 0x98, 0x56, 0xE5, 0x63, 0xC3, 0xA4, 0xE5, 0x56, 0x68,
        0x13, 0xAF, 0x0A, 0x8C, 0x77, 0x48, 0x72, 0x64, 0xAB, 0xE7, 0x6F, 0xA2, 0x36, 0x4D, 0x78, 0x7B,
        0xC7, 0xF9, 0x08, 0x1B, 0x66, 0x33, 0x71, 0x95, 0xB4, 0x75, 0x44, 0x63, 0x92, 0xB9, 0x8E, 0xE8,
        0x28, 0x38, 0xE9, 0xA6, 0xAD, 0x54, 0x4F, 0x0C, 0x52, 0x07, 0xDF, 0xFE, 0x4D, 0x83, 0x95, 0xDA
    };

    uint8_t sm2_sign[64] =
    {
        0x8F, 0x34, 0x8B, 0x86, 0x9A, 0x2E, 0x78, 0x05, 0x86, 0xBD, 0x3F, 0xB0, 0x1E, 0xC1, 0x2C, 0x1A, 
        0x4F, 0x24, 0xE6, 0xE4, 0x7E, 0x1B, 0x55, 0x25, 0x67, 0x8D, 0xDD, 0x08, 0x14, 0x1B, 0xE1, 0x9B,
        0xAE, 0xD9, 0x1D, 0x8B, 0xE9, 0xD0, 0x42, 0x67, 0x92, 0x62, 0xA7, 0xB9, 0x45, 0x6C, 0x92, 0x53, 
        0x34, 0x38, 0x4A, 0x13, 0x34, 0xAF, 0x44, 0x8A, 0xF7, 0x08, 0x64, 0x3F, 0x87, 0xD0, 0x71, 0x8D
    };

    int ret = crypto_sm2_verify(sm2_pubkey, sm2_msg, sm2_sign);

    printf("Crypto Demo: Do Sm2 Vrify %s.\n", (ret == CRYPTO_RET_SUCCESS) ? "success" : "failed");

    return 0;
}
```

从现象看似乎和不同 CPU 的汇编优指令优化有关，不知道有没有人遇到过类似的情况；

**Comment by FrozenFort** [comment]
你遇到的问题，在不加-no-asm的情况下编译，是每次生成的新签名都不能通过验证还是一部分不行？

**Comment by xianrenqiu** [comment]
> 你遇到的问题，在不加-no-asm的情况下编译，是每次生成的新签名都不能通过验证还是一部分不行？

是有概率通不过   可能几十万次出现一次   但我用其他工具做了验证   签名值是对的   但GmSSL验签失败

**Comment by xianrenqiu** [comment]
> 你遇到的问题，在不加-no-asm的情况下编译，是每次生成的新签名都不能通过验证还是一部分不行？

我代码中的这组数据    在有些 PC 上每次都验证失败（不加 -no-asm）   加上 -no-asm 后验证可以通过

**Comment by FrozenFort** [comment]
> 我代码中的这组数据 在有些 PC 上每次都验证失败（不加 -no-asm） 加上 -no-asm 后验证可以通过
> 是有概率通不过 可能几十万次出现一次 但我用其他工具做了验证 签名值是对的 但GmSSL验签失败

我猜测这可能是两个问题。加-no-asm可以解决的这个问题可能跟与架构相关的算法优化相关，而概率性出无效签名的问题可能是算法实现上有边界校验的bug。有可能这个边界校验在-no-asm的未做算法优化的模式下不会引起问题。对概率出现的这个问题我目前还没有找到好的解决方案 >_<

**Comment by xianrenqiu** [comment]
> > 我代码中的这组数据 在有些 PC 上每次都验证失败（不加 -no-asm） 加上 -no-asm 后验证可以通过
> > 是有概率通不过 可能几十万次出现一次 但我用其他工具做了验证 签名值是对的 但GmSSL验签失败
> 
> 我猜测这可能是两个问题。加-no-asm可以解决的这个问题可能跟与架构相关的算法优化相关，而概率性出无效签名的问题可能是算法实现上有边界校验的bug。有可能这个边界校验在-no-asm的未做算法优化的模式下不会引起问题。对概率出现的这个问题我目前还没有找到好的解决方案 >_<

恩    你说的很对   我也做了一些 debug，两台机器使用相同的程序进行调试，一台可以验证通过，一台验证失败，验证失败的会在计算点乘的过程中出错，但追到下面就是汇编代码了   能力有限没有继续深入，希望遇到这个问题的同学可以一起讨论分享一下解决方法。 

还有一个现象是只有 SM2 验签和 SM2解密才会出现    有趣的是 SM2签名和 SM2加密都需要使用随机数   不知道这个线索是否有分析价值；

**Comment by xianrenqiu** [comment]
> > 我代码中的这组数据 在有些 PC 上每次都验证失败（不加 -no-asm） 加上 -no-asm 后验证可以通过
> > 是有概率通不过 可能几十万次出现一次 但我用其他工具做了验证 签名值是对的 但GmSSL验签失败
> 
> 我猜测这可能是两个问题。加-no-asm可以解决的这个问题可能跟与架构相关的算法优化相关，而概率性出无效签名的问题可能是算法实现上有边界校验的bug。有可能这个边界校验在-no-asm的未做算法优化的模式下不会引起问题。对概率出现的这个问题我目前还没有找到好的解决方案 >_<

刚刚没注意到   我这里做了校验  这个签名并不是无效签名   是合法的签名    但是有几率验证失败

**Comment by FrozenFort** [comment]
> > > 我代码中的这组数据 在有些 PC 上每次都验证失败（不加 -no-asm） 加上 -no-asm 后验证可以通过
> > > 是有概率通不过 可能几十万次出现一次 但我用其他工具做了验证 签名值是对的 但GmSSL验签失败
> > 
> > 
> > 我猜测这可能是两个问题。加-no-asm可以解决的这个问题可能跟与架构相关的算法优化相关，而概率性出无效签名的问题可能是算法实现上有边界校验的bug。有可能这个边界校验在-no-asm的未做算法优化的模式下不会引起问题。对概率出现的这个问题我目前还没有找到好的解决方案 >_<
> 
> 刚刚没注意到 我这里做了校验 这个签名并不是无效签名 是合法的签名 但是有几率验证失败

我试验的现象是出错的签名一定通过不了验证，可能是我试验验签不够多没有撞到通过的情况 >_< 所以我之前猜测是签名的算法有问题，特定随机数、原文、公钥的组合导致生成错误的签名。我再验一下我的出错的签名看看会不会出现通过的情况。

**Comment by piggypiggy** [comment]
试试[https://github.com/guanzhi/GmSSL/issues/858](url)，可能是用bmi2指令优化的那部分写错了点

**Comment by xianrenqiu** [comment]
> 试试 #858，可能是用bmi2指令优化的那部分写错了点

多谢   可以把这部分的修改截图发我参考一下吗 

![image](https://user-images.githubusercontent.com/9956984/82173586-631b3a80-9900-11ea-8ed4-c3c63138d033.png)

**Comment by piggypiggy** [comment]
> 
> 
> > 试试 #858，可能是用bmi2指令优化的那部分写错了点
> 
> 多谢 可以把这部分的修改截图发我参考一下吗
> 
> ![image](https://user-images.githubusercontent.com/9956984/82173586-631b3a80-9900-11ea-8ed4-c3c63138d033.png)



在4个 `# reduction step ...`前都加上`add \$0, $acc2`
![sm2 bmi2 bugfix](https://user-images.githubusercontent.com/18366460/82178526-cb711880-990e-11ea-8161-db1fef432575.jpg)

**Comment by xianrenqiu** [comment]
@piggypiggy   厉害！！！    我验证了一下   真的是这个问题导致的   建议详细描述一下现象并提交一个 pull request     感觉被这个问题困扰的同学还挺多的；

最后，非常感谢 @piggypiggy  提供的帮助！

**Comment by piggypiggy** [comment]
> @piggypiggy 厉害！！！ 我验证了一下 真的是这个问题导致的 建议详细描述一下现象并提交一个 pull request 感觉被这个问题困扰的同学还挺多的；
> 
> 最后，非常感谢 @piggypiggy 提供的帮助！

pull request #961，但gmssl都快半年没更新了，感觉是不维护了

**Comment by xianrenqiu** [comment]
@piggypiggy   是的   感觉很久没有人维护了   如果GmSSL能像之前的 PolarSSL(现在的 ARM mbedtls) 一样，有公司收购并负责维护是最好的    我觉得GmSSL 是目前国内比较优秀的安全组件，适配性很强，从底层的国密算法(SM2/SM3/SM4/SM9等)到硬件 SDF/SKF 引擎，再到 SSL VPN套件的支持(后面希望能有标准组织定义国内的TLS标准)，真心希望有公司或社区做下支持。

**Comment by FrozenFort** [comment]
@xianrenqiu 这个问题里，调错汇编指令的地方是被签名调用的还是被验签调用的呀？
我想知道出了这个问题的签名，使用正确的验签逻辑是否能通过验证呢？

**Comment by xianrenqiu** [comment]
> @xianrenqiu 这个问题里，调错汇编指令的地方是被签名调用的还是被验签调用的呀？
> 我想知道出了这个问题的签名，使用正确的验签逻辑是否能通过验证呢？

签名没问题   验签出错

**Comment by piggypiggy** [comment]
> @xianrenqiu 这个问题里，调错汇编指令的地方是被签名调用的还是被验签调用的呀？
> 我想知道出了这个问题的签名，使用正确的验签逻辑是否能通过验证呢？

这段汇编是使用adx和mulx指令的蒙哥马利模乘，签名和验签都会调用。如果是在签名的时候出错了，那就不能验签，如果只是在验签的时候出错了，用正确的验签逻辑就能通过验证。
