### ISSUE TITLE
调用GO的API时，编译报错

### ISSUE THREAD

**Issue by infinite1900** [guanzhi/GmSSL#953]
我想要调用go包的sm4算法的api，编译时报错

# github.com/guanzhi/GmSSL/go/gmssl
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:62:2: imported and not used: "unsafe"
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:63:2: imported and not used: "errors"
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:64:2: imported and not used: "runtime"
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:67:6: GetPublicKeyAlgorithmNames redeclared in this block
	previous declaration at ../../../../../github.com/guanzhi/GmSSL/go/gmssl/pkey.go:568:37
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:98:6: GetSignAlgorithmNames redeclared in this block
	previous declaration at ../../../../../github.com/guanzhi/GmSSL/go/gmssl/pkey.go:578:52
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:136:2: cannot use nil as type string in return argument
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:140:2: cannot use nil as type string in return argument
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:144:2: cannot use nil as type string in return argument
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:152:2: cannot use nil as type string in return argument
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:156:2: cannot use nil as type string in return argument
../../../../../github.com/guanzhi/GmSSL/go/gmssl/sm9.go:156:2: too many errors

**Comment by chuanbowen** [comment]
golang 1.14，下面的语法是错误的。不太清楚兼容哪个版本的Golang
```
func (msk *SM9MasterSecret) GetPublicParametersPEM() (string, error) {
    return nil, nil;
}
```
