### ISSUE TITLE
执行go包中gmssltest示例时偶尔会报错

### ISSUE THREAD

**Issue by infinite1900** [guanzhi/GmSSL#955]
示例如下：
/* SM2 key pair operations */
sm2keygenargs := map[string]string {
	"ec_paramgen_curve": "sm2p256v1",
	"ec_param_enc": "named_curve",
}
sm2sk, err := gmssl.GeneratePrivateKey("EC", sm2keygenargs, nil)

报错信息：
207750592:error:1010C0B1:elliptic curve routines:pkey_ec_ctrl:no parameters set:crypto/ec/ec_pmeth.c:391:

这个示例有时会成功，有时会失败，失败的都是以上原因。

**Comment by guanzhi** [comment]
GmSSL-Go最近贡献给了超级账目项目的国密工作组 https://github.com/Hyperledger-TWGC/Gm-Go ，后续GmSSL的Go Wrapper会在超级账本的中国社区维护开发，请将问题新项目中。
