### ISSUE TITLE
用gmssl client 指定SM2-WITH-SMS4-SM3出错

### ISSUE THREAD

**Issue by huangyehui** [guanzhi/GmSSL#957]
我用客户端命令：
gmssl s_client -cipher "SM2-WITH-SMS4-SM3" -connect 127.0.0.1:1443 -key Client.key -cert ClientCA.crt -CAfile RootCA.crt -msg -debug 
指定套件为SM2-WITH-SMS4-SM3  就会报错
SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1502:
看支持的算法列表，是可以支持SM2-WITH-SMS4-SM3  。有人遇到过类似问题吗

**Comment by jiangbinghua** [comment]
我也遇到过类似问题，请问你解决了吗
