### ISSUE TITLE
./libcrypto.so: undefined reference to `EC_GFp_sm2z256_method'

### ISSUE THREAD

**Issue by liyuzhao** [guanzhi/GmSSL#958]
**Describe the bug**
when compile in aarch64 machine .
report:
./libcrypto.so: undefined reference to `EC_GFp_sm2z256_method'

what will resolve this issue ?

**Comment by pengtianabc** [comment]
你找一下这个函数的实现, 这个函数的上下文应该有一个宏定义, 有个else, 然后再编译期增加一个宏定义就可以了

**Comment by willson-chen** [comment]
这个属于移植问题，x86代码迁移到arm平台，需要做软件适配才会编译通过。

**Comment by Clinale** [comment]
根据关老师的回复，`EC_GFp_sm2z256_method` 只适用于Intel的CPU，可以在 `config` 阶段将该段优化代码屏蔽：
`./config -DGMSSL_NO_TURBO enable-ec_nistp_64_gcc_128`

相关问题链接：https://github.com/guanzhi/GmSSL/issues/660
