### ISSUE TITLE
master分支编译错误太多

### ISSUE THREAD

**Issue by wxh1013** [guanzhi/GmSSL#96]
commit id : d7aca8255f8f50c6eacf4a73c8bf096efb986a22

crypto/saf/saf_ec.c:94:33: note: each undeclared identifier is reported only once for each function it appears in
crypto/saf/saf_ec.c: In function 'SAF_GetEccPublicKey':
crypto/saf/saf_ec.c:184:22: error: 'pucContainerNamae' undeclared (first use in this function)
  if (!hAppHandle || !pucContainerNamae || !pucPUblicKey ||
                      ^
crypto/saf/saf_ec.c:184:44: error: 'pucPUblicKey' undeclared (first use in this function)
  if (!hAppHandle || !pucContainerNamae || !pucPUblicKey ||
                                            ^
crypto/saf/saf_ec.c:216:3: warning: passing argument 6 of 'saf_get_sdf_session_and_keyindex' makes integer from pointer without a cast [enabled by default]
   &uiKeyIndex)) != SAR_Ok) {
   ^
crypto/saf/saf_ec.c:148:5: note: expected 'unsigned int' but argument is of type 'unsigned int *'
 int saf_get_sdf_session_and_keyindex(
     ^
crypto/saf/saf_ec.c:249:2: warning: implicit declaration of function 'sdf_release_sdf_session' [-Wimplicit-function-declaration]
  sdf_release_sdf_session(hSessionHandle);
  ^
crypto/saf/saf_ec.c: In function 'SAF_EccSign':
crypto/saf/saf_ec.c:282:22: error: 'pucContainerNamae' undeclared (first use in this function)
  if (!hAppHandle || !pucContainerNamae || !pucPUblicKey ||
                      ^
crypto/saf/saf_ec.c:282:44: error: 'pucPUblicKey' undeclared (first use in this function)
  if (!hAppHandle || !pucContainerNamae || !pucPUblicKey ||
                                            ^
crypto/saf/saf_ec.c:283:20: error: 'pucSignDataLen' undeclared (first use in this function)
   !pucSignData || !pucSignDataLen) {
                    ^
crypto/saf/saf_ec.c:308:7: error: 'rv' undeclared (first use in this function)
  if ((rv = saf_get_sdf_session_and_ecsignkey(
       ^
crypto/saf/saf_ec.c:338:26: error: 'hSessionhandle' undeclared (first use in this function)
  saf_release_sdf_session(hSessionhandle);
                          ^
crypto/saf/saf_ec.c: In function 'SAF_EccVerifySign':
crypto/saf/saf_ec.c:358:23: error: expected ';' before ')' token
   return SAR_IndataErr);
                       ^
crypto/saf/saf_ec.c:358:23: error: expected statement before ')' token
crypto/saf/saf_ec.c:360:31: error: 'ECCrefPublic' undeclared (first use in this function)
  if (uiPublicKeyLen != sizeof(ECCrefPublic)) {
                               ^
crypto/saf/saf_ec.c: In function 'SAF_EccPublicKeyEnc':
crypto/saf/saf_ec.c:411:31: error: 'ECCrefPublic' undeclared (first use in this function)
  if (uiPublicKeyLen != sizeof(ECCrefPublic)) {
                               ^
crypto/saf/saf_ec.c:445:2: error: 'ret' undeclared (first use in this function)
  ret = SAR_Ok;
  ^
crypto/saf/saf_ec.c: In function 'SAF_EccPublicKeyEncByCert':
crypto/saf/saf_ec.c:477:23: error: expected ';' before ')' token
   return SAR_IndataErr);
                       ^
crypto/saf/saf_ec.c:477:23: error: expected statement before ')' token
crypto/saf/saf_ec.c:479:31: error: 'uiCertificate' undeclared (first use in this function)
  if (uiCertificateLen <= 0 || uiCertificate > INT_MAX) {
                               ^
crypto/saf/saf_ec.c: In function 'SAF_EccVerifySignByCert':
crypto/saf/saf_ec.c:550:23: error: expected ';' before ')' token
   return SAR_IndataErr);
                       ^
crypto/saf/saf_ec.c:550:23: error: expected statement before ')' token
crypto/saf/saf_ec.c:552:31: error: 'uiCertificate' undeclared (first use in this function)
  if (uiCertificateLen <= 0 || uiCertificate > INT_MAX) {
                               ^
crypto/saf/saf_ec.c: At top level:
crypto/saf/saf_ec.c:606:5: error: conflicting types for 'SAF_GenerateAgreementDataWithECC'
 int SAF_GenerateAgreementDataWithECC(
     ^
In file included from include/openssl/gmapi.h:61:0,
                 from crypto/saf/saf_ec.c:58:
include/openssl/saf.h:476:5: note: previous declaration of 'SAF_GenerateAgreementDataWithECC' was here
 int SAF_GenerateAgreementDataWithECC(
     ^
crypto/saf/saf_ec.c: In function 'SAF_GenerateAgreementDataWithECC':
crypto/saf/saf_ec.c:620:15: error: 'uiISKIndex' redeclared as different kind of symbol
  unsigned int uiISKIndex;
               ^
crypto/saf/saf_ec.c:608:15: note: previous definition of 'uiISKIndex' was here
  unsigned int uiISKIndex,
               ^
crypto/saf/saf_ec.c: In function 'SAF_GenerateKeyWithECC':
crypto/saf/saf_ec.c:666:3: error: label 'end' used but not defined
   goto end;
   ^
crypto/saf/saf_ec.c:654:6: warning: unused variable 'ret' [-Wunused-variable]
  int ret = -1;
      ^

**Comment by guanzhi** [comment]
./config no-saf no-sdf no-skf no-sof no-zuc
