### ISSUE TITLE
用gmssl 2.0做的签名，用gmssl 2.5.4不能验签，反之亦然

### ISSUE THREAD

**Issue by suishixingkong** [guanzhi/GmSSL#964]
用gmssl pkeyutl命令做的签名和验签，不同版本不能相互兼容，为什么？我有一个国密加密卡，这个加密卡和gmssl2.0版本是可以相互验签的，gmssl2.5.4就不行

**Comment by guanzhi** [comment]
SM2正式标准中对签名过程和签名值的格式都有了更明确的要求，而2.0版本时遵守的是早期的规范，和目前的不通用。你买的同期的加密卡应该也是遵守了早期的规范草案，只要向生产商要最新的驱动或者开发包应该就可以和目前的GmSSL版本兼容。
