### ISSUE TITLE
关于现有库裁剪去掉不需要的模块

### ISSUE THREAD

**Issue by 942685826** [guanzhi/GmSSL#966]
关老师，您好。我们想要在嵌入式开发板上允许gmssl，由于我们的文件大小有限。我通过了./config no-zlib no-asm no-threads...配置关闭了不需要的算法，也把优化等级-O3改为-O。这样编译完库只是缩小了500k左右。请问还有没有其他方法可以缩减更多，最小可以小到多少？ 我们要使用SM2-SMS4-SM3这个加密套件

**Comment by wuyougongzi** [comment]
看了下源代码的结构，加密套件部分代码应该可以分离，没有亲自试过，可以试下仅保留你需要的加密套件，然后编译试下。
