### ISSUE TITLE
SM9 算法现在实现了吗？

### ISSUE THREAD

**Issue by wxh1013** [guanzhi/GmSSL#97]
SM9 算法现在实现了吗？

**Comment by guanzhi** [comment]
No

**Comment by wxh1013** [comment]
guanzhi，
   你好，目前国密官网上没看到SM9的spec文档。我在网上http://dacas.cn/thread.aspx?ID=2690搜索到一份。不知道是否国密发布的是否一样？目前也在研究怎么实现它

**Comment by guanzhi** [comment]
crypto/sm9 目录下有实现，只是依赖的pairing运算还没有最终完成。gmssl应该很快会提供sm9以及IBC的国际标准算法的实现。

**Comment by guanzhi** [comment]
目前sm9算法实现就是参考这个文本的，数据结构编码上使用了自定义的格式。由于没有购买标准文本，因此即使国密标准定义的和目前的实现有比较大的出入，gmssl-2.x版本内也不会参考标准做大的调整了。

**Comment by RundongYang** [comment]
想问下pairing运算现在加进去了吗 ？SM9现在完整了吗？
 @guanzhi
