### ISSUE TITLE
SDF引擎无法运行

### ISSUE THREAD

**Issue by gaoshangdelu** [guanzhi/GmSSL#971]
在我编译完成后执行 gmssl engine sdf -vvvv
出错
Using configuration from /usr/lib64/openssl/ssl/openssl.cnf
139742205196096:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/usr/lib64/openssl/lib/engines-1.1/sdf.so): /usr/lib64/openssl/lib/engines-1.1/sdf.so: cannot open shared object file: No such file or directory
139742205196096:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
139742205196096:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
139742205196096:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=sdf

**Comment by willson-chen** [comment]
Command  `$ export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` could solve your problem?

**Comment by gaoshangdelu** [comment]
> 
> 
> Command `$ export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` could solve your problem?
报错相同.我觉得问题可能有两个方面
1.代码有问题，在之前编译的情况下，sm9test.c本身编译报错，在注释掉几行后编译才通过。
2.sdf代码里有sansec的代码，据我所知这是三未信安加密卡的适配，不知道是不是因为没安三未信安加密卡的问题。
现在商密需要硬件适配
我做的就是另外一个加密卡适配，如果gmssl能给个详细的gmssl调用加密卡的讲解demo就好了，或者建立一个gmssl的社区

**Comment by willson-chen** [comment]
> 1.代码有问题，在之前编译的情况下，sm9test.c本身编译报错，在注释掉几行后编译才通过。

这部分是测试代码，和这部分测试代码没有关系。

> 2.sdf代码里有sansec的代码，据我所知这是三未信安加密卡的适配，不知道是不是因为没安三未信安加密卡的问题。
> 现在商密需要硬件适配
> 我做的就是另外一个加密卡适配，如果gmssl能给个详细的gmssl调用加密卡的讲解demo就好了，或者建立一个gmssl的社区

#569 和#878 中有讨论到这个问题，可以参考下。
