### ISSUE TITLE
recipe for target 'test/sm9test' failed

### ISSUE THREAD

**Issue by Kindhearted57** [guanzhi/GmSSL#976]
**Describe the bug**
在`make`的时候报错

**Expected behavior**
应该能够成功`make`，并且进行`make install `

**Screenshots**
![016DCC0A946F13CB7EFD039917971D28](https://user-images.githubusercontent.com/34344692/84582865-47825180-ae24-11ea-9097-94db078cc8cd.jpg)

**Environments**
- OS: ubuntu 18.04LTS
- Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Additional context**
看报错找到sm9test.c这个文件，418行
```if(!rate_test())...```
然而，`rate_test`只在这个文件中出现过一次，所以可能是`rate_test`这个变量的问题？

**Comment by Demontf** [comment]
同样遇到这个问题

**Comment by Demontf** [comment]
@Kindhearted57 我把418的那组判断注释掉就编译通过了

**Comment by 8585435** [comment]
> @ Kindhearted57我把418的那组判断注释掉就编译通过了

我也是这么干的

**Comment by zhaoxiaomeng** [comment]
已经在最新的代码中修复了
