### ISSUE TITLE
TLS ECDHE过程中错误的SM2曲线名称

### ISSUE THREAD

**Issue by Trisia** [guanzhi/GmSSL#978]
1. 执行TLS SM2的密钥交换构造中使用了错误的椭圆曲线名称`30`。

位置：`ssl/statem/statem_gmtls.c`中的`static int gmtls_construct_ske_sm2dhe(SSL *s, unsigned char **p, int *l, int *al)`

```c
	/* output ECParameters as NameCurve */
	*d++ = NAMED_CURVE_TYPE;
	*d++ = 0;
	*d++ = 30;
```

根据IANA注册`curveSM2`应该使用`41`的标识标识符

![image](https://user-images.githubusercontent.com/17817790/84846838-3fbfe880-b082-11ea-84eb-d1e0bbc41fbd.png)

- 请参考[IANA Transport Layer Security (TLS) Parameters #TLS Supported Groups ](https://www.iana.org/assignments/tls-parameters/tls-parameters.xml#tls-parameters-8)

2. 在对SM2 ECDHE的处理函数上检查了命名椭圆曲线的，按照《GM/T 0024-2014 SSL VPN技术规范》 6.4.4.3 Server Key Exchange消息 a) ServerECDHEParameters 中的说明：“如果使用SM2算法，第一个参数不校验”

![image](https://user-images.githubusercontent.com/17817790/84846219-e3a89480-b080-11ea-82ec-6efba47f2e76.png)

在`ssl/statem/statem_gmtls.c`的`static int gmtls_process_ske_sm2dhe(SSL *s, PACKET *pkt, int *al)`校验了该参数：
```c
	if (ecparams[0] != NAMED_CURVE_TYPE || ecparams[1] != 0 || ecparams[2] != 30) {
		*al = SSL_AD_DECODE_ERROR;
		SSLerr(SSL_F_GMTLS_PROCESS_SKE_SM2DHE, SSL_R_WRONG_CURVE);
		return 0;
	}
```

**Comment by reclock** [comment]
这个应该怎么修改？我也遇到报错 wrong curve

**Comment by zhenyuwei** [comment]
后面两个判断直接删掉
