### ISSUE TITLE
Mac编译报错

### ISSUE THREAD

**Issue by ltmhaha** [guanzhi/GmSSL#981]
MacOs 10.15.5
make命令后

Undefined symbols for architecture x86_64:
  "_rate_test", referenced from:
      _main in sm9test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_app.darwin] Error 1
make[1]: *** [test/sm9test] Error 2
make: *** [all] Error 2

请问这个要怎么解决？

**Comment by JacksonTian** [comment]
同问。

**Comment by zhaoxiaomeng** [comment]
已修复
