### ISSUE TITLE
16进制转私钥

### ISSUE THREAD

**Issue by langrybird** [guanzhi/GmSSL#984]
比如我有一个4D96465BAB202D6BEF221A6E387137A699170E9FFCA3788A2C30C0A8FAD1AA93
这样16进制的字符串，怎么转成openssl_sign 中的$prikey！急求

**Comment by pengtianabc** [comment]
见 sm2test.c-new_ec_key(...)

**Comment by foryougood** [comment]
每次取两位，转16进制的数，依次往私钥数组赋值就可以
