### ISSUE TITLE
使用JNA调用gmssl的sm9解密算法时出现错误

### ISSUE THREAD

**Issue by eyebrown** [guanzhi/GmSSL#987]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eyebrown** [comment]
在sm9_enc.c文件中469行，SM9_decrypt函数中的 if (*outlen < C2_len)语句。
        编译后的sm9test程序可以通过sm9加解密的测试，但在sm9test.c中，sm9test_enc函数在调用SM9_decrypt函数时，传入了mlen的地址（outlen）。可是mlen是个未初始化的随机值，在469行拿一个随机值进行比较不合理。
        在使用JNA调用SM9_decrypt函数时，我同sm9test.c中一样，没有对outlen指向的变量初始化，但Java中未初始化的变量默认为0，所以在469行出错。
         我理解的是，outlen用来让函数调用者获得解密后数据的长度，不应该在未赋值时参与比较。
         想请教下，这个地方是sm9test_enc函数中忘记了给传入的变量赋值?还是SM9_decrypt函数中的函数处理流程有错误？
`int SM9_decrypt(int type,const unsigned char *in, size_t inlen,unsigned char *out, size_t *outlen,SM9PrivateKey *sk){
     ......
     ......
     	if (!out) {
		*outlen = C2_len;
		ret = 1;
`		goto end;
	} else if (*outlen < C2_len) {  //第469行出问题的地方   
		SM9err(SM9_F_SM9_DECRYPT, SM9_R_BUFFER_TOO_SMALL);
		goto end;
	}
   ......
   ......
}`

**Comment by w158rk** [comment]
@eyebrown *outlen应该事先赋值为out缓冲区的大小，感觉这里是为了检查明文缓冲区够不够大

**Comment by DWFLZXJ** [comment]
> 在sm9_enc.c文件中469行，SM9_decrypt函数中的 if (*outlen < C2_len)语句。 编译后的sm9test程序可以通过sm9加解密的测试，但在sm9test.c中，sm9test_enc函数在调用SM9_decrypt函数时，传入了mlen的地址（outlen）。可是mlen是个未初始化的随机值，在469行拿一个随机值进行比较不合理。 在使用JNA调用SM9_decrypt函数时，我同sm9test.c中一样，没有对outlen指向的变量初始化，但Java中未初始化的变量默认为0，所以在469行出错。 我理解的是，outlen用来让函数调用者获得解密后数据的长度，不应该在未赋值时参与比较。 想请教下，这个地方是sm9test_enc函数中忘记了给传入的变量赋值?还是SM9_decrypt函数中的函数处理流程有错误？ `int SM9_decrypt(int type,const unsigned char *in, size_t inlen,unsigned char *out, size_t *outlen,SM9PrivateKey *sk){ ...... ...... if (!out) { *outlen = C2_len; ret = 1; ` goto end; } else if (*outlen < C2_len) { //第469行出问题的地方 SM9err(SM9_F_SM9_DECRYPT, SM9_R_BUFFER_TOO_SMALL); goto end; } ...... ...... }`

请问有支持SM9的相关代码吗？现在gmssl的版本里java接口并不支持SM9
