### ISSUE TITLE
使用ssl库，连接HTTP2协议的服务器，调用SSL_free()崩溃

### ISSUE THREAD

**Issue by zelxzhou** [guanzhi/GmSSL#988]
**Describe the bug**
使用GmSSL-master.zip源码编译出来的libssl库，连接苹果的推送服务器api.push.apple.com:2197，服务器是HTTP2协议，TLS连接建立成功后，立即断开连接，调用SSL_free()崩溃，连接华为推送服务器login.vmall.com:443，SSL_free()正常

SSL_new(ssl_ctx);
SSL_do_handshake(ssl);
SSL_shutdown(ssl);
SSL_free(ssl);

**Comment by QinLongFei** [comment]
请问libssl用的是SM算法建立的TLS连接吗？

**Comment by zelxzhou** [comment]
我就是正常调用openssl的api，调用顺序我上面已经列出来了，应该不是SM算法建立连接的，因为没有指定算法的入参，苹果推送服务器应该也不支持SM算法，我就是正常调用api，我用官方版本的openssl的编译库，连接苹果推送服务器是正常的，但用gmssl的编译库就不行，所以我怀疑是gmssl在支持http2协议哪里有问题，导致在断开连接的时候，调用SSL_free(ssl)导致程序崩溃

**Comment by zelxzhou** [comment]
补充一下，gmssl的编译库连接苹果推送服务器是没有问题的，但在断开的时候，调用SSL_free(ssl)就程序崩溃
