### ISSUE TITLE
GMSSL在windows上编译成功的环境有什么要求呢？

### ISSUE THREAD

**Issue by gracesun** [guanzhi/GmSSL#992]
我的编译环境：
windws10+VS2015+perl 5.26.3(64bit)

报错信息如下：
Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.17336
Copyright (C) Microsoft Corporation.  All rights reserved.
        IF EXIST libcrypto-1_1.dll.manifest DEL /F /Q libcrypto-1_1.dll.manifest
        link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1.dll /def:libcrypto-1_1.def @C:\Users\grace-PC\AppData\Local\Temp\nmABC4.tmp || (DEL /Q libcrypto.* libcrypto-1_1.* && EXIT 1)
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_ciphernames
libcrypto-1_1.def : error LNK2001: 无法解析的外部符号 EVP_get_digestnames
libcrypto.lib : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “link”: 返回代码“0x1”

希望项目组给与指导，谢谢！

**Comment by Msgg-zy** [comment]
我遇到了跟你一样的问题，然后从之前的一个回复中找到了一个解决我问题的解答，你可以参考一下。
在历史中找到旧版本的crypto\evp\names2.c文件覆盖你下载的新版本里的同名文件就可以了，前提是其中实现了这两个无法解析的外部符号接口，具体可以打开看一下

**Comment by fartec** [comment]
我是直接删除了定义来解决这个问题，但是在使用的时候sgd.h中的数据类型与Windows中的数据类型重定义，暂时没找到好的解决办法。。。不知道还有没有其他人在Windows下使用？遇到过这个问题？

**Comment by gracesun** [comment]
> 我遇到了跟你一样的问题，然后从之前的一个回复中找到了一个解决我问题的解答，你可以参考一下。
> 在历史中找到旧版本的crypto\evp\names2.c文件覆盖你下载的新版本里的同名文件就可以了，前提是其中实现了这两个无法解析的外部符号接口，具体可以打开看一下

谢谢，可以正常编译，还在测试对结果是否有影响。

**Comment by reclock** [comment]
> 我遇到了跟你一样的问题，然后从之前的一个回复中找到了一个解决我问题的解答，你可以参考一下。
> 在历史中找到旧版本的crypto\evp\names2.c文件覆盖你下载的新版本里的同名文件就可以了，前提是其中实现了这两个无法解析的外部符号接口，具体可以打开看一下

现在没有旧版本了，去哪里找一个names2.c  ??

**Comment by Msgg-zy** [comment]
> > 我遇到了跟你一样的问题，然后从之前的一个回复中找到了一个解决我问题的解答，你可以参考一下。
> > 在历史中找到旧版本的crypto\evp\names2.c文件覆盖你下载的新版本里的同名文件就可以了，前提是其中实现了这两个无法解析的外部符号接口，具体可以打开看一下
> 
> 现在没有旧版本了，去哪里找一个names2.c ??

还有啊，我刚看了一下还有三年前的历史啊

**Comment by heyanheyan** [comment]
> > > 我遇到了跟你一样的问题，然后从之前的一个回复中找到了一个解决我问题的解答，你可以参考一下。
> > > 在历史中找到旧版本的crypto\evp\names2.c文件覆盖你下载的新版本里的同名文件就可以了，前提是其中实现了这两个无法解析的外部符号接口，具体可以打开看一下
> > 
> > 
> > 现在没有旧版本了，去哪里找一个names2.c ??
> 
> 还有啊，我刚看了一下还有三年前的历史啊

没用啊在！只有19年的

**Comment by dengpeng1004** [comment]
/*
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <internal/objects.h>
#include <openssl/x509.h>
#include "internal/evp_int.h"

const EVP_CIPHER *EVP_get_default_cipher(void)
{
	return NULL;
}

/*
 * use MD5 as default:
 *	X509_REQ_to_X509		x509_r2x.c
 *	X509_issuer_and_serial_hash	x509_cmp.c
 *	X509_NAME_hash_old		x509_cmp.c
 *	PEM_ASN1_write_bio		pem_lib.c
 */
const EVP_MD *EVP_get_default_digest(void)
{
#if !defined(OPENSSL_NO_MD5)
	return EVP_md5();
#elif !defined(OPENSSL_NO_SHA)
	return EVP_sha1();
#elif !defined(OPENSSL_NO_SM3)
	return EVP_sm3();
#elif !defined(OPENSSL_NO_RIPEMD)
	return EVP_rmd160();
#else
	return NULL;
#endif
}

static void cipher_name_len(const EVP_CIPHER *cipher, const char *from,
	const char *to, void *x)
{
	*((int *)x) += strlen(EVP_CIPHER_name(cipher));
}

static void cipher_name(const EVP_CIPHER *cipher, const char *from,
	const char *to, void *x)
{
	strcat((char *)x, EVP_CIPHER_name(cipher));
}

char *EVP_get_ciphernames(int aliases)
{
	char *ret = NULL;
	int len = 0;
	EVP_CIPHER_do_all_sorted(cipher_name_len, &len);

	ret = OPENSSL_zalloc(len);
	if (!ret) {
		return NULL;
	}

	EVP_CIPHER_do_all_sorted(cipher_name, ret);
	return ret;
}

char *EVP_get_digestnames(int aliases)
{
	return "sm3:sha1:sha256";
}

**Comment by luhongxin1349** [comment]
Comment on these two lines
