### ISSUE TITLE
windows JNI编译通过的方法

### ISSUE THREAD

**Issue by zhangxy123666** [guanzhi/GmSSL#994]
1- 按照官网正常流程编译，不要在Configure里面加java，加上一定编译不过，貌似要改很多东西吧
2- linux是make, windowns是nmake, 编译好之后， 进入到GmSSL的java目录，建立包名的目录
    也就是建立  org/gmssl  然后把GmSSL.java移到这个目录下
    win下或者linux都可以，我装了msys2在win10测试的
    先在GMSSL里面的java目录下执行 gcc -shared -fPIC -Wall -I./jni -I ../include -L ../ GmSSL.c -lcrypto -o libgmssljni.dll
    然后执行编译  javac org\gmssl\GmSSL.java
   **（如果提示找不到动态库，就直接这样写 
     static {
		System.load("D:\\xxxxx\\GmSSL-master\\GmSSL-master\\java\\libgmssljni.dll");
	}）**
    然后执行 java org.gmssl.GmSSL

来个图
![image](https://user-images.githubusercontent.com/41684879/87018467-dc9a1f80-c203-11ea-9586-addeb35b00f4.png)

SM2在win下可以跑通了

**Comment by Nu1i** [comment]
请教windows底下如何生成JNI相关的东西

**Comment by zhangxy123666** [comment]
windows按照官网文档，直接编译就行，但是记得Configure里面不要加java，加了编译不过

**Comment by Nu1i** [comment]
> windows按照官网文档，直接编译就行，但是记得Configure里面不要加java，加了编译不过

安装官方编译通过之后，按照您之前的也编译通过，但是在windows平台执行java的时候虚拟机似乎崩溃了

**Comment by zhangxy123666** [comment]
可以运行的，需要把   编译出来的3个文件复制过来，在gmssl-master面
![image](https://user-images.githubusercontent.com/41684879/89248211-bff5d980-d641-11ea-8ad0-2a94ef38bcb3.png)
放进去就能运行了
![image](https://user-images.githubusercontent.com/41684879/89248235-d00db900-d641-11ea-8168-70717e1c9217.png)

**Comment by zhangxy123666** [comment]
分别用gcc和vs自带的cl进行编译输出dll以及调用

https://github.com/zhangxy123666/gmssl-ftw/blob/master/README.md

**Comment by Nu1i** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: gmssl.GmSSL.getVersions()[Ljava/lang/String;

这是方法名不对？

**Comment by zhangxy123666** [comment]
我看着像是DLL文件没加载对把，你看下system.load的那里 路径对不对

**Comment by xinyannna** [comment]
在GMSSL里面的java目录下执行 gcc -shared -fPIC -Wall -I./jni -I ../include -L ../ GmSSL.c -lcrypto -o libgmssljni.dll
这个还是在vs的cmd里面执行吗，可是它提示：
D:\项目\SM9\GmSSL-master\java>gcc -shared -fPIC -Wall -I./jni -I ../include -L ../ GmSSL.c -lcrypto -o libgmssljni.dll
GmSSL.c:1: warning: -fPIC ignored for target (all code is position independent)
C:\mingw\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe: cannot find -lcrypto
collect2: ld returned 1 exit status
这个怎么解决啊

**Comment by cccgnit** [comment]
C:\mingw\bin..\lib\gcc\mingw32\3.4.5........\mingw32\bin\ld.exe: cannot find -lcrypto 同问

**Comment by xcw233** [comment]
> javac org\gmssl\GmSSL.java

具体放在jdk哪个位置

**Comment by DWFLZXJ** [comment]
cannot find -lcrypto 是因为32位编译的libcrypto.lib，gcc的时候又是用的64位的环境所以当前目录就算有libcrypto.lib他也会skip掉 要用x64的命令窗口去执行以下命令 1、perl Configure VC-WIN64A 2、nmake 3、nmake install  
![image](https://user-images.githubusercontent.com/16658633/161016106-12776c1b-a5eb-44d8-8a1a-d92116b0d250.png)
