### ISSUE TITLE
mac 环境的客户端无法ssl_connect 到服务端

### ISSUE THREAD

**Issue by mindandhand** [guanzhi/GmSSL#995]
**Describe the bug**
mac 环境的客户端无法ssl_connect 到服务端，但是windows 或者centos是正常的，通过抓包发现，windows 发送clienthello的时候版本是0301，而mac发送的版本是0101，且在包头尾部无Extension，导致此阶段服务端无应答。

**Expected behavior**
mac clientHello 问题得到修复
**Screenshots**

*
![image](https://user-images.githubusercontent.com/36306789/87238769-667efe00-c439-11ea-869a-aea71c397a99.png)
![image](https://user-images.githubusercontent.com/36306789/87238914-5700b480-c43b-11ea-9fb8-0ad32c09f8bc.png)
*Environments**
- OS: [10.14.6 ]
- Compiler: [Apple clang version 11.0.0 (clang-1100.0.33.17)]

**Additional context**

**Comment by zhaoxiaomeng** [comment]
您这边用什么命令connect的呢？用的s_client还是？

**Comment by ww1999520** [comment]
linux的gmssl也存在这样的问题,我通过socket封装的httpclient在连接https服务器时,connect成功之后,ssl_connect失败;
ssl_connect返回值为-1;SSL_get_error返回值为5;errno = 104;
https服务器打印的握手错误是:unknown protocol;
下面是部分伪代码,是在connect成功之后的代码(备注:这份代码在windows下是正常的)
int fd;
	int iret;
	const SSL_METHOD *meth1 = SSLv23_client_method();
	SSL_CTX* __ssl_ctx = SSL_CTX_new(meth1);
	if(__ssl_ctx != NULL)
	{
		SSL_CTX_set_verify(__ssl_ctx,SSL_VERIFY_NONE,NULL);
		SSL* __ssl = SSL_new(__ssl_ctx);
		if(__ssl != NULL)
		{
			iret = SSL_set_fd(__ssl,(int)fd);
			if(iret == 1)
			{
				iret = SSL_connect(__ssl);
				if(iret != 1)
				{
					printf("SSL_connect failed,iret:%d,ssl_err:%d,err:%d",iret,SSL_get_error(__ssl,iret),errno);
				}
			}
		}
	}

**Comment by ww1999520** [comment]
> linux的gmssl也存在这样的问题,我通过socket封装的httpclient在连接https服务器时,connect成功之后,ssl_connect失败;
> ssl_connect返回值为-1;SSL_get_error返回值为5;errno = 104;
> https服务器打印的握手错误是:unknown protocol;
> 下面是部分伪代码,是在connect成功之后的代码(备注:这份代码在windows下是正常的)
> int fd;
> int iret;
> const SSL_METHOD meth1 = SSLv23_client_method();
> SSL_CTX __ssl_ctx = SSL_CTX_new(meth1);
> if(__ssl_ctx != NULL)
> {
> SSL_CTX_set_verify(__ssl_ctx,SSL_VERIFY_NONE,NULL);
> SSL* __ssl = SSL_new(__ssl_ctx);
> if(__ssl != NULL)
> {
> iret = SSL_set_fd(__ssl,(int)fd);
> if(iret == 1)
> {
> iret = SSL_connect(__ssl);
> if(iret != 1)
> {
> printf("SSL_connect failed,iret:%d,ssl_err:%d,err:%d",iret,SSL_get_error(__ssl,iret),errno);
> }
> }
> }
> }

linux是centos7:
centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by ww1999520** [comment]
> linux的gmssl也存在这样的问题,我通过socket封装的httpclient在连接https服务器时,connect成功之后,ssl_connect失败;
> ssl_connect返回值为-1;SSL_get_error返回值为5;errno = 104;
> https服务器打印的握手错误是:unknown protocol;
> 下面是部分伪代码,是在connect成功之后的代码(备注:这份代码在windows下是正常的)
> int fd;
> int iret;
> const SSL_METHOD meth1 = SSLv23_client_method();
> SSL_CTX __ssl_ctx = SSL_CTX_new(meth1);
> if(__ssl_ctx != NULL)
> {
> SSL_CTX_set_verify(__ssl_ctx,SSL_VERIFY_NONE,NULL);
> SSL* __ssl = SSL_new(__ssl_ctx);
> if(__ssl != NULL)
> {
> iret = SSL_set_fd(__ssl,(int)fd);
> if(iret == 1)
> {
> iret = SSL_connect(__ssl);
> if(iret != 1)
> {
> printf("SSL_connect failed,iret:%d,ssl_err:%d,err:%d",iret,SSL_get_error(__ssl,iret),errno);
> }
> }
> }
> }
> 
> linux是centos7:
> centos-release-7-7.1908.0.el7.centos.x86_64

我搞错了,windows也存在这个问题....很奇怪,我单独用openssl 1.0.1i来连第三方服务就不会出问题,ssl.version我也看了也是0x303
不过linux下通信的时候会打印:
ssl_get_algorithm2=0x08x
这个应该是gmssl内部的代码打印出来的

**Comment by ww1999520** [comment]
我使用了s_client做测试:

CONNECTED(00000003)
depth=1 C = CN, ST = SHANDONG, L = JINAN, O = SDCA, OU = SDCA, CN = ShanDongRSACA
verify error:num=20:unable to get local issuer certificate
ssl_get_algorithm2=0x08x
ssl_get_algorithm2=0x08x
ssl_get_algorithm2=0x08x
ssl_get_algorithm2=0x08x
write:errno=104
---
Certificate chain
 0 s:/CN=60.208.56.186/OU=\xE5\xB1\xB1\xE4\xB8\x9C\xE5\x9B\xBD\xE7\x9B\xBE\xE7\xBD\x91\xE4\xBF\xA1\xE6\x81\xAF\xE7\xA7\x91\xE6\x8A\x80\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/O=\xE5\xB1\xB1\xE4\xB8\x9C\xE5\x9B\xBD\xE7\x9B\xBE\xE7\xBD\x91\xE4\xBF\xA1\xE6\x81\xAF\xE7\xA7\x91\xE6\x8A\x80\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/L=jinan/ST=SD/C=CN
   i:/C=CN/ST=SHANDONG/L=JINAN/O=SDCA/OU=SDCA/CN=ShanDongRSACA
 1 s:/C=CN/ST=SHANDONG/L=JINAN/O=SDCA/OU=SDCA/CN=ShanDongRSACA
   i:/C=CN/ST=\xE5\xB1\xB1\xE4\xB8\x9C\xE7\x9C\x81/L=\xE6\xB5\x8E\xE5\x8D\x97\xE5\xB8\x82/O=\xE5\xB1\xB1\xE4\xB8\x9C\xE7\x9C\x81\xE6\x95\xB0\xE5\xAD\x97\xE8\xAF\x81\xE4\xB9\xA6\xE8\xAE\xA4\xE8\xAF\x81\xE7\xAE\xA1\xE7\x90\x86\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/OU=\xE5\xB1\xB1\xE4\xB8\x9C\xE7\x9C\x81\xE6\x95\xB0\xE5\xAD\x97\xE8\xAF\x81\xE4\xB9\xA6\xE8\xAE\xA4\xE8\xAF\x81\xE7\xAE\xA1\xE7\x90\x86\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/CN=SDCA Root Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFEzCCA/ugAwIBAgIIIBkFMQE5FGAwDQYJKoZIhvcNAQEFBQAwZjELMAkGA1UE
BhMCQ04xETAPBgNVBAgMCFNIQU5ET05HMQ4wDAYDVQQHDAVKSU5BTjENMAsGA1UE
CgwEU0RDQTENMAsGA1UECwwEU0RDQTEWMBQGA1UEAwwNU2hhbkRvbmdSU0FDQTAe
Fw0xOTA1MzAxOTU2MDFaFw0yNDA1MzAxOTU2MDFaMIGmMRYwFAYDVQQDDA02MC4y
MDguNTYuMTg2MTAwLgYDVQQLDCflsbHkuJzlm73nm77nvZHkv6Hmga/np5HmioDm
nInpmZDlhazlj7gxMDAuBgNVBAoMJ+WxseS4nOWbveebvue9keS/oeaBr+enkeaK
gOaciemZkOWFrOWPuDEOMAwGA1UEBwwFamluYW4xCzAJBgNVBAgMAlNEMQswCQYD
VQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANepSPx77x+f
TaPn7unANlTfUzYzXSTrabcdrZlRCkuHyDDd1l76+yPtLSfk0+2dt0Ug35RRkQkn
3eKsL/m7qzNR4ZHfy4Xk/bzUA1mOL0Wj0f/CBCOyeIbbqRziogalPnsEq3gNPmEj
PgRXYoj/ELOzoDojAlEaCZvHSrthvo0XzltLIcIeIm2IxiMcvj+X24zPwSGFLQ1O
HQLcY+qkD2xyvxPeXK32pI+GOeK+Fti0a6+dis0C8D0td2NHdQhpcu9lXrhPxh2m
KKQLHT6XcnXHeLJtRmiLrPiGaBq9UE2Lq7tP9LCe0jsyYV1XX7XBaHS+PlE+dwsr
jn76AYVuXLsCAwEAAaOCAYIwggF+MB8GA1UdIwQYMBaAFM0suD3RjbSVnO06gWLG
5YZgjIc3MB0GA1UdDgQWBBQtYSReJR5JiLHJosPI802qhNJ06DAJBgNVHRMEAjAA
MEIGA1UdHwQ7MDkwN6A1oDOGMWh0dHA6Ly8yMjEuMjE0LjUuNjY6ODA4OC9TaGFu
RG9uZ1NNMkNBL1NNMkNSTC5qc3AwWQYIKwYBBQUHAQEETTBLMEkGCCsGAQUFBzAB
hj1odHRwOi8vMjIxLjIxNC41LjY2OjgwODgvU2hhbkRvbmdTTTJDQS9kb3dubG9h
ZC9TTTJDQWNlcnQuY2VyMFYGA1UdIARPME0wSwYKKwYBBAGBkkgBCjA9MDsGCCsG
AQUFBwIBFi9odHRwOi8vd3d3LnNkY2EuY29tLmNuL1VwbG9hZEZpbGVzL1NEQ0Et
Q1BTLnBkZjAOBgNVHQ8BAf8EBAMCBsAwKgYDVR0lAQH/BCAwHgYIKwYBBQUHAwgG
CCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOCAQEAV9G/knz+SnSU
1j7//CcVlsdWheRH1Og263oeEmbmiTNAgr/g33d25zqhcGWc+PKcrJnJApaovaZH
+cNpBMr43gSigzF+JAm1W2hdj6YH54HN8KYDB4V7StASjpeOwNDeNTAi1NGGaecZ
dV8Or+pCmQBoUEUwZm/labUEZONGSTDYZ2Ha2ZZjsuWbc/tLFTzkNhPXdmkzX9Bb
xJQpsn4mzlHHLOmVBn/xM1GvbtSYKg38NeEICQZGbfGzhzy3qC1WvTqnL7XQ4QDV
Dn6SMyxg8kJOvYt9rBYJqscuY/1REPW0OJT7C1cm7g+SvifrUeImaUFMjxflwVD4
1kL4YYBChA==
-----END CERTIFICATE-----
subject=/CN=60.208.56.186/OU=\xE5\xB1\xB1\xE4\xB8\x9C\xE5\x9B\xBD\xE7\x9B\xBE\xE7\xBD\x91\xE4\xBF\xA1\xE6\x81\xAF\xE7\xA7\x91\xE6\x8A\x80\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/O=\xE5\xB1\xB1\xE4\xB8\x9C\xE5\x9B\xBD\xE7\x9B\xBE\xE7\xBD\x91\xE4\xBF\xA1\xE6\x81\xAF\xE7\xA7\x91\xE6\x8A\x80\xE6\x9C\x89\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8/L=jinan/ST=SD/C=CN
issuer=/C=CN/ST=SHANDONG/L=JINAN/O=SDCA/OU=SDCA/CN=ShanDongRSACA
---
No client certificate CA names sent
---
SSL handshake has read 2382 bytes and written 522 bytes
Verification error: unable to get local issuer certificate
---
New, SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: 020400006A755DEB8C2C2E640530ACA9F7A87B5A35BB76A61632E4B5B7C033B9
    Session-ID-ctx: 
    Master-Key: 19E2C41D963F1793F0573727A68F247FBF1B43B1EE49B2ECB73B79A4A438A7CF2635C95B3ED1859BC646218252AF66CC
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1596131410
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
---
error in s_client
