### ISSUE TITLE
使用CURL链接GMSSL库，卡在sk_insert的realloc中。

### ISSUE THREAD

**Issue by josephusmv** [guanzhi/GmSSL#997]
**Describe the bug**
使用LibCURL链接GMSSL库，程序在curl的easy perform中卡住，暂停程序后堆栈如下：
<unknown> 0x00007fb97c2a4491
OPENSSL_sk_insert 0x00007fb97c2a4693
X509_STORE_add_lookup 0x00007fb97c2b7ce2
X509_STORE_load_locations 0x00007fb97c2b7286
ossl_connect_step1 0x000056401bad51ee
ossl_connect_common 0x000056401bad85cf
Curl_ssl_connect_nonblocking 0x000056401baa58fc
https_connecting 0x000056401baab7f6
Curl_http_connect 0x000056401baad153
multi_runsingle 0x000056401ba950dd
curl_multi_perform 0x000056401ba960c1
curl_easy_perform 0x000056401ba8fdab

分析汇编怀疑是因为Realloc导致，链接最新版的OpenSSL无此问题。
新版OpenSSL已经大幅修改了此函数，请查阅：
https://github.com/openssl/openssl/commit/41bff723c6784cc846054a4fd4add6dbec8c2c64
及：
https://github.com/openssl/openssl/commit/1b3e2bbf64b96f636277ca29b31ba152c1831e74#diff-13f175c8dd316f50c0d8ed604e1e415b

**Expected behavior**

**Screenshots**

**Environments**
- OS: Ubuntu20
- Compiler: gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Additional context**
CURL 7.67 ~ latest 均可复现此问题。

**Comment by Mr-LZG** [comment]
> **描述错误**
> 使用的libcurl链接GMSSL库，程序在卷曲的容易执行中卡住，暂停程序后堆栈如下：
> 0x00007fb97c2a4491
> OPENSSL_sk_insert 0x00007fb97c2a4693
> X509_STORE_add_lookup 0x00007fb97c2b7ce2
> X509_STORE_load_locations 0x00007fb97c2b7286
> ossl_connect_step1 0x000056401bad51ee
> ossl_connect_common 0x000056401bad85cf
> Curl_ssl_connect_nonblocking 0x000056401baa58fc
> https_connecting 0x000056401baab7f6
> Curl_http_connect 0x000056401baad153
> multi_runsingle 0x000056401ba950dd
> curl_multi_perform 0x000056401ba960c1
> curl_easy_perform 0x000056401ba8fdab
> 
> 分析汇编怀疑是因为Realloc导致，链接最新版本的OpenSSL无此问题。新版本
> OpenSSL已经明显修改了此函数，请查阅：
> [openssl / openssl @ 41bff72](https://github.com/openssl/openssl/commit/41bff723c6784cc846054a4fd4add6dbec8c2c64)
> 及：
> [openssl / openssl @ 1b3e2bb＃diff-13f175c8dd316f50c0d8ed604e1e415b](https://github.com/openssl/openssl/commit/1b3e2bbf64b96f636277ca29b31ba152c1831e74#diff-13f175c8dd316f50c0d8ed604e1e415b)
> 
> **预期行为**
> 
> **屏幕截图**
> 如果适用，请添加屏幕截图以帮助解释您的问题。
> 
> **环境环境**
> 
> * 操作系统：Ubuntu20
> * 编译器：gcc版本9.3.0（Ubuntu 9.3.0-10ubuntu2）
> 
> **附加上下文**
> CURL 7.67〜最新可能重复存在此问题。
你好，请问使用的curl也支持国密吗，有开源项目吗

**Comment by liuxl-lin** [comment]
> > **描述错误**
> > 使用的libcurl链接GMSSL库，程序在卷曲的容易执行中卡住，暂停程序后堆栈如下：
> > 0x00007fb97c2a4491
> > OPENSSL_sk_insert 0x00007fb97c2a4693
> > X509_STORE_add_lookup 0x00007fb97c2b7ce2
> > X509_STORE_load_locations 0x00007fb97c2b7286
> > ossl_connect_step1 0x000056401bad51ee
> > ossl_connect_common 0x000056401bad85cf
> > Curl_ssl_connect_nonblocking 0x000056401baa58fc
> > https_connecting 0x000056401baab7f6
> > Curl_http_connect 0x000056401baad153
> > multi_runsingle 0x000056401ba950dd
> > curl_multi_perform 0x000056401ba960c1
> > curl_easy_perform 0x000056401ba8fdab
> > 分析汇编怀疑是因为Realloc导致，链接最新版本的OpenSSL无此问题。新版本
> > OpenSSL已经明显修改了此函数，请查阅：
> > [openssl / openssl @ 41bff72](https://github.com/openssl/openssl/commit/41bff723c6784cc846054a4fd4add6dbec8c2c64)
> > 及：
> > [openssl / openssl @ 1b3e2bb＃diff-13f175c8dd316f50c0d8ed604e1e415b](https://github.com/openssl/openssl/commit/1b3e2bbf64b96f636277ca29b31ba152c1831e74#diff-13f175c8dd316f50c0d8ed604e1e415b)
> > **预期行为**
> > **屏幕截图**
> > 如果适用，请添加屏幕截图以帮助解释您的问题。
> > **环境环境**
> > 
> > * 操作系统：Ubuntu20
> > * 编译器：gcc版本9.3.0（Ubuntu 9.3.0-10ubuntu2）
> > 
> > **附加上下文**
> > CURL 7.67〜最新可能重复存在此问题。
> > 你好，请问使用的curl也支持国密吗，有开源项目吗

同问，有libcurl支持国密的开源项目吗
